### ISSUE TITLE
Last CocoaPods version is too old

### ISSUE THREAD

**Issue by alexfrankiv** [CosmicMind/Material#1001]
Hello

Could you please **update the version** of your framework **for CocoaPods**? Cause the **last available is 1.2.2** and it contains some pretty bad bugs with false triggering actions and so on.

P.S. Really nice job, guys! Wonderful framework.

**Comment by danieldahan** [comment]
Please give [Material 2.13.0](https://github.com/CosmicMind/Material/releases/tag/2.13.0) a try. If the issue persists, please reopen it. Thank you!
