### ISSUE TITLE
Cannot invoke initializer for type 'AppNavigationDrawerController' with an argument list of type '(rootViewController: AppToobarController, leftViewController: LeftViewController, rightViewController: RightViewController, tabsController: AppTabsController, toolbarController: AppToolbarController, menuController: AppFABMenuController)'

### ISSUE THREAD

**Issue by kjhatis** [CosmicMind/Material#1002]
Cannot invoke initializer for type 'AppNavigationDrawerController' with an argument list of type '(rootViewController: AppToobarController, leftViewController: LeftViewController, rightViewController: RightViewController, tabsController: AppTabsController, toolbarController: AppToolbarController, menuController: AppFABMenuController)'
![screen shot 2017-12-22 at 5 30 52 pm](https://user-images.githubusercontent.com/24405562/34297419-1207d26e-e73e-11e7-88e4-22b331537b43.png)
![screen shot 2017-12-22 at 5 30 44 pm](https://user-images.githubusercontent.com/24405562/34297420-123dc996-e73e-11e7-8485-df02a3acfa69.png)

` 
        window!.rootViewController = AppNavigationDrawerController(
            rootViewController: appToolbarController,
            leftViewController: leftViewController,
            rightViewController: rightViewController,
            tabsController: tabsController,
            toolbarController: toolbarController,
            menuController: menuController)
        
        window!.makeKeyAndVisible()`

How to Attach the menuController and TabsController with the rootViewController. 
I am trying to include the CardtableView into the NavigationDrawerController.

**Comment by danieldahan** [comment]
You would want to do something like this: 

```swift
window!.rootViewController = AppNavigationDrawerController(rootViewController: menuController, leftViewController: leftViewController, rightViewController: rightViewController)
```

You have already made the relationships in these lines: 

```swift
let tabsController = ...
let toolbarController = ...
let menuController = ...
```

If you need, please reopen this issue :)

**Comment by kjhatis** [comment]
**I want do something like this:** Please take a look once again
`
 window!.rootViewController = AppNavigationDrawerController(
            rootViewController: appToolbarController,
            leftViewController: leftViewController,
            rightViewController: rightViewController,
            tabsController: tabsController,
            toolbarController: toolbarController,
            menuController: menuController
            )
        
        window!.makeKeyAndVisible()
`

**Comment by kjhatis** [comment]
i am not able to combine any two controller, and if it is not possible with material have to look for any other framework.

**Comment by danieldahan** [comment]
@kjhatis I described how to do it above. The initializer you are using to setup the controller is invalid and does not exist. Please refer to my comment above or the [Samples](https://github.com/CosmicMind/Samples) repo. It is very easy to combine controllers. If you feel the need to use another framework, then please do so. 

All the best :)
