### ISSUE TITLE
How to add vertical space between cells?

### ISSUE THREAD

**Issue by wstudios** [CosmicMind/Material#1005]
This is a great library but I can't seem to find a way to add a vertical space between each cell. Any help would be greatly appreciated.

**Comment by chaitanya-ramji** [comment]
If you mean collectionViewCells, there are two functions namely
```swift
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
...
}


func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
 ...
 }
```

Use them to manage spacing between cells in your collectionView

**Comment by danieldahan** [comment]
@wstudios please share your setup code. If you are using the `CollectionView` object from `Material`, there should be an `interimSpace` and `interimSpacePreset` property. Let me know, thank you!
