### ISSUE TITLE
Unbalanced appearance transition breaks SFSafariViewController

### ISSUE THREAD

**Issue by 666tos** [CosmicMind/Material#1007]
iOS 11.2
SFSafariViewController gets broken and does not load content

Console output: Unbalanced calls to begin/end appearance transitions for <Material.NavigationController: 0x7f9328828200>.

Please see sample https://github.com/666tos/MaterialSafariBug

Also, this code in `Motion+UIViewController` is wrong
`get { return transitioningDelegate is Motion }`
since `transitioningDelegate` is set to `MotionTransition.shared` which is not subclass of `Motion`

**Comment by danieldahan** [comment]
Thank you! I updated motion with your find, [Motion 1.3.1](https://github.com/CosmicMind/Motion/releases/tag/1.3.1). [Material 2.13.1](https://github.com/CosmicMind/Material/releases/tag/2.13.1) has the update as well. I will take a look at the sample project now.

**Comment by danieldahan** [comment]
I will need to look further into this. The issue only seems to happen in your sample project.

**Comment by danieldahan** [comment]
The unbalanced calls should now be gone in [Motion 1.3.2](https://github.com/CosmicMind/Motion/releases/tag/1.3.2). [Material 2.13.2](https://github.com/CosmicMind/Material/releases/tag/2.13.2) :)

**Comment by danieldahan** [comment]
Please find a correct fix for this in [Material 2.13.3](https://github.com/CosmicMind/Material/releases/tag/2.13.3) and [Motion 1.3.3](https://github.com/CosmicMind/Motion/releases/tag/1.3.3).
