### ISSUE TITLE
How to prevent FABMenu from closing unless a button is clicked?

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#1009]
I couldn't find a way to keep the FABMenu open, everytime I tap on anywhere on the screen it just closes.

**Comment by danieldahan** [comment]
Can you try setting the `FABMenu.isEnabled` property to false when you do not want it to close? I may need to make some adjustments to make this easier. So please let me know how that works for you.

**Comment by danieldahan** [comment]
Hey, I haven't heard from you. If you still have this issue, please reopen it. Thank you!
