### ISSUE TITLE
Feature request for Date picker

### ISSUE THREAD

**Issue by nitishrana28** [CosmicMind/Material#1010]
Hi there,
This is a feature request. Since There should be a provision of custom date picker like this : 
https://github.com/wdullaer/MaterialDateTimePicker  
  
![screen shot 2018-01-04 at 12 51 53 am](https://user-images.githubusercontent.com/1484780/34535911-882bd7d8-f0e9-11e7-9e73-6c694ad0b332.png)
  
Looking forward !!

Regards,
Nitish

**Comment by danieldahan** [comment]
Hey, this has been requested and is in progress for Material 3. Please follow this issue https://github.com/CosmicMind/Material/issues/560. Thank you!

**Comment by nitishrana28** [comment]
Great. Thanks
