### ISSUE TITLE
Why is Motion folder not getting downloaded after installing  pod 'Material', '~> 2.0'?? 

### ISSUE THREAD

**Issue by Maddy10** [CosmicMind/Material#1011]

**Comment by Maddy10** [comment]
![screen shot 2018-01-04 at 2 04 09 pm](https://user-images.githubusercontent.com/25656422/34555170-793f169e-f158-11e7-8af9-77de7820a5cb.png)

**Comment by danieldahan** [comment]
Did you figure this out?

**Comment by Maddy10** [comment]
Yes.
