### ISSUE TITLE
Can we set visibility icon custom for password textfield to enable and disable the action??

### ISSUE THREAD

**Issue by swift1022** [CosmicMind/Material#1012]

**Comment by danieldahan** [comment]
You can set if it is enabled by using the `TextField.isVisibilityIconButtonEnabled` property. As for changing the image, I will need to make that a feature request. I can include this behavior in Material 3. I will leave this up as a reminder. Thank you!

**Comment by danieldahan** [comment]
There are two new properties in [Material 2.16.0](https://github.com/CosmicMind/Material/releases/tag/2.16.0). 

```swift
visibilityIconOn
visibilityIconOff
```

Each allow an image to be set for the visibility icon. If you need any further help, please reopen, or create a new issue. Thank you!
