### ISSUE TITLE
Version 2.13.2 viewWillAppear(_ animated: Bool) not work

### ISSUE THREAD

**Issue by tanakorn-dev** [CosmicMind/Material#1015]
When I updated this pod to version 2.13.2 this function not work
`
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
}
`

**Comment by danieldahan** [comment]
Yes, I am going to fix this today. Please follow this issue https://github.com/CosmicMind/Motion/issues/24. Thank you! Sorry for the inconvenience.

**Comment by danieldahan** [comment]
Please find a correct fix for this in [Material 2.13.3](https://github.com/CosmicMind/Material/releases/tag/2.13.3) and [Motion 1.3.3](https://github.com/CosmicMind/Motion/releases/tag/1.3.3).
