### ISSUE TITLE
wrong instance returned by fabMenuController

### ISSUE THREAD

**Issue by ijameelkhan** [CosmicMind/Material#1016]
In my app I have two FAB controllers both are used in total different vertical. But when I try to access fabMenuController it returns wrong instance from different vertical. 

Issue comes from how the traversing work. I think it should start from current ViewController and try to find upward. From the code execution that I see  it jumps to app delegate root controller and then start to traverse down. Which returns the first instance it find for FabMenuController not the FabMenuController for the vertical I am sitting in ?

**Comment by danieldahan** [comment]
It actually goes up and then goes down. I think the issue is that it is only looking for `TransitionController` types. You can see this in the line below: 

```swift
v = v?.parent as? TransitionController
```

If I push a change to `development`, would you be able to try it? Or can you send me a sample project I can try?

Thank you!

**Comment by ijameelkhan** [comment]
yes I can try. Push to dev and I will let you know. 
Project it self has grown too much to be shared.

**Comment by danieldahan** [comment]
Okay, give this commit a try: cf88010a46778f7fb98a29ebb6d63632cfc75f2b

**Comment by danieldahan** [comment]
Basically it was skipping over one of your contained view controllers and making it nil, forcing it to search top down. This was happening because it was only looking for `TransitionController` types, and your would have been a UIViewController with potentially a different subclass. I will make a release now for this :)

**Comment by danieldahan** [comment]
Here is a release for the update: [Material 2.13.4](https://github.com/CosmicMind/Material/releases/tag/2.13.4). Thank you for sharing :)

**Comment by ijameelkhan** [comment]
thank you! Good job
