### ISSUE TITLE
Issues pushing BottomNavigationController on a NavigationController

### ISSUE THREAD

**Issue by multinerd** [CosmicMind/Material#1018]
https://i.stack.imgur.com/z8vfE.gif

Pushing BottomNavigationController on a NavigationController causes the backbutton to indent as seen in the image above.  (my global tint of `white` also gets reseted)

When replacing `BottomNavigationController` -> `UITabBarController` and `NavigationController` -> `UINavigationController`, the back arrow acts as intended (does NOT indent), which leads me to believe that the issue lies with the subclasses themselves.

**Comment by danieldahan** [comment]
Can you share: 

Material version, 
iOS version, 
Device

that you are using? Thank you!

**Comment by multinerd** [comment]
- Material/Core (2.13.2):
    - Motion (~> 1.3.0)

iOS: 11.1.2
Device: 7+

**Comment by danieldahan** [comment]
I will investigate this. Thank you for sharing. If you do not hear from me by Friday, please follow up.

**Comment by multinerd** [comment]
I've attempted to reproduce the bug in a simple application [found here](https://github.com/multinerd/materialbug) and noticed something interesting.

Using `NavigationController` as root makes the first back arrow indented (not sure why my code works right until i push to a tabbar, i will look into this as well)

**Comment by danieldahan** [comment]
Perfect! That is very helpful :) Thank you!

**Comment by multinerd** [comment]
were you able to figure out a solution to this?

**Comment by multinerd** [comment]
i was browsing the other issues and realize this issue is the same as #650

**Comment by danieldahan** [comment]
@adamdahan Can you follow up on this please :) Thank you!

**Comment by multinerd** [comment]
any updates?

**Comment by danieldahan** [comment]
Sorry for the delay. I have been working on another task. I will make an effort to look this through within the next couple days. Thank you!

**Comment by OrkhanAlikhanov** [comment]
![](https://user-images.githubusercontent.com/15037839/43223428-1b0be344-9064-11e8-813b-b6d1adfd5b55.gif)

@multinerd This is what is happening in the sample project you've attached. The plus button on the right is a `UIBarButtonItem` (and is misaligned). We don't support using `UIBarButtonItem`s with the Material's `NavigationController`. You should be using an `IconButton` on the `navigationItem.rightView`. You can check out [NavigationController sample](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationController) for usage. Thank you!

**Note:** As a recommendation of mine to you, use programmatic approach for complex projects, storyboards are time consuming and hard to maintain.

**Comment by multinerd** [comment]
> Note: As a recommendation of mine to you, use programmatic approach for complex projects, storyboards are time consuming and hard to maintain. 

The more i learn about developing mobile apps, the more i agree with that statement. Thanks for explaining what was going on.
