### ISSUE TITLE
Cursor wrong position when toggle visibility on password field

### ISSUE THREAD

**Issue by fabianbraach** [CosmicMind/Material#1023]
We use a `TextField` for the password input on our login screen, but when you enter a password and toggle the visibility, the cursor doesn't get updated with the new length of the text input since the clear password may be longer or shorter than the bullet points.

![screen shot 2018-01-18 at 16 18 47](https://user-images.githubusercontent.com/5269541/35105219-577c7ee8-fc6b-11e7-9c30-702330cf3417.png)

**Comment by danieldahan** [comment]
Hmmm.... are you using another language? What version of Material are you using, device, and may you send over a reproducible project?

Thank you!

**Comment by danieldahan** [comment]
Hi, we have not heard from you. Please reopen the issue if this persist. Thank you!

**Comment by garrialmighty** [comment]
I can still experience this.
Can be easily replicated by creating a new project and adding the library via CocoaPods

[TextFieldTest.zip](https://github.com/CosmicMind/Material/files/1702571/TextFieldTest.zip)
