### ISSUE TITLE
Set viewControllers in TabsController

### ISSUE THREAD

**Issue by Recouse** [CosmicMind/Material#1024]
I want to set `viewControllers` in `TabsController`, not when initializing it. So, when I do it in `prepare` method, it runs 2 times.
How can I do this? I tried different ways but failed.

**Comment by Recouse** [comment]
Found a solution with convenience init:
```swift
convenience init(someParam: String) {
    let firstVC = FirstViewController()
    let secondVC = SecondViewController()
        
    self.init(viewControllers: [firstVC, secondVC])
        
    self.someParam = someParam
}
```

**Comment by danieldahan** [comment]
Excellent :) All the best!
