### ISSUE TITLE
IBInspectible

### ISSUE THREAD

**Issue by jeffmiralles** [CosmicMind/Material#1027]
UIView for example, layer attributes not present in Attribute inspector, like offset color etc

**Comment by adamdahan** [comment]
@jeffmiralles Are you referring to the default values?

**Comment by DisignirJefferson** [comment]
In the current version of Material, in Material+UIView.swift a lot of IBInspectable properties was gone, where in older versions it has them.

**Comment by DisignirJefferson** [comment]
[materialCurrentVersion.txt](https://github.com/CosmicMind/Material/files/1680170/materialCurrentVersion.txt)
[materialOldVersion.txt](https://github.com/CosmicMind/Material/files/1680173/materialOldVersion.txt)

**Comment by danieldahan** [comment]
The properties were removed to avoid conflicts with other frameworks. If you want them back, create a local extension and copy and paste the code :) 

All the best and if you have any further issues, please reopen it.

**Comment by DisignirJefferson** [comment]
yep, that's what i did. thank you for the information.
