### ISSUE TITLE
statusbar color - navigationdrawer (left menu open)

### ISSUE THREAD

**Issue by volkangurol** [CosmicMind/Material#1029]
When i open left menu statusbar color is not apply on left menu. How can i set it?

<img width="161" alt="screen shot 2018-02-01 at 01 17 06" src="https://user-images.githubusercontent.com/2510054/35650608-bfb86954-06ed-11e8-9160-ccac3418fd39.png">
<img width="286" alt="screen shot 2018-02-01 at 01 17 16" src="https://user-images.githubusercontent.com/2510054/35650609-c0849ace-06ed-11e8-8e9d-4d7405d9b383.png">

my hierarchy is,
tabsController
toolbarController
navigationDrawerController
fabMenuController

**Comment by danieldahan** [comment]
You can access the helper `statusBarController? optional property available in all UIViewControllers: 

```swift
statusBarController?.statusBar.backgroundColor = Color.blue.base
```

If you need any further help, please reopen this issue :)
