### ISSUE TITLE
Cursor wrong position when toggling isSecureTextEntry via visibilityIconButton

### ISSUE THREAD

**Issue by garrialmighty** [CosmicMind/Material#1030]
Related to #1023 
Can be easily replicated by creating a new project and adding the library via CocoaPods

[TextFieldTest.zip](https://github.com/CosmicMind/Material/files/1702586/TextFieldTest.zip)

**Comment by danieldahan** [comment]
I will give this a try :) Thank you!

**Comment by garrialmighty** [comment]
Thank you sir.

I'll also try to dig through the source code on my end as our QA team insists it's really a bug. 😄

**Comment by danieldahan** [comment]
@garrialmighty It does look like a bug. Okay, I will work on this tomorrow and push a fix. Thank you!

**Comment by garrialmighty** [comment]
Thank you @danieldahan!

I'll continue my digging maybe I'll find something that will help you or make the fix easier.

**Comment by garrialmighty** [comment]
Just found out that this is also the default behaviour/bug for the native UITextField

**Comment by garrialmighty** [comment]
[PR] (https://github.com/CosmicMind/Material/pull/1031) created.

Kindly review. :)

**Comment by fabianbraach** [comment]
Thank you from my side, as we have the same issue but didn't had the time to create a new demo project at work as it was not so important to us. 🙂👍

**Comment by danieldahan** [comment]
You will find a fix in [Material 2.13.6](https://github.com/CosmicMind/Material/releases/tag/2.13.6) for this issue. Thank you!
