### ISSUE TITLE
Tabar items don't highlight when viewController is a NavigationController

### ISSUE THREAD

**Issue by wess** [CosmicMind/Material#1034]
When putting NavigationController instances in the viewControllers array of a TabController, the icons in the tabbar stop highlighting

**Comment by danieldahan** [comment]
I will take a look, thank you.

**Comment by danieldahan** [comment]
The issue is that the `NavigationController` is a wrapper around a view controller. The preparation method needs to be moved to the NavigationController, and called in the viewDidLoad phase. Something like this:

```swift
class AppNavigationController: NavigationController {
  open override func prepare() {
    super.prepare()
    prepareTabItem()
  }
}

extension AppNavigationController {
  func prepareTabItem() {
    tabItem.title = "Blue"
    tabItem.setTabItemImage(Icon.add, for: .normal)
    tabItem.setTabItemImage(Icon.pen, for: .selected)
    tabItem.setTabItemImage(Icon.photoLibrary, for: .highlighted)
  }
}
```

If you need any further help, please reopen or create a new issue. Thank you!
