### ISSUE TITLE
TabsController animation cancel

### ISSUE THREAD

**Issue by nCr78** [CosmicMind/Material#1036]
Is there a way to cancel the animation when tapping to another tab while that animation is happening? If not, is there a way to change the animation's duration? The UI feels laggy when a user wants to switch tabs faster than the animation's duration.

**Comment by danieldahan** [comment]
I will take a look, thank you!

**Comment by danieldahan** [comment]
This will be added as a feature request. Thank you!

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
