### ISSUE TITLE
MaterialTextField crashes when used with storyboard

### ISSUE THREAD

**Issue by moger777** [CosmicMind/Material#1039]
I can't seem to embed a MaterialTextField in a storyboard since the init by NSCoder is not implemented:

```swift
  required init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
```

**Comment by danieldahan** [comment]
What version of Material are you using. There isn't a `MaterialTextField`, only 1TextField`.

**Comment by moger777** [comment]
Shit, this class is not part of this lib, sorry.

**Comment by danieldahan** [comment]
No worries.
