### ISSUE TITLE
a issue about the Button click pulse animation!

### ISSUE THREAD

**Issue by lhalcyon** [CosmicMind/Material#1040]
There is a problem about button pulse animation and button click event!
the button click sequence in Android
1.button clicked; 2. ripple wave(pulse animation) shows 3.when animation finish,click event responding.
while the button click sequence in Material lib
1.button clicked; 2.ripple wave shows and click event responding.
as a result ,we almost can'see  the pulse before a new view controller pushed.

**Comment by danieldahan** [comment]
I will take a look into this, do you have a sample project that demonstrates the issue you re facing? Thank you!

**Comment by intoxicated** [comment]
@danieldahan i'll follow up the issue and will push PR soon

**Comment by intoxicated** [comment]
I didn't look at the code yet but most likely a solution would be do push view in animation completion block

**Comment by danieldahan** [comment]
I am closing this issue, if you send a sample project or code block that demonstrates the issue, please reopen this. Thank you!
