### ISSUE TITLE
TabsController - Update titles of tabs looks wrong

### ISSUE THREAD

**Issue by fabianbraach** [CosmicMind/Material#1044]
When updating the title of the tabs in a `TabsController`, it looks weird as seen on the screenshot below. We also created an example project for you to check it out. 
Calling `tabBar.setNeedsLayout()` directly after the title change, it works on iPhone SE, but not on iPhone 8.

![simulator screen shot - iphone 8 - 2018-03-02 at 09 26 44](https://user-images.githubusercontent.com/5269541/36890220-680adc7e-1dfd-11e8-88f1-b13db5e2035d.png)

[MaterialTabBarTitleTest.zip](https://github.com/CosmicMind/Material/files/1774267/MaterialTabBarTitleTest.zip)

**Comment by danieldahan** [comment]
That is because the tabs are being shrunk down. Have you tried the tabs with the scrolling option which should avoid such an issue?

**Comment by fabianbraach** [comment]
We also enabled scrolling behaviour by default, instead of automatic, but then the tab bar is not the full width, if the tab titles are not long enough..

**Comment by danieldahan** [comment]
I'll take a look at your sample project. Thank you!

**Comment by danieldahan** [comment]
Give this a try, [Material 2.13.7](https://github.com/CosmicMind/Material/releases/tag/2.13.7). I updated your code as follows: 

***swift
import UIKit
import Material
import Motion

class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let viewControllers = [
            makeViewController(backgroundColor: .red),
            makeViewController(backgroundColor: .green),
            makeViewController(backgroundColor: .blue),
            makeViewController(backgroundColor: .yellow)
        ]
        
        let tabsController = TabsController(viewControllers: viewControllers)
        tabsController.tabBarAlignment = .top
        tabsController.tabBar.dividerAlignment = .bottom
        tabsController.tabBar.lineHeight = 2
        tabsController.tabBar.heightPreset = .small
        
        addChildViewController(tabsController)
        view.addSubview(tabsController.view)
        view.layout(tabsController.view).edges(top: 50, left: 0, bottom: 0, right: 0)
        
        Motion.delay(3) {
            viewControllers.first?.tabItem.title = "abcdef (10) really long"
            tabsController.tabBar.setNeedsLayout()
            tabsController.tabBar.layoutIfNeeded()
        }
    }
    
    func makeViewController(backgroundColor: UIColor) -> UIViewController {
        let vc = UIViewController()
        vc.view.backgroundColor = backgroundColor
        vc.tabItem.title = "abcdef"
        
        return vc
    }
}
***

I made your text longer and used Motion to set a time delay. 

Thank you for sharing this issue and if you have any further trouble, please reopen this issue or create a new one.

**Comment by fabianbraach** [comment]
Thank you, we will try it out today!

**Comment by fabianbraach** [comment]
We tried it out, with your example, `abcdef (10) really long` as title, it works as expected. But with our shorter title, `abcdef (10)`, it still doesn't work. We think it is a problem with the `tabItemsTotalWidth` calculation in `TabBar.swift` line 359, because it calculated 352 as totalWidth, but scrollView width is 375 (on iPhone 8) and the first item title is truncated in the middle.

**Comment by danieldahan** [comment]
Hmmm... I will try your sample again.

**Comment by danieldahan** [comment]
I am not sure exactly why, but the issue is your `()` characters.

**Comment by danieldahan** [comment]
Weird... this is something in the String system I would think. Very interesting.
