### ISSUE TITLE
Transparent toolbar

### ISSUE THREAD

**Issue by mjurenka** [CosmicMind/Material#1045]
Hello,

first of all, this is great lib, makes material development so much easier.
I'm using ToolbarController inside NavigationDrawer and I'm trying to make the entire toolbar transparent so I can see the image stretched underneath, but I cannot get the toolbar to become fully transparent. Either it will have white background or when I change bg color of view of the ToolbarController to clear (and opaque=false) I get black color.
When I debug the UI, toolbar shows as transparent and everything looks pretty, but in simulator (or device) it has either white or black background.

I have no idea how to fix it and i was changing almost everything, either in my code or in your lib.

Thanks

**Comment by danieldahan** [comment]
Have you tried: 

```swift 
toolbar.backgroundColor = .clear
``` 

You can access the toolbar from any view controller by using the optional helper: 

```swift
toolbarController?.toolbar.backgroundColor = .clear
```

Give that a try, and if you need, please reopen this issue and I will continue to help. Thank you!
