### ISSUE TITLE
isShadowPathAutosizing is doing the opposite

### ISSUE THREAD

**Issue by Tylerian** [CosmicMind/Material#1048]
So I was navigating trough CALayer's extension code and I saw that piece of code:

[Material+CALayer.swift#L279](https://github.com/CosmicMind/Material/blob/6cb791998af3962c1a0c2dc18f16f09f6227942b/Sources/iOS/Material%2BCALayer.swift#L279)
```
open func layoutShadowPath() {
    guard isShadowPathAutoSizing else {
        return
    }
    if .none == depthPreset {
      shadowPath = nil
    } else if nil == shadowPath {
      shadowPath = UIBezierPath(roundedRect: bounds, cornerRadius: cornerRadius).cgPath
    } else {
      animate(.shadow(path: UIBezierPath(roundedRect: bounds, cornerRadius: cornerRadius).cgPath))
    }
}
```

Isn't _isShadowPathAutosizing_ used to delegate the shadows drawing to UIKit?
If yes, then the guard is preventing it to happen.

**Comment by danieldahan** [comment]
What it is saying is to leave the shadow handling to the framework... otherwise it is completely managed by the developer. What are you trying to do?

**Comment by danieldahan** [comment]
Hey! I haven't heard from you, so if you need, please reopen or create a new issue. Thank you!
