### ISSUE TITLE
TextView does not have shadow or raised effect

### ISSUE THREAD

**Issue by robmontesinos** [CosmicMind/Material#1049]
Hi there, 
I'm trying to implement a TextView beneath a TextField and they don't match in look.

I inserted the border for testing only - can you help me out with what I am doing wrong? 

Thank you

<img width="364" alt="screen shot 2018-03-15 at 9 23 02 pm" src="https://user-images.githubusercontent.com/258556/37503736-4b3aac1a-2897-11e8-9c10-761711128e9a.png">

`

    fileprivate func createMessageTextView() -> TextView {
        let textView = TextView(frame: .zero)
        textView.backgroundColor = .white
        textView.placeholder = "Tweet Body"
        textView.font = UIFont.init(name: Theme.Fonts.fontBold.rawValue, size: 16)
        
        textView.cornerRadiusPreset = .cornerRadius2
        textView.depthPreset = .depth3

        textView.layer.borderColor = UIColor.black.cgColor
        textView.layer.borderWidth = 1.0
        textView.layer.cornerRadius = 4.0
        
        textView.layer.shadowOpacity = 0.3
        textView.layer.shadowOffset = CGSize(width: 0.0, height: 2.0)
        textView.layer.shadowRadius = 2.0
        textView.layer.shadowColor = UIColor.textColorDarkPrimary.cgColor
        
        textView.delegate = self
        
        return textView
    }
`

**Comment by danieldahan** [comment]
Try setting the `depth` or `depthPreset` property off the TextView. 

```swift
textView.depthPreset = .depth3
```

As an example. Let me know if this helps, as well, let's move this conversation to https://gitter.im/CosmicMind/Material. Thank you!

**Comment by robmontesinos** [comment]
Thank you @danieldahan but it is still not working. The above code has


```
textView.depthPreset = .depth3


```


I also tried

`textView.depth = Depth(preset: .depth3)`


Still not working.

**Comment by danieldahan** [comment]
Okay, go to the Gitter channel and we can discuss more.

**Comment by robmontesinos** [comment]
Thank you @danieldahan

**Comment by robmontesinos** [comment]
So @danieldahan helped me out on https://gitter.im/CosmicMind/Material really quickly.

Daniel Dahan @danieldahan 11:11

> So I tried a few things, the best solution right now is to wrap the TextView with another view and apply the depth to the wrapper view.

A little setup: I subclassed a UIView to be used as contentView for Material Card and then used a UIView extension for constraints: methods "anchor" and "fillSuperview" - 
The following worked:

```
import UIKit
import Material

class TBTweetContainerView: UIView {
    var clipboardButton: IconButton
    var linkTextField: TextField
    var messageTextView: TextView
    var messageContainerView: UIView!

    // MARK: - Init
    init(frame: CGRect, clipBoardButton: IconButton, linkTextField: TextField, messageTextView: TextView) {
        self.clipboardButton = clipBoardButton
        self.linkTextField = linkTextField
        self.messageTextView = messageTextView
        
        super.init(frame: frame)
        
        buildUI()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: - Setup
    fileprivate func buildUI() {
        // wrap textView in containerView and add depth to containerView
        messageContainerView = UIView(frame: .zero)
        messageContainerView.addSubview(messageTextView)
        
        messageTextView.fillSuperview()
        messageContainerView.depthPreset = depthPresetLarge
        messageContainerView.cornerRadiusPreset = cornerRadiusPresetLarge
        
        addSubviews([clipboardButton, linkTextField, messageContainerView])
        
        let clipboardDimension: CGFloat = 30.0
        let linkY: CGFloat = 25.0
        
        clipboardButton.anchor(topAnchor, left: nil,
                               bottom: nil, right: rightAnchor,
                               topConstant: linkY, leftConstant: 0,
                               bottomConstant: 0, rightConstant: 0,
                               widthConstant: clipboardDimension, heightConstant: clipboardDimension)
        
        linkTextField.anchor(topAnchor, left: leftAnchor,
                             bottom: nil, right: clipboardButton.safeLeftAnchor,
                             topConstant: linkY, leftConstant: 0,
                             bottomConstant: 0, rightConstant: tbLabelPadding - 2,
                             widthConstant: 0, heightConstant: 42)
        
        messageContainerView.anchor(linkTextField.bottomAnchor, left: leftAnchor,
                                    bottom: nil, right: rightAnchor,
                                    topConstant: tbVertPadding, leftConstant: tbLabelPadding - 2,
                                    bottomConstant: 0, rightConstant: tbLabelPadding - 2,
                                    widthConstant: 0, heightConstant: 120)
    }
}
<img width="378" alt="screen shot 2018-03-16 at 12 14 33 pm" src="https://user-images.githubusercontent.com/258556/37540343-cff42db0-2913-11e8-822f-5e04061f50d0.png">

```
