### ISSUE TITLE
Pageview inside TabsController 

### ISSUE THREAD

**Issue by edwinps** [CosmicMind/Material#1051]
I have a UIpageview inside of one tab of TabsController, but the pageview take al the control of the swipe gesture, and there are no way to get out from the pageview withe swipe. In the component before of tabscontroller I didn't have that problem, the example is like this:
![screenshot](https://user-images.githubusercontent.com/1847837/37724452-1d8dba48-2d31-11e8-994e-ac95b61ee16d.png)
The idea is in the moment that I am in the first item of the pageview , I can't swipe to the right item of the tabscontroller

**Comment by danieldahan** [comment]
I understand the issue. How would you like the swipe to work for your project?

**Comment by edwinps** [comment]
I would need to swipe to the tab on the left on in this case the first tab

**Comment by danieldahan** [comment]
You can enable and disable it. You can enable it when it is not on the first tab with `isSwipeEnabled` and disable it when on the first tab.

**Comment by danieldahan** [comment]
If you need any further help, let's chat on [Material Gitter](http://gitter.im/CosmicMind/Material).
