### ISSUE TITLE
Delegation methods never fired on Tab swipe

### ISSUE THREAD

**Issue by angelix** [CosmicMind/Material#1056]
If you are using tab swipe (#1019) and tab delegate, when a user swipes to a new tab, delegate methods are never fired.

**Comment by thomascsorbamedia** [comment]
Hi, any update on this?

**Comment by danieldahan** [comment]
Hey! I will push a release by tonight for this. Thank you!

**Comment by danieldahan** [comment]
Hey! I have a bit more to do with the release, so tomorrow during the day I will push it. Thank you!

**Comment by autumnssun** [comment]
@angelix I ran into the same problem.
Here is a quick fix. 
https://github.com/autumnssun/Material/commit/955cec565892d7b3b14c7dc84cfccf3b31c4ca1a

**Comment by danieldahan** [comment]
I am reviewing this now and confirming a releasable fix. Sorry for the delays. Thank you!

**Comment by OrkhanAlikhanov** [comment]
#1086 is merged in, so next release gonna have a fix, thank you for finding this!

**Comment by danieldahan** [comment]
Please find the fix in [Material 2.16.0](https://github.com/CosmicMind/Material/releases/tag/2.16.0). Thank you!
