### ISSUE TITLE
TabBar set image for specific states (normal/selected etc)

### ISSUE THREAD

**Issue by nCr78** [CosmicMind/Material#1057]
Correct me if I'm wrong but the only way to set an image per tab is by adding it to the TabItem's image variable which has a didSet observer to set the image for all possible UIControl states..
I tried setting different images (fill/no fill) per corresponding UIControl state and it's being overridden somehow. Is it possible to change this behaviour? If not, could this functionality be added in a future release maybe?

Thank you :)

**Comment by danieldahan** [comment]
Hey! I am working on a release for Sunday with the latest that has been in development. I'll make sure that the functionality you are looking for exists in that release. Update you shortly.

**Comment by danieldahan** [comment]
@nCr78 I am updating Xcode and doing a final test. Material 2.15 will be released today with your feature request. Thank you.

**Comment by danieldahan** [comment]
Hey! Give [Material 2.15.0](https://github.com/CosmicMind/Material/releases/tag/2.15.0), and try: 

```swift
tabItem.setTabItemImage(Icon.add, for: .normal)
tabItem.setTabItemImage(Icon.pen, for: .selected)
tabItem.setTabItemImage(Icon.photoLibrary, for: .highlighted)
```

All the best!
