### ISSUE TITLE
how to add content tabBar inside

### ISSUE THREAD

**Issue by gowthamand** [CosmicMind/Material#1058]
Please help me how add content with tab give a sample

**Comment by gowthamand** [comment]
`func makeViewController(backgroundColor: UIColor) -> UIViewController {
        let vc = UIViewController()
        vc.view.backgroundColor = backgroundColor
        vc.tabItem.title = "abcdef"

        return vc
    }`

**Comment by gowthamand** [comment]
`func makeViewController(backgroundColor: UIColor) -> UIViewController {
        let vc = UIViewController()
        vc.view.backgroundColor = backgroundColor
        vc.tabItem.title = "abcdef"

        return vc
    }`

**Comment by danieldahan** [comment]
Hey! Take a look at these two samples [TabsController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabsController) and [TabBar](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabBar). If you still have any questions, please use [Material Gitter](https://gitter.im/CosmicMind/Material) and I will help you out.
