### ISSUE TITLE
 cell.detailTextLabel?.text = "\(detArray[indexPath.row])" Not Working

### ISSUE THREAD

**Issue by gowthamand** [CosmicMind/Material#1059]
@`
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

        let cell = tableView.dequeueReusableCell(withIdentifier: "MyCell", for: indexPath as IndexPath)
        cell.textLabel?.text = "\(myArray[indexPath.row])"
        let image : UIImage = UIImage(named: "\(imgArray[indexPath.row])")!
        cell.imageView?.image = image
        cell.detailTextLabel?.text = "\(detArray[indexPath.row])"
        cell.dividerColor = Color.grey.lighten2
        return cell
    }
`

**Comment by gowthamand** [comment]
`cell.detailTextLabel?.text = "\(detArray[indexPath.row])"
`

and Check Your search sample app

**Comment by danieldahan** [comment]
Let's move this to [Material Gitter](https://gitter.im/CosmicMind/Material). Thank you!
