### ISSUE TITLE
How to achieve like this please help me

### ISSUE THREAD

**Issue by gowthamand** [CosmicMind/Material#1064]
[https://i.stack.imgur.com/lSWXt.jpg](https://i.stack.imgur.com/lSWXt.jpg)

<img src="https://i.stack.imgur.com/lSWXt.jpg]" alt="sample" />

`import UIKit
import Material
import Graph
import Motion
import SwiftyJSON
import Alamofire

class HealthPackagesViewController: UIViewController {
    
    fileprivate var buttons = [TabItem]()
    fileprivate var tabBar: TabBar!

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        prepareNavigationItem()
        prepareButtons()
        prepareTabBar()
    }
    
}
extension HealthPackagesViewController {
    
    func prepareNavigationItem() {
        navigationItem.titleLabel.text = "Health Packages"
    }
    
    fileprivate func prepareButtons() {
        let btn1 = TabItem(title: "Library", titleColor: Color.blueGrey.base)
        btn1.pulseAnimation = .none
        buttons.append(btn1)
        
        let btn2 = TabItem(title: "Photo", titleColor: Color.blueGrey.base)
        btn2.pulseAnimation = .none
        buttons.append(btn2)
        
        let btn3 = TabItem(title: "Video", titleColor: Color.blueGrey.base)
        btn3.pulseAnimation = .none
        buttons.append(btn3)
    }
    
    fileprivate func prepareTabBar() {
        tabBar = TabBar()
        tabBar.delegate = self
        tabBar.dividerColor = Color.grey.lighten2
        tabBar.dividerAlignment = .bottom
        
        tabBar.lineColor = Color.blue.base
        tabBar.lineAlignment = .bottom
        
        tabBar.backgroundColor = Color.grey.lighten5
        tabBar.tabItems = buttons
        
        view.layout(tabBar).horizontally().top()
    }
}

extension HealthPackagesViewController: TabBarDelegate {

    @objc func tabBar(tabBar: TabBar, willSelect tabItem: TabItem) {
        print("willSelect")
    }
    
    @objc func tabBar(tabBar: TabBar, didSelect tabItem: TabItem) {
        print("did select")
    }

}`

**Comment by danieldahan** [comment]
Please send this question to [Material Gitter](https://gitter.im/CosmicMind/Material). Thank you!
