### ISSUE TITLE
TabBarItem Not Show

### ISSUE THREAD

**Issue by tanakorn-dev** [CosmicMind/Material#1066]
Hi, I am code from your sample project but I have problem.
<img width="412" alt="screen shot 2018-05-04 at 09 22 50" src="https://user-images.githubusercontent.com/27723511/39610796-fcc1e3ac-4f7c-11e8-8184-d1b2c88b3e50.png">
<img width="603" alt="screen shot 2018-05-04 at 09 23 07" src="https://user-images.githubusercontent.com/27723511/39610797-fd120940-4f7c-11e8-89c8-404851b4ccc9.png">

Please help me.

**Comment by danieldahan** [comment]
Hey! May I see your AppDelegate that sets up the TabsController?

**Comment by tanakorn-dev** [comment]
@danieldahan This is my AppDelegate.

<img width="537" alt="screen shot 2018-05-04 at 23 08 08" src="https://user-images.githubusercontent.com/27723511/39638428-5950f5e0-4ff0-11e8-9ec8-bb759bd1874f.png">
<img width="811" alt="screen shot 2018-05-04 at 23 08 57" src="https://user-images.githubusercontent.com/27723511/39638429-598cf9a0-4ff0-11e8-9a99-0a76084c9d75.png">

**Comment by danieldahan** [comment]
Okay, so the first view in the hierarchy that will be looked for using the TabsController is actually the `UINavigationController`. The line: 

```swift
let homeNavi = ...
``` 

So put the `TabItem` code in there, by subclassing the `UINavigationController`. 

That's it. In the future, I will make a feature that sniffs lower in the hierarchy, but for now, it uses only the first controller it detects. 

If you have any further issues, please reopen this issue. Thank you!
