### ISSUE TITLE
What should i write to install podfile in swift 4?

### ISSUE THREAD

**Issue by goribchat** [CosmicMind/Material#1068]
i am writing pod 'Material', '~> 2.4.0' in the podfile , but it is showing error. someone please tell me what to write to install podfile

**Comment by danieldahan** [comment]
You should update to [Material 2.15.0](https://github.com/CosmicMind/Material/releases/tag/2.15.0). Let me know if you have any further issues. Thank you!

**Comment by goribchat** [comment]
okay sir. Thanks you.. i am checking with the updated one, and informing you.

**Comment by goribchat** [comment]
Not get enough information from this link "Material 2.15.0",that's why I am importing the "ErrorTextField.swift","TextField.swift","TextStorage.swift","TextView.swift" into my project and change the class of UITextfield to TextField, but when i am running my project it is showing Command failed due to signal: Segmentation fault: 11. can you please help me regarding this matter. i am very willing to use material in my project as i have already used this feature in one of my previous project in swift 3. Please help.

**Comment by danieldahan** [comment]
I believe in your Pod settings, the project that is in Xcode, you would need to set it there. Give that a try. Let me know, we can solve this today.

**Comment by goribchat** [comment]
Okay sir i am trying
