### ISSUE TITLE
Jetbrain Appcode cannot show autocomplete for Material's methods/properties

### ISSUE THREAD

**Issue by haithngn** [CosmicMind/Material#1069]
Hi,
I'm using Material via Carthage, also using Xcode and Appcode together.
On Apple Xcode Material's methods/properties are displayed on autocomplete popup but on Appcode it does not show.

Does it relate to the way we define the Material's header ?
Could you please investigate that ?

**Comment by danieldahan** [comment]
Hey! I would love to help, but I don't support 3rd party IDEs and or products I don't use on the regular. I would be open to making adjustments if there is a direct issue with how my headers are written, but from what I know, I haven't done anything out of the norm. Please feel free to connect on possible solutions you may find. Thank you!

**Comment by haithngn** [comment]
@danieldahan , my source code quite heavy, could I have your email or something like that ?

**Comment by danieldahan** [comment]
please use : support@cosmicmind.com
