### ISSUE TITLE
TabsController stops animating

### ISSUE THREAD

**Issue by fabianbraach** [CosmicMind/Material#1070]
Hey there,

I just found a bug, after some time of usage, the animation of the tabs switching in a `TabsController` stops working. I debugged it a little bit, and it seems that `animatingFromViews` and `animatingToViews` are both empty after `prepareAnimatingViews()` in `MotionTransition+Start.swift:199`. I couldn't get deeper into it, but I hope you may have an idea why this occurs. It's not for all tabs and not easy to reproduce, it seems a little bit random. Hope you can help.

**Comment by danieldahan** [comment]
Hey! Sorry for the late reply. We have made updates to both Material and Motion. Give the latest a try, and if you still face any issues, please reopen or create a new one. Thank you!
