### ISSUE TITLE
FABMenuController does't work on ios 8.0

### ISSUE THREAD

**Issue by daveleenew** [CosmicMind/Material#1072]
FABMenuController does't work on ios 8.0.

**Comment by danieldahan** [comment]
What exactly is not working? I am downloading a simulator for it now.

**Comment by daveleenew** [comment]
I run the demo on IOS 8 simulator.but crash~~~

**Comment by daveleenew** [comment]
@danieldahan  I like this library so much..Thank you

**Comment by danieldahan** [comment]
@daveleenew Thank you! I recently updated the samples, can you give it another try. If you need, please reopen this issue or create another.
