### ISSUE TITLE
myriad problems running the example projects

### ISSUE THREAD

**Issue by AlexanderBollbach** [CosmicMind/Material#1073]
e.g. I cannot launch the "Search" example, fails to compile with `Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'`

**Comment by danieldahan** [comment]
I will take a look. Thank you! I haven't updated all the samples and will do that.

**Comment by danieldahan** [comment]
I recently updated the samples for the latest frameworks. Please update and try the samples again. Thank you!
