### ISSUE TITLE
Need to use a NavigationBar subclass with NavigationController

### ISSUE THREAD

**Issue by phlippieb** [CosmicMind/Material#1074]
Hi!

As part of our app, we have UI elements [similar to this](https://github.com/hyperoslo/Whisper). They are added as subviews of the navigation bar, but they display outside its bounds. These views must be tappable.

My solution was to subclass NavigationBar and override `hitTest(:with)`. However, in order to use my subclass of NavigationBar, I had to fork Material and add a new designated initializer to NavigationController that accepts a `navigationBarClass` parameter, which it then passes to super:

```
public init(rootViewController: UIViewController, navigationBarClass: Swift.AnyClass?) {
    super.init(navigationBarClass: navigationBarClass, toolbarClass: nil)
    setViewControllers([rootViewController], animated: false)
}
```

This was necessary because the existing initializers on Material's NavigationController hide the initializer on UINavigationController that accepts a  navigationBarClass parameter.

This is fine for us, for now, but we would prefer to point to this repo, and not our fork. Would you be interested in merging a PR that extends NavigationController with the ability to specify a navigationBarClass? Or is there perhaps another suggested way to achieve what I need?

**Comment by danieldahan** [comment]
Yes I would be. Please send it over and in general, I am interested in all PRs. Thank you!

**Comment by danieldahan** [comment]
Please link your PR to this issue and I will get it in for you.

**Comment by phlippieb** [comment]
Great! I created pull request #1079 for this.

**Comment by danieldahan** [comment]
@phlippieb Awesome, I will merge this in tonight or tomorrow. Thank you! Closing this for now.
