### ISSUE TITLE
Clicking FabMenuItem UILabel (title)

### ISSUE THREAD

**Issue by shemchavez** [CosmicMind/Material#1076]
Is it possible to get the same action when clicking the FabButton in FabMenuItem in clicking UILabel in FabMenuItem also? Even I add a UITapGestureRecognizer in UILabel it still won't work cause you handle clicking by checking clicked point really inside a subview of FabMenu. Frame of FabMenuItem does not scale including the frame of UILabel.

![screen shot 2018-05-22 at 10 46 38 am](https://user-images.githubusercontent.com/19364885/40340293-c11eba36-5db0-11e8-975b-8d34a0226c33.png)
![screen shot 2018-05-22 at 11 04 02 am](https://user-images.githubusercontent.com/19364885/40340297-c58ddc96-5db0-11e8-95a9-5b8de4df6b9b.png)

**Comment by shemchavez** [comment]
Up

**Comment by danieldahan** [comment]
The handler is actually set to the button. The UILabel is not a button, but a label. That said, you could alter the entire FABMenuItem and customize it. Let's move this to the [Material channel](https://gitter.im/CosmicMind/Material) and discuss further :) Thank you!

**Comment by shemchavez** [comment]
Will join then.

**Comment by Matungos** [comment]
How has this "fixed"?
I would like to have the click on the label also.
