### ISSUE TITLE
ChipBarDelegate not implemented

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Material#1077]
this function is never called, because there is no implementation in the code
`func chipBar(chipBar: ChipBar, didSelect chipItem: ChipItem)` of `ChipBarDelegate`

**Comment by danieldahan** [comment]
Hey! It was a n unfinished component that was in an alpha release. It is marked for completion in the next round of component releases. At the moment, the education centre I have been working is near complete and will release with updates to all the frameworks, including this. Sorry for the inconvenience and thank you!
