### ISSUE TITLE
`convenience init()` across the framework prevents generic initialization of the components 

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#1085]
All of the following convenience initializers that are defined for `UIView` subclasses are redundant.
```swift 
public convenience init() {
  self.init(frame: .zero)
}
```

With or without it, we can create object of `UIView` and its subclasses. Adding it actually causes a problem for their use in generic initialization
For example `TextField()`. 

![image](https://user-images.githubusercontent.com/15037839/40936712-421be6ee-684d-11e8-8183-9620544c86a0.png)

**Comment by danieldahan** [comment]
Let's remove them. Great find.

**Comment by danieldahan** [comment]
I merged in the PR. I will close this now. Thank you!
