### ISSUE TITLE
TabBar item is selected even though TabsController delegate shouldSelect always returns false

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#1087]
I have tabsController and following delegate method implemented
```swift
func tabsController(tabsController: TabsController, shouldSelect viewController: UIViewController) -> Bool {
  return false
}
```
View controller is not selected but tab bar item is getting selected but it shouldn't: 
![](https://user-images.githubusercontent.com/15037839/40972457-d4ffd8d8-68d1-11e8-9448-a4e6d3f46e3e.gif)

But normally it looks like: 

![](https://user-images.githubusercontent.com/15037839/40972524-0488998c-68d2-11e8-95ad-6e7bf9287e26.gif)

**Comment by danieldahan** [comment]
We can close this now as it is merged in. Than you!
