### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by rex3du** [CosmicMind/Material#1089]
I've got this error :
Material.framework: bundle format unrecognized, invalid, or unsuitable Command /bin/sh failed with exit code 1

I installed the framework using CocoaPods.

**Comment by OrkhanAlikhanov** [comment]
Xcode version?
Material version?
CocoaPods version?

**Comment by rex3du** [comment]
Xcode 9.4
Material  version 2.0
CocoaPods 1.5.3

**Comment by OrkhanAlikhanov** [comment]
[Material 2.0.0](https://github.com/CosmicMind/Material/releases/tag/2.0.0) is released on October 1, 2016 and 752 commits have been made to master since that time. Latest version is 2.15.0 as of now. Can you try and let us know if the issue persists in the latest release?

**Comment by OrkhanAlikhanov** [comment]
Interesting. Can you try to integrate it to a brand new project and see if it fails to compile again? It suspect it arose after updating to Xcode 9.4, which I don't and won't have in the near future to check this issue.

**Comment by rex3du** [comment]
I create a brand new project and only install Material for the project. The same issue is still there.

**Comment by OrkhanAlikhanov** [comment]
Thank you. It would be great if you attach that project here.

**Comment by danieldahan** [comment]
@rex3du Can you clean your CocoaPods cache and try installing again?

**Comment by rex3du** [comment]
@danieldahan  I've tried to clean the cache and reinstall the pods. It's still the same. 
@OrkhanAlikhanov  Here's the link for that brand new project
https://drive.google.com/file/d/1PcP8zLUEocZpjSVJJi2UW6QSCbt-Gyys/view?usp=sharing

**Comment by rex3du** [comment]
@OrkhanAlikhanov @danieldahan  Thanks for your help.
After doing those below, the issue has been fixed:
rm -rf ~/Library/Caches/CocoaPods; 
rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*;
 pod deintegrate; 
pod setup; 
pod install;

**Comment by danieldahan** [comment]
@rex3du Are you using a beta version of Xcode?

**Comment by rex3du** [comment]
No, the Xcode version is 9.4

**Comment by danieldahan** [comment]
@rex3du awesome, thank you!
