### ISSUE TITLE
 Is there any possibility to install this framework like pod

### ISSUE THREAD

**Issue by ajay2c9** [CosmicMind/Material#1090]
I want to install the framework using the pod. Is there any possibility to install this framework like pod

Thank you

**Comment by OrkhanAlikhanov** [comment]
Sure, there is. Material defines [.podspec](https://github.com/CosmicMind/Material/blob/master/Material.podspec). So you can import it:
```ruby
pod 'Material', '~> 2.0'
```

You may want to look into [installation guide](https://www.cosmicmind.com/danieldahan/lesson/6).

**Comment by danieldahan** [comment]
I will close this issue now. Thank you @OrkhanAlikhanov
