### ISSUE TITLE
2.15.0 doesn't compile?

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Material#1091]
Just refreshed my cocoapods and got a bunch of compile errors, had to revert to 2.14.0 which compiles fine.

**Comment by OrkhanAlikhanov** [comment]
Can you share those errors with us, so that we may help?

**Comment by muzoman** [comment]
Apologies, something strange going on in my podfile. If I just include non version specific pod lines like: pod 'Material' I don't pick up the 2.15.0 but some ancient version, no idea why. Similarly, I had pod 'Motion' in  the next line and it picked up an ancient version. I had to add specific version information to the podfile and everything compiled OK.

**Comment by OrkhanAlikhanov** [comment]
Great! That's probably because of Podfile.lock

**Comment by muzoman** [comment]
can I delete that file then?

**Comment by OrkhanAlikhanov** [comment]
You shouldn't actually. It will be generated anyways when you do `pod install`.
