### ISSUE TITLE
TextField.placeholderLabel is positioned higher than before in version 2.x.x

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#1092]
https://github.com/CosmicMind/Material/issues/568#issuecomment-394635129 says that we have huge margin between `TextField` and its `placeholderLabel`.

Currently a `TextField` with placeholder looks like this:
![](https://user-images.githubusercontent.com/15037839/41105493-ee68f238-6a7e-11e8-925c-5d9ab04dad96.jpg)
Layers: 
![](https://user-images.githubusercontent.com/15037839/41105497-ef28ec46-6a7e-11e8-9240-68d8fd1e50ea.jpg)

But after applying the fix in the above linked comment we got this:
![](https://user-images.githubusercontent.com/15037839/41105496-eeca5faa-6a7e-11e8-8fce-bdd036179719.jpg)
Layers: 
![](https://user-images.githubusercontent.com/15037839/41105498-ef77f138-6a7e-11e8-8db5-133d7bd10eb8.jpg)

Somehow, `placeholderLabel.bounds.height` returns `32.0` but `placeholderLabel.frame.height` gives `24.0`. But why? 

@danieldahan I personally always increased `placeholderVerticalOffset` to lower that margin. I thought it has that height *by design* lol. It would be great if @jbaez sends his fix for this as a PR.

**Comment by jbaez** [comment]
I just sent a PR with the fix. @OrkhanAlikhanov that's exactly the issue. The placeholder used to be positioned right above the textfield by using the frame height (24.0)

**Comment by danieldahan** [comment]
Excellent, thank you! I merged it into development and it will be out in the next release. I will close this issue now. Thank you!
