### ISSUE TITLE
Textfield - Divider Line 

### ISSUE THREAD

**Issue by Ronaldoh1** [CosmicMind/Material#1099]
![textfields-annotations-1](https://user-images.githubusercontent.com/1154424/41780343-76d900a2-7602-11e8-8661-2c4d3bbf095a.png)
Good morning, 

first of all thank you for making this project available. It's been of great help. 

I am working on a couple of screens that use your Meterial TextFields. I was wondering if there is any way to make the divider line (line under textfield) to stretch all the way the end of the left view. 
Essentially the line would be underneath the leftView icon and the textfield itself. 

Something like this 

[https://material.io/design/assets/1Ejie5ILk2-eAB9wBRFG93aJtYV7gJtJV/textfields-annotations-1.png](url)

any help would be greatly appreciated.

**Comment by OrkhanAlikhanov** [comment]
Hey! That's only possible by subclassing currently. Set `dividerContentEdgeInsets.left = 0`
```swift
class MyTextField: TextField {
  override func layoutSubviews() {
    super.layoutSubviews()
    dividerContentEdgeInsets.left = 0
  }
}
```

**Comment by danieldahan** [comment]
@Ronaldoh1 I am happy you are getting value out of Material :) 

@OrkhanAlikhanov made a good suggestion. If you have any further issues, please reopen or create a new issue.
