### ISSUE TITLE
Setting default state not working

### ISSUE THREAD

**Issue by albertml** [CosmicMind/Material#1105]
I write this code in viewDidLoad to save default state but its not working. Please simulate thanks

localizationSwitch.switchState = Localize.currentLanguage() == "en" ? .on : .off

**Comment by danieldahan** [comment]
What is not working exactly? The switch, or the correct flag? I looked through the code and tested the sample project and all works as expected. If you need, please reopen or create a new issue. Thank you!

**Comment by albertml** [comment]
The switch.. I set the state of the switch to off and exit the app. But when I reopen the app the switch state value is off which is correct but the problem is the Switch UI. I want the UI when it set to off to be like this 
![screen shot 2018-07-02 at 3 06 38 pm](https://user-images.githubusercontent.com/8196166/42149643-9e438392-7e09-11e8-951f-6d23767b4f64.png) but it result like this 
![screen shot 2018-07-02 at 3 07 04 pm](https://user-images.githubusercontent.com/8196166/42149658-aa388972-7e09-11e8-84d3-ad70b621d0c6.png). This is not the ON status of my switch. The ON status of my switch is the big circle color is white.

**Comment by danieldahan** [comment]
Interesting. I will need to replicate this issue and see if it is an issue with Material's internals.

**Comment by danieldahan** [comment]
@albertml Can you send over a sample project for us to test?

**Comment by albertml** [comment]
yeah... I'll to create a sample project that will replicate this issue

**Comment by albertml** [comment]
@danieldahan I thing the issue was in the setting of custom color

@IBOutlet weak var localizationSwitch: Switch!
        {
        didSet {
            localizationSwitch.buttonOnColor = .white
            localizationSwitch.buttonOffColor = .lightGray
            localizationSwitch.trackOnColor = .lightGray // change this to .lightText and animation work
            localizationSwitch.trackOffColor = .lightGray
            localizationSwitch.switchSize = .small
        }
    }

**Comment by danieldahan** [comment]
@albertml So is there still an issue?

**Comment by albertml** [comment]
It must be fix why animation not work when trackOnColor is .lightGray...

**Comment by OrkhanAlikhanov** [comment]
@albertml How do you animate it? Can you attach a sample project for us to test?

**Comment by albertml** [comment]
just use the default... I just change the custom colors.

**Comment by OrkhanAlikhanov** [comment]
Well, we can't help this way. Can't you create a sample project?

**Comment by danieldahan** [comment]
I am closing this issue. Nothing has proven to be an issue here.
