### ISSUE TITLE
Links broken on  the README

### ISSUE THREAD

**Issue by philosopherdog** [CosmicMind/Material#1108]
We're not seeing any images and the links to instructions on the README are not working.

**Comment by OrkhanAlikhanov** [comment]
Thank you for reporting this. To me, it's really weird that actively requested images are deleted from GitHub's CDN. @danieldahan You can contact GitHub if you want but we can obtain and re-upload images from [a cached copy](https://web.archive.org/web/20180109072014/https://github.com/CosmicMind/Material) which was crawled on 9 January, 2018

**Comment by danieldahan** [comment]
I will make a fix for this, it was an accident on my behalf when I updated the servers for the CM site.

**Comment by danieldahan** [comment]
I fixed the image issue, and need to update the README on installation. This will be done separately. Thank you!
