### ISSUE TITLE
No Alert View Controller Component?

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Material#1118]
Seems conspicuous by it's absence? 

What do folks typically do when creating Apps built to Material guidelines for Alerts? Just use Apples UIAlertController? Can't believe they do as it's not customisable...

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank you! It will be in Material 3. It's been implemented in #1021 but merged to m3 branch not the main branch. You can add the files from PR to your local if you want to use it

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Let's move the Alert view to the development branch after our next release. I am going to close this as we no longer maintain feature requests here.
