### ISSUE TITLE
TextField is not scrolling when inputing characters and using a large Font size.

### ISSUE THREAD

**Issue by kylebrowning** [CosmicMind/Material#1123]
Using the example project. 

Set your font to something high, example:

```swift
emailField.font = UIFont.systemFont(ofSize: 29)
emailField.placeholderLabel.font = UIFont.systemFont(ofSize: 29)
```

Type enough characters to reach the end of the TextField and notice that it does not continue to scroll.

If you move back one character with your arrow keys, or if you move back by bringing up the text scroll (force press) then continue to type, it works normally.

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov for your PR (https://github.com/CosmicMind/Material/pull/1124), which is now merged into development. In our next release, this will be available. Thank you!
