### ISSUE TITLE
TextView could auto-adjust hight based on text lines

### ISSUE THREAD

**Issue by kolczak** [CosmicMind/Material#1127]
Hi,
did you think about enhancing the TextView to automatically adjust its height to display all the text it contains? It could expand its hight while user typing.
Regards!

**Comment by OrkhanAlikhanov** [comment]
I think if you disable  `isScrollEnabled` and set relevant constraints, it will behave like that.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Let's confirm this. If not, I agree that we should support it.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan By disabling `isScrollEnabled` we lose ability to scroll. I think we can introduce `preferredMaxLayoutHeight`, allow growing upto that point and scroll after.

**Comment by danieldahan** [comment]
This issue has been addressed in this PR https://github.com/CosmicMind/Material/pull/1130
