### ISSUE TITLE
 BottomNavigationController same swipe behaviour as Tabbar

### ISSUE THREAD

**Issue by Parilar** [CosmicMind/Material#1132]
Hello,
i had the same Issue with the title at bottom and changed from Tabbar to BottomNavigationController.
But now i lost the swipe effect to change the Page. I', looking for the same swipe effect like android has it to change the page where you can see both pages while swiping.

Is there any way to archive that behavior with BottomNavigationController?

**Comment by Parilar** [comment]
Nope, I'll try the other class and give feedback later

Daniel Dahan <notifications@github.com> schrieb am Mo., 13. Aug. 2018,
18:24:

**Comment by OrkhanAlikhanov** [comment]
@Parilar You changed from `UITabBarController` to `BottomNavigationController` or from `TabsContoller`?
Among those, only `TabsContoller` has swipe gesture feature (which is with animation). 
`BottomNavigationController` is direct subclass of  `UITabBarController`, I don't believe we can easily add animation to it. I need to take a look at though.

**Comment by danieldahan** [comment]
@Parilar Motion, which is part of Material, allows for you to tap into `UITabBarController`'s interactive and non-interactive transitions. We will put together a mini example on how to accomplish this.

**Comment by Parilar** [comment]
From TabsController

Daniel Dahan <notifications@github.com> schrieb am Mo., 13. Aug. 2018,
19:07:

**Comment by danieldahan** [comment]
@Parilar Why do you need to switch navigation controllers from TabsController?

**Comment by Parilar** [comment]
Because I want the title at the bottom and in another ticket you said that
I have to use bottomNavigationController

Daniel Dahan <notifications@github.com> schrieb am Mo., 13. Aug. 2018,
19:36:

**Comment by Parilar** [comment]
@danieldahan in #932 you metioned it
