### ISSUE TITLE
Cocoapods Last Version

### ISSUE THREAD

**Issue by savasadar** [CosmicMind/Material#1137]
When I use Material repo with cocoapods like this` pod 'Material', '~> 2.16.4' `

I got an error.

> [!] CocoaPods could not find compatible versions for pod "Material":
>   In Podfile:
>     Material (~> 2.16.4)

Please update cocoapods

Thanks

**Comment by OrkhanAlikhanov** [comment]
Hey! Try `pod install --repo-update`

**Comment by danieldahan** [comment]
@OrkhanAlikhanov good suggestion. As well, the version exists [Material 2.16.4](https://github.com/CosmicMind/Material/tree/2.16.4).
