### ISSUE TITLE
TabsController inside a UINavigationController not showing tabBar 

### ISSUE THREAD

**Issue by vitormesquita** [CosmicMind/Material#1138]
Hi, I'm trying use `TabsController` with `tabBarAlignment = .top` inside a navigation controller, but when I run my project the `tabBar` is behind `UINavigationBar`.

My `TabsController` is:

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func prepare() {
        super.prepare()
        
        tabBarAlignment = .top
        tabBar.lineAlignment = .bottom
        tabBar.backgroundColor = .primary
        tabBar.setLineColor(.white, for: .selected)
        tabBar.setTabItemsColor(.white, for: .selected)
        tabBar.setTabItemsColor(.white, for: .highlighted)
        tabBar.setTabItemsColor(UIColor.white.withAlphaComponent(0.7), for: .normal)
        tabBar.dividerColor = .primary
        tabBar.lineHeight = 1
    }
```

I've ran on iPhone 7 and iPhone X but the same error happened.
Can you help me? I'm doing some mistake?

**Comment by bstillitano** [comment]
`import Foundation
import UIKit
import Material
import SVProgressHUD

class VenueProfileViewController: TabsController {
    //UI Elements
    var saveBarButtonItem: UIBarButtonItem!

    //Data
    var profileDetailsViewController: VenueProfileDetailsViewController!
    var profileHoursViewController: VenueProfileHoursViewController!
    var profileOperationsViewController: VenueProfileOperationsViewController!

    open override func prepare() {
        super.prepare()
        
        //Add Header
        let headerView: OMVenueCompletionView = OMVenueCompletionView()
        self.view.addSubview(headerView)
        headerView.snp.makeConstraints { (make) in
            make.top.equalTo(0)
            make.left.equalTo(0)
            make.width.equalToSuperview()
            make.height.equalTo(66)
        }
        
        //Fetch Profile Completion
        OMProfileService().getProfileCompletion(accessToken: OMKeychainService.loadAccessToken()!, retailerId: OMVenuesManager.instance.selectedVenue.id, completion: { (completionCode, omProfileCompletion) in
            DispatchQueue.main.async {
                switch completionCode {
                case .ERROR_PROCESSING_JSON:
                    break
                    
                case .INVALID_SERVER_RESPONSE:
                    break
                    
                case .NETWORK_ERROR:
                    break
                    
                case .SUCCESS:
                    //Set Profile Card Data
                    headerView.setData(venueName: OMVenuesManager.instance.selectedVenue.tradingName!, percentComplete: (omProfileCompletion?.profilePercent)!)
                    break
                }
            }
        })

        //Setup TabBar
        tabBar.setLineColor(OMColorUtils.brightOrange, for: .selected)
        tabBarAlignment = .top
        tabBar.tabBarStyle = .auto
        tabBar.lineAlignment = .bottom
        tabBar.dividerAlignment = .bottom
        
        //Set TabBar Colors
        tabBar.setTabItemsColor(OMColorUtils.brightOrange, for: .selected)
        
        //Set View Constraints
        tabBar.snp.makeConstraints { (make) in
            make.top.equalTo(headerView.snp.bottom)
        }
        
        //Setup Close Button
        let closeBarButtonItem: UIBarButtonItem = UIBarButtonItem(title: nil, style: .plain, target: self, action: #selector(closeViewController))
        closeBarButtonItem.image = UIImage(named: "iconClose")
        closeBarButtonItem.tintColor = OMColorUtils.charcoalGrey
        self.navigationItem.leftItemsSupplementBackButton = false
        self.navigationItem.setLeftBarButton(closeBarButtonItem, animated: true)
        
        //Setup Save Button
        saveBarButtonItem = UIBarButtonItem(title: "SAVE", style: .plain, target: self, action: #selector(saveAction))
        saveBarButtonItem.tintColor = OMColorUtils.brightOrange
        self.navigationItem.setRightBarButton(saveBarButtonItem, animated: true)
    }
    
    @objc func closeViewController() {
        self.dismiss(animated: true, completion: nil)
    }
    
    @objc func saveAction() {
        //Save Venue Details
        
        //Save Venue Operations
        updateVenueOperations()
    }
    
    func updateVenueOperations() {
        //Show HUD
        SVProgressHUD.show(withStatus: "Updating Operations")
        
        //Save Venue Operations
        OMDataAttributesService().updateVenueOperations(accessToken: OMKeychainService.loadAccessToken()!, posName: profileOperationsViewController.posTextField.text, accountingName: profileOperationsViewController.accountingTextField.text, bankingName: profileOperationsViewController.bankTextField.text, completion: { (completionCode) in
            DispatchQueue.main.async {
                switch completionCode {
                case .ERROR_PROCESSING_JSON:
                    break
                    
                case .NETWORK_ERROR:
                    break
                    
                case .INVALID_SERVER_RESPONSE:
                    SVProgressHUD.showError(withStatus: "Update Failed")
                    break
                    
                case .SUCCESS:
                    SVProgressHUD.showSuccess(withStatus: "Venue Updated")
                    break
                }
                
                //Dismiss HUD
                SVProgressHUD.dismiss(withDelay: 0.8)
            }
        })
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        //Set Title
        self.title = "VENUE PROFILE"
        
        //Hide Navigation Bar Hairline
        self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        self.navigationController?.navigationBar.shadowImage = UIImage()
    }
}`

Was able to implement this using the code above.

**Comment by bstillitano** [comment]
I’ve implemented this just fine in a UINavigationController
programmatically.

@vitormesquita try to see if just a simple UINavigationController with a
TabsController embedded reproduces the issue. I have a suspicion it’s
something else that causes this given that it’s not happening for others.

**Comment by danieldahan** [comment]
Okay, unless we have a reproducible project, we put this in the queue internally for us to investigate as work. So I will close this now as you seem to have solved your issue, and we will make any new issues as we investigate more about this.

**Comment by vitormesquita** [comment]
@danieldahan I can send my classes to you reproduce this issue. 

But answer your question I'm using UINavigationController. I've investigated to see what is happening, and I think the problem is on safearea, but I really don't know.

The pod version is `2.16.4`

**Comment by danieldahan** [comment]
The more you can send and help us discover the issue. The better :) Thank you!

**Comment by vitormesquita** [comment]
Ok @danieldahan Thank you for answer quickly. I'll investigate more to help you.
