### ISSUE TITLE
Layout - constraint to another view

### ISSUE THREAD

**Issue by davidevincenzi** [CosmicMind/Material#1139]
Hello,

it's a pretty basic question but I can't find an answer.
I have two labels, both children of the same view.

I set up the first label like this:
`view.layout(firstLabel).top(100).right(10).left(10)`

How do I set up the secondLabel so that it's 30 pixels below the bottom edge of the firstLabel?

Using standard autolayout syntax I would write it like this:

```
self.view.addConstraint(
    NSLayoutConstraint(
        item: secondLabel,
        attribute: .Top,
        relatedBy: .Equal,
        toItem: firstLabel,
        attribute: .Bottom,
        multiplier: 1.0,
        constant: 0
    ))
```

Is there a way to do that by using Material?

Thanks!

**Comment by OrkhanAlikhanov** [comment]
@davidevincenzi Hey! Thank you for sharing your issue with us. It seems there isn't any way to achieve that using Material's Layout system. We will probably rework it to add support for that. Thank you!

**Comment by davidevincenzi** [comment]
@OrkhanAlikhanov thanks a lot :)

**Comment by danieldahan** [comment]
@OrkhanAlikhanov let's move this to a feature request, and I do believe it has great value in our Layout system. Thanks guys!

**Comment by OrkhanAlikhanov** [comment]
Hey @davidevincenzi! It's coming in #1185! 

With new update you can achieve what you asked in this issue:
```swift
view.layout(firstLabel).top(100).right(10).left(10)
view.layout(secondLabel)
      .top(firstLabel.layout.bottom, 30)
      .leftRight(firstLabel.layout.leftRight)
```

**Comment by davidevincenzi** [comment]
Wow! Thank you guys, I love this library!
👍👍👍
