### ISSUE TITLE
navigationItem properties are not working

### ISSUE THREAD

**Issue by CHONUMAN** [CosmicMind/Material#1140]
When I set a NavigationController as a viewcontroller of a BottomNavigationController in storyboard I am setting the navigation titlelabel, leftviews etc from the rootviewcontroller of the NavigationController but they are not appearing when I run.

**Comment by danieldahan** [comment]
Did you set in your Storyboard the `NavigationController` and `NavigationBar` class names in the Xcode editor.

**Comment by CHONUMAN** [comment]
yes. I subclassed both NavigationController and BottomNavigationController then set them in storyboard. The navigationcontroller could not set the tabbaritem in the prepare() method. Instead i had to override the init?(coder aDecoder: NSCoder) method to set it.

Also a different issue. I did the same without the storyBoard. BottomNavigationController -> NavigationController -> UIViewController. Where BottomNavigation is the initial view set in appdelegate. this time the status bar wont appear. If i click another tab that does not have a NavigationController the status bar appears. If I switch back the NavigationController of the previous viewcontroller hides it again.

**Comment by OrkhanAlikhanov** [comment]
As far as I remember `navigationItem.title` and `navigationItem.{left|right}Views` can only be manipulated via code. That's a limitation.

**Comment by danieldahan** [comment]
They need to be set programmatically, that is correct. The navigation items will need to be set in the root view controller of the NavigationController as per usual. If there is a failure to this, please send us a project that replicates the issue. Thank you!

**Comment by OrkhanAlikhanov** [comment]
@CHONUMAN Please send us a project that replicates the issue.

**Comment by CHONUMAN** [comment]
ok i got it. i have to set the NavigationBar class in the storyboard. Thanks for the help.

**Comment by danieldahan** [comment]
@CHONUMAN awesome. If you need any further help, please reopen or create a new issue. Thank you!
