### ISSUE TITLE
Set base configuration of Checkbox to tint = clear.

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#1141]
Let's investigate this based on this issue https://github.com/CosmicMind/Samples/issues/121#issuecomment-418155039

**Comment by OrkhanAlikhanov** [comment]
I believe this is solved via https://github.com/CosmicMind/Samples/issues/121#issuecomment-420444249

**Comment by danieldahan** [comment]
Excellent, thank you!
