### ISSUE TITLE
Need help with component flow.

### ISSUE THREAD

**Issue by CHONUMAN** [CosmicMind/Material#1145]
Hello @danieldahan.  I'm trying to make a tab based app with a navigation bar and a navigationdrawermenu. So far i have succeeded in implementing the following flow -

- BottomNavigationController -> NavigationController -> ViewController

Now Im trying to include a navigationDrawer but so far I have failed. Any suggestions will be appreciated. P.S. I'm using storyboard, mostly.

**Comment by OrkhanAlikhanov** [comment]
Hey! For questions, use stackoverflow with `cosmicmind` tag or our [`gitter channel`](https://gitter.im/CosmicMind/Material)


For `NavigationDrawerController` you'll have to define your hierarchy in code, see [NavigationDrawerController sample](https://github.com/CosmicMind/Samples/blob/master/Projects/Storyboards/NavigationDrawerController/NavigationDrawerController/)

**Comment by OrkhanAlikhanov** [comment]
NavigationDrawerController should be the topmost controller generally.
```swift
let homeVc = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "HomeViewController")

let tabsVc = AppTabViewController(viewControllers: [HomeNavigationController(rootViewController: homeVc), SearchMediaViewController()])
window?.rootViewController =  AppNavigationDrawerViewController(rootViewController: tabsVC, leftViewController: nil, rightViewController: DrawerViewController())
```

**Comment by CHONUMAN** [comment]
you're an angel @OrkhanAlikhanov . bless you man. another minor thing. everything is as I want them to be but when the drawer opens the status bar in the back gets disappeared. when i close the drawer it comes back again.

**Comment by OrkhanAlikhanov** [comment]
Hey! No need to overpraise me :) Thank you for your appreciation.


You can set `isHiddenStatusBarEnabled` to `false`. Default value is true.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Thank you!

**Comment by CHONUMAN** [comment]
hi. im using NavigationDrawerController. I have a right view that comes out when i press the menu button. how can i close the right view when i tap to the left part past the right view.

**Comment by OrkhanAlikhanov** [comment]
@CHONUMAN Hey, we you can call `navigationDrawerController?.closeRightView()`. It's available for leftView as well. You can check [`NavigationDrawerController.swift`](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationDrawerController.swift) out for more info.
