### ISSUE TITLE
Enabling swipe effect on AppTabsController >> Line of current tab not going to be change while using swipe on tabs

### ISSUE THREAD

**Issue by shroff-kandarp** [CosmicMind/Material#1149]

**Comment by OrkhanAlikhanov** [comment]
Hey! Can you share a minimal sample project replicating the issue?

**Comment by shroff-kandarp** [comment]
I found problem. 
    self.tabBar.animate(to: self.tabBar.tabItems[index])

Add above line in function 

private func internalSelect(at index: Int, isTriggeredByUserInteraction: Bool) -> Bool {
 guard index != selectedIndex else {
      return false
    }
    
    if isTriggeredByUserInteraction {
      guard !(false == delegate?.tabsController?(tabsController: self, shouldSelect: viewControllers[index])) else {
        return false
      }
    }
    
    **self.tabBar.animate(to: self.tabBar.tabItems[index])**
    
    transition(to: viewControllers[index], isTriggeredByUserInteraction: isTriggeredByUserInteraction) { [weak self] (isFinishing) in
      guard isFinishing else {
        return
      }
      
      self?.selectedIndex = index
    
        
    }
}

**Comment by OrkhanAlikhanov** [comment]
Latest code is a little bit different:

https://github.com/CosmicMind/Material/blob/c9fb3f6f3067ddc869ca6128b5e4e5a783075688/Sources/iOS/TabsController.swift#L399-L432

**Comment by shroff-kandarp** [comment]
Okay. Thanks. I have old version of this library.

**Comment by OrkhanAlikhanov** [comment]
The code I pointed is from development branch. It might not be in release

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov. @shroff-kandarp if you have any further questions, or another issue, please reopen or create a new one. Thank you!
