### ISSUE TITLE
Cannot change height of Tabbar

### ISSUE THREAD

**Issue by shroff-kandarp** [CosmicMind/Material#1150]

**Comment by OrkhanAlikhanov** [comment]
Hey! How do you set height of TabBar?

**Comment by shroff-kandarp** [comment]
I need to change height of tabbar but library does not provides this (i didn't find anything regarding this.).

**Comment by OrkhanAlikhanov** [comment]
Try:
```
tabBar.heightPreset = .normal
```

**Comment by danieldahan** [comment]
Both `tabBar.height` and `tabBar.heightPreset` should work. Let's investigate this. Thank you!

**Comment by shroff-kandarp** [comment]
tabBar.height is not available in current cocoa pod version. tabBar.heightPreset is working but labels in tab is stick to top. It should be vertically center in tab area.

**Comment by danieldahan** [comment]
@shroff-kandarp sorry, that is correct, we removed the helper extensions. I checked the sample project and can confirm that the `tabBar.heightPreset` works and aligns the buttons correctly, as you can see in the photo. That said, the `tabBar.frame.size.height = x` is not working, so @OrkhanAlikhanov and I will look into this. 

<img width="458" alt="screen shot 2018-09-11 at 9 27 16 am" src="https://user-images.githubusercontent.com/9982123/45363331-3f3d1880-b5a5-11e8-8bdd-62f84624dff9.png">

**Comment by shroff-kandarp** [comment]
Yes, my mistake. Vertical Alignment is working properly. Thanks for reply.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan We cannot support `tabBar.frame.size.height = x`. Because we do `tabBar.frame.size.height = tabBar.heightPreset.rawValue + y` in some places. If we change `tabBar.heightPreset.rawValue` to `tabBar.frame.size.height`, the code would be equal to `tabBar.frame.size.height += y` which would cause infinite growing/shrinking of `tabBar` depending on the `y`. 

However, we can add `tabBar.heightPreset = .custom(x)`. What do you think?

**Comment by danieldahan** [comment]
@OrkhanAlikhanov The `.custom(x)` option is a much better decision. And yes, I remember now about the infinite growing issue. That is correct. Thank you!

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov. 

@shroff-kandarp The latest https://github.com/CosmicMind/Material/pull/1151 merged into `development` now includes the feature required to solve this issue.

**Comment by Hamna21** [comment]
Setting _heightPresent_ for tabBar in **BottomNavigationController** changes the vertical alignment. Is there any way to maintain title and image position? 
_titlePositionAdjustment_ is not working for this.

**Comment by OrkhanAlikhanov** [comment]
@Hamna21 Sorry for late response, I checked all were working fine. Can you try again, we've just pushed a tiny fix in #1167
