### ISSUE TITLE
QUESTION: Why adding FABMenu as outlet in view controller is not working? 

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [CosmicMind/Material#1152]
Hi there, 

We are trying to upgrade CosmicMind SDK from  v2.3.21 to latest. But, we are stuck in the middle. In previous version we have added `Menu` as outlet in viewcontrollers, but in latest version it's not working, we are getting a crash. 

<img width="939" alt="fabmenu" src="https://user-images.githubusercontent.com/17313049/45413805-a76c2700-b697-11e8-9d89-a77fc09bda4a.png">

 Please help us to resolve this, Thanks.

**Comment by danieldahan** [comment]
Hi @ThiyagarajanShivSankaran we haven't heard back from you, if you still require help, please reopen or create a new issue. Thank you!

**Comment by ThiyagarajanShivSankaran** [comment]
@OrkhanAlikhanov, @danieldahan Sorry guys for the late reply.

We have tried by resetting the class in storyboard, but no luck we are facing the same issue. Even, we have tried by adding a new view with `FABMenu` class but it's not working too.

<img width="926" alt="fabmenu issue" src="https://user-images.githubusercontent.com/17313049/45606538-90488300-ba63-11e8-8386-3639b76e7bbd.png">

**Comment by danieldahan** [comment]
Please send over a sample project for our review. Thank you!

**Comment by ThiyagarajanShivSankaran** [comment]
@danieldahan Here, I am attaching the sample code.
[FABMenuIssue.zip](https://github.com/CosmicMind/Material/files/2392054/FABMenuIssue.zip)

**Comment by OrkhanAlikhanov** [comment]
Interesting, this is reproducible with development branch. Just create a brand-new project, I add view to view controller in storyboards and set its class to `FABMenu`. Running the app prints following:
>Unknown class _TtC8Material7FABMenu in Interface Builder file.

I tried various ways to fix the issue none worked so far. Haven't tried with latest Xcode 10 yet.

@danieldahan Issue can be reopened I believe

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Thank you for looking into this. Let's continue the investigation.

**Comment by ThiyagarajanShivSankaran** [comment]
@danieldahan , @OrkhanAlikhanov Do you guys have any chance to fix this issue, Thank you.

**Comment by OrkhanAlikhanov** [comment]
Not yet. I don't know where to start. Will look into it on next week's weekend.
