### ISSUE TITLE
How to make "NavigationController" transparent.

### ISSUE THREAD

**Issue by MuhammadNayabButt** [CosmicMind/Material#1154]
I am using AppNavigationController class which has following source code.

```
class AppNavigationController: NavigationController {
    open override func prepare() {
        super.prepare()
        guard let v = navigationBar as? NavigationBar else {
            return
        }
        
        v.depthPreset = .depth3
        v.dividerColor = Color.separator.value
    
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

```

I want to make the navigation Bar Transparent.
I tried using following piece of code in ViewDidLoad as well as viewWillAppear(which works in case of default UINavigationController) but it is not working here.

```
self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
self.navigationController?.navigationBar.shadowImage = UIImage()
self.navigationController?.navigationBar.isTranslucent = true

```

**Comment by ashusath** [comment]
Hi @MuhammadNayabButt, you can try adding following code in prepare
`v.setBackgroundImage(UIImage(), for: .default)
    v.isTranslucent = true
    v.backgroundColor = .clear`
this worked for me, hope this will work for you too.

**Comment by danieldahan** [comment]
Thank you @ashusath, we appreciate your response. @MuhammadNayabButt Please let us know if this works for you, and if not, please reopen or create a new issue. Thank you!

**Comment by MuhammadNayabButt** [comment]
I will do it and would let you know.

**Comment by MuhammadNayabButt** [comment]
Hi @ashusath @danieldahan I have tried above code it works(I created a separate project). But my problem is bit different.

On previous screens I have hidden the navigation controller. When I come to the required viewcontroller I unhide/show the view controller using this command
```
self.navigationController?.setNavigationBarHidden(false, animated: true)
```

strangely after unhiding the navigation controller not even backbutton hides properly neither its tint changes.
like following two lines of code does not have any effect. I get the back button in only blue colour

```
navigationItem.backButton.isHidden = true
navigationItem.backButton.tintColor = UIColor.black
```

it seems there is a problem with native navigation controller and material navigation controller although I am using only material navigation controller

**Comment by OrkhanAlikhanov** [comment]
@MuhammadNayabButt Can you send a sample project replicating the issue?

**Comment by MuhammadNayabButt** [comment]
@OrkhanAlikhanov where should I send the project?

**Comment by OrkhanAlikhanov** [comment]
You can share zip file here or send it to support@cosmicmind.com

**Comment by MuhammadNayabButt** [comment]
@OrkhanAlikhanov Code sent with Subject "Navigation Controller Issues"

**Comment by OrkhanAlikhanov** [comment]
Thank you!

**Comment by MuhammadNayabButt** [comment]
@OrkhanAlikhanov any update
