### ISSUE TITLE
README link to installation instructions is broken

### ISSUE THREAD

**Issue by dmjones** [CosmicMind/Material#1155]
In the README file, there is a link to 
https://www.cosmicmind.com/danieldahan/lesson/6, which is broken.

I can't find where this has moved to, otherwise I'd submit a PR. Have those lessons been deleted?

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank you! The site is under development right now, and will be available soon with new cool stuff. 

#1121

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Thank you! We have been working hard on a new platform, and will be launching the documentation there. In the meantime, we will be posting basic documentation in the [Samples Wiki](https://github.com/CosmicMind/Samples/wiki), and I believe what you are looking for can be found here, with this sample [installation guide](https://github.com/CosmicMind/Samples/wiki/Installation). If you need any further help, we are here :)
