### ISSUE TITLE
TabsController inside TabBarController as RootView

### ISSUE THREAD

**Issue by bstillitano** [CosmicMind/Material#1156]
I am trying to set a TabsController as the root view of a tab inside my UITabBarController.

The issue I am facing is that I can not set the viewcontrollers before the tab loads which makes the view controller crash. Any way to do this?

**Comment by bstillitano** [comment]
@OrkhanAlikhanov thanks in advance for your help. I have attached a sample project.

All I am want to do is make the SecondViewController an instance of TabsController however it crashes in the below line. My feeling as to why it crashes is because we need to init the viewControllers parameter when pushing or presenting the TabsController instance however I can not find a why to do this because it is the root view controller for a tab inside a UITTabBarController

[TabsControllerSample.zip](https://github.com/CosmicMind/Material/files/2390618/TabsControllerSample.zip)

![image](https://user-images.githubusercontent.com/40552246/45656453-e59a9800-bb28-11e8-88b3-15239fce0c2b.png)

**Comment by OrkhanAlikhanov** [comment]
I looked into your setup, `TabsController` does not support storyboards. You have to setup hierarchy through code. Just continue to create individual tabs in storyboards, but to nest them in `TabsController`, init them from storyboards with some identifier then use `TabsController(viewControllers:)` to create TabsController. Thank you!

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov

**Comment by bstillitano** [comment]
Are you able to provide an example please @OrkhanAlikhanov ?

**Comment by OrkhanAlikhanov** [comment]
Something like this:

```swift
extension UIStoryboard {
    class func viewController(identifier: String) -> UIViewController {
        return UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: identifier)
    }                   
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
   
    lazy var leftViewController: BlueViewController= {
        return UIStoryboard.viewController(identifier: "BlueViewController") as! BlueViewController
    }()
    
    lazy var brownViewController: BrownViewController = {
        return UIStoryboard.viewController(identifier: "BrownViewController") as! BrownViewController
    }()
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        window = UIWindow(frame: Screen.bounds)
        let tabs = TabsController([blueViewController, brownViewController])
        window!.rootViewController = UITabBarController(viewControllers: [tabs])
        window!.makeKeyAndVisible()
    }
```

**Comment by bstillitano** [comment]
@OrkhanAlikhanov thanks for your help, that won't work for this situation, I've created my own workaround that i'll post if i get a chance. Thankyou once again.

**Comment by danieldahan** [comment]
@bstillitano @OrkhanAlikhanov awesome :)
