### ISSUE TITLE
Xcode 10 Update

### ISSUE THREAD

**Issue by karasahinemre** [CosmicMind/Material#1157]
After Xcode 10 release this pods gives 292 warnings about --> 'let' properties are implicitly 'final'; use 'public' instead of 'open'. We are waiting for new iOS SDK. Thanks.

**Comment by OrkhanAlikhanov** [comment]
Hey, you can use development branch until we make a release. We're trying so hard to do so. Thank you!

**Comment by danieldahan** [comment]
A release is coming soon. As @OrkhanAlikhanov mentioned, please use the `development` branch, it is pretty stable for now. Thank you!
