### ISSUE TITLE
TabsController Layout Problem with Navigation Bar Large Titles

### ISSUE THREAD

**Issue by karasahinemre** [CosmicMind/Material#1158]
When we present tabs controller on top it is not scrolling with navigation bar. You can see the images below.

Normal
![img_006d5a8467a1-1](https://user-images.githubusercontent.com/9135318/45643976-0b8e5100-bac5-11e8-9f99-75198b95f9a5.jpeg)
While scrolling down the page
![img_3a9f96b4e241-1](https://user-images.githubusercontent.com/9135318/45643968-07faca00-bac5-11e8-9cfd-2ba0df2c9b2f.jpeg)

**Comment by OrkhanAlikhanov** [comment]
Can you send over a sample project replicating the issue? Thank you!

**Comment by OrkhanAlikhanov** [comment]
@karasahinemre You can manually update `tabBar` position for now, until we come up with a better solution.
```swift
class AppTabsController: TabsController {
  
  var navBarFrameObserver: NSKeyValueObservation!
  open override func prepare() {
    super.prepare()
    tabBarAlignment = .top
    navBarFrameObserver= navigationController?.navigationBar.observe(\.frame) { [weak self] nav, _ in
      self?.layoutSubviews()
    }
  }
  
  override func layoutSubviews() {
    super.layoutSubviews()
    
    guard let navBar = navigationController?.navigationBar  else {
      return
    }
    
    let additionalInset = max(0, navBar.frame.height - 96)
    tabBar.frame.origin.y += additionalInset
  }
}
```

**Comment by karasahinemre** [comment]
Thank you for your response. Manually update is working as expected. Waiting for good news from you about better solution 😊

**Comment by danieldahan** [comment]
@OrkhanAlikhanov thank you! @karasahinemre I am happy it worked out for you. We will keep note of this and make a better solution.
