### ISSUE TITLE
Error installing development branch.

### ISSUE THREAD

**Issue by johnmikel** [CosmicMind/Material#1162]
So with the recent update of Xcode, I kept reading in the issues closed to use the 'development' branch for now.

I added the following to my Podfile:
**'pod 'Material', :git =>'https://github.com/CosmicMind/Material.git', :branch => 'development'**

I also added the below to meet the requirements of this pod:
**pod 'Motion'**

But for reasons that I do not understand, it throws me an error like the below:

![screen shot 2018-09-23 at 8 06 16 am](https://user-images.githubusercontent.com/42767995/45924420-5dd9d280-bf08-11e8-8991-18ac8e2c1657.png)

Can you enlighten me on what I'm doing wrong?
Thanks.

**Comment by OrkhanAlikhanov** [comment]
Use development branch for Morion as well. 
```ruby
'pod 'Material', :git =>'https://github.com/CosmicMind/Material.git', :branch => 'development'
'pod 'Motion', :git =>'https://github.com/CosmicMind/Motion.git', :branch => 'development'
```

**Comment by johnmikel** [comment]
Thanks @OrkhanAlikhanov. I'll give it a try!

**Comment by johnmikel** [comment]
@OrkhanAlikhanov it worked. Thanks for your help!
