### ISSUE TITLE
rightView is not working

### ISSUE THREAD

**Issue by cuong1112035** [CosmicMind/Material#1163]
I try to add a custom view to rightView, then I set rightViewMode = .always to show my custom right view. But I cannot find a way to show the rightView and every thing works pretty well with leftView. Does anyone know how to fix this?

**Comment by OrkhanAlikhanov** [comment]
Hey! How do you add your custom view to `textField.rightView` ? Can you share some code? A sample project replicating the issue would be welcomed :)

**Comment by cuong1112035** [comment]
```
class ViewController: UIViewController {

    @IBOutlet var textField: TextField!
    let temp = UIView(frame: CGRect.init(x: 0, y: 0, width: 20, height: 20))

    override func viewDidLoad() {
        super.viewDidLoad()

        temp.backgroundColor = .red
        textField.rightView = temp
        textField.rightViewMode = .always
    }
}
```
this is my code

**Comment by OrkhanAlikhanov** [comment]
Thank you, looking at the source code, it seems `rightView` gets resized based on views that are in `rightView.grid`. 
https://github.com/CosmicMind/Material/blob/6dc1048c419d5ed5989852605518b6e3be6ea5db/Sources/iOS/TextField.swift#L612-L621

If you add your custom view to grid, `rightView.grid.views = [temp]`, it should work. However size of the your custom view `temp` will be overridden by grid system.

**Comment by cuong1112035** [comment]
It works, thank so much

**Comment by Ronaldoh1** [comment]
this doesn't really solve the problem of the right view. I have used the suggested solution 

rightView.grid.views = [someView]

the button is floating on the left corner of the screen.

**Comment by markst** [comment]
Not sure if this is related. But rather than create another issue - I'm puzzled as to how I display the clear button constantly rather than when editing. I can't figure out where exactly the logic for it appearing is.

```swift
self.tableField.isClearIconButtonEnabled = true
```

**Comment by majeedyaseen** [comment]
@daniel-jonathan was this issue fixed anyhow or any workaround found ?
@OrkhanAlikhanov ?

**Comment by stevendinggang** [comment]
我收到啦！！！

**Comment by majeedyaseen** [comment]
@stevendinggang 
如何 ？
