### ISSUE TITLE
Why isn't DialogView, Builder & Controller Classes in Master Branch?

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Material#1170]
Are there plans to move these classes from M3 into the Master branch any time soon?

**Comment by OrkhanAlikhanov** [comment]
Absolutely! Probably next week it will be development branch. Thank you!

**Comment by kerem1905** [comment]
what about Editor.swift ? @OrkhanAlikhanov

**Comment by OrkhanAlikhanov** [comment]
@kerem1905 It's already in `development` branch.

**Comment by danieldahan** [comment]
We will be moving everything during this month to the `master` branch, though, we are aiming to pair documentation with it. If you would like to be part of our #opensource Slack channel, send your email to support@cosmicmind.com, and we can answer questions directly and keep you posted. Thank you :)
