### ISSUE TITLE
ErrorTextField doesn't reveal errors after upgrading to swift 4.2

### ISSUE THREAD

**Issue by evagnostic** [CosmicMind/Material#1175]
I have the following code in my app. It used to work fine until the swift 4.2 upgrade. 

```
@IBOutlet weak var usernameTextField: ErrorTextField!

self.usernameTextField.isErrorRevealed = true;
self.usernameTextField.detailLabel.text = "Username or Password is incorrect"
```

I updated Podfile to the following, but it didn't help

```
pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'
pod 'Motion', :git => 'https://github.com/CosmicMind/Motion.git', :branch => 'development'
```

**Comment by OrkhanAlikhanov** [comment]
Hey! See https://github.com/CosmicMind/Material/issues/1131#issuecomment-411734473

**Comment by evagnostic** [comment]
@OrkhanAlikhanov Thanks for your response. Another change I noticed is that neither `detailLabel` or `errorLabel` would show unless the field has been a first responder before. In this case, error only show up when the user clicks into the field. How should I resolve this issue?

**Comment by OrkhanAlikhanov** [comment]
Interesting. How and where do you set text for labels? Can you send a sample reproducing the issue?

**Comment by OrkhanAlikhanov** [comment]
That probably happens since it does not layout errorLabel. You can layout by calling `textField.layoutSubviews()`

I suggest that instead of `textField.errorLabel.text = "blah"` use `textField.error = "blah"`, we internally call `layoutSubviews`

**Comment by evagnostic** [comment]
Thanks so much. It worked! @OrkhanAlikhanov

**Comment by OrkhanAlikhanov** [comment]
Awesome! 

I believe we should call `layoutSubviews` internally when `isErrorRevealed` is set as we were doing before. It was removed in last update, that's why you ran into this issue.

**Comment by OrkhanAlikhanov** [comment]
@evagnostic Check out new validator for ErrorTextField #1082. You can set validation rules and error messages on `errorTextField.validator` and check if they pass using `errorTextField.isValid()`. There is more detailed information in the pr.

Basic example:
```swift
let usernameField = ErrorTextField()
usernameField.placeholder = "Username"
usernameField.validator
  .notEmpty(message: "This field is mandatory")
```

and then
```swift
func didTapSignIn() {
  guard usernameField.isValid() else {
     return // relevant error message is shown automatically.
  }

  // sign user up
} 
```

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov :)
