### ISSUE TITLE
Problem with colors branch development Swift 4.2

### ISSUE THREAD

**Issue by ludivinefafournoux** [CosmicMind/Material#1176]
Hi, i'm using the development branch to use Material in my swift project. I'm updating it to Swift 4.2.
I have a problem with flatbuttons colors: 
![img_d7fec82802d9-1](https://user-images.githubusercontent.com/17699165/47208342-d4de7b80-d38d-11e8-8556-b600dc205047.jpeg)
![img_0048](https://user-images.githubusercontent.com/17699165/47208343-d4de7b80-d38d-11e8-8c20-ceba81ffb4fe.PNG)

When i switch to development branch, i don't have the same colors, and they are set in storyboard. I don't know why they changed.

Thanks

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank you! Most likely it happens due to theming #1115. We'll look into this soon. For now, you can add `Theme.isEnabled = false`  to your `AppDelegate.swift`. It is introduced in #1174. To use it point to that branch. Assuming you are using cocoapods:
```ruby
pod 'Material', :git => 'https://github.com/OrkhanAlikhanov/Material', :branch => 'theme-global-disable'
```

**Comment by ludivinefafournoux** [comment]
Ok, thanks i will test that !

**Comment by danieldahan** [comment]
@ludivinefafournoux the [development](https://github.com/CosmicMind/Material/tree/development) branch now includes the fix to @OrkhanAlikhanov PR. Thank you @OrkhanAlikhanov.
