### ISSUE TITLE
RTL UITextField iOS 12

### ISSUE THREAD

**Issue by pedroOliveiraptc** [CosmicMind/Material#1177]
https://github.com/CosmicMind/Material/issues/1166
> Hey guys congrats for the work.
i am facing a problem since ios12 and the new version that you guys release, my textfield in rtl break alignments as you can see above,
Do you already face this issue ? On iOS 11 and old version of the framework I don't have problems.
Thanks.

Hello sorry for the delay, the link for sample project

https://drive.google.com/file/d/1gl4BQvgH2QvU5FrU0FM3ViHDwUVVr_7U/view

**Comment by danieldahan** [comment]
Hey @pedroOliveiraptc thank you. Let's go to the original issue https://github.com/CosmicMind/Material/issues/1166, so we maintain the correct history.
