### ISSUE TITLE
Visual layer corner radius to clip subviews/layers?

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#1184]
Is it possible to shine some light on the use of visual layer?

I have a cell view with some subviews & a corder radius.
If I apply the below snippet to my cell, it had the desired setup with shadow on the backing layer, clipping the pulse touch & dotted border. 

However my subviews aren't clipped by the rounded corners. 
The only way I can think of doing this is by containing all my subviews in a 'container view'. Though I feel this kind of defeats the idea of the visual layer?

```swift
class BookingCollectionCell: CollectionViewCell {
    
    fileprivate func displayDottedBorder(lineDashPattern:[NSNumber]) {
        self.visualLayer.lineWidth = 1.0
        self.visualLayer.lineDashPattern = lineDashPattern
        self.visualLayer.strokeColor = #colorLiteral(red: 0.7176470588, green: 0.7137254902, blue: 0.737254902, alpha: 1).cgColor
    }
    override func layoutSubviews() {
        super.layoutSubviews()
        
        self.clipsToBounds = false
        
        self.depth = Depth(offset: UIOffset(horizontal: 0, vertical: 6.5), opacity: 0.04, radius: 10)
        self.cornerRadiusPreset = .cornerRadius3
        
        self.visualLayer.cornerRadiusPreset = .cornerRadius3
        self.visualLayer.path = UIBezierPath(roundedRect: self.bounds, cornerRadius: 8).cgPath
        self.visualLayer.frame = self.bounds
        self.visualLayer.fillColor = UIColor.clear.cgColor
    }
```

**Comment by danieldahan** [comment]
@markst Hey! Great question. The `visualLayer` allows a view to contain clipped content without needing to add another container view for shadowing. The parent view's backing layer acts as that container. 

In your code, add the subview's layers to the `visualLayer`, which will clip the radius corners, and allow for your shadow to be displayed.

If you would like to join our `Slack` channel to further discuss send your email to `support@cosmicmind.com`, or you may answer here to keep the history of this issue. Please reopen or create a new issue if you need. Thank you!
