### ISSUE TITLE
NavigationDrawer and TabBar issue?

### ISSUE THREAD

**Issue by hhoangna** [CosmicMind/Material#1189]
I am using NavigationDrawer and UITabBarController in my App. And I want to show TabBar all the time. It's mean when I click to open NavigationDrawer slides in from the left or right, the TabBar always appear in front.
Could someone help me? Thanks

**Comment by OrkhanAlikhanov** [comment]
Hey! You will have to change the hierarchy order. Instead of nesting `UITabBarController` inside `NavigationDrawerController`,  make `UITabBarController` topmost and nest each tab in `NavigationDrawerController`

**Comment by danieldahan** [comment]
@OrkhanAlikhanov thank you that is correct. @hhoangna if you need any further help, please reopen or create a new issue.

**Comment by hhoangna** [comment]
I tried but i don't know how to change the hierarchy. Can someone give me a examples?

**Comment by OrkhanAlikhanov** [comment]
Share the hierarchy here

**Comment by hhoangna** [comment]
@OrkhanAlikhanov Can you create a sample for me?

**Comment by danieldahan** [comment]
@hhoangna take a look at the [Samples](https://github.com/CosmicMind/Samples) repo to start.
