### ISSUE TITLE
`SearchBar` does not honour centre alignment

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#1191]
I am setting my content view alignment to:
```swift
self.searchBar.contentViewAlignment = .center
```
 
But the content is not centred, however if I set the text field alignment to centre:
```swift
self.searchBar.textField.textAlignment = .center
```

The following occurs:

![screen capture on 2018-11-27 at 13-14-57](https://user-images.githubusercontent.com/274318/49053964-80f56b00-f246-11e8-9820-510777b5523b.gif)

Should the search bar not align the text field left view so as to produce the following appearance?

<img width="451" alt="image" src="https://user-images.githubusercontent.com/274318/49054052-e2b5d500-f246-11e8-939a-7b9911c0f31b.png">

**Comment by danieldahan** [comment]
@markst Hey, the `contentViewAlignment` does not belong to the search text, but the search element. It says to keep the centerView aligned in the center relative to the left and right views.
