### ISSUE TITLE
NavigationController backgroundColor resets on tab change

### ISSUE THREAD

**Issue by angelix** [CosmicMind/Material#1193]
On Development branch, when setting the backgroundColor of the NavigationBar::NavigationController and inside the TabsController we change the tab, the backgroundColor of the bar resets to the default blue color.

**Comment by OrkhanAlikhanov** [comment]
This is because of theming #1115. You can disable theming at all by `Theme.isEnabled = false` or disable it for specific instance `navigationBar.isThemingEnabled = false` or all instances `NavigationBar.isThemingEnabled = false`
