### ISSUE TITLE
TabsController tabItem contentEdgeInsets issue

### ISSUE THREAD

**Issue by 22Round** [CosmicMind/Material#1194]
I want to change tabItem position but `contentEdgeInsets` not works

my sample

```
class BlueViewController: UIViewController {
    let v1 = UIView()
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = Color.blue.base
        
        prepareTabItem()
        
        v1.motionIdentifier = "v1"
        v1.backgroundColor = Color.red.base
        view.layout(v1).width(100).height(100).centerX().left()
    }
}

extension BlueViewController {
    fileprivate func prepareTabItem() {
        tabItem.setTabItemImage(Icon.bell, for: .normal)
        tabItem.contentEdgeInsets = EdgeInsets(top: -50, left: 0, bottom: 0, right: 0)
   
    }
}
```

**Comment by danieldahan** [comment]
Hi @22Round, thank you for sharing your issue. Please provide more information on how `contentEdgeInsets` is not working, and what you are trying to do with its positioning. Pictures are very helpful, and more detail is always great. When you have that ready, feel free to send your email to join our Slack channel to support@cosmicmind.com, or reopen this issue. Thank you!

**Comment by 22Round** [comment]
@danieldahan I want archive something like this 
<img width="452" alt="screen shot 2018-12-10 at 12 53 41" src="https://user-images.githubusercontent.com/5682469/49721037-bfdde480-fc7a-11e8-95dd-3a0c77db4f5b.png">

customize middle items Y pos
