### ISSUE TITLE
centerVertically returns an error

### ISSUE THREAD

**Issue by KingOlami** [CosmicMind/Material#1198]
I am trying to center the UIView vertically which works before till I migrated my codes to swift 4.2. now it shows an error when I use this code

`view.layout(searchState).left(10).right(10).centerVertically(offset: 150)`

the error it show is

`Value of type 'Layout' has no member 'centerVertically'`

I do not no why I have this error

**Comment by OrkhanAlikhanov** [comment]
Hey! Sorry for the breaking change. It's now called `centerY`. See #1185 for more details

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov ! @KingOlami If you have any further issues, please reopen or create a new one.
