### ISSUE TITLE
White color turns blue on Pod Update

### ISSUE THREAD

**Issue by KingOlami** [CosmicMind/Material#1199]
Hi, I incorporated material in most of my UI components and I updated my pod to use this 

`pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :commit => '4ab1b08c3365a00f409a210162ae72ed8425f299'` when I run the application, all my white color turns blue and I cannot seem to understand why.

**Comment by KingOlami** [comment]
when I disabled the Theme, the navigation bar color turns black which is supposed to be white

**Comment by KingOlami** [comment]
if I set `Theme.light.primary = .white`, the navigation becomes white and my UIButton colors become white too. while the button is supposed to be black

**Comment by OrkhanAlikhanov** [comment]
> when I disabled the Theme, the navigation bar color turns black which is supposed to be white

Hmm, that's a regression. Before default color was `.white`, currently it's expected to be set by theming.

You can check the removed line:
https://github.com/CosmicMind/Material/pull/1115/files#diff-b2493560b26f2b7a682624a8d8178015L171

**Comment by OrkhanAlikhanov** [comment]
Unfortunately, the best thing is that you disable theming and set white color on navigation bar manually.

**Comment by KingOlami** [comment]
how can I set that globally for material so that it reflects on all my navigation

**Comment by OrkhanAlikhanov** [comment]
`Theme.light.primary = .white` should've done the trick. Which buttons turned into white in buttons navigationItem or others? Did you explicitly set black color on them?

**Comment by KingOlami** [comment]
I had to set the tintcolor of each button. I would work with that now. Thanks
