### ISSUE TITLE
FABMenuItem Label is not customisable

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Material#1201]
I need to be able to change the font and background color of the title label of menu items. Currently the label is hard coded to use Roboto font and a white background. 

If the title label initialisation was overridable then I could subclass it and customize as required.

**Comment by OrkhanAlikhanov** [comment]
Hey! Did you find solution or accidentally closed the issue?

**Comment by muzoman** [comment]
Hi @OrkhanAlikhanov, I closed on purpose - I realised I could simply customise the title label by assigning directly to its properties after the default initialisation.
