### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by dmwesterhoff** [CosmicMind/Material#1203]
http://www.cosmicmind.com/material/icons is in the README, which currently 404s out.

**Comment by danieldahan** [comment]
Thank you for sharing this. We are uploading a completely new README with links in a week. So please bare with us, and this will be fixed soon.

**Comment by metrue** [comment]
Issue still there

**Comment by danieldahan** [comment]
Sorry about the delay for the link. We missed it in our last updates. It will be updated in the next release, that said, the icons can be found in the Icon.swift file, https://github.com/CosmicMind/Material/blob/master/Sources/iOS/Icon/Icon.swift

**Comment by adamdahan** [comment]
@metrue Thank you for giving us the heads up on this: There is an open PR to fix this issue. https://github.com/CosmicMind/Material/pull/1263

**Comment by danieldahan** [comment]
@adamdahan thank you@ and @dmwesterhoff thanks for sharing the issue.
