### ISSUE TITLE
Where can I find the sample of Sticker Sheet?

### ISSUE THREAD

**Issue by hardikamal** [CosmicMind/Material#1208]
Hi,

Firstly, Thanks for the awesome library.

May I know where can I find the sample of Sticker Sheet?

**Comment by danieldahan** [comment]
Thank you @hardikamal 

There is a link at the bottom of the README that takes you here https://www.uplabs.com/posts/material-design-sticker-sheets. 

All the best!

**Comment by hardikamal** [comment]
@danieldahan It's just an adobe illustrator file and no sample code of implementing it. Where can I find the sample code of implementation?

**Comment by danieldahan** [comment]
@hardikamal You mean this https://github.com/CosmicMind/Samples

**Comment by hardikamal** [comment]
@danieldahan There is no sticker sheet sample in the above link

**Comment by danieldahan** [comment]
@hardikamal, what is a sticker sheet sample?

**Comment by hardikamal** [comment]
@danieldahan How do I use the sticker sheet component in my app? I am asking for the code to use it in my app.

**Comment by danieldahan** [comment]
The sticker sheet is used only in illustrator. What specifically are you trying to accomplish?
