### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by universonic** [CosmicMind/Material#1209]
Apple released Xcode 10.2 for Swift 5 support (see [here](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2)). Is there a plan to support Swift 5 in Material?

**Comment by muzoman** [comment]
There's breaking changes in this version of Swift - stringInterpolationSegment parameter label on String constructor no longer exists - compiler says use _cocoaString but using this crashes at runtime, so not sure what the right fix is.

`internal var id: String {
        guard let moc = managedObjectContext else {
            fatalError("[Graph Error: Cannot obtain permanent objectID]")
        }
        
        var result: String?
        moc.performAndWait { [unowned self, unowned moc] in
            do {
                try moc.obtainPermanentIDs(for: [self])
            } catch let e as NSError {
                fatalError("[Graph Error: Cannot obtain permanent objectID - \(e.localizedDescription)]")
            }
            result = String(stringInterpolationSegment: self.nodeClass) + self.type + self.objectID.uriRepresentation().lastPathComponent
        }
        return result!
    }`

**Comment by danieldahan** [comment]
@universonic Hey, good question. We are releasing Swift 4.2 support by pushing `development` to `master`, That will be Material 3.0. Once that is done, we will branch from development 3.1 and support Swift 5. We will continue to support Material 3.0.* from `development`. There may be some revisions to this plan, but this is the general one. Thank you!

**Comment by glennposadas** [comment]
Hey @universonic someone forked Material and Motion, and updated them to Swift 5.0, but Daniel and team have plans, like what he just discussed above. But if you can't wait for Swift 5.0 support like me, I'd like to share my temp solution.

  pod 'Material',
  :git => 'https://github.com/glennposadas/Material.git',
  :commit => '74aeecb'   									# For Material Design

  pod 'Motion',
  :git => 'https://github.com/glennposadas/Motion.git',
  :commit => '6461dda'	    								# Material's dependency.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I would like to setup a release candidate for Swift 4.2 and Swift 5.0 and create candidate branch releases from development, thoughts?

**Comment by OrkhanAlikhanov** [comment]
@danieldahan Would be great. Current development branch is at supports swift 4.2. So, creating `swift-4.2` brach and then updating `development` branch to swift 5 would be enough I think

**Comment by universonic** [comment]
Thanks @glennposadas , I'll try it later.
