### ISSUE TITLE
prepare() is called twice on NavigationDrawerController

### ISSUE THREAD

**Issue by ariantomichael** [CosmicMind/Material#1215]
![Screen Shot 2019-04-08 at 16 03 46](https://user-images.githubusercontent.com/25115350/55704804-16381580-5a18-11e9-9bac-99d94f91976e.png)

As you see from the screen shot, prepare() is called twice. Fix please :)
Thank you

**Comment by danieldahan** [comment]
@ariantomichael Thank you for sharing this. How are you initializing the navigation controller and what version of Material are you using?

**Comment by ariantomichael** [comment]
@danieldahan Sorry for the late reply. I initialize the nav controller like this.
![Screen Shot 2019-05-17 at 12 36 41](https://user-images.githubusercontent.com/25115350/57901596-ca8f4c00-78a0-11e9-99c2-3ed5ac9d7af6.png)
And I'm using :
- Material (2.16.4):
    - Material/Core (= 2.16.4)
  - Material/Core (2.16.4):
    - Motion (~> 1.4.3)
  - Motion (1.4.3):
    - Motion/Core (= 1.4.3)
  - Motion/Core (1.4.3)
Thank you :)

**Comment by danieldahan** [comment]
@ariantomichael thank you! We will look into this today.

**Comment by OrkhanAlikhanov** [comment]
Should be fixed by #1240

**Comment by danieldahan** [comment]
@ariantomichael thank you for bringing this issue to our attention and @OrkhanAlikhanov thank you for the fix. It is now available in https://github.com/CosmicMind/Material/releases/tag/3.1.4.
