### ISSUE TITLE
TextField with Storyboard

### ISSUE THREAD

**Issue by av089** [CosmicMind/Material#1217]
Hello,

I didn't find any example of Textfield or ErrorTextField with storyboard.
Can you please provide me ?

Also, If I want to set textfield in storyboard then what will be the height for that?

Thank you,

**Comment by OrkhanAlikhanov** [comment]
1. Just add a `UITextField` into your storyboard and set its class to `TextField` or `ErrorTextField` under `Identity Inspector` pane. 
2. Just set width, there is no need to set height, it is autoresized to depending on font

**Comment by danieldahan** [comment]
Thanks for the answer @OrkhanAlikhanov and good question @av089 :) I am closing this for now, and if you need any further help, please reopen or create a new issue.

**Comment by av089** [comment]
Hello @OrkhanAlikhanov 

I did the same, but when I try to enter input then placeholder is gone too much above the textfield & I can not able to see it.

Thank you,

**Comment by OrkhanAlikhanov** [comment]
You've probably a height or top-bottom constraint on your textfield

**Comment by silnose** [comment]
Are there some similar example like [this one ](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/TextField/TextField/ViewController.swift) to aplied validations in storyboard? . Currently I can't figure out how :(.

**Comment by danieldahan** [comment]
@silnose are you looking to validate something in particular, or looking for a general strategy?

**Comment by silnose** [comment]
A general strategy wold be good. But i find the solution. I set the ErrorTextField in the swift file but never in the identity inspector 🤦‍♀  so all the time I get an error all the time. 

If it helps this was my solution

**In the storyboard:**

<img width="268" alt="Screen Shot 2019-05-30 at 10 57 52" src="https://user-images.githubusercontent.com/10604773/58638508-62426080-82cb-11e9-8716-93f3a524d956.png">

<img width="265" alt="Screen Shot 2019-05-30 at 10 58 11" src="https://user-images.githubusercontent.com/10604773/58638510-653d5100-82cb-11e9-8370-53d1736dd8d4.png">

**In the swift code:**
`import Foundation
import Material

class ProfileViewImpl: UIViewController, ProfileView {
    
    var presenter: ProfileViewPresenter!
    var profileViewModel: ProfileViewModel!
    open var isViewPresented = false
    @IBOutlet weak var firstNameTextField: ErrorTextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.presenter = ProfilePresenterImpl<ProfileViewImpl>(view: self)
        self.prepareTextFieldPlaceholder()
        self.prepareTextFieldData()
        self.prepareTextFieldRules()
    }


    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    func validate() { //TODO call in the save button
        let isAllValid = [self.firstNameTextField].reduce(true) { $1.isValid() && $0
        }
        guard isAllValid else { return }
    }
}
extension ProfileViewImpl {
    fileprivate func prepareTextFieldPlaceholder() {
        self.firstNameTextField.placeholder = NSLocalizedString(Constants.firstNameString, comment: "")
    }
    fileprivate func prepareTextFieldData() {
        self.firstNameTextField.text = 
    }
    fileprivate func prepareTextFieldRules() {
        self.firstNameTextField.validator.notEmpty(message: NSLocalizedString(Constants.mandatoryField, comment: ""))
       
    }
}
}`

**Comment by OrkhanAlikhanov** [comment]
What is the error you are getting? Note that there is no way to use `ErrorTextField.validator` except in code. Your code looks perfectly fine.
