### ISSUE TITLE
lower title/text for tab bar items used by a bottom navigation controller

### ISSUE THREAD

**Issue by michaeldebo** [CosmicMind/Material#1218]
The way to lower the text/title associated with tab bar items used in regular iOS does not work when using Material's bottom navigation controller. How does one lower the text of tab bar items used by Material's bottom navigation controller?

**Comment by OrkhanAlikhanov** [comment]
The insets you set are overriden in [`layoutSubviews`](https://github.com/CosmicMind/Material/blob/22462d97138b05e3563b026c418bc924a037de7f/Sources/iOS/BottomTabBar/BottomNavigationController.swift#L129-L154) method of `BottomNavigationController`.

As a workaround subclass `BottomNavigationController` override `layoutSubviews` method but do not call it on `super`.
```swift
class MyBottomNavigationController: BottomNavigationController {
  override func layoutSubviews() {
    tabBar. layoutDivider()
  }
}
```

@danieldahan I think it's better to remove [these lines](https://github.com/CosmicMind/Material/blob/development/Sources/iOS/BottomTabBar/BottomNavigationController.swift#L130-L151) as they are rather specific for users' need.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I agree :) Would you like to PR that?

**Comment by OrkhanAlikhanov** [comment]
Did that, see #1222

**Comment by danieldahan** [comment]
@OrkhanAlikhanov awesome! Thank you.
