### ISSUE TITLE
Support all relations for Layout constraints

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#1220]
Asked by @leedsalex in https://github.com/CosmicMind/Material/commit/3742fdc010685f78e2fc707c45e009fc34332f
> Any plans to support <=, <, >, >= in the Material layout constraint system. Currently, all relations are equal to..

**Comment by leedsalex** [comment]
@OrkhanAlikhanov Thank you for making the ticket

**Comment by 22Round** [comment]
@OrkhanAlikhanov @danieldahan guys any plans to support this in near future ?

**Comment by OrkhanAlikhanov** [comment]
Hey @22Round, @leedsalex this feature is implemented in #1220! Check it out!

If you have questions or other suggestions, feel free :)

**Comment by danieldahan** [comment]
@OrkhanAlikhanov nicely done :)

**Comment by OrkhanAlikhanov** [comment]
@22Round Did you try the PR? Does it work for you?

**Comment by danieldahan** [comment]
Please find this new feature in https://github.com/CosmicMind/Material/releases/tag/3.1.3, thank you! :)

**Comment by 22Round** [comment]
@OrkhanAlikhanov will try soon, thanks nice feature.
