### ISSUE TITLE
Broken Install link on README

### ISSUE THREAD

**Issue by vizulefllry** [CosmicMind/Material#1224]
Deciding if we will use CosmicMind or Material for iOS (google), and cannot install CosmicMind because the tutorial links are dead.
https://www.cosmicmind.com/danieldahan/lesson/6
tried:
https://www.cosmicmind.com/lesson/6
https://www.cosmicmind.com/lesson/

**Comment by danieldahan** [comment]
We are updating our server setup, I’ll fix this up. Sorry about that.

**Comment by vizulefllry** [comment]
Any chance these are on YouTube or some other site?

**Comment by danieldahan** [comment]
Whichever you choose to use, CM or Google components... note that our documentation centre is launching in May as a continuous rollout. All the best!

**Comment by vizulefllry** [comment]
> Yeah, I can make a more robust tutorial for you, and better to ask, are you planning to embed the framework, use CocoaPods, or Carthage, etc... ?

We got it up and running for xcode10.1. Now working on getting it running on xcode10.2 because the lead dev wants to use Swift 5.
Thanks or the replies.

**Comment by danieldahan** [comment]
Hey! Please find Swift 5 support in master and installation instructions. Sorry for the delay. Thank you!
