### ISSUE TITLE
Updated Material Design Spec?

### ISSUE THREAD

**Issue by jstngoulet** [CosmicMind/Material#1225]
This library looks awesome! 

Before integrating it, however, I was curious if there are any plans to update to the newest Material Design Standards. For example, the text fields match the old Material Design Style, not the [new](https://material.io/design/components/text-fields.html#usage) ones.

**Comment by danieldahan** [comment]
HI @jstngoulet thanks for the question and comment :) We have been working on a new platform and updates to the frameworks for the past couple years and it is soon to release. The soft date is June 1st and the official date is July 1st. That said, we will be then making all the updates to support new concepts by us, Apple, and the Material Design Spec. We are also releasing some really powerful new technologies that will integrate with Material and our other frameworks. So in short, yes we will be updating.
