### ISSUE TITLE
dismiss navigation drawer 

### ISSUE THREAD

**Issue by michaeldebo** [CosmicMind/Material#1228]
I can't find where in the documentation it states how to close the navigation drawer programmatically. I have made the slide out drawer a tableview with each cell being a button that is supposed to close the navigation drawer and bring the user to the desired screen. What code do I write to close the left view controller?

**Comment by OrkhanAlikhanov** [comment]
Try something like this:

```swift
let navVC = self as? NavigationDrawerController ?? self.navigationDrawerController
navVC?.closeLeftView()
```

**Comment by michaeldebo** [comment]
Thanks. That works. Is it possible to keep the navigation drawer as part of the navigation controller so I can then push or pop? Am I forced to use "present" to go to a new view controller?

**Comment by danieldahan** [comment]
@michaeldebo I am not sure I understand your second question, *Is it possible to keep the navigation drawer as part of the navigation controller so I can then push or pop?*. 

If I understand correctly, I think you mean from the `NavigationDrawerController`, you would like to be able to call the `NavigationController` push and pop methods. If that is the case, every view controller has access to optional helper properties that access the related navigational controller. So in this case, from the NavigationDrawerController, you can call the NavigationController's pop method by doing this...

```swift
//... in some function call
navigationController?.pushViewController(...)
```

If the `navigationController` exists, the call will be made from the `navigationDrawerController`.
