### ISSUE TITLE
tint color for Textfields

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#1229]
Hi,

Material 3.x introduces a bug where the tint color of a text field will be ignored completely, because, you are changing it based on placeholder's colors (Active/Normal) in the process. It has consequences for someone who doesn't have a placeholder and want to set the tint color.

I guess the tint color explicitly set by user should override such behavior.

For now, the workaround is to set both `placeholderActiveColor` and `placeholderNormalColor` to your desired color to achieve a simple `tintColor`!

**Update**:
I guess this is not new and has been a case since Material 2 (at least)

**Comment by OrkhanAlikhanov** [comment]
We forceable update `tintColor` to a single value `placeholderActiveColor`.

https://github.com/CosmicMind/Material/blob/3e2637838e446e8a2bfc550129bf5766e7f88af4/Sources/iOS/Text/TextField.swift#L535-L538
I think we can set it once in `didSet` of `placeholderActiveColor`.

@danieldahan What do you think worth updating?

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I think @mohpor's point is a really good one. Maybe we only need to update both values like @mohpor mentioned when a user sets the `tintColor`. We still do want to use the placeholder(Active/Normal)Color functionality. Thoughts?
