### ISSUE TITLE
Layout breaks view arrangements

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#1232]
Hi,

In Material 2.x when we used Layout, we considered the child as free and the layout function would add it to the parent, and it is done through `addSubview`, there were cases that this was not the desired effect, for example when I add a blur view in my code, I want it to be at the bottom, so, first I would've inserted the child at 0, and then lay it out:

```swift
parent.insertSubview(child, at: 0)
parent.layout(child).edges()
```

Material 3 breaks this simple rule and adds the child to super view, without checking to see if the child already has a parent, and therefore breaks the arrangement the developer might have desired.

There is workaround for this, you can simply arrange the view afterwards, but now I have to look for every instance I've done it! This is a breaking change.

>P.S.: I did the Material 2's Layout, although it has been erased from git's history due to restructuring.

**Comment by mohpor** [comment]
This is a serious problem.
 I'm sure many developers would see views that has been laid out using `Layout` out of order, without being able to detect why this is happening!

**Comment by OrkhanAlikhanov** [comment]
So the problem is that order of inserted view changes? The reason might be we don't check if the view is already child. 

https://github.com/CosmicMind/Material/blob/3677b2688e0e43d8cbc76666313c7867327ec3c8/Sources/iOS/Layout/Layout.swift#L43-47

**Comment by mohpor** [comment]
Exactly, 
In the previous versions, in the layout function, we added the subview ONLY if the parent was missing!

**Comment by OrkhanAlikhanov** [comment]
I submitted PR for this. Thank you for reporting :muscle:

**Comment by OrkhanAlikhanov** [comment]
Btw, you could workaround it by:
```swift
parent.insertSubview(child, at: 0)
child.translatesAutoresizingMaskIntoConstraints = false
parent.layout.edges()
```
:)

**Comment by danieldahan** [comment]
@mohpor please find your fix here: https://github.com/CosmicMind/Material/releases/tag/3.1.2, thank you @OrkhanAlikhanov :)
