### ISSUE TITLE
Regarding Shadow Effect

### ISSUE THREAD

**Issue by avagh** [CosmicMind/Material#1234]
i am not getting any shadow after updating the latest version of Material (3.1.2). My older version was (2.9.4) even if i have tried in (2.16.4 +) versions but i am getting same issue like i am not getting shadow effect in any of my buttons and other stuff. Note that in my older version (2.9.4) shadow effects work perfectly but now i need to convert my project to latest version of swift code. in that older version (2.9.4) is no longer supported swift 4.2. so, please resolve this issue as soon as possible.

**Comment by OrkhanAlikhanov** [comment]
Hey! Before resolving the issue as soon as possible, we first need to confirm that this is an issue on our side. Can you please share some code showing how you set shadow effect?

**Comment by avagh** [comment]
Here is my code and these same parameters i am setting in runtime attributes in Interface builder.

> stackBaseView = [[UIView alloc] initWithFrame:CGRectMake(20, frame.size.height-(IS_IPHONE_X ? 45 : 60), frame.size.width-40, 40)];
>     stackBaseView.backgroundColor = [UIColor clearColor];
>     stackBaseView.layer.shadowColor = [UIColor blackColor].CGColor;
>     stackBaseView.layer.masksToBounds = NO;
>     stackBaseView.layer.shadowOffset = CGSizeMake(0, 0);
>     stackBaseView.layer.shadowRadius = 3;
>     stackBaseView.layer.shadowOpacity = 0.12;

**Comment by OrkhanAlikhanov** [comment]
How is this related to `Material` library?

**Comment by codal-hardik** [comment]
This is working fine before updating the library to latest version but once it is updated. We are not getting any shadow on button, view, textview anything.

**Comment by OrkhanAlikhanov** [comment]
@codal-hardik and @avagh Do you both talk about same project or @codal-hardik you are experiencing the same thing in a different project? 

@avagh Do you set shadow using code or through storyboards?

**Comment by codal-hardik** [comment]
Yes i am talking about the same project as @avagh talking.

**Comment by codal-hardik** [comment]
@OrkhanAlikhanov Yes from the storyboard we are setting the shadow.

**Comment by avagh** [comment]
@OrkhanAlikhanov this issue seems related to the view layer so, this issue was not from your end. we have resolved this from our end.
