### ISSUE TITLE
TabsController iPad

### ISSUE THREAD

**Issue by karasahinemre** [CosmicMind/Material#1235]
When using tabs controller on iPad and controller position is set as top, it creates a gap between Large Navigation Controller and tab items.

**Comment by OrkhanAlikhanov** [comment]
Hey! Large Title is not supported in Navigation Controller yet. That said, in #1158 we had helped you regarding that. Now, can you please at least show us a screenshot so that we can see what you see?

**Comment by karasahinemre** [comment]
Sure, You can find the image from below.

Thank you for your attention.

<img width="768" alt="Unknown" src="https://user-images.githubusercontent.com/9135318/58174490-bc796b00-7ca6-11e9-94eb-d87bb75b3c29.png">

**Comment by OrkhanAlikhanov** [comment]
If you are using the same code snippet I shared in #1158, then you are using a constant value of `96` to  calculate additional inset. That `96` (which is default height of collapsed navigation bar I believe) should be a different number for iPad. In fact, it can be different number for each device as well as orientation. I can't think of any dynamic way of calculating that `96` right now.

**Comment by danieldahan** [comment]
@karasahinemre if you need any further help, please reopen or create a new issue. Thank you!
