### ISSUE TITLE
ErrorTextField Cursor Color

### ISSUE THREAD

**Issue by 22Round** [CosmicMind/Material#1238]
How can I change `ErrorTextField` blinking cursor color? when I change `placeholderActiveColor` it changes, but I want different color for cursor.
Any thoughts?

**Comment by OrkhanAlikhanov** [comment]
Set `placeholderActiveColor` then set `tintColor`. Make sure you use latest version of Material. I think it's version 3.1.1

**Comment by 22Round** [comment]
@OrkhanAlikhanov works grate, thanks
