### ISSUE TITLE
transition(to: UIViewController) does not complete if called twice serially.

### ISSUE THREAD

**Issue by MarkBorazio** [CosmicMind/Material#1241]
There is an issue with multiple calls to `transition(to: UIViewController,  completion: ((Bool) -> Void)?)`, where **if the second call is made immediately after the first call's completion handler completes** then the first view controller does not dismiss itself. The debug view hierarchy shows that both destination view controllers are placed on top of each other. The top-most view controller also has user interaction disabled, effectively rendering the app unusable.

I can see that the second call is not having is completion handler being called. The issue is that `MotionTransition.shared.isTransitioning` is still true when the second call is being executed, and ultimately, `MotionTransition.transition(...)` is guarding against this and not calling it's own completion handler as a result.

Here is how we are calling the function:
```
NotificationCenter.default.rx.notification(.routingRequested)
    .observeOn(MainScheduler.instance)
    .concatMap { [unowned self] _ -> Observable<()> in
        Observable.create { observer in
            let route = AppState.shared.selectedRoute
            Logger.log(level: .info, topic: .appState, message: "Changing route to: \(route)")
            self.closeLeftView()
            self.isLeftViewEnabled = route.hasSideMenu
            let viewController = UIStoryboard(named: route.storyboardName).instantiateInitialViewController()!
            let navigationController = CommonNavigationController(rootViewController: viewController)
            self.dismiss(animated: true)
            self.transition(to: navigationController) { _ in
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }
    .subscribe()
    .disposed(by: disposeBag)
```

For context: We are using RxSwift to observe notification calls and routing to the new viewController. The use of `concatMap` is ensuring that these calls are being made serially, with the completion handler of the `transition(...)` function being used to determine that the block has completed.

**Comment by MarkBorazio** [comment]
For added context, we are doing this in a `NavigationDrawerController`.

**Comment by OrkhanAlikhanov** [comment]
What is `self.dismiss(animated: true)` doing?

>The issue is that `MotionTransition.shared.isTransitioning` is still true when the second call is being executed, and ultimately, `MotionTransition.transition(...)` is guarding against this and not calling its own completion handler as a result.

Why do you think it's an issue? Why would you need 2 transitions at the same time?

**Comment by MarkBorazio** [comment]
Our app uses bluetooth, and there are times when the pairing credentials can be cleared from the device that the app is connected to, effectively rendering the app unusable until the user pairs again. In this case we detect this and boot the user back to the bluetooth setup screen.

> What is self.dismiss(animated: true) doing?
There will be times when we want to route to the bluetooth setup screen but we have a modal presented at that time. In this case, if we do not call `self.dismiss(animated: true)` then the modal stays on the screen even after the transition finishes.


> Why do you think it's an issue? Why would you need 2 transitions at the same time?
Due to routing being affected state of the bluetooth connection, there are edge cases where two routing calls can be made very close to each other from different parts of the app.

**Comment by danieldahan** [comment]
Wouldn't we only need a cancel transition method to set the state back to the default values, or last values? I don't agree that we should handle multiple transition blocks in a call because of this use case. This sounds like a routing problem really. I would suggest approaching the fix from there, possibly using a cancel call for the transition if needed, or creating a smoother modal removal when this edge case occurs. I am open to more ideas, but for now, I don't see that making a change in Material/Motion will result in the best solution for this issue. Please reopen or create a new issue if you would like more help from us. Sorry if this didn't solve much for you, and we are here to help. Thank you!

**Comment by OrkhanAlikhanov** [comment]
Sorry for late response @MarkBorazio. I agree with @danieldahan. You should make transition **after dismissal animation** is complete:
```swift
let isBluetoothModalPresented = self.presentedViewController != nil

let finishTranstion: () -> Void = {
  self.transition(to: navigationController) { _ in
    observer.onCompleted()
  }
}

if isBluetoothModalPresented {
  self.dismiss(animated: true, completion: finishTranstion)
} else {
  finishTranstion()
}
```
