### ISSUE TITLE
TabsController RTL support

### ISSUE THREAD

**Issue by Kaakati** [CosmicMind/Material#1243]
Hello @danieldahan & @OrkhanAlikhanov 

I've been building an Arabic app, and I'm currently using the TabBar, I looked up into the TabsController and didn't find a way for RTL direction, so I did a work around with:

```
tabBar.scrollView.transform = CGAffineTransform(rotationAngle: CGFloat(Double.pi))
tabBar.scrollView.subviews.forEach { (view) in
    view.transform = CGAffineTransform(rotationAngle: CGFloat(Double.pi))
}
```

My only issue remained with the transition of the scrollView subviews, I tried to use the delegate but it didn't work.
`tabsController(tabsController: TabsController, didSelect viewController: UIViewController)`

Currently i'm only have to use .fade animation since it doesn't look weird.
Also the tabBar items text color is not changing.

And thanks for the awesome library, great efforts indeed.

Edited:
I've was able to achieve the animation as I wanted after I implemented the TabBarDelegate:

```
func tabBar(tabBar: TabBar, didSelect tabItem: TabItem) {
        let index = tabBar.tabItems.firstIndex(of: tabItem)
        switch index {
        case 0:
            self.motionTransitionType = .slide(direction: .right)
        default:
            self.motionTransitionType = .slide(direction: .left)
        }
    }
```

**Comment by danieldahan** [comment]
Hi, @Kaakati How are you? I am happy you are enjoying the frameworks :) To better help you with the scroll view issue, can you send a project or video of the issue and we can recommend a solution from there. The approach of using `motionTransitionType` is the correct approach for updating the transition animation. Well done.

**Comment by Kaakati** [comment]
Hello @danieldahan 

Thanks for your prompt reply, I'm sorry for not being able to share something, I currently resolved it with this two tabs solution, the main issue is in `setAnimationForNextTransition` I can not have access to it, otherwise it would've solved a problem where there would be more than 2 tabs.

I usually relay on AutoLayout `leading` & `trailing` but in this case I can not.

but here is my class
```

class AppTabsController: TabsController, TabsControllerDelegate, TabBarDelegate {
    
    var oldIndex = 0
    var newIndex = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tabBar.lineAlignment = .bottom
        tabBarAlignment = .top
        tabBar.isDividerHidden = true
        
        tabBar.tabItems = [
            TabItem(title: "homeView.mapView".localized),
            TabItem(title: "view 2".localized),
            TabItem(title: "view 3".localized),
            TabItem(title: "homeView.nearBy".localized, titleColor: .red)]
        
        tabBar.delegate = self
        
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        //  Localizable
        //  Created by Roman Sorochak <roman.sorochak@gmail.com> on 6/23/17.
        if Language.language == .arabic {
            print("UIApplication is RTL")
            tabBar.lineAlignment = .top
            tabBar.scrollView.transform = CGAffineTransform(rotationAngle: CGFloat(Double.pi))
            tabBar.scrollView.subviews.forEach { (view) in
                view.transform = CGAffineTransform(rotationAngle: CGFloat(Double.pi))
            }
            self.motionTransitionType = .slide(direction: .right)
        }
    }
    
    func tabBar(tabBar: TabBar, didSelect tabItem: TabItem) {
        
//        if newIndex < oldIndex {
//            self.motionTransitionType = .slide(direction: .right)
//        } else {
//            self.motionTransitionType = .slide(direction: .left)
//        }
//        print("Old Index \(oldIndex)")
        
        if Language.language == .arabic {
            let index = tabBar.tabItems.firstIndex(of: tabItem)
            switch index {
            case 0:
                self.motionTransitionType = .slide(direction: .right)
                
            default:
                self.motionTransitionType = .slide(direction: .left)
            }
        }
        
    }
    
    func tabBar(tabBar: TabBar, willSelect tabItem: TabItem) {
//        oldIndex = tabBar.tabItems.firstIndex(of: tabBar.selectedTabItem!)!
//        newIndex = tabBar.tabItems.firstIndex(of: tabItem)!
//        print("Old Index \(oldIndex)")
//        print("New Index \(newIndex)")
        let generator = UIImpactFeedbackGenerator(style: .medium)
        generator.impactOccurred()
        //            if self.newIndex > self.oldIndex {
        //                print("Transition Right")
        //                self.motionTransitionType = .slide(direction: .right)
        //            } else {
        //                print("Transition Left")
        //                self.motionTransitionType = .slide(direction: .left)
        //            }
    }
}

```

**Comment by danieldahan** [comment]
What version of Material and Motion are you using? Because `setAnimationForNextTransition` is public.

**Comment by Kaakati** [comment]
I'm using 

  - Material (2.16.4):
  - Motion (~> 1.4.3)

**Comment by danieldahan** [comment]
Hmmm... I have to double check the code to see if `setAnimationForNextTransition` was public then. Otherwise, if you don't mind Swift 5, I would update to the latest across the board. We added many Layout features and updates across the board. @OrkhanAlikhanov knows more of the details on that, so let's tie him into this conversation.

**Comment by Kaakati** [comment]
@danieldahan Not at all, I'm actually working on Swift 5.

Thanks a lot and I really appreciate your support, have a great day/evening. :)

**Comment by danieldahan** [comment]
@Kaakati Thank you :) I am going to close this issue for now, and if you find an issue with the latest releases, please reopen or create a new issue.
