### ISSUE TITLE
Switch: toggle completion not call

### ISSUE THREAD

**Issue by linhCrystal** [CosmicMind/Material#1245]
In func toggle have `isTriggeredByUserInteraction: false, completion: completion`.
But completion not trigger because `isTriggeredByUserInteraction = false`

**Comment by OrkhanAlikhanov** [comment]
Hey! Yes, that's by design. What are you trying to achieve?

**Comment by linhCrystal** [comment]
@OrkhanAlikhanov completion in `func toggle` will be useless if it's never trigger.
Should have move `completion?(s)` to before `guard isTriggeredByUserInteraction else` in `func updateSwitchState`.

**Comment by OrkhanAlikhanov** [comment]
Lol, yeah. That's absolutely right. Will fix that.

**Comment by danieldahan** [comment]
@linhCrystal I will be fixing this tonight, thank you!

**Comment by danieldahan** [comment]
@linhCrystal please find a fix in [Material 3.1.6](https://github.com/CosmicMind/Material/releases/tag/3.1.6). Thank you!
