### ISSUE TITLE
Is there any way to achieve this with ErrorTextField

### ISSUE THREAD

**Issue by silnose** [CosmicMind/Material#1249]
Use  placeholderLabel with one text on the top 
Use placeholder inside the textField with different text.

![image](https://user-images.githubusercontent.com/10604773/60269774-7b87fe00-98c5-11e9-9d61-11dfe801ebf3.png)

Thank in advance! ;)

**Comment by danieldahan** [comment]
@silnose Hey! There isn't out of the box. You can subclass the ErrorTextField class and then add the UILabel and show it when the component is active. Let me know how it goes, and I would be happy to help further if you show me an initial approach.

**Comment by silnose** [comment]
Thk for the early response @danieldahan !. 

I can do the thick following this steps: 
1. Set attribute 'isPlaceholderAnimated' to false: 
`textField.isPlaceholderAnimated = false`
2. Set property  attributedPlaceholder
```
 textField.attributedPlaceholder = NSAttributedString(string:"my real placeholder",
                                                   attributes: [NSAttributedString.Key.foregroundColor: UIColor(named: "cloudy_blue"
```

and magic happens!. The first one is acting like a label and the second one as a placeholder.

**Comment by danieldahan** [comment]
Nicely done! And no added elements :)
