### ISSUE TITLE
Support New Materials Design

### ISSUE THREAD

**Issue by 22Round** [CosmicMind/Material#1251]
@danieldahan @OrkhanAlikhanov do you plan to support new material design?

[Material.io](https://material.io/develop/ios/components/)

**Comment by danieldahan** [comment]
Hi @22Round, the short answer is yes. We are wrapping up a long running project this month, and then will be back to the frameworks, where we plan to release documentation and make major updates to support general design and development, as well as specific ones like Material Design. 

Material is evolving to en entirely new and modern framework, without causing much difficulty for current users. If anything, there is so much in Material that users don't know about, and we want to start sharing so users can take advantage of it. As well, during the time of Material, the concepts have changed, and we will make sure to support those changes.

**Comment by 22Round** [comment]
@danieldahan perfect, waiting.

**Comment by adamdahan** [comment]
@22Round 👍 Closing this ticket - will make sure to let everyone know when the new updates arrive!
