### ISSUE TITLE
hi textview placeholder position

### ISSUE THREAD

**Issue by nodle-J** [CosmicMind/Material#1256]
I try to  add textview in view 
![7CFB6591-888E-4944-BC45-D817020B0A88](https://user-images.githubusercontent.com/9136682/63479611-82944c80-c4c1-11e9-8f15-707958666d21.png)

**Comment by danieldahan** [comment]
Hi, please add more details, code, and the actual problem you are facing. Thank you! We would be happy to help when we have that information. Until, I will close this issue.

**Comment by nodle-J** [comment]
my code 


let textview1 =  TextView()
textview1.placeholder = "请输入原因"
textview1 font = UIFont.systemFont(ofSize: 14)
self.addSubview(textview1)


override func layoutSubviews() {
        super.layoutSubviews()
        
        textView.frame = bounds
        
    }




In TextView ,I fond this code
The height of the placeorder lable  minimumTextHeight = 35


h = max(h, minimumTextHeight)
h = min(h, bounds.height - insets.top - insets.bottom)


by  minimumTextHeight 










在 2019-08-24 21:14:40，"Daniel Jonathan" <notifications@github.com> 写道：


Closed #1256.

**Comment by adamdahan** [comment]
@nodle-J @danieldahan I see the issue..

<img width="679" alt="Screen Shot 2019-09-08 at 8 34 14 AM" src="https://user-images.githubusercontent.com/1205894/64488231-9525ba00-d213-11e9-9878-1de7aab8458d.png">

**Comment by adamdahan** [comment]
@nodle-J thank you for your patience - I will keep this ticket up until we have a fix. 👍

**Comment by OrkhanAlikhanov** [comment]
@adamdahan is this happening only when we have Chinese characters?

**Comment by adamdahan** [comment]
@OrkhanAlikhanov So far, yes.

**Comment by nodle-J** [comment]
It is Font less than 17 ,I think
 In TextView  
func layoutPlaceholderLabel() 
    var h = placeholderLabel.sizeThatFits(CGSize(width: w, height: .greatestFiniteMagnitude)).height
    h = max(h, minimumTextHeight)
    h = min(h, bounds.height - insets.top - insets.bottom)
    placeholderLabel.frame = CGRect(x: leftPadding, y: insets.top, width: w, height: h)
  
I don't understand  h，  I set font less than 17 but  minimumTextHeight is constant 。

I canceled this code . 

  h = max(h, minimumTextHeight)
  h = min(h, bounds.height - insets.top - insets.bottom)

Its all right

I have just learned swift
if I am wrong,please forgive me

thanks

**Comment by adamdahan** [comment]
@nodle-J I have confirmed that this does indeed solve the issue with no reprocussions. Would you like to submit a pull request that removes lines 425 & 426 from TextView.swift?

**Comment by adamdahan** [comment]
@nodle-J We have started an internal conversation to re-write this component. For now a simple fix would be to set the 
```
Line 326.
  internal let minimumTextHeight: CGFloat = 0
```
For your specific use case. 

We will push a fix soon that's more appropriate for everyone!

Thank you for submitting this issue and getting us to notice :)

**Comment by danieldahan** [comment]
Linking the task issue: https://github.com/CosmicMind/Material/issues/1264

**Comment by nodle-J** [comment]
I'd love to.
Thank you very much










At 2019-09-10 21:26:08, "Adam Dahan" <notifications@github.com> wrote:


@nodle-J I have confirmed that this does indeed solve the issue with no reprocussions. Would you like to submit a pull request that removes lines 425 & 426 from TextView.swift?
