### ISSUE TITLE
Change TextField Spacing

### ISSUE THREAD

**Issue by julianpomper** [CosmicMind/Material#126]
Is it possible to change the space between the TextField and the titleLabel or detailLabel?

**Comment by sohayb** [comment]
I think the spacing is based on the material design guidelines and specs, thus it shouldn't be changed (I think it can't be changed on Android as well) [check the design spec](https://www.google.com/design/spec/components/text-fields.html#text-fields-labels)

**Comment by julianpomper** [comment]
Yeah I know, but since the spacing changed, the titleLabels overlap with other TextFields

**Comment by danieldahan** [comment]
Hi @julianpomper, yes you may change the value. For example:

```swift
textField.titleLabelAnimationDistance = 16
textField.detailLabelAnimationDistance = 16
```

I am going to double check the guidelines. It should be a space of 16 between the text and bottom of titleLabel.
