### ISSUE TITLE
[Auto Layout] - How to set constraints relative to a view except parent view?

### ISSUE THREAD

**Issue by samma89** [CosmicMind/Material#1260]
Hi @all,

I am trying to create a huge form with multiple types of input fields. What I am trying to achieve here is to place all the inputs vertically one after another. 

![Untitled-1](https://user-images.githubusercontent.com/2077773/63988091-403dc180-caf8-11e9-80f5-16839009e3f1.jpg)

it seems there is a way like below. but didn't work out for me properly.
Please help!

```
        let tf = TextField()
        tf.placeholder = "Category Name"
        tf.clearButtonMode = .whileEditing
        
        let tf2 = TextField()
        tf2.placeholder = "Category Description"
        tf2.clearButtonMode = .whileEditing
        
        mainView.formContainer.layout(tf)
            .centerX()
            .leftRight(left: 30, right: 30)
            .top(20)
        
        mainView.formContainer.layout(tf2)
            .centerX()
            .leftRight(left: 30, right: 30)
            .top(tf2, 10)
```

Thank you

**Comment by samma89** [comment]
Hi,

I think I figured out after small dive into your source. 

I should be using LayoutAnchor implementation of the view as `view.anchor` yeah?

if yes, let's close this. 

Thank you guys!

**Comment by OrkhanAlikhanov** [comment]
Hey! So, you want to position the `top` of t2 to the `bottom` of t1.

Instead of `.top(tf2, 10)` you can use `.below(tf2, 10)`, or `.top(tf2.anchor.bottom, 10)` both are the same

**Comment by danieldahan** [comment]
Thank you @OrkhanAlikhanov for helping out with this issue. @samma89 if you have any further issues or need any help, please reopen or create a new issue. Thank you!
