### ISSUE TITLE
How to animate placeholder in textfield?

### ISSUE THREAD

**Issue by KiranYechuri** [CosmicMind/Material#1261]
I am trying to animate placeholder but I am unable to do it? can u show me piece of code related to textfield placeholder animation.

**Comment by danieldahan** [comment]
@KiranYechuri The placeholder should animate to a title over the textfield area. What kind of animation are you trying to do?

**Comment by KiranYechuri** [comment]
Same animation that you have showed in GitHub how to achieve that animation?

**Comment by danieldahan** [comment]
The TextField has the animation by default, so is it broken or are you trying to replicate it?

**Comment by KiranYechuri** [comment]
I am not trying to replicate it. I was trying to implement as it is but
animation is not working when user starts editing.

**Comment by danieldahan** [comment]
Okay, so what’s your setup? We will fix it. Thank you for sharing this issue. 

What OS are you using?
Device to test? 
Code implementation?

**Comment by KiranYechuri** [comment]
Currently I am using simulator for testing. I didn't write anycode I have
just subclassed it and try to use it but placeholder is not animating when
user starts editing.

**Comment by KiranYechuri** [comment]
I think it broken. Can u please look into it and kindly update it

**Comment by danieldahan** [comment]
Yes we will fix it, but I need the details above. An no problem we are here to help.

**Comment by adamdahan** [comment]
@KiranYechuri 

1. What version of iOS are you running? 
2. Can you send me the code for your subclass? 

Thanks :)

**Comment by adamdahan** [comment]
@KiranYechuri Please try this code 👍 

```
import UIKit
import Material

class ViewController: UIViewController {
  
  private var textField: SubclassTextField!
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    setup()
  }
  
  // MARK: - Setup
  
  private func setup() {
    setupTextField()
  }
  
  private func setupTextField() {
    textField.placeholder = "Username"
    view.addSubview(textField)
  }
  
  // MARK: - Layout
  
  private func layout() {
    layoutTextField()
  }
  
  private func layoutTextField() {
    textField.frame = CGRect(
      center: view.center,
      size: CGSize(width: 200, height: 40)
    )
  }
}

// MARK: - Subclass Testing

class SubclassTextField: TextField {
  
  
}

```

**Comment by adamdahan** [comment]
@KiranYechuri Please reopen ticket when some sample code is provided!
