### ISSUE TITLE
Distill failed for unknown reasons

### ISSUE THREAD

**Issue by bstillitano** [CosmicMind/Material#1272]
When building with Xcode >= 11 I get the following error.

`.../Pods/Material/Sources/Assets.xcassets:1:1: Distill failed for unknown reasons.`

Any help resolving it would be appreciated.

**Comment by daniel-jonathan** [comment]
@bstillitano sorry for the delay in responding. Is this still an issue? If so, please reopen the issue and we can help. Thank you!
