### ISSUE TITLE
iOS 13.1中 TextFiled 添加LeftView是 光标位置问题

### ISSUE THREAD

**Issue by jamil36** [CosmicMind/Material#1274]

**Comment by jamil36** [comment]
当在13.1 系统时，光标位置会紧贴LeftView

**Comment by lazarte** [comment]
Is there a fix for this issue?

**Comment by daniel-jonathan** [comment]
We don't understand the issue, if you can translate it, that would be great! Thank you. @lazarte

**Comment by OrkhanAlikhanov** [comment]
I think its same as #1277
