### ISSUE TITLE
Class Name Conflict

### ISSUE THREAD

**Issue by Marcoaferrer** [CosmicMind/Material#128]
im getting a class name conflict with the class "Text". The name is used in SVGKit and another library Im using.  I was considering refactoring it to a different name and building my own version of the library. I just wanted to bring it up just in case you think it would better to update the library as to avoid conflicts.

**Comment by danieldahan** [comment]
Are you using obj-c or swift? 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by Marcoaferrer** [comment]
Swift

**Comment by danieldahan** [comment]
You should be able to specify the module name before the class to avoid name conflicts. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by Marcoaferrer** [comment]
I get an error message during after I build my app. I dont have the exact message but something like this class already exists using first ... I can get the exact message later.

**Comment by Marcoaferrer** [comment]
The app doesnt crash but I get problems with code that use the other implementation of Text. Again not a major issue though.

**Comment by danieldahan** [comment]
I am going to consider alternative names. Thank you for bringing this to our attention. All the best!
