### ISSUE TITLE
 How to set max characters limit for material textfield?

### ISSUE THREAD

**Issue by sachinrana028** [CosmicMind/Material#1282]

**Comment by OrkhanAlikhanov** [comment]
Hey! There is no specific way of setting a limit for Material's TextField. You can set limit using the [UITextField way](https://stackoverflow.com/questions/433337).

That said, you can allow user to type any number of characters but visually validate it via the validation api of `ErrorTextField` before using the content of that field. Check out for more info #1082 
```swift
let usernameField = ErrorTextField()
usernameField.placeholder = "Username"
usernameField.detail = "You can use letters, numbers & periods"
usernameField.validator.autoValidationType = .always /// check for errors as user types
usernameField.validator
  .notEmpty(message: "Choose username")
  .max(length: 10, message: "A username can contain 10 characters at most")


/// later in somewhere
guard usernameField.isValid() else { return }
```

**Comment by amritanavixel** [comment]
Thanks for the help @OrkhanAlikhanov .

**Comment by sachinrana028** [comment]
Thanks for the help @OrkhanAlikhanov.

**Comment by sachinrana028** [comment]
Suppose I have 2 textfields. Both require different max char limit, one require 10 char and other require 20 char. In that case what approach should I need to follow.
