### ISSUE TITLE
Value of type 'Layout' has no member 'horizontally'

### ISSUE THREAD

**Issue by SiddRamesh** [CosmicMind/Material#1287]
It was working fine in swift 4.2, but after I migrated to swift 5.1 I m getting this error :(

**Comment by juvs** [comment]
Based on this change... use leftRight instead.

![image](https://user-images.githubusercontent.com/204912/77579181-82b55a00-6e9f-11ea-9e35-0a10561d4b8a.png)

**Comment by SiddRamesh** [comment]
thanks it worked
