### ISSUE TITLE
[SideViewController][Storyboard example] didSelectRowAtIndexPath not working

### ISSUE THREAD

**Issue by havocked** [CosmicMind/Material#131]
Hi,

When i implement a tableview in the UIViewController that is aimed to be the sideViewController (using storyboard). I do the usual init: 

```swift
class SideViewController: UIViewController {
    
    @IBOutlet weak var customTableview: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        customTableview.delegate = self
        customTableview.dataSource = self

        // Do any additional setup after loading the view, typically from a nib.
    }
}

extension SideViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath)
        
        cell.textLabel?.text = "test"
        
        return cell
    }
   
    func tableView(tableView: UITableView, willSelectRowAtIndexPath indexPath: NSIndexPath) -> NSIndexPath? {
        print("will select")
        return indexPath
    }
    
    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        print("do smthing")
    }
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    
    func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        return 1
    }
}
```
But when i click on a cell, it doesn't use ```didSelectRowAtIndexPath```.

What is the recommended step to use a ```UITableView``` inside the SideViewController ?

Thanks again for your great work !

**EDIT**: It seems that when I switch this SideViewController as the main view:
```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Get view controllers from storyboard
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("MainViewController") as! MainViewController
        let sideViewController = storyboard.instantiateViewControllerWithIdentifier("SideViewController") as! SideViewController
        
        // Configure the window with the SideNavigationViewController as the root view controller
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        window?.rootViewController = SideNavigationViewController(mainViewController: sideViewController, leftViewController: mainViewController)
        window?.makeKeyAndVisible()
        return true
    }
``` 
The selection works, so the problem is not my code or my initialization, seems to me that there something wrong when the sideViewController inits.

**Comment by peymayesh** [comment]
In `SideNavigationViewController.swift`, you should replace this part of code with existing one:
```swift
public func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldReceiveTouch touch: UITouch) -> Bool {
	if gestureRecognizer == panGesture {
		return opened || isPointContainedWithinLeftViewThreshold(touch.locationInView(view)) || isPointContainedWithinRightViewThreshold(touch.locationInView(view))
	}
	if opened && gestureRecognizer == tapGesture {
		if let view = touch.view {
			if let leftView = self.leftView {
				if view.isDescendantOfView(leftView) {
					return false
				}
			}
			if let rightView = self.rightView {
				if view.isDescendantOfView(rightView) {
					return false
				}
			}
		}
		return true
	}
	return false
}
```

**Comment by havocked** [comment]
Hi !

Thanks it works !

But maybe it would nice to set a public parameter, in order to prevent from modifying directly the content  of SideViewNavigationController.

Thanks again !

**Comment by protactinium** [comment]
Can you provide more details how to solve the issue?

**Comment by danieldahan** [comment]
I am going to leave this open, and provide a solution that doesn't require anyone to make any internal adjustments. Thanks!

**Comment by havocked** [comment]
@protactinium You'll find a file named: "SideNavigationViewController.swift" inside the Material directory. Search for ```gestureRecognizer``` method and replace it entirely by the one provided above.

@danieldahan Thanks again !

**Comment by peymayesh** [comment]
@danieldahan I think it's better to provide a function in `delegate` that developer can decide for `gestureRecognizer: shouldReceiveTouch:` result also.

But in my opinion, it's the most logical that if `tapGestureHandling` be left for the `sideViewControllers`. If somebody wants to customize `tapGestureHandling`, he shall implement the optional delegate of corresponding function.

I hope this help. ;)

**Comment by danieldahan** [comment]
I believe this is related (https://github.com/CosmicMind/Material/issues/137) and we will push a release today with the fix. Thank you! 

I will leave the issue up until the release.

**Comment by danieldahan** [comment]
This is now fixed in issue 1.29.2, which will be out shortly. Thank you!

**Comment by AndreMarvell** [comment]
Hi @danieldahan i have the same issue with the latest version 2.3.19. When i put a table view in my rightViewController, didDeselectRowAt is never called. Could you show me how i can fix this?
Thank you

**Comment by danieldahan** [comment]
@AndreMarvell Can you share your code setup, or possibly send a sample project to support@cosmicmind.com ? Thank you

**Comment by AndreMarvell** [comment]
This is the content of my RightViewController. It's loaded from storyboard with a tableview and custom cells

![image](https://cloud.githubusercontent.com/assets/5513545/20651823/b7742fca-b4ec-11e6-8a4b-871b461597af.png)

```swift

class FavouriteViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    
    var appDelegate  : AppDelegate!
    var eventService : EventService!
    
    @IBOutlet weak var favouriteTable: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.events.listenTo(eventName: "favourite_events_updated", action: favouriteTable.reloadData)
        
        favouriteTable.rowHeight = 75
        favouriteTable.tableFooterView = UIView()
        favouriteTable.cellLayoutMarginsFollowReadableWidth = false
        
        eventService = EventService()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        favouriteTable.reloadData()
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return appDelegate.favouriteEvents.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = Bundle.main.loadNibNamed("FavorisCell", owner: self, options: nil)?.first as! FavorisCell
        let eventsKeyArray = Array(self.appDelegate.favouriteEvents.keys)
        if(eventsKeyArray.count > indexPath.row){
            let id = eventsKeyArray[indexPath.row]
            let event  = self.appDelegate.favouriteEvents[id]!
            cell.configureWithData(event, index: indexPath.row)
        }
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {
        let eventsKeyArray = Array(self.appDelegate.favouriteEvents.keys)
        if(eventsKeyArray.count > indexPath.row){
            let id = eventsKeyArray[indexPath.row]
            let event  = self.appDelegate.favouriteEvents[id]!
            self.previewEvent(event: event)
        }
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if cell.responds(to: #selector(setter: UITableViewCell.separatorInset)) {
            cell.separatorInset = UIEdgeInsets.zero
        }
        if cell.responds(to: #selector(setter: UIView.preservesSuperviewLayoutMargins)) {
            cell.preservesSuperviewLayoutMargins = false
        }
        if cell.responds(to: #selector(setter: UIView.layoutMargins)) {
            cell.layoutMargins = UIEdgeInsets.zero
        }
    }
        
}

```


PS: editingStyleForRowAtIndexPath doesn't work neither

Is it enough for you?
Thank you very much for your help

**Comment by danieldahan** [comment]
I think I know why this may not be working. Do you mind sending a sample to the email with the Storyboard all setup ? Thank you!

**Comment by danieldahan** [comment]
@AndreMarvell I am not sure if you sent a sample. Thank  you :)

**Comment by AndreMarvell** [comment]
Hi @danieldahan i've just sent you the sample right now. Sorry for the delay.

**Comment by danieldahan** [comment]
@AndreMarvell no worries. Got it :)

**Comment by danieldahan** [comment]
@AndreMarvell I will be looking at this tonight :)

**Comment by AndreMarvell** [comment]
Hi @danieldahan have you already check the sample i sent? 
Thank you

**Comment by danieldahan** [comment]
I will be able today. This past week was a really busy one. Sorry for any delay :) @AndreMarvell

**Comment by danieldahan** [comment]
@AndreMarvell is there a reason you are using `didDeselectRowAt` rather than `didSelectRowAt`? When I change it to `didSelectRowAt` all works.

**Comment by AndreMarvell** [comment]
![image](https://cloud.githubusercontent.com/assets/5513545/21076167/b328db4a-bf24-11e6-9d58-bdec53046d4e.png)


OMG!!!!!!!!!!!!!!!!, Sorry for wasting your time. I'm so stupid, I didn't pay attention to "Deselect". I've been searching this for days...

Anyway, thank you for you help.
And again great job with this library

**Comment by danieldahan** [comment]
@AndreMarvell no worries :) Happy to help.
