### ISSUE TITLE
Error installing with CocoaPods

### ISSUE THREAD

**Issue by adriga** [CosmicMind/Material#1313]
I got this error when I try to install any version with CocoaPods:

[!] Error installing Material
[!] /usr/bin/git clone https://github.com/CosmicMind/Material.git /var/folders/zm/dm0yzh656t90hfwn2pbpd9_r0000gp/T/d20221007-68668-w6i90z --template= --single-branch --depth 1 --branch 3.1.8

Cloning into '/var/folders/zm/dm0yzh656t90hfwn2pbpd9_r0000gp/T/d20221007-68668-w6i90z'...
warning: Could not find remote branch 3.1.8 to clone.
fatal: Remote branch 3.1.8 not found in upstream origin

I think that the repository path is changed (```git@github.com:CosmicMind/Material-deprecated.git```), but it's not changed in the podspec file (```s.source = { :git => 'https://github.com/CosmicMind/Material.git', :tag => s.version }```).

**Comment by daniel-jonathan** [comment]
Hey! Sorry about that. I am in the process of revitalizing this framework. I haven't worked on it in years. That said, I am updating the name back to its original path, and all should be fine now. Thank you!
