### ISSUE TITLE
Change spacing of items in Navigation bar view

### ISSUE THREAD

**Issue by vishiswoz** [CosmicMind/Material#133]
Hi, is it possible to change the width of the space for items in the Navigation bar view? I have a flat button titled "Delete All", but the whole word doesn't show up, so I would like to increase the spacing so I can see the whole word.

**Comment by danieldahan** [comment]
Yes it is, would you mind sending me the code you are using, so I can send you the correct usage?

**Comment by danieldahan** [comment]
I am going to close this for now, as I have not heard from you. Please reopen, or create a new ticket if the issue persists.

**Comment by Hamna21** [comment]
@danieldahan Hello, Can you please tell the correct way of doing this?

Currently my navigation bar is looking like this. I am using IconButtons.
![image](https://user-images.githubusercontent.com/20511422/65225574-d1dc9580-dade-11e9-8e58-bf7858feb05d.png)

**Comment by OrkhanAlikhanov** [comment]
Hey! Try playing with navigation bar's `contentEdgeInsets` and `interimSpace`;
```swift
if let v = navigationController?.navigationBar as? NavigationBar {
  v.interimSpace = -8
  v. contentEdgeInsets.right = -1
}
```
