### ISSUE TITLE
Material.xcworkspace Load Material.xcodeproj Path issue

### ISSUE THREAD

**Issue by DaidoujiChen** [CosmicMind/Material#136]
Hello @danieldahan,

The location path may not correct in [Material.xcworkspace](https://github.com/CosmicMind/Material/blob/master/Examples/Material.xcworkspace/contents.xcworkspacedata#L5), in my case, I fix it to `location = "group:./../Material.xcodeproj"`, thanks.

**Comment by danieldahan** [comment]
Excellent, this will be fixed in todays release. I will leave this up until then.

**Comment by danieldahan** [comment]
fixed in 1.29.2, thank you!

**Comment by DaidoujiChen** [comment]
:)
