### ISSUE TITLE
Trouble Running Example Code

### ISSUE THREAD

**Issue by Chris-Sipe** [CosmicMind/Material#141]
I'm trying to run the example projects by opening the Material.xcworkspace file in the Examples directory and selecting a project to build from the dropdown menu that appears to the right of the build and stop buttons. It builds fine, but I get this error as soon as it begins to run. 

"dyld: Library not loaded: @rpath/Material.framework/Material
  Referenced from: /var/mobile/Containers/Bundle/Application/60178D7F-6BCA-41DF-9552-B6130385B82A/SideNavigationViewController.app/SideNavigationViewController
  Reason: image not found"

**Comment by danieldahan** [comment]
Hi, @Chris-Sipe 

You need to embed the Material.framework in the project you want to run. By default, they are not embedded, to avoid build errors and version conflicts. I am making a push now v1.29.3 that updates the SideNavigationViewController, so you know, as you test the examples. 

If the issue persists, please reopen the ticket, or create a new one. Thank you!

**Comment by Chris-Sipe** [comment]
Awesome! You rock!

**Comment by sujithv28** [comment]
How do you embed a framework in xCode?

**Comment by danieldahan** [comment]
1. Compile the Material.framework project, by choosing the scheme in the Xcode navigation bar. The device needs to be on Generic Device, or an actual iOS device, not simulator. 

2. Click on the project you want to run in the examples directory. 
3. Open the 'General' page in the project inspector. 
4. Go to Embedded Binaries, and add the Material.framework binary. 
5. Choose the project scheme in the top navigation bar that you want to run. 
6. Press run.
