### ISSUE TITLE
Fab button crashing while setting background color in code  and also not  showing rounded corner

### ISSUE THREAD

**Issue by ajaybeniwal** [CosmicMind/Material#143]
When i try to set the background color of fab button in the code it crashes and neither it is showing rounded corners 

I get the error 2016-02-03 21:04:42.535 TransitFare[3631:1539353] Unknown class FabButton in Interface Builder file.
//Crash Line 
addButton.backgroundColor = UIColor(red: 255.0/255.0, green: 64.0/255.0, blue: 129.0/255.0, alpha: 1.0)

Button width = 64 height = 64 
//Code 
       @IBOutlet var addButton: FabButton!
        let img: UIImage? = UIImage(named: "AddNew")
        addButton.setImage(img, forState: .Normal)
        addButton.setImage(img, forState: .Highlighted)
        addButton.tintColor = UIColor.whiteColor()

**Comment by adamdahan** [comment]
@ajaybeniwal Based on this: "I get the error 2016-02-03 21:04:42.535 TransitFare[3631:1539353] Unknown class FabButton in Interface Builder file." 

It makes me believe that you did not change the class from UIButton to FabButton. Did you ensure that you did this first?

**Comment by sujithv28** [comment]
I get that error too even if I set it to FabButton in the IB Inspector

**Comment by danieldahan** [comment]
Have you had a chance to look at the example projects in Examples/Storyboards?

**Comment by adamdahan** [comment]
@ajaybeniwal @sujithv28 Just make sure the class is set to FabButton & the module is set to Material and there will be no issues.
