### ISSUE TITLE
[SideNavigationViewController] Configure Threshold

### ISSUE THREAD

**Issue by havocked** [CosmicMind/Material#146]
Seems that we cannot configure the threshold property:

```swift
sideNavigationViewController?.leftViewThreshold = 0
```
I get this warning: 

<img width="330" alt="screen shot 2016-02-05 at 17 05 59" src="https://cloud.githubusercontent.com/assets/7999585/12847086/5dc659a4-cc2a-11e5-88db-5007b8440cd5.png">

The reason I would like to configure it, is for the following use-case:
- I want the user to open de side view only by tap on button.
- But i also want to enable the pan gesture for closing the side view.

Maybe it is already possible, but i can't see the way to properly doing it without modifying your source code.

Thanks again !

**Comment by danieldahan** [comment]
Hi @havocked, 

Yes, you can achieve this without having to modify the source. These are the steps I would try:

Set the sideNavigationViewController?.enabled property to false. This will disable the panning gesture when closed. It will also disable the toggle functionality. So when you click on the button you want to have open the side nav, set the enabled property back to true, and toggle it open. The user will now have the ability to slide the side nav closed, or tap it closed. 

With the delegation methods available, use the ...DidClose... delegation method to detect when the user closed it. Once closed, whether from panning or tapping, set the enabled property back to false. 

This should work, and it would be what I would do to avoid any code fuss.

**Comment by havocked** [comment]
Alright, thanks again for your cool work !

**Comment by danieldahan** [comment]
:) thank u

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
