### ISSUE TITLE
NavigationBarView title not positioned right

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#148]
hello, I tried to setup the ````NavigationBarView```` like this:
```swift
    func initNavBar() {
        navigationBarView.backgroundColor =  UIColor(rgba: Constants.Colors.colorPrimary)
        navigationBarView.statusBarStyle = .LightContent
        // Title label.
        let titleLabel: UILabel = UILabel()
        titleLabel.text = Localizations.AppName
        titleLabel.textAlignment = .Left
        titleLabel.textColor = MaterialColor.white
        titleLabel.font = RobotoFont.regularWithSize(Constants.FontSize.Large)
        navigationBarView.titleLabel = titleLabel
        navigationBarView.titleLabelInset.left = 64
        
        let img1: UIImage? = UIImage(named: "ic_menu_white_24dp")
        let profileButton: FlatButton = FlatButton()
        profileButton.pulseColor = MaterialColor.white
        profileButton.pulseScale = true
        profileButton.setImage(img1, forState: .Normal)
        profileButton.setImage(img1, forState: .Highlighted)
        profileButton.addTarget(self, action: "toggleSideMenu", forControlEvents: .TouchUpInside)
        navigationBarView.leftButtons = [profileButton]
        
        let img2: UIImage? = UIImage(named: "ic_search_white_24dp")
        let searchButton: FlatButton = FlatButton()
        searchButton.pulseColor = MaterialColor.white
        searchButton.pulseScale = true
        searchButton.setImage(img2, forState: .Normal)
        searchButton.setImage(img2, forState: .Highlighted)
        navigationBarView.rightButtons = **[searchButton]**
    }
```
But I get this look:
 
![simulator screen shot feb 7 2016 9 14 23 pm](https://cloud.githubusercontent.com/assets/2195533/12874722/18dc537a-cde2-11e5-82f3-f9c0f7c83311.png)

Any idea?

**Comment by adamdahan** [comment]
Hi @sohayb, 

The titleLabel is purposely set to the left by default, however, you can adjust it's position using the titleLabelInset property. 

Hope that helps!

**Comment by sohayb** [comment]
hi @adamdahan 
Actually my concern is that it's not centred vertically, not talking about the horizontal position.
Thanks

**Comment by danieldahan** [comment]
You can use the same titleLabelInset and contentInset properties to align
both vertically and horizontally. :)

**Comment by sohayb** [comment]
I tried that, the problem is whenever I modify the bottom inset, the navigation bar height changes, it gets bigger!

**Comment by danieldahan** [comment]
You want to reduce the top insets

**Comment by sohayb** [comment]
that worked! thanks a lot. But shouldn't the text be centred vertically by default?

**Comment by danieldahan** [comment]
Depending on the size of text it centres. 
Future iterations will handle this issue more elegantly :)


---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
