### ISSUE TITLE
Why you don't use @IBInspectable?

### ISSUE THREAD

**Issue by svyatoslav-reshetnikov** [CosmicMind/Material#151]
Hi. This is a good UI library, but you may to be better. I think it would be much more convenient to edit parameters in Attributes inspector. All what you need - add @IBInspectable for all UI parameters.
Why you must to do it? I'm programmer and i don't like use code for change background color, button radius, border width etc. I want to do it quick and simple use storyboard.

If you do this, I'll be very grateful to you. And not only me. Thank you!

**Comment by danieldahan** [comment]
Agreed :) we will provide a solution to this within one of our next releases. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by svyatoslav-reshetnikov** [comment]
It's simple task. I may to help you to do it if you want :)

**Comment by danieldahan** [comment]
Yeah, help is always appreciated :)

**Comment by danieldahan** [comment]
If you can get it started, and make any PRs to development, we can get this going. Otherwise, I will do it by the end of the month most likely. I am closing this issue for now :)

**Comment by svyatoslav-reshetnikov** [comment]
I start it in this weekends, i need about 4-5 days on it because i have full time job :)

**Comment by danieldahan** [comment]
No rush :) Thank you! Also, check this out, a new feature coming out today. 

https://github.com/CosmicMind/Material/wiki/Grid <https://github.com/CosmicMind/Material/wiki/Grid>

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by svyatoslav-reshetnikov** [comment]
Cool feature :)
I working on this task, but i have few questions. Can we contact skype, e-mail, etc?

**Comment by danieldahan** [comment]
Great! Yes, lets Skype. My name is djondahan.

When were you thinking?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by svyatoslav-reshetnikov** [comment]
I already added you, i propose to continue in skype and don't clutter up this issue.

**Comment by gkye** [comment]
Any progress on this?

**Comment by danieldahan** [comment]
Being added to the next release. Thanks for double checking on this.
