### ISSUE TITLE
Cocoapods requires submission

### ISSUE THREAD

**Issue by JoeShi** [CosmicMind/Material#154]
I got a situation. I write my own UILib which dependent on your lib

`'pod 'MK', :git => 'https://github.com/CosmicMind/Material.git'` this work if I use the it as a pod.

`s.dependency 'MK', '~> 1.32.2'`, it does not work. This is cause error if I use the pod as an dependency.

**Comment by sohayb** [comment]
hello,
the official framework nam is now 'Material' so you can you it as follows:
````s.dependency 'Material', '~> 1.32.2'````

**Comment by JoeShi** [comment]
Got it . Thank you @sohayb
