### ISSUE TITLE
Crash when MaterialButton subclass is removed from its superview due to pending animation

### ISSUE THREAD

**Issue by matthewkrueger** [CosmicMind/Material#156]
Hi cosmicmind - thanks for the great library!

I'm embedding some FlatButton's inside a custom UIView.  I have a method in this UIView to hide the whole thing, like this:

```
    func hideView(){
        
        UIView.animateWithDuration(0.2, animations: { () -> Void in
            
            //Here's the animation
            self.alpha = 0.0
            
            }) { (Bool) -> Void in
                
                //This is the completion closure
                self .removeFromSuperview()
        }
    }
```

Unfortunately, sometimes after hideView is called, my app crashes in MaterialButton.pulseAnimation method at line 483: 

`if nil != self.pulseColor && 0 < self.pulseColorOpacity {`

Thread 1: EXC_BREAKPOINT (code=1, subcode=0x101ce9418)

I have tried manually canceling all pending animations in the hideView method like so:
```

    func hideView(){
        
        UIView.animateWithDuration(0.2, animations: { () -> Void in
            
            //Here's the animation
            self.alpha = 0.0
            
            }) { (Bool) -> Void in
                
                //I noticed a crash because there were animations still running in the material button when removing
                for view in self.subviews{
                    view.layer.removeAllAnimations()
                }
                
                //Now, remove any animations from the parent too.
                self.layer.removeAllAnimations()
                
                self .removeFromSuperview()
        }
    }
```

This worked for a few open/closes of the view, but eventually the same crash happened.

Can you advise on a way to safely remove a MaterialButton from it's superview, or is this a bug?

Please let me know if you need more info, love your library!

**Comment by matthewkrueger** [comment]
Hey there - it appears if you change 

`[unowned self]` to `[weak self]` and check that `nil != self` it works.  The fix needs to happen in two places in MaterialButton.swift.

**Comment by danieldahan** [comment]
Nice :) I will test this out and when we make our release today, it will include a fix. I'll keep you posted.

**Comment by danieldahan** [comment]
Where are the two places you made the change?

**Comment by matthewkrueger** [comment]
[http://oi66.tinypic.com/jqghly.jpg](MaterialButton.swift changes)

**Comment by danieldahan** [comment]
Excellent, I made the changes. This will be out later today. I will close the issue once the release is made. Thank you!

**Comment by matthewkrueger** [comment]
Thank you @danieldahan !

**Comment by danieldahan** [comment]
I am closing this ticket. The fix is in the next release. Thanks again :)
