### ISSUE TITLE
[SideNavigationViewController] A view of rightViewController doesn't get pulled sometimes.

### ISSUE THREAD

**Issue by njovy** [CosmicMind/Material#159]
I'm using ```SideNavigationViewController``` in my app with a rightViewController.
When I swipe or pan the screen to pull a rightViewController, only the backdrop appears. Then I have to pan again to pull the rightViewController. Any possible fix to avoid this issue?
Thanks for this great library!

**Comment by danieldahan** [comment]
:) Hey, what version are you using?

**Comment by njovy** [comment]
Oops I forgot to add the version. I am using 1.32.2!

**Comment by danieldahan** [comment]
Interesting, I can't seem to reproduce it. Before the next release, which I am planning for today, I will continue to try and reproduce the issue. :) If I can find it, I will make a fix, otherwise, we will need to try another approach, or it may have been resolved with the current work I am doing.

**Comment by danieldahan** [comment]
I haven't been able to reproduce this. Please update to the latest version, and if the issue persists, reopen the issue or create a new one. 

All the best!
