### ISSUE TITLE
About UIFont's pointSize and the actual line height

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#160]
I have a problem with `TextField`'s `titleLabel`. it'll cut off my text because I'm using a custom font and it won't align well, anyway, when I was investigating the code (Swift version) I've encountered the use of `UIFont`'s `pointSize` as an indication of the line's height. I'm sure it'll work on some fonts but it's not the best approach. You can always use sizing mechanism provided on strings but in case you don't want to rely on the text itself, there are some ways you can use to get a decent line height out of a font.

Checkout this gist: [CoreText - Calculating Line Height](https://gist.github.com/zsiegel/3939819#file-gistfile1-m)

I'm not sure about the contribution guideline of the framework, otherwise I would've submitted a PR.

Best Regards,
M.

**Comment by mohpor** [comment]
In retrospect, `UIFont` DOES provide a `lineHeight` property as of iOS 4.0! You can just replace `pointSize` with `lineHeight`.

**Comment by danieldahan** [comment]
I had made a fix for this that is ready in the next release. I am going to try the lineHeight approach and see which gives the best results. Excellent find and suggestion, thank you. As for contributing, I will make it more clear on how to do that. Thank you!

**Comment by danieldahan** [comment]
If you look in the development branch, the fix is in both TextField and TextView. Would you be able to confirm that it is working for you?

**Comment by mohpor** [comment]
I can confirm, it fixes the problem.

But it has some backward compatibility issues. (I'm guessing it's just a test for the solution) corner radius of Material Views are CGFloat now!

**Comment by sohayb** [comment]
You can check #161 for that

**Comment by danieldahan** [comment]
so cornerRadius is a CGFloat now to solve Storyboard support, and there is an added cornerRadiusPreset property that allows you to use the MaterialRadius enum types. This pattern will follow for other properties as well.
