### ISSUE TITLE
.CornerRadius poperty

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#161]
hello,
I moved to the development branch, now ```` mainCardView.cornerRadius = .Radius1```` is not working anymore, had to do this to work: ```` MaterialRadiusToValue(.Radius1)````, was that intentional or am I doing something wrong?
Thank you :)

**Comment by chaitanya-ramji** [comment]
Hey,
Try this out. `mainCardView.cornerRadiusPreset = MaterialRadius.Radius1` I guess cornerRadius requires a float value whereas the return type of .Radius1 isn't float.

**Comment by danieldahan** [comment]
Yes, the enum property settings are moving to the ***Preset property values so that Storyboards can be better supported.

```swift
obj.cornerRadius = 3
obj.cornerRadiusPreset = .Radius3
```
