### ISSUE TITLE
Unable to add MaterialSwitch using CGRectMake

### ISSUE THREAD

**Issue by chaitanya-ramji** [CosmicMind/Material#162]
Hey,
I tried manually positioning the switch in my View (I am not a huge fan of Auto Layout). The Switch however keeps getting positioned on the top corner of the View. This was my code:

`let c3: MaterialSwitch = MaterialSwitch(state: .Off, style: .LightContent, size: .Large)
        c3.frame = CGRectMake(10,80,40,60)
        c3.delegate = self
        c3.enabled = false
        c3.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(c3)`

Is there something wrong in what I have done?

**Comment by danieldahan** [comment]
try getting rid of this line

```swift
c3.translatesAutoresizingMaskIntoConstraints = false
```

**Comment by chaitanya-ramji** [comment]
Worked a charm!
Thanks :)
