### ISSUE TITLE
Adjust placeholder colour?

### ISSUE THREAD

**Issue by craigpearce5** [CosmicMind/Material#168]
Can the placeholder text colour be changed?

**Comment by danieldahan** [comment]
Which component are you talking about, TextField?

```swift
if let v: String = textField.placeholder {
	textField.attributedPlaceholder = NSAttributedString(string: v, attributes: [NSForegroundColorAttributeName: MaterialColor.white])
}
```

**Comment by craigpearce5** [comment]
Yes, textField.  I was kind of hoping there would be a `.placeholder.textColor = MaterialColor.grey.darken1` way of changing it.

**Comment by danieldahan** [comment]
Sounds like a nice addition :) tomorrow's release will have it. Please leave the issue open.

Thanks :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
This has been updated to:

```swift
textField.placeholderTextColor = MaterialColor.green.base
```

And will be in today's release. Thank you!

**Comment by craigpearce5** [comment]
That's awesome - thanks!
