### ISSUE TITLE
Adjust background colour?

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#169]
Can i change the textfield background color through code?

**Comment by danieldahan** [comment]
You can change the area where the textField is.

```swift
textField.backgroundColor = MaterialColor.green.base
```

![screen shot 2016-02-21 at 1 34 56 pm](https://cloud.githubusercontent.com/assets/9982123/13204512/ffe83884-d89f-11e5-9617-11202d0d015b.png)

**Comment by HowardCsie** [comment]
thanks.
