### ISSUE TITLE
How to use textfield detailLabel?

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#170]
As title, can i get  an example? thanks.

**Comment by danieldahan** [comment]
There is an examples [project](https://github.com/CosmicMind/Material/blob/master/Examples/Programmatic/TextField) and [code](https://github.com/CosmicMind/Material/blob/master/Examples/Programmatic/TextField/TextField/ViewController.swift)

**Comment by HowardCsie** [comment]
sorry for asking stupid question.I m pretty new using Material.I have seen the example already .thanks

**Comment by danieldahan** [comment]
No worries, did you need help with something?
