### ISSUE TITLE
Image Not Found error when building example projects 

### ISSUE THREAD

**Issue by mertnesvat** [CosmicMind/Material#171]
I downloaded project and tried to build example projects but got error like below; 
    ```Library/Developer/Xcode/DerivedData/Material-djrnmjribzxolscwjzeojckbbkqx/Build/Products/Debug-iphonesimulator/Material.framework/Material
  Reason: image not found```

Is there anything I did wrong?

**Comment by chaitanya-ramji** [comment]
Add the Material.xcodeproj to your project as an embedded binary. Select Material as a Target and Build. Then select your project as a Target and Compile and Run.

**Comment by danieldahan** [comment]
Hi @mertnesvat, have you looks at these instructions https://github.com/CosmicMind/Material/wiki/Installation

Thanks @chaitanya-ramji :)

**Comment by mertnesvat** [comment]
I didn't see wiki page sorry :+1: thanks @danieldahan  and @chaitanya-ramji

**Comment by chaitanya-ramji** [comment]
Always happy to help @mertnesvat @danieldahan  :)

**Comment by hisham2007** [comment]
I face the same issue. I followed installation page. some examples and some give mentioned error. example: CardView and ImageCardView. Please help

**Comment by hisham2007** [comment]
I managed to fix it. there is 2 projects with the same name. one programatic and one with storyboard. I was using wrong one
