### ISSUE TITLE
Exemple project 

### ISSUE THREAD

**Issue by terflogag** [CosmicMind/Material#172]
When I try to build  the exemple project I found fatal error : 
```
dyld`dyld_fatal_error:
->  0x120019088 <+0>: brk    #0x3
```
Any idea ?

**Comment by danieldahan** [comment]
Which project, and on what device? Have you looked at these instructions: https://github.com/CosmicMind/Material/wiki/Installation

**Comment by terflogag** [comment]
Yep, for exemple with "MaterialButton" and "SideNavigationViewController" in storyboard folder.
But it's ok for "App" project...

**Comment by danieldahan** [comment]
Hmmm... I just tried both and they seem to be working fine. Have you embedded the Material.framework? What device are you doing this on, or simulator?

**Comment by danieldahan** [comment]
Try clearing the build directory and Derived Date directory.

**Comment by terflogag** [comment]
After delete and download from github (+ reboot) it work.. really strange ! 
Thank you :-)
