### ISSUE TITLE
SideNavigationController and push view

### ISSUE THREAD

**Issue by terflogag** [CosmicMind/Material#174]
Hello, 

Generally I use SWRevealViewController to make SideBar in my project, but SideNavigationController seem to be more simple and cool. 
So, I'm trying to make SideBar and push some view on sidebar's row selection. 

Currently I have this in my sidebar controller : 

```
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        switch indexPath.row {
        case 0:
            self.presentSportView()
            break
        default:
            break
        }
    } 

private func presentSportView() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("mainView") as! SportChoiceTableViewController
        let navController = UINavigationController(rootViewController: mainViewController)
        let sideViewController = storyboard.instantiateViewControllerWithIdentifier("sidebarView") as! SideBarTableViewController
        let fullView = SideNavigationViewController(mainViewController: navController, leftViewController: sideViewController)
        
        self.presentViewController(fullView, animated: true, completion: nil)
    }
```

And this in my storyboard : 
<img width="688" alt="capture d ecran 2016-02-23 a 13 41 37" src="https://cloud.githubusercontent.com/assets/14054997/13251888/35e496a0-da33-11e5-8207-dc2842e8bf20.png">

It work but not with push transition. How can I do that ? Or it's not available with SideNavigationController ?

`self.performSegueWithIdentifier("pushViewSettings", sender: self)`
Don't provide good transition and disable navigation item.

And thank you for Material library, that's awesome :-)

**Comment by danieldahan** [comment]
Hi @terflogag 

Are you trying to change the mainViewController? If so, there is a 

```swift
transitionFromMainViewController
```

method that you can use. Otherwise, there are ways to make the push work and such, but it takes more effort.

**Comment by terflogag** [comment]
Oups, I had not seen that ! 

```
    private func presentSportView() {
        // Hide side bar
        sideNavigationViewController?.toggleLeftView(0.3)
        
        // Show new controller
        let mainViewController = self.storyboard?.instantiateViewControllerWithIdentifier("mainView") as! SportChoiceTableViewController
        let navController = UINavigationController(rootViewController: mainViewController)
        sideNavigationViewController?.transitionFromMainViewController(navController, duration: 0.5, options: .TransitionNone, animations: nil, completion: nil)
    }
```
Now work with this, but I need to find the good UIViewAnimationOptions.

Thank your :-)

**Comment by danieldahan** [comment]
:) Great!

**Comment by danieldahan** [comment]
By the way, you can add more transition animations using the MaterialAnimation.transition method. 

add the transition to the addAnimation method like so

```swift
Controller.view.layer.addAnimation(MaterialAnimation.transition(.MoveIn, direction: .Bottom), forKey: kCATransitionFromBottom) 

then use the transitionFromMainViewController method. That is a hidden gem :)

**Comment by terflogag** [comment]
Nice, I will try it ! :+1:

**Comment by hidrodixtion** [comment]
`transitionFromMainViewController` is now `transitionFromRootViewController`
