### ISSUE TITLE
Feature Request: MaterialView ClipsToBounds with shadows showing

### ISSUE THREAD

**Issue by XemaCobra** [CosmicMind/Material#176]
Right now and because of the way UIView works, If I want a MaterialView to have rounded corners and would like to clipToBounds, the shadow/depth will disappear. 

It would be great if the clipsToBounds is overridden to make this masking possible while the shadow/depth persists.

**Comment by danieldahan** [comment]
It is already done that way, using maskToBounds and understanding the layering system. What are you trying to place as a subview, and I can better help you from there.

**Comment by XemaCobra** [comment]
I'm adding another UIView inside the MaterialView.

**Comment by danieldahan** [comment]
Okay, I'll play with the internals a bit and see if I can make this really easy, otherwise, I will explain an approach you can take. I want to make sure my solution doesn't cause a UIView hierarchy issue.

**Comment by XemaCobra** [comment]
Thanks

**Comment by danieldahan** [comment]
This is in the queue. Didn't forget about you :)

**Comment by danieldahan** [comment]
If you use a CardView, then you can set the detailView value with the UIView you want to have clipped. Set the CardView divider property to false as well. I will look into making a view that handles this as a direct feature. Thanks and all the best! Sorry this took so long to respond too, has been really busy.

**Comment by zgosalvez** [comment]
@danieldahan Setting the detailView with the custom UIView hides the pulse. It's still there but it's behind the detailView.

**Comment by danieldahan** [comment]
@zgosalvez  Yes, that is correct. The pulse is an underlying layer. So it does not cover text or content. Setting the defaultView to a `clear` background color allows it to still be seen.
