### ISSUE TITLE
Request: Change access level or implementation of TextField method

### ISSUE THREAD

**Issue by Strobocop** [CosmicMind/Material#177]
First off...thanks for the amazing library!

I might be missing something obvious so please steer me in the right direction if I am wrong. Because the following method of TextField is internal and the behavior cannot be overridden, it becomes impossible to use the detailTextLabel to display validation error messages as shown in the demo. It seems like this will force the detailTextLabel to disappear anytime text is added to a field (which in my opinion is too limiting). I am hoping to actually validated the information in the field before showing or dismissing the detail label.

  
The method in question:
```
  internal func textFieldValueChanged() {
        if !detailLabelHidden {
            detailLabelHidden = true
            MaterialAnimation.animationDisabled { [unowned self] in
                self.bottomBorderLayer.backgroundColor = self.titleLabelActiveColor?.CGColor
            }
        }
    }
```

**Comment by danieldahan** [comment]
Thank you :)

Yes this came as an adjustment from the Material Design spec. What I think is that a flag should be set to enable or disable that feature, auto-hiding the detailLabel. This would keep the internals safe from exposure, and give both outcomes. Thoughts?

**Comment by Strobocop** [comment]
Interesting. In that case, I agree 100%. Best of both worlds.

**Comment by danieldahan** [comment]
Cool, this will be out later today. I'll leave the issue up and take it down when I make the release. Generally, Material and other frameworks we make, are geared towards no-fuss, while removing the need for hacky code. This was a great suggestion. Thanks !

**Comment by Strobocop** [comment]
Awesome, thanks Daniel. Recommending this framework to every iOS developer I know. Keep up the great work!

**Comment by danieldahan** [comment]
Here is the [1.34.4](https://github.com/CosmicMind/Material/releases/tag/1.34.4) release, which solves your issue, and there is an example in the Examples/Programmatic/TextField project.

:) All the best

**Comment by Strobocop** [comment]
Once again, you rock! Thanks Daniel. Would love to contribute to the project in the future when I free up if you guys could use it.
