### ISSUE TITLE
Overriding problem in Example/App

### ISSUE THREAD

**Issue by papay0** [CosmicMind/Material#178]
I do not know if the problem is in the code example or in the library, but in Example/App:

- In **AppSearchBarViewController.swift**, there is a problem with prepareView()
It is currently private func prepareView(), and I think it should be internal override func prepareView()
- The same in **AppNavigationBarViewController**.

Moreover, even with these changes, the Example/App does not want to show up.

**Comment by danieldahan** [comment]
Thank you! The examples are fixed in 1.34.5.
