### ISSUE TITLE
TextField Cursor Color when the user selects the field before starting to type

### ISSUE THREAD

**Issue by alexvbush** [CosmicMind/Material#180]
Hi guys, great framework, love it so far! I have an issue with visibility/color of the cursor in my `TextField`. Here's what I've got:
```swift
private func setupNameTextField() {
        nameTextField.backgroundColor = UIColor.clearColor()
        
        nameTextField.placeholderTextColor = MaterialColor.grey.lighten3
        nameTextField.font = RobotoFont.regularWithSize(20)
        nameTextField.textColor = MaterialColor.white
        
        nameTextField.titleLabel = UILabel()
        nameTextField.titleLabel!.font = RobotoFont.mediumWithSize(12)
        nameTextField.titleLabelColor = MaterialColor.white
        nameTextField.titleLabelActiveColor = MaterialColor.white
}
```

The problem is - when the user selects the field, right before start typing the blinking cursor is not visible, which means it's hard to tell which field you selected.

![screenshot 2016-02-25 11 37 46](https://cloud.githubusercontent.com/assets/311077/13331891/625657b4-dbb4-11e5-8603-766a64dbc876.png)

But after the user types something the cursor becomes visible and blinking as expected.

![screenshot 2016-02-25 11 40 16](https://cloud.githubusercontent.com/assets/311077/13331942/95e968a0-dbb4-11e5-9a10-b47a1c324e0a.png)

Am I doing something wrong?

**Comment by danieldahan** [comment]
Hi @alexvbush 

Before the release today, we will look into this and either make a fix or provide a suggestion :)

**Comment by alexvbush** [comment]
thank you @danieldahan

**Comment by alexvbush** [comment]
hey @danieldahan, any updates?

**Comment by danieldahan** [comment]
Hi @alexvbush Sorry, for the delay.

I don't see the tintColor set for the textField. Can you try and set the tintColor

```swift
emailField.tintColor = MaterialColor.green.darken4
```

**Comment by danieldahan** [comment]
I tested this programmatically and through storyboards. I can't replicate the issue. There is an added storyboards project that shows TextFields in use in the Examples directory. If this issue persists, let me know. Thank you!
