### ISSUE TITLE
MaterialSwitch

### ISSUE THREAD

**Issue by hassiumsoft** [CosmicMind/Material#181]
**error**
  	/// A boolean indicating if the switch is on or not.
	public var on: Bool {
		get {
			return .On == internalSwitchState
		}
		set(value) {
			setOn(on, animated: true)   //error on value is  .On == internalSwitchState
		}
=================>
	public var on: Bool {
		get {
			return .On == internalSwitchState
		}
		set(value) {
			setOn(value, animated: true)
		}

**Comment by danieldahan** [comment]
Ah... nice. Thank you! I made the change and it will be in today's release.
