### ISSUE TITLE
sideNavigationViewController without App Deligate

### ISSUE THREAD

**Issue by azeeshan** [CosmicMind/Material#182]
In an existing app, how do I just add sideNavigationViewController?
Seems like I have to initialize it in AppDeligate assigning the rootViewController. Is that correct? 
In my existing AppDeligate I have some not so good code and I cannot change that. What would be the best way to use sideNavigationViewController and not do anything in app delegate

**Comment by danieldahan** [comment]
The SideNavigationViewController only needs to exist as the rootViewController, or a child of another UIViewController. Is it possible to go about it that way? Can you let me know more about your app to better help you?

**Comment by danieldahan** [comment]
Checkout [Navigation Controllers](https://github.com/CosmicMind/Material/wiki/Navigation-Controllers). This should help in your understanding. This weekend we will be writing more documentation on Navigation Controller features.

**Comment by danieldahan** [comment]
I haven't heard from you, so please reopen or create a new issue if you have any further questions. Thank you!
