### ISSUE TITLE
Make FabButton transition preserving NavigationBarView

### ISSUE THREAD

**Issue by monkeythecoder** [CosmicMind/Material#183]
Is it possible to make a transition triggered by a FabButton but preserving the current NavigationBarView. I want to trigger a "modal" and be able to close it.

Example:
![Material](http://i.imgur.com/FcDk4PG.png)

And after tapping the FabButton, see something like this

![Material](http://i.imgur.com/8SmSCN9.png)

 and link the backbutton with the previous screen (so I can close it).

I'm currently using ```transitionFromMainViewController```from my ```MenuViewController````

```swift
internal func handleMenu() {
        self.menuButton.hidden = true //Hide Fabbutton
        self.transitionFromMainViewController(CreateStateViewController() as UIViewController,  options: [.TransitionCrossDissolve])
``` 

But my NavigationBarView dissapears.

Am I doing something wrong?

**Comment by danieldahan** [comment]
Yes, there are a couple things. 

The MenuViewController has its own `mainViewController`, so the transitionFromMainViewController is calling it on `self`, which is referencing the MenuViewController. That is why the entire view controller is being replaced, including the NavigationBarView.

To reference the NavigationBarViewController, which is the `mainViewController` for the MenuViewController, you would want to do this

```swift
(mainViewController as? NavigationBarViewController)?.transitionFromMainViewController(InboxViewController() ...)
```

That will preserve the NavigationBarView.

If you want to have a modal UIViewController, you can set the `floatingViewController` property for the NavigationBarViewController, like so:

```swift
(mainViewController as? NavigationBarViewController)?.floatingViewController = InboxViewController()
```

To close the `floatingViewController`, set in the InboxViewController a button that triggers this line of code:

```swift
navigationBarViewController?.floatingViewController = nil
```

I need to write some documentation on this. Something we are doing. Generally, the different Navigation Controllers can be stacked in any order to change how everything moves around. In the Examples/App project, the AppDelegate shows a configuration of stacking Navigation Controllers. Easily, the MenuViewController and NavigationViewControllers can switch parent child relationships. 

In the Examples/App, there is code that demonstrates using the `floatingViewController` code when opening the SearchBarViewController.

**Comment by danieldahan** [comment]
Checkout [Navigation Controllers](https://github.com/CosmicMind/Material/wiki/Navigation-Controllers) for more information. This weekend I will be spending time writing up documentation on Navigation Controllers.

**Comment by danieldahan** [comment]
I am closing this issue. If you need, please reopen, or create a new issue. 

All the best!

**Comment by monkeythecoder** [comment]
Hi, first of all thank you for your fast response. I couldn't try the suggested solution in the past days.

I tried both approaches but  ```floatingViewController``` was the one that best fitted my needs. However, I want also be able to hide the fabbutton when the ```floatingViewController``` appears. I tried setting the zPosition by hand so the fabbutton stays behind the view but it didn't seem to work. Do you have any idea what could it be?

i appreciate the time and the effort you guys are making with this awesome framework. thanks!
