### ISSUE TITLE
 SearchBarView , textField.backgroundColor is customizable?

### ISSUE THREAD

**Issue by TThana** [CosmicMind/Material#184]
For SearchBarView
Can textField.backgroundColor is customizable please?

now it is set to
textField.backgroundColor = MaterialColor.clear
in func prepareTextField() 

Thank you very much!

**Comment by danieldahan** [comment]
You can set the value like this.

```swift
searchBarView.textField.backgroundColor = MaterialColor.green.base
```

That should work. If you have any further issues, reopen or create a new issue. 

Thank you!
