### ISSUE TITLE
xcode sim, just cloned the repo

### ISSUE THREAD

**Issue by misbell** [CosmicMind/Material#185]
I get a noop, image not found error, on every app I try to run.

**Comment by chaitanya-ramji** [comment]
Hey @misbell,
 Did you add the Material framework to your project? Check out the [Installation guide](https://github.com/CosmicMind/Material/wiki/Installation) for use with Pods and Carthage. Incase you are not using either, directly drag and drop the Material.xcodeproj into your project. Add it as an embedded binary, select Material as a Target, Compile and Build. This should work for you.

**Comment by mohpor** [comment]
When you open the examples workspace, in Project Navigator select the project you want to run and in `General` tab, section `Embedded Binaries` click the `+` sign and select the `Material.framework` and then run the project.

**Comment by misbell** [comment]
thanks!

On Sat, Feb 27, 2016 at 6:45 AM, M. Porooshani <notifications@github.com>
wrote:

> When you open the examples workspace, in Project Navigator select the
> project you want to run and in General tab, section Embedded Binaries
> click the + sign and select the Material.framework and then run the
> project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189621331>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
can't be added as an embedded binary. can be added as a framework but
changes nothing.

[image: Inline image 1]

On Sat, Feb 27, 2016 at 6:45 AM, M. Porooshani <notifications@github.com>
wrote:

> When you open the examples workspace, in Project Navigator select the
> project you want to run and in General tab, section Embedded Binaries
> click the + sign and select the Material.framework and then run the
> project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189621331>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
wait it won't run on the simulator? how come?

On Sat, Feb 27, 2016 at 8:57 AM, Michael Prenez-Isbell <
michael.isbell@gmail.com> wrote:

> can't be added as an embedded binary. can be added as a framework but
> changes nothing.
>
> [image: Inline image 1]
>
> On Sat, Feb 27, 2016 at 6:45 AM, M. Porooshani <notifications@github.com>
> wrote:
>
>> When you open the examples workspace, in Project Navigator select the
>> project you want to run and in General tab, section Embedded Binaries
>> click the + sign and select the Material.framework and then run the
>> project.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189621331>
>> .
>>
>
>
>
> --
> Mike Isbell
>
>


-- 
Mike Isbell

**Comment by misbell** [comment]
found the page, framework won't install in embedded binary.

wait, why won't it run on the simulator? what's that about?

On Sat, Feb 27, 2016 at 6:45 AM, M. Porooshani <notifications@github.com>
wrote:

> When you open the examples workspace, in Project Navigator select the
> project you want to run and in General tab, section Embedded Binaries
> click the + sign and select the Material.framework and then run the
> project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189621331>
> .
>



-- 
Mike Isbell

**Comment by mohpor** [comment]
If you can run on device but can not run on a simulator, the only reason could be that x86 arch is not included in the framework. Cleaning the material project first and re-run should solve this.

**Comment by misbell** [comment]
[image: Inline image 1]

On Sat, Feb 27, 2016 at 2:01 AM, Chaitanya Ramji <notifications@github.com>
wrote:

> Hey @misbell <https://github.com/misbell>,
> Did you add the Material framework to your project? Check out the Installation
> guide <https://github.com/CosmicMind/Material/wiki/Installation> for use
> with Pods and Carthage. Incase you are not using either, directly drag and
> drop the Material.xcodeproj into your project. Add it as an embedded
> binary, select Material as a Target, Compile and Build. This should work
> for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189592845>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
[image: Inline image 1]

here's a video



On Sat, Feb 27, 2016 at 9:04 AM, M. Porooshani <notifications@github.com>
wrote:

> If you can run on device but can not run on a simulator, the only reason
> could be that x86 arch is not included in the framework. Cleaning the
> material project first and re-run should solve this.
>
>
> On Feb 27, 2016, 5:31 PM +0330, Michael Prenez-Isbell<
> notifications@github.com>, wrote:
> > found the page, framework won't install in embedded binary.
> >
> > wait, why won't it run on the simulator? what's that about?
> >
> > On Sat, Feb 27, 2016 at 6:45 AM, M. Porooshani<notifications@github.com>
> > wrote:
> >
> > >When you open the examples workspace, in Project Navigator select the
> > >project you want to run and in General tab, section Embedded Binaries
> > >click the + sign and select the Material.framework and then run the
> > >project.
> > >
> > >—
> > >Reply to this email directly or view it on GitHub
> > ><
> https://github.com/CosmicMind/Material/issues/185#issuecomment-189621331>
> > >.
> > >
> >
> >
> >
> > --
> > Mike Isbell
> >
> > —
> > Reply to this email directly orview it on GitHub(
> https://github.com/CosmicMind/Material/issues/185#issuecomment-189644286).
>
> >
> >
> >
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189645363>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
https://www.dropbox.com/s/o80a0300z28ut6a/Material.mp4?dl=0

here's a video of my attempt to run Material


On Sat, Feb 27, 2016 at 2:01 AM, Chaitanya Ramji <notifications@github.com>
wrote:

> Hey @misbell <https://github.com/misbell>,
> Did you add the Material framework to your project? Check out the Installation
> guide <https://github.com/CosmicMind/Material/wiki/Installation> for use
> with Pods and Carthage. Incase you are not using either, directly drag and
> drop the Material.xcodeproj into your project. Add it as an embedded
> binary, select Material as a Target, Compile and Build. This should work
> for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189592845>
> .
>



-- 
Mike Isbell

**Comment by danieldahan** [comment]
When you build the framework, build it on Generic device or device. Embedded frameworks won't work unless that is done. Then when you build the project you want to run, you can choose a simulator or device.

**Comment by mohpor** [comment]
@danieldahan I have a vivid memory that it's not true. You can build frameworks for simulators too, and you can use that framework or running on simulators afterwards. Or you can make a fat binary using lipo that will make you able to run a project on both simulators and devices.

**Comment by misbell** [comment]
https://www.dropbox.com/s/o80a0300z28ut6a/Material.mp4?dl=0

here's a video of my attempt to run Material

On Sat, Feb 27, 2016 at 9:35 AM, M. Porooshani <notifications@github.com>
wrote:

> @danieldahan <https://github.com/danieldahan> I have a vivid memory that
> it's not true. You can build frameworks for simulators too, and you can use
> that framework or running on simulators afterwards. Or you can make a fat
> binary using lipo that will make you able to run a project on both
> simulators and devices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189652890>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
https://www.dropbox.com/s/o80a0300z28ut6a/Material.mp4?dl=0

here's a video of my attempt to run Material

On Sat, Feb 27, 2016 at 9:27 AM, Daniel Dahan <notifications@github.com>
wrote:

> When you build the framework, build it on Generic device or device.
> Embedded frameworks won't work unless that is done. Then when you build the
> project you want to run, you can choose a simulator or device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189651585>
> .
>



-- 
Mike Isbell

**Comment by danieldahan** [comment]
@mohpor You are probably right, but in this instance, @misbell I noticed in your video you are not building the framework on Generic Device, or a device, it is being built on the simulator. Try building the framework on Generic Device, and then when choosing to build the App, use simulator.

**Comment by danieldahan** [comment]
<img width="1440" alt="screen shot 2016-02-27 at 9 45 08 am" src="https://cloud.githubusercontent.com/assets/9982123/13373475/d8585f74-dd36-11e5-85a6-53efa5a397e7.png">

**Comment by misbell** [comment]
Daniel your answer turned out to be correct. Thank you for the help.

On Sat, Feb 27, 2016 at 9:45 AM, Daniel Dahan <notifications@github.com>
wrote:

> [image: screen shot 2016-02-27 at 9 45 08 am]
> <https://cloud.githubusercontent.com/assets/9982123/13373475/d8585f74-dd36-11e5-85a6-53efa5a397e7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/185#issuecomment-189654899>
> .
>



-- 
Mike Isbell

**Comment by danieldahan** [comment]
@mohpor @chaitanya-ramji Thanks for your help.

@misbell Happy to help :)
