### ISSUE TITLE
Error on NavigationBarView storyboard run on device.

### ISSUE THREAD

**Issue by misbell** [CosmicMind/Material#187]
2016-02-27 16:49:59.338 NavigationBarView[5613:2626129] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 10]'
*** First throw call stack:
(0x183ec5900 0x183533f80 0x183ec5848 0x1865b9800 0x1865b975c 0x1865b96f4 0x188bafbe8 0x1000f9494 0x1000f784c 0x1000f789c 0x10012bb94 0x10012c4bc 0x188bb3778 0x1000c4be0 0x1000c4cfc 0x1865c2b2c 0x1865bd738 0x188bca454 0x1001a563c 0x10012c500 0x1001a55bc 0x1001a55f0 0x188bb24a4 0x188bb2178 0x188bbfb80 0x188ebc640 0x1891a267c 0x1891a23c4 0x18908215c 0x1891a267c 0x1891a27f4 0x1891a23c4 0x189081490 0x188f2b33c 0x188cf4250 0x188bb7d6c 0x188bb7cc4 0x188bbeab4 0x188bbbfa0 0x188c31cd0 0x188e5c358 0x188e604b8 0x188e5d5c0 0x18547b790 0x18547bb10 0x183e7cefc 0x183e7c990 0x183e7a690 0x183da9680 0x188c26580 0x188c20d90 0x100056090 0x18394a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

![new_issue_ _cosmicmind_material_and_appdelegate_swift](https://cloud.githubusercontent.com/assets/356572/13375613/888d4144-dd72-11e5-8028-564edbedd25c.png)

**Comment by danieldahan** [comment]
Hmmm.... I ran the project now and didn't have the error. Could you share more about your setup?

**Comment by misbell** [comment]
well...every other project runs okay. I'm running using XCode 7C1002
(7.2.1) on a device with 9.2.1 installed, an iPhone Six Plus.

I tried deleting the installed non storyboard app and running again, same
result.



On Sat, Feb 27, 2016 at 4:57 PM, Daniel Dahan <notifications@github.com>
wrote:

> Hmmm.... I ran the project now and didn't have the error. Could you share
> more about your setup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/187#issuecomment-189735677>
> .
>



-- 
Mike Isbell

**Comment by misbell** [comment]
crashes on the simulator too

On Sat, Feb 27, 2016 at 5:21 PM, Michael Prenez-Isbell <
michael.isbell@gmail.com> wrote:

> well...every other project runs okay. I'm running using XCode 7C1002
> (7.2.1) on a device with 9.2.1 installed, an iPhone Six Plus.
>
> I tried deleting the installed non storyboard app and running again, same
> result.
>
>
>
> On Sat, Feb 27, 2016 at 4:57 PM, Daniel Dahan <notifications@github.com>
> wrote:
>
>> Hmmm.... I ran the project now and didn't have the error. Could you share
>> more about your setup?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CosmicMind/Material/issues/187#issuecomment-189735677>
>> .
>>
>
>
>
> --
> Mike Isbell
>
>


-- 
Mike Isbell

**Comment by misbell** [comment]
tried it on a few other simulators, same result.

On Sat, Feb 27, 2016 at 5:22 PM, Michael Prenez-Isbell <
michael.isbell@gmail.com> wrote:

> crashes on the simulator too
>
> On Sat, Feb 27, 2016 at 5:21 PM, Michael Prenez-Isbell <
> michael.isbell@gmail.com> wrote:
>
>> well...every other project runs okay. I'm running using XCode 7C1002
>> (7.2.1) on a device with 9.2.1 installed, an iPhone Six Plus.
>>
>> I tried deleting the installed non storyboard app and running again, same
>> result.
>>
>>
>>
>> On Sat, Feb 27, 2016 at 4:57 PM, Daniel Dahan <notifications@github.com>
>> wrote:
>>
>>> Hmmm.... I ran the project now and didn't have the error. Could you
>>> share more about your setup?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/CosmicMind/Material/issues/187#issuecomment-189735677>
>>> .
>>>
>>
>>
>>
>> --
>> Mike Isbell
>>
>>
>
>
> --
> Mike Isbell
>
>


-- 
Mike Isbell

**Comment by misbell** [comment]
also just tried it on an iPad Air purchased in late 2015, same result.

**Comment by misbell** [comment]
FWIW just ran the graph project, all projects ran on sim and device.

**Comment by misbell** [comment]
https://www.dropbox.com/s/vp27lbl4d3ysexn/navbarstoryboard.mp4?dl=0

**Comment by misbell** [comment]
also, we can do a join.me session if you want to poke around on my system. how's that for accomodating :-)

**Comment by danieldahan** [comment]
I am looking into this today. If needed, a join.me session sounds good.

**Comment by danieldahan** [comment]
Can you try 1.34.9 and see if the issue persists?

**Comment by misbell** [comment]
will do

On Sun, Feb 28, 2016 at 12:27 PM, Daniel Dahan <notifications@github.com>
wrote:

> Can you try 1.34.9 and see if the issue persists?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/187#issuecomment-189911176>
> .
>



-- 
Mike Isbell

**Comment by danieldahan** [comment]
I haven't been able to reproduce this issue. If you continue to have the issue, please reopen the ticket, or create a new one. All the best :)

**Comment by misbell** [comment]
Will do, work is taking up my time today.
