### ISSUE TITLE
Question: MaterialTabViewController

### ISSUE THREAD

**Issue by chaitanya-ramji** [CosmicMind/Material#193]
Hey,
When would you be releasing MaterialTabViewController?

**Comment by danieldahan** [comment]
As early as this week, and no later than Monday.

**Comment by chaitanya-ramji** [comment]
Cool. Thanks :)

**Comment by ahusseini** [comment]
@danieldahan any update on MaterialTabViewController? Thank you for all your hard work!

**Comment by chaitanya-ramji** [comment]
Any ETA on the TabBar @danieldahan ?

**Comment by danieldahan** [comment]
Hey, sorry for the delay on this component. I will put this at the top of the list for new components for this week. If it is not out by Friday, then I will have a better estimate of the time it will be available.

**Comment by chaitanya-ramji** [comment]
Cool @danieldahan :D Thanks man!
