### ISSUE TITLE
NavigationBarView wrong height in iPad landscape

### ISSUE THREAD

**Issue by ajkiosd** [CosmicMind/Material#196]
wrong height in iPad landscape

<img width="85" alt="screen shot 2016-03-02 at 8 49 21 am" src="https://cloud.githubusercontent.com/assets/4210881/13451390/dd7799aa-e053-11e5-880a-19f0e123805b.png">

seams device type not checked here:

```swift
// General alignment.
		if UIApplication.sharedApplication().statusBarOrientation.isLandscape {
			grid.contentInset.top = 8
			height = 44
		} else {
			grid.contentInset.top = 28
			height = 64
		}
```

**Comment by danieldahan** [comment]
We will have a fix for this tomorrow. Thank you for submitting this.

**Comment by danieldahan** [comment]
This has been confirmed and we will have a fix for later today. Thank you!

**Comment by danieldahan** [comment]
Try [1.35.1](https://github.com/CosmicMind/Material/releases/tag/1.35.1). If the issue persists, reopen the issue or create a new one. Thank you for submitting this issue.
