### ISSUE TITLE
Using SearchBarViewController brakes on run

### ISSUE THREAD

**Issue by pml2571** [CosmicMind/Material#197]
Hi, 
I'm trying to add serchbar on my existing project using SearchBarViewController following exactly your sample project provided. But when i run it on my device it breaks. I attached the screenshot where it shows the breakpoint which is from actual SearchBarViewController.swift file. Any help would be appreciated. Thanks

![screen shot 2016-03-01 at 9 46 54 pm](https://cloud.githubusercontent.com/assets/3819719/13451790/2fcc1238-dff7-11e5-8918-f2f43334eeec.png)

How I implemented it:
(SearchTableVC is UIVIewController embedded to UINavigationContorller in storyboard.)
`class SearchTableVC: SearchBarViewController, UITableViewDelegate, UITableViewDataSource, TextFieldDelegate {...`

 `override func viewDidLoad() {
        super.viewDidLoad()
        self.prepareView()
        self.prepareSearchBarView()
}`

And the function to prepare searchbar:
`    
    func prepareSearchBarView() {
        
        var image = UIImage(named: "ic_close_white")?.imageWithRenderingMode(.AlwaysTemplate)

        
        let clearButton: FlatButton = FlatButton()
        clearButton.pulseColor = MaterialColor.blueGrey.darken4
        clearButton.pulseScale = false
        clearButton.tintColor = MaterialColor.blueGrey.darken4
        clearButton.setImage(image, forState: .Normal)
        clearButton.setImage(image, forState: .Highlighted)
        clearButton.setTitle("Clear", forState: .Normal)
        
        // Back button.
        image = UIImage(named: "ic_arrow_back_white")?.imageWithRenderingMode(.AlwaysTemplate)
        let backButton: FlatButton = FlatButton()
        backButton.pulseColor = MaterialColor.blueGrey.darken4
        backButton.pulseScale = false
        backButton.tintColor = MaterialColor.blueGrey.darken4
        backButton.setImage(image, forState: .Normal)
        
        backButton.setImage(image, forState: .Highlighted)
        backButton.setTitle("Back", forState: UIControlState.Normal)
        
        // Switch control.
        //let switchControl: MaterialSwitch = MaterialSwitch(state: .Off, style: .Default, size: .Small)
        
        // More button.
        image = UIImage(named: "ic_more_horiz_white")?.imageWithRenderingMode(.AlwaysTemplate)
        let moreButton: FlatButton = FlatButton()
        moreButton.pulseColor = MaterialColor.blueGrey.darken4
        moreButton.pulseScale = false
        moreButton.tintColor = MaterialColor.blueGrey.darken4
        moreButton.setImage(image, forState: .Normal)
        moreButton.setImage(image, forState: .Highlighted)

        
        searchBarView.statusBarStyle = .Default
        
        searchBarView.delegate = self
        searchBarView.placeholder = "Search"
        searchBarView.tintColor = MaterialColor.blueGrey.darken4
        searchBarView.textColor = MaterialColor.blueGrey.darken4
        searchBarView.placeholderTextColor = MaterialColor.blueGrey.darken4
        searchBarView.textField.font = RobotoFont.regularWithSize(20)
        searchBarView.textField.delegate = self
        
        searchBarView.clearButton = clearButton
        //searchBar.leftControls = [backButton]
        searchBarView.rightControls = [backButton]
        
    }
    
`

` override func prepareView() {
        super.prepareView()
    }`

**Comment by danieldahan** [comment]
The code looks to reference a navigationBarView. When I look at the [SearchBarViewController](https://github.com/CosmicMind/Material/blob/master/Sources/SearchBarViewController.swift), the code is not the same. What Material version are you using?

**Comment by pml2571** [comment]
Sorry, I just updated the screenshot attached. The old screenshot was when i was trying to use NavigationBarViewController.swift But they both giving same error.

**Comment by danieldahan** [comment]
I believe it is because of the storyboard constraints, they are breaking with the height change that is being made in the layoutSubviews method. In the morning, we will look into this. Thank you.

**Comment by danieldahan** [comment]
Please try version [1.35.1](https://github.com/CosmicMind/Material/releases/tag/1.35.1). If the issue persists, reopen the issue or create a new one. Thank you for submitting this.

**Comment by danieldahan** [comment]
Sorry, this is persisting. I will make another update.

**Comment by pml2571** [comment]
I got it worked. I figured that SearchBarView uses custom UIView on storyboard. However,  where would be the best place to change the background color of SearchBarView or SearchBarNavigationController? 
I tried `searchBarView.backgroundColor = MaterialColor.green.base` but it's not changing it.

**Comment by danieldahan** [comment]
That should work. Make sure in your storyboard you don't have an overriding value in the settings.
