### ISSUE TITLE
NavigationBarView rightControls not appear in PresentationStyleFormSheet

### ISSUE THREAD

**Issue by ajkiosd** [CosmicMind/Material#198]
when i use NavigationBarView in viewController  and set FormSheet for PresentationStyle, rightControls of NavigationBarView not appear 
```swift
        vc.modalPresentationStyle = .FormSheet
```
before PresentationStyle change
<img width="106" alt="screen shot 2016-03-02 at 9 14 49 am" src="https://cloud.githubusercontent.com/assets/4210881/13451763/4eabd6ec-e057-11e5-9aff-b9442cb0fec8.png">
after PresentationStyle change
<img width="124" alt="screen shot 2016-03-02 at 9 14 18 am" src="https://cloud.githubusercontent.com/assets/4210881/13451768/548bc63a-e057-11e5-8b2c-080b09a6f97a.png">

also height of NavigationBarView is more then default when presentation in FormSheet:
<img width="571" alt="screen shot 2016-03-02 at 9 17 00 am" src="https://cloud.githubusercontent.com/assets/4210881/13451818/de1b8ef8-e057-11e5-8494-ed7677f2ab11.png">

**Comment by danieldahan** [comment]
Thank you for this. Tomorrow we will look into this.

**Comment by ajkiosd** [comment]
this issue fixed in 1.35.1 Thanks.
just issue of NavigationBarView's height persists:
<img width="560" alt="screen shot 2016-03-03 at 8 31 33 am" src="https://cloud.githubusercontent.com/assets/4210881/13485200/7b137cc6-e11a-11e5-9521-c71ac77bf903.png">

**Comment by danieldahan** [comment]
The height issue is most likely due to the NavigationBarView being a subclass of StatusBarView, which is used for views that are affected by the StatusBar. Can you try to use a ControlView. It has the left and right UIControl features, but doesn't have a set size.

**Comment by ajkiosd** [comment]
i try ControlView and height issue resolved. but because of control's size i prefer NavigationBarView with wrong height

![untitled](https://cloud.githubusercontent.com/assets/4210881/13497224/7e433b1c-e169-11e5-8e83-fbaee1cef467.png)

Thanks anyway :)

**Comment by danieldahan** [comment]
We are working on Navigation and UIViewController updates. This will be addressed in those. Thank you for bringing this to our attention. All the best :)
