### ISSUE TITLE
Minimum deployment target

### ISSUE THREAD

**Issue by kruyvanna** [CosmicMind/Material#201]
Hi,

In you project description page you said minimum deployment is 8.0
But when I build it says minimum is 9.2 

<img width="706" alt="screen shot 2016-03-04 at 4 59 19 pm" src="https://cloud.githubusercontent.com/assets/1171793/13523923/df1f9ac2-e22a-11e5-8c56-7801625a06a2.png">

**Comment by danieldahan** [comment]
Hmmm.... I am seeing 8.0 on my end. Is this on a new project you are making or an example one?

**Comment by danieldahan** [comment]
Please checkout version [1.35.3](https://github.com/CosmicMind/Material/releases/tag/1.35.3) :)
