### ISSUE TITLE
Make NavigationBarViewController independent of the navigation

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#202]
Can we make `NavigationBarViewController` independant of the navigation requirement? In other words, what if I wanted to present a view controller that should have the `NavigationBarView`? Now it will crash on this (because it doesn't have `mainViewController`):
```swift
	/// Layout subviews.
	private func layoutSubviews() {
		let size: CGSize = UIScreen.mainScreen().bounds.size
		let h: CGFloat = UIApplication.sharedApplication().statusBarFrame.size.height
		mainViewController.view.frame = CGRectMake(0, navigationBarView.height, size.width, size.height - navigationBarView.height - (20 >= h ? 0 : h - 20))
	}
```
Or you can provide a class that has the `NavigationBarView` in it without all the other stuff.

**Comment by danieldahan** [comment]
Why not use a NavigationBarView itself and that's it in your own view?

**Comment by sohayb** [comment]
I was thinking Android 😁, like `ActionBarActivity` would have the actual `ActionBar` but has nothing to do with navigation. And you `NavigationBarView` has the same concept. Same thing goes for the regular `UIViewController` which has a `navigationItem` property.

**Comment by danieldahan** [comment]
Your best bet is to use the NavigationBarView as a child view of a UIViewController, and then you won't have any issue with the `mainViewController`. That's what you mean right?

**Comment by sohayb** [comment]
Exactly :+1:

**Comment by danieldahan** [comment]
Great :) If you need an example of that, there is a NavigationBarView example project :)
