### ISSUE TITLE
TitleLabel floating when TextField is focused

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#203]
Can we make the title label float whenever the TextField is focused and not when it starts editing.

**Comment by danieldahan** [comment]
Not 100% sure I understand what you are asking. May you elaborate?

**Comment by sohayb** [comment]
Right now, the title label in `TextField` floats (moves up) whenever a there's input but not just when it becomes `firstResponder`, which I think should be the case.

**Comment by danieldahan** [comment]
Hmm... that is not how I have seen it done. I have only seen it that when you change the text, from the placeholder it appears. I don't think it would make sense to have the placeholder display the same value as the titleLabel. Am I missing something here, or is this a one-off need?

**Comment by sohayb** [comment]
Sorry about this but again I'm copying Android behavior, this is the way text fields behave there. I need to double check the material specs for that, since you're not copying android, rather implementing Material design specs.

**Comment by danieldahan** [comment]
Well the idea is that we can improve on what has been done, not necessarily copy it verbatim. The goal of Material is to bring the look and feel in combination with Apple's concepts into one place. Not necessarily adhere to everything, as iOS is not Android.

**Comment by sohayb** [comment]
You're right, that's why I mentioned that I need to check the specs :). Well it's as I mentioned in the specs [Labels](https://www.google.com/design/spec/components/text-fields.html#text-fields-input)

**Comment by danieldahan** [comment]
Now I am missing something even more... lol :) The visuals I see only show the titleLabel when there is text.

**Comment by sohayb** [comment]
haha :) well it's not the visuals, they aren't showing any animation there, it's the description, and I quote "When the user engages with the text input field, the floating inline labels move to float above the field."

**Comment by danieldahan** [comment]
Ah... Well then, now we got something. Yes, that is the spec. Okay, We should make the change then.

**Comment by danieldahan** [comment]
This is now fixed in 1.39.0. :)

**Comment by sohayb** [comment]
Awesome 😍
