### ISSUE TITLE
Upgrading from 1.33.2 to 1.34.10 breaks the detailLabel

### ISSUE THREAD

**Issue by crewshin** [CosmicMind/Material#204]
It will show up for a split second, then disappear.

I have a TextField setup to display when an email is invalid on "Editing Changed". The detail label simply says Email is invalid and only shows up on each keystroke until my regex matches. With each letter, it pops up for a split second.

**Comment by danieldahan** [comment]
Try setting the TextField detailLabelAutoHideEnabled property to false.

```swift
textField.detailLabelAutoHideEnabled = false
```

In the 1.34.* series, the auto hide flag for TextFields was added. The default is true.

**Comment by crewshin** [comment]
Hah! Very cool.

Thanks.

**Comment by danieldahan** [comment]
:) Anytime
