### ISSUE TITLE
Ripple effect triggered when scrolling

### ISSUE THREAD

**Issue by smkhalsa** [CosmicMind/Material#207]
I've noticed that when scrolling though a table with MaterialTableViewCells, the ripple effect animation gets triggered on items that my finger touches as I scroll down. 

I would expect the ripple animation to only be triggered when an item is actually pressed. 

I believe this is because we are using the touchesBegan / touchesEnded method which is triggered with any contact, not just a definitive tap / press.

**Comment by danieldahan** [comment]
This is a nice catch. We will update this in our next release. Thank you!

**Comment by danieldahan** [comment]
This seems to be an issue when using a CollectionView or TableView and not having a select item. 
Also, CollectionViews and TableViews reuse cells, so sometimes, when scrolling fast the pulse is still animating while generating a new cell. This should be handled within in the CollectionView or TableView.

Please check if this issue still persists, and if so, reopen or create a new issue. Thank you!
