### ISSUE TITLE
SideNav + UIScrollView

### ISSUE THREAD

**Issue by vamseems** [CosmicMind/Material#208]
There seems to be a problem when using SideNav and mainViewController is UIScrollView. The scrolling of the view is overridden by the gesture recogniser for the SideNav.

**Comment by danieldahan** [comment]
In the Examples Programmatic directory, the App project uses a UICollectionView as the mainViewController. That may help you. 

If you share some code, I can further assist :)

**Comment by vamseems** [comment]
Sorry my bad. Figured it out

**Comment by danieldahan** [comment]
Great! :)
