### ISSUE TITLE
MaterialCollectionViewCell Shadow Performance

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#213]
I'm not sure if this is a bug, but simply setting the depth does not trigger the shadow path unless enabled. Might be related to #186 when it was addressed.

```swift
cell.shadowPathAutoSizeEnabled = true // App lags without this
cell.depth = .Depth1
```

**Comment by danieldahan** [comment]
Hey :) This has been fixed in 1.36.0. All the best!
