### ISSUE TITLE
Feature request: Material Tabs

### ISSUE THREAD

**Issue by hisham2007** [CosmicMind/Material#214]
Dears,
        Thank you for great work. I wish if you can add Material tabs:
[https://www.google.com/design/spec/components/tabs.html#tabs-usage](url)

Many thanks,
Hisham

**Comment by danieldahan** [comment]
Yes, this is coming up :)

**Comment by danieldahan** [comment]
Closing this for now as it will be coming out shortly. Basically once we workout the kinks with NavigationController, we will be adding the tabs as a separate and combined view.
