### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hisham2007** [CosmicMind/Material#216]
sorry for asking many questions today. as I am assessing Material framework before starting our new project. I want to make sure that it is easy to support RTL as we will develop Arabic app with Arabic language only so we want to enforce RTL. I switched language of device but found Material didnt mirror layout. Please advise.

Thank you,
Hisham

**Comment by danieldahan** [comment]
Nice, question. This should be a feature request, and we will make it happen. So let’s leave this issue up. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
This is now added to upcoming :) Thank you!
