### ISSUE TITLE
Material Button: pulse hides on button's highlighted state

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#217]
Please, implement the corresponding flag that would control whether pulse hides or stays not hidden on button's highlighted state. Current implementation contradicts google's guide (Components -> Buttons -> Behavior). Thank you

**Comment by waterskier2007** [comment]
I'd like to take a look at this, but I'm not seeing where in the Behavior section that shows a button pulse staying persistent. Under what conditions would a button remain 'highlighted'?

**Comment by RuslanPatyk** [comment]
Brendan,

A button is highlighted when user did tap it and holding it down, to say in google’s terminology, there is a focus on that button.

Below is a link to google’s video showing the behavior of pulse when we are having focus on the button. Please watch:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFRmZDbzdkSEp0ZEk/components-buttons-raisedbuttons.webm <https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFRmZDbzdkSEp0ZEk/components-buttons-raisedbuttons.webm>

Thank you,
Ruslan

**Comment by danieldahan** [comment]
A flag for this feature is doable. Over the weekend I am going to be making adjustments for this issue [207](https://github.com/CosmicMind/Material/issues/207). This would be a good time to make the adjustment you are suggesting.

**Comment by danieldahan** [comment]
This is fixed in development and will be released in 1.36.1, which should be out later today. Thank you! Closing this ticket to cleanup.
