### ISSUE TITLE
NavigationBarView doesn't update layout after frame changed

### ISSUE THREAD

**Issue by TheHmmka** [CosmicMind/Material#223]
This is my first part of code:

```
self.playerView = [MaterialPulseView new];
self.playerView.backgroundColor = [UIColor blackColor];
self.playerView.pulseColor = [UIColor whiteColor];
self.playerView.pulseScale = NO;
self.playerView.masksToBounds = YES;
[self addSubview: self.playerView];

FlatButton* closeButton = [FlatButton new];
closeButton.pulseColor = [UIColor whiteColor];
closeButton.pulseScale = NO;
[closeButton setImage: [UIImage imageNamed: @"CloseIcon"] forState: UIControlStateNormal];
[closeButton addTarget: self action: @selector(closeButtonTouchSelector) forControlEvents: UIControlEventTouchUpInside];
	
FlatButton* moreButton = [FlatButton new];
moreButton.pulseColor = [UIColor whiteColor];
moreButton.pulseScale = NO;
[moreButton setImage: [UIImage imageNamed: @"SettingsSectionIcon"] forState: UIControlStateNormal];
[moreButton addTarget: self action: @selector(moreButtonTouchSelector) forControlEvents: UIControlEventTouchUpInside];
	
self.navigationBarView = [[NavigationBarView alloc] initWithTitleLabel: titleLabel detailLabel: detailLabel leftControls: @[closeButton] rightControls: @[moreButton]];
self.navigationBarView.backgroundColor = BLUE_COLOR;
[self.playerView addSubview: self.navigationBarView];
```

This is second part:

```
-(void) layoutSubviews
{
	[super layoutSubviews];
	
	self.playerView.frame = self.bounds;
}
```

The problem is that NavigationBarView doesn't update layout (or do it bad) after changing the frame of superview. I can't see "moreButton" at the right of navigation bar. This is result:

<img width="487" alt="screenshot 2016-03-14 15 32 31" src="https://cloud.githubusercontent.com/assets/468660/13744621/06b0e8bc-e9fa-11e5-8f2f-e199e69308e5.png">

**Comment by danieldahan** [comment]
I will take a look at this later today. Thank you!

**Comment by danieldahan** [comment]
Please try 1.37.0, if the issue persists, reopen the issue, or create a new one. All the best!

**Comment by TheHmmka** [comment]
Oh, you deleted NavigationBarView, need some time to make changes. :-)

**Comment by danieldahan** [comment]
Yes it is called Toolbar now, and there is a NavigationBar :) So it shouldn't be too bad.

**Comment by TheHmmka** [comment]
Thanks for info :-)

**Comment by TheHmmka** [comment]
Nope. 1.37.0 didn't help.
Btw I think it's time to create prefix for classes like MToolbar or MNavigationBar :-)

**Comment by danieldahan** [comment]
Hmm...

**Comment by TheHmmka** [comment]
And may be you can tell me, how to change controls paddings in Toolbar, cause they were changed?

**Comment by danieldahan** [comment]
Okay, I will see if I can replicate your issue using your code. I think the issue is arising when you make the Toolbar a child of the pulseView. 

Also, to update the insets and padding.... 

using `toolbar.contentInset` and `toolbar.spacing`. 

Also, why make the Toolbar a child of the pulseView, and not a child of the ViewController?

**Comment by TheHmmka** [comment]
In my case even pulseView is not a child of ViewController :-) I have complex structure with several subviews. I need to have one transparent view at the top of any UIViewControllers with different controls like Toolbar, PulseView and so on.

**Comment by danieldahan** [comment]
Ah... okay. I am working on replicating the issue. As well, MaterialLayout may be a good solution here, as it automatically adjusts the views, as an idea.

**Comment by TheHmmka** [comment]
Thanks!

**Comment by danieldahan** [comment]
Can you try adding to your layoutSubviews this line... 

```objc
-(void) layoutSubviews
{
    [super layoutSubviews];

    self.playerView.frame = self.bounds;
   self.toolbar.width = self.bounds.width;
}
```

In anyway I try it, it works for me. So the above is a test to see what happens. If that doesn't work, then there is clearly an issue that I will need to dive into.

**Comment by TheHmmka** [comment]
This code works:

```
-(void) layoutSubviews
{
	[super layoutSubviews];
	
	self.playerView.frame = self.bounds;
	self.navigationBarView.frame = self.playerView.bounds;
}
```

**Comment by danieldahan** [comment]
Great :) as always let us know when there is an issue. All the best!

**Comment by TheHmmka** [comment]
Deal! :-)
