### ISSUE TITLE
XCode can't run tests if the latest version of Material is imported into the project and 'Gather coverage data' is turned-on

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#224]
The project can be built, tests can't. Please, make sure that tests can be run under Material (1.36.0), Material (1.35.0) is OK

Command failed due to signal: Segmentation fault: 11

Everything goes well until you turn on the option 'Gather coverage data' in Test tab in your edit scheme,
but the same project configuration works well on the 1.35 version. 

Thank you

**Comment by danieldahan** [comment]
@RuslanPatyk are these your own tests?

**Comment by RuslanPatyk** [comment]
No, not only. I have alose configured an empty test project, initialized it with cocoa pods, added the only lib Material, made pod install and turned Gather coverage data. You can also try this. My Xcode Version is 7.2.1. Please, try, you should reproduce this issue. Thank you.

**Comment by danieldahan** [comment]
Sweet, will do. We are going to be writing tests for Material aside from the projects. Thank you!

**Comment by RuslanPatyk** [comment]
Is it fixed? Should I pull the updated version?

**Comment by danieldahan** [comment]
It will be in the next release scheduled today. 1.36.1. I am cleaning up the tickets that are left.

**Comment by RuslanPatyk** [comment]
Thank you :)
