### ISSUE TITLE
hideStatusBar Does Not Hide

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#226]
After trying out the **App** example, I noticed that the status bar hides by default when opening the left view controller of SideNavigationViewController. I tried recreating in my project (with CocoaPods) but it doesn't hide, even after using the example code. Can someone reproduce this problem?

**Comment by danieldahan** [comment]
Maybe this has something to do with the info.plist values. Did you set the "View controller-based status bar appearance" to NO?

**Comment by zgosalvez** [comment]
Appreciate your relatively quick response @danieldahan . That did the trick.

Need help with your docs? I am using your library extensively for a project, so there will be a lot of components that I will be dealing with.

**Comment by danieldahan** [comment]
Awesome! 

As for docs, we hired someone who will be working on that extensively, @prateeksan. If anything, keep the questions coming and we will continue to make the notes as we put our documentation together. 

If you want to discuss helping further, message us at support@cosmicmind.io :)

**Comment by zgosalvez** [comment]
Looking forward to them docs @prateeksan !

@danieldahan noticed a quirk when hiding. I initially followed **SideNavigationViewController** example. It hides now, but it doesn't animate and move up as seen in the **App** example. 

Not sure if it's a bug or just a docs thing, but I had to put the _mainViewController_ as a root of a `NavigationController` to get the status bar animation.

**Comment by prateeksan** [comment]
@zgosalvez thank you! Your feedback is and will be much appreciated.

**Comment by danieldahan** [comment]
Taking a look now.

**Comment by zgosalvez** [comment]
More info if it helps: my _mainViewController_ is a `NavigationBarViewController`

**Comment by danieldahan** [comment]
Yes that does make a difference. The animation you are seeing is specific to the NavigationBar that is part of the NavigationController. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by zgosalvez** [comment]
I see. So, I ended up not using `NavigationBarViewController` and used `navigationItem` property of `NavigationController` as implemented in the **App** example. Strange that I had to do that tho. Thanks.

**Comment by danieldahan** [comment]
NavigationItem is the correct way to set nav items in iOS.
NavigationBarView is a replica so it behaves differently.

There is also a standalone NavigationBar example that is a subclass of
UINavigationBar.

This is all a part of an effort to built out our nav controls. Since they
are all new, the API is being fleshed out.
