### ISSUE TITLE
TextField Bottom Border Thickness

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#228]
The TextField's bottom border thickness/height cannot be customised. Material Design docs show that when the text field is active or has detail shown, the border thickens.

**Comment by danieldahan** [comment]
Have you tried playing with the `bottomBorderLayer` and `bottomBorderLayerDistance` ? Good point on the thickness of the bottom border. I am going to link this issue [203](https://github.com/CosmicMind/Material/issues/203)

**Comment by zgosalvez** [comment]
I did play around with `bottomBorderLayer` and changed the height from 1 to 2 and looked close to the Material Design docs.

**Comment by danieldahan** [comment]
Cool, we will perfect it when we make the changes to 203. Awesome catch :)

**Comment by danieldahan** [comment]
This is now fixed in 1.39.0. Thank you for bringing this to our attention :)
