### ISSUE TITLE
TextField Clear Button Customization

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#229]
Allow us to handle/override the `clearButton`'s action.

In my case, I need to implement a password text field but can't get the visibility icon to work using the `clearButton` property.

Reference: [Material Design: Password Input](https://www.google.com/design/spec/components/text-fields.html#text-fields-password-input)

**Comment by danieldahan** [comment]
To avoid the clear functionality that is added to the clearButton when set, you can add the button to the textField, then clear the handlers, and then add your own.

**Comment by zgosalvez** [comment]
Great. You've been helpful by giving a workaround.

This worked for me in the mean time:
```swift
passwordTextField.clearButton = clearButton
clearButton.removeTarget(passwordTextField, action: "handleClearButton", forControlEvents: .TouchUpInside)
clearButton.addTarget(self, action: "handleClearButton", forControlEvents: .TouchUpInside)
```

**Comment by danieldahan** [comment]
Yes, that is perfect. I will link this to [203](https://github.com/CosmicMind/Material/issues/203) as well.

**Comment by danieldahan** [comment]
In 1.39.0, which will be released shortly, there is a boolean flag ```clearButtonAutoHandleEnabled``` that when set to ```false``` disables the automatic handling for clearing the TextField ```text```. Thank you and all the best!
