### ISSUE TITLE
NavigationController Missing Back Arrow Button

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#231]
Modified **App** example's `AppDelegate` to simply set:

```swift
window!.rootViewController = AppNavigationController(rootViewController: RecipesViewController())
```

This works because tapping on a recipe pushes the `ItemViewController` onto the `navigationController` and the back button is a back arrow button (not the iOS left chevron).

However, in my project, I am unable to reproduce this desired effect. I also have 2 controllers that do the same flow as the **App** example.

- `AppNavigationController` (same code as the example; `rootViewController` is `FirstViewController`).
- `FirstViewController` (has a button that pushes a `UIViewController` on to the `navigationController`).

Doing this does not show any content on the `navigationBar`, even the back arrow button in the `UIViewController`. I checked `ItemViewController` if there's any manual setup for this but didn't find any.

**Comment by danieldahan** [comment]
I am making changes to the nav bar for the next release. I meant to push it yesterday, but I found a few issues I would like to smooth out. Once my changes are done, I will test against this and see if all works.

**Comment by zgosalvez** [comment]
Found out that the button is there, because I can tap the left side and a pulse shows before popping back. I already checked the Assets for the back arrow icon in `App` example, but couldn't find it there yet it appears when running. Finally found it in `SearchBarView` example and copied it into my project. So now it works! The `App` example is somehow using the icon from `SearchBarView` example instead of its own assets.

**Comment by danieldahan** [comment]
I think the reason the button image may not be loading is because Cocoapods is not configured correctly to bring in the Assets bundle, located in Material. I am looking into this, but that would be my initial thought. The image you are loading in App, is actually using the icon from Material itself, MaterialIcon.arrowBack. I have added commonly used icons, as I go, to the Material Assets bundle.

**Comment by zgosalvez** [comment]
In that case, it appears that icons aren't being loaded when using Cocoapods. I've manually had to import the assets when using `MaterialIcon` for it to work. For now I initialise `UIImage` instead since I like using PDF versions of the assets.

**Comment by danieldahan** [comment]
Cool. This issue is really a bug with the configuration for cocoapods.

**Comment by danieldahan** [comment]
I am closing this issue and making another that accurately depicts the issue. Thank you!
