### ISSUE TITLE
Changes to placeholder text are not propagated to the title label

### ISSUE THREAD

**Issue by brandonroth** [CosmicMind/Material#232]
Steps to recreate:

1. Add a TextField and set the placeholder text.
2. Type type
3. Programatically clear the textfield and update the placeholder text to something else.
4. The placeholder text will be accurate, but after inputing text the title label reflects the previous placeholder.

This (without workarounds) makes it diffucult to reuse the same textfield for multiple input types.

**Comment by danieldahan** [comment]
This wasn't a bug. It was to allow the title text to be different from the placeholder text value. So reuse was not a consideration. Thought, the spec dictates that the title should be the same as the placeholder, so your PR works nicely :) Thank you!
