### ISSUE TITLE
MaterialIcon and loading images using Cocoapods

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#236]
CocoaPods does not load the MaterialIcon images correctly. For now, they will have to be done manually using `UIImage(named: "ic_icon_name")` or any other strategy when setting the icon image. This issue will be fixed once I find a suitable solution.

**Comment by jesusjjf** [comment]
I am attempting to use `UIImage` with` FabButton`, but no image is visible, just red round button. Am I missing something?

```swift
let img1: UIImage? = UIImage(named: "ic_create_white")
let btn3: FabButton = FabButton(frame: CGRectMake(175, 315, 64, 64))
btn3.setImage(img1, forState: .Normal)
btn3.setImage(img1, forState: .Highlighted)
view.addSubview(btn3)
```

**Comment by danieldahan** [comment]
Yes, unless you have the "ic_create_white" image in your project, it won't appear. 

If you update to 1.39.0 -- you can use this instead as an example: 

```swift
let img1: UIImage? = MaterialIcon.add // or a custom pen icon, MaterialIcon.cm.pen
let btn3: FabButton = FabButton(frame: CGRectMake(175, 315, 64, 64))
btn3.setImage(img1, forState: .Normal)
btn3.setImage(img1, forState: .Highlighted)
view.addSubview(btn3)
```

**Comment by jesusjjf** [comment]
Thanks for the reply. Unfortunately I can't get it to work.
Updated to 1.39 and used your example.

Upgraded Material to 1.39.0
![screen shot 2016-04-05 at 11 58 19 pm](https://cloud.githubusercontent.com/assets/2798097/14308357/7f1bb6f0-fb8a-11e5-9b76-c2d28c1e5f4d.png)

 ViewController.swift
![screen shot 2016-04-05 at 11 57 53 pm](https://cloud.githubusercontent.com/assets/2798097/14308365/8a1be7e6-fb8a-11e5-81d2-c5d3ff46256e.png)

Button as it appears:
![screen shot 2016-04-05 at 11 58 42 pm](https://cloud.githubusercontent.com/assets/2798097/14308375/930f3114-fb8a-11e5-809d-dfd59faf125a.png)

**Comment by danieldahan** [comment]
I think it is the bundle identifier. Give me a sec, I am making an update to 1.39.2


---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
Alright, 1.39.3 works :)

**Comment by jesusjjf** [comment]
works! 👍  thank you!

**Comment by leelir** [comment]
When i use 1.40.0, it can't work again. Can you help me?

**Comment by mohpor** [comment]
@leelir what doesn't work exactly?

**Comment by danieldahan** [comment]
@leelir 
What version of CocoaPods are you using?

**Comment by leelir** [comment]
I am using cocoapods-0.39.0 @danieldahan

**Comment by leelir** [comment]
The material icons can not be loaded, when i use the method like this

```swift
let image: UIImage? = MaterialIcon.cm.settings
```

**Comment by danieldahan** [comment]
@leelir  The version you are using (1.0.0.rc.2) is a release candidate, not the 0.39* version that is stable and released. I would downgrade to that version. This is probably because the image bundle handling in the 1*.rc.* version is handling bundles differently.

**Comment by leelir** [comment]
@danieldahan Thank you so much, I'll try to downgrade my pod version.

**Comment by mohpor** [comment]
@danieldahan podsepc should be tested with 1.0.0 version o Pod. I have been using it until last week, every time I ran a pod update with material (and some other pods) they would add a bogus bundle framework that needed to be removed manually from the list of pod targets. It worths investigating on it as the release of pod 1.0.0 is imminent.

**Comment by danieldahan** [comment]
@mohpor Yes testing against it is an excellent idea. Supporting it with a production release we cannot do until it is fully released.

**Comment by mohpor** [comment]
Agreed. Meanwhile, it is release candidate and wouldn't change that much to make any difference and I have faced it from day one of 1.0.0, we should at least find the cause and a solution.

**Comment by danieldahan** [comment]
Yes, I will put a task on this.

**Comment by jamalzafer** [comment]
Still facing this issue with pod version 2.10.2

![simulator screen shot - iphone 8 plus - 2017-10-27 at 17 45 52](https://user-images.githubusercontent.com/2232880/32104663-da7156ca-bb3e-11e7-823a-3ab833661294.png)

**Comment by danieldahan** [comment]
@jamalzafer The issue was fixed in later versions. Please update to the latest, if that is not possible, make sure that you place the size constraints before the position constraints. All the best!
