### ISSUE TITLE
TextView handle out of bounds text, and placeholder alignment. 

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#237]
Hi again,
I've been testing `TextView` in my project today and I've encountered a few bugs I wanted to share.

1. `placeholderLabel` gets positioned to the upper left corner of the text view regardless of any settings of the actual textView itself. I need a right aligned text view but placeholder gets sucked to the left. (I couldn't find a way around it, the placeholder label's frame seems to be encompassing the placeholder text and aligned to the parent, therefore ignoring the text view's alignment.)

2. If the contents of the `TextView` grow beyond its bounds, the text will be visible outside of the text view. This could be easily  solved by setting `clipsToBounds` property of the `TextView` to `true` but that will make `titleLabel` invisible too.

3. In the case of the text being larger than bounds and the `titleLabel` visible, the title label will get scrolled along with the text.

**Comment by danieldahan** [comment]
Hey! Sorry for the late handling on this. It is the next rework on the agenda. Thank you for your patience.

**Comment by mohpor** [comment]
No problem at all. I understand.

**Comment by danieldahan** [comment]
FYI, I will be solving these issues of the next couple days as I rewrite the TextView. Thank you for your patience.

**Comment by Vice-Pre** [comment]
Hello,

For me placeholderlabel don't show is face at all.. I got just the title label correctly.

By the Way of this couple days, if you could add the possibility to have placeholderlabel parameters, and titlelabel.text directly on the user panel of Xcode, it could be useful, don't you think?

Hope that you can make it Great (&fast) :-)
regards,

**Comment by RuslanPatyk** [comment]
Are TextView bugs being fixed? If not, so when do you plan to start? Thank you.:)

**Comment by danieldahan** [comment]
They are. I have already started working on them. They should be all tackled by next week.

**Comment by RuslanPatyk** [comment]
Thank you. By the way, pulse animation is awesome

**Comment by danieldahan** [comment]
@RuslanPatyk Thank you! :) And thanks for bringing it to our attention.

**Comment by danieldahan** [comment]
I am closing this as the notes have been made for the rework. Thank you!

**Comment by joryacooper** [comment]
Are these issues fixed? Or still being worked on? Thanks

**Comment by danieldahan** [comment]
I am currently working on them, and they shouldn't be long.

**Comment by joryacooper** [comment]
Sorry to bother but any updates on this? Thanks for everything.

**Comment by danieldahan** [comment]
You are not bothering me. I am finishing iCloud support for Graph tonight. Then I am going to work on Capture and Editor. Capture is for camera/video and Editor, is the TextView. So it should be soon.
