### ISSUE TITLE
Status bar disappearing

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#239]
Whenever the side drawer is open, the status bar disappears, resulting in bad UX for the user. You can check that directly, as it's even obvious in [the first gif image](https://camo.githubusercontent.com/ecfd0bd7e5ebe8d8c505c0be1da77a630c53f6d9/687474703a2f2f7777772e636f736d69636d696e642e696f2f4d4b2f4d6174657269616c4170702e676966) in this project's home page. Is this a known bug?

**Comment by danieldahan** [comment]
It is not a bug, it is a matter of opinion. You can easily set the instance property of the `sideNavigationController.hideStatusBar = false`.

**Comment by danieldahan** [comment]
@sohayb I am going to update this with a better solution. Thank you for bringing this to my attention. I wasn't so pleased with it, though, I thought launching the NavigationController as is was a better overall approach. All the best!

**Comment by sohayb** [comment]
Sorry, didn't check github since this was posted :) 
Yeah you're right, I think it's a matter of opinion as you said; I still think the UX is not that intuitive to the users nor to developers (having to handle this manually). Waiting your update on this.

**Comment by danieldahan** [comment]
In the latest release, this is fixed :) 1.38.0. Should be out soon.
