### ISSUE TITLE
Starting New Project And Adding Different Of The Examples Into It...

### ISSUE THREAD

**Issue by jacobsgo** [CosmicMind/Material#240]
I started a new Xcode Project and ran "pod init" and then added the stuff into the podfile and then ran "pod install" but I am having trouble actually getting the menu thing into my project. How do I do this?

**Comment by danieldahan** [comment]
Hello,

There are a few projects you can take a look at that will help you. By the "menu thing" are you meaning the floating button at the bottom right that pops-up a group of buttons?

Example 1: This example uses the [Menu](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/Menu) controller. 

Example 2: This example uses a [MenuView](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/MaterialView).

Example 3: This example uses a [MenuViewController](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/MenuViewController).

Example 4: This examples uses a MenuViewController in an example [App](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/App) project.

If you have any questions, please reopen or create a new issue. Looking at the example links should get you started very nicely. 

All the best!
