### ISSUE TITLE
layoutShadowPath() causing custom shadowPath to be overridden

### ISSUE THREAD

**Issue by XemaCobra** [CosmicMind/Material#242]
Hey again,

I've been trying to set a custom shadowPath to a MaterialCollectionViewCell. Unfortunately, it was not working after a bit of digging I found the problem in the following line of code.

https://github.com/CosmicMind/Material/blob/85585b427234fdd798e85e1ae392e1475dc9044a/Sources/MaterialCollectionViewCell.swift#L628

``` Swift
	/// Sets the shadow path.
	internal func layoutShadowPath() {
		if shadowPathAutoSizeEnabled {
			if .None == depth {
				shadowPath = nil
			} else if nil == shadowPath {
				shadowPath = UIBezierPath(roundedRect: bounds, cornerRadius: cornerRadius).CGPath
			} else {
				animate(MaterialAnimation.shadowPath(UIBezierPath(roundedRect: bounds, cornerRadius: cornerRadius).CGPath, duration: 0))
			}
		}
	}
```

I think this is not in MaterialCollectionViewCell alone but in most the Material Views. Not sure what this line does exactly but my guess would be that it maybe needs to use the `shadowPath` instead of a hardcoded one. Something like this:

``` Swift
	/// Sets the shadow path.
	internal func layoutShadowPath() {
		if shadowPathAutoSizeEnabled {
			if .None == depth {
				shadowPath = nil
			} else if nil == shadowPath {
				shadowPath = UIBezierPath(roundedRect: bounds, cornerRadius: cornerRadius).CGPath
			} else {
				animate(MaterialAnimation.shadowPath(shadowPath!, duration: 0))
			}
		}
	}
```

Please let me know if this is a correct solution or not.
Thanks

**Comment by danieldahan** [comment]
Try setting this to false `shadowPathAutoSizeEnabled = false` and then set your path. This way the code block won't have any effect. The last line, is actually to animate the shadowPath on transitions, when you want it to automatically adjust, otherwise, the shadowPath stays where positioned when the item moves.

**Comment by XemaCobra** [comment]
Thanks

**Comment by danieldahan** [comment]
Did it work?

**Comment by XemaCobra** [comment]
Yes, it did. Thanks a lot.

**Comment by danieldahan** [comment]
Awesome, all the best!
