### ISSUE TITLE
Help with custom shaped MaterialViews

### ISSUE THREAD

**Issue by XemaCobra** [CosmicMind/Material#243]
I'm trying to create a MaterialCollectionViewCell with a custom shape based on a CGPath.
I was able to mask the visualLayer and that helped with the pulse. Thanks to your help a few minutes ago, I'm able to customize the shadow as well with the same path. The hard part for me is trying to mask the actual view (`self.layer`) without masking the shadow as well.

As a work around I can just have the view with a clearColor background and draw my path on top but that is not the best solution. Do you have any suggestions?

If not available yet in the library to add a custom path for the view, I'm would be happy to add it and make a pull request. I'll need you to point me in the right direction with it though.

Thanks

**Comment by danieldahan** [comment]
Well the backing layer, `self.layer` is acting as a container for the `visualLayer`. The `layer` is holding the shadow path. If you append your content within the `visualLayer`, which has its mask set to true by default, you should be able to achieve what you are looking for. If I understand you correctly. For example... 

try as an experiment:

```swift
cell.visualLayer.addSublayer(myview.layer)
```

Something like this. This is my first thought.

**Comment by danieldahan** [comment]
Another option is to use a CardView, which has a child view, called detailView. You can add what you like to that, set it to clipBounds, and then apply the path to the CardView.

**Comment by danieldahan** [comment]
Another option is to use a CardView, which has a child view, called detailView. You can add what you like to that, set it to clipBounds, and then apply the path to the CardView. You may need to apply it to the detailView as well. These suggestion have not been tested as I am about to sign-off for the night. If none of these suggestions work, I can work on one tomorrow.

All the best!

**Comment by XemaCobra** [comment]
I'll try them tonight and let you know how it goes. Thanks.

**Comment by XemaCobra** [comment]
I ended up using the first solution (Adding views to the visualLayer as sublayers) as it seemed simpler and more straight forward to me. It works great so far. My only issue, now, is the performance hit from the masking layer that I added. That's unrelated to Material though.  I'll deal with that when I'm optimizing at the end.

Thanks a lot for your help on this.

**Comment by danieldahan** [comment]
You don't need the masking layers now. You should be able to use the `visualLayer` and that's it. The path for the backing `layer` will automatically conform to the `visualLayer`. This is a general statement. I would try the process again with the `visualLayer`. Also, the approach you are taking is an advanced approach and an optimization. Like a hidden gem with what you can do. I am happy you found help here :) All the best!

**Comment by XemaCobra** [comment]
The main reason I still need the masking is to mask the pulse effect to be limited to the custom path that I set originally and not extend beyond the shape.

**Comment by danieldahan** [comment]
The pulse effect is limited to the visualLayer, it is attached to that layer. Hopefully that helps.
