### ISSUE TITLE
If Gather coverage data is turned-on, tests do not run, application can't be built

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#244]
If Gather coverage data is turned-on, tests do not run, application can't be built: 

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

Please explore this issue. It appeared again in 1.37.2.

Thank you

**Comment by danieldahan** [comment]
Hey! Sorry about that. Please checkout [1.37.3](https://github.com/CosmicMind/Material/releases/tag/1.37.3), the issue should be resolved.
