### ISSUE TITLE
CardView width does not work when setting from Storyboard

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#245]
I try to use the CardView from a storyboard but having trouble with the width.
I set the constraint and width in the storyboard, but when I set the title label and a button the size change.

How can I avoid that the CardView width changes from what i put in the storyboard?

**Comment by danieldahan** [comment]
We are still adding support for Storyboards. Programmatically, this wouldn't be an issue. Over the course of the next few iterations, we will have more examples to aid in this. I will leave this issue up for now, as I experiment with a solution.

**Comment by danieldahan** [comment]
Hi, we launched 1.38.0 recently. I have still not been able to reproduce this issue. We will keep on trying. Please let me know if you have found a solution, or reopen this issue if the problem still persists. 

Thank you and all the best.
