### ISSUE TITLE
Line under Toolbar

### ISSUE THREAD

**Issue by adhiravishankar** [CosmicMind/Material#250]
I have a view with the same color as my toolbar underneath the toolbar. Since I want them to be unified, I have a line now underneath my toolbar and above that custom view. I'm not sure where that line is coming from. I would like to know what that line is or where that line is coming from. I have looked at the source code and can't find a source for it. 

Also, do you know of a timeline of when a TabsController might become available? 

Thanks for the library and all you have done!

**Comment by danieldahan** [comment]
Can you send a screen shot? Also, I am working on the BottomNavigationBar now, and tabs following. The last week has been spent on this framework [AlgorithmJS](https://github.com/CosmicMind/AlgorithmJS), and now all our attention is on the latest updates from Apple, and latest MaterialDesign components :) I'd give it a couple days before they are fully fleshed out. 

And it is our pleasure to work on this :)

**Comment by adhiravishankar** [comment]
![img_0924 1](https://cloud.githubusercontent.com/assets/3884741/14036331/e3d35a96-f205-11e5-8c97-4371cbd9cec0.PNG)
Here's my own implementation of Tabs, and I would like for it to look like the Youtube App, which doesn't have that line separating the navigation bar and the tabs.
![screen322x572](https://cloud.githubusercontent.com/assets/3884741/14036364/0eb65092-f206-11e5-8f75-a7541b977031.jpeg)

**Comment by adhiravishankar** [comment]
And, because you might wonder if that line comes from the tabs rather than the toolbar, I have created a custom view of pure green in another screen to test it out and that line still shows up. This is a ToolbarController with a custom UIViewController as the Main View Controller. On the very top of the UIViewController is a uiview with the same color background as the toolbar. 

![img_0926](https://cloud.githubusercontent.com/assets/3884741/14036390/50ad1e40-f206-11e5-8a7c-2531b30dc0f9.PNG)

**Comment by danieldahan** [comment]
Nice view :) 

To fix the line, set the depth of the toolbar to .None

'''Swift 
toolbar.depth = .None
'''

**Comment by danieldahan** [comment]
Also I am launching the BottomNavigationBar tomorrow and tabs tomorrow as well most likely

**Comment by adhiravishankar** [comment]
This has been fixed! Might I suggest a line of code referencing this in toolbar and maybe some other classes that would show that this exists? Thank you very much!

**Comment by danieldahan** [comment]
Pretty much every view has the ```depth``` property. Generally, you are correct. We are working on bringing documentation to Material as we continue to rollout new technologies and features. All the best and keep the questions coming if you have any :)
