### ISSUE TITLE
Swift 2.2/3.0

### ISSUE THREAD

**Issue by ohgodno** [CosmicMind/Material#251]
As I'm sure you've heard, "C-Style for loops", "++", and "--" are all now depreciated and are going to be removed at the June release of Swift 3. Xcode is freaking out on my end with 40+ warnings and it is ridiculous that Apple would these cut basic yet essential features. If you could put out a version without these now depreciated items, it would be much appreciated. I know that Xcode 7.3 and Swift 2.2 were only released Monday, but I just wanted to let you know for the future of this project.

**Comment by danieldahan** [comment]
Excellent! Latest Friday this will be resolved with the release of BottomNavigationBar and tabs.

**Comment by ohgodno** [comment]
Awesome! Thanks for the really fast reply as well.

**Comment by danieldahan** [comment]
This is coming out in an hour.

**Comment by ohgodno** [comment]
Awesome, looking forward to it.
On Sat, Mar 26, 2016 at 5:21 PM Daniel Dahan <notifications@github.com>
wrote:

> This is coming out in an hour.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/251#issuecomment-201930767>
>
-- 
- Harrison Crandall
