### ISSUE TITLE
Is NavigationBarViewController going to replace ToolbarController ?

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#252]
I use Material 1.35.3. I was going to use toolbar to replace iOS default navigation controller.
`private var toolbar: Toolbar = Toolbar()`
However ,it showed "Use of  undeclared type Toolbar" ( I did import Material
Is there any solution?

**Comment by danieldahan** [comment]
So you are using an older version, the latest is [1.37.3](https://github.com/CosmicMind/Material/releases/tag/1.37.3). The Toolbar replaced the NavigationBarView and now there is a NavigationBar and NavigationController, as well as, a ToolbarController. In the examples directory, you should be able to find many examples demonstrating these features. If you have any further questions, please reopen or create a new issue :) All the best!

**Comment by HowardCsie** [comment]
I used pod update,and it just updated to the version 1.35.3.
Am i going to reinstall?

**Comment by danieldahan** [comment]
Yes try that, and possibly set the version to at least 1.37.3 in the pod file. Not sure why it wouldn't update you to the latest.

**Comment by HowardCsie** [comment]
<img width="762" alt="2016-03-25 12 38 51" src="https://cloud.githubusercontent.com/assets/17197816/14038069/ab5cb5b4-f286-11e5-9ae0-548231f95cb4.png">
Just like this.
Here is my Podfile.
<img width="642" alt="2016-03-25 12 40 39" src="https://cloud.githubusercontent.com/assets/17197816/14038084/d528be06-f286-11e5-8f9b-d3b32def2c48.png">

**Comment by danieldahan** [comment]
Try setting the pod like so:

```
pod 'Material', '~> 1.37.3'
```

**Comment by HowardCsie** [comment]
<img width="642" alt="2016-03-25 13 30 30" src="https://cloud.githubusercontent.com/assets/17197816/14038584/d0b42b56-f28d-11e5-8786-8ce4899fbdbd.png">
I got an error like this. Is  1.37.3 really available on cocoapods?
Thank you in advance.

**Comment by danieldahan** [comment]
<img width="662" alt="screen shot 2016-03-25 at 1 38 29 am" src="https://cloud.githubusercontent.com/assets/9982123/14038662/58650020-f22a-11e5-82db-d56f378dbe1b.png">
<img width="658" alt="screen shot 2016-03-25 at 1 38 36 am" src="https://cloud.githubusercontent.com/assets/9982123/14038661/58650296-f22a-11e5-9117-354bbf76f400.png">

I did a fresh test project and install and all seemed to work. Possibly uninstall cocoapods and then reinstall it using the ```gem install cocoapods``` command.

**Comment by danieldahan** [comment]
I think that a ticket sent to CocoaPods would help. There could be an issue with the server distributing to your location.

**Comment by danieldahan** [comment]
Also, seems to exist http://cocoapods.org/?q=Material

**Comment by HowardCsie** [comment]
Thanks. I ll go send it.
Is there any way that i can manually put Material in to my project？

**Comment by danieldahan** [comment]
Yes, if you are using CocoaPods, you can add the Material.framework to your workspace. 

1. Open your CocoaPods workspace. 
2. Add the Material project to your workspace by dragging it from the downloads folder, after you [download it here](https://github.com/CosmicMind/Material/archive/master.zip).
3. Then select the Material scheme and build for generic device. 
4. Go to your application project and click on the general tab. 
5. Click the "+" under the embed binaries section and add Material.framework to your project. 

That should do it.  

<img width="1216" alt="screen shot 2016-03-25 at 2 13 07 am" src="https://cloud.githubusercontent.com/assets/9982123/14039118/2d4ab88a-f22f-11e5-9c3d-a793024a317f.png">

**Comment by HowardCsie** [comment]
I made it.
I m very appreciate ：））））））

**Comment by danieldahan** [comment]
Awesome! Enjoy :)
