### ISSUE TITLE
Need Help to open side menu from bottom tab bar 

### ISSUE THREAD

**Issue by ansu** [CosmicMind/Material#258]
HI,

In my project, I have bottom tab bar controller and right tab bar item is the menu. When the user presses on that,  side menu  should get opened. Can you help me out, how I can open material side menu using tab bar controller item?

**Comment by danieldahan** [comment]
An immediate thought is to set the bottomNavigationController.delegate (UITabBarControllerDelegate) property, and implement the method:

```swift
func tabBarController(tabBarController: UITabBarController, shouldSelectViewController viewController: UIViewController) -> Bool {
		if viewController is PlaceholderViewController {
			sideNavigationController?.openRightView()
			return false
		}
		return true
	}

```

Notice the ```PlaceholderViewController``` class check. You can add an instance of a PlaceholderViewController at the end of the BottomNavigationController viewControllers array. When detected, it will return false and execute the ```sideNavigationController?.openRightView()``` command, thus opening the ```right side nav panel```, and returning false will stop the BottomNavigationController from opening the PlaceholderViewCotroller.

That should do it. There are other ways I am sure, and maybe more efficient. This is a good start.

**Comment by ansu** [comment]
@danieldahan : Thanks for the quick reply and will try the way you have mentioned.
I am just wondering, Is it possible to you share the sample code for this requirement?

**Comment by danieldahan** [comment]
You mean this?

```swift
class AppDelegate: UIResponder, UIApplicationDelegate, UITabBarControllerDelegate {
	
	var window: UIWindow?
	var sideNavigationController: SideNavigationController!
	
	
	func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
		
		let bottomNavigationController: BottomNavigationController = BottomNavigationController()
		bottomNavigationController.viewControllers = [VideoViewController(), PlaceholderViewController()]
		bottomNavigationController.delegate = self
		
		sideNavigationController = SideNavigationController(rootViewController: bottomNavigationController, rightViewController: RightViewController())
		
		window = UIWindow(frame: UIScreen.mainScreen().bounds)
		window!.rootViewController = sideNavigationController
		window!.makeKeyAndVisible()
		return true
	}
	
	func tabBarController(tabBarController: UITabBarController, shouldSelectViewController viewController: UIViewController) -> Bool {
		if viewController is PlaceholderViewController {
			sideNavigationController.openLeftView()
			return false
		}
		return true
	}
//...
}	
```

**Comment by danieldahan** [comment]
If you need further help, reopen the issue, or create a new one :) You can also continue chatting on this thread.

**Comment by ansu** [comment]
@danieldahan : Thanks for helping me out.

**Comment by danieldahan** [comment]
Anytime :)

**Comment by ansu** [comment]
@danieldahan : Thanks once again..You have made my day..:)
