### ISSUE TITLE
Designables are crashing

### ISSUE THREAD

**Issue by dsempel** [CosmicMind/Material#259]
I like using the storyboard for auto layout, but since you implemented the Designables I keep getting these errors (image below). There is no problem with building the code, it's just the annoying errors :)

<img width="204" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4086503/14082478/7deeda58-f510-11e5-9f7e-131e6d0a6132.png">

From the crash logs I found `fatal error: use of unimplemented initializer 'init(frame:)' for class 'Material.MaterialSwitch'`.
It seems that it is just the MaterialSwitch class that causes the crash, because the crash logs do not mention any other class.

**Comment by danieldahan** [comment]
Would you be able to share  a sample project that causes these crashes and I can then use it as a test case to fix the issues from? I don't use Storyboards at all when developing, so my use cases are limited. 

I really appreciate your help on this.

**Comment by dsempel** [comment]
Sure, I've added a MaterialSwitch to your MaterialButtons example. If you open the examples workspace and click the Main.storyboard of the MaterialButtons example, it crashes. Without the MaterialSwitch it works fine here.
[Material-master_Switch-Example.zip](https://github.com/CosmicMind/Material/files/192119/Material-master_Switch-Example.zip)

**Comment by danieldahan** [comment]
Cool, I will look at this later today.

**Comment by danieldahan** [comment]
Thank you for this. I fixed it with:

```swift
public override init(frame: CGRect) {
		trackLayer = MaterialLayer()
		button = FabButton()
		super.init(frame: frame)
		prepareTrack()
		prepareButton()
		prepareSwitchSize(.Default)
		prepareSwitchStyle(.LightContent)
		prepareSwitchState(.Off)
	}
```

Basically the issue is when you implement IBDesignable, both the code and frame init methods need to be implemented. This will be out in the next release. Which I am doing now. Thank you!

**Comment by dsempel** [comment]
Works great, thank you!
