### ISSUE TITLE
Custom MaterialSwitch colors

### ISSUE THREAD

**Issue by dsempel** [CosmicMind/Material#260]
I changed the MaterialSwitch colors like this (in viewDidLoad):
 ```
materialSwitch.buttonOnColor = MaterialColor.grey.lighten3
materialSwitch.trackOnColor = MaterialColor.red.darken1.colorWithAlphaComponent(0.8)
materialSwitch.buttonOffColor = MaterialColor.grey.lighten4
materialSwitch.trackOffColor = MaterialColor.grey.lighten3
```
It still uses the .Default style colors in the initial state of the switch. After activating the switch it starts using the colors I set. The MaterialSwitch is instantiated from the storyboard (but I don't think that would make a difference). I think the problem is that the method below (from MaterialSwitch) is not called after I set the new colors.
```
private func updateColorForEnabledState(state: MaterialSwitchState) {
    if .On == state {
        button.backgroundColor = buttonOnColor
        trackLayer.backgroundColor = trackOnColor.CGColor
    } else {
        button.backgroundColor = buttonOffColor
        trackLayer.backgroundColor = trackOffColor.CGColor
    }
}
```
I fixed the problem like below, but i'm not sure if that's the right thing to do.. I just thought I better let you know.
```
materialSwitch.button.backgroundColor = materialSwitch.buttonOffColor
materialSwitch.trackLayer.backgroundColor = materialSwitch.trackOffColor.CGColor
```
This is an example:
[Material-master_Switch-Example2.zip](https://github.com/CosmicMind/Material/files/192174/Material-master_Switch-Example2.zip)

**Comment by danieldahan** [comment]
Nice, I will look at this later today. FYI, I am planning a revamp on MaterialSwitch and TextField to give better customization and such. Thanks for this!

**Comment by dsempel** [comment]
Alright, thanks! It is not an urgent problem, so take your time. Just wanted to let you know.

**Comment by danieldahan** [comment]
This is fixed and will be in tomorrow's release. Thank you for letting us know about this :)

**Comment by danieldahan** [comment]
These changes have been released. Thanks for bringing this to our attention.
