### ISSUE TITLE
BottomNavigationController crashing due to force unwrap of nil in transition animation

### ISSUE THREAD

**Issue by ahusseini** [CosmicMind/Material#261]
Hello, the BottomNavigationController is crashing on the following lines due to force unwrap of `nil`:

```
let fromView : UIView = transitionContext.viewForKey(UITransitionContextFromViewKey)!
let toView : UIView = transitionContext.viewForKey(UITransitionContextToViewKey)!
```

I'm starting with no child viewcontrollers, and adding them after. Ideally the following can avoid the issue by ignoring the first call to the animation, but I'm not sure if this would be a valid solution for everyone.

```
public func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
  if transitionAnimation == .Fade {
    return BottomNavigationFadeAnimatedTransitioning()
  } else {
    transitionAnimation = .Fade
    return nil
  }
}
```

**Comment by danieldahan** [comment]
How are you adding them after? Do you mean that you are adding them after you already add the BottomNavigationController to the view hierarchy?

**Comment by ahusseini** [comment]
Yes, that's correct, I'm adding view controllers based on data received from a remote API.

**Comment by danieldahan** [comment]
Okay cool, I am fixing it now. Will be released in 1.38.2 :)

**Comment by ahusseini** [comment]
Thank you!

**Comment by danieldahan** [comment]
So, I am trying to reproduce this. Could you explain your setup?

**Comment by ahusseini** [comment]
Hello Daniel, 

Sorry, I was setting the animated parameter to `true` on `setViewControllers()`, setting it to `false` fixed the problem.

**Comment by danieldahan** [comment]
I think though, I should put a check that there are at least two ViewControllers before returning an animation object. That will avoid the need for false. Thoughts?

**Comment by ahusseini** [comment]
I agree, it's going to look ugly though since `fromVC` and `toVC` are not optional params. The following worked for me, are you okay with this as a PR?

```
public func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController?) -> UIViewControllerAnimatedTransitioning? {
    let fromVC: UIViewController? = fromVC
    let toVC: UIViewController? = toVC
    if fromVC == nil || toVC == nil {
      return nil
    }
    return .Fade == transitionAnimation ? BottomNavigationFadeAnimatedTransitioning() : nil
}
```

**Comment by danieldahan** [comment]
generally we could do this:

public func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
		if 2 > tabBarController.viewControllers?.count {
			return nil
		}
		return .Fade == transitionAnimation ? BottomNavigationFadeAnimatedTransitioning() : nil
	}

**Comment by ahusseini** [comment]
Not working for me, it's not hitting that check.

**Comment by danieldahan** [comment]
Your's is actually more clear, but I think we can do this: 

```swift
public func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController?) -> UIViewControllerAnimatedTransitioning? {
	if nil == toVC {
		return nil
	}
	return .Fade == transitionAnimation ? BottomNavigationFadeAnimatedTransitioning() : nil
}
```

I don't believe the transition method would be called if there wasn't a ```fromVC``` as seen in the method definition, Optionals are not passed. Try that, if it works.

**Comment by ahusseini** [comment]
Not sure why, but it's called when `fromVC` is `nil`, `toVC` is not `nil`, switching the optional to `fromVC` works.

**Comment by danieldahan** [comment]
Okay, submit a PR if you like, I can test further from there :)

**Comment by danieldahan** [comment]
You know what is really interesting, is that the method definition for doesn't even offer optionals when auto-written by xcode: 

```swift
public func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController) -> UIViewControllerAnimatedTransitioning?
```

**Comment by ahusseini** [comment]
That's right, I get the following warning in AppCode: 

```
Warning:(132, 14) parameter of 'tabBarController(_:animationControllerForTransitionFromViewController:toViewController:)' has different optionality than expected by protocol 'UITabBarControllerDelegate'
```

For my PR, I think I will convert to optional first, just in case, this way we're not changing the signature as provided in the delegate.

**Comment by danieldahan** [comment]
These changes have been released. Thanks for bringing this to our attention. Let me know if this is an issue still. Thank you!
