### ISSUE TITLE
Help laying out TextField in TableViewCell or CollectionViewCell. 

### ISSUE THREAD

**Issue by ansu** [CosmicMind/Material#264]
HI,

We are trying to show material text field in each cell. We are not able to show detail label of text field inside table view cell. Can you please tell me, how to use material text field inside table view cell.

**Comment by danieldahan** [comment]
Hey, Why a tableViewCell? Maybe a collectionViewCell would be better? Much easier to size, and layout.

**Comment by ansu** [comment]
@danieldahan : Thanks for quick reply once again. We have used tableview cell becuase we have long form and in each form we have 15-20 text fields. Can you please share code snippet using collection view cell.

**Comment by danieldahan** [comment]
I can do it tomorrow :) I am about to sign-off for the evening.

**Comment by ansu** [comment]
Thanks @danieldahan. I will wait for your reply.

**Comment by ansu** [comment]
@danieldahan : please reply asap

**Comment by danieldahan** [comment]
Yes I will be adding a demo for you later today. Are you in a rush?

**Comment by ansu** [comment]
@danieldahan :  If you can reply by the end of the day, that would help me a lot.

**Comment by danieldahan** [comment]
What timezone are you in? My end of day is in 6 hours. Also, to ensure accuracy, if you can post a simple drawing of what you are hoping to achieve, that would speed things up.

**Comment by ansu** [comment]
Please try to reply by end of your day. Here is the screen shot which I am trying to achieve:
![untitled](https://cloud.githubusercontent.com/assets/190119/14115586/336b2b8c-f5f9-11e5-9dd7-066f9f73e314.png)

So far I have made every field in table view cell. If you can suggest any other approach please do let me know.

**Comment by danieldahan** [comment]
Generally, if you can do this in the UITableViewCell and it is maintainable for you, I wouldn't veer from that approach. Especially if you have already coded it. I think your main concern was the display of the detailLabel, is that correct?

**Comment by ansu** [comment]
Yes, My main concern is detail label only. 
Regarding, forms where We have less than 7 text fields, we have used scrollview and that place it is working fine though I have been waiting for your Scrolling Techniques upcoming list :)

**Comment by danieldahan** [comment]
Yes a ScrollView was my thinking when I saw your view. 
The next components in this order are, Paging Tabs, Snackbar, Scroll Techniques. 

So why I was suggesting a CollectionView rather than a TableView was that it is easy to adjust the size of a CollectionViewCell over a TableView, to make room for the detailLabel. 

I will think about this over the course of the day. I don't think that you need me to code the whole thing, and that will be tough with my day today, but I am open to play and experiment with an approach. Cool?

**Comment by ansu** [comment]
If you can share the code with one or two fields using collection view that would be great.

**Comment by danieldahan** [comment]
Cool, I will try my best :)

**Comment by danieldahan** [comment]
Hey! Is there still time for this?

**Comment by ansu** [comment]
It's just morning in India. Can you please share it now.

**Comment by danieldahan** [comment]
Hey,

Yes, checkout the development branch, and look in the Examples directory for the [MaterialCollectionView](https://github.com/CosmicMind/Material/tree/development/Examples/Programmatic/MaterialCollectionView) example project. 

This should get you started. If you need further help, reopen or create a new issue.

**Comment by ansu** [comment]
@danieldahan : Thanks once again. Though it is not part of your code, but wondering can you tell me how to move to next field while pressing on return of one field. Previously we were using https://github.com/simonbs/BSKeyboardControls. to move up and down text field but bskeyboardcontrols doesn't give support to material text fields.

If you can help me out on this, i will be very thankful to you. :)

**Comment by danieldahan** [comment]
Hey, anytime. 

Why doesn't it support Material TextField? TextField is subclassed from UITextField, so all properties should hold true.

If not, you can store an array of TextFields and when the user clicks on the Return key, you can check if there is another TextField following the one just clicked in the array. Then you can set becomeFirstResponder to that TextField. That would be the premise of a solution.
