### ISSUE TITLE
Collapsing Toolbar Layout

### ISSUE THREAD

**Issue by saipnc** [CosmicMind/Material#269]
Hi Cosmic Mind team,

A bow to you guys for the amazing work! 
I was wondering if you could consider developing the collapsing toolbar in your next update. My whole project UI is based on your library moved the UI from apple's flat UI to Google's Material design with the help of your amazing work, I couldn't ask for more but if you guys could do this it will help us a lot. For the exact behaviour please refer the following gif. 
![collapsing-toolbar-layout](https://cloud.githubusercontent.com/assets/2713981/14136891/dc2c68d8-f682-11e5-867e-686611101513.gif)

**Comment by danieldahan** [comment]
Thank you for helping us grow :) I think your suggestion would be a wonderful addition and many people would love it. That said, I can't say it will come out in our next release, as we are working on TabBars, but I can see it being available very soon. An app that we are making would benefit greatly from this feature. I am going to leave this issue up for now, as we will inform you and create a thread on this topic.

**Comment by danieldahan** [comment]
I added this to the upcoming list. Thank you!

**Comment by mortenholmgaard** [comment]
@danieldahan Any news on this? - I can't find the component or any notes about its state

**Comment by danieldahan** [comment]
@mortenholmgaard nothing yet.
