### ISSUE TITLE
Pulse focus

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#274]
Guys, it would be nice if there were some options for focus. You have implemented it in the way it is described in the material guide, user highlights the element and focus covers it in the form of wave. But one thing is missed: The "hamburger" button (menu button) in Google's inbox application is highlighted in a bit different way: it is highlighted using focus but the focus is not in the form of wave. Look at the app and you will understand what I mean. It would be great if you, guys,  implemented this in the library. One option of enum, for example, for the pulse that is used now, the other one for the pulse used in the Inbox app, and the third one is a combination of 1st and 2nd one that is used throughout android apps. Thank you.

**Comment by danieldahan** [comment]
You mean the circle look for the buttons? Yeah, I think it would be cool to move things to an enum, and then be able to grow the effects for pulse. Nice suggestion. I'll leave this issue up, and will roll something out very soon.

**Comment by RuslanPatyk** [comment]
No, not the circle look for the button, but the way the pulse behaves on a circle menu button of Inbox application. That circle button is just an example. First type - the type that is used now, second one - the type used on a button that I have written above and 3-d one is a combination of 1st and 2nd type, when 2nd type pulse is covered with 1st one, but 1st one is not as translucent as 2n one in such a case. 

Thank you so much.

:)

**Comment by danieldahan** [comment]
I will look into it :) 

As for the opacity, you could set the pulseOpacity, so you know.

**Comment by RuslanPatyk** [comment]
Yes…

Thank you

**Comment by RuslanPatyk** [comment]
It would be nice to reduce pulse delay on tap, it will give more responsiveness

**Comment by danieldahan** [comment]
Yeah, when I rework the pulse, I will see what can be done. Any suggestions?

**Comment by colinmorelli** [comment]
@danieldahan if you plan on re-working the pulse, I do have a suggestion: I'd love to see the pulse bounds be resized, rather than scaled. In cases where you can see the bounds of the pulse, the edges are very distorted because of the scaling.

**Comment by danieldahan** [comment]
@colinmorelli nice. Yes that is primarily why I want it redone. To make it crisp. Excellent suggestion.

**Comment by danieldahan** [comment]
@RuslanPatyk Hi, I rewrote the pulse animation, to match this [spec](https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input), the surface reaction and Material response. I am going to add an enum handler to set the different states. I will close this for now, and once the release is out, please test. Sorry, if this is closed early in your opinion, this is mainly to coordinate with what I have in development pending release.

**Comment by danieldahan** [comment]
@colinmorelli I definitely agree about the scaling and have made some changes. I will be adding a new type of scale, or correcting it based on the scaleFactor, which was not set. Thank you!
