### ISSUE TITLE
TextField bottom border now showing until first highlight

### ISSUE THREAD

**Issue by diogoguimaraes** [CosmicMind/Material#276]
I'm having an issue with `TextFields` only since I've updated from `v1.37.3` to `v1.38.4` that prevents the bottom border of appearing when the text field is displayed. 
The border only stays visible after highlighting the text field for the first time.

Do you have any idea of what it could be?
Thank you.

**Comment by danieldahan** [comment]
Let me look into it. There are TextField related issues that I will do in one swoop. I'll give you clear insight once I look into them later today.

**Comment by danieldahan** [comment]
This was an issue that arose when the bottomLayer color handling was introduced. I fixed it in 1.39.0. Sorry for the delay on this.
