### ISSUE TITLE
Change navigationItem titleLabel font size

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#277]
I used the code below to set my TitleLable.However, the font size of title label didn't change.Is there any way i can customize my title label font size?
```
private func prepareTitleLabel() {
        titleLabel = UILabel()
        titleLabel.text = "課表"
        titleLabel.font = UIFont(name: "system Font", size: 8)
        titleLabel.textAlignment = .Left
        titleLabel.textColor = UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 0.7)
    }
```

**Comment by danieldahan** [comment]
At the current moment they are a fixed size. In the next release, I will make it that you can customize it.

**Comment by HowardCsie** [comment]
thank you:)

**Comment by danieldahan** [comment]
This is going to be fixed in a separate release from 1.39.0. Should follow really quickly. Thanks for your patience.

**Comment by HowardCsie** [comment]
How to use it? It is still not working.(using 1.39.1

**Comment by danieldahan** [comment]
I am going to do your fix tomorrow. It is 4 am here, so I am tidying up the last fix. Sorry, but your fix requires some reworking I need to be fully awake for :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by HowardCsie** [comment]
okok. Have a nice dream~
It is 3:32 pm here (taiwan  :))

**Comment by danieldahan** [comment]
:) Thank you!

**Comment by mohpor** [comment]
What's the status on this issue @danieldahan, @HowardCsie?

**Comment by danieldahan** [comment]
This is now fixed in the issue-366 branch. I am going to close this and in the next release it will be available.
