### ISSUE TITLE
Help with Grid layout and spacing when using Toolbar

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#278]
I having trouble using grid layout. I'm doing av ipad application with ToolbarController. But when I add the subviews to the root controller and add some contentInset and spacing it doesn't work as I expected.

I'm using the code below but with the presets, the height is calculated wrong. If I uncomment the row below for the contentInset and and increase the bottom value with the height of the toolbar (64) it works as I want.

But should I have to do that?

```
func prepareView() {
        
    let summary = UIView()
    summary.grid.columns = 4
    summary.backgroundColor = MaterialColor.grey.darken3
        
    let items = UIView()
    items.grid.columns = 8
    items.backgroundColor = MaterialColor.grey.base
        
    view.addSubview(summary)
    view.addSubview(items)
        
    view.grid.contentInsetPreset = .Square3
    view.grid.spacingPreset = .Spacing3
        
    //view.grid.contentInset = UIEdgeInsetsMake(16, 16, 64+16, 16)
        
    view.grid.views = [summary, items]
        
}
```

**Comment by danieldahan** [comment]
Most likely you are executing the `prepareView` method in the `viewDidLoad` method of the ViewController that is the rootViewController of the ToolbarController. At that point, the dimensions of the ViewController will be the screen, as the viewDidLoad method is executed prior to the relationship made with the ToolbarController. To avoid this issue, use the `viewDidAppear` method:

```swift
class YellowViewController: UIViewController {
	override func viewDidLoad() {
		super.viewDidLoad()
		
	}
	
	override func viewDidAppear(animated: Bool) {
		super.viewDidAppear(animated)
		prepareView()
	}
	
	/// Prepares view.
	private func prepareView() {
		view.backgroundColor = MaterialColor.yellow.base
		
		
		let summary = UIView()
		summary.grid.columns = 4
		summary.backgroundColor = MaterialColor.grey.darken3
		
		let items = UIView()
		items.grid.columns = 8
		items.backgroundColor = MaterialColor.grey.base
		
		view.addSubview(summary)
		view.addSubview(items)
		
		view.grid.contentInsetPreset = .Square3
		view.grid.spacingPreset = .Spacing3
		
//		view.grid.contentInset = UIEdgeInsetsMake(16, 16, 64+16, 16)
		
		view.grid.views = [summary, items]
	}
}
```

This should solve your issue.

**Comment by sverin** [comment]
Thank you, it works the way you describe.
