### ISSUE TITLE
[CocoaPods] MaterialIcon not displaying

### ISSUE THREAD

**Issue by gilthonweapps** [CosmicMind/Material#279]
Hi,

If you install Material with cocoapods, the icons from MaterialIcon (e.g. MaterialIcon.close) always return nil.

I submitted a PR a while ago that was fixing this issue, but I saw that you recently put back your old code...

**Comment by danieldahan** [comment]
Hey, 

When I tried your solution in an app without CocoaPods it broke and could not find the bundle. We would need to think of another solution.

**Comment by danieldahan** [comment]
I would like to solve this issue. So I am going to leave this up and we can work on it, or I will update you when I have come to a resolution. I will aim for this weekend to have a solution.

**Comment by ramonvic** [comment]
I also had this problem here, I fix by changing the path of the bundle
on MaterialIcon.swift line 34 to 
`public static let bundle = NSBundle(URL: NSBundle(forClass: MaterialView.self).resourceURL!.URLByAppendingPathComponent("io.cosmicmind.Material.bundle"))!`

**Comment by danieldahan** [comment]
This has been resolved in [1.38.5](https://github.com/CosmicMind/Material/releases/tag/1.38.5). The fix is to check if the bundle can be found using the CocoaPods approach, and if not, use the default bundle location.
