### ISSUE TITLE
preferredStatusBarUpdateAnimation = .Fade not working

### ISSUE THREAD

**Issue by levuhai** [CosmicMind/Material#281]
the status bar always slides up when opening menu from SideNavigationController
How can i change this behavior of SideNavigationController?

Thank you so much for your great work

**Comment by danieldahan** [comment]
Hey! Thank you. 

I will look into this.

**Comment by levuhai** [comment]
in your examples, the status bar's hide animation is always slide, no matter how i change preferredStatusBarUpdateAnimation
while importing to my project, the animation is fade

**Comment by danieldahan** [comment]
Hi there, if you checkout the example project in release [1.39.6](https://github.com/CosmicMind/Material/releases/tag/1.39.6) I added helpers to SideNavigationController to allow for different animations to be used. Thank you for bringing this to our attention. All the best!
