### ISSUE TITLE
Additional components: BottonSheet and Dialogs

### ISSUE THREAD

**Issue by ramonvic** [CosmicMind/Material#282]
It will be created components BottonSheet and Dialogs?

**Comment by danieldahan** [comment]
Yes, I will put these in the upcoming list. Thank you!

**Comment by ramonvic** [comment]
If you want help, I'll need to create these elements in the next days, if you want, I can do and push here, I'm loving this repository :)

**Comment by danieldahan** [comment]
Yeah, let's do it together :) Send me a PR, questions, whatever you need. Once you have something, I can add my input and help integrate it into Material.
