### ISSUE TITLE
Missing Roboto Fonts

### ISSUE THREAD

**Issue by ramonvic** [CosmicMind/Material#284]
Was deliberate not attach Roboto fonts in Pod? I saw that them are on the sources folder, but are not in the pod.

**Comment by danieldahan** [comment]
No, I will add them. Thank you!

**Comment by ramonvic** [comment]
Thanks for the quick response.

**Comment by danieldahan** [comment]
Do you mind trying 1.39.0? If the issue persists, reopen the issue, or create a new one. Thank you!

**Comment by ramonvic** [comment]
The fonts are embeded now, but it not are loaded. this is because diferent bundle, i fixed it if you like ai can make a PR.
