### ISSUE TITLE
Question about change on Material Icons

### ISSUE THREAD

**Issue by ramonvic** [CosmicMind/Material#285]
I checked that the Icons embedded in library are not same from Google Material Icons, this change was deliberated? if yes, i like know if has a method to set a custom images to 'MaterialIcon' class, because it is used internally and i like to go back for the google icons. Or i can make a PR with Google Icons back, and maybe add more icons. Whats your opinion?

**Comment by danieldahan** [comment]
I am going to include both, the CosmicMind ones and the Google ones. I'll be doing a release later tonight with some updates, and those will be included.

**Comment by ramonvic** [comment]
Great News. Thanks

**Comment by danieldahan** [comment]
This is now fixed, and will be in release 1.39.0, that will come out later tonight. Thank you!

**Comment by ramonvic** [comment]
Worked for me now, but i had a fork and added some icons on Google, like 

```
ic_add_circle_outline_white
ic_add_circle_outline_white
ic_audiotrack_white
ic_edit_white
ic_history_white
ic_image_white
ic_movie_white
ic_edit_white
ic_place_white
ic_photo_camera_white
ic_photo_library_white
ic_settings_white
ic_star_border_white
ic_star_half_white
```

Tell me if i can make a PR. Would greatly appreciate be contributing to the library.

**Comment by danieldahan** [comment]
Yeah, that would be great! Please send the PR to development, and please in the MaterialIcon file, add the values alphabetically. Makes everything so much easier to maintain. We are adding more icons today as well. 

Thank you!

**Comment by ramonvic** [comment]
i do this right now
