### ISSUE TITLE
DerivedData

### ISSUE THREAD

**Issue by aoiserizawa** [CosmicMind/Material#289]
guys Im having problem on running one of my project, it says "Products/Debug-iphonesimulator/Material/io.cosmicmind.material.fonts.bundle: No such file or directory"

I checked the location it cant find it because it creates its file inside Products/Debug-iphonesimulator/Material/Material/.io.cosmicmind.material.fonts.bundle any solution about this? Im using the latest xcode and latest release of Material. TIA

**Comment by ramonvic** [comment]
The author is aware about this, PR #288  fixed this, i hope so he merge it today

**Comment by aoiserizawa** [comment]
thanks!!

**Comment by danieldahan** [comment]
Hey! 

An update has been merged into development, thanks to @ramonvic. We are going to make a release today, which will include the additions made.

All the best!

**Comment by danieldahan** [comment]
[1.39.5](https://github.com/CosmicMind/Material/releases/tag/1.39.5) has been published, please try using the fonts now. As well, clear your DerivedData folder and clean your build folder.

All the  best and thank you @ramonvic :)
