### ISSUE TITLE
Appearance behavior

### ISSUE THREAD

**Issue by gilthonweapps** [CosmicMind/Material#292]
Hi,

Really great lib. I love it and am busy implementing it everywhere in my app :-)

You should add a way to have a global appearance config for your classes using the UI_APPEARANCE_SELECTOR marker.
For example, if I want all my material views to use the same pulseColor, I should be able to write something like: Material.appearance().pulseColor = UIColor.redColor();

Thanks for the great work :+1:

**Comment by danieldahan** [comment]
Awesome, thank you! We are planning to launch a Theme API, which would do what you are describing :)

**Comment by sohayb** [comment]
hey @danieldahan, any update on the Theme API? Thanks a lot :)

**Comment by danieldahan** [comment]
Not sure why this was closed, I am going to reopen it and put it on the ToDo. Sorry about that. As for timing, it will be sooner than later. I have a few items that I want to tackle first. If you have any ideas on this, I'd be happy to learn about them. Thank you!

**Comment by sohayb** [comment]
Well TBH I haven't thought about how to design a Theme API in a generic way, I'm just using a solution I found online:
```swift
extension UILabel{
    var defaultFont: UIFont? {
        get { return self.font }
        set { self.font = UIFont(name:newValue!.fontName, size: self.font.pointSize) }
    }
}
````
Then in my AppDelegate:
```swift
UILabel.appearance().defaultFont = RobotoFont.regular
````
I hope this is helpful.

**Comment by sohayb** [comment]
I was just overhauling the app's code by removing all initialization inline code and replace by this code in the app's delegate 😃
```swift
        UILabel.appearance().appFont = RobotoFont.regular
        
        TextField.appearance().appFont = RobotoFont.regular
        TextField.appearance().appIsClearIconButtonEnabled = true
        TextField.appearance().appPlaceHolderActiveColor = .appColor
        TextField.appearance().appDividerActiveColor = .appColor
        
        Button.appearance().appFont = RobotoFont.regular
        RaisedButton.appearance().appDepthPreset = .depth5
        RaisedButton.appearance().appTitleColor = .white
        RaisedButton.appearance().appPulseColor = .white
        RaisedButton.appearance().appBackgroundColor = .appColor
        
        FlatButton.appearance().appTitleColor = .appColor
        FlatButton.appearance().appBackgroundColor = .clear
        FlatButton.appearance().appPulseOpacity = 0
```

**Comment by danieldahan** [comment]
Cool, I will come up with something for this. I think it is a great idea to theme Material.

**Comment by OrkhanAlikhanov** [comment]
I think the `UIAppearance` is a bit outdated for swift. It will require the `dynamic` keyword for every property in order to be eligible for Objective-C.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I fully agree. In [Material Gitter](http://gitter.im/CosmicMind/Material) we can discuss and then update this issue with our solution.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
