### ISSUE TITLE
Pulse Animation Sometimes Not Triggered

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#294]
Given a pulse view that segues to another view controller. When you tap (and release quickly) the pulse view, the animation doesn't show. Unless I tap and hold a bit longer before releasing.

**Comment by zgosalvez** [comment]
Clarified title.

**Comment by danieldahan** [comment]
I'll look into it, might be an issue with animations firing on the same thread and disrupting each other.

**Comment by RuslanPatyk** [comment]
Yes... I wrote about that in comments to my other issue connected with Pulse.

**Comment by danieldahan** [comment]
I fixed this in the rewrite of the pulse animations. I am adding some documentation and will be making the release. You can check the development branch and App example project to confirm. I am closing this issue for clean up. Thank you!
