### ISSUE TITLE
TextField Clear Button don't call textFieldShouldClear

### ISSUE THREAD

**Issue by juvs** [CosmicMind/Material#296]
The normal behavior should call textFieldShouldClear delegate according to Apple's documentation:
[textFieldShouldClear](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextFieldDelegate_Protocol/index.html#//apple_ref/occ/intfm/UITextFieldDelegate/textFieldShouldClear:) but when pressed clear button this not happen.

Based on #229 issue, you can replace the current handler for the clear button (that's ok), but when you have a delegate class this is not at option. I see difficult to invoke the textFieldShouldClear delegate (currently researching...) from TextField code, so that's why I propose to be optional for use FlatButton for clear button and preserve default behavior.

**Comment by danieldahan** [comment]
Yes, I verified this issue and will be putting in a fix today with a release. Thank you!

**Comment by danieldahan** [comment]
This is now fixed in [139.7](https://github.com/CosmicMind/Material/releases/tag/1.39.7), thank you for bringing this to our attention :)
