### ISSUE TITLE
No way to visualize code? @IBDesignable or @IBInspectable?

### ISSUE THREAD

**Issue by FateRiddle** [CosmicMind/Material#297]
I love Material. But as a beginner in iOS development, I find visualized design with storyboard pretty attractive. So I'll simply put some of my questions:
1. Is there similar stuff to @IBDesignable or @IBInspectable in Material? So that I can see the outcome right away?
2. what about autolayout?
3. Is it possible to drag and draw on the storyboard instead of writing spesific numbers?
4. I installed and imported Material with Carthage, will the components build by Material code fit in all devices automatically?

**Comment by danieldahan** [comment]
Hi @FateRiddle 

I will answer your questions with corresponding numbers:

1. Material has added @IBDesignable and @IBInspectable throughout the code base. So you can see it in storyboards as best as Apple supports it.

2. We have 3 layout mechanisms: Grid, MaterialLayout, and general alignment done by the components. 

3. You can drag and drop the UI component you like to storyboard, and then change the class name and module in the configuration panels. 

4. Components make their best attempt to fit everywhere.

If you have any further questions, please reopen or create a new issue.
