### ISSUE TITLE
TextView TitleLabel frame computed incorrectly

### ISSUE THREAD

**Issue by brandonroth** [CosmicMind/Material#298]
There is an issue in the Textview class where the title label is computed incorrectly if the frame of the text field hasn't been set yet.  This can occur if you set the text before the view is laid out.  I saw it mentioned in issue #237 that TextField was going to be rewritten so I'm not sure how relevant this is.

Steps to reproduce

1: Add a TextField to a view controller.
2. Setup the TextField to have a titleLabel.
3. Set the placeholder text and the normal text.
4. Show the view.  The field will have text but the title label will be missing (it will have a width of zero).  The only way to get it visible is to delete the text, causing the field to hide, then enter text which shows the view with the correct frame.

A simple fix would be to, in the `showTitleLabel` function, calculate the correct width of the label by using sizeToFit and then set the frame instead of using the views bounds.width property.  However if the TextViews width was really supposed to be zero then this could cause issues.  I think a better solution may be to implement `layoutSubviews` and set the correct width and height there.

Thoughts? I'm willing to implement the fix but I don't want to do the work if things are going to change significantly.

**Comment by danieldahan** [comment]
Thank you for this. Things will change significantly. I plan to rewrite the TextView in preparation for additions we want to add down the road :) I will keep this up until the effort is complete as the steps you outlined are important.

**Comment by mohpor** [comment]
@brandonroth,
@danieldahan has pushed a major redesign for the `TextField`. Could you please check if your issue has been resolved using the new `TextField` (currently on `development` branch)?

Thanks

**Comment by mohpor** [comment]
Is this still a problem @danieldahan, @brandonroth ?

**Comment by danieldahan** [comment]
This is actually not so much an issue but rather a suggestion as I write the new TextView. I have taken note of this and will put it into play as the new one comes out. Thank you!
