### ISSUE TITLE
sideNavigationController crash

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#299]
<img width="745" alt="2016-04-13 11 01 13" src="https://cloud.githubusercontent.com/assets/17197816/14481609/4dc3de60-0167-11e6-8ca7-67d81621b06f.png">
SideNavigationController works fine in simulator but crashes in real device.

**Comment by danieldahan** [comment]
What version are you running and on what device?

**Comment by HowardCsie** [comment]
lates material 1.39.7. Runned on iPhone 5s.

**Comment by danieldahan** [comment]
Okay, tomorrow morning I will look into it. Thank you.

**Comment by HowardCsie** [comment]
ok.thank you.have a nice dream:)

**Comment by HowardCsie** [comment]
I fixed it by delete all my DerivedData.Thanks anyway.

**Comment by danieldahan** [comment]
cool :)
