### ISSUE TITLE
cannot assign to property: 'clearButton' setter is inaccessible & more question

### ISSUE THREAD

**Issue by FateRiddle** [CosmicMind/Material#300]
1. I drag a UITextField into the storyboard, then ctrl drag into ViewController 
`@IBOutlet weak var textField: UITextField` then I change its class to TextField, it works just fine. But when I copy paste the following code into my ViewController's ViewDidLoad()

`
textField.placeholder = "First Name"
textField.placeholderTextColor = MaterialColor.grey.base
textField.font = RobotoFont.regularWithSize(20)
textField.textColor = MaterialColor.black

textField.titleLabel = UILabel()  **//error**
textField.titleLabel!.font = RobotoFont.mediumWithSize(12)
textField.titleLabelColor = MaterialColor.grey.base
textField.titleLabelActiveColor = MaterialColor.blue.accent3

let image = UIImage(named: "ic_close_white")?.imageWithRenderingMode(.AlwaysTemplate)

let clearButton: FlatButton = FlatButton()
clearButton.pulseColor = MaterialColor.grey.base
clearButton.pulseScale = false
clearButton.tintColor = MaterialColor.grey.base
clearButton.setImage(image, forState: .Normal)
clearButton.setImage(image, forState: .Highlighted)

textField.clearButton = clearButton  **// error**
`
error shows up saying:"cannot assign to property: 'clearButton' setter is inaccessible ", why?

I'm pretty new as a coder, if possible, would you please suggest me a writing style for specifying how  a textfield( or anything) presents itself on screen, after you create it on storyboard and insert an outlet in code(like where should I paste those code above)? Thanks! 

And 2. I noticed I can only change the class of a textfield from UITextField to TextField, and if I needed a flatButton, I'll have to create a button. So how do I create a CardView by changing the class of an existing object on  storyboard?

**Comment by danieldahan** [comment]
No worries :)

The TextField was recently updated, which actually removes all that setup. Checkout the [storyboard examples](https://github.com/CosmicMind/Material/tree/master/Examples/Storyboards) to help get you started. There is a TextField example. 

On the [home](https://github.com/CosmicMind/Material/wiki) page of the wiki, there is a setup lesson, which will help you setup the example projects. 

Give those a try, and feel free to ask more questions. All the best.

**Comment by FateRiddle** [comment]
@danieldahan Thanks! I've followed setup, the example deleted the storyboard and wrote all the code in ViewDidLoad. I've got several labels and textfields to edit, should I write everything in there? D;

**Comment by danieldahan** [comment]
For question 2: You should choose the corresponding view. So if you want a button, you should choose UIButton, and if you want a CardView, you should choose a UIView. Choosing a UILabel and then setting it to CardView will cause issues. If you want to see the type of view you should choose for each item in Material, the easiest way is to look in the class files and see the class that the Material item inherits from. 

Sorry if that sounds cryptic, but it is the most simple way I can put it. Aside from that, you are always welcome to ask questions and reach out to the Material community. They are really helpful. 

For the `viewDidLoad` question, essentially that is a great place to setup code, but not always the most ideal in certain situations. I think you are on the right path :)
