### ISSUE TITLE
TextField Crash (attempted to retain deallocated object)

### ISSUE THREAD

**Issue by ramonvic** [CosmicMind/Material#301]
As `Textfield.hideTitleLabel` is async, when the complete block is executed, the text field already gone deallocated

![screen shot 2016-04-13 at 12 23 22 am](https://cloud.githubusercontent.com/assets/87956/14481972/22546316-010e-11e6-8121-5e11a2651d1c.png)

**Comment by ramonvic** [comment]
i can make a PR?

**Comment by danieldahan** [comment]
Yes you can :)

**Comment by ramonvic** [comment]
Changing [unowned self] to [weak self] fix that

**Comment by danieldahan** [comment]
So this is fixed in the development branch. Thank you! I am going to close this for cleanup purposes, and later today there will be a release with the fix.
