### ISSUE TITLE
io.cosmicmind.material.icons.bundle: No such file or directory

### ISSUE THREAD

**Issue by plokijuhhb** [CosmicMind/Material#303]
please forgive me for my poor English.
hello
i can't build success  when i use Material by cocoapods  

`Build/Products/Debug-iphoneos/Material/io.cosmicmind.material.fonts.bundle: No such file or directory
 `
`Build/Products/Debug-iphoneos/Material/io.cosmicmind.material.icons.bundle: No such file or directory`
two error

when i delete it in target `Copy Bundle Resource`   I can  build success
![snip20160413_6](https://cloud.githubusercontent.com/assets/12380310/14487708/da9da4b8-0196-11e6-8f89-5cdbd0ba60c9.png)
but when update pods  I have to delete again

cocoapods version 1.0.0.beta6

Material version 1.39.7
thanks

**Comment by danieldahan** [comment]
Well I cannot really comment on `beta` software by CocoaPods. I ran the pod install using the stable version and all worked well. It seems in CocoaPods' new version they are eliminating the hackiness of bundles. When they are stable, we will support the 1.* release. For now, only their stable versions. All the best and feel free to reopen or create a new issue if you need help :)

**Comment by plokijuhhb** [comment]
Thanks when I use CocoaPods version 0.39.0  all well now  :P

**Comment by danieldahan** [comment]
Sweet :)

**Comment by leandono** [comment]
Hello!
Is there other alternative than downgrade cocoapod? All our team has the beta6 version and for some developers is a little hard do the downgrade. 
A workaround that we found to solve the problem is install Material using Carthage and then add it manually into the project.... but we think that is not the best approach to solve the problem,
Thanks!

**Comment by danieldahan** [comment]
You could follow this [lesson](https://github.com/CosmicMind/Material/wiki) that will show you how to add the framework to a Workspace. CocoaPods uses a Workspace, so you can add it to that one. That is a way better approach than using Carthage.
