### ISSUE TITLE
Crashing upon adding two card views

### ISSUE THREAD

**Issue by psuedonovicecoder** [CosmicMind/Material#304]
Storyboard implementation of two card views crash giving a Thread 1:EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0) error, highlighting the Title Label

**Comment by danieldahan** [comment]
Would you be able to provide an example of this? I added as a test another CardView to the example project and all seemed well. Thank you!

**Comment by danieldahan** [comment]
Hi, I updated the storyboard CardView example to use two CardViews in release [1.39.9](https://github.com/CosmicMind/Material/releases/tag/1.39.9). Hopefully this helps. If you have any further issues, please reopen or create a new one. Thank you!
