### ISSUE TITLE
Interface Builder issue

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#305]
When I use Material's views in IB as custom classes, I always get strange messages:
- Failed to update auto layout status. The agent crashed
- Failed to render instance of Material View: The agent crashed

I do not know whether it is Apples's issue or your, but it was in Xcode 7.2 and now after update to 7.3 it has not been fixed. Please look.

Thank you

**Comment by danieldahan** [comment]
Do you mind sending me an example of this?

**Comment by danieldahan** [comment]
I haven't been able to reproduce this. If you can send a project that I can then use to reproduce this, it would be great. Until then, I will close this issue. Thank you!

**Comment by RuslanPatyk** [comment]
> On Apr 14, 2016, at 8:49 PM, Daniel Dahan <notifications@github.com> wrote:
> 
> I haven't been able to reproduce this. If you can send a project that I can then use to reproduce this, it would be great. Until then, I will close this issue. Thank you!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/CosmicMind/Material/issues/305#issuecomment-210074292>
Hi, Daniel

I did not have time at all to do this today,
I will try to make a project for you tomorrow.

Thanks,
Ruslan

**Comment by danieldahan** [comment]
No rush. I like to leave active issues up, so once you have a reproducible project, we can reopen this :)
