### ISSUE TITLE
Allow LineLayer height to be customized

### ISSUE THREAD

**Issue by MPiccinato** [CosmicMind/Material#307]
Right now it appears that the lineLayer height defaults to 1 when not active and 2 when active.

It would be nice to be able to adjust this size.

Typically I would just override the methods but with the internal/private funcs it doesn't seem possible.

**Comment by danieldahan** [comment]
I can add some properties you can set that will enable this :)

**Comment by danieldahan** [comment]
This has been fixed and is in the development branch. I will be making a release later today.

**Comment by MPiccinato** [comment]
Awesome! Thanks, I would have made a pull request myself but a little swamped today. I appreciate it.

**Comment by danieldahan** [comment]
Released :)
