### ISSUE TITLE
TextField borderColor Not Changing

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#308]
![img_5654](https://cloud.githubusercontent.com/assets/17197816/14518781/d4e7f274-024c-11e6-807e-9c0d65ed73aa.jpg)

I used the code below to change my textfield border from black to white, but it failed.
Nothing changed. Did i use the correct way to change the color of my textfield line?
`passwdTF.borderColor = MaterialColor.white`

**Comment by danieldahan** [comment]
Did you set a borderWidth?

```swift
v.borderWidth = 2
// or
v.borderWidthPreset = .Border2
```

**Comment by HowardCsie** [comment]
No,I didnt use that.let me try:)

**Comment by danieldahan** [comment]
oh... the lineLayer? 

There are 4 color settings you can set: 

```swift
// The lineLayer color when inactive.
textField.lineLayerColor: UIColor? {
	
// The lineLayer active color.
textField.lineLayerActiveColor: UIColor?
	
// The lineLayer detail color when inactive.
textField.lineLayerDetailColor: UIColor?
	
// The lineLayer detail active color.
textField.lineLayerDetailActiveColor
```

**Comment by HowardCsie** [comment]
Thanks a lot :DDD
