### ISSUE TITLE
SideNavigationBar Example Unclear

### ISSUE THREAD

**Issue by psuedonovicecoder** [CosmicMind/Material#309]
The SideNavigationBar example is a bit unclear on how to transition the RootVC to a different VC. 
I am am aware of the stackoverflow question/answer addressing this issue but it is a bit vague and hard to understand. Since a common usage of the sidenavigationbar is to change ViewControllers, I thought it would be a good idea to include it in the SideNavigationBar example

Thank you so much for your time and patience,
Have a nice day 😄

**Comment by danieldahan** [comment]
Hey :) Yes, we can update the example. I will do it later today, or latest tomorrow morning.

**Comment by levuhai** [comment]
+1

**Comment by danieldahan** [comment]
I am going to update this today :)

**Comment by danieldahan** [comment]
Please check [1.39.12](https://github.com/CosmicMind/Material/releases/tag/1.39.12), the Example/Programmatic/SideNavigationController project has been updated to demonstrate how to transition the rootViewController. If you need any help, reopen or create a new issue. All the best :)
