### ISSUE TITLE
Create Automatic TitleLabel

### ISSUE THREAD

**Issue by ramonvic** [CosmicMind/Material#313]
Hi, for each viewController I create, I need create a `UILabel` for this viewController, the `NavigationBar` can be changed to make this work, based in `viewController.title` and `UINavigationBar.appearance`, 
Or you make this propositally? 
I also saw that the width of titleView is the width of the navigationBar, overlapping the rightButtons, you saw this?

**Comment by ramonvic** [comment]
With this, the font and fontSize of the title can be changed dinamically

**Comment by danieldahan** [comment]
Nice, yes I wanted to visit this again to help in this issue [277](https://github.com/CosmicMind/Material/issues/277). I am going to take a look at the titleView overlapping the rightButtons, it shouldn't. That would be a bug, possibly a regression.

**Comment by ramonvic** [comment]
I try fix that and Make a PR

**Comment by danieldahan** [comment]
Perfect! I would appreciate that very much :)

**Comment by danieldahan** [comment]
We can continue this issue within the PR. I am closing this for cleanup purposes. Thank you :)
