### ISSUE TITLE
Stuttering with transitioning from a ViewController with CardViews to another blank view

### ISSUE THREAD

**Issue by psuedonovicecoder** [CosmicMind/Material#315]
I am getting quite a bit of stuttering when i transition from a view controller that has CardViews to another ViewController

`self.navigationController?.pushViewController(exampleLoadViewController(), animated: true)`

where `self.navigationController?` is the VC with cardviews and exampleLoadViewController() is the VC I am trying to transition to.

Example of this:

![error](https://cloud.githubusercontent.com/assets/14855761/14584643/ccc0ffee-0415-11e6-8633-78457719f875.gif)

**Comment by danieldahan** [comment]
Hey,

Are you testing against a view that does not have a transparent background? The lag may be due to the animation from the right taking place, but you are not seeing it since that VC `exampleLoadViewController` does not have a background.

**Comment by psuedonovicecoder** [comment]
exampleLoadViewController is basically a blank view controller that I added in my storyboard. So I am assuming that it has a default background

**Comment by danieldahan** [comment]
Try adding one, because I don't see it in the animation you sent me.

**Comment by psuedonovicecoder** [comment]
I set the target VC to the default background color and the problem persists. 
I also noticed the same problem with other buttons (that are not Material)
So I think the problem may not arise from Material

**Comment by danieldahan** [comment]
If you would like to package an example project and send it to support@cosmicmind.io we may be able to help. All the best :)

**Comment by ndlinh** [comment]
I got the same problem

**Comment by danieldahan** [comment]
Do you have a background color set on the view controller you are pushing?

**Comment by mohpor** [comment]
@ndlinh as @danieldahan has mentioned before, it normally means one of the view controllers involved in the transition, has a transparent background. Can you confirm that it's not true in your case?
