### ISSUE TITLE
Wrong TextField Placeholder text (and titleLabel text) after changing Placeholder + Refocus focus

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#316]
## Steps to reproduce:

1. Setup a `TextField` and set a placeholder text
2. Start typing
3. (While still focused) Clear the text field programmatically and change the placeholder string (Placeholder will be right at this point)
4. Focus on the text field
5. Leave the text field (at this point the placeholder string will get back to the original value)

## Reason:
`showTitleLabel()` uses a variable called `placeholderText` to store the placeholder string before removing it from the text field. `hideTitleLabel()` uses the same variable to restore the placeholder string. Now if the placeholder value gets updated while the title label is displaying (between a call to the mentioned methods), the `placeholderText` variable doesn't get updated, and when `hideTitleLabel()` gets called, it will set the placeholder value back to the the last time `showTitleLabel()` has updated it.

## Resolution:

Simple: ~~Move the `placeholderText` setter line to the `didSet` of the `placeholder`~~ (not a good idea)

----

I will submit a PR ASAP

**Comment by danieldahan** [comment]
Good catch. I will add this to the release later today. Thank you!

**Comment by danieldahan** [comment]
As always, I appreciate you bringing this to our attention. It is now fixed in [1.39.13](https://github.com/CosmicMind/Material/releases/tag/1.39.13).

**Comment by danieldahan** [comment]
Sorry, I didn't see that you would submit a PR.

**Comment by mohpor** [comment]
Thanks and No problem
I had fixed it in my PR but I didn't got the time to actually test it, therefore, No PR from me.

Thanks again
Glad to be of any help
M.

**Comment by mohpor** [comment]
Sorry to bother you again,
This fix doesn't work. When I was working on it yesterday, I did the same thing (at first) and forgot to consider this fact that `showTitleLabel()` actually sets the `placeholder` to `nil` after storing it in `placeholderText` therefore in the `didSet` we will lose the placeholder value altogether! The only way I could think of (without introducing a new state variable) is to check if the `titleLabel` is visible when updating the `placeholderText`. i.e.:

```swift
if !titleLabel.hidden {
    placeholderText = placeholder
 }
```

The idea here is that the problem happens only when the title label is visible, the rest is working just fine. 
To think about it, the whole mechanism needs to be redesigned.

**Comment by mohpor** [comment]
Well, that won't work either! in the `showTitleLabel()` the `titleLabel` is still hidden.

**Comment by danieldahan** [comment]
In the original fix I went with your recommendation. I think that a rethink in some aspect of the TextField would be a good idea. Tomorrow I can work on it as I continue my work on the TextView. Either way there will be a fix, but I don't want to push one tonight and then not be around for the next 12 hours. If you can think of an approach that would be great too.

**Comment by mohpor** [comment]
Yeah, my original idea sucked. That's why I didn't submit a PR at the first place.
I'm working today and I will find the time to do some thinking on at and I will share my ideas later on.
a bientôt

**Comment by riteshtechno** [comment]
Hello folks,

I am using this since the beginning and i am facing the same issue my side too. Let me know once you can fix that as i am stuck on this change.

Quick change is highly appreciated. 

Thank you in advance.

**Comment by jlichti** [comment]
I also hit this issue.

As a quick workaround I just wrapped the setting of placeHolderText inside the didSet for placeholder in a nil check so it wouldn't overwrite. (~line 380 in TextField.swift)

`if nil == placeholderText {
                placeholderText = placeholder
            }`

**Comment by mohpor** [comment]
It works but fails when you want to remove the placeholder.

**Comment by jlichti** [comment]
Yeah - true. Certainly not a robust solution but works for my small use as a workaround.

**Comment by mohpor** [comment]
Yeah, definitely works. Should revise the whole mechanism.

**Comment by danieldahan** [comment]
I'll be posting a solution later today with a couple of other issues fixed.

**Comment by mohpor** [comment]
I was thinking about it today. The only thing I could come up with was to introduce a new public variable that holds on to the placeholder value, propagates the changes to the underlying mechanism.

It has the caveat of introducing a small redundancy and breaking the `UiTextField` api.

**Comment by danieldahan** [comment]
I'll have a better idea of my solution in a couple hours when I am in front of my computer. All the suggestions though are good, as they are pointing out edge cases that still exist. I'll probably rework the internals to handle this more appropriately than introduce a quick fix.

**Comment by riteshtechno** [comment]
Hey Man,

Let me know if you have committed the patch so that i can work on that new patch. 

Thanks.

**Comment by danieldahan** [comment]
@riteshtechno Yes, almost done. Will be out later today. Thank you! :)

**Comment by danieldahan** [comment]
@riteshtechno and for those who are monitoring this issue. I am testing the solution I would like to push. Should be done momentarily.

**Comment by danieldahan** [comment]
Hey guys, please try [1.39.14](https://github.com/CosmicMind/Material/releases/tag/1.39.14). Thank you!

**Comment by mohpor** [comment]
Thanks @danieldahan,
I can confirm it solves the problem.

**Comment by riteshtechno** [comment]
I think its even worse. Now the place holder color gets changed in default place and nothing seems to be working.

**Comment by mohpor** [comment]
@riteshtechno 
Lets focus on the issue. If the placeholder color is not working right, open a new issue.

**Comment by danieldahan** [comment]
@riteshtechno The color issue is a new issue, and in general that would be a simple fix. If you open an issue with an example where it is breaking, or a suggested PR with the updated code from 1.39.14, we can release a new update.
