### ISSUE TITLE
[Request] Pull To Refresh

### ISSUE THREAD

**Issue by JackoPlane** [CosmicMind/Material#317]
Is the currently any plans to support Material's Swipe to Refresh control? Documentation: https://www.google.com/design/spec/patterns/swipe-to-refresh.html#swipe-to-refresh-swipe-to-refresh

**Comment by danieldahan** [comment]
Yeah, I will add it to upcoming :)

**Comment by danieldahan** [comment]
I plan to implement the upcoming list within the next couple weeks.

**Comment by JackoPlane** [comment]
Any update on this @danieldahan ?

**Comment by danieldahan** [comment]
Its unfortunately still in the queue. I'd be happy to work on it with you.
