### ISSUE TITLE
Side navigation bar for a single viewcontroller

### ISSUE THREAD

**Issue by sajeelmuhammed** [CosmicMind/Material#318]
I have a storyboard application written in Swift 2.0. Is there any way to use Side Navigation in a single View Controller. I tried implementing it as specified in the WiKi, to include the code in the AppDelegate, but unfortunately its applying to all the View controllers.

**Comment by danieldahan** [comment]
In the UIViewControllers you do not want the SideNav to be enabled, set the `enabled` flag to `false`. It works best to set it in the ```viewWillAppear``` method. 

```swift
override func viewWillAppear(animated: Bool) {
	super.viewWillAppear(animated)
	sideNavigationController?.enabled = false
}
```

All the best and please reopen or create a new issue you need more help :)
