### ISSUE TITLE
SideNavigation issue: main view gesture does not handle gesture correctly when user pan to close Left/Right sidebar 

### ISSUE THREAD

**Issue by hvbnet** [CosmicMind/Material#320]
You can try this scenario with your main App example.
Open sidebar, then try to pan for close sidebar and also scroll tableview
You must see that sometime tableview does not scroll and user think app hang. but if user remove hand from screen and pan again for scroll it work without any problem

Please note that i use map view on mainView and hang many times.
 
Thanks in advanced

**Comment by danieldahan** [comment]
Yes, I noticed this too, when you pan downward it actually triggers the SideNav to move. I would like to fix this today. I'll update you shortly.

**Comment by danieldahan** [comment]
@hvbnet Please try version 1.40.0. If the issue persists, please reopen the issue, or create a new one. Thank you!

**Comment by hvbnet** [comment]
thanks a lot
