### ISSUE TITLE
Card view depth 

### ISSUE THREAD

**Issue by saipnc** [CosmicMind/Material#323]
Hi,

I'm using card view with depth to show shadow effect which is even for all sides. Can we mimic like android's behaviour like the shadow effect is not even from all the sides, it varies from side to side.

**Comment by danieldahan** [comment]
Sounds good. I will take a look later today.

**Comment by saipnc** [comment]
Hi @danieldahan 

Thank you very for the reply, when can this is be updated in the library?

**Comment by danieldahan** [comment]
Well first I need to verify the difference in shadowing and if it would look good, etc. I will probably need to make another update on the TextField today, so I will update this issue at the time as your other one, [332](https://github.com/CosmicMind/Material/issues/332) :)

**Comment by saipnc** [comment]
@danieldahan, yes the TextField issue is important thanks :)

**Comment by danieldahan** [comment]
Hi @saipnc I updated the depths in [1.39.17](https://github.com/CosmicMind/Material/releases/tag/1.39.17) to give a better balance of the shadows. You as well can customize it further if you like. I added a MaterialDepth example project in the Programmatic directory if you would like to test it out. 
![screen shot 2016-04-22 at 11 19 19 am](https://cloud.githubusercontent.com/assets/9982123/14746516/07d6f3c4-087e-11e6-84e2-78269714cf54.png)

**Comment by saipnc** [comment]
@danieldahan thank you very much!
