### ISSUE TITLE
Example for MaterialTableViewCell.

### ISSUE THREAD

**Issue by mukeshthawani** [CosmicMind/Material#326]
Hi,

I was looking for an example or any help in using MaterialTableViewCell but it is present in the wiki. Can you add any example for that or any link so that like others this also becomes easier to implement?

Thanks

**Comment by danieldahan** [comment]
Hi, you can find an example of using the MaterialTableViewCell in the [App](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/App) example project. I am working on new documentation, so finding resources will be easier. Please feel free to reopen or create a new issue if you need any help. All the best!
