### ISSUE TITLE
TextField titleLabel issues

### ISSUE THREAD

**Issue by saipnc** [CosmicMind/Material#332]
Hi Guys,

In the recent update of the library, we have got new implementations of the TextField, we have an issue with the titleLabel animation. The titleLabel doesn't come back when nothing is typed (or when the text field is empty) in the TextField. We have gone through the implementation, we figured out that the hideTitleLabel function is not called when the handleEditingDidEnd if the text is empty. 

Also, in the library, we have been using CGRectNull in many places but it is crashing at sometimes, a solution that we found is to replace CGRectNull to CGRectZero. http://stackoverflow.com/questions/32919051/sublayer-with-non-finite-position-inf-inf

**Comment by danieldahan** [comment]
I am going to verify, as my tests returned different results. Thank you!

**Comment by danieldahan** [comment]
@saipnc When you say the titleLabel doesn't come back, are you still focused on the TextField?

**Comment by TonyStarkk** [comment]
Hi,

I have the same problem the label doesn't display anymore.

<img width="432" alt="capture d ecran 2016-04-21 a 17 35 22" src="https://cloud.githubusercontent.com/assets/6490189/14712857/829c42f4-07e7-11e6-95c2-5aab927d234a.png">
<img width="432" alt="capture d ecran 2016-04-21 a 17 35 17" src="https://cloud.githubusercontent.com/assets/6490189/14712859/8517b75c-07e7-11e6-9648-43e81dcf1f81.png">
<img width="432" alt="capture d ecran 2016-04-21 a 17 35 11" src="https://cloud.githubusercontent.com/assets/6490189/14712867/87334236-07e7-11e6-8db6-45d206fdd7dd.png">

Thank you

**Comment by danieldahan** [comment]
@TonyStarkk  Can you confirm what version you are using, Material 1.39.15?

**Comment by TonyStarkk** [comment]
I'am using Material 1.39.15.

**Comment by danieldahan** [comment]
Do you mind sharing your code setup? I tried a few devices and I can't reproduce the issue. Thank you!

**Comment by danieldahan** [comment]
@TonyStarkk I think this has to do with the internal setup of the titleLabel not having a frame size. Which is causing it to not display.

**Comment by TonyStarkk** [comment]
how i can setup it ?

**Comment by danieldahan** [comment]
Are you using AutoLayout to layout your views?

**Comment by TonyStarkk** [comment]
Yes i am using stackview and autolayout

**Comment by TonyStarkk** [comment]
<img width="1792" alt="capture d ecran 2016-04-21 a 18 39 15" src="https://cloud.githubusercontent.com/assets/6490189/14715131/5e68a81a-07f0-11e6-8a0f-10f31827e5b5.png">
<img width="1792" alt="capture d ecran 2016-04-21 a 18 39 03" src="https://cloud.githubusercontent.com/assets/6490189/14715135/6109bd70-07f0-11e6-8407-c00edc8462c3.png">

**Comment by danieldahan** [comment]
If I pushed a change to development, would you be able to try it? Or if I gave you a line of code to change, would you be able to do that?

**Comment by TonyStarkk** [comment]
Yes, as you want

**Comment by danieldahan** [comment]
Please try development.

**Comment by TonyStarkk** [comment]
You pushed i can try to update ?

**Comment by danieldahan** [comment]
yes, please

**Comment by TonyStarkk** [comment]
I tried but There is still no update

**Comment by danieldahan** [comment]
Are you using CocoaPods to get the package?

**Comment by TonyStarkk** [comment]
Yes :)
<img width="1792" alt="capture d ecran 2016-04-21 a 18 48 33" src="https://cloud.githubusercontent.com/assets/6490189/14715498/aec6b986-07f1-11e6-87a4-aa0728bbc4be.png">

**Comment by danieldahan** [comment]
OKay, give me a sec, I will make a CocoaPods installation and do the test.

**Comment by TonyStarkk** [comment]
Okay, thank you so much

**Comment by danieldahan** [comment]
no worries, it is a pleasure :)

**Comment by danieldahan** [comment]
Okay, all works for me. Which, now makes this more interesting. Would you be able to send me a sample project, or the one you have and I can see what the issue is?

**Comment by TonyStarkk** [comment]
Yes give me a sec, 
i send you it by email ?

**Comment by danieldahan** [comment]
Yes, @ support@cosmicmind.io

**Comment by saipnc** [comment]
@danieldahan in my case the titlaLabel once the text field becomes the first responder goes up and if nothing is typed it should come back right but the text field is out of focus it is not coming back. In earlier versions of the library, it is working well.

**Comment by danieldahan** [comment]
@saipnc Yes, there was a regression. I am working to fix this. It seems this is only in certain cases. Can you explain your setup, are you using AutoLayout, etc... ?

**Comment by TonyStarkk** [comment]
@danieldahan I've just send a sample of the project by we transfert, sorry for the time.

Thank you again

**Comment by danieldahan** [comment]
Yes, I received it now :) Thank you. I will look into this.

**Comment by saipnc** [comment]
Yes I'm using AutoLayout to position the text field with constraints: left, right and top.  This is happening in all the test fields for me. Do you want me to send a sample project?

**Comment by danieldahan** [comment]
Yes if you don't mind, please send to support@cosmicmind.io The issue is related to AutoLayout in some setups. Thanks!

**Comment by danieldahan** [comment]
@TonyStarkk I think the source files were stripped when sending the files. 
![screen shot 2016-04-21 at 1 28 52 pm](https://cloud.githubusercontent.com/assets/9982123/14718511/2046cfba-07c5-11e6-8ff9-6b68283dc2db.png)

**Comment by saipnc** [comment]
@danieldahan sent you the code through email. With details of the issues.

**Comment by danieldahan** [comment]
@saipnc thank you

**Comment by danieldahan** [comment]
@saipnc I have your project working now. One last case to handle, clearing the text programmatically.

**Comment by danieldahan** [comment]
Please try [1.39.16](https://github.com/CosmicMind/Material/releases/tag/1.39.16). If the issue persists, please reopen or create a new issue. Thank you very much for helping with this @TonyStarkk @mohpor @saipnc

**Comment by saipnc** [comment]
Thanks a lot @danieldahan :)
