### ISSUE TITLE
Raised Button font color cannot be changed

### ISSUE THREAD

**Issue by kaunteya** [CosmicMind/Material#333]
I dont know if I am doing anything wrong, but I am not able to change font color when I try to configure `RaisedButton` from Storyboard. No matter what Color you choose, it ends up showing White color font

**Comment by danieldahan** [comment]
Yes this was an issue and not it should be fixed in [1.39.17](https://github.com/CosmicMind/Material/releases/tag/1.39.17). Thank you for bringing this to our attention.
