### ISSUE TITLE
Setting `textField.titleLabel.font` does not change the font size.

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#334]
Note: these might be two separate issues.

- Setting `textField.titleLabel.font` does not change the font size but the frame is smaller/bigger.
- I noticed that in `showTitleLabel()` the `titleLabel.font` is set to the TextField's font. However there is no corresponding code to reset to the original `titleLabel.font`.

Also proposing to change the default `titleLabel.font` to `RobotoFont.regularWithSize(12)` as per Material Docs' [Text fields: Labels](https://www.google.com/design/spec/components/text-fields.html#text-fields-labels)

**Comment by danieldahan** [comment]
I like your proposal and will be working on the TextField today. I will take your other suggestion [336](https://github.com/CosmicMind/Material/issues/336) into consideration while working on this.

**Comment by danieldahan** [comment]
@zgosalvez Test this with the new TextField, temporary name MTextField in development. Please add any concerns to this issue [342](https://github.com/CosmicMind/Material/issues/342). Thank you!
