### ISSUE TITLE
Help: TextField Designables Build Failure

### ISSUE THREAD

**Issue by francisykl** [CosmicMind/Material#335]
Hi guys,

I am facing build issue for TextFields Designables. This also causes crashes when i try to configure placeholders and other property during runtime. Any idea what might be the cause?

![Image of Screenshot](https://i.imgsafe.org/842da15.png)
![Image of Screenshot](https://i.imgsafe.org/239d38c.png)

**Comment by danieldahan** [comment]
Yes, the crash is that their is a nil value. Are you setting the Module to Material when using the TextField? Not sure why you are marking out the text, makes it harder to diagnose.

**Comment by francisykl** [comment]
I set the module to my project, not material (default setting). 
I am marking out the text because the names contains sensitive info, but it shouldn't affect diagnostics though (its just class names)

**Comment by danieldahan** [comment]
When you set a class name, you have to set the module name to where the class lives. Try setting the module name to Material.

**Comment by francisykl** [comment]
I don't think that's the issue though. i am using cocoapods, they resides in the same workspace, and MaterialButton wouldn't have worked if that's the issue

![Image of Screenshot](https://i.imgsafe.org/016da05.png)

**Comment by danieldahan** [comment]
Can you show me the setup of the TextField?

**Comment by francisykl** [comment]
I found the cause, it seems the issue comes from my extension trying to set

`self.titleLabel = UILabel()` setter is inaccessible. 

in your example `textField.titleLabel = UILabel()` seems to be fine.. Any idea why it doesn't work in the extension of TextField

**Comment by danieldahan** [comment]
What version of Material are you using?

**Comment by francisykl** [comment]
i am using v1.39.17. Will take note on this. thanks

**Comment by danieldahan** [comment]
All the best :)
