### ISSUE TITLE
Button's Pulse Not Triggered

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#337]
When a button's `pulseFocus` is `true` quick tapping on the button does not trigger pulse.

**Comment by danieldahan** [comment]
The pulseFocus doesn't ripple, it stops the pulse once the touch is done. Hence the focus part, it only exists when focused. Can you confirm this?

**Comment by zgosalvez** [comment]
Based on my experience with Android, the pulse/ripple effect does not fade out until I lift my finger. I hoped to get this same experience by setting `pulseFocus` to `true`.

**Comment by danieldahan** [comment]
Yeah, it should pulseFocus, and then ripple out. This is a really important one, since Pulse is used everywhere. We must get it right :)

**Comment by danieldahan** [comment]
I resolved this in the new rewrite of the pulse animation. It is currently in development and I will push the fix tonight. Thank you!
