### ISSUE TITLE
"build failed" when I change the class of UIButton to FlatButton

### ISSUE THREAD

**Issue by FateRiddle** [CosmicMind/Material#341]
So I carthage installed Material, then dragged a UIButton into VC, when I changed the class of that UIButton to FlatButton in the identity inspector, "Designables" label showed under, and said " build failed". 
How to make it work?

**Comment by MarkOnly** [comment]
@FateRiddle change the calls of the UIButton to FlatButton before dragged it. Then you can drag and choose the class of the IBAction to FlatButton

**Comment by FateRiddle** [comment]
@MarkOnly  I change the class of the UIbutton before dragging, still the same error. But I do get to choose the class of the IBAction to FlatButton, then a runtime error: "Unknow class FlatButton in Interface Builder file".

**Comment by MarkOnly** [comment]
@FateRiddle if you get this error in storyboard it seems like you didn't have the framework imported correctly in the project

**Comment by danieldahan** [comment]
@FateRiddle Are you setting the Module to Material, after setting the class to FlatButton?

**Comment by FateRiddle** [comment]
@danieldahan  how do I set the module to Material?

**Comment by danieldahan** [comment]
@FateRiddle You should see a field under the field where you specify the class value. See the screenshot attached. 
![screen shot 2016-04-28 at 2 23 20 pm](https://cloud.githubusercontent.com/assets/9982123/14896703/ea59a642-0d4c-11e6-9b41-4926365f860e.png)

Also, please refer to this [example project](https://github.com/CosmicMind/Material/tree/master/Examples/Storyboards/MaterialButton) to see this in a working example.

**Comment by FateRiddle** [comment]
My project don't have the "Material" option in module. Guess I haven't install it properly. I've only used Carthage to install Material. What other steps should I proceed? BTW, I can use the sample code to generate UI programatically on a blank storyboard, after "import Material".

**Comment by danieldahan** [comment]
Hmmm... I am not sure of Carthage's limitations. Though, when I add the module, Material, I am using the setup from [here](https://github.com/CosmicMind/Material/wiki), which is the least dependant method of setting up Material.  Did you try adding the module and running anyway?

**Comment by danieldahan** [comment]
As I have not heard from you, I am going to close this issue. If it continues to persist, please reopen the issue, create a new one, or join us on gitter: https://gitter.im/CosmicMind/Material
