### ISSUE TITLE
Toolbar Title Label not centered with left button

### ISSUE THREAD

**Issue by mitch10e** [CosmicMind/Material#343]
The title label for a Toolbar is not centered if the textAlignment is set to .Center and there is a button in the leftControls. The label is centered if I remove the leftControls.

![simulator screen shot apr 28 2016 9 48 06 am](https://cloud.githubusercontent.com/assets/5041044/14892020/51fd9352-0d26-11e6-8f42-2aa0e8161652.png)

```
@IBOutlet weak var toolbar: Toolbar!
    
    // MARK: View Preparation
    
    override func prepareToolbar() {
        // Stylize.
        toolbar.backgroundColor = Color.navy
        
        // Title label.
        let titleLabel: UILabel = UILabel()
        titleLabel.text = "Material"
        titleLabel.textAlignment = .Center
        titleLabel.textColor = MaterialColor.white
        titleLabel.font = RobotoFont.regular
        toolbar.titleLabel = titleLabel
        
        // Menu button.
        let img1: UIImage? = MaterialIcon.cm.menu
        let btn1: FlatButton = FlatButton()
        btn1.pulseScale = false
        btn1.pulseColor = MaterialColor.white
        btn1.tintColor = MaterialColor.white
        btn1.setImage(img1, forState: .Normal)
        btn1.setImage(img1, forState: .Highlighted)
        
        // Add buttons to left side.
        toolbar.leftControls = [btn1]
        

    }
```

**Comment by danieldahan** [comment]
@mitch10e At the current moment, the Toolbar only works with equal siding for both controls. You can use a clear button with no pulse to balance our the two sides. The toolbar is going to be updated shortly to handle the issue you are facing in a cleaner manner.

**Comment by mitch10e** [comment]
Awesome! Thank you so much! Love this library!

**Comment by danieldahan** [comment]
:) Amazing. Thank you!
