### ISSUE TITLE
Toolbar Title Label not in the center with left button.

### ISSUE THREAD

**Issue by mitch10e** [CosmicMind/Material#344]
The title label for a Toolbar is not centered if the textAlignment is set to .Center and there is a button in the leftControls. The label is centered if I remove the leftControls.

![simulator screen shot apr 28 2016 9 48 06 am](https://cloud.githubusercontent.com/assets/5041044/14892020/51fd9352-0d26-11e6-8f42-2aa0e8161652.png)

```
@IBOutlet weak var toolbar: Toolbar!
    
    // MARK: View Preparation
    
    override func prepareToolbar() {
        // Stylize.
        toolbar.backgroundColor = Color.navy
        
        // Title label.
        let titleLabel: UILabel = UILabel()
        titleLabel.text = "Material"
        titleLabel.textAlignment = .Center
        titleLabel.textColor = MaterialColor.white
        titleLabel.font = RobotoFont.regular
        toolbar.titleLabel = titleLabel
        
        // Menu button.
        let img1: UIImage? = MaterialIcon.cm.menu
        let btn1: FlatButton = FlatButton()
        btn1.pulseScale = false
        btn1.pulseColor = MaterialColor.white
        btn1.tintColor = MaterialColor.white
        btn1.setImage(img1, forState: .Normal)
        btn1.setImage(img1, forState: .Highlighted)
        
        // Add buttons to left side.
        toolbar.leftControls = [btn1]
        

    }
```

**Comment by danieldahan** [comment]
@mitch10e Did you fix it?

**Comment by jmheist** [comment]
@danieldahan  This same issue still exists for Navigation Controller. When a back button is present, it offsets the title. Adding buttons to the navigationItem.right/leftBarButtonItems does not effect the layout of the title.

**Comment by danieldahan** [comment]
Yes this was not fixed yet. It is coming up in the 2.0 branch I am working on. I am fixing a bunch up while cleaning up the code in that branch. You can see the changes as I go in development.

**Comment by danieldahan** [comment]
Working on this today, so hopefully a fix will be in the `development` branch today or tomorrow. Thank you!

**Comment by danieldahan** [comment]
Hey! This has been fixed as in the development branch. Please set the `textAlignment` property of either the `titleLabel` or `detailLabel` to `center` and the label should always maintain a centered state.
