### ISSUE TITLE
TableView Editing Enabled Randomly

### ISSUE THREAD

**Issue by smkhalsa** [CosmicMind/Material#345]
About every 20th time I swipe a table view cell left, I see the edit button slide out. I have not enabled editing via the delegate method.

The odd part is how inconsistent it is. I can swipe the same cell left 15 times and nothing happens, then twice in a row it might show the edit button. 

I'm using tableViews extensively in my application, and this issue appears to be present in all of them.

**Comment by danieldahan** [comment]
Are you using the MaterialTableViewCell, as well, are you using the SideNav?

**Comment by danieldahan** [comment]
Hi, as I have not heard from you, I am closing this issue. If this continues to persist, please let me know. I have double checked the TableViewCell code, and the userInteraction is all set to false

```swift
imageView?.userInteractionEnabled = false
textLabel?.userInteractionEnabled = false
detailTextLabel?.userInteractionEnabled = false
```

The only interaction we added is the pulse animation, which has nothing to do with panning or any sort of gesturing. 

If you need, send an example project to support@cosmicmind.io and we will see if we can help you. 

All the best!
