### ISSUE TITLE
Problem with importing Material

### ISSUE THREAD

**Issue by MaticConradi** [CosmicMind/Material#346]
So I've just started with Material. I've followed the instructions on https://github.com/CosmicMind/Material/wiki but I can't get `import Material` to work. It says
![screen shot 2016-04-29 at 21 00 18](https://cloud.githubusercontent.com/assets/5693961/14926773/1a23770c-0e4e-11e6-973b-5ce74fbf42e6.png)
Any ideas what I could have done wrong?

**Comment by danieldahan** [comment]
Welcome to Material :) 
Did you add the framework to embedded binaries?

**Comment by MaticConradi** [comment]
Yes. Here it is...
![screen shot 2016-04-29 at 21 22 34](https://cloud.githubusercontent.com/assets/5693961/14927153/90c112be-0e50-11e6-8019-fbd7ea3155fa.png)

**Comment by danieldahan** [comment]
When you built the framework, was it the iOS one? Can you send me a screen grab of your workspace so I can see all the moving parts?

**Comment by MaticConradi** [comment]
I built the framework before I created my own project and it was the iOS one (I built it on Generic iOS device)
![screen shot 2016-04-29 at 21 54 25](https://cloud.githubusercontent.com/assets/5693961/14927901/fb6d26f8-0e54-11e6-8a8b-40adcb3a17ef.png)

**Comment by danieldahan** [comment]
I don't see anything wrong with your setup. If you can close your workspace, and open the Examples/Material workspace. Build Material, then go to a project and embed it and then run the project. See if that works.

**Comment by MaticConradi** [comment]
It seems like this fixed my problem, but I have no idea why. Thanks!

**Comment by danieldahan** [comment]
Well as long as you are in a forward direction. Probably had to do with DerivedData and build directory conflicts. When you dragged in Material, it could of linked incorrectly. Either way, welcome and feel free to post an issue if you have any.
