### ISSUE TITLE
Disable TextField's placeholder animation

### ISSUE THREAD

**Issue by gilthonweapps** [CosmicMind/Material#347]
Hi,

In some of my views, I am using several TextField objects. Sometimes, they are quite close to each other in a UITableViewCell.
When one TextField receives the focus, the placeholder text is animated and move to the top of the field. The animation is really nice, but in my case, the text overlaps the TextField that is above.
You have already added an option to hide the detailLabel. I think you should add another option to hide the titleLabel.
Thanks.

**Comment by danieldahan** [comment]
Hi, so I have recently rewrite the TextField and will be releasing it shortly with some additional changes, [342](https://github.com/CosmicMind/Material/issues/342). Please join the discussion there :) I would like to discuss this more.
