### ISSUE TITLE
SideNavigationController still receive gesture

### ISSUE THREAD

**Issue by MarkOnly** [CosmicMind/Material#348]
Hello, it's all day that I try, maybe I miss something... From what I read sideNavigationController?.enabled = false it's uses to remove the pan gesture recognize. But it doesn't work..
In a view I won't that the user could open the sidenavigationcontroller but with a pan gesture I can still open it... 

Sorry for my english.
Thank you.

**Comment by danieldahan** [comment]
Put the enabled setting in the viewWillAppear method

**Comment by MarkOnly** [comment]
@danieldahan yeah that fix this. Thank you ! :)
