### ISSUE TITLE
titleLabel in CardView takes up space even if not set

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Material#354]
I'm using a CardView but only setting detailView:
```
        //cardView.titleLabel = titleLabel
        contentView.backgroundColor = MaterialColor.green.base
        cardView.detailView = contentView
        postsView.addSubview(cardView)
```
It seems as the titleLabel is taking up some space even when I don't set it.

<img width="460" alt="screen shot 2016-05-02 at 10 35 49" src="https://cloud.githubusercontent.com/assets/14074538/14950416/c5513510-1051-11e6-95f3-d255e912e643.png">

**Comment by mohpor** [comment]
have you tried to set the `titleLabelInsetPreset` of the card view? it is defaulted to `Square2`

**Comment by mohpor** [comment]
there is a `detailViewInsetPreset` available too. My guess is the second inset preset.

**Comment by mohpor** [comment]
@theolof 
in a test project I have found that setting two parameters on card view should solve your problem:

```swift
    cardView.contentInsetPreset = .None
    cardView.detailViewInsetPreset = .None
```

**Comment by theolof** [comment]
Thanks, @mohpor. `cardView.detailViewInsetPreset = .None` was the one that did it. I didn't need `cardView.contentInsetPreset = .None` since I wanted some margins inside the CardView.
