### ISSUE TITLE
Mix MaterialTableViewCell and SWTableViewCell

### ISSUE THREAD

**Issue by gilthonweapps** [CosmicMind/Material#356]
Hi,

I am using MaterialTableViewCell for all my cells in my app as I really like the pulse effect and all the other features.
I am as well looking at SWTableViewCell (https://github.com/CEWendel/SWTableViewCell) because I would like to be able to display extra buttons when swiping left or right.
So, I suppose I have to use SWTableViewCell for my cells. But how can I use all the visual effects of MaterialTableViewCell on top of it?

Thanks

**Comment by mohpor** [comment]
you can use the `SWTableViewCell` as normal, and while formatting your cell, slip a `MaterialPulseView` in the background or even set cell's `backgroundView` and `selectedBackgroundView` with `MaterialPulseView`.

**Comment by danieldahan** [comment]
Yes that sounds correct. :) @mohpor

**Comment by gilthonweapps** [comment]
Thanks for the info :)

**Comment by danieldahan** [comment]
I am closing this issue. If you have any further issues, please reopen, or create a new one. Thank you!
