### ISSUE TITLE
How to make MaterialTableCells have an image indentation but not an image?

### ISSUE THREAD

**Issue by psuedonovicecoder** [CosmicMind/Material#358]
This seems quite strange but, when you add an image to a MaterialTableCell, the divider gets an indentation. However, the other cells do not. This irks me quite a bit and I was wondering how I can add the effect (the divider indentation).

**Comment by danieldahan** [comment]
Thank you for bringing this to our attention. I fixed the issue by adding this line of code to the cell

```swift
cell.separatorInset = UIEdgeInsetsZero
```
In the next release, this will already be set and you will not have to include it in your application. 

Thank you!
