### ISSUE TITLE
MaterialSwitch sizes

### ISSUE THREAD

**Issue by tySwift93** [CosmicMind/Material#360]
It seems to me that currently the only way to have a custom size for a Material Switch is to alter the code directly before building the framework.  Am I missing something?  I feel like changing its size should be easy and that I'm probably missing something!  Thank you for the help

**Comment by danieldahan** [comment]
There are three different sizes, .Small, .Default, and .Large.

```swift
let c1: MaterialSwitch = MaterialSwitch(state: .Off, style: .LightContent, size: .Small)
let c2: MaterialSwitch = MaterialSwitch(state: .On, style: .LightContent) /* Default doesn't need to be set. */		
let c3: MaterialSwitch = MaterialSwitch(state: .Off, style: .LightContent, size: .Large)
```

Otherwise, the customization of the MaterialSwitch is a little tricky. It will be rewritten soon, so if you have any suggestion, please send them this way.
