### ISSUE TITLE
TextView autoresizing

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#361]
Android text views can be automatically autoresized according to their content height. It would be nice to see such a functionality incapsulated into Material TextView. Thank you.

**Comment by danieldahan** [comment]
Yes, I will add this type of feature while I rebuild the TextView :) Thank you!

**Comment by danieldahan** [comment]
I have taken this into consideration and will include it in the release of the TextView. Thank you! As it is not an issue, I will close it for now. I plan on the releasing the new TextView within the next 10 days.
