### ISSUE TITLE
2x and 3x Assets Are Ignored when using CocoaPods

### ISSUE THREAD

**Issue by jstheoriginal** [CosmicMind/Material#362]
When using CocoaPods, the assets don't work correctly as all 2x and 3x assets end in "_2x" and "_3x" instead of "@2x" and "@3x". iOS just defaults to the base png which is pixelated. When I change the "_3x" to "@3x" on an asset, it displays correctly.

I believe the solution is to rename the assets, but if there is another solution, please advise.

**Comment by danieldahan** [comment]
Please try [1.40.1](https://github.com/CosmicMind/Material/releases/tag/1.40.1). I updated all the icons :)

**Comment by jstheoriginal** [comment]
Woohoo! Thank you. :D
