### ISSUE TITLE
SideNavigationViewController disable swipe gesture

### ISSUE THREAD

**Issue by Sunitadaffodil** [CosmicMind/Material#365]
How to disable swipe gesture of SideNavigationController . I want to open side menu on button click only. 
Right now it opens on right and left swipe also.

**Comment by mohpor** [comment]
Right now `panLeftViewGesture` and `panRightViewGesture` are `internal` variables and you don't have access to disable them. We need to make them public.
Meanwhile, you can subclass the `SideNavigationViewController` and override `public func gestureRecognizer(_, shouldReceiveTouch touch) -> Bool` function to return `false`.

**Comment by danieldahan** [comment]
The approach you are about to take may or may not be effective. I am going to add a property that says to enable and disable both pan and tap.

**Comment by danieldahan** [comment]
Please try [1.40.1](https://github.com/CosmicMind/Material/releases/tag/1.40.1). I added enable booleans for all gestures. Thank you! :)
