### ISSUE TITLE
TextField text label widens when becomes active with clear button enabled

### ISSUE THREAD

**Issue by jstheoriginal** [CosmicMind/Material#367]
When you have a clear button enabled, enter some text and then leave the field. click in the field again and the text will quickly widen and return to it's correct size. This only happens when the clear button is enabled.

This is just a textfield dropped in and set to be TextField class, with clear button turned on.

Gif: http://cl.ly/2P1x0C0N2R2w

Any ideas what might be causing this?

**Comment by danieldahan** [comment]
Can you send me your code setup?

**Comment by jstheoriginal** [comment]
Hey Daniel,

We've figured out the issue...we were calling view.layoutIfNeeded() which was what caused the TextField to perform that way. Not sure if there's a way to prevent that with an enhancement in the future, but for now, we just removed that line of code.

Thanks!

**Comment by danieldahan** [comment]
Awesome! I will close this issue then. Thank you!
