### ISSUE TITLE
Sidenavigationbar with 3 tab

### ISSUE THREAD

**Issue by girishghoda** [CosmicMind/Material#369]
hi danieldahan,
Thanks for create great library. i use sidenavigatincontroller with 3 tab but how to handle 3 view controller with same side navigationcontoller.

my view as same as you display demo view in material github main page https://camo.githubusercontent.com/ecfd0bd7e5ebe8d8c505c0be1da77a630c53f6d9/687474703a2f2f7777772e636f736d69636d696e642e696f2f4d4b2f4d6174657269616c4170702e676966

please help

thank you

**Comment by danieldahan** [comment]
Are you asking how to switch the view from the SideNav, or the Tab?

**Comment by girishghoda** [comment]
ya for tab but toolbar & sidenavigationcontroller same for 3 view

**Comment by danieldahan** [comment]
I am about to head out and will be back in a couple hours. I will give you feedback on the easiest way to do it once I am back to my computer.

**Comment by girishghoda** [comment]
ok thank you danieldahan.

**Comment by girishghoda** [comment]
![img_0224](https://cloud.githubusercontent.com/assets/19307918/15184097/83e81f14-17b1-11e6-9881-268d5c394ad1.jpg)
 i attach screenshot for your better understand.

**Comment by danieldahan** [comment]
So the setup you should have is:

1. Global SideNav, which wraps The BottomNavigation (TabBar)
2. When you Tab between UIViewControllers in the Tab, rather than this:

```swift
let bottomNavigationController: BottomNavigationController = BottomNavigationController()
bottomNavigationController.viewControllers = [VideoViewController(), PhotoViewController()]
```

do this:

```swift
let bottomNavigationController: BottomNavigationController = BottomNavigationController()
bottomNavigationController.viewControllers = [NavigationController(rootViewController: VideoViewController()), NavigationController(rootViewController: PhotoViewController())]
```

So you are not tricking anything in this solution. If you are not using the internal NavigationController panning, you should use a Toolbar, and thus switch out the NavigationController(root...) code to ToolbarController(root...) code. 

Make sense? Or did I misunderstand your issue?

**Comment by danieldahan** [comment]
If you have any further issues, please let us know, or if you require more assistance on this issue, please let us know. Thank you!

**Comment by girishghoda** [comment]
i want to create same as one activity with navigation drawer with 3 fragment like android.
so in ios problem is that tab have seprate viewcontroller ,so i lost rootview which has toolbar & sidenavigation.

so i can handle for tab view which have upper toolbar & side navigation are same like android one activity have 3 fragment only inner view change.

**Comment by danieldahan** [comment]
Okay, in the morning I will help you out. It is late now and I am going to be sleeping soon.

**Comment by danieldahan** [comment]
Actually for this issue, let's move to [Gitter](https://gitter.im/CosmicMind/Material). Add any details you like there, and in the morning I will take a look. I believe I know what you are looking for.

**Comment by girishghoda** [comment]
ok no problem danieldahan. actually i from india so i post my problem at tis time.
sorry for interfere.

thank you

**Comment by danieldahan** [comment]
No worries :) we are here to help.
