### ISSUE TITLE
1.41 will not build Carthage...NavigationController in Storyboard examples is missing project.pbxproj

### ISSUE THREAD

**Issue by lutzj82** [CosmicMind/Material#371]
It looks like a recent check-in may have meant to remove the example project completely? But left behind some files?

**Comment by danieldahan** [comment]
Can you share the error you are getting?

**Comment by lutzj82** [comment]
sure.
`*** Checking out Material at "1.41.0"
*** xcodebuild output can be found in /var/folders/1r/gw68_wv57bn807_b2sm71scm0000gp/T/carthage-xcodebuild.GnzolL.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/devaccount/Code/rounding-ios/Carthage/Checkouts/Material/Examples/Storyboards/NavigationController/NavigationController.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'NavigationController.xcodeproj' from folder '/Users/devaccount/Code/rounding-ios/Carthage/Checkouts/Material/Examples/Storyboards/NavigationController'.
	Reason: Project /Users/devaccount/Code/rounding-ios/Carthage/Checkouts/Material/Examples/Storyboards/NavigationController/NavigationController.xcodeproj cannot be opened because it is missing its project.pbxproj file.`

**Comment by danieldahan** [comment]
Can you try cleaning your build folder and derived data?

**Comment by lutzj82** [comment]
That worked. Is this a Carthage issue?

**Comment by danieldahan** [comment]
No just files left over in the caching of the build system. It happens in compiled systems here and there. Happy it worked :)
