### ISSUE TITLE
Square shadow in FabButton

### ISSUE THREAD

**Issue by urizev** [CosmicMind/Material#375]
Hi,

There is a weird shadow under a FabButton. Here is a video:

  https://youtu.be/O4CIaIu7eow

It not always happens. Sometimes the square doesn't appear and it is alright and other times it happens like the video shows. When the button is tapped, the square shadow disappears and everything goes right.

¿Any idea? I have tried to tweek some shadow parameters but it does not work

Thanks

**Comment by mohpor** [comment]
Could you post some code too?
How are you initialize your fabButton?

**Comment by urizev** [comment]
I create the button in the StoryBoard. I can post screenshots or sourcecode if it helps

**Comment by mohpor** [comment]
yeah, that would be nice.
If you're formatting your button in code, please add some of the code, and if you use only the storyboard, please add some screenshots.
Thanks a lot.

**Comment by urizev** [comment]
Here you can find the screenshots. Let me know if you need further information

<img width="124" alt="captura de pantalla 2016-05-13 a las 12 35 16" src="https://cloud.githubusercontent.com/assets/997364/15245531/60bc01fc-1907-11e6-8259-78039b37a7d2.png">
<img width="269" alt="captura de pantalla 2016-05-13 a las 12 35 33" src="https://cloud.githubusercontent.com/assets/997364/15245527/5d7c7d0a-1907-11e6-9365-6f77f804038b.png">
<img width="265" alt="captura de pantalla 2016-05-13 a las 12 35 49" src="https://cloud.githubusercontent.com/assets/997364/15245520/53a02cfa-1907-11e6-82a9-6dcb7325a313.png">
<img width="266" alt="captura de pantalla 2016-05-13 a las 12 36 07" src="https://cloud.githubusercontent.com/assets/997364/15245517/4dc2b546-1907-11e6-9641-bfb213789deb.png">

Thanks!

**Comment by mohpor** [comment]
could you try and set the `shape` property of the fab button to `.Circle` in the `viewDidLoad()` of your view and see what happens then?

```swift
fabButton.shape = .Circle
```

**Comment by urizev** [comment]
The same thing happens: The square shadow appears sometimes and when it does not appears, it flickers before disappear.

**Comment by mohpor** [comment]
Hmmm.... It's interesting.
I'm going to try and reproduce it in a test project, would be great if you could do that.

**Comment by urizev** [comment]
I have just check that if shape is set to .Circle in viewDidAppear(), the square shadow doesn't appear but there still are some flickers

**Comment by mohpor** [comment]
Ok,
about the view hierarchy, your fabButton is inside a MapView? does it especially flicker when you pan or zoom your map view?

**Comment by mohpor** [comment]
What Material version are you using? Have you updated your pod recently? it is currently at `1.41.1

**Comment by urizev** [comment]
No, it is over the map but not inside.

It flickers only at the begining. Square shadow does not appear after the flickers.

I was using 1.39.17, but the same thing happens with 1.41.1

**Comment by mohpor** [comment]
I can't really reproduce the issue my self, but I can suggest a couple of things:

1. Call `prepareView()` in `viewWillAppear()`
2. Setup the fab button in code and see what happens.

**Comment by urizev** [comment]
Ok, I will try that approach. Thanks

**Comment by urizev** [comment]
If I call prepareView on viewWillAppear() its background color is red. If I change the background color after calling prepareView() it shows ok.

Anyway, it keeps on flickering

**Comment by danieldahan** [comment]
This is a weird issue @urizev. It would result because the FabButtons frame is being altered to a square at one point. The flickering means it is struggling to maintain its shape. What AutoLayout constraints do you have on it from Storyboards?

**Comment by urizev** [comment]
Yep! Here you have a screenshot. Really simple as you can see

<img width="260" alt="captura de pantalla 2016-05-13 a las 19 19 00" src="https://cloud.githubusercontent.com/assets/997364/15256013/a09eb084-193f-11e6-8006-10d62b3d6ce5.png">

**Comment by urizev** [comment]
I have been able to create a small project with the same issue:
   https://github.com/urizev/FabButtonTester

**Comment by danieldahan** [comment]
Excellent I will take a look shortly.

**Comment by mohpor** [comment]
So,
I checked upon your sample project.
There is nothing wrong with it! I mean on device it never happens (Have you tested it on device too?).
I saw it once, on simulator only, and after I opened up story board in xcode and saved it, it never came up on simulator too. It must be a glitch with Xcode's Interface Builder.

@urizev Can you confirm that it happens on device or not?

**Comment by mohpor** [comment]
@urizev have you tested it on device? Are you still seeing that square shape shadows?

**Comment by danieldahan** [comment]
Let's move this to Gitter for further discussion as it is not reproducible. Thank you! [Gitter/CosmicMind/Material](https://gitter.im/CosmicMind/Material).

**Comment by urizev** [comment]
Sorry for my silence. I was busy these days.

I have no real device available for the tests. So if you say it doesn't occur for me it's perfect.

Thank you and sorry for the inconveniences

**Comment by danieldahan** [comment]
It is not an inconvenience at all. Thank you for bringing this to our attention :)

**Comment by Matungos** [comment]
I'm having this issue now. On simulator and on a device too.

**Comment by danieldahan** [comment]
@marungos please share your setup code and what version of Material you are using. Thank you

**Comment by Matungos** [comment]
I'm using version 1.42.7
I've added the FabButton via Storyboard with constraints height = 56 and width = 56

My prepareFabButton called in viewDidLoad is:
```
    private func prepareFabButton() {
        let img: UIImage? = MaterialIcon.cm.add
        fabButton.setImage(img, forState: .Normal)
        fabButton.addTarget(self, action: #selector(handleFabButton), forControlEvents: .TouchUpInside)
    }
```

The workaround suggested works fine: 
```
override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        fabButton.prepareView()
        fabButton.backgroundColor = UIColor.grayColor()
    }
```
but I would like to have a workaround-free code.

This could be a clue: on first tap on the button, the square shadow makes an animation shrinking and rotating counterclockwise 90° and don't appear again until restart the app.

Sorry for my english.

BTW, great framework! Thank you

**Comment by danieldahan** [comment]
@Matungos I am not seeing anything that looks incorrect. Would you be able to send an example project to support@cosmicmind.io ? Thank you!
