### ISSUE TITLE
Can't set UILabel for title of Toolbar.

### ISSUE THREAD

**Issue by TheHmmka** [CosmicMind/Material#376]
Hi! Found one problem that property titleLabel of Toolbar is readonly in 1.41.1. How could I set label for title and detail?

**Comment by mohpor** [comment]
As of `1.41.1` `Toolbar` doesn't need you to setup a label and assign to it, just format the toolbar's `TitleLabel` and `DetailLabel` however you like.

Good luck.

**Comment by TheHmmka** [comment]
Confused with this page: https://github.com/CosmicMind/Material/wiki/Toolbar.
And when I just set text and font for titleLabel - it looks unlayouted. Can't make screenshot right now cause I reverted to 1.40.0.

**Comment by mohpor** [comment]
@TheHmmka The toolbar's Wiki page is not reflecting the last version of Material. The whole documentation is being under reconstruction. Sorry for the inconvenience for now. I have used toolbar with 1.41.1 and it works like a charm. Would love to see some screenshots about it not having the correct layout any time you possibly could.
Cheers
M.

**Comment by mohpor** [comment]
@TheHmmka is this still an issue or we can safely close this issue?

**Comment by danieldahan** [comment]
I am going to close this, thank you @mohpor. @TheHmmka if the issue persists. Please let me know. I am updating docs during today and this week. Thank you!

**Comment by TheHmmka** [comment]
Looks like it works. But I found other issues. Will open another ticker.
