### ISSUE TITLE
Facing issue (pulseScale)

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#377]
<img width="1024" alt="screen shot 2016-05-13 at 5 03 26 pm" src="https://cloud.githubusercontent.com/assets/8962264/15246726/b1c76328-192c-11e6-8584-cb204bae52d6.png">

ScreenShot ^

**Comment by mohpor** [comment]
There has been a change in pulse animation and toolbar controls:

* Pulse controls and views now have a new property to handle pulse: `pulseAnimation` which controls the way an item pulses, and about the `pulseScale` option.

* `Toolbar` doesn't need you to setup labels for title and detail label. You can now format the toolbar title and detail label however you like.

**Comment by chashmeetsingh** [comment]
how to format the toolbar title and detail thing ?
code or example? @mohpor

**Comment by mohpor** [comment]
before, you would setup a `UILabel` and formatted it (font, text color, etc.) and assign it to the toolbar's `titleLabel` or `detailLabel`. 
Now, toolbar has the pre-formatted `titleLabel` and `detailLabel`. you just need to modify it to match your own formatting (font, text color, etc)

e.g.:

```swift
toolbar.titleLabel.textColor = UIColor.White()
...
```

**Comment by chashmeetsingh** [comment]
thanks

**Comment by chashmeetsingh** [comment]
No images are being displayed

**Comment by mohpor** [comment]
Well, that's a whole another issue. I have submitted a pull request to solve it. it'll be fixed ASAP.

**Comment by chashmeetsingh** [comment]
<img width="404" alt="screen shot 2016-05-13 at 5 38 33 pm" src="https://cloud.githubusercontent.com/assets/8962264/15247390/867719ca-1931-11e6-8497-98902deca7ba.png">

tried center aligning a label

**Comment by mohpor** [comment]
That's because the tile is getting centered to the available width. the only way I can think of, is to set content inset for the toolbar itself to compensate for right toolbar items.

**Comment by chashmeetsingh** [comment]
Thanks @danieldahan
