### ISSUE TITLE
cocoapods 1.0 installation failed 

### ISSUE THREAD

**Issue by piromano** [CosmicMind/Material#380]
In the new cocopods the XCAssets of icons are not copied during the build

**Comment by mohpor** [comment]
It's in the works, will be released shortly. For now you can use the development branch (with a solution to this) or revert back to Cocoapods 0.39.

**Comment by mohpor** [comment]
here is how to use the development branch own your podfile:
```
pod 'Material', :git => "https://github.com/CosmicMind/Material.git", :branch => 'development'
```

**Comment by piromano** [comment]
it works, thanks.
