### ISSUE TITLE
Layout doesn't respect frame of Toolbar.

### ISSUE THREAD

**Issue by TheHmmka** [CosmicMind/Material#382]
<img width="412" alt="2016-05-16 09 56 00" src="https://cloud.githubusercontent.com/assets/468660/15282588/fec7215a-1b4c-11e6-9776-e0b1085ecd6d.png">

As you can see layout on the picture above - plus and back arrow doesn't sit in right play.
I have gray UIView with Toolbar at the top of this view. I setup frame for Toolbar with next code:

```
self.contentView.frame = self.bounds;
self.navigationBarView.frame = CGRectMake(0, 0, self.contentView.bounds.size.width, self.navigationBarView.bounds.size.height);
```

**Comment by mohpor** [comment]
where are setting the frame? `viewDidLoad()`?

**Comment by TheHmmka** [comment]
No, no. This is not UIViewController. It's just UIView. I set frame in `-(void) layoutSubviews` method.

**Comment by mohpor** [comment]
`Toolbar` is a subclass of `StatusBar` they assume the device's width as their width. and changing the frame and laying out won't affect their actual width.

If you want to embed a toolbar inside a view with a width smaller than the device's, you should subclass the `Toolbar` and override the `intrinsicContentSize()` function and return the appropriate size for your view. You can use the `super`'s `intrinsicContentSize()` and just change the width.

And I think it's a good pattern to call the `layoutSubviews()` of the toolbar in your view's layout mechanism.

Let me know if it you needed more explanation.
Cheers,
M.

**Comment by TheHmmka** [comment]
Ok, thanks, I will try.

**Comment by mohpor** [comment]
Here is the code I used to test my theory :


```swift
// In a subclass ot `Toolbar`
  override func intrinsicContentSize() -> CGSize {
    var size = super.intrinsicContentSize()
    size.width = self.frame.width
    return size
  }

```

```objc
// In a subclass ot `Toolbar`
-(CGSize)intrinsicContentSize {
  CGSize size = [super intrinsicContentSize];
  size.width = self.frame.size.width;
  return size; 
}

```
and it worked like a charm!

**Comment by danieldahan** [comment]
Should be fixed [1.41.2](https://github.com/CosmicMind/Material/releases/tag/1.41.2) :)

**Comment by TheHmmka** [comment]
Oh, with 1.41.2 I totally lost Toolbar. :-)

<img width="422" alt="2016-05-18 13 29 26" src="https://cloud.githubusercontent.com/assets/468660/15355666/c6586a52-1cfc-11e6-9fa6-8704e4729610.png">

**Comment by mohpor** [comment]
@TheHmmka you need to set a frame for your toolbar now. Height will have a default value, but make sure you set an appropriate `width` for the toolbar. It most likely will be its superview's width.

**Comment by TheHmmka** [comment]
I mean that It disappeared even when I use Toolbar with UIViewController. As I understood I need to set width in this case too?

**Comment by mohpor** [comment]
@TheHmmka That's right. You can init your toolbar with a frame or set its frame after init.

**Comment by TheHmmka** [comment]
It works. Thanks!
