### ISSUE TITLE
Docs not updated for tab controller

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#385]
Need the docs for using tab controller 
Links ? Also the navigation controller one doesn't have images

**Comment by danieldahan** [comment]
Yes I am working on the documentation.

**Comment by danieldahan** [comment]
The best way to view the documentation for now is through the example projects. During this week I will be updating the documentation at the http://cosmicmind.io/material website. If you have any question, please open an issue or visit the [Gitter/CosmicMind/Material](https://gitter.im/CosmicMind/Material) page. All the best!

**Comment by chashmeetsingh** [comment]
thanks
