### ISSUE TITLE
 whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by JeremyJF** [CosmicMind/Material#389]
My code is as follows and I get the above error

		override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
		if (segue.identifier == "ActivityPref") {
			let nav3 = segue.destinationViewController as! UINavigationController
			let svc3 = nav3.topViewController as! ActivityPreferencesTableViewController
			svc3.majCat = majCat //Pass the category
			svc3.subCat = subCat
			print(svc3.subCat)
			svc3.personDict = personDict //Pass first name on

**Comment by danieldahan** [comment]
I will need some more information to help you. First, what is the error? Is it this "whose view is not in the window hierarchy!", because that is not 100% clear. Can you paste the error from the console? Thank you!

**Comment by JeremyJF** [comment]
Thanks for the response by email.

The error is “whose view is not in the window hierarchy!” and this occurs when i segue to a a Nav controller in the middle of a Storyboard accessed from a Storyboard Reference 










using:



if (segue.identifier == "ActivityPref") {

			let nav3 = segue.destinationViewController as! UINavigationController
			let svc3 = nav3.topViewController as! ActivityPreferencesTableViewController
			svc3.majCat = majCat //Pass the category
			svc3.subCat = subCat
			print(svc3.subCat)
			svc3.personDict = personDict //Pass first name on

The actual full msg: 2016-05-19 18:03:00.824 LBAactivityDetailsForm[9135:3571385] Warning: Attempt to present <UINavigationController: 0x149f4400> on <LBAactivityDetailsForm.ViewController2: 0x1457ed90> whose view is not in the window hierarchy!

I would be grateful for any help - its got me baffled.

Thanks

Jeremy

**Comment by danieldahan** [comment]
Okay... so it sounds like you are missing a view in the hierarchy. Give me a bit, I will be able to help you. I am caught up in something right now  :)

**Comment by JeremyJF** [comment]
Many thanks

**Comment by JeremyJF** [comment]
This might help

**Comment by JeremyJF** [comment]
Manage to resolve the problem with a work-around using 


	func tableView(tableView: UITableView, willSelectRowAtIndexPath indexPath: NSIndexPath) -> NSIndexPath?{
		tableView.deselectRowAtIndexPath(indexPath, animated: true)
		row =  indexPath.row
		sec = indexPath.section
		print(sec,row)
//to determine the data to pass
		return  indexPath
}
and not calling segue programatically but  segue only from the SB one.

Thanks for the interest - perhaps there is a better way but it seems that tableview in UIViewcontroller has a problem

**Comment by danieldahan** [comment]
Well tableVIew and UIViewController are iOS native elements. We haven't done anything to them. So your issue may be in iOS completely. If you have any other issues, please open a new issue. All the best.

**Comment by JeremyJF** [comment]
Thank you
