### ISSUE TITLE
Interface Builder issue

### ISSUE THREAD

**Issue by RuslanPatyk** [CosmicMind/Material#390]
Using material view and material button as custom classes for views in IB, I am getting warnings "Failed to update auto layout. The agent crashed" and other IB warnings. I did not manage to make demo for this issue, I believe that there is a need in large project with great amount of different storyboards. I can send screenshots to your mail. If it is possbile, it would be great to make an option for the lib whether @IBInspectables or not, because I believe that this options are making IB crash.

**Comment by danieldahan** [comment]
Yes, please send the screenshots to support@cosmicmind.io.

**Comment by danieldahan** [comment]
Hey, as I haven't heard from you. I am going to close this issue.
