### ISSUE TITLE
SideBar Controller doesn't work 

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#398]
I copied the files and I am getting the table view with items 
its o'clock doesn't open up another view

**Comment by danieldahan** [comment]
Would you mind sharing your setup code?

**Comment by chashmeetsingh** [comment]
https://github.com/chashmeetsingh/MaterialApp

**Comment by mohpor** [comment]
@chashmeetsingh I have tested your sample project. 
You are using `sideNavigationController` which is not initialized! in fact, those optional are `nil` when you are calling transition methods on them. 
Please follow the App form examples to see how sideNavigation must be used.
Cheers,
M.

**Comment by danieldahan** [comment]
I think I am missing something. When I looked at your sample app, it was an incomplete copy of the example project. There isn't any code in the AppDelegate launching the application, as well, I don't see any setup in your Main.storyboard. Please try again, following the example project, if the problem still persists, feel free to reopen or create a new issue. Thank you!
