### ISSUE TITLE
TextField(password) marker is not placed correctly with respect to the text.

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#400]
![img_0072](https://cloud.githubusercontent.com/assets/8962264/15557567/a169d4a6-22f1-11e6-9d95-7310f7037d4b.PNG)
![img_0071](https://cloud.githubusercontent.com/assets/8962264/15557569/a234af14-22f1-11e6-935d-0116bf32adf0.PNG)

**Comment by chashmeetsingh** [comment]
please help me fix this https://github.com/chashmeetsingh/Material-Toolbar 
I am getting issues

**Comment by danieldahan** [comment]
I have tested your example app that you shared in the link. It doesn't seem to be setup correctly. You are trying to use NavigationItems in a Toolbar. That won't work. Try following the example project in Storyboards, which shows how to use a Toolbar and Storyboards together.

**Comment by danieldahan** [comment]
This is now fixed in release 1.41.3, and is being release today. I will close this issue when it is released.

**Comment by danieldahan** [comment]
released [1.41.3](https://github.com/CosmicMind/Material/releases/tag/1.41.3)
