### ISSUE TITLE
toolbar has no title member

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#404]
https://github.com/chashmeetsingh/testing.git

**Comment by mohpor** [comment]
Could you elaborate more on the issue please?

**Comment by chashmeetsingh** [comment]
<img width="898" alt="screen shot 2016-05-27 at 7 30 23 pm" src="https://cloud.githubusercontent.com/assets/8962264/15610161/7a776146-2441-11e6-8485-452c4d73c947.png">
@mohpor

**Comment by mohpor** [comment]
What material version are you using? Have you updated to 1.41.3?

**Comment by chashmeetsingh** [comment]
its 1.41.2

**Comment by mohpor** [comment]
could you run a `pod update` and see what happens? Because I can see those properties in `1.41.3`

**Comment by chashmeetsingh** [comment]
thanks! that worked but now another error 
<img width="860" alt="screen shot 2016-05-27 at 7 42 28 pm" src="https://cloud.githubusercontent.com/assets/8962264/15610528/5b207e7a-2443-11e6-98ac-0da9a3a89826.png">

I have updated the repo with the current code 
https://github.com/chashmeetsingh/testing.git

**Comment by mohpor** [comment]
It's a whole another issue. If you don't mind, please close this issue, move to a new issue with a complete description of the circumstances, including how this `prepareToolbar()` is getting called.

Thanks.

**Comment by chashmeetsingh** [comment]
sure

**Comment by mohpor** [comment]
Plus, you can always use Material's [Gitter](https://gitter.im/CosmicMind/Material) channel to ask questions about implementations and unknown issues.

**Comment by chashmeetsingh** [comment]
thanks for the info
