### ISSUE TITLE
add closeMenu() function trigger

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#406]
on clicking the menu button down having many other buttons shouldn't there be a functionality by which if we click somewhere else other than the buttons menu closes

**Comment by ahusseini** [comment]
The method already exists. 

If you're using MenuViewController use `closeMenu(completion: (() -> Void)? = nil)`

**Comment by mohpor** [comment]
I guess what @chashmeetsingh is trying to achieve is something different, like touch outside to dismiss.

**Comment by chashmeetsingh** [comment]
yes exactly @mohpor

**Comment by danieldahan** [comment]
This is solved in [1.41.5](https://github.com/CosmicMind/Material/releases/tag/1.41.5) thank you @mohpor :)
