### ISSUE TITLE
Side Navigation Controller Crashes

### ISSUE THREAD

**Issue by saipnc** [CosmicMind/Material#410]
When we navigate to different controllers from the side menu, randomly it crashes.  Could you, please suggest any fixes we have to make the app live and it is creating a problem? Please refer to the image.

<img width="971" alt="screen shot 2016-05-31 at 2 16 50 pm" src="https://cloud.githubusercontent.com/assets/2713981/15668947/6d6b2332-273b-11e6-8495-6d8292f13c4e.png">

**Comment by mohpor** [comment]
@saipnc what version of Material you are using?

**Comment by saipnc** [comment]
v1.40.1

**Comment by mohpor** [comment]
v1.41.6 is the latest version, and it is a well known issue with older versions I guess. Could you upgrade to the latest version and see if it helps?

**Comment by danieldahan** [comment]
In the version you are using, the reason it crashes is because of the 'unowned' self. In the latest version, all references like that were switched to 'weak'. Please upgrade to the latest, and if the issue persists let us know. Thanks for bringing this to our attention. :)
