### ISSUE TITLE
What is the image size to create custom IconButton?

### ISSUE THREAD

**Issue by aemgtz** [CosmicMind/Material#413]
I have tried to using custom image to create  IconButton.
It seems to produce ugly button. 
![screen shot 2559-06-01 at 4 14 53 pm](https://cloud.githubusercontent.com/assets/276439/15704251/0689a1a0-2814-11e6-862a-cc1aa54369b1.png)
![screen shot 2559-06-01 at 4 14 57 pm](https://cloud.githubusercontent.com/assets/276439/15704252/06b99342-2814-11e6-9856-b192bf72951f.png)

**Comment by aemgtz** [comment]
The red one is what it should be.
The blue on is creating by using IconButton

**Comment by mohpor** [comment]
The image size should not be important. You can update you icon butt's image view to adapt to the button's size:

```swift
iconBtn.imageView?.contentMode = .ScaleAspectFit
```

**Comment by aemgtz** [comment]
![simulator screen shot jun 1 2559 be 4 44 03 pm](https://cloud.githubusercontent.com/assets/276439/15705141/2a946374-2818-11e6-8368-aac7065f22ff.png)

Thanks man

But I think my image is too large so, I need to resize the image for using  IconButton

**Comment by mohpor** [comment]
that would be wise.

**Comment by aemgtz** [comment]
Resizing image isn't a nice idea because my project has more than a hundred images.

**Comment by aemgtz** [comment]
If creating IconButton programmatically ,it seem to be a perfect size.
If creating from Interface builder, The size will be wrong.
<img width="38" alt="screen shot 2559-06-02 at 4 46 05 pm" src="https://cloud.githubusercontent.com/assets/276439/15740962/8a1bc3cc-28e1-11e6-8642-6c1ec8a2680b.png">

**Comment by aemgtz** [comment]
After 
`contentMode = .ScaleAspectFit`
<img width="68" alt="screen shot 2559-06-02 at 4 51 59 pm" src="https://cloud.githubusercontent.com/assets/276439/15741117/5ab3b4cc-28e2-11e6-9c7e-e6c9e05c3530.png">

**Comment by mohpor** [comment]
dear @aemgtz, from what I see, your button's insets are meddling with the size of your icons. You can change the content inset and the contentMode (`.ScaleAspectFill` for example) to see if you can improve the situation.

**Comment by danieldahan** [comment]
@aemgtz well essentially all icons passed to IconButton are custom. The button has no idea where the image comes from. As for the sizing, we use 24, 48, 72 for @1x, @2x, and @3x.

**Comment by danieldahan** [comment]
I am going to close this issue for now. I posted the sizes we use for buttons, and that should get you in the right direction. If you need any further help, please reopen or visit the [Gitter](https://gitter.im/CosmicMind/Material) channel. All the best!
