### ISSUE TITLE
Need Google Material Design Bottom Sheets.

### ISSUE THREAD

**Issue by saipnc** [CosmicMind/Material#414]
Hi, 

We appreciate the efforts put in to develop this library, it would be great if you guys include latest google's bottom sheets.

Thanks :)

**Comment by danieldahan** [comment]
Yeah, I will leave this up as I work on it.

**Comment by akhilm3** [comment]
@saipnc  @danieldahan  Suggestion for this idea, why not just subclass UIAlertSheet and add PulseViews on top of it?

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.
