### ISSUE TITLE
Snackbar

### ISSUE THREAD

**Issue by akhilm3** [CosmicMind/Material#415]
Thank you so much for working on this framework. I would love the addition of a snackbar. I even have an idea of how to make it. 
1) make a black bar/ view 
2) animate it popping up from the bottom 
3) add buttons to the view
4) add materialpulse view everywhere

**Comment by danieldahan** [comment]
Cool :) There is an example project that called ControlView that mimics the Snackbar. I think that a Snackbar component would be very handy. So we will keep this up as I make it.

**Comment by akhilm3** [comment]
@danieldahan  I added some more idea on how to tackle this in my first comment, please, if you can, check it out.

**Comment by danieldahan** [comment]
@akhilm3 Yes, your suggestions are on track. The BarView which subclasses the ControlView offers all that you suggested with the mathematics to align everything built in :) I appreciate the ideas of how to approach the challenge.

**Comment by akhilm3** [comment]
I also would suggest that the buttons on the snackbar default to the global tint of the application in order to maintain UI consistency

**Comment by danieldahan** [comment]
I need to add a feature that allows global setup like you described. Then Material can offer themes.

**Comment by akhilm3** [comment]
@danieldahan Do you know when the snackbar will be released?

**Comment by danieldahan** [comment]
Not long. We are tackling a big release for today. So, once that is done, it is all feature requests and documentation for me

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.

**Comment by danieldahan** [comment]
This is in the `development` branch now. For help in using it, please go to the [Gitter](https://gitter.im/CosmicMind/Material) page. I am posting documentation shortly. Thank you!
