### ISSUE TITLE
dyld: Library not loaded: @rpath/Material.framework/Material

### ISSUE THREAD

**Issue by tianqiujie** [CosmicMind/Material#416]
dyld: Library not loaded: @rpath/Material.framework/Material
  Referenced from: /Users/tian/Library/Developer/CoreSimulator/Devices/8C5F2D2E-8312-45B2-8678-4251AB92EEBA/data/Containers/Bundle/Application/1D6E6247-B4C1-469D-B441-B56F2925A3DC/xxx.app/xxx
  Reason: image not found

**Comment by danieldahan** [comment]
Are you trying to load a sample project?

**Comment by akhilm3** [comment]
I also got this problem when I tried in console 
`pod try 'Material'` 
and I ran the project

**Comment by danieldahan** [comment]
So if you are adding the framework to the example projects, you need to build and embed the framework. This should give you help, [Installation Tutorial](https://github.com/CosmicMind/Material/wiki). When you use CocoaPods, you will need the pod workspace open, otherwise it wont know where to find the framework.

**Comment by akhilm3** [comment]
`pod try` generates the sample project in a temporary directory. Maybe this is the cause of the problem?

**Comment by danieldahan** [comment]
It could be. I don't use CocoaPods, so I am not sure. Generally what you need to do is:

1. Open the Material workspace found in the Examples directory.
2. Build the framework for iOS with the Generic Devices set, not simulator. 
3. Go to the sample project you want to test. 
4. Embed Material in the Embed binaries tab. 
5. Run the sample project. 

That should work.

**Comment by danieldahan** [comment]
You should be able to find more help here, https://github.com/CosmicMind/Material/wiki/Installation.

**Comment by danieldahan** [comment]
You should be able to solve the issue, if has not been already solved with the examples I directed you too. If you have any further issues, please reopen or create a new issue. Thanks!
