### ISSUE TITLE
Make pulseLayers accessible internally on MaterialPulseView

### ISSUE THREAD

**Issue by JackoPlane** [CosmicMind/Material#417]
I propose a change from 

`public private(set) lazy var pulseLayers: Array<CAShapeLayer> = Array<CAShapeLayer>()`

to `public internal(set) lazy var pulseLayers: Array<CAShapeLayer> = Array<CAShapeLayer>()`

Our use case is subclassing `MaterialPulseView` and overriding `func touchesEnded(touches: Set<UITouch>, withEvent event: UIEvent?)` In an event of not wanting to call super on the touch event it's currently impossible to complete the animation without calling super.

**Comment by danieldahan** [comment]
yes that could work. Give me a sec, let me see if I can do it now.

**Comment by danieldahan** [comment]
Question, as we are looking to make this change. Why do you need the setter to be internal? Since the layers are essentially public? Are you trying to add and remove layers?

**Comment by JackoPlane** [comment]
Here's a better example:

```
	internal override func touchesEnded(touches: Set<UITouch>, withEvent event: UIEvent?)
	{
		// We don't call super since we want to handle the tap "manually" upstream
		// super.touchesEnded(touches, withEvent: event)

		// Contract the animation (normally this would be handled by super)
		MaterialAnimation.pulseContractAnimation(layer, visualLayer: visualLayer, pulseColor: pulseColor, pulseLayers: &pulseLayers, pulseAnimation: pulseAnimation)
}
```

**Comment by danieldahan** [comment]
Okay, I will be able to help you in the morning.

**Comment by danieldahan** [comment]
So we have been mulling this over and we are hesitant to make the change you are looking for. We don't get why you would want to suppress the touch event. Why not use a Tap Gesture for this, and leave the touches completely alone? The other option, and probably the best for you, is to subclass MaterialView and copy the minimal code used in the MaterialPulseView, to achieve what you want. You could literally copy and paste the code and omit what you don't want.

**Comment by danieldahan** [comment]
I am going to close this issue for now. If you would like to share some code and describe what you are trying to accomplish, we are happy to help. The [Gitter](https://gitter.im/CosmicMind/Material) channel is great for that. Thanks for sending this out way.
