### ISSUE TITLE
Material Design Segemented Control

### ISSUE THREAD

**Issue by akhilm3** [CosmicMind/Material#425]
Basically a square segmented control with material pulse layers and maybe a little indicator below it.

**Comment by nhnam** [comment]
Vote for it :)

**Comment by danieldahan** [comment]
hello :) are you talking about [this](https://material.google.com/components/buttons.html#buttons-dropdown-buttons) look to the bottom where it says toggle buttons. If not, can you show us. Thank you!

**Comment by nhnam** [comment]
Yeah, we can use it instead. Thanks Daniel !

**Comment by akhilm3** [comment]
@danieldahan  You are indeed correct.

**Comment by mohpor** [comment]
@danieldahan, @akhilm3  Can we safely close this issue then?

**Comment by akhilm3** [comment]
@mohpor We can add a [Feature Request] tag to this and then leave it open

**Comment by danieldahan** [comment]
The tag has been added, and yes, I would prefer to leave this open so we can discuss further on this thread.

**Comment by iNoles** [comment]
I would use this as top tab bar like Android's TabLayout.

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.
