### ISSUE TITLE
Material Not Compiling

### ISSUE THREAD

**Issue by philipposslicher** [CosmicMind/Material#427]
No matter what I try, whenever I try to compile any app with material in it, I always get 66 errors in xcode pertaining to various Material files. I am not sure why this is happening. All these errors have to do with 'Expected , separator' or 'Expected expression in list of expressions'
Using Xcode Version 7.3 beta 3 (7D141l)

**Comment by danieldahan** [comment]
Well I can't comment on beta xcode software, but what I can say, is try and follow these steps: https://github.com/CosmicMind/Material/wiki

**Comment by philipposslicher** [comment]
I have tried doing those steps but same thing. This isn't an xcode issue I would believe as it has to do with the compiling stage, and the actual Swift code seems to be wrong, according to Xcode. Not sure though. Downloading non-beta as we speak just to make sure, even though I've been a forever beta user ;)

**Comment by danieldahan** [comment]
Possibly, but that would be weird as I released an app two days ago, and am compiling and running the bleeding edge of Material. If you don't mind letting us know the result, that would be great! Thanks.

**Comment by philipposslicher** [comment]
Will do! I am assuming that you are running 7.3.1 then. Waiting for those 3.8gb to download now....

**Comment by danieldahan** [comment]
Yes I am. I stopped using Apple's beta software. I can't provide support to the mass on Xcode betas.

**Comment by philipposslicher** [comment]
Makes sense, I don't develop stuff FOR xcode so I tend to use the beta anyways.

**Comment by danieldahan** [comment]
I don't either.. I develop with xcode.

**Comment by danieldahan** [comment]
Did this manage to work for you?

**Comment by danieldahan** [comment]
As I haven't heard from you, I am going to close this issue. If you have any further questions, please send them our way. Thank you!

**Comment by philipposslicher** [comment]
Sorry, time zone differences, went to sleep, had to redownload xcode. It finally works now.

**Comment by danieldahan** [comment]
Wonderful and no worries, so long as you are up and running :)
