### ISSUE TITLE
Help wanted with use of Material

### ISSUE THREAD

**Issue by philipposslicher** [CosmicMind/Material#429]
So now that Material compiles, and I have used it a little, I am noticing that I am not really sure how to use it. I've used the wiki and the examples but they don't really seem to work. Could someone explain, lets say how to make a toolbar with a burger button, or something like that, as I'm not really sure how to do this. I have also noticed that documentation is a little bit lacking, and could help if necessary.

**Comment by danieldahan** [comment]
Yes documentation is being worked on this month. Have you had a chance to take a look at these example projects: https://github.com/CosmicMind/Material/tree/master/Examples.

**Comment by danieldahan** [comment]
Also, let's move this to [Gitter](https://gitter.im/CosmicMind/Material).

**Comment by philipposslicher** [comment]
First of all. I really love how your reply so fast, this is almost unheard of. THANK YOU.
As I said, I have tried the Examples but none of them really seem to work. They just have projects with empty views in them for me.

**Comment by danieldahan** [comment]
No worries, for our discussion though, the channel is best. As this will create noise for watchers.
