### ISSUE TITLE
Material Design Dialogs 

### ISSUE THREAD

**Issue by akhilm3** [CosmicMind/Material#433]
In accordance to issue #414 , I suppose that a brand new 'MaterialAlertController' be made which will create a new  alert dialog as well as a new alert sheet. 

A suggestion would be an alert controller that displays a cardView (without pulses) and bottom buttons (with pulses)

@danieldahan If you can, i would love this with the next release (if possible)

**Comment by danieldahan** [comment]
The next release is about updates to Layout and hiding the BottomNavigationController. This will be added soon though :) It has been asked for many times and finally I am getting time to do it.

**Comment by lukka5** [comment]
Any news about this?

**Comment by danieldahan** [comment]
Still in the queue.

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.
