### ISSUE TITLE
No Such module error

### ISSUE THREAD

**Issue by satyamub** [CosmicMind/Material#434]
Hi All,

I am trying to see the implemention and not able to see this because of  "no such module" error.

I have tried the steps given in Issue https://github.com/CosmicMind/Material/issues/122 but with no help.

Please help me out. I am not creating any new project, just using the example Material

**Comment by mohpor** [comment]
@satyamub 
I hav

**Comment by chashmeetsingh** [comment]
Steps:
- Clone the repo
- Open Examples/Material.xcworkspace
- Select the app u want to run
- Add Material.framework in embedded binaries for that project
- Hit Run

**Comment by chashmeetsingh** [comment]
@satyamub did it work?

**Comment by satyamub** [comment]
@chashmeetsingh  No sir jee... did not work

**Comment by chashmeetsingh** [comment]
whats the error?

**Comment by danieldahan** [comment]
Hi, sorry for the delay, please try [1.42.0](https://github.com/CosmicMind/Material/releases/tag/1.42.0) for a fix. If the issue persists, please reopen or create a new issue. Thank you!
