### ISSUE TITLE
Toast Messages

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#435]
Toast messages with short and long duration as in android

**Comment by akhilm3** [comment]
@chashmeetsingh Let us also add the ability to change the color of the toast with a `color:UIColor` specifier. 
P.S @danieldahan  This could also be apart of the MaterialAlert Controller I have been talking about for a while

**Comment by chashmeetsingh** [comment]
hmm colours will be nice @akhilm3

**Comment by chashmeetsingh** [comment]
I am thinking to implement this myself and send a PR :)

**Comment by danieldahan** [comment]
Sounds wonderful, we are here to help :)

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.
