### ISSUE TITLE
ToolBar leftControls

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#438]
is there a way to vertically center the leffControls/rightControls buttons as to make them appear in the center and not towards the bottom of the ToolBar?

**Comment by danieldahan** [comment]
Sorry, I don't fully get your question. You are asking about vertically aligning the buttons in the center position, and not be towards the bottom of the Toolbar? Do you mind sharing a drawing of what you are looking for.

**Comment by GreyEcologist** [comment]
I'd like the hamburger and the search FlatButtons to align with the logo in the center of the Toolbar below:

![screen shot 2016-06-14 at 12 12 28 am](https://cloud.githubusercontent.com/assets/1141963/16034123/d11a8ec0-31c4-11e6-9a52-724afda40c2d.png)

**Comment by danieldahan** [comment]
yes, you can make that happen. Are you using a ToolbarController, or Toolbar?

**Comment by danieldahan** [comment]
Tomorrow, I will make an adjustment for you that will make this much easier. I am about to sign off for the night.

**Comment by GreyEcologist** [comment]
Thanks, I appreciate that. FYI, I'm using a Toolbar as below:
```
        let menuButton: FlatButton = FlatButton()
        menuButton.pulseColor = MaterialColor.white
        menuButton.pulseAnimation = .None
        menuButton.setImage(R.image.ic_menu_white()!, forState: .Normal)
        menuButton.setImage(R.image.ic_menu_white()!, forState: .Highlighted)
        
        let rightButton: FlatButton = FlatButton()
        rightButton.pulseColor = MaterialColor.white
        rightButton.pulseAnimation = .None
        rightButton.setImage(R.image.ic_search_white()!, forState: .Normal)
        rightButton.setImage(R.image.ic_search_white()!, forState: .Highlighted)
        
        let navBar: Toolbar = Toolbar()
        navBar.frame = Constants.kNavigationBarRect
        navBar.leftControls = [menuButton]
        navBar.rightControls = [rightButton]
```

**Comment by danieldahan** [comment]
Where are you adding the image?

**Comment by GreyEcologist** [comment]
the setImage() methods contain the image, the R.image thing is just a library to keep track of images. I saw the change in alignment happening when I moved to 1.41.8 from 1.41.2.

**Comment by GreyEcologist** [comment]
Hey Dan, I found a way to set those elements. All good here!

```
navBar.grid.contentInset.bottom = 20
```

**Comment by danieldahan** [comment]
Sweet! I am going to document Grid in the next few days. That should help you, as Grid is the layout tool used in most of Material. Have you checkout this out [Layout](http://www.cosmicmind.io/material/layout), which is a really easy AutoLayout tool. All the best!
