### ISSUE TITLE
Transition Issue with NavigationDrawerController

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#439]
Hey, I'm running into a new issue since updating to 1.42.0 where my custom transition turns the detailViewController to black.

I have SideNavigationController/NavigationDrawerController set in my AppDelegate:

```
self.window!.rootViewController = NavigationDrawerController(rootViewController: MasterViewController(), leftViewController: SettingsViewController())
```

In my MasterViewController I call presentViewController to move to DetailViewController:
```
        let detailVC = DetailViewController()
        detailVC.transitioningDelegate = self.transitionManager
        self.transitionManager.setIndexedCell(index: indexPath.row)
        self.presentViewController(detailVC, animated: true, completion: nil)
```

with the custom transition below: 

```
final class TransitionManager: NSObject, UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate
```

With the changes of 1.42.0 the DetailViewController changes to black during the transition, which kills the smooth transition effect. I traced the issue in the NavigationDrawerController.prepareContentViewController() at line 883, commenting the line below fixes the issue:

```
contentViewController.view.backgroundColor = MaterialColor.black
```

That line was actually in previous version but was attached to a local view controller, not a global one. So I'm not sure why it didn't behave similarly in the previous versions, but if the transition view controller is to be transparent (line 341)  then it shouldn't be black to begin with, right? If so, could you guys remove that line?

**Comment by danieldahan** [comment]
Its black actually for a different purpose, and could be any color really. I could default it to white, I think that would be better. There needs to be a color though, because the statusBar hides in a different way now. Basically it updates window levels and goes behind the contentViewController. The previous statusBar hiding had too many cases where it wouldn't work if not setup in a specific configuration. I'll keep this issue up and write my findings.

**Comment by GreyEcologist** [comment]
Ok, that makes sense. Then there's no issue, I just set up the contentViewController as such and that fixes it for me:

```
        let nav: NavigationDrawerController = NavigationDrawerController(rootViewController: MasterViewController(), leftViewController: SettingsViewController())
        nav.contentViewController.view.backgroundColor = UIColor.clearColor()
        self.window!.rootViewController = nav
```

Thanks for the quick replies!

**Comment by danieldahan** [comment]
Sweet, then I shall close this issue. Thank you!
