### ISSUE TITLE
Library not loaded: @rpath/libswiftAVFoundation.dylib

### ISSUE THREAD

**Issue by Sorix** [CosmicMind/Material#441]
Trying to load any example app ends with crash (opened Examples/Material.xcworkspace). Xcode 7.3.1, clean performed.

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/sorix/Library/Developer/Xcode/DerivedData/Material-gjjlwkhvhpugkhdapjvdonjdrqog/Build/Products/Debug-iphonesimulator/Material.framework/Material
  Reason: image not found
(lldb) 
```

**Comment by Sorix** [comment]
Issue resolved, I haven’t followed: https://github.com/CosmicMind/Material/wiki/Installation

**Comment by chashmeetsingh** [comment]
No this is an issue I have confirmed this you were are using an older version that's why u can't find it anymore @danieldahan u need to look into this

**Comment by danieldahan** [comment]
Hey, Clear your project and clean your derived data. Thank you will solve this.
