### ISSUE TITLE
pods products io.cosmicmind.material.icons.bundle is empty

### ISSUE THREAD

**Issue by kaich** [CosmicMind/Material#442]
When I update material in my project, All icons don't load. Is it a bug in new version ?

**Comment by danieldahan** [comment]
What version of cocoapods are you running? If it is the latest, try cleaning your build folder and clearing derived data. We found that cocoapods had a caching issue with the latest 1.0.

**Comment by kaich** [comment]
@danieldahan The version of pod is 0.39.0. I clean all and delete derived data , but it is still empty.
![2016-06-17 9 26 25](https://cloud.githubusercontent.com/assets/5013020/16138191/a52fabd2-346d-11e6-9243-d5aa3e29821c.png)

I found the old material  don't use `Assets.xcassets`. It works fine. Is there any suggestion ?

**Comment by danieldahan** [comment]
You should update to the latest cocoapods and then clean your build folder and delete your derived data. Material supports the latest from CocoaPods. To update, you may be able to do it as easily as:

```
sudo gem uninstall cocoapods
sudo gem install cocoapods
```

**Comment by danieldahan** [comment]
I am closing this issue, if you find it continues to persist, please reopen or create a new issue. Also, joining [Gitter](https://gitter.im/CosmicMind/Material) is an easy way to get help :)
