### ISSUE TITLE
Allow configure SideNavigationController from StoryBoard

### ISSUE THREAD

**Issue by urizev** [CosmicMind/Material#443]
Hi everyone,

I would like to add a SideNavigationController just using the StoryBoard. I have some modifications made on SideNavigationController.swift code.

```swift
public override func awakeFromNib() {
    super.awakeFromNib()
    self.rootViewController = self.storyboard?.instantiateViewControllerWithIdentifier("Main")
    self.leftViewController = self.storyboard?.instantiateViewControllerWithIdentifier("Left")
    prepareView()
}
```
I works but I'm afraid it is not the best approach.

I have not much knowledge at this point so that I didn't dare to make a pull request. Maybe it would be better if the viewcontrollers are specified with segues.

Thanks.

**Comment by danieldahan** [comment]
This is a specific need, especially with the naming you have chosen, Main and Left. So subclassing it and providing customizations is best, and the approach we hope people would take in these kind of situations. So is it working for you then?

**Comment by danieldahan** [comment]
I am closing this issue, if you would like, please send a project to support@cosmicmind.io and join the [Gitter](https://gitter.im/CosmicMind/Material) channel to discuss project specific help. All the best :)
