### ISSUE TITLE
Replacing rootviewController of drawer 

### ISSUE THREAD

**Issue by levuhai** [CosmicMind/Material#444]
After updating to the latest code, I use this code to change the top viewcontroller of drawerController when clicking to a row in leftView

`if let v: NavigationController = navigationDrawerController?.rootViewController as? NavigationController {
            v.pushViewController(main, animated: true)
            navigationDrawerController?.closeLeftView()
 }`

However, backbutton always appears. How can I remove it? Can you suggest any solution? 
Each row in left menu is linked to different sections, so putting backbutton there does not make sense. Previously, I used this to fulfill the requirement

        // Show new controller
        let nav = AppNavigation(rootViewController: main)
    
        sideNavigationController?.transitionFromRootViewController (
            nav,
            duration: 1,
            options: .TransitionNone,
            animations: nil,
            completion: {
                [weak self] _ in
                self?.sideNavigationController?.closeLeftView()
            })
        }

Thank you so much for your great work. I really appreciate your work and I want to donate, but could not find any button on your site. Please let me know how I can donate

**Comment by danieldahan** [comment]
The fix should be in [1.42.2](https://github.com/CosmicMind/Material/releases/tag/1.42.2). Thank you for bringing this to our attention. All the best :)

As for donations. I never really thought of that, so don't feel any pressure. If you did donate, I'd be happy with a cup of coffee :) The only way I can accept money at the current time is through paypal, with email: dahan.daniel@me.com.
