### ISSUE TITLE
Toolbar alignment issue when detailLabel is empty

### ISSUE THREAD

**Issue by ahusseini** [CosmicMind/Material#445]
Hello Daniel, 

When setting the toolbar's detail attribute to an empty string it still has a height of 10pt, so the title is not vertically in alignment with the toolbar's buttons.

![toolbar1](https://cloud.githubusercontent.com/assets/6011755/16133094/201ba6a0-33e4-11e6-9991-b051607b7d54.png)

**Comment by danieldahan** [comment]
set the detail value to nil, an empty string is still considered a string. This may be unintuitive. So it should consider that case as well.

**Comment by ahusseini** [comment]
that worked, thank you!

**Comment by danieldahan** [comment]
The empty string case will be handled like having a nil value. I will close this issue when it is released later today. Thank you!

**Comment by danieldahan** [comment]
The fix should be in [1.42.2](https://github.com/CosmicMind/Material/releases/tag/1.42.2). Thank you for bringing this to our attention. All the best :)
