### ISSUE TITLE
The example code is wrong!

### ISSUE THREAD

**Issue by tianqiujie** [CosmicMind/Material#447]
int the ToolBar project, it should be 
view.layout(containerView).edges(top: 0, left: 0, bottom: view.frame.size.height - toolbar.height, right: 0)

**Comment by danieldahan** [comment]
I don't see how the sample is wrong. The sample is meant to show you how you can put a Toolbar in a container view of any size and it will fit. If you want to see another example, or feel that this is incorrect. Please reopen or create a new issue. Thank you!
