### ISSUE TITLE
1.42.2 Regression: FabButtons are no longer circular when added via storyboard

### ISSUE THREAD

**Issue by JRG-Developer** [CosmicMind/Material#450]
On commit with tag `1.42.2`, `FabButton`s are no longer circular when added via storyboard.

I noticed the commit for this tag removes the call to `prepareView()` from `init?(coder:)` initializer on `MaterialButton`, which appears to the cause of this issue.

I wanted to confirm: this isn't intentional for some reason, right?

**Comment by danieldahan** [comment]
That is a regression. I will post a fix for it now with the release I am doing.

**Comment by JRG-Developer** [comment]
Cool, thanks!

**Comment by danieldahan** [comment]
Thank you and the release is available [1.42.3](https://github.com/CosmicMind/Material/releases/tag/1.42.3). If the issue persists, please reopen or create a new issue. Thank you!
