### ISSUE TITLE
xCode 8 Swift 2.3 support timeline

### ISSUE THREAD

**Issue by wm-j-ray** [CosmicMind/Material#451]
Could you tell me when this might be available?

**Comment by danieldahan** [comment]
I will be working on it this weekend, with aims to update the v2.x.x branch for Monday, latest Tuesday.

**Comment by wm-j-ray** [comment]
Yay!!

**Comment by danieldahan** [comment]
:) I am going to leave this issue up until I am done.

**Comment by danieldahan** [comment]
Hey! I am finishing some iCloud integration with Graph. Once I am done, I can complete this update. Thanks!

**Comment by danieldahan** [comment]
Starting this tomorrow. Very sorry for any delays.

**Comment by danieldahan** [comment]
So this is in the development branch. I had made some updates along the way. Please consult the [wiki](https://github.com/CosmicMind/Material/wiki/Changelog). I will be making many more updates to get ready for Material 2. So please, if you have any questions, feel free to ask on [Gitter](https://gitter.im/CosmicMind/Material).

**Comment by akashlazy** [comment]
i want to use swift 2.3 in xcode 8 
i did legacy mode yes but still more issues
