### ISSUE TITLE
Left and RightViewController are nil

### ISSUE THREAD

**Issue by adhiravishankar** [CosmicMind/Material#452]
When preparing the view for the second time, the side never gets re-enabled like its supposed to. 

Take for example:

if nil == leftViewController {
			enabledLeftView = false
			enabledLeftPanGesture = false
			enabledLeftTapGesture = false
		} else if nil == leftView {
			leftViewWidth = .iPhone == MaterialDevice.type ? 280 : 320
			leftView = MaterialView()
			leftView!.frame = CGRectMake(0, 0, leftViewWidth, view.frame.height)
			leftView!.backgroundColor = MaterialColor.clear
			view.addSubview(leftView!)
			
			leftView!.hidden = true
			leftView!.position.x = -leftViewWidth / 2
			leftView!.zPosition = 2000
			prepareLeftViewController()
		}

The init function goes through this function twice when doing the stacktrace, but it never re-enables the booleans enabledLeftView, enabledLeftPanGesture, and leftTapGesture

**Comment by danieldahan** [comment]
Yes, I noticed a race condition in certain situations with the refactor. I am going to look into it now.

**Comment by danieldahan** [comment]
This should fix the issue [1.42.4](https://github.com/CosmicMind/Material/releases/tag/1.42.4). Let me know :) Thanks for bringing this to our attention.
