### ISSUE TITLE
CaptureView microphone Permission

### ISSUE THREAD

**Issue by AhmettKeskin** [CosmicMind/Material#454]
Hey Daniel,

I'm using captureView for taking photos and its ok to ask camera permission. But microfon permission also comes with it. I digged library but couldn't find any permission request for camera or microfon. I added requesting permissions but yours comes automaticly. Is there any chance binding permissions to boolean or a different solution ? Because i do not want to microfon permission from my users although i didn't use recording

**Comment by danieldahan** [comment]
Hey! Yes, I am finishing up iCloud support in Graph, and then will be able to look into this. Generally, I am rewriting the entire CaptureView library to be more robust. I think this is a good starting point. Thank you!

**Comment by danieldahan** [comment]
Hey! I will be looking at this in the morning. Sorry for any delays. Thank you!

**Comment by danieldahan** [comment]
Hey! We have taken note of this, and will prepare for release with Material 2.
