### ISSUE TITLE
Problem use CardViews

### ISSUE THREAD

**Issue by ggomez1728** [CosmicMind/Material#455]
when run the example have error

        view.layout(cardView).top(100).left(20).right(20)
say UIView has not member layout

please help me

**Comment by danieldahan** [comment]
How have you included the Material framework ?

**Comment by ggomez1728** [comment]
I'm noob in iOS and use pods. installed pack in my new proyect in Podfile include and install pod

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Material', '~> 1.0'
```

but when copy the example TableCardExample and buld proyect, this give me error in  line

`        view.layout(cardView).edges(left: 10, right: 10, top: 100, bottom: 100)
` 
compiler say: Value of type 'UIView' has not member 'layout'

Please help me 
:(
I like your job..

**Comment by danieldahan** [comment]
Did you place the `import Material` statement at the top of the file. Also, checkout the Examples projects.

**Comment by ggomez1728** [comment]
Yes i did, I ran  some examples but  this example has error :(

**Comment by danieldahan** [comment]
Which example? The one in your comments, or a certain project? Basically, I am looking to reproduce the issue. Can you send an example project with the issue to support@cosmicmind.io?

**Comment by ggomez1728** [comment]
I did send you the mail the project

**Comment by danieldahan** [comment]
Cool, I will look at it :) Thank you! You should hear from me very soon.

**Comment by danieldahan** [comment]
So the issue is: the version of Material that you are using is not up to date. Make sure you are running this version [1.42.6](https://github.com/CosmicMind/Material/releases/tag/1.42.6). If you continue to face issues, or need any help, please reopen or create a new issue. Thank you!
