### ISSUE TITLE
Impossible disabling swipe gestures recognizers. (aka removeGestures method is PRIVATE)

### ISSUE THREAD

**Issue by TNikolai** [CosmicMind/Material#458]
The problem caused by enabled gesture recognizers from sideNavigation, I pushed new one viewController on which i have priceRange when i want swipe I cant because gestures was catched by Sidenavigation.

I resolved this on local version setting two methods from private to public 

	 public func removeGestures() {
		if let v: UIPanGestureRecognizer = panGesture {
			view.removeGestureRecognizer(v)
			panGesture = nil
		}
		if let v: UITapGestureRecognizer = tapGesture {
			view.removeGestureRecognizer(v)
			tapGesture = nil
		}
	}

public func prepareGestures() {
		if nil == panGesture {
			panGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePanGesture))
			panGesture!.delegate = self
			view.addGestureRecognizer(panGesture!)
		}
		
		if nil == tapGesture {
			tapGesture = UITapGestureRecognizer(target: self, action: #selector(handleTapGesture))
			tapGesture!.delegate = self
			tapGesture!.cancelsTouchesInView = false
			view.addGestureRecognizer(tapGesture!)
		}
	}

**Comment by danieldahan** [comment]
If you are using the latest version. There are enable properties you can set. 

For example

```swift
enabledLeftPanGesture = false
```

and so forth. Give those a try, and let me know how it goes. Thank you!

**Comment by TNikolai** [comment]
I use version 1.39 and in this version i have not this property : navigationDrawerController.
.

**Comment by danieldahan** [comment]
Yes currently Material is at version 1.42.7. I believe I added the enable handler in 1.40.*. Personally I would update to the latest. So many fixes have been made.

**Comment by danieldahan** [comment]
The NavigationDrawerController is the new name for the SideNavigationController.

**Comment by TNikolai** [comment]
Mhm now i installed new pod version and i see enabledLeftPanGesture.

**Comment by TNikolai** [comment]
So it solved issue! thx.

**Comment by danieldahan** [comment]
:) awesome! Thank you

**Comment by TNikolai** [comment]
Hi danieldahan, my problem was solved particulary, i saw very strange bug in my app when i download app at first launch bug appears, if i press homeButton and again open app leftPanRecognizer not triggers. In both casses i verified code called : 
unwrappedSideNavigationController.enabledLeftPanGesture = enabled
        unwrappedSideNavigationController.enabledLeftTapGesture = enabled

**Comment by danieldahan** [comment]
If you have that code in the viewDidLoad it won't fire because it is not a child of the NavDrawer. Put it in the viewWillAppear or viewDidAppear method. Or possibly you should share your setup code for that area.

**Comment by TNikolai** [comment]
override func viewDidDisappear(animated: Bool) {
        super.viewDidDisappear(animated)
        LeftMenuWireFrame.enableLeftSideMenu(false)
    }

**Comment by TNikolai** [comment]
class func enableLeftSideMenu(value: Bool) {
        if let appDelegate = UIApplication.sharedApplication().delegate as? AppDelegate {
            appDelegate.appFlow.homeModule.enableLeftSideMenu(value)
        }
    }

   func enableLeftSideMenu(enabled: Bool) {
        if let unwrappedSideNavigationController = sideNavigationController  {
            unwrappedSideNavigationController.enabledLeftPanGesture = enabled
            unwrappedSideNavigationController.enabledLeftTapGesture = enabled
        }
    }

**Comment by TNikolai** [comment]
i call this method in viewDidDisapear and i verified in debuger it all time entered in all if's.

**Comment by danieldahan** [comment]
I need to see the setup code. How are you adding the view controllers to the NavigationDrawer, also, what are you enabling and disabling the panning for, could the other parts using pan be causing an issue. Also as a tip, you can simplify these lines

```swift
unwrappedSideNavigationController.enabledLeftPanGesture = enabled
unwrappedSideNavigationController.enabledLeftTapGesture = enabled
```

to 

```swift
unwrappedSideNavigationController.enabledLeftView = enabled
```

**Comment by TNikolai** [comment]
I verified and in my initializatiin code i have initializing SideNavigation(root: NavigationController(homeVc), leftMenuControkker, nil). I think problem in initializing root like navigation controller.

**Comment by danieldahan** [comment]
Yes, you could put in the viewWillAppear a disable or enable call.

There is a helper optional property `navigationDrawerController?.enableLeftGesture`  that you can use in any child view controller. This includes deep hierarchal view controllers.

**Comment by TNikolai** [comment]
pod 'Material', '~> 1.41' And i have only SideNavigationController class, so i have not controller or property  named : "navigationDrawerController".

**Comment by chashmeetsingh** [comment]
@TNikolai update the pod to the latest version!

**Comment by TNikolai** [comment]
My current version  Using Material (1.41.1)
pod 'Material', '~> 1.4'
which version i need to use ?

**Comment by chashmeetsingh** [comment]
1.42.7

**Comment by TNikolai** [comment]
So i updated pods and all works fine, thx a lot.
