### ISSUE TITLE
Captureview Toolbar missing

### ISSUE THREAD

**Issue by despisedIcon** [CosmicMind/Material#460]
In the example project when I run the CaptureView scheme the top toolbar buttons appear to be missing. This was working on previous versions. I recently updated pods and am using 1.42.7 in a project I'm working on and this issue is present.

![screen shot 2016-07-04 at 2 20 13 pm](https://cloud.githubusercontent.com/assets/7425648/16550779/8c899e98-41f2-11e6-889d-9b8496c3da45.png)

**Comment by danieldahan** [comment]
Hey! I am signing off for now, but will check tomorrow morning for you. Thank you!

**Comment by danieldahan** [comment]
Sorry for any delays. I will look at this in the morning. Thank you!

**Comment by danieldahan** [comment]
Hey! I haven't had a chance yet to look at this. Still working out kinks on iCloud.

**Comment by phlippieb** [comment]
I got it to work using AutoLayout. Probably the toolbar isn't being set up with constraints.

**Comment by danieldahan** [comment]
Excellent. I am sorry I didn't respond to this earlier. I am focusing on Material 2 and all that will be released shortly. In Material 2 there is a new CaptureController which will really help with the setup of the camera. I will close this issue for now. Thanks again!
