### ISSUE TITLE
StatusBar Missing when using a UIDocumentInteractionController with a custom NavigationController

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#462]
<img width="459" alt="2016-07-11 10 01 19" src="https://cloud.githubusercontent.com/assets/17197816/16718049/7358ad9a-474e-11e6-8aa6-29535bec1853.png">
```
func documentInteractionControllerViewControllerForPreview(controller: UIDocumentInteractionController) -> UIViewController{
        if let topController = UIApplication.topViewController(){
           return ((topController as! NavigationDrawerController).rootViewController as! AppNavigationController)
        }
        return self
}
```
I am currently using the latest vesion.

**Comment by danieldahan** [comment]
Do you mind sending me an example project so I can reproduce this? Thank you! Please send to support@cosmicmind.io

**Comment by HowardCsie** [comment]
Thanks.
I began to work just now :((
I will make a sample after work :))

**Comment by danieldahan** [comment]
No worries :)

**Comment by danieldahan** [comment]
Hey, I am going to close this for now. When you get a chance to make a sample, please send it to me, and I will take a look. Thank you!
