### ISSUE TITLE
Include password TextField behaviour that only displays plain text while the eye button is pressed down

### ISSUE THREAD

**Issue by balazsgerlei** [CosmicMind/Material#463]
The built-in plain text displaying behaviour for the TextField is awesome, but I think that an option to only show the plain text password as long as the user continuously presses down on the little "eye" icon would be a great option.

It is a bit better (safer) alternative for revealing the password in my opinion. (of course I may be wrong, but having an option like this is nice anyways).

Thank you in advance!

**Comment by danieldahan** [comment]
I am not sure I follow. Is it not only allowing plain-text to be displayed when the eye-button is down?

**Comment by balazsgerlei** [comment]
No, you press down the eye-button and it switches to plain text. It stays like that until you press the eye button down again, and only than changes back to dots.

What I propose, is to have an option to only display the password in plain text until the user actively presses down on the eye-button, and switch back to dots as soon as the user stops pressing down on it. I don't know if you tried Windows 10, but this is the default behaviour for password fields there.

**Comment by danieldahan** [comment]
I would have to take a look at Windows 10. Currently, you are not forced to have the default behaviour. You can set the text to not be secure with the `secureTextEntry` TextField property. As well, you can switch the look of the eye as you please and remove the handlers on that button.

I think you can get what you are looking for with the current system, though, it would require you to modify the default behaviours. 

At this point, I don't have much time to work on it myself, so if you would like to work on it and submit a PR, that would be cool and we can go from there. 

I appreciate the suggestion very much. I'll try and get my hands on a Windows device and see what you are talking about first hand.

**Comment by balazsgerlei** [comment]
Ok, I'll try to implement it and submit when I came up with somethig I will share. Thank you for your attention.

**Comment by danieldahan** [comment]
Anytime, and if you need any assistance with ideas and such, please join the [Gitter](https://gitter.im/CosmicMind/Material) channel :)
