### ISSUE TITLE
xcode 8 issue

### ISSUE THREAD

**Issue by gtulga** [CosmicMind/Material#468]
Hi,

I tried to use it on swift 2.3. But convert gives lot of errors. Is there any guide to use xcode 8 and swift 2.3?

Thanks

**Comment by chashmeetsingh** [comment]
What steps did u follow? @gtulga

**Comment by gtulga** [comment]
I'm using cocoapods

**Comment by gtulga** [comment]
I used development branch and build success. How to implement it to my own project? Do I need cocoapods?

**Comment by chashmeetsingh** [comment]
for swift 2.3 or 3 u will need to use development branch of the pod
`pod 'Graph', , :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'` 
though this branch is still in development

**Comment by gtulga** [comment]
Thanks, problem solved

**Comment by Gerst20051** [comment]
pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'

**Comment by chashmeetsingh** [comment]
Right apologies for that 😅
