### ISSUE TITLE
placeholderVerticalOffset Does not work when setting .text value 

### ISSUE THREAD

**Issue by ed-mejia** [CosmicMind/Material#469]
For my project the actual distance between the text and the placeholder looks excessive, we have access to the placeholderVerticalOffset property to adjust this but only works when the placeholder animation takes place, if you set this value and at the same time you set an initial text the placeholder will appear initially with the default offset.

If you remove the text, the animation takes place and then is when the value coming from placeholderVerticalOffset is being used properly.

Is there any work around we can apply to solve this?

**Comment by danieldahan** [comment]
I'll will take a look for you. Thank you for bringing this to our attention :)

**Comment by azatZ** [comment]
Faced the problem too. It seems there is missing case in `func layoutPlaceholderLabel()`. Adding
`if false == text?.isEmpty {
               placeholderLabel.frame.origin.y = -placeholderLabel.frame.size.height + placeholderVerticalOffset
            }` 
solved my problem

**Comment by danieldahan** [comment]
@azatZ Nice, thank you for the workaround. @ed-mejia The issue was that this line on `387`

```swift
placeholderLabel.frame.origin.y = -placeholderLabel.frame.size.height
```

needed to change to 

```swift
placeholderLabel.frame.origin.y = -placeholderLabel.frame.size.height + placeholderVerticalOffset
```

Which is similar to the workaround suggested. I am posting this solution in Material 2 (development) branch.

**Comment by ed-mejia** [comment]
Great work! thanks 👍
