### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by Gerst20051** [CosmicMind/Material#470]
Trying to ```import Material``` for my macOS app but it fails to find module.

**Comment by danieldahan** [comment]
The only part of material available for macOS is the color library. As well, make sure to build the macOS target. How are you adding Material in your project?

**Comment by Gerst20051** [comment]
Ok that makes sense. I'm using CocoaPods. Do you know why there isn't a library like Material for macOS?

**Comment by danieldahan** [comment]
Not sure. I will close this issue for now :)
