### ISSUE TITLE
Module was created by a newer version of the compiler

### ISSUE THREAD

**Issue by Vigilante13** [CosmicMind/Material#471]
I don't understand why I'm getting this error. I'm using version 1.28.1 and i'm running my project on xcode 7.3. What is the solution to this?

**Comment by danieldahan** [comment]
Try cleaning your build folder and deleting your user derived directory.

**Comment by Vigilante13** [comment]
How do I delete my user derived directory?

**Comment by danieldahan** [comment]
Go to preferences, then locations. Click the arrow button to find the folder in the finder. Close Xcode and then delete.

**Comment by Vigilante13** [comment]
Alright that worked thanks!

**Comment by danieldahan** [comment]
Great!
