### ISSUE TITLE
Missing Properties/Enums in Objective-C

### ISSUE THREAD

**Issue by ggammon** [CosmicMind/Material#472]
Enums don't contain @objc or inherit from Int. This causes the enums and associated properties/methods that rely on them to not be visible through the Objective-C Bridge (such as MaterialSwitch properties). I encountered this problem while binding this framework in Xamarin, which relies on the Objective-C visibility.

I created a branch and tested tagging the MaterialSwitch enums which seemed to work fine and allowed the missing properties/constructor to appear for Objective-C. Is there any reason all enums can't be marked for Objective-C visibility?

**Comment by danieldahan** [comment]
Hey, let me look into this shortly. Generally if the enums could be marked, they should be for visibility. I will make that change, test, and post an update. Thank you!

**Comment by danieldahan** [comment]
This is now updated in Material 2. Thank you very much :)

**Comment by SeeD-Seifer** [comment]
@ggammon could you share the experience with making Xamarin bindings for this library? Spend half a day with no success using tutorial for Swift-to-Xamarin binding https://stackoverflow.com/documentation/xamarin.ios/6091/binding-swift-libraries#t=201707032228154316842
Your knowledge could be a good start for https://github.com/CosmicMind/Material/issues/739

**Comment by ggammon** [comment]
I actually have a working version of this for Xamarin already. Its a bit outdated (I made it sometime last fall) but it definitely was working at one point. I built it using the objective-c bridge to the swift libraries and then trying to add Obj-C indicators where things weren't visible. Let me see if I can find it and I can attach it here.

**Comment by ggammon** [comment]
[CosmicMind.Material.iOS.zip](https://github.com/CosmicMind/Material/files/1120749/CosmicMind.Material.iOS.zip)

That is the version I made for Xamarin. Last I checked it was functional. I haven't updated it to the newest version of this library though so doing that might actually cause some issues.

Some notes about the process. I bound the original library using Xamarin's framework binding tool (objective-sharpie). I then went through and cleaned up (or at least attempted) some of the method names/properties to be more C#/.NET aligned. I also tried to break up the objects into their respective associated header files for easy look up.

Also, some things to note. Xamarin does not support dynamic libraries (swift) easily; so in order to get this to work, I had to modify the build settings of this to embed the necessary swift dependencies into the .framework itself ("Always Embed Swift Standard Libraries - YES").

I don't think the binding is 100% there yet, I can spend some time trying to get 1:1 parity but this should at least help.

**Comment by SeeD-Seifer** [comment]
@ggammon that's cool, thanks!

I found a few tricky (and annoying) steps in the SO link above, so here are some questions:
1. Have you converted Material.framwork to *fat* library?
2. Have you used Xamarin lib in the production app (uploaded to the Apple Store)? There is a note about *SwiftSupport* folder in production IPA file.
3. Do you only include compiled DLL into the app project? Or Material.framework is also required?
4. Is the resulted DLL can be used for both Simulator and Device?
