### ISSUE TITLE
shadow problem 

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#473]
I'm using the development branch on xcode 8 with swift 3.

I'm seeing two cases where a FabButton is initially rendered with an incorrect shadow.

In a simple menu-view; if the image is not set, then the shadow is rendered wrongly at the outset.

![2016-07-28 05 31 49 pm](https://cloud.githubusercontent.com/assets/586910/17220886/3c1231c8-54e9-11e6-9119-874c1d11f16f.png)

as soon as you tap on the view, it is redrawn correctly

![2016-07-28 05 31 56 pm](https://cloud.githubusercontent.com/assets/586910/17220900/46cb3da8-54e9-11e6-90cf-e860d2b52d8c.png)

In this case - setting an image fixes the issue, but I don't think it is the root cause as I have another case where I'm using Fab buttons in a colour selector. Each button is in a cell in a collection view.

In this case, even adding an image doesn't fix the shadow for cells that are brought onscreen.

![2016-07-28 05 37 25 pm](https://cloud.githubusercontent.com/assets/586910/17221057/f82119d8-54e9-11e6-824d-fca800f24d86.png)

do you have any suggestions?

link to the demo project is here:
https://dl.dropboxusercontent.com/u/4262242/Shadow.zip

let me know if you'd like a demo project with the collection view issue.

thank you!

**Comment by danieldahan** [comment]
Thank you for this. Yes, I am aware of this issue. I have not completed the ShadowPath mapping to UIView objects with a depth/shadow set.

**Comment by ConfusedVorlon** [comment]
good to know. 

Do you have any suggestions for workaround or timing on a fix?

I can just avoid using the fab button in my colour selector if I need to.

**Comment by danieldahan** [comment]
I plan on having a fix for you tomorrow morning.

**Comment by ConfusedVorlon** [comment]
awesome - thank you!

**Comment by danieldahan** [comment]
@ConfusedVorlon Hey! I am working on this, I wasn't able to reproduce unless I used your project. So I am going to make some changes that I had hoped to make around this area, then I will push it to dev and you can verify it works. I am working on it now. :)

**Comment by danieldahan** [comment]
@ConfusedVorlon Hey, I updated development to handle shadow paths now. Please update your pod. As well, I update the "Use Legacy Swift..." flag, but found in the Pods project I needed to do the same. Check this out for help on that, [stackoverflow issue](http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift). If you need any other help with the shadows... please message me on [Gitter](https://gitter.im/CosmicMind/Material), or create a new issue. Thanks!

**Comment by ConfusedVorlon** [comment]
thank you
