### ISSUE TITLE
attempted to retain deallocated object- Material Button

### ISSUE THREAD

**Issue by Vigilante13** [CosmicMind/Material#474]
Anytime I'm clicking on a FlatButton that I have in a NavigationBarView, I get this error:
`attempted to retain deallocated object`
and it's in this code:
```
if nil != self.pulseColor && 0 < self.pulseColorOpacity { //this line gives the error
	MaterialAnimation.animateWithDuration(t, animations: {
		pulseLayer.hidden = true
	}) {
	    pulseLayer.removeFromSuperlayer()
	}
}
```

**Comment by danieldahan** [comment]
What version of Material are you using?

**Comment by Vigilante13** [comment]
Version 1.32.0

**Comment by danieldahan** [comment]
Well, we are currently at 1.42.7. So you should upgrade to the latest, it will fix that issue. All the best :)

When you update, consult the [changelog](https://github.com/CosmicMind/Material/wiki/Changelog). It will help you understand changes that have been made.

**Comment by Vigilante13** [comment]
Which version did you fix this issue? I don't really want to update to the latest version as you have changed a lot of the names.

**Comment by danieldahan** [comment]
I am not sure. You would need to look in the changelog. Look when the pulse animations were updated.
