### ISSUE TITLE
What's the new command for navigationBarView.titleLabelInset.left = 110

### ISSUE THREAD

**Issue by Vigilante13** [CosmicMind/Material#475]
In my code, I was using `navigationBarView.titleLabelInset.left` or `navigationBarView.titleLabelInset.right`, what's the alternative for this using `Toolbar`?

**Comment by danieldahan** [comment]
What version of the framework are you using?

**Comment by danieldahan** [comment]
I haven't heard from you. If you still need help, please reopen this issue. Thank you!
