### ISSUE TITLE
ErrorTextField question

### ISSUE THREAD

**Issue by gtulga** [CosmicMind/Material#476]
Hi,

I have 2 ErrorTextFields and 1 button to login. I want to show detail when I click button. how to do it?

Another question is how to implement ErrorTextField's validation? I want first ErrorTextField only allow 5-8 characters only. I cannot find this kind of example.

Thanks

**Comment by danieldahan** [comment]
Hi, 

I will be able to help out shortly :)

**Comment by chashmeetsingh** [comment]
add a target to the button and in the target function hide or show the detail @gtulga

**Comment by gtulga** [comment]
Great thank you!
