### ISSUE TITLE
Material Switch

### ISSUE THREAD

**Issue by gtulga** [CosmicMind/Material#477]
Hi,

I'm not found switch and other features in storyboard example. is it possible to use them in storyboard? or only by swift code?

Thanks

**Comment by chashmeetsingh** [comment]
@gtulga Add a UIView and in identity inspector change its class to MaterialSwitch :)

**Comment by gtulga** [comment]
Thanks. It works. I changed MaterialSwitch to just Switch. Because I'm using Swift 3.

When will you release development branch's examples? Some parts are changed much.

**Comment by danieldahan** [comment]
@chashmeetsingh Thank you for helping on this. @gtulga Yes, the API will be changing and advancing. Stay up to date with the [change log](https://github.com/CosmicMind/Material/wiki/Changelog). As well, I will be making new samples when we release. I am closing this issue now as it seems solved. Thanks!
