### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by gtulga** [CosmicMind/Material#478]
Hi,

I need to make settings page like this. Groups like account, push and get help. Also settings listed like table. How to do it? is there any example?

![image](https://cloud.githubusercontent.com/assets/2021932/17300187/4acb4540-584c-11e6-86aa-04b8cbb0a4cd.png)

Thanks

**Comment by danieldahan** [comment]
Hi, no problem. I think we should move this issue to [Gitter](https://gitter.im/CosmicMind/Material) though. Chat with us there. Thanks!
