### ISSUE TITLE
TextField text is always black

### ISSUE THREAD

**Issue by btelintelo** [CosmicMind/Material#487]
I have a TextField and it is on a dark background.  So I want the text to be white.  But it is always black despite what I set it to in interface builder.  A plain UITextField works properly.

Attached is a sample project showing the issue
[TextFieldTest.zip](https://github.com/CosmicMind/Material/files/413366/TextFieldTest.zip)
.

**Comment by chashmeetsingh** [comment]
@danieldahan reproducible. Property for setting text field's textColour property is not present I suppose

**Comment by danieldahan** [comment]
@btelintelo Should be fixed with [Material 1.42.9](https://github.com/CosmicMind/Material/releases/tag/1.42.9). Thanks @chashmeetsingh :)

**Comment by btelintelo** [comment]
Pulled in 1.42.9 in to project.  Xcode 7 with ios 9.3 simulator, I now see white text as expected.  iOS 10 beta 4, still black text.  Can't imagine a new property in ios10 for this, but something to see if apple fixes in new betas.

**Comment by danieldahan** [comment]
I fixed it on iOS 10 as well, I pushed a sync change to the dev branch. Can you pull in the latest dev and try again?

**Comment by btelintelo** [comment]
I saw you made the change for xcode 8 as well.  The second issue was in ios 10 built from xcode 7.  But, it looks like apple fixed the issue in ios 10 beta 5.  Now all the text is white!  Thanks!

**Comment by danieldahan** [comment]
Anytime :)
