### ISSUE TITLE
'sharedApplication' is unavailable: not available iOS (App Extension)

### ISSUE THREAD

**Issue by SBiOSoftWhare** [CosmicMind/Material#488]
I would like to use Material in an action app extension, but it is not possible due to usage of 'UIApplication.sharedApplication'.
Unfortunately I do not have a pull request to send to you right now but maybe there are solutions like using size class instead of status bar orientation to handle orientation for example or using a Cocoapods subspec to embed components only for app extension.
Have you any other ideas on how to use your library in the context of an app extension ?

Thanks for your work on this library !

**Comment by danieldahan** [comment]
Nice :) Thank you. I will have to look into this. For now, I am going to post it as a `feature request`.

**Comment by danieldahan** [comment]
I am going to close the issue and review the PR very soon. Once again thank you!
