### ISSUE TITLE
Toolbar less height after update.

### ISSUE THREAD

**Issue by MarcoCarnevali** [CosmicMind/Material#489]
Hello, I had a older version of the library... today I updated it and I now the height of the toolbar is less and the status bar is over the toolbar, see the screenshots. In the first the toolbar was attached to the contacts and chats bar.
Thank you in advance.

<img width="378" alt="schermata 2016-08-14 alle 12 49 02 pm" src="https://cloud.githubusercontent.com/assets/9656572/17651535/190a7680-621e-11e6-94d1-93ef7b97271d.png">
<img width="377" alt="schermata 2016-08-14 alle 12 53 07 pm" src="https://cloud.githubusercontent.com/assets/9656572/17651537/1b97e4c8-621e-11e6-8e1e-1d563dcc72ba.png">

**Comment by danieldahan** [comment]
Can you share your setup, or a sample project?

**Comment by MarcoCarnevali** [comment]
Also another thing... In the code I set two other buttons that before the update worked and now seems to be hidden, this is my code:



`    func setNavigationController(){
        // Left title setting
        
        
        // Menu button.
        var image: UIImage? = MaterialIcon.menu
        let menuButton: FlatButton = FlatButton()
        menuButton.pulseColor = MaterialColor.white
        menuButton.tintColor = MaterialColor.white
        menuButton.setImage(image, forState: .Normal)
        menuButton.setImage(image, forState: .Highlighted)
       menuButton.addTarget(self, action: #selector(handleFabButton), forControlEvents: .TouchUpInside)
        menuButton.pulseAnimation = .Center
        menuButton.tag = 1010
        
        // Search button.
        image = MaterialIcon.search
        let searchButton: FlatButton = FlatButton()
        searchButton.pulseColor = MaterialColor.white
        searchButton.tintColor = MaterialColor.white
        searchButton.setImage(image, forState: .Normal)
        searchButton.setImage(image, forState: .Highlighted)
        searchButton.contentEdgeInsets = UIEdgeInsetsZero
        searchButton.pulseAnimation = .Center
        searchButton.tag = 1000
        
        
        
        
        // More vertical button.
        image = MaterialIcon.moreVertical
        let moreVertical: FlatButton = FlatButton()
        moreVertical.pulseColor = MaterialColor.white
        moreVertical.pulseAnimation = .Center
        moreVertical.tintColor = MaterialColor.white
        moreVertical.setImage(image, forState: .Normal)
        moreVertical.setImage(image, forState: .Highlighted)
        moreVertical.addTarget(self, action: #selector(homeStartup.menus(_:)), forControlEvents: .TouchUpInside)
        moreVertical.tag = 1001
        
        
        // ToolBar setting
        
        if Companies != []{
            toolbar.titleLabel.text = Companies[0]
        }else{
            toolbar.titleLabel.text = ""
        }
        toolbar.titleLabel.textAlignment = .Left
        toolbar.titleLabel.textColor = MaterialColor.white
        toolbar.titleLabel.font = RobotoFont.boldWithSize(20)
        //toolbar.titleLabel.adjustsFontSizeToFitWidth = true
        
        toolbar.leftControls = [menuButton]
        toolbar.rightControls = [searchButton,moreVertical]
        toolbar.shadowPathAutoSizeEnabled = true
        toolbar.shadowOpacity = 0
        toolbar.height = 32
        toolbarFrame = toolbar.frame
        
        
        
        
    }
`

**Comment by danieldahan** [comment]
I don't see the initialization of the Toolbar. Could you share that?

**Comment by MarcoCarnevali** [comment]
I have a @IBOutlet var toolbar: Toolbar!

**Comment by danieldahan** [comment]
Okay, can you send me a sample? I need to see your storyboard and such.

**Comment by MarcoCarnevali** [comment]
it's a little bit complicated, anyway before the updates was working perfectly so...

**Comment by danieldahan** [comment]
Yeah things have changed since the last time you have updated I am sure. Have you looked at this https://github.com/CosmicMind/Material/tree/master/Examples/Storyboards/Toolbar ?

**Comment by danieldahan** [comment]
I am going to close this issue for now. If you have trouble with the example, let me know and we can go from there. It would be easier to use the [Material Gitter](https://gitter.im/CosmicMind/Material) channel for this :) Thank you!
