### ISSUE TITLE
Please mark classes as open

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#491]
the latest iteration of swift (xcode 8, beta 6) has made it so that public classes are useable, but not subclassable outside of the module.

https://github.com/apple/swift-evolution/blob/master/proposals/0117-non-public-subclassable-by-default.md

so my class:

`class ColourButton: FabButton {...`

generates the error

`Cannot inherit from non-open class 'FabButton' outside of its defining module`

the fix is just a global search/replace. Wherever you have `public class`, just replace it with `open class`

thank you

**Comment by danieldahan** [comment]
Cool, I will update this later today. Thank you!

**Comment by danieldahan** [comment]
@ConfusedVorlon this is almost done. So please pull development as I progress on this.

**Comment by ConfusedVorlon** [comment]
yup - I'm using it now! Thank you.

**Comment by danieldahan** [comment]
Cool, I am going to close this as the updates are being made where appropriate. Thank you!
