### ISSUE TITLE
Is Material supporting Swift 2.3?

### ISSUE THREAD

**Issue by reidmain** [CosmicMind/Material#492]
I haven't been able to find any concrete word on wether or not Material will support Swift 2.3 or jump directly to Swift 3.

I've stumbled across a number of issues where people talk about it and it seems like the decision to support Swift 2.3 has bounced back and forth between yes and no but at the time of raising this issue all I see is a "development" branch that only supports Swift 3.

I am asking this because it is physically impossible for my application to be upgraded to Swift 3 any time soon and since Material is a dependency I need a Swift 2.3 version to be able to use Xcode 8. I wanted to first double check that Swift 2.3 support is indeed dead before I fork the repository and attempt to to the migration myself.

**Comment by danieldahan** [comment]
@reidmain Excellent question. I have been only supporting Swift 3 and all latest updates have been in Swift 3. If you would like help in supporting 2.3, then please start the process, and I will create a branch that you can merge into and then I will take over support for it. Thank you!

**Comment by reidmain** [comment]
@danieldahan I am looking at making the changes on whatever Carthage pulls into the Carthage/Checkouts folder just to see if I can get `carthage build --platform ios` to succeed and my iOS app to build against Swift 2.3

Once I get to that point I'll report back my findings and we can talk about merging any changes I make into a branch.

**Comment by danieldahan** [comment]
Awesome! Thank you, please feel free to reach out to us for any help. All the best!

**Comment by jlaws** [comment]
@danieldahan can you create that branch, I will send a PR will support for 2.3

**Comment by danieldahan** [comment]
@jlaws awesome! Here is the branch link https://github.com/CosmicMind/Material/tree/swift-2.3

**Comment by jlaws** [comment]
@danieldahan I actually removed my dependency on Material last night since I was not really taking advantage of the library.  Hopefully @reidmain will send in a fix for 2.3

**Comment by danieldahan** [comment]
No worries :)

**Comment by reidmain** [comment]
Unfortunately we are no longer planning on migrating to Swift 2.3

After making the quickest possible changes to get Material to work with Swift 2.3 (I don't know if they were all the correct ones since I didn't see any tests and we only use two components from Material) I also had to hack about 8 other dependencies to work with Swift 2.3 because it seems like the majority of people are skipping it.

Currently we are looking at waiting 2-3 weeks after the Xcode 8 GM is released and then attempting to migrate to Swift 3 then with the hope that all of our dependencies have been migrated.

**Comment by danieldahan** [comment]
@reidmain I like that choice :) I have added many updates to the Swift 3 version, so ping me if you need any help. All the best!
