### ISSUE TITLE
Button doesn't like being squeezed by stackView

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#493]
if you have a horizontal stackview, then it will adjust to take account of views that are hidden/shown.

If you throw in animation, then it does this by squeezing the view that is being hidden down to zero.

If you hide/show a fabButton, then you hit two problems

1) the circle doesn't squeeze, although the image does
2) when you 'unsqueeze' it, the image disappears

problem 2 is there even if you don't animate the transition.

I think that problem 2 has appeared with since yesterday (e.g. related to one of yesterday's commits)

I have attached a simple demo project.

[buttonDeath.zip](https://github.com/CosmicMind/Material/files/426729/buttonDeath.zip)

**Comment by ConfusedVorlon** [comment]
note - I'm using today's head, on xCode 8 beta 6.

**Comment by danieldahan** [comment]
@ConfusedVorlon what is this `squeeze` animation. Where is it coming from?

**Comment by ConfusedVorlon** [comment]
it is implemented by the UIStackView.

This is mentioned in the UIStackView docs here
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/

```
You can animate both changes to the arranged subview’s hidden property and changes to the stack view’s properties by placing these changes inside an animation block.

OBJECTIVE-C

// Animates removing the first item in the stack.
[UIView animateWithDuration:0.25 animations:^{
    UIView * firstView = self.stackView.arrangedSubviews[0];
    firstView.hidden = YES;
}];
SWIFT

// Animates removing the first item in the stack.
UIView.animateWithDuration(0.25) { () -> Void in
    let firstView = stackView.arrangedSubviews[0]
    firstView.hidden = true
}
```

**Comment by ConfusedVorlon** [comment]
Ok - I did some digging. Slightly updated debug project attached:

[buttonDeath 2.zip](https://github.com/CosmicMind/Material/files/428311/buttonDeath.2.zip)

The StackView is simply telling the view to shrink - it does this by setting an autolayout width constraint of zero.

I found a couple of issues that are causing this to not work nicely.

#1) when you set a width constraint for a fab button where width != height - the image shrinks, but the background layout (circle) does not.

You can see this by tapping the 'shrink' button.

Clearly you weren't expecting non-round fab buttons! Might a transform do the job here for non-round cases?
(LayoutSubviews is getting called here with the frame width == 0)

#2 Something wierd is happening when the button is expanded again. 
For my debug view (just a regular UIView), layoutSubviews is called when I expand - and the frame is set to 45,45

for the FabButton, layoutSubviews is called after the expansion, but the frame is 0,45 when the layoutSubviews is called.
this explains why the image doesn't get displayed after the layout (it is still zero width).

If I look at the view debugger - then the view does expand to 45,45.

however - I can't figure out why layout isn't getting called after the size change. If I try making a regular button hide/show, then it behaves properly.

I can work around this partially by using a completion block on the animation

        UIView.animate(withDuration: 0.5, animations: {
            self.plane.isHidden = !self.plane.isHidden
            self.debug.isHidden = !self.debug.isHidden
            self.shrink.isHidden = !self.shrink.isHidden
        }) { (complete) in
            self.plane.setNeedsLayout()
            self.plane.layoutIfNeeded()
        }

this triggers another layout pass, and the image shows properly. 

by a process of random hacking, I have identified the problematic function, though I'm not sure exactly how to fix it:

    open override func layoutSublayers(of layer: CALayer) {
        super.layoutSublayers(of: layer)
        if self.layer == layer {
            //layoutShape()
            layoutVisualLayer()
        }
    }

and specifically, the problem within layoutShape is setting the frame:

```
    open func layoutShape() {
//        if .none != shapePreset {
//            if width < height {
//                frame.size.width = height
//            } else if width > height {
//                frame.size.height = width
//            }
//        }
        
        if .circle == shapePreset && width != 0 {
            cornerRadius = width / 2
        }
    }
```

If you comment out these lines, and don't let the cornerRadius get set to zero when the width is zero, then the layouts get called correctly, and the shape shrinks - although it isn't perfect.

clearly this isn't a proper fix - but hopefully it gives you some clues!

I know that modifying frame when autolayout is doing its thing is problematic with UIViews, and I suspect the same is true with the layer...

**Comment by danieldahan** [comment]
I have an idea here. I will give it a try and share the result.

**Comment by danieldahan** [comment]
Please pull the latest from development. Also, I added a convenience property `image` to avoid having to set the `setImage` and in Storyboards, when you use the new `image` property, it sets both the `.normal` and `.highlighted` state for you, rather than just the `.normal` state, which causes a grey tint on the image.

**Comment by ConfusedVorlon** [comment]
that does the trick - thanks.
