### ISSUE TITLE
How can i put icons on the textfield like this 

### ISSUE THREAD

**Issue by sagaya** [CosmicMind/Material#495]
![screen shot 2016-08-24 at 3 42 12 pm](https://cloud.githubusercontent.com/assets/12961966/17935215/660b1498-6a12-11e6-89e8-39aab90f172c.png)

**Comment by adamdahan** [comment]
@cosmo1234 

Few techniques you can use for this: 

1. You can tap into the textField.layer and perform a transform that will push the actual textfield's editable view over to the right. Then you can just draw the image in the paddings space. 

2. You can override UITextfield layout and add an image as a subview @ position 0, 0.

3. You can create a custom view with a regular textfield + a CAShapeLayer as a divider and an image as subviews. 

@danieldahan Might be nice to consider this for option in Material 2. 

Thanks @cosmo1234 - closing this ticket.

**Comment by danieldahan** [comment]
@adamdahan agreed.

**Comment by CavalcanteLeo** [comment]
any news about that?

**Comment by danieldahan** [comment]
@CavalcanteLeo can you try this commit: 5065e8837e10b5ba6753586aa1b832c83ddd1d18, it is available in Objc-C now. As well, have you looked at the [TextField](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TextField) sample? To put it fully across as the image above, I will need to investigate that.

**Comment by CavalcanteLeo** [comment]
I could do it by creating a UITextField Category in objective-c

```objective-c
#import <objc/runtime.h>

@implementation UITextField (Padding)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"

- (CGRect)textRectForBounds:(CGRect)bounds {
    return CGRectMake(bounds.origin.x + 21, bounds.origin.y + 8,
                      bounds.size.width - 31, bounds.size.height - 16);
}
- (CGRect)editingRectForBounds:(CGRect)bounds {
    return [self textRectForBounds:bounds];
}

@end

```


and then i just imported to my viewcontroller,

But i will try this commit, this might work, and will be much better than create a category to change the properties

**Comment by danieldahan** [comment]
@CavalcanteLeo Yes, I reopened the issue to make an internal fix for this :) Maybe you can suggest something before I jump into this issue more.

**Comment by CavalcanteLeo** [comment]
It's visible now, and worked perfectly!

Thanks dude!

**Comment by danieldahan** [comment]
Amazing!
