### ISSUE TITLE
Material Overrides default navigation controller

### ISSUE THREAD

**Issue by shshalom** [CosmicMind/Material#496]
I'm using Material for just few of the components like buttons and the menu, but after bashing my head for two days I've notice that the reason my UINavigationController setup doesn't work is because Material is overriding it, even if I don't use it.

My current options is either use Material's NavigationController instead (which I really don't want be to forced to do) or to remove the framework which I also don't want to do since I really like it.

Another option is to try and fix it my self,  the question is this behavior is normal or intended?

**Comment by danieldahan** [comment]
What part does it override that is creating the conflict?

**Comment by danieldahan** [comment]
Also what version are you using?

**Comment by shshalom** [comment]
It overrides UINavigationItem.
and I'm using the latest one.

Just to point out, I'm using the framework and not as pod since while using the Pod version none of the Icons and other assets are loading (which is another issue, unrelated)

**Comment by danieldahan** [comment]
When you say latest, do you mean development or master? Also, what is the actual issue. You will need to share an error log, code that is not working, or further describe. :)

**Comment by shshalom** [comment]
I've cloned it from master branch.

There's no error to share.. that's why it took me two days to catch what went wrong.
I can tell you what I did and you can reproduce this problem.

 

- Create new single page view project.
-  In the Main.Storyboard embed the ViewController inside NavigationController
-  Inside viewDidLoad add  self.navigationItem.title = "some thing"

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    self.navigationItem.title = "hello world"
}
```
 

- Run the project, you can see that everything is ok.
-  Add Material.framework to the project and embed it.
-  import Material
-  Here's things starts to get weird: 

```swift
import UIKit
import Material

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.title = "Hello"
    }
}
```
- Run the project. - you can see that the title is gone.
-  Delete Import Material line
-  Delete self.navigationItem.title = "hello world" line and rewrite it - otherwise it will try to access Material's UINavigationItem extension.

From what I've noticed, as you Import Material, when ever you access "self.navigationItem" it goes to Material's NavigationItem.swift - UINavigationItem extension, and since you clearly override the variables there, the super class never get called, hence, the problem.

**Comment by danieldahan** [comment]
Got it :) I agree, there needs to be a better solution. I will play with it today and tomorrow and most likely push something within then. Thanks for sharing this.

**Comment by shshalom** [comment]
Happy to obligee :-). Thank you for the awesome framework.

**Comment by danieldahan** [comment]
Didn't forget about this... going to think about a better solution today. Sorry, was busy in the past week. Thank you!

**Comment by adamdahan** [comment]
@shshalom Inside your controller you should not be using self.navigationItem.title. You should be using self.title. 

Cheers

**Comment by shshalom** [comment]
I know, but what about adding buttons, icons or any other Object to the navigation controller? the title was the simplest example to demonstrate the problem, besides that there's no way to set a native navigation controller while Material is imported to the same controller.

Why not create a fallback to the native Navigation Item if Material Navigation controller is not in use?

**Comment by danieldahan** [comment]
I am going to have to disagree. Material doesn't override any of the UINavigationController or UINavigationBar behaviours, especially when adding buttons. You will only face conflicts if you use the Material NavigationController and Material NavigationBar, which use a separate API for adding controls. So if your issue is that you want to use the default API for the UINavigationController, than you will need to opt out of using Material's. After Adam's point about the self.title, it is clear that using navigationItem.title is actually a second best approach.

If you can suggest a mechanism or fallback that can improve the situation that would be helpful, and a PR would be appreciated. Otherwise for now I am closing this issue and will think of ways to not conflict with the navigationItem.title property. 

All the best :)

**Comment by shshalom** [comment]
I will take a look.  thank you. 👍
