### ISSUE TITLE
IBDesignables are too heavy. How can I disable/avoid it?

### ISSUE THREAD

**Issue by zbangsatz** [CosmicMind/Material#497]
With complex storyboard I usually wait a long time when they're rendering. How can I disable/avoid it?
Plus, I really don't like Material override "navigationItem.title"

**Comment by danieldahan** [comment]
Hey, I don't use Storyboards personally, so I haven't felt the pain point. It makes sense though and I will look into this. Do you have any suggestions? As well for the navigation title... agreed, I will come up with something there :)

**Comment by danieldahan** [comment]
Hey, I am looking into solutions for this. Thank you for your patience. :)

**Comment by annphan** [comment]
I usually config everything in code and just use the class to connect IBOutlets,

**Comment by zbangsatz** [comment]
I usually config everything in code and just use class to connect IBOutlet. I think many many people have the same situation with me. Maybe another branch or a config like Material.enableDesign when app launch will help. 
Thank for you help

**Comment by danieldahan** [comment]
I am leaning towards removing it completely. I will make a decision tomorrow and push a solution.

**Comment by adamdahan** [comment]
@danieldahan We should remove IBDesignable support.

**Comment by danieldahan** [comment]
@adamdahan 100% agree. It will be removed in Material 2, most likely in the next push.

@zbangsatz So this is the approach :) I will close this issue once I make the push to `development`.

**Comment by danieldahan** [comment]
@IBDesignables have now been removed, in favour of a lighter weight storyboard experience. Thank you!
