### ISSUE TITLE
Custom Height of divider in Card View

### ISSUE THREAD

**Issue by umeshjavastar** [CosmicMind/Material#499]
I am trying to increase the height of divider in CardView via Storyboard but unable to customize it??

**Comment by zbangsatz** [comment]
I'm afraid it's not possible.

**Comment by danieldahan** [comment]
The height is fixed at 1 `dividerLayer?.frame = CGRectMake(dividerInset.left, y, width - dividerInset.left - dividerInset.right, 1)` In Material 2, you will be able to customize the divider value through the `Divider` object. All the best!

**Comment by umeshjavastar** [comment]
thanks a lot
