### ISSUE TITLE
suggested subclassing approach doesn't work with CardSubclass()

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#501]
If I understand correctly, the suggestion is to set properties in ```prepareView```

So, I have my subclass (trivial changes for the example)
```

class SharingCard:Card {
    var stampHolder:StampViewHolder!
    
    override func prepareView() {
        super.prepareView()
        
        let titleLabel: UILabel = UILabel()
        titleLabel.text = "Share me!"
        titleLabel.textColor = Color.white
        titleLabel.font = UIFont.preferredFont(forTextStyle: .headline)
        self.titleLabel = titleLabel

    }
}
```

If you create a SharingCard with 

`let myCard=SharingCard()`

then the following happens

`public convenience init?(image: UIImage? = nil, titleLabel: UILabel? = nil, contentView: UIView? = nil, leftButtons: [UIButton]? = nil, rightButtons: [UIButton]? = nil)`

is called
this calls self.init(frame:)
which calls prepareView
(all good so far!) 

but then within the convenience initialiser, you call

`prepareProperties(image: image , titleLabel: titleLabel , contentView: contentView , leftButtons: leftButtons , rightButtons: rightButtons)`

all these properties are zero (they come from the params, rather than the instance properties
this sets titleLabel back to nil

the fix is easy - just default to the instance properties:

`prepareProperties(image: image ?? self.image, titleLabel: titleLabel ?? self.titleLabel, contentView: contentView ?? self.contentView, leftButtons: leftButtons ?? self.leftButtons, rightButtons: rightButtons ?? self.rightButtons)`

I haven't hunted, but I'm guessing this pattern probably appears elsewhere too.

**Comment by danieldahan** [comment]
This is going to be completely reworked. So I will be generally making updates to solve these issues. If you have a solution locally for now, I suggest use it, and soon enough my update will come to the `development` branch and then `Material 2`.

**Comment by ConfusedVorlon** [comment]
the easy fix at the moment is just to use `.init(frame:.zero)` and skip the convenience initialiser

thanks again.
