### ISSUE TITLE
suggestion: let card view take any view type in leftButtons & rightButtons

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#502]
the code already seems to support this. I just changed the declaration to
```
	/**
	:name:	rightButtons
	*/
	open var rightButtons = [UIView]() {
		didSet {
			reloadView()
		}
	}
```

no other code changes required.

that lets me use a stack view again which is handy for the free animations when buttons change.

**Comment by danieldahan** [comment]
Yes, this is correct. In other views this has been the setting. I haven't updated the Card and ImageCard yet, which will have this treatment :) So wonderful catch, and it will be updated for Material 2. I will make a push now to support the change you suggested, and rework the components later this month before release.

**Comment by ConfusedVorlon** [comment]
that was quick!
thanks.

**Comment by danieldahan** [comment]
No worries. The temporary fix is in development.
