### ISSUE TITLE
NavigationController and navigationItem.titleView problems

### ISSUE THREAD

**Issue by leobouilloux** [CosmicMind/Material#503]
Hi there,

I'm using the last version of you framework in my application.
I have 2 problems when setting navigationItem.titleView.

Here is the code involved:
```swift
let button = FlatButton()
button.frame = CGRectMake(0, 0, 20, 40)
button.setTitle(title, forState: .Normal)
button.setTitleColor(Style.textColor, forState: .Normal)
button.titleLabel?.font = RobotoFont.medium
button.addTarget(self, action: #selector(NodeViewController.showPathPopover(_:)), forControlEvents: .TouchUpInside)
self.navigationItem.titleView = button
```

1/ Setting the frame changes nothing, my button takes the whole navigationBar.
2/ My FlatButton makes this pulse effect each time when I press it, but my event is only firing when I touch the very bottom of the button.

I hope you can help me :)

**Comment by leobouilloux** [comment]
Here is a gif resuming the 2 problems:

![titleview problem](https://cloud.githubusercontent.com/assets/1726316/18200131/aa08ee8e-7103-11e6-9c6e-ed76b9959762.gif)

**Comment by danieldahan** [comment]
Hey! I think you are trying to add a button to the center of the `NavigationBar`? If this is correct, you should add the button to the `contentView`. Internally the `titleView` is used to make the layout. The `NavigationBar` is made using [Grid](http://cosmicmind.io/material/grid). So to add something to the contentView where it will be managed for you layout wise, use the following code snippet as an example:

```swift
let button = FlatButton(title: "Button", titleColor: Color.blue.base)
navigationItem.contentView.grid.views.append(button)
```

That's all you need to do to have the button align in the center

**Comment by leobouilloux** [comment]
Thank you very much for your reply.
I'll try you suggestion Monday and give you a feedback.
Have a nice weekend.

**Comment by danieldahan** [comment]
You too and if you have further issues, please use the [Gitter Chanel](https://gitter.im/CosmicMind/Material) or open up a new github issue. Thank you!

**Comment by leobouilloux** [comment]
Hi Daniel,

I have given a try with your code, and it's not working.
I cloned the latest version of your framework and opened to the examples to give another try.

In Programmatic/NavigationController project, I changed the prepareNavigationItems method to the following:
```swift
	private func prepareNavigationItem() {
//		navigationItem.title = "Recipes"
//		navigationItem.titleLabel.textAlignment = .Left
//		navigationItem.titleLabel.font = RobotoFont.mediumWithSize(20)
        
		navigationItem.leftControls = [menuButton]
		navigationItem.rightControls = [switchControl, searchButton]
        
        
        let button = FlatButton()
        button.setTitleColor(MaterialColor.red.base, forState: .Normal)
        button.setTitle("Hello", forState: .Normal)
        navigationItem.contentView?.grid.views?.append(button)
	}
```
The button is never appended because contentView is nil.

Am I missing something?

**Comment by danieldahan** [comment]
@leobouilloux What version of Material are you using? `master` or `development`

**Comment by leobouilloux** [comment]
@danieldahan I just ran pod install to make sure I'm up to date.
 I'm using the lastest version (1.42.9) in the master branch.

I've installed Material with Cocoapod here is the line in my Podfile:
`pod 'Material', '~> 1.0'`

Thanks!

**Comment by leobouilloux** [comment]
Forgot to tell you that I cloned the latest version in master to try your solution in the example project Programmatic/NavigationController

**Comment by danieldahan** [comment]
Okay, no worries. In Material 2 this is way easier to handle. For Material 1, this is a workaround:

```swift
let button = FlatButton()
button.frame = CGRectMake(0, 0, 20, 40)
button.setTitle("BD", forState: .Normal)
button.setTitleColor(MaterialColor.black, forState: .Normal)
button.titleLabel?.font = RobotoFont.medium
        
navigationItem.titleView?.layout(button).center()
navigationItem.contentView?.hidden = true
        
navigationItem.leftControls = [menuButton]
navigationItem.rightControls = [switchControl, searchButton]
```

The key is to hide the contentView, and add the button to the titleView and then use the layout facility to center it based on size. 

:) All the best!

**Comment by leobouilloux** [comment]
It's not working in my app, but it's working in the sample, so I now need to fix my navigation bar :)
Can't wait to try Material 2!

Thank you so much for your time!
