### ISSUE TITLE
Suggestion: SearchBar should post notification when the clear button is pressed

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#504]
at the moment, handle clear button changes the text directly, so no notification is posted.

this change would let subscribers to UITextFieldTextDidChange know when the bar is cleared

```
	open func handleClearButton() {
		textField.text = nil
        
        NotificationCenter.default.post(name: NSNotification.Name.UITextFieldTextDidChange,
                                        object: self,
                                        userInfo: nil)
	}

```

**Comment by danieldahan** [comment]
You can add a handler to the `clearButton`, and in Material 2, I will be adding delegation calls to the SearchBar. When I get to that piece of work, I will consider this design :) thank you!
