### ISSUE TITLE
Add RadioButton and Checkbox.

### ISSUE THREAD

**Issue by alexliubj** [CosmicMind/Material#505]
I feel I have the requirement to use checkbox but I didn't see any control which are related to that. 
By the way I know Apple doesn't Checkbox/Radio buttons neither.

**Comment by danieldahan** [comment]
Yes, those are already on the queue for Material 2 :)

**Comment by alexliubj** [comment]
One more question, when do you think we can expect it?

**Comment by alexliubj** [comment]
@andanieldahan

**Comment by danieldahan** [comment]
@alexliubj Material 2 is expected to ship at the end of September, and will be pushing continuous updates throughout that month. It is a really big release, so I suggest checking out the `development` branch to start familiarizing yourself with some of the latest concepts.

**Comment by svachmic** [comment]
Hi there, I'm having hard time finding Radio Buttons. Has it been dropped or is it hidden under a different name? Thank you.

**Comment by danieldahan** [comment]
@svachmic They haven't been made yet, they are still a feature request. Soon I will get to them, or someone will make a PR :)

**Comment by danieldahan** [comment]
Adding PR https://github.com/CosmicMind/Material/pull/864

**Comment by danieldahan** [comment]
This issue can be closed now as the above mentioned PR is acting on its behalf. Thank you!
