### ISSUE TITLE
Navigation Drawer through IB/Storyboard?

### ISSUE THREAD

**Issue by PuneetKohli** [CosmicMind/Material#507]
Hi,

I was looking to do the Navigation Drawer completely through Storyboards.

I have a `MainViewController` (home screen) and a `LeftViewController` (nav drawer).

Right now what happens is, the Login page segues to `MainViewController`.

Is there any way I can have the Nav Drawer show up either directly through Storyboard segues or through the `MainViewController`?

(Tried following the examples but couldn't seem to adapt it to my use case - since your first screen to open was the page with the nav drawer in it)

**Comment by danieldahan** [comment]
I don't believe you can do this entirely through storyboards. You would most likely need to make your `MainViewController` the NavDrawer and then add the original `MainViewController as the `rootViewController` of the NavDrawer. You can add it as your `rootViewController` through an instance that is generated from a Storyboard. Does this make sense ?

**Comment by adamdahan** [comment]
@PuneetKohli There is currently no supported way to do what you want to do purely through storyboards. It has to be done as a hybrid approach as mentioned by @danieldahan above. 

The basic premise here is: 

You can style your controllers in storyboards but the actual creation of the drawer has to be done in code. You can see this in the examples. 

Reason being - we are not a storyboard first framework. 

Closing this ticket - let us know if you need further guidance.

**Comment by PuneetKohli** [comment]
I'm a bit confused.

My mainviewcontroller is the home screen UI.
And leftviewcontroller is the nav drawer UI.

What you're suggesting is:-

So in the storyboard I'd segue from my login screen to mainviewcontroller and in the initialization code of mainviewcontroller , I would set it as the rootview of leftviewcontroller?

Possibly I'm not understanding this correctly please let me know if you can provide a more detailed explanation

**Comment by adamdahan** [comment]
@PuneetKohli you can check the Examples folder in the Material repo and click on the Programmatic folder. Then go to the NavigationDrawerController folder and open the project's App Delegate. You will see an example of how to do it. 

`func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
		let navigationController: NavigationController = NavigationController(rootViewController: YellowViewController())
		let navigationDrawerController: AppNavigationDrawerController = AppNavigationDrawerController(rootViewController: navigationController, leftViewController: AppLeftViewController(), rightViewController: AppRightViewController())
		
		window = UIWindow(frame: UIScreen.mainScreen().bounds)
		window!.rootViewController = navigationDrawerController
		window!.makeKeyAndVisible()
		return true
	}`

If you are using storyboards just don't alloc + init your controllers via (). Use storyboard methods like instantiateViewControllerWithIdentifier.
