### ISSUE TITLE
There is a error when TabBar has 5 buttons

### ISSUE THREAD

**Issue by OnlyMyRailgun** [CosmicMind/Material#508]
When TabBar has 5 buttons, each button's width is seems like it has 6 buttons.
Could u please check it?
Really thank you for making this wonderful framework!

**Comment by adamdahan** [comment]
@OnlyMyRailgun can you send me a screenshot?

**Comment by OnlyMyRailgun** [comment]
<img width="432" alt="2016-09-09 12 52 18" src="https://cloud.githubusercontent.com/assets/2841260/18374949/67f0f8d2-768c-11e6-8049-73adbca37678.png">
⬆️5 buttons but seem like 6 buttons
![simulator screen shot 2016 09 09 12 52 39](https://cloud.githubusercontent.com/assets/2841260/18374954/6fef5eb6-768c-11e6-8035-837b204653b1.png)
⬆️real 6 buttons are normally presented.

**Comment by chashmeetsingh** [comment]
@OnlyMyRailgun you will need to play around with the width of the tab

**Comment by danieldahan** [comment]
@OnlyMyRailgun This looks like an issue, It should be sizing correctly. Can you share your setup code, and the version of Material that you are using? Thank you!

**Comment by OnlyMyRailgun** [comment]
@danieldahan I'm glad to do it. In fact I used the example program. The version I think is 1.42.9 (Not sure are you figure this or not). Hope this can be helpful.
```
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        let tabBar: TabBar = TabBar(frame: CGRectMake(0, 100, view.bounds.width, 44))
        tabBar.backgroundColor = MaterialColor.blue.base
        
        view.addSubview(tabBar)
        
        let btn1: FlatButton = FlatButton()
        btn1.pulseColor = MaterialColor.white
        btn1.setTitle("1", forState: .Normal)
        btn1.setTitleColor(MaterialColor.white, forState: .Normal)
        
        let btn2: FlatButton = FlatButton()
        btn2.pulseColor = MaterialColor.white
        btn2.setTitle("2", forState: .Normal)
        btn2.setTitleColor(MaterialColor.white, forState: .Normal)
        
        let btn3: FlatButton = FlatButton()
        btn3.pulseColor = MaterialColor.white
        btn3.setTitle("3", forState: .Normal)
        btn3.setTitleColor(MaterialColor.white, forState: .Normal)
        
        let btn4: FlatButton = FlatButton()
        btn4.pulseColor = MaterialColor.white
        btn4.setTitle("4", forState: .Normal)
        btn4.setTitleColor(MaterialColor.white, forState: .Normal)
        
        let btn5: FlatButton = FlatButton()
        btn5.pulseColor = MaterialColor.white
        btn5.setTitle("5", forState: .Normal)
        btn5.setTitleColor(MaterialColor.white, forState: .Normal)
        
        let btn6: FlatButton = FlatButton()
        btn6.pulseColor = MaterialColor.white
        btn6.setTitle("6", forState: .Normal)
        btn6.setTitleColor(MaterialColor.white, forState: .Normal)
        
        tabBar.buttons = [btn1, btn2, btn3, btn4, btn5]

    }
```

**Comment by danieldahan** [comment]
It looks like you are using the master branch. This is fixed now in the development branch and will be fully released in Material 2. I am not updating Material 1 with any further fixes as most of everything has been rewritten. Please let us know if you need any further help. 

Also, the version of the TabBar in Material 2 includes another type PageTabBarController, which connects a UIPageViewController to the tabs.

**Comment by OnlyMyRailgun** [comment]
@danieldahan 
I got it. Right now I think I don't have 5 buttons. Thank you.
I'm really happy to hear that we will have a PageTabBarController to use. I have to implement it by myself. When will you release the great Material 2? I have to say your framework is really awesome!

**Comment by danieldahan** [comment]
Thank you! The framework will be released by the end of this month :)
