### ISSUE TITLE
Crash when using TableViewCell in development branch.

### ISSUE THREAD

**Issue by nthtrung09it** [CosmicMind/Material#510]
I switch from master branch to development branch to use with swift3 and xcode 8 GM. But it crash when using subclass DrawerCell: TableViewCell.

Here is the log: "unexpectedly found nil while unwrapping an Optional value", at line 165:
internal func prepareVisualLayer() {
		visualLayer.zPosition = 0
		...           
}

I think it is not initialized.
How can I avoid this problem? Tks.

-----------------------------------------------------------------------------
-	A CAShapeLayer used to manage elements that would be affected by
-	the clipToBounds property of the backing layer. For example, this
-	allows the dropshadow effect on the backing layer, while clipping
-	the image to a desired shape within the visualLayer.
-	*/
-	public private(set) lazy var visualLayer: CAShapeLayer = CAShapeLayer()

+     A CAShapeLayer used to manage elements that would be affected by
+     the clipToBounds property of the backing layer. For example, this
+     allows the dropshadow effect on the backing layer, while clipping
+     the image to a desired shape within the visualLayer.
+     */
+	open internal(set) var visualLayer: CAShapeLayer!

**Comment by danieldahan** [comment]
Nice catch :) I pushed a fix for you. Thank you.

**Comment by nthtrung09it** [comment]
And please **open class NavigationDrawerController** instead of **class NavigationDrawerController** for using subclass.

Greate library + Quick support. Thank you!

**Comment by danieldahan** [comment]
Updated NavigationDrawerController to be `open` :)
