### ISSUE TITLE
suggestion: move privacy-relevant functionality to a subspec, or wrap in a define..

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#511]
I just submitted my app and got this warning

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

I'm not using the camera, but some Material components can. Obviously as I'm not using them, I don't want to have to include them and try to explain to the app review team what is happening.

there are a couple of ways to easily disable these where not wanted:

1) use a compiler flag (similar to the extension safe method in my pull request https://github.com/CosmicMind/Material/pull/490 )

2) use a subspec - privacy relevant code would just be in material/camera (or whatever)

thanks!

**Comment by danieldahan** [comment]
Is this blocking you? I will launch a solution before the release.

**Comment by ConfusedVorlon** [comment]
I'm just manually removing the relevant files. 
It means that updating the pod is a pain - but it isn't a big deal.

thanks for checking.

**Comment by danieldahan** [comment]
Okay we will push a fix shortly for this :)

**Comment by danieldahan** [comment]
I added this item as a ToDo to the [Material Components](https://github.com/CosmicMind/Material/projects/1) project. Thanks for the suggestion.

**Comment by danieldahan** [comment]
Linking this to https://github.com/CosmicMind/Material/issues/549
