### ISSUE TITLE
[Development branch] How can i change pulse color of backButton & some issues

### ISSUE THREAD

**Issue by nthtrung09it** [CosmicMind/Material#512]
1) In master branch, I see backButton default pulse color is while, but when i switch to development branch, it was changed:

MASTER branch:
let backButton: IconButton = IconButton()
backButton.pulseColor = MaterialColor.white
backButton.setImage(v.backButtonImage, forState: .Normal)
backButton.setImage(v.backButtonImage, forState: .Highlighted)

DEVELOPMENT branch:
let backButton = IconButton(image: v.backButtonImage, tintColor: Color.blueGrey.base)

How can I change pulse color without modifying the source code?

2) Can you give an example about how to use NavigationController correctly: Add left controls, right controls, dynamic remove them, then re-add, then add them again.

Thank you.

**Comment by danieldahan** [comment]
I am stepping out for a bit, and I will send you answers very shortly. Thank you!

**Comment by danieldahan** [comment]
For the backButton, in the pushed view controller, use the `viewDidAppear` method to set the pulseColor. 

```swift
open override func viewDidAppear(_ animated: Bool) {
       super.viewDidAppear(animated)
       navigationItem.backButton?.pulseColor = Color.red.base
}
```

For the NavigationController, we are writing documentation that will be out soon and will show what you are looking for. 

:) feel free to message, or create another issue if you need any further help. 

Thank you!
