### ISSUE TITLE
Swift 3: @escaping may only be applied to parameters of function type

### ISSUE THREAD

**Issue by Spilly** [CosmicMind/Material#514]
Throughout the code the @escaping keyword is being used for specific closure parameters inside the completion handlers, instead of @escaping the function type itself. This is now a hard error and fails to compile.

**Comment by danieldahan** [comment]
awesome! I will fix this :)

**Comment by danieldahan** [comment]
This should now be updated in development :)

**Comment by cooler333** [comment]
How to fix?

**Comment by danieldahan** [comment]
Pull the latest from master, that should do it :)

**Comment by cooler333** [comment]
The question was: How can I fix it in my code? :)

**Comment by danieldahan** [comment]
Oh, you need to add @escaping before the function closure, Xcode should provide a suggestion, or you can share your code here.

**Comment by cooler333** [comment]
Question was about optional closure
 
You fix it by removing "@escaping": https://github.com/CosmicMind/Material/commit/770946589f842887efbdc04f89ef92b21793cba2

That's my code. I don't want to remove escaping.
```swift
class func show(withError error: MyError, completion: @escaping (() -> ())?) {

}
```

**Comment by danieldahan** [comment]
Well @escaping is only needed when your closure executes after the function returns. Is this the case?

**Comment by cooler333** [comment]
Yes, i'll pass it to another func(or set to property)

**Comment by danieldahan** [comment]
So the issue is probably that you have not defined that other function yet, so the compiler doesn't know what you are thinking of doing. So do not add the @escaping until you actually pass it to another function that is async.

**Comment by cooler333** [comment]
This is known swift 3 compiler [issue](http://stackoverflow.com/questions/39618803/swift-3-optional-escaping-closure-parameter)

I think you found some pretty workaround.

**Comment by SlonGL** [comment]
> class func show(withError error: MyError, completion: @escaping (() -> ())?) {

Optional completion is escaping anyway and doesn't need adding of "@escaping"
