### ISSUE TITLE
How to resolve Auto layout constraints 

### ISSUE THREAD

**Issue by umeshjavastar** [CosmicMind/Material#515]
I am unable to add multiplier, priority and Identifier in Layout constraints.
    `

    let parentView = UIView(frame: CGRect(x: 0, y: 0, width: 300, height: 500)) 
    let childView = UIView()
    parentView.layout.topLeft(childView, top: 50, left: 50)`

How to add multiplier, priority and Identifier in child view and also parent view

**Comment by danieldahan** [comment]
I will add this ability later today. Thank you!

**Comment by umeshjavastar** [comment]
Thanks for your anticipation,
I'm waiting for new update

**Comment by danieldahan** [comment]
Hey, I haven't had a chance to focus fully on updating Layout to potentially handle what you are looking for. I will update you shortly. Thank you!

**Comment by danieldahan** [comment]
So after playing with this for a while, I am going to suggest to write raw Constraints to achieve what you are looking for. The API into Layout is meant to be simple. Going in the direction you are asking will make it complex. All the best! :)
