### ISSUE TITLE
Detail label misplacement of TextField

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#517]
When I use the detail on a TextField, it's misplaced at first.
When I press the text field and start typing, it's move down below the divider.

1. Create a new project in XCode 8.
2. Add pod to the development branch to use Swift 3 version
3. Add a UITextField to the storyboard and add the TextField class
4. Add a placeholder
5. Add a detail
6. Run

Before I enter a value:
<img width="381" alt="skarmavbild 2016-09-14 kl 23 29 46" src="https://cloud.githubusercontent.com/assets/2380634/18531028/7ea02430-7ad4-11e6-9136-919baf303ac5.png">

After I enter a value:
<img width="385" alt="skarmavbild 2016-09-14 kl 23 30 06" src="https://cloud.githubusercontent.com/assets/2380634/18531029/7ea36438-7ad4-11e6-9ccb-9e1a554f17c4.png">

But as soon as I have entered a value, it stays at it's position.

**Comment by Flar49** [comment]
Just had the same issue. The problem was that i was assigning detail text directly to `field.detailLabel.text` and not via `field.detail`. 

I searched Material's source for the solution and found that after assigning `detail` `layoutDetailLabel` method is called: http://take.ms/kInSP
Apparently, it's not called after assigning string to `field.detailLabel.text` directly.

Replacing `field.detailLabel.text = value` with `field.detail = value` fixed the issue for me.

**Comment by sverin** [comment]
Does not work for me.

```
let field = TextField(frame: CGRect(x: 20, y: 50, width: 200, height: 25))
field.placeholder = "My label"
field.detail = "My detail label"
```

Tried both programatically and through storyboard.
 
The first attached imaged show how the field is display at startup.

<img width="231" alt="01" src="https://cloud.githubusercontent.com/assets/2380634/18649669/0c800dac-7ec1-11e6-9dbb-15ca271a80a3.png">

The second attachment how the field looks after focus on the field.

<img width="233" alt="02" src="https://cloud.githubusercontent.com/assets/2380634/18649670/0c82a0a8-7ec1-11e6-83a0-1df113d861d9.png">

And the last after I have entered a value.

<img width="231" alt="03" src="https://cloud.githubusercontent.com/assets/2380634/18649668/0c800492-7ec1-11e6-97c0-01dac491c695.png">

**Comment by btelintelo** [comment]
I have a similar issue in xcode 8 while using a stack view with text fields inside.  The top callout text doesnt cause the stack view to resize, so it just lays over top view above it.

**Comment by brokenworld** [comment]
I have same issue too in Xcode8. I can't fix by replace text option and place margin top, but I can resolve this problem below code.

Try to repositioning this code.
`view.layout(textField).top(originalTop).horizontally(left: mariginLeft right: marginRight)`

**Comment by danieldahan** [comment]
Thanks everyone for your input. I am looking at the TextField later this week before release in Material 2. I will get back to everyone with solutions and updates.

**Comment by danieldahan** [comment]
Working on this today before we release Material 2. Thank you!

**Comment by danieldahan** [comment]
When ready, would you be able to test the `development` branch for a fix to the issue. Thank you!

**Comment by sverin** [comment]
I updated to the latest development branch and it's all working fine now!
Looking forward to the official 2.0 release.

Thanks!

**Comment by danieldahan** [comment]
Sweet! Thank you :)
