### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by aizcheryz** [CosmicMind/Material#518]
Hi, please update it support for swift 3. Thanks.

**Comment by jbhav24** [comment]
This would be great

**Comment by chashmeetsingh** [comment]
Please check the development branch

**Comment by akashlazy** [comment]
not working development branch please help

**Comment by danieldahan** [comment]
By not working, what do you mean?

**Comment by sverin** [comment]
It works fine for me through cocoa pods.

pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'

**Comment by reidmain** [comment]
The development branch is working fine through Carthage as well. Any estimation as to when a formal Swift 3 release will occur?

**Comment by adamdahan** [comment]
@reidmain we are preparing the official release of Material 2 with Swift 3 support now. Very soon, hard date not set but sometime over the next week.

**Comment by reidmain** [comment]
@adamdahan excellent. Thank you very much for giving a timeline. I was planning on delving into our port in about two weeks to hopefully give all of our dependencies time to update.

**Comment by danieldahan** [comment]
I am closing this issue, and soon enough we will be releasing Material 2. Thank you!
