### ISSUE TITLE
UIView has no member 'Layout'

### ISSUE THREAD

**Issue by kingdana92** [CosmicMind/Material#522]
view.layout(containerView).edges(top: 100, left: 20, right: 20)

i cant seem to find the solution for this.

**Comment by danieldahan** [comment]
What version of Material are you using? And when was the last time you updated if you are using the `development` branch?

**Comment by kingdana92** [comment]
Hello Daniel,

version 1.0

i installed via cocoa pod (pod 'Material', '~> 1.0')

**Comment by danieldahan** [comment]
Can you confirm you are on version 1.42.9, if not on the development branch? Otherwise, the layout object doesn't even exist in version 1.0.

**Comment by kingdana92** [comment]
Im on version 1.41.6

here is the log from installation 

Analyzing dependencies
Downloading dependencies
Installing Material (1.41.6)
Generating Pods project
Integrating client project

**Comment by danieldahan** [comment]
Would you mind forcing 1.42.9? You can put that in the pod spec, and it should download that version for you.

**Comment by kingdana92** [comment]
This is what i received

[!] Unable to satisfy the following requirements:

- `Material (>= 1.42.9)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Material (>= 1.42.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by kingdana92** [comment]
This is my pod file

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'SearchBar' do
use_frameworks!

pod 'Material', '>= 1.42.9'

end

**Comment by kingdana92** [comment]
updated the repo and installing 1.42.9 now

**Comment by kingdana92** [comment]
Problem solver after updating to 1.42.9.

Thank you

**Comment by danieldahan** [comment]
Excellent!
