### ISSUE TITLE
suggestion: make Colors inherit from a shared structure

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#523]
this is a small thing - but would make my code slightly neater!

I like to define an extension with accent/primary, like this:

```
extension Color {
    static var  primary : Color.indigo.Type {
        return Color.indigo.self
    }
    
    static var  accent : Color.red.Type {
        return Color.red.self
    }
}
```

the duplication between the type and the return value is marginally annoying!

it would be somewhat neater if the colors had a shared inheritance and I could write the following

```
extension Color {
    static var  primary : Color
        return Color.indigo.self
    }
    
    static var  accent : Color {
        return Color.red.self
    }
}
```

(I'm not clear whether the 'self' would be required here or not)

**Comment by danieldahan** [comment]
I tried this

```swift
extension Color {
    static var primary: Color.indigo.Type {
        return Color.indigo.self
    }
    
    static var accent: Color.red.Type {
        return Color.red.self
    }
}
```

in an external project using Material and it worked fine. So what exactly is the issue that you are seeing? Sorry, I am not clear on this one. Thanks!

**Comment by ConfusedVorlon** [comment]
this is definitely a minor point, it is just feels like a slight code smell to have to change both the return type, and the return value  if you want to change a colour

so to go from red to blue, you need to go from

```
static var accent: Color.red.Type {
        return Color.red.self
    }
```

to

```
static var accent: Color.blue.Type {
        return Color.blue.self
    }
```

as opposed to

```
static var accent: Color {
        return Color.red.self
    }
```

to

```
static var accent: Color {
        return Color.blue.self
    }
```

as I said, not a big deal, but essentially we have the same behaviour in multiple structures, but without it being formalised through inheritance.

re the second option; It doesn't do the same job as you can't then use

`Color.primary.lighter`

**Comment by danieldahan** [comment]
Ahhh I get what you mean. Yes, we can make a Color type and then you can achieve what you are looking for. Cool, I'll add that :)

**Comment by danieldahan** [comment]
Made a fix for this, now you can do this

```swift
extension Color {
    static var primary: ColorPalette.Type {
        return Color.indigo.self
    }
    
    static var accent: ColorPalette.Type {
        return Color.red.self
    }
}
```

As well, the Color class is open and you can extend it alongside each ColorPalette class type.

**Comment by ConfusedVorlon** [comment]
thank you. My code will smell all the sweeter ;)
