### ISSUE TITLE
Some weirdness with Switch

### ISSUE THREAD

**Issue by alexander-larsson** [CosmicMind/Material#524]
I'm using the "Switch" component (Yes, I am on the development branch) in my app with Storyboards. In order to add it to your app the steps should be simple. 

1. Add UIView to Storyboard
2. Set the custom class to "Switch" and the module to "Material"

That does not work. The following message is printed in the console:

`2016-09-16 09:49:02.229 MyApp[10266:789088] Unknown class _TtC8Material6Switch in Interface Builder file.`

In the file Material-Swift.h this can be found:

```
SWIFT_CLASS_NAMED("Switch")
@interface Switch : UIControl
```

So I think the  problem here is that there is a mismatch in names but I'm not quite sure why this happens or where the name "_TtC8Material6Switch" comes from.

Lastly, It works just fine if i don't set the Module to "Material" which is not the case with the other components I have used. Those won't work at all if I don't set module to "Material"

What is going on here?

**Comment by danieldahan** [comment]
The MaterialSwitch example is from version 1.*, which means that the name is not the same. Before it was MaterialSwitch and now it is Switch. You should be able to see examples in that project of how to use the Switch programmatically. The interface is the same, only the name has changed. As for your storyboards issues, I would need to see a sample of what you are doing.

All the best,

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by alexander-larsson** [comment]
I only perform step 1 and 2 above. Nothing else. It seems like it is still called MaterialSwitch according to IB but not in the actual Swift classes or something.  The file Material-Swift.h seems to have something to do with this. I am NOT using any examples.

The thing is I can use it, it does work, I just give it a class of Switch and NO module in IB. That should not work, but it does.

I have built Material with Carthage from the development branch and added the .framework to the project.

**Comment by danieldahan** [comment]
Can you clean your build folder and delete the UserDerived data ? I will take a look and see if something else comes up.

**Comment by danieldahan** [comment]
I haven't heard back from you, so I am closing this issue, and if you continue to face an issue, please reopen or create a new GitHub issue. Thank you!
