### ISSUE TITLE
support for swift 3

### ISSUE THREAD

**Issue by hisham2007** [CosmicMind/Material#525]
Thanks for great effort.

Apple just released official xcode 10.  when I add 
pod 'Material', '~> 1.0'

I face many compilation errors with swift 3

**Comment by chashmeetsingh** [comment]
try
`pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'`

**Comment by danieldahan** [comment]
Yes, the development branch is where Swift 3 support is currently. It is only on development as we make our final revisions for Material 2 and Swift 3. Please follow along here [520](https://github.com/CosmicMind/Material/issues/520).
