### ISSUE TITLE
textAlignment switch in navigationItem

### ISSUE THREAD

**Issue by nthtrung09it** [CosmicMind/Material#526]
Hello, I have a problem but I don't know to resolve it.
I have a navigation item, and want to show choice mode if a item in UITableView is selected.
Default navigationItem title alignment in normal mode is .left, and in choice mode is .center

-- navigationItem title textAligment LEFT in normal mode and choice mode --
NavigationItem in normal mode:
![image](https://cloud.githubusercontent.com/assets/7716509/18605516/1954480e-7cbe-11e6-95b1-0fdaede67f78.png)

Navigation in choice mode:
![image](https://cloud.githubusercontent.com/assets/7716509/18605523/2c9267de-7cbe-11e6-91b8-dda26f9421a6.png)

-- navigationItem title textAligment LEFT in normal mode and CENTER in choice mode --
![image](https://cloud.githubusercontent.com/assets/7716509/18605530/4fb7d60e-7cbe-11e6-84ba-8c3a732ef36f.png)

![image](https://cloud.githubusercontent.com/assets/7716509/18605531/52dadc8c-7cbe-11e6-9ac9-88536cac98c4.png)

Demo project:
https://github.com/nthtrung09it/HelloMaterial
Comment/ uncomment line 35 and 64 to see this bug.

Thank you so much :)

**Comment by danieldahan** [comment]
What version of Material are you using? This was fixed in Material 2 on the development branch with Swift 3 support.

**Comment by nthtrung09it** [comment]
I'm using Material 2 on the development branch.
If you have time, take a look at:
https://github.com/nthtrung09it/HelloMaterial
Comment/ uncomment line 35 and 64 to see this bug.

Thank you!

**Comment by nthtrung09it** [comment]
How can I fix this problem?

**Comment by danieldahan** [comment]
Hey! 

Excellent find :)

I pushed a fix to development. So you only need to update from CocoaPods. 

Thanks again!

<img width="372" alt="screen shot 2016-09-20 at 1 20 11 pm" src="https://cloud.githubusercontent.com/assets/9982123/18687440/04a3f80e-7f35-11e6-97b3-e6053455052b.png">
<img width="390" alt="screen shot 2016-09-20 at 1 20 54 pm" src="https://cloud.githubusercontent.com/assets/9982123/18687454/165e9680-7f35-11e6-8052-615ea60a5bee.png">
<img width="400" alt="screen shot 2016-09-20 at 1 21 12 pm" src="https://cloud.githubusercontent.com/assets/9982123/18687468/1eb60a34-7f35-11e6-871f-a58a8434fbb4.png">

**Comment by nthtrung09it** [comment]
Yes, It works 👍 Thank you!
