### ISSUE TITLE
Material Swift 3 Issue

### ISSUE THREAD

**Issue by siryu8888** [CosmicMind/Material#527]
I have some issue about material, 
<img width="336" alt="screen shot 2016-09-17 at 10 17 06" src="https://cloud.githubusercontent.com/assets/12934177/18605593/ff4e75d6-7cbf-11e6-91f9-51cdb0662db8.png">

any help about this?? Thx in advance...

**Comment by chashmeetsingh** [comment]
Try the development branch

**Comment by danieldahan** [comment]
Yes, you need to use the `development` branch for Swift 3 at the moment, which is also the Material 2 branch. This will be officially released on the 30th of September. Thank you!

**Comment by siryu8888** [comment]
Ok.. thx for info
