### ISSUE TITLE
Add @discardableResult to Layout helper

### ISSUE THREAD

**Issue by mohpor** [CosmicMind/Material#528]
As per [SE-0047](https://github.com/apple/swift-evolution/blob/master/proposals/0047-nonvoid-warn.md) (implemented in Swift 3.0), `@warn_unused_result` is default for non-void functions. 

`Layout` functions return `Layout` for chaining purposes and should add `@discardableResult` to them to prevent unwanted warnings about their results not being used.

**Comment by danieldahan** [comment]
Fixed :) in the `development` branch! Thanks for this.
