### ISSUE TITLE
Button with text "Done" will be clipped

### ISSUE THREAD

**Issue by tiennth** [CosmicMind/Material#530]
I don't know if there are any specials with button "Done".

If I create a MaterialButton with text "Done", that button's text will be clipped.

![clipped](https://cloud.githubusercontent.com/assets/3277692/18923921/62f1a862-85d8-11e6-9c6e-ab19fbd90f5b.png)

If I change the text to other string like "Next" or "Done " or " Done" (add a space before or after Done), there will be no problem.

![np](https://cloud.githubusercontent.com/assets/3277692/18923922/65510aa8-85d8-11e6-8a28-5dc909194a28.png)

**Here is what I did:**
```
let nextButton = MaterialButton()
        nextButton.pulseColor = MaterialColor.blue.lighten1
        nextButton.setTitleColor(MaterialColor.blue.base, forState: .Normal)
        nextButton.setTitle("Done", forState: .Normal)
        nextButton.addTarget(self, action: #selector(nextButtonDidClick(_:)), forControlEvents: .TouchUpInside)
        navigationItem.rightControls = [ nextButton ]
```

**Comment by danieldahan** [comment]
Hey, what version of Material are you using?

**Comment by danieldahan** [comment]
I believe this is fixed in Material 2 that launches in the next couple days and is currently in the development branch.

**Comment by tiennth** [comment]
I'm using the latest version installed by cocoa pods:
`pod 'Material'`

**Comment by danieldahan** [comment]
Okay, you will need to use the `development` branch, or wait until the 30th of September for Material 2s release :)
