### ISSUE TITLE
Development branch log message

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#531]
objc[3200]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11bc51910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11ba7b210). One of the two will be used. Which one is undefined.

**Comment by chashmeetsingh** [comment]
@danieldahan How to resolve this ?

**Comment by danieldahan** [comment]
I am not sure, has this issue been isolated to Material ?

**Comment by danieldahan** [comment]
Further more, I will need reproducible steps.

**Comment by chashmeetsingh** [comment]
I thought it's material because of photolibrary involvement

**Comment by danieldahan** [comment]
It could be, but I would need reproducible steps. Are you trying to use PhotoLibrary ?

**Comment by chashmeetsingh** [comment]
I can share the projects GitHub url. 
No not even using it 
https://github.com/chashmeetsingh/Track-My-Shows-iOS

**Comment by danieldahan** [comment]
I wont have time to look immediately, and if you are not using PhotoLibrary, it shouldn't affect anything. I will try and look soon :)
