### ISSUE TITLE
suggestion: make it possible to render the placeholder labelat the top from the beginning

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#534]
Is there a way for the placeholder label of TextField to be rendered at the top from the beginning?
I don't want it to be animated when I focus on the textfield and it's empty.

**Comment by danieldahan** [comment]
Hey! Pull the latest, [2.1.0](https://github.com/CosmicMind/Material/releases/tag/2.1.0) and set the TextField's `isPlaceholderAnimated` property to false. That should create the effect you are looking for. Thanks and all the best!
