### ISSUE TITLE
Is Material protocolable?

### ISSUE THREAD

**Issue by zbangsatz** [CosmicMind/Material#535]
If I want to mix Material TextField with https://github.com/bkook/BKMoneyKit or something else I need to write my new. It's not quite comfortable.
My suggestion is make Material UI to something like "Protocol-Oriented Programming". I think it's really nice and easy compare with others. 
Resource https://realm.io/news/doios-natasha-murashev-protocol-oriented-mvvm/

**Comment by danieldahan** [comment]
Great suggestion :) Yes, I am familiar with Protocol Orientation. I'll give the framework a pass and see if and where possible to add this style. Protocols have their own limitations, so as long as it is possible, we will make it work. All the best!
