### ISSUE TITLE
Problem compiling material with swift 3

### ISSUE THREAD

**Issue by tarek903** [CosmicMind/Material#536]
i tried migrating assistant but still tons of errors am i doing something wrong or its not supported by swift 3 ?
thanks in advance

![screen shot 2016-10-03 at 1 30 42 pm](https://cloud.githubusercontent.com/assets/11038057/19034706/ac00d972-896d-11e6-951e-004df90a9834.png)

**Comment by kiwo12345** [comment]
I got the same error

**Comment by kiwo12345** [comment]
@tarek903 I got it working by using:
**pod 'Material', :git => 'https://github.com/CosmicMind/Material', :branch => 'development'**

**Comment by danieldahan** [comment]
You are using version 1.42.9, which is not supported. You need to use 2.1.0, which is now officially released in master. So install the latest from master, and you should be good :)

**Comment by kiwo12345** [comment]
@danieldahan I just tested with pod **'Material', '~> 1.0'** and got the same errors, then I used **pod 'Material', :git => 'https://github.com/CosmicMind/Material', :branch => 'development'**

And now it works :)

**Comment by danieldahan** [comment]
Switch to 'Material', '~> 2.0'

**Comment by kiwo12345** [comment]
@danieldahan My bad, I took the version from the docs/installation guide

**Comment by danieldahan** [comment]
@kiwo12345 Actually that is my bad, I need to update that. Thank you!

**Comment by Dmurph24** [comment]
@danieldahan  Is swift 3 support for this repo yet? I tried both master and development and errors tell me to use a legacy version of swift.

**Comment by danieldahan** [comment]
Yes, swift 3 is very much supported. If you are using CocoaPods, you may have to manually set the legacy flag to No.

**Comment by Dmurph24** [comment]
Awesome thanks, I got it to work. If you have legacy swift 3 build error you can add this to the end of your podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by danieldahan** [comment]
Awesome!!! Thank you :)
