### ISSUE TITLE
trigger snackBar with button click

### ISSUE THREAD

**Issue by chashmeetsingh** [CosmicMind/Material#538]
How do we trigger the snack bar as many times a button is pressed. I tried but didn't seem to work.

```
private func prepareSnackbar() {
        guard let sc = snackbarController else {
            return
        }
        
        sc.snackbar.text = "Reminder saved."
    }
    
    private func animateSnackbar() {
        guard let sc = snackbarController else {
            return
        }
        
        _ = sc.animate(snackbar: .visible, delay: 1)
        _ = sc.animate(snackbar: .hidden, delay: 4)
    }

    @IBAction func action(_ sender: AnyObject) {
        prepareSnackbar()
        animateSnackbar()
    }
```

**Comment by danieldahan** [comment]
Well you have a delay on the animation `_ = sc.animate(snackbar: .visible, delay: 1)` so you cannot click the button many times and then queue the animation. You have to wait until the animation plays out. If you want to do it as many times as you click, then keep a queue, and then cycle through the queue to trigger your function to call the animations. 

All the best :)
