### ISSUE TITLE
Trigger show NavigationDrawer with UIButton

### ISSUE THREAD

**Issue by devcaststudio** [CosmicMind/Material#539]
Hi, 

i'm trying to show Left or RIght Navigation Drawer with button but i dont know how to use that, i'm adding button in navigation Bar, please share how to make that :)

**Comment by danieldahan** [comment]
Hello, 

From any view controller, you can access the `navigationDrawerController` optional property. So you could add to a button handler the ability to toggle the Left or Right drawer by doing this:

```swift
func handleButton(button: UIButton) {
    navigationDrawerController?.openLeftView()
    navigationDrawerController?.toggleLeftView()
    navigationDrawerController?.closeLeftView()

    navigationDrawerController?.openRightView()
    navigationDrawerController?.toggleRightView()
    navigationDrawerController?.closeRightView()
}
```

And that's it :)
