### ISSUE TITLE
Incorrect display for placeholder text if leftView

### ISSUE THREAD

**Issue by MGStudio** [CosmicMind/Material#541]
Hello ! 
Nice job for the library, I needed to add au leftView to my textfield and when I did I realize that the placeholder view simply ignored the left view. I'm looking for a solution to move the placeholder like this it will avoid the intersection with the left view.

I will subclass textfield and come back when I will have a solution.

**Comment by MGStudio** [comment]
I have a fix, I will create a pull request soon.

**Comment by danieldahan** [comment]
Great! Looking forward to it :)

**Comment by danieldahan** [comment]
I await your PR, closing the issue for now. Thank you!

**Comment by okankocyigit** [comment]
waiting for pr, thanks.
