### ISSUE TITLE
Feature discovery: Tap Target

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#542]
Hello @danieldahan ,
First congrats on your big release! I'd like to see this feature added to your library, it should be awesome! 😄
To check the specs of it, you can check this [Google's Material Design guidelines on feature discovery](https://material.google.com/growth-communications/feature-discovery.html#feature-discovery-design)
And here's how it looks before you check the link:
![useredu_er_featuredisc_design_01](https://cloud.githubusercontent.com/assets/2195533/19188259/3b4fb43a-8c99-11e6-84e0-27bacfb7f364.png)

**Comment by danieldahan** [comment]
@sohayb Thank you :)

I added this feature request to the [Material Project](https://github.com/CosmicMind/Material/projects/1?fullscreen=true). I think this would be a great addition.

**Comment by sohayb** [comment]
Thx a lot!

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
