### ISSUE TITLE
Come up with a solution to organize Privacy type features (Camera, Micrphone, Reminders).

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#549]

**Comment by ConfusedVorlon** [comment]
fwiw - I think subspecs would be neater than using defines.

the interface for defines is just ugly in xcode/swift

by comparison, subspecs would be really easy - and simple to document.

**Comment by danieldahan** [comment]
Yeah I fully agree. Would you be able to PR this change?

**Comment by ConfusedVorlon** [comment]
I don't have any spare time at the moment. Sorry.

**Comment by danieldahan** [comment]
Cool, then eventually I shall get to this, it is on the radar.

**Comment by danieldahan** [comment]
https://github.com/CosmicMind/Material/pull/564

**Comment by reidmain** [comment]
Would you like me to open up an issue for how people who are using Carthage do not have the ability to not include features that would trigger privacy warnings?

I understand it is a complex problem with manually created framework targets but I just want to get the team's official opinion on how they would like people to handle it.

At this point in time I am looking at removing Material as a Carthage dependency and manually copying in files but this obviously doesn't scale and is going to have problems in the future for rewrites (like Swift 4 for example).

**Comment by danieldahan** [comment]
@reidmain Yes please. This is a good issue to have on the board and to tackle. Thank you!

**Comment by reidmain** [comment]
Done https://github.com/CosmicMind/Material/issues/580
