### ISSUE TITLE
Issue displaying more then 6 Buttons in PageTabBarController

### ISSUE THREAD

**Issue by DennisNehrenheim** [CosmicMind/Material#551]
When I add more than 6 buttons to the tabBar there is an display issue: 
![image](https://cloud.githubusercontent.com/assets/19328249/19380890/8af0b7e0-91f9-11e6-9bbb-71f707a66a80.png)
whereas with 6 buttons everything works fine:
![image](https://cloud.githubusercontent.com/assets/19328249/19380979/f3eafb0c-91f9-11e6-8738-6c0ae9f80d84.png)
In Landscape the error exists to:
![image](https://cloud.githubusercontent.com/assets/19328249/19380928/bfcea7c4-91f9-11e6-9ffa-2f9bf411cb41.png)
whereas with 6 buttons:
![image](https://cloud.githubusercontent.com/assets/19328249/19381015/0cd30452-91fa-11e6-9878-3384334b0916.png)
Best Regrads

**Comment by danieldahan** [comment]
Very interesting, I'll take a look :) thank you

**Comment by DennisNehrenheim** [comment]
It would be nice to solve this by using a scrollable PageTabBar. Is such a feature planned for future releases?

**Comment by danieldahan** [comment]
I verified this issue, thank you for bringing it to our attention. I also like the feature request, and will see if I can add it while fixing this, if not, I will make it a standalone feature request for the very near future.

**Comment by danieldahan** [comment]
Hey I will be looking at this later today :)

**Comment by danieldahan** [comment]
Linking this issue https://github.com/CosmicMind/Samples/issues/7

**Comment by danieldahan** [comment]
I will be reworking this all tomorrow. Sorry for any delays.

**Comment by danieldahan** [comment]
I will be reworking this all tomorrow. Sorry for any delays.

**Comment by danieldahan** [comment]
Sorry the delay. Finally had a chance to fix the issue. I will be posting an update later today. Thank you!

**Comment by danieldahan** [comment]
Please update to [Material 2.4.0](https://github.com/CosmicMind/Material/releases/tag/2.4.0) for a solution to this issue :)

**Comment by apemobilu** [comment]
Hi Daniel,

Any news about making the PageTabBar scrollable when there is a lot of buttons?
I would find that feature really interesting.

Thanks

**Comment by danieldahan** [comment]
@apemobilu Yeah, I am currently working on it within in an App I am building. Once ready, which should be soon I will release it :)

**Comment by thuca1992** [comment]
@danieldahan 
Please release it soon, I really need it as soon as possible.
Thank you so much

**Comment by danieldahan** [comment]
No worries, tonight I a working on Samples and features :) Thanks for your patience.

**Comment by danieldahan** [comment]
Feature Request to make TabBar scrollable: https://github.com/CosmicMind/Material/issues/642
