### ISSUE TITLE
Weird left view behavior on NavigationDrawerController

### ISSUE THREAD

**Issue by duyduong** [CosmicMind/Material#553]
Hi, 

I would like to report a bug. It is seemed that the side view on NavigationDrawerController is taking the full width of the device. Please see details below:

![image](https://cloud.githubusercontent.com/assets/450564/19395623/b9fe523a-9268-11e6-9b56-9101225e92e0.png)
In this image, View should be your leftView and it got correct frame size (320x1024)

![image](https://cloud.githubusercontent.com/assets/450564/19395600/9d503d92-9268-11e6-9aa8-f30b42b31687.png)
In this image, UIView should be the view from my menu view controller. It got correct frame size (320x104). But the width constraint is wrong (self.width = 768 @ 1000). I think this is because of the auto translate resizing mask into constraints

![image](https://cloud.githubusercontent.com/assets/450564/19395720/3d058acc-9269-11e6-8ed9-f7763b9ee8ea.png)
Then it made my table view inside my menu view controller completely full width of the device

My testing device is iPad Air 2, iOS 9.3.5

Thanks

**Comment by danieldahan** [comment]
Excellent, thank you. I will investigate this today.

**Comment by danieldahan** [comment]
I looked into this. I am not able to reproduce the issue. What version of Material are you using? Can you send me your project or a sample so I can investigate further? Thank you!

**Comment by danieldahan** [comment]
Hey! I cannot reproduce this issue and I haven't heard back from you. Please reopen or create a new issue if this persists, thank you :)

**Comment by lutzj82** [comment]
I too am getting this.  I have a tableview inside the view that represents the Left view. I am using autolayout and if i set the width constraint of the tableview equal to the width of the parent view it takes up the entire width of the screen. I am using 2.2.5 of Material

**Comment by danieldahan** [comment]
@lutzj82 Can you send a sample project to support@cosmicmind.com?

**Comment by lutzj82** [comment]
I've got a sample project up now where I can't duplicate it :(
I'm trying to go over the differences between the two projects to see why I'm getting an actual width that is greater than the left view width.

**Comment by lutzj82** [comment]
Ok, I think I've identified the problem.
If the view controller is hosted using storyboards and not programmatically, I am getting the issue in regards to height and width. The view frame is being resized when it is done using storyboards where it is not happening when loading programmatically. @danieldahan, I've sent you the sample project.

**Comment by danieldahan** [comment]
Yes, this makes sense. I will look this over and make an update :)

**Comment by danieldahan** [comment]
Hey, please give [Material 2.3.19](https://github.com/CosmicMind/Material/releases/tag/2.3.19) a try. I believe it may fix this issue. Thank you :)
