### ISSUE TITLE
How to dynamically set TableViewCell with Cards

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#554]
StackOverflow Question: 

http://stackoverflow.com/questions/39800349/how-to-set-get-table-cell-height-dynamically-using-cosmicmind-material-framework?noredirect=1#comment67401191_39800349

**Comment by hisham2007** [comment]
Many thanks :)

**Comment by danieldahan** [comment]
No worries. If you take a look here [Material Project](https://github.com/CosmicMind/Material/projects/1) you can see what I am working on.

**Comment by danieldahan** [comment]
@hisham2007 does this need to be a TableViewCell, or could you use a CollectionViewCell ?

**Comment by hisham2007** [comment]
table view cell

**Comment by danieldahan** [comment]
Okay, cool, thank you!

**Comment by danieldahan** [comment]
I will be working on this today :)

**Comment by danieldahan** [comment]
Hey! I am almost done the example. I have a prototype of the idea here: https://github.com/CosmicMind/Graph/tree/development/Examples/DynamicCardTableViewCell. Tomorrow I will polish it off and make it look really nice :) The concepts may change, so don't get too fixated on this initial pass.

**Comment by hisham2007** [comment]
many thanks for your big support

**Comment by danieldahan** [comment]
Hey, I started a samples project repository where I will make samples based on requests and needs. Here is your issue https://github.com/CosmicMind/Samples/issues/2 :) We can chat there.

**Comment by hisham2007** [comment]
Many thanks. I will try it in weekend and feedback you there
