### ISSUE TITLE
Components – Menus (Feature request)

### ISSUE THREAD

**Issue by aemgtz** [CosmicMind/Material#555]
I needs control like menus in iOS
https://material.google.com/components/menus.html#
This components is appeared in Duo for iOS.
It would be great If Material provide this kind of control.

Thanks

**Comment by danieldahan** [comment]
Yes it would. I will add this to the Feature Request column in the [Material Project](https://github.com/CosmicMind/Material/projects/1). Thank you!

**Comment by danieldahan** [comment]
Working on this today :)

**Comment by danieldahan** [comment]
I will be reworking the Menu into a Menu, FABMenu, ToolbarMenu, and others.

**Comment by danieldahan** [comment]
This has been added, and will be released in Material 2.5.0. Thank you!
