### ISSUE TITLE
Black content area after converting App from Material 1 to Material 2

### ISSUE THREAD

**Issue by robcecil** [CosmicMind/Material#557]
My app's view architecture was initially modeled after the old Material 1.x "App" programmatic example. I just recently converted to Swift3/Xcode8 and Material 2.1.0. Now I'm getting a strange behavior where all the views disappear and I get a black content area. When I examine the view hierarchy in Xcode either there is a single view, or I get a message about the view hierarchy not being available. I have narrowed a repro down to a simple app that uses Material and replicates the components in my main app.

I'm not sure if the problem lies in Material (a Material bug), my usage of Material, or a bug elsewhere.

There are two ways to operate the repro - as-is it will present a modal dialog, clicking the [Close] will dismiss the viewcontroller, and you get the black content, and the views will disappear. If you remove the code in the Nav controller's ViewDidAppear that launches the modal viewcontroller, you see the black content immediately.

[Material2Repro.txt](https://github.com/CosmicMind/Material/files/537851/Material2Repro.txt)

**Comment by danieldahan** [comment]
I will follow your steps to reproduce.

**Comment by danieldahan** [comment]
So the issue is in your `AppDelegate`

There is a class level property `var window: UIWindow?`

and in your `app didFinish...` method you are not actually setting it. 

```swift
let window = UIWindow(frame: Device.bounds)
window.rootViewController = navigationDrawerController
window.makeKeyAndVisible()
```

It should be:

```swift
window = UIWindow(frame: Device.bounds)
window!.rootViewController = navigationDrawerController
window!.makeKeyAndVisible()
```

Because you have `let window` in your code, you are never accessing the class level `window` property. 

:) All the best!

**Comment by robcecil** [comment]
Thanks Daniel. Must have stared at that several times during the conversion and never caught it.

**Comment by danieldahan** [comment]
No worries :) Glad you reached out.
