### ISSUE TITLE
How do I set a divider on a Card in Material 2?

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Material#558]
Before: cardView.divider = true

How do I add a divider now, in Material 2?

The divider on Card is not settable.

**Comment by danieldahan** [comment]
The divider is now a `Divider` object. This gives it features independently from the card. Actually any view now has the ability to access a divider. To use the Divider it needs a color to be seen. These are the properties you can set directly from any view:

```swift
view.dividerColor = Color.grey.lighten3
view.dividerAlignment = .top
view.dividerThickness = 3
```

You can access the `Divider` object directly using the `view.divider` property. 

I will be adding to the available properties, in the next release Material 2.2.1: 

```swift
view.dividerContentEdgeInsets = .zero
view.dividerContentEdgeInsetsPreset = .square1
```

If you want to access the above properties currently, you need to do it through the `view.divider` property: 

```swift
view.divider.contentEdgeInsets = .zero
view.divider.contentEdgeInsetsPreset = .square1
```

That's about it :)

**Comment by theolof** [comment]
awesome, thanks!
