### ISSUE TITLE
Support for Swift 2.3

### ISSUE THREAD

**Issue by aleufms** [CosmicMind/Material#559]
Is there no support for swift 2.3?

**Comment by danieldahan** [comment]
Yes, use the swift-2.3 branch :)

**Comment by mxia** [comment]
The swift-2.3 branch doesn't appear to exist any more. Is there a tagged version we could check out that works for Swift 2.3?  Thanks!

**Comment by danieldahan** [comment]
@mxia That branch has gotten very far behind and was not supported. So I removed it in favour of only leaving branches that are supported.

**Comment by danielneri** [comment]
@danieldahan what options do we have if we're not ready to upgrade to Swift 3?

**Comment by danieldahan** [comment]
@danielneri there really isn't another option. Material will be expanding a lot this month with new features. At this point only Swift 3 will be realistic to maintain.

**Comment by danielneri** [comment]
I don't think this is a good option for people that have adopted the
library and aren't ready to migrate to Swift 3.

Personally this was motivation enough to migrate, but I have a medium sized
app that will take me a good 10-20 hours to migrate - I can't imagine a
more enterprise sized app.

Can you bring back that old branch if possible so people aren't forced to
migrate?

**Comment by danieldahan** [comment]
Well there is a few ways to think about this. 

1. Material 2.3 is far behind and therefor not a correct representation of the library. 
2. Your 10 - 20 hours to migrate, or my months of maintenance on an old version of the library. I think the 10 - 20 hours is an easier task and you will be progressing at the rate I do. 
3. I never created the 2.3 branch. It was done by a community member that did not maintain it. 
4. Material is maintained by myself, so unless I have more help, and maybe you are suggesting you want to help, I will need to do it as I see fit at the end of the day.
