### ISSUE TITLE
Please Add Date And Time PickerView

### ISSUE THREAD

**Issue by satishVekariya** [CosmicMind/Material#560]

**Comment by danieldahan** [comment]
Yes, this is in the pipeline :) I will leave it up as a `feature request`.

**Comment by satishVekariya** [comment]
Thanks

**Comment by satishVekariya** [comment]
thnx

**Comment by danieldahan** [comment]
https://github.com/CosmicMind/Material/issues/1010

**Comment by adamdahan** [comment]
@danieldahan @OrkhanAlikhanov Is it possible we start working on this feature? @OrkhanAlikhanov seems to want to take the lead on it. I am glad to contribute as well. We most likely will need to settle on design first.

**Comment by danieldahan** [comment]
This would be incredible to work on. I am in.

**Comment by Recouse** [comment]
Here is an implementation in swift https://github.com/weilsonwonder/WWCalendarTimeSelector

**Comment by danieldahan** [comment]
Thank you @Recouse :)

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
