### ISSUE TITLE
Issue using light content statusBarStyle

### ISSUE THREAD

**Issue by despisedIcon** [CosmicMind/Material#562]
As in the ToolbarController project example I'm setting status bar style and color with the following:

```
private func prepareStatusBar() {
        statusBarStyle = .lightContent
        statusBar.backgroundColor = Color.blue.darken3
}
```

The backgroundColor gets set correctly, but the status bar text remains black.
Is this a bug or is it possibly being overwritten somewhere else? Do you know whether storyboard properties could be causing this?

Cheers

**Comment by danieldahan** [comment]
Hey! I think you are missing a value in your `info.plist` file. You need to set the `View controller-based status bar appearance` to `NO`. 

:)

**Comment by despisedIcon** [comment]
Thank you!
