### ISSUE TITLE
Recommended Implementation: CardView with dynamic number of subViews 

### ISSUE THREAD

**Issue by DennisNehrenheim** [CosmicMind/Material#569]
Do you have a recommendation regarding such an implementation:
![mockup](https://cloud.githubusercontent.com/assets/19328249/19765005/638eb8ee-9c46-11e6-97e9-491ad27dc4ea.png)
I need to have grouped sections in a Material Card Layout. 
The sections include a variable number of cells. 
The cells per section are not fix and they can differ like shown in the picture. Some will have switches, some textfields,...

**Comment by danieldahan** [comment]
Yes, I can make a suggestion, which version of Material are you using ?

**Comment by DennisNehrenheim** [comment]
Version 2.0

**Comment by danieldahan** [comment]
Excellent. So in the latest version there are few things to consider. Each card has a structure that includes an area that can be any UIView. In the `Card` and `ImageCard`, it is known as the `contentView` and in the `PresenterCard` there are two areas, `presenterView` and `contentView`. 

All the cards then have a common `Toolbar` that adjusts to the layout and bottom `Bar` type that is always at the bottom.

What I think you can do, based on the first card I see, is use a general `Card`. The "Section 1" title would be your `card.toolbar?.title`. The form input area will be in the `contentView` and you should make a layout in a UIView that contains all the subviews in the format you are showing. You can set that container view to the `contentView` property. 

The last part, will be allocated to the `card.bottomBar?.centerViews`. You can set another view, or button, which will expand the full area and give that center alignment. You will probably want to set the `card.bottomBarContentEdgeInsets` and `card.bottomBar?.contentEdgeInsets` to eliminate any spacing that you don't want, or to add any spacing that you do want around the `centerViews`. 

There is an example that comes out on Monday, latest Tuesday that shows how to dynamically size the `Card` types in a `UITableView` in a data-driven way. Check it out [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView). Feel free to continue the dialog here, or open a new issue, or chat on [Gitter](https://gitter.im/CosmicMind/Material) for more help :)
