### ISSUE TITLE
[Textfield] Can I set divider active color?

### ISSUE THREAD

**Issue by babatimmai** [CosmicMind/Material#572]
I use Textfield material, and I want to set my divider color for active state but now I can't.
Can you help me?

Thank you so much,

**Comment by danieldahan** [comment]
Hey, yes, I can help. Here is some sample code that shows properties you can set to change the color states.

```swift
emailField.placeholderNormalColor = Color.amber.darken4
emailField.placeholderActiveColor = Color.pink.base
emailField.dividerNormalColor = Color.cyan.base
emailField.dividerActiveColor = Color.green.base
```

All the best :)
