### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by hamedmohammadi** [CosmicMind/Material#575]
first of all thank to you for making this useful and brilliant project .
i want to know , how can we use this project for rtl language .i looked at your codes and it is not made with constraints and so it is big problem i think for rtl support .
can i ask why not using constraints ?
is there any way to achieve  rtl material design  using this project?

**Comment by danieldahan** [comment]
Thank you :) 

I am putting this as a feature request on high priority.

**Comment by hamedmohammadi** [comment]
thanks a lot bro.
i don't have time till next month but i will try to join you as soon as possible.

**Comment by danieldahan** [comment]
No worries. So you know, the way I am building Material is in layers. I try and solidify each stage of the framework to ensure that when I add more, it has stable foundations. So RTL is a great next step.

**Comment by tarek903** [comment]
@danieldahan  will RTL support be available for 2.5.0 update?

**Comment by danieldahan** [comment]
@tarek903 I may be able to squeeze it in as I work on `Editor (TextView)`.

**Comment by PrabhuBhosale25** [comment]
what is expected release for this feature?

**Comment by vimalrick** [comment]
Thanks for the great Material library. 
Could you please update when we can expect the release of RTL support?

**Comment by danieldahan** [comment]
I am going to release a roadmap once I finish the documentation and release for Motion and Material. I will comment on all open feature requests soon. Thank you!

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
