### ISSUE TITLE
Menu View transitioning issue (swift 3 )

### ISSUE THREAD

**Issue by gristoi** [CosmicMind/Material#577]
Hi, i am trying to absorb the great library you guys have built here, but ive hit a bit of a wall. Its either because im not transitioning properly or there is a bug. Im hoping its the first option.

So i followed your programatic sample for menu view, and amended it slightly to use storyboard, so the App Delegate looks like this:

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let rootVC = storyboard.instantiateViewController(withIdentifier: "RootViewController")
        self.window?.rootViewController = AppMenuController(rootViewController: rootVC)
        self.window?.makeKeyAndVisible()
        return true
    }`

The root view controller is like the example, except its from storyboard. In prepareMenuController i add 

`mc.transition(to: self.storyboard?.instantiateViewController(withIdentifier: "NewViewController") as! NewViewController)`

and it loads with the new ViewController. The problem is that the Menu is now stuck in a layer behind the new View Controller:

![screen shot 2016-11-03 at 19 01 42](https://cloud.githubusercontent.com/assets/1233206/19981025/17ac163a-a1f8-11e6-88af-bd8094b208ba.png)

![screen shot 2016-11-03 at 18 56 54](https://cloud.githubusercontent.com/assets/1233206/19980975/eb6c8672-a1f7-11e6-849d-b52620c39c93.png)

is it something stupid that i am doing?

**Comment by danieldahan** [comment]
Hey!

I found storyboards to behave interestingly in some cases. Though, I have never seen this. 
I pushed a potential fix to `development`, could you try the `development` branch?

If that doesn't work, then please send a sample to support@cosmicmind.com so I can assess further. 

Thank you for bringing this to our attention :)

**Comment by gristoi** [comment]
sure!, I'll give it a go today

**Comment by gristoi** [comment]
Hi dan, I gave it a whirl, and see you moved the transistioned vied to the background, which seems to have worked :)

But the menu now does not work when tapped on. I have popped my demo onto my github for you to show the issue, I hope it helps, and anything i can do to help let me know

https://github.com/gristoi/sight-marker

thanks 
Ian

**Comment by danieldahan** [comment]
@gristoi Yes, the issue there is that your `RootViewController` had the handler set, and now you have a `NewViewController`, so now your handler is not available any longer. This is where you can leverage the `AppMenuController` to put in base code that is shared amongst your transitioning root view controllers.

**Comment by danieldahan** [comment]
I am going to make a release with the fix to this issue later today. I will close this once that happens, until then, please try to move your handle code to the AppMenuController to avoid loss of the handler functionality :)

**Comment by gristoi** [comment]
really appreciate the quick response, I will do :)

**Comment by danieldahan** [comment]
The fix for this is in `master` :) [Material 2.3.2](https://github.com/CosmicMind/Material/releases/tag/2.3.2). Thank you for bringing this to our attention.
