### ISSUE TITLE
Referencing Color in Attributes Inspector

### ISSUE THREAD

**Issue by minademian** [CosmicMind/Material#578]
I'd like to set the background color of a RaisedButton in Xcode's Attribute Inspector to the color codes specified in Color.swift. Is there a way to load/reference them in the GUI?

I'm using the latest version of Material 2 in XCode 8.1 (8B62).

**Comment by danieldahan** [comment]
I am investigating a solution for this :)

**Comment by minademian** [comment]
thanks a lot. i appreciate the Swift response!

:)

**Comment by danieldahan** [comment]
Hey, sorry for any delay. I found this StackOverflow question and answer, and it shows how to add colors as a palette to IB. http://stackoverflow.com/questions/2889491/how-to-define-colors-in-xcodes-interface-builder

I don't think there is an easy import method for this. If you have found any solutions that I can help implement or you want to PR, it would be very much appreciated. 

Thank you!
