### ISSUE TITLE
Can't omit Capture and Photos code for Carthage builds

### ISSUE THREAD

**Issue by reidmain** [CosmicMind/Material#580]
When integrating Material using Carthage you are building the entire Material framework and including it in your app. This means you need to include `NSCameraUsageDescription ` and `NSPhotoLibraryUsageDescription` in your Info.plist and provide reasons that you may not have if you are not using those features of Material.

The quick workaround I have is to stop integrating Material with Carthage and just copy the files directly into my app which has the problem of making updating to future versions of Material much harder. Also I have to deal with including resources.

A longer term solution for me would be fork Material and remove the Capture and Photos code from being included in the framework and then I could continue to integrate with Carthage and updating to latest versions would simply be me rebasing off the master Material branch.

A possible solution from the Material side would be to create two new framework targets for Capture and Photo. Anyone using Carthage would drag the Core framework into Xcode and then if they needed Capture or Photos they could drag those in as well.

**Comment by danieldahan** [comment]
I can't seem to find any way to do this in Carthage. If you have an idea of how, as I am not that familiar with using Carthage, please reopen the issue with your suggestion. One idea is to separate out the privacy components into separate repos and component libraries. This is something I am thinking about. Sorry I couldn't be more help on this.
