### ISSUE TITLE
TextField left icon not working properly in version 2.3.2

### ISSUE THREAD

**Issue by tomtharakan** [CosmicMind/Material#582]
<img width="497" alt="screen shot 2016-11-05 at 14 28 31" src="https://cloud.githubusercontent.com/assets/5616425/20028925/6050ce90-a364-11e6-81f3-e0ae8c207057.png">
<img width="523" alt="screen shot 2016-11-05 at 14 28 55" src="https://cloud.githubusercontent.com/assets/5616425/20028926/605136c8-a364-11e6-945b-d6fa143956d0.png">

**Comment by danieldahan** [comment]
I am revisiting the TextField to look at the issues that have popped up. Sorry for the inconvenience.

**Comment by danieldahan** [comment]
Can you share your setup code for this? Also, if possible, please try the `development` branch, as I made some updates. Thank you!

**Comment by tomtharakan** [comment]
lazy var username: TextField = {
        let username = TextField();
        //username.translatesAutoresizingMaskIntoConstraints = false;
        username.dividerColor = UIColor.lightGray
        username.autocapitalizationType = UITextAutocapitalizationType.none;
        username.tag = 12
        username.placeholder = NSLocalizedString("username", comment: "")
        username.keyboardType = .emailAddress
        username.delegate = self
        username.returnKeyType = UIReturnKeyType.next;
        //username.isClearIconButtonEnabled = true
        
        let leftView = UIImageView()
        leftView.image = UIImage(named:"ic_person")
        username.leftView = leftView
        
        username.leftViewMode = .always
        
        return username;
    }();

**Comment by danieldahan** [comment]
I am going to test this tonight with the other issues that surround `TextField` and update you. Thank you for your help :)

**Comment by danieldahan** [comment]
I haven't been able to reproduce this. I am making a release with TextField updates today. Would you be able to share a sample project? Thank you!

**Comment by danieldahan** [comment]
When I get my hands on a reproduction of this issue, we can open it up again. Thank you very much for submitting this :)
