### ISSUE TITLE
Device model as enumeration

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#584]
At the moment the device model is returned as a string. Wouldn't it be better returned as an enumeration?

**Comment by danieldahan** [comment]
Yes, that is a great idea. I will put that in the next release.

**Comment by danieldahan** [comment]
This is ready for release and coming out today :) Thank you!

**Comment by sverin** [comment]
Great news! Looking forward to it!

**Comment by danieldahan** [comment]
Released :) [Material 2.3.9](https://github.com/CosmicMind/Material/releases/tag/2.3.9)
