### ISSUE TITLE
PageTabBarController

### ISSUE THREAD

**Issue by ZahraShams** [CosmicMind/Material#585]
I Added PageTabbarCotroller with three view controllers. in each of them I used a table view which I added swipe gesture for deleting row. but with swiping instead of table view delete style action ,the the view get transitioned to the other one  . how can I disable pan gesture in page tabbar controller?

**Comment by danieldahan** [comment]
Try the:

```swift
    open var isBounceEnabled: Bool {
        didSet {
            scrollView?.bounces = isBounceEnabled
        }
    }
```

This currently removes all bouncing from left to right, so will effectively stop the swiping. I plan to refactor this shortly. So to get the page to stop bouncing, set the 

```swift
pageTabBarController?.isBounceEnabled = false
```

of if you subclassed the `PageTabBarController`, you can set the property to:

```swift
open override func prepare() {
super.prepare()
isBounceEnabled = false
}
```

For now this is the easiest way. Let me know how it works, thank you :)
