### ISSUE TITLE
Set rootViewController from Stotyboard

### ISSUE THREAD

**Issue by Ybrin** [CosmicMind/Material#586]
It would be great if we could change the `rootViewController` from within the Storyboard. There are certain use cases where this is a lot easier than instantiating the Controller together with its rootViewController manually.

**Comment by danieldahan** [comment]
I can't seem to get the `rootViewController` property to appear in the Storyboard pane. I am not the best with Storyboards as I do everything programmatically. So if you have a proposed method to accomplish this, I would be able to help you make it happen. For now, I am going to close this issue and leave it to you to reopen it if needed. Thank you!
