### ISSUE TITLE
Investigate Any Memory Leaks

### ISSUE THREAD

**Issue by foxsin10** [CosmicMind/Material#588]
This UI framework is awesome, I really like it.And I have been used it in my project since `Swift 2.2`.
Recently, I decided to migrate to `Swift 3.0`, but When I run the NavigatioanController Demo with Instruments two days ago,I found there are leaks  .There are some issues with `Grid.swift`

**Comment by danieldahan** [comment]
Nice catch. I'll investigate, and please share more if possible. Thank you :)

**Comment by foxsin10** [comment]
I'm coding with version `Material 2.2.5`. 
The demo I downloaded is using `Material 2.0`.
Maybe It's been fixed in `Material 2.3` .Anyway , I'm updating and then try it again.

**Comment by danieldahan** [comment]
I verified the issue. I will fix this tomorrow. Thank you!

**Comment by foxsin10** [comment]
Good job!

**Comment by danieldahan** [comment]
The fix is in [Material 2.3.4](https://github.com/CosmicMind/Material/releases/tag/2.3.4). Thank you for bringing this to my attention :)

**Comment by foxsin10** [comment]
Appreciated your work.
Maybe there are some work left to be done. :)
see:
<img width="821" alt="qq20161108-2 2x" src="https://cloud.githubusercontent.com/assets/11630650/20104175/ec6f392a-a607-11e6-8a4c-e57914065adb.png">

**Comment by danieldahan** [comment]
Yes, I want to go through each part. I closed your issue as it was related to GridAxis itself. Let's reopen this issue and treat it as a general memory leak investigation :)

**Comment by danieldahan** [comment]
@foxsin10 So I am looking through all the code in Material and I get what seems to be a strange memory issue that I think you may be able to help with. In the `Bar` type objects, there is a property `contentView` that I have reduced down to a `UIView` from a `View` to simplify the investigation. It seems that whenever I do this `bar.contentView.<property> = value` I get an issue where the getter adds a new retain. Please look at the images below. 

<img width="603" alt="screen shot 2016-11-10 at 8 11 44 am" src="https://cloud.githubusercontent.com/assets/9982123/20184543/dcd7fa08-a71d-11e6-89fc-bad635db62db.png">
<img width="1033" alt="screen shot 2016-11-10 at 8 12 49 am" src="https://cloud.githubusercontent.com/assets/9982123/20184544/de5c91f4-a71d-11e6-8296-098a75792a9b.png">

Do you have any ideas what is going on here?

**Comment by foxsin10** [comment]
Sorry , forgot to check my email.
 I’m kind of busy recently, maybe after I check your source code and do some investigation, now I get to turn to my work. :)

**Comment by danieldahan** [comment]
No worries :) I figured it out.

**Comment by danieldahan** [comment]
I am going to continue to make improvements in this area if I find any issues. For now, unless there is a specific memory leak found, there doesn't need to be an issue. Thank you for bringing this to my attention :)
