### ISSUE TITLE
PageTabBarController

### ISSUE THREAD

**Issue by wlching** [CosmicMind/Material#589]
Does it possible set my layout constraint to pageTabBarController's view?
I want to set scrollView of PageTabBarController in a certain region.
I try to set autolayout constraint to scrollView of PageTabBarController.
But it still doesn't work. Could anyone give me a hint?
Thanks.

**Comment by danieldahan** [comment]
Hey, I can help you out, but let's move this to [Material Gitter](https://gitter.im/CosmicMind/Material). Ping me there :)
