### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by unittesting0** [CosmicMind/Material#590]
Can we see in the near future a Time Picker like in Android.

I found a Xamarin version here: https://github.com/fpt-software/Material-Controls-For-iOS#mdtimepicker

**Comment by danieldahan** [comment]
Yes, it is definitely coming in the near future. There is already a request for it, so I will close this off and link it this issue https://github.com/CosmicMind/Material/issues/560, 

Thank you! Keep the great feature requests coming.
