### ISSUE TITLE
Unable to Build Material...

### ISSUE THREAD

**Issue by kaifucious** [CosmicMind/Material#591]
Whenever i execute a carthage update, it fails to build and gives me this line:

Material+UIImage.swift:309:30: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
                var radius = UInt32(floor(inputRadius * 3.0 * CGFloat(sqrt(2 * M_PI)) / 4 + 0.5))

Has anyone ran into this issue yet?

**Comment by danieldahan** [comment]
Yes, I had seen this earlier today. I will post a fix for that within the hour :) Thank you!

**Comment by kaifucious** [comment]
Sweet, let me know when it's fixed! :)

**Comment by danieldahan** [comment]
Please fine a fix in [Material 2.3.5](https://github.com/CosmicMind/Material/releases/tag/2.3.5) :)
