### ISSUE TITLE
[HELP] hide status bar inside NavigationDrawerController

### ISSUE THREAD

**Issue by oleynikd** [CosmicMind/Material#596]
Hi,

First of all - thank you for such a great tool!!!

I have a little problem, I can't hide status bar with `prefersStatusBarHidden` inside inner `UIViewController` after I added `NavigationDrawerController` to my app.

I did set `isHiddenStatusBarEnabled = false` in `NavigationDrawerController`. I need the ability to handle status bar visibility manually!

Please help.
Thanks!

**Comment by danieldahan** [comment]
Thank you! :) It has been a dream working on Material and building with our great community. 

As for helping you, yes, I can for sure help you. What version of Material are you using?

**Comment by oleynikd** [comment]
@danieldahan I'm using version 2.3.1
`Using Material (2.3.1)`

I'm not sure why cocapods not installing latest 2.3.10. When I try to specify exact version I get:
```
[!] Unable to satisfy the following requirements:

- `Material (~> 2.3.10)` required by `Podfile`
```

**Comment by oleynikd** [comment]
@danieldahan OK, I ran `pod repo update` and now I have `2.3.10`!
Question remains the same...
Thanks in advance!

**Comment by danieldahan** [comment]
Great! I will take a look a bit later today and help you out :)

**Comment by oleynikd** [comment]
@danieldahan Thank you! Looking forward, cuz I'm out of ideas.

**Comment by oleynikd** [comment]
@danieldahan OK, never mind, just had to move my statusBar logic to `NavigationDrawerController` instance. Solved. Thank you!!!

**Comment by danieldahan** [comment]
You can use `Application.isStatusBarHidden = true`, that can be used anywhere, and you could set the `navigationDrawerController?.isStatusBarHidden = true` property. 

Glad you found a way :)
