### ISSUE TITLE
Navigation item in leftViews and rightViews not appear in "modalPresentationStyle = .formSheet"

### ISSUE THREAD

**Issue by aemgtz** [CosmicMind/Material#597]
Navigation items in leftViews and rightViews not appear in "modalPresentationStyle = .formSheet"

Before added support for iPad

![screen shot 2559-11-16 at 2 27 57 pm](https://cloud.githubusercontent.com/assets/276439/20338331/f39dc8fe-ac08-11e6-9cb5-80be6ec93e43.png)

After adjusted the code to support iPad
with

``                    if UI_USER_INTERFACE_IDIOM() == .pad {
                        navController.modalPresentationStyle = .formSheet
                    }``

The navigation items was disappeared

![image](https://cloud.githubusercontent.com/assets/276439/20338349/0b58ec8a-ac09-11e6-8626-8665f6037ae0.png)

Any idea ?
I am using Material 2.3.6

**Comment by danieldahan** [comment]
I will take a look, and if you can, please send a reproducible project :)

**Comment by aemgtz** [comment]
@danieldahan 
I have created the sample project which demonstrate the problem
https://github.com/aemgtz/Matreial-iOS-Problem

**Comment by danieldahan** [comment]
Thank you, I will take a look and make an update :)

**Comment by danieldahan** [comment]
Taking a look now.

**Comment by danieldahan** [comment]
I downloaded your sample, and updated Material to 2.3.21, and go this outcome: 

<img width="370" alt="screen shot 2016-12-01 at 12 35 26 pm" src="https://cloud.githubusercontent.com/assets/9982123/20807000/c3d03f7e-b7c2-11e6-8837-c0716a8963cb.png">
<img width="376" alt="screen shot 2016-12-01 at 12 35 20 pm" src="https://cloud.githubusercontent.com/assets/9982123/20807012/cc8138a8-b7c2-11e6-94bf-143fc00790fe.png">

Looks fine to me. Is there something I am missing here?

**Comment by danieldahan** [comment]
Oh may, I need to try this on an iPad. I will try that now.

**Comment by danieldahan** [comment]
I see the issue now, I will fix this, one moment.

**Comment by danieldahan** [comment]
I fixed it, now running tests to avoid a regression, and then I will post an update :) Thanks for bringing this issue up :)

**Comment by danieldahan** [comment]
Please find a fix for your issue in [Material 2.3.22](https://github.com/CosmicMind/Material/releases/tag/2.3.22). Thank you :)

**Comment by aemgtz** [comment]
Super! Thank you.
If there is anything I can help please let me know.

**Comment by danieldahan** [comment]
I appreciate it. You are already helping by bringing issues to the community :) Thank you!
