### ISSUE TITLE
Problem with TextView ( add placeholder to TextView in Editor component ).

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Material#598]
I used this code before:
`    var textView: TextView!
    /// A Text storage object that monitors the changes within the textView.
    lazy var text: Text = Text()
`
I did a pod update and now I cannot compile. "Use of undeclared type 'Text'".
Need help :-)

**Comment by danieldahan** [comment]
Hey, 

So in Material 2, I silently launched a new component that is officially launched at the end of the month. It is called `Editor`. It now encapsulates all the work needed to setup a dynamic textView. Later today I will post an example for you, and for now if you can take a look at the `Editor` and `EditorController` API, that will get you started. For example: 

```swift
let editor = Editor()
editor.textViewEdgeInsetsPreset = .square4
editor.textView.font = RobotoFont.regular
        
view.layout(editor).edges()
```

Place that code in a UIViewController and see what happens. You could also hook delegation methods and a new enum for tapping into character attributes. For example:

```swift
extension ViewController: EditorDelegate {
    @objc
    fileprivate func editor(editor: Editor, willProcessEditing textStorage: TextStorage, text: String, range: NSRange) {
        textStorage.updateAttributes(characterAttributes: [.font: RobotoFont.regular, .forgroundColor: Color.black], range: range)
    }
    
    @objc
    fileprivate func editor(editor: Editor, didProcessEditing textStorage: TextStorage, text: String, range: NSRange) {
        textStorage.updateAttributes(characterAttributes: [.font: RobotoFont.bold, .forgroundColor: Color.blue.base], range: range)
        uniqueMatches = editor.uniqueMatches
    }
}
```

Let me know how it goes. Also, I made an issue [Samples Editor Issue](https://github.com/CosmicMind/Samples/issues/20) that we can use to get you up to speed with a sample project :)

**Comment by theolof** [comment]
Thanks, I'm trying to implement Editor now. I'll let you know how it goes.

**Comment by theolof** [comment]
I have Editor working now, but I still need the placeholder text. Can I do a workaround until you release the full version? Or is the full version coming really soon?

**Comment by danieldahan** [comment]
@theolof Its coming really soon :) When is the latest you need it by?

**Comment by theolof** [comment]
Well, we are ready to release the next version except for some color changes and this. Thinking of changing to TextField in the meantime.

**Comment by danieldahan** [comment]
Okay, I will do my best to have it done really soon. It is one of the final parts to releasing the `Editor` component. So I need it and want it done as well. Thanks for your patience.

**Comment by danieldahan** [comment]
I am a few hours from being done the TextView will placeholder and simplified interface. I will push a release by tomorrow. Thank you!

**Comment by danieldahan** [comment]
Hey, please find your feature request in [Material 2.6.0](https://github.com/CosmicMind/Material/releases/tag/2.6.0) and a sample [TextView](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TextView) project. Thank you and all the best!
