### ISSUE TITLE
NavigationDrawerController's (left|right)ViewThreshold values and behavior

### ISSUE THREAD

**Issue by oleynikd** [CosmicMind/Material#599]
Hi,

[Here](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationDrawerController.swift#L182) it is said that:
```
The leftViewThreshold is always at half the width of the leftView.
```
So the Drawer will never be opened unless you drag it at least half of its width, right?
Is there some reason for that? Actually for me it is not expected behavior. In Android velocity is more important then traveled distance. If you make short but fast swipe from edge - you expect Drawer to open, but with this `(left|right)ViewThreshold` you only see how it shows a bit and then flies away...

Maybe we could consider more realistic and familiar behavior?

**Comment by danieldahan** [comment]
Hey :)

So in this case, the comment is actually outdated. As well, you can set it to a value that you like. There should also be a velocity measure applied internally in the algorithm that calculates the distance to open and close the NavigationDrawer. 

Please try and set the `leftThreshold` and `rightThreshold` to a value that works more for you. If you feel there is an improvement that can be made and have a chance to prototype a PR, I would be happy to review it and work on it with you. 

Thank you!
