### ISSUE TITLE
UITableViewController doesn't autoresize when used as NavigationDrawer pane

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#603]
Hello!

I'm using a TableViewController as the left hand pane of a NavigationDrawer.
Everything is working perfectly fine except for the TableView Cells autoresizing.

I'm composing the static cells of the TableViewController in a storyboard:
![image](https://cloud.githubusercontent.com/assets/8849554/20456823/97d72bdc-ae7e-11e6-82a4-313af8c93cd9.png)

And I've added layout constraints to the buttons and the ImageView:
![image](https://cloud.githubusercontent.com/assets/8849554/20456837/bff832c8-ae7e-11e6-9907-e5b8f11bd61a.png)

But this is how it actually looks like:
![image](https://cloud.githubusercontent.com/assets/8849554/20456846/00ba73b6-ae7f-11e6-8d55-5eaa3629180d.png)

As I'm very new to iOS development, I'm sure this problem is my bad... 😄 
But maybe someone had a similar experience and want to give a hint...

Thank you!

**Comment by danieldahan** [comment]
Hey! Would you be able to share your project as a sample to support@cosmicmind.com and I can take a look ?

**Comment by AndreMarvell** [comment]
Hi @timoschwarzer i have the same issue. Did you solve the problem?

**Comment by danieldahan** [comment]
@AndreMarvell yes, try updating to the latest [Material 2.3.19](https://github.com/CosmicMind/Material/releases/tag/2.3.19). I didn't update this issue yet :)

**Comment by AndreMarvell** [comment]
Perfect, thank you @danieldahan
