### ISSUE TITLE
Materialish Progress Indicator

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#604]
Hello there!

Is it possible to implement a materialish circular progress indicator as described in Material Design guidelines?
https://material.google.com/components/progress-activity.html#progress-activity-types-of-indicators

Thanks!

**Comment by danieldahan** [comment]
Yes, I will add this to the feature request list :)

**Comment by timoschwarzer** [comment]
You are fast, man! Thanks!

**Comment by danieldahan** [comment]
No worries. There are new features coming out this month, and next month. I will include it in one of the major updates :)

**Comment by timoschwarzer** [comment]
I was only stunned by your reply speed!
Keep up the good work... 😄

**Comment by cody1024d** [comment]
Any update on this?

**Comment by danieldahan** [comment]
@cody1024d soon, I am releasing some updates within the next day, and then going back to the feature request list.

**Comment by cody1024d** [comment]
Sounds good! ---Thanks for the quick response @danieldahan!

**Comment by Iambecomeroot** [comment]
Any news? I don't see this feature. Also, is there a place to get a list of all the features with a short example. I cloned the samples but that doesn't seem complete.

**Comment by danieldahan** [comment]
The next release will include a bunch of updates. This one I have been working on for a couple months now, getting the latest Motion framework in. At the moment, I have not had a chance to work on an indicator, though it should be fairly simple with the Motion framework now. So I will prioritize it, make a list like you are requesting and update the repo. Sorry for any inconvenience.

**Comment by lddd** [comment]
This would be awesome.

**Comment by hardikamal** [comment]
@danieldahan Any updates?

**Comment by danieldahan** [comment]
Hey! I haven't had a chance to work on this yet. I am wrapping up the new education centre, and once that is out, components will be flying out the door. Please share a starter project for this, or wait a bit longer and it will be in your hands. Thank you!

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!

**Comment by mihailsalari** [comment]
Hi, Did you add Circular progress & activity indicator?

Regards

**Comment by OrkhanAlikhanov** [comment]
Hey! Not yet. Not in the priority

**Comment by danieldahan** [comment]
@mihailsalari we have a bunch of new features coming out and will release with documentation. Then we will add a roadmap for the next components. The indicator is something we want, but not something that made it into the latest batch of updates. Thank you for checking in.
