### ISSUE TITLE
Having a PageTabBarController within a NavigationDrawerController makes the Drawer not opening on swipe

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#605]
When a PageTabBarController is the rootViewController of a NavigationDrawerController, the NavigationDrawer's panes can't be opened with a swipe gesture.

I've attached a sample project for testing.
[TabBarControllerWithNavigationDrawer.zip](https://github.com/CosmicMind/Material/files/602246/TabBarControllerWithNavigationDrawer.zip)

**Comment by danieldahan** [comment]
Nice, adding this to the list of items to investigate with the PageTabBar rewrite.

**Comment by danieldahan** [comment]
This component has now been updated in [Material 2.8.0](https://github.com/CosmicMind/Material/releases/tag/2.8.0). Features like swiping have not been included in 2.8.0, and will be included in a following release. The overall TabsController adds stability and scrollable Tabs. I am closing this issue and thank you for your patience.

**Comment by kizitonwose** [comment]
@danieldahan Any update on this issue? Still happening with TabsController on [2.9.4](https://github.com/CosmicMind/Material/releases/tag/2.9.4)

**Comment by danieldahan** [comment]
The TabsController doesn't have a swipe feature. So there shouldn't be anything conflicting with it. If you can send me an updated sample, I can take a look at what is going on: @kizitonwose, thank you!

**Comment by kizitonwose** [comment]
@danieldahan I just realized this. Will this feature be added in the future?

**Comment by danieldahan** [comment]
Yes, it is in the short list to release :)

**Comment by danieldahan** [comment]
@kizitonwose Most likely within a couple weeks.
