### ISSUE TITLE
The line of a PageTabBarController behaves weird when the PageTabBarController has only two views attached

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#606]
The line stops somewhere at 2/3 of the window's width and then it goes further to its target position.
You can launch this sample project and swipe between the two tabs:
[TabBarControllerWithTwoViewControllers.zip](https://github.com/CosmicMind/Material/files/602252/TabBarControllerWithTwoViewControllers.zip)

**Comment by danieldahan** [comment]
I will take a look at this. I have gathered a a few issues on the PageTabBar, so I will be most likely rewriting it to include more features and correct all the issues. Thank you for sharing this, I have added it to the list of things to investigate.

**Comment by danieldahan** [comment]
Working on this now, and this is a related issue, please follow this one. https://github.com/CosmicMind/Material/issues/619
