### ISSUE TITLE
SearchBarController in TabBarController

### ISSUE THREAD

**Issue by kaifucious** [CosmicMind/Material#607]
I'm trying to setup my app using a tab bar controller, and the first tab should show a table view with the  Material search bar on top...the trouble is I can't seem to find an example of how this is done, outside of setting a root view controller to App Delegate's window, which won't work for me because I'm using Storyboards. 

Is there an example that shows the Material SearchBar with a Table View inside of Tab Bar Controller, using strictly Storyboards? 

Thanks! :)

**Comment by danieldahan** [comment]
Using strictly storyboards no, there isn't an example. It could be possible though a bit of code and storyboards. I will work on a sample and place it in the [Samples](http://github.com/CosmicMind/Samples.git) repo :) If you would like to further discuss this, let's chat in [Material Gitter](https://gitter.im/CosmicMind/Material). All the best!
