### ISSUE TITLE
Is PageTabBarController possible to dynamicly arrange view controllers?

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#608]
I want to insert or delete view controllers corresponding to user operation.
Is it possible? 
The error message popped out while doing so.
```The number of view controllers provided (3) doesn't match the number required (1) for the requested transition```

**Comment by danieldahan** [comment]
Have you tried this function: 

```swift
open func setViewControllers(_ viewControllers: [UIViewController], direction: UIPageViewControllerNavigationDirection, animated: Bool, completion: ((Bool) -> Void)? = nil)
```

It allows you to set the Array of UIViewControllers.

**Comment by HowardCsie** [comment]
yes, I have tried.
I initialized a PageTabBarController with one root view controller,then i used that function to set three UIViewControllers (Array). I got that error message above.

**Comment by danieldahan** [comment]
Okay, I will take a look. I am planning to update the PageTabBar this week, so I will investigate today to help you out, and then release a new PageTabBar. Thanks :)

**Comment by HowardCsie** [comment]
Thank you very much.I'll be waiting to hear from you.

**Comment by danieldahan** [comment]
Hey, I didn't forget about this issue. I will be able to focus on it within the next couple days. Sorry for any delays.

**Comment by HowardCsie** [comment]
Thank you very much!!!

**Comment by asyl** [comment]
the same error `The number of view controllers provided (3) doesn't match the number required (1) for the requested transition` appears again.

**Comment by asyl** [comment]
Hi, I need your help! I can't rewrite the amount of `viewControllers` with method 
`open func setViewControllers(_ viewControllers: [UIViewController], direction: UIPageViewControllerNavigationDirection, animated: Bool, completion: ((Bool) -> Void)? = nil)`

**Comment by danieldahan** [comment]
@asyl Yes, this is in the queue to fix. I was working on launching [Motion](http://github.com/CosmicMind/Motion). Will be updated soon.

**Comment by asyl** [comment]
I found the way how to add dynamically view controllers.
First, redefine property `viewControllers` of `PageTabBarController` with your `viewControllers`.
Second use
```
swift
open func setViewControllers(_ viewControllers: [UIViewController], direction: UIPageViewControllerNavigationDirection, animated: Bool, completion: ((Bool) -> Void)? = nil)
```
to show the page you want. Simply
```
swift
pageTabBarController.viewControllers = viewControllers
pageTabBarController.setViewControllers([viewControllers[0]], direction: .forward, animated: true)
```

**Comment by danieldahan** [comment]
@asyl Thank you for sharing. I am working on an update to simplify switching view controllers. Your reference is very helpful :)

**Comment by danieldahan** [comment]
You can now use the `selectedIndex` property to select a tab in [Material 2.6.2](https://github.com/CosmicMind/Material/releases/tag/2.6.2). For example: 

```swift
pageTabBarController.selectedIndex = 3
```

Thank you!

**Comment by HowardCsie** [comment]
@danieldahan Thanks a lot. I 'll try it later :)
