### ISSUE TITLE
Conflicting UIView Extension on width & height

### ISSUE THREAD

**Issue by Daeda88** [CosmicMind/Material#609]
For my current project using Material, I am moving to a use_frameworks setup. However, Im running into some problems due to conflicting extensions. In Material+UIView.swift, an extension is created to access the layers width and height via "width" and "height" respectively. Unfortunately, I am also currently using the Masonry framework for some legacy code. Since that framework also specifies an extension to UIView names "width" and "height", and since said extension returns a different type, Material gets conflicting results and no longer renders properly.

While I will try to phase out Masonry to fix this issue on my side, I think it is best if the Material framework renames its extension to something a little less straightforward. Since "width" and "height" are very standard names, the risk of them breaking whenever any other framework uses the same names is simply too big. Resolving this on the framework's side will no doubt reduce a lot of headaches down the line.

**Comment by danieldahan** [comment]
I appreciate your suggestion. At the current moment making such a change would not be ideal. I am going to close this for now, but that said, I will think about this more and see if I can come up with something elegant to solve this issue :) Feel free to discuss more with me and the community on [Material Gitter](https://gitter.im/CosmicMind/Material).
