### ISSUE TITLE
Transitioning the RootViewController of a ToolbarController to an UITableViewController causes flickering

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#610]
Transitioning the RootViewController of a ToolbarController to an UITableViewController causes the Toolbar not being shown for the duration of the transition:

`myToolbarController.transition(to: myTableViewController, duration: TimeInterval(1))`
-> Toolbar is hidden for 1 sec

Using a duration of 0 causes a bit flickering even with normal UIViewControllers.

**Comment by danieldahan** [comment]
Could you send me a sample of this?

**Comment by timoschwarzer** [comment]
@danieldahan You can take the programmatic NavigationDrawerController sample and make the `TransitionedViewController` extend `UITableViewController` instead of `UIViewController`. I tried this and it shows the mentioned effect.

**Comment by danieldahan** [comment]
This could be when the UITableVIewController is setup. Usually this is done after the view loads and could give a stutter effect. I will take a look and see if I can replicate the behavior.

**Comment by timoschwarzer** [comment]
But the toolbar is hidden for exactly the same amount of time like the transition's duration is. So if you call `transition(to: duration:)` with a duration of 10sec, you won't see the toolbar for 10sec.

**Comment by danieldahan** [comment]
Ahh... I think I know why. Okay, I will take a look later today. I am finishing up some documentation, and then will tackle this issue and some others on the board. Thanks for bringing this to my attention.

**Comment by timoschwarzer** [comment]
Thanks! 😄

**Comment by danieldahan** [comment]
Thank you for sharing this issue with me. Please give [Material 2.3.18](https://github.com/CosmicMind/Material/releases/tag/2.3.18) a try :)
