### ISSUE TITLE
Separate files into different pods

### ISSUE THREAD

**Issue by Maxatma** [CosmicMind/Material#614]
Just have found that loading whole Material is unnecessary. Actually, i use some classes, but not whole project. Even tool that search unused files says that in project those files unused:

_BottomTabBar,FlatButton,ImageCardView,MenuController,SearchBarController,StatusBarController,ToolbarController_

Maybe it would be better if we could load, for example only
 **pod Material/Button**
 or
 **pod Material/TextField** 
?

**Comment by danieldahan** [comment]
Yes, that is a good suggestion, I have done that for certain classes, such as Capture / PhotoLibrary. I'll make an update for that.

**Comment by Maxatma** [comment]
Would be awesome ! 
👍

**Comment by danieldahan** [comment]
Hey, I am not going to get a chance to do this for a while. So I have put it as a note. To clean up the project board, I am closing this issue. Thank you!

**Comment by Maxatma** [comment]
@danieldahan well, seems like this still not working :)

**Comment by OrkhanAlikhanov** [comment]
It is possible to implement but still requires some dedication to decide what to put under which subspec. It's not a tough work but I don't think it's relevant time to start working on this. A PR is more than welcome though ;)
