### ISSUE TITLE
Position of the Snackbar

### ISSUE THREAD

**Issue by iamszabo** [CosmicMind/Material#615]
@danieldahan first of all thanks for the great project and for the even greater support.

It would be great to have a custom position of the snackbar. Could you make it happen?

**Comment by danieldahan** [comment]
Thank you for helping to make Material wonderful :) Yes, I can make an update with this feature tomorrow.

**Comment by danieldahan** [comment]
Please update to [Material 2.3.21](https://github.com/CosmicMind/Material/releases/tag/2.3.21). You can use the `snackbarEdgeInsets` and `snackbarEdgeInsetsPreset` to position the `Snackbar` away from the edges anywhere you would like :) 

Thanks and all the best!
