### ISSUE TITLE
Line of PageTabBarController lags when swiping fast

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#619]
As title :))

**Comment by danieldahan** [comment]
Yes, I agree. I finally have a chance to visit the PageTabBar issues :) This will be fixed in the next update for PageTabBar.

**Comment by danieldahan** [comment]
This is a related issue, https://github.com/CosmicMind/Material/issues/619. Working on this now.

**Comment by drinkius** [comment]
Still facing the same issue, will try to look into it as well when I have some spare time

**Comment by danieldahan** [comment]
@drinkius No need to look into it. It is an issue that will be solved in a replacement component coming out, `TabsController`. Solving it in the current component will be replaced anyways. 

Thank you though :)

**Comment by danieldahan** [comment]
This component has now been updated in [Material 2.8.0](https://github.com/CosmicMind/Material/releases/tag/2.8.0). Features like swiping have not been included in 2.8.0, and will be included in a following release. The overall TabsController adds stability and scrollable Tabs. I am closing this issue and thank you for your patience.

**Comment by HowardCsie** [comment]
@danieldahan Thank you so much:)
