### ISSUE TITLE
Menu disappears when it is closed.

### ISSUE THREAD

**Issue by gerbiljames** [CosmicMind/Material#620]
If you close a menu by tapping on the original menu button then the menu disappears. This only happens on a device, not in the simulator. It doesn't happen if you close the menu by tapping outside of it.

I've tested it on iOS 10.1 only and I'm using Xcode 8.1 and Material 2.3.22.

You can reproduce this in the MenuController sample project.

**Comment by danieldahan** [comment]
Thank you, I will take a look today.

**Comment by gerbiljames** [comment]
Thanks! I'd have submitted a pull request but I haven't got a clue whats going wrong.

**Comment by danieldahan** [comment]
No worries :) It was in the `Motion` library. The `CAAnimation` that sets the `delegate`, I believe should be omitted. I will make a push. This would have been a really hard bug to find if I had not been working in that area already.

**Comment by danieldahan** [comment]
This was the [ifx](https://github.com/CosmicMind/Material/commit/c1c421dec684b6ed151b1285bcc4961fbf54b027).

**Comment by danieldahan** [comment]
Please update to [Material 2.4.0](https://github.com/CosmicMind/Material/releases/tag/2.4.0) for a solution to this issue :)
