### ISSUE TITLE
A suggestion to make Layout class more robust

### ISSUE THREAD

**Issue by shshalom** [CosmicMind/Material#621]
Hi,

Lately I have realized how heavily I am using Layout class to layout my views, that said, It also made me notice the gap between what I though the class is capable of doing and what it actually does.

I really fond of the way (I thought) the class works, and when things didn't worked as I expected them to work, I went looking under the hood and then understood that I was using it wrong, as well how limited the class is.

So now that I know what Layout can do, I use it only on a specific occasions, but then I thought why not making it like I originally thought it did.

Allow me to show you how I was using Layout at the beginning:
```swift

let imageView = UIImageView()
let label = UILabel()

view.layout(imageView).top(50.0).centerHorizontally()
view.layout(label).bottom(imageView, 10).centerHorizontally()
```
which would have been equivalent to the following:

```swift
let imageView = UIImageView()
let label = UILabel()

imageView.translatesAutoresizingMaskIntoConstraints = false
imageView.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
imageView.topAnchor.constraint(equalToConstant: 50).isActive = true

label.translatesAutoresizingMaskIntoConstraints = false
label.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
label.bottomAnchor.constraint(equalTo:imageView.bottomAnchor, constant:10).isActive = true
```

Now, I know that it may be more complicated than what I thought, but I just wondered what do you think about it, do you think it possible?

**Comment by danieldahan** [comment]
Give me a day or two think about this. I have been thinking about expanding the layout system.

**Comment by danieldahan** [comment]
Today I will be playing with some ideas. I will let you know what I come up with :)

**Comment by shshalom** [comment]
Great, looking forward.

**Comment by danieldahan** [comment]
Hey, I didn't get a chance to fully hash this out. I have been really busy for the past few days, and was only able to help out on so many issues. I am back in full gear now, so I should have something in the works very soon :)

**Comment by danieldahan** [comment]
Hey, so I have been thinking about this for a bit, and I don't see me working on a new Layout system for a bit. So I am going to make a note to look back into this, and close the issue for now. Thank you!
