### ISSUE TITLE
Card with TableView as ContentView

### ISSUE THREAD

**Issue by lazarte** [CosmicMind/Material#625]
<img width="351" alt="screen shot 2016-12-06 at 11 34 21 am" src="https://cloud.githubusercontent.com/assets/248630/20912034/bf7d230e-bba7-11e6-9877-75287298b8e2.png">

Tried to have a card with the contentview of tableview. I don't know what happen but the tableview(picture above orange background) looks fine but the cell was broken. See the code below using the latest Material version.

func prepareCardView() {
        let cardView: Card = Card()
        
        cardView.toolbar = toolbar
        cardView.toolbarEdgeInsetsPreset = .none
        
        cardView.contentView = self.tableView
        
        cardView.contentViewEdgeInsetsPreset = .none
        
        self.layout(cardView).edges(top: 0, left: 0, bottom: 0, right: 0)
    }

**Comment by danieldahan** [comment]
Was this working before? Have you tried the [CardTableView sample project](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView)? Also, if you are defaulting all values to `0` in the `Layout.edges` you don't need to set them, you can do this `layout(cardView).edges()`.

**Comment by danieldahan** [comment]
Hey, I haven't heard from you, so if you still face this issue, please reopen or create a new one. Thank you very much :)
