### ISSUE TITLE
navigationItem.rightViews issue: On smaller screens, some icons don't show

### ISSUE THREAD

**Issue by ttrushin** [CosmicMind/Material#627]
I have an app that uses three IconButtons, which I place in the navigationItem's 'rightViews'.  On an iPhone 6 or larger, all three icons show perfectly.  However on anything smaller (5, 5S, SE, etc) the third item in the list simply doesn't display.  Through debugging I can see that it is there, just off screen.
I am assuming this is a bug, however please let me know if there is some sort of limit that I am not aware of!  Thank you, and ESPECIALLY thank you for creating such a fantastic and versatile framework.

(For reference, I use a NavigationController in my app.)

**Comment by danieldahan** [comment]
Hey :) Thank you for sharing this issue. I will take a look and see, it might be a bug, or a limitation, is it possible you share both a screenshot and your code setup so I can see what you are trying to achieve?

**Comment by danieldahan** [comment]
So I tested this out. It looks like a limitation based on the calculations. I can make this more dynamic and will look good. I will work more on this later today. Wonderful catch, thanks :)

**Comment by tySwift93** [comment]
Thanks for looking at this so quickly!  Looking forward to seeing how you solve it

**Comment by danieldahan** [comment]
Hey, I didn't forget about this. I wanted to tackle some issues prior to diving in. I think today would be a good day to play with a solution :) All the best and sorry for any delay.

**Comment by quanguyen** [comment]
Hi

I got [the same issue](https://github.com/CosmicMind/Samples/issues/58), but my problem is on the large screen (i6S+, i6+), not the small screen (i5S, i6).

Have you got solution to this problem?

**Comment by quanguyen** [comment]
Hi @danieldahan 

Have you got some updates on this issue?

**Comment by danieldahan** [comment]
Hey :) @quanguyen It is one of the next items on queue to be looked at. Sorry for any delays.

**Comment by angelix** [comment]
Hi @danieldahan, do we have an update on this. NavigationController is useless on devices like iPhone 5s etc.

Thanks!

**Comment by danieldahan** [comment]
@angelix It is still in the queue. If you want it to move faster, help by coding it up with me. Telling me it's uselessness is just as useless.

**Comment by angelix** [comment]
@danieldahan i didn't mean to disrespect you. Just wanted to point out the situation.
I'll take a look.

Any hint to where to start?

Thanks

**Comment by danieldahan** [comment]
@angelix no worries :) It is more helpful to always be helpful. 

Anyway, the NavigationBar uses an internal Toolbar, which inherits the Bar. So look in the Bar.layoutSubviews function to get started. If you start looking at this, I can guarantee that it will be tackled sooner. Possibly @mohpor may be available to peak at it as well.

**Comment by danieldahan** [comment]
Linked issue: https://github.com/CosmicMind/Samples/issues/58

**Comment by danieldahan** [comment]
The linked issue has been confirmed as fixed. If this issue still persists, please reopen the issue. Thank you!
