### ISSUE TITLE
Add Alert & AlertController.

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#629]

**Comment by adeesh** [comment]
Does this support custom Alert designs as well?

**Comment by danieldahan** [comment]
Yes it will. Everything in Material is customizable :)

**Comment by JuandreBarnard** [comment]
Hi, I cant find Dialogs & Alerts in your new release, will you still be releasing it?

**Comment by danieldahan** [comment]
Hey, @JuandreBarnard . Yes they are coming. I was waiting to build [Motion](http://github.com/CosmicMind/Motion) before I made those components.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
