### ISSUE TITLE
Cannot disable  left pan gesture on Navigation Drawer Controller.

### ISSUE THREAD

**Issue by tiennth** [CosmicMind/Material#633]
Thank you very much for this very very useful library.
I use Material version 2.3.19 using Cocoa pod.

I created a navigation drawer controller like this:
```
class AppNavigationDrawerController: NavigationDrawerController {
    override func prepare() {
        super.prepare()
        delegate = self
        isLeftPanGestureEnabled = false
        isHiddenStatusBarEnabled = false
    }
}

extension AppNavigationDrawerController: NavigationDrawerControllerDelegate {
    
}

```

However, the pan gesture is not removed. The left view still show up when I pan from left side of screen.
Could you please take a look? Thank you very much!

**Comment by danieldahan** [comment]
So I tried the latest [NavigationDrawerController sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/NavigationDrawerController) with Material 2.4.0 and all works. Can you try that and verify? Based on your setup, all looks good.

**Comment by tiennth** [comment]
I checked again and see that, I called this method afterwards: `navigationDrawerController?.isEnabled = true`
This method add the pan gesture back to the navigation drawer controller. That's why I though the pan gesture was not disabled.

**Comment by danieldahan** [comment]
No worries :) we are here to help
