### ISSUE TITLE
can not run normal 

### ISSUE THREAD

**Issue by tianqiujie** [CosmicMind/Material#635]
#/Users/tian/Library/Developer/Xcode/DerivedData/voicechanger-cdqrblyblzegcbbudsyrhuxrxdbe/Build/Products/Debug-iphonesimulator/io.cosmicmind.material.fonts.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

 pod 'Material', '~> 2.0'

**Comment by danieldahan** [comment]
What version of CocoaPods are you using?

**Comment by danieldahan** [comment]
Sorry didn't mean to close the issue.

**Comment by danieldahan** [comment]
I haven't heard from you, so I am going to close this issue. It should be fixed with updating to the latest CocoaPods, either the beta or the latest stable release. If you continue to have this issue, please reopen this issue. Thank you :)

**Comment by tianqiujie** [comment]
![image](https://cloud.githubusercontent.com/assets/2835129/21269534/046e2bfe-c3ee-11e6-9374-f85a6d511454.png)
```
Build/Products/Debug-iphonesimulator/voicechanger.app/Frameworks/Material.framework: bundle format unrecognized, invalid, or unsuitable
Command /bin/sh failed with exit code 1
```

**Comment by danieldahan** [comment]
Hmmm... can you send me the project so I can try? Because all works for me. Also, make sure to clean and clear your cache. Maybe something is getting in the way.

**Comment by tianqiujie** [comment]
![image](https://cloud.githubusercontent.com/assets/2835129/21270950/c2676814-c3f3-11e6-8767-bf2b91afe44a.png)
Is this right ?

**Comment by danieldahan** [comment]
Hmm... can you update to Material 2.4.0 and try ?

**Comment by tianqiujie** [comment]
OK, thank you, the 2.4.0 solved my problem

**Comment by danieldahan** [comment]
perfect :) Thank you!
