### ISSUE TITLE
Card Material hides my UIView

### ISSUE THREAD

**Issue by calvinsug** [CosmicMind/Material#636]
After using Xcode8, when i implement Card material to my UiView, the container cover my UIView, so my UIView is not appear, i must remove its container from my code every time i implement Card material using this code:

`@IBOutlet weak var card: Card!

override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        self.card.container.removeFromSuperview()
    }`

bringSubview to front is not working at my UIView

**Comment by danieldahan** [comment]
This is strange... can you send a sample project to support@cosmicmind.com, I will need to be able to reproduce this. Thank you :)

**Comment by danieldahan** [comment]
Hey, I haven't heard from you. If this issue still persists, please reopen or create a new issue. Also, please update to the latest Material. All the best :)

**Comment by calvinsug** [comment]
ok, wait, i`m using Material 2.1.2

**Comment by danieldahan** [comment]
Please send me a sample, and I can take a look. Send to support@cosmicmind.com :)

**Comment by calvinsug** [comment]
ok, code sample sent! I use your sample card project to implement Card the same way i implement it in my project

**Comment by danieldahan** [comment]
Thank you, I am looking now :)

**Comment by danieldahan** [comment]
So I have taken a look at your project. When you get a chance, let's chat on [Gitter Material](https://gitter.im/CosmicMind/Material)

**Comment by danieldahan** [comment]
I am going to close this issue here, and help you on Gitter :) This isn't an issue with Material. I need to show you how to set this up.

**Comment by danieldahan** [comment]
I am actually going to write an article about this now, and post the full instructions on how to use the Card with Storyboards.

**Comment by danieldahan** [comment]
@calvinsug I added to the development branch [Storyboard Card](https://github.com/CosmicMind/Samples/tree/development/Material/Storyboards/Card) sample project. I will be writing about this tonight and then release a final copy once done into master with any Material updates at the same time.

**Comment by calvinsug** [comment]
i have seen your ViewController code in development. Should we set toolbar, contentView, and bottomBar every time i want to implement Card material ?

**Comment by danieldahan** [comment]
Then you shouldn't use the `Card`, you can use a `View` and that will give you the drop shadow and radius effect :)

**Comment by calvinsug** [comment]
thanks for the information :) ,
but i will still use the `Card` because i don`t know the exact value of drop shadow radius effect :D

**Comment by danieldahan** [comment]
No worries :) Have fun and experiment with Material. There is so much you can do and it really comes to life when you explore. For your reference, these are the settings: 

```swift
depthPreset = .depth1
pulseAnimation = .none
cornerRadiusPreset = .cornerRadius1
```
