### ISSUE TITLE
Application going into infinite loop when I set shapePreset to circle in Layer

### ISSUE THREAD

**Issue by hbgovindarao** [CosmicMind/Material#637]
Hi, 

I run sample Layer app and I found issue that app is going into infinite loop at following line 

> layer.shapePreset = .circle

I debugged and found the countrol going infinate loop in **Material+CALayer.swift** 313 line 

` cornerRadius = width / 2` 

I think issue with following over written variable 

```
@IBInspectable
    open override var cornerRadius: CGFloat {
		didSet {
			layoutShadowPath()
			if .circle == shapePreset {
				shapePreset = .none
			}
		}
	}
```
if I changed `open override var cornerRadius: CGFloat` to `open var cornerRadius1: CGFloat` , sample working fine. 

Please have a look once , thanks

**Comment by danieldahan** [comment]
Hey,

What version are you using? Thank you :)

**Comment by danieldahan** [comment]
So I double checked, and the latest `master` has a fix for this. Please update, and this was a great catch... I caught early on from a release I made, so an update should be good to fix it for you. Thanks again :)
