### ISSUE TITLE
Support multi line text field

### ISSUE THREAD

**Issue by astromme** [CosmicMind/Material#638]
The android EditText widget supports multiline text. It appears that the TextView component keeps all content on one line. It would be nice to have the widget automatically grow vertically.

**Comment by danieldahan** [comment]
I can add this to the new `Editor` component that is coming out this month.

**Comment by IceFloe** [comment]
Hi, I am just wondering will we have multiline TextField like Google have here https://material.io/guidelines/components/text-fields.html#text-fields-field-types. Are you still planning to do it?

**Comment by danieldahan** [comment]
@IceFloe Hey, So the only way to support multi-line text is with a TextView and that has been released :) Let me know if you need any further help. All the best!

**Comment by IceFloe** [comment]
@danieldahan Yes, but the TextView is not the multiline TextFiled ) It does not have all needed properties, thx for answer )

**Comment by danieldahan** [comment]
Well a PR is always nice :)
