### ISSUE TITLE
TextField's placeholder text gets smaller than it should be when textField's text property is set to empty string (or nil) programmatically

### ISSUE THREAD

**Issue by jjmean2** [CosmicMind/Material#640]
I used text field like a label, so I set text property of textField programmatically on result of API call. When I set empty string on textField which already had some text, font size of placeholder text is as same as when it displayed as title label. It is smaller than original font size of placeholder text.

below, I tested this issue in a fresh simple project. 
![2016-12-19 15_52_37](https://cloud.githubusercontent.com/assets/11574475/21303761/130e093c-c604-11e6-8f20-ec6e7fa479de.gif)

* Xcode 8.2 (8C38)
* Targeting: newer than iOS 9.0
* Mateiral Version: 2.4.1

**Comment by danieldahan** [comment]
Ah... very interesting. Thank you I will test this out. Can you share your code setup?

**Comment by danieldahan** [comment]
I confirmed the issue. Fixing it now :)

**Comment by danieldahan** [comment]
Try [Material 2.4.6](https://github.com/CosmicMind/Material/releases/tag/2.4.6) for a fix :) Thank you, this was a great find.
