### ISSUE TITLE
Adding another type of PulseView animation

### ISSUE THREAD

**Issue by jyounus** [CosmicMind/Material#641]
Hey there,

Any chance you'd consider adding a "new" type of animation? Basically I'd like the PulseView to have the same effect as if it was a standard iOS UITableViewCell highlight. This means it would instantly highlight the view when the user touches it, and then deselect with an animation.

It's pretty much exactly the same as the ```pulseAnimation = .backing``` animation, the only difference is it wouldn't delay the fade in. It would instantly highlight and then fade out using an animation once the user stops touching the view.

I know this doesn't have much to do with Material Design and rather a more iOS-y animation, but this would be perfect for my existing project.

**Comment by danieldahan** [comment]
Doesn't sound like a bad suggestion to me :) It will be out by the end of the month, along with all the other latest features.

**Comment by danieldahan** [comment]
Adding this for release Material 2.5.0.

**Comment by jyounus** [comment]
Nice one, thank you! I'll go ahead and close this "issue". :D

**Comment by danieldahan** [comment]
Hey, here is the [commit](https://github.com/CosmicMind/Material/commit/4b8a39b83d6262dad52d4b41d96a81ecbd7596ec) for your `feature request`. It will be out shortly in Material 2.5.0 :)

**Comment by jyounus** [comment]
Gave it a quick try, just what I wanted! Thank you!

**Comment by danieldahan** [comment]
Sweet :)
