### ISSUE TITLE
PageTabBar scrollable

### ISSUE THREAD

**Issue by tato469** [CosmicMind/Material#642]
There is any way to do the PageTabBar or TabBar scrollable? Else could be a nice improvement of this component.

**Comment by danieldahan** [comment]
Yes it is already in the works :) I will leave this up as a Feature Request. Thank you.

**Comment by brucehappy** [comment]
Hey @danieldahan , thanks very much for Material.  There is some great stuff in here.  Wondering where you were with the scrollable tab bar.  Didn't want to dive in myself if you were close to checking something in.  Thanks much.

**Comment by danieldahan** [comment]
Hey, thank you :)

I don't have anything coming in the immediate future, but near future yes. If you had some ideas you would want to share, that would be great.

**Comment by danieldahan** [comment]
@brucehappy The scrollable TabBar is almost done.

**Comment by brucehappy** [comment]
That's great, @danieldahan Looking forward to checking it out.  I've been using https://github.com/xmartlabs/XLPagerTabStrip .  Will your version implement what they call the "Button Bar" approach?

**Comment by danieldahan** [comment]
Not sure what the `Button Bar` approach is. Any links you want to share on that?

**Comment by brucehappy** [comment]
You can see it on the project page I linked to in the Readme section.

**Comment by danieldahan** [comment]
Then the answer is yes :)

**Comment by Akshayp101192** [comment]
If I add 10 tabs to base controller , How Can I make page tab controller swipable ?
How Can I change Line width of tab ?

**Comment by danieldahan** [comment]
@Akshayp101192 The width of the line will be automatic, and the swipe feature is automatic too. Are you having trouble at the moment with the PageTabBarController to achieve this?

**Comment by Akshayp101192** [comment]
@danieldahan  yes with  PageTabBarController I am having trouble . If I add 6 tabs and their tab titles are of greater length .tab width is fixed and upper tabs does not scroll . is there any property of PageTabBarController ? I need to get this done because I will have to make lot of changes in project if it does not work .. Please help me out !

**Comment by danieldahan** [comment]
I am working on that feature. It is in the development branch and almost ready to go. I have been making some really key updates, and unfortunately they are all necessary to release at once. I mentioned in another issue that I plan to have this done within a week. Hopefully that works for you :)

**Comment by ro22e0** [comment]
Hello, is there any update ?

Thanks in advance.

**Comment by ro22e0** [comment]
Hello, is there any update ?

Thanks.

**Comment by danieldahan** [comment]
@ro22e0 I am almost done. Finishing some documentation for `Motion's` latest release / rework. Finishing the TabsController next with a release.

**Comment by YoonjaeYoo** [comment]
Nice! Can't wait to check it.

**Comment by Akshayp101192** [comment]
Yes , In a severe need of update and specially scrollable tab pager controller .

**Comment by danieldahan** [comment]
This component has now been updated in [Material 2.8.0](https://github.com/CosmicMind/Material/releases/tag/2.8.0). Features like swiping have not been included in 2.8.0, and will be included in a following release. The overall TabsController adds stability and scrollable Tabs. I am closing this issue and thank you for your patience.
