### ISSUE TITLE
Card align to top

### ISSUE THREAD

**Issue by maba1984** [CosmicMind/Material#643]
Hi, i am not sure if this is a bug or if i did something wrong. Maybe you want to take a look at it...

http://stackoverflow.com/questions/41270762/how-to-position-top-in-ios-swift

**Comment by danieldahan** [comment]
I answered on `StackOverflow` :) It is not a big, it is AutoLayout not used correctly.

**Comment by maba1984** [comment]
i changed my code but still the same problem...

`import UIKit
import Material

class UserProfileViewController: UIViewController {
    fileprivate var card: Card!
    
    fileprivate var toolbar: Toolbar!
    fileprivate var moreButton: IconButton!
    
    fileprivate var contentView: UILabel!
    
    fileprivate var bottomBar: Bar!
    fileprivate var dateFormatter: DateFormatter!
    fileprivate var dateLabel: UILabel!
    fileprivate var favoriteButton: IconButton!
    

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor(red:0.15, green:0.24, blue:0.37, alpha:1.0)
        guard let tc = toolbarController else {
            return
        }
        tc.toolbar.height = 0
        tc.toolbar.isHidden = true
        prepareDateFormatter()
        prepareDateLabel()
        prepareFavoriteButton()
        prepareMoreButton()
        prepareToolbar()
        prepareContentView()
        prepareBottomBar()
        prepareImageCard()
        prepareMainView()


    }

}


extension UserProfileViewController {
    fileprivate func prepareMainView() {
        view.layout(card!).horizontally(left: 10, right: 10).top(10)
    }
    
    fileprivate func prepareDateFormatter() {
        dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .none
    }
    
    fileprivate func prepareDateLabel() {
        dateLabel = UILabel()
        dateLabel.font = RobotoFont.regular(with: 12)
        dateLabel.textColor = Color.blueGrey.base
        dateLabel.text = dateFormatter.string(from: Date.distantFuture)
    }
    
    fileprivate func prepareFavoriteButton() {
        favoriteButton = IconButton(image: Icon.favorite, tintColor: Color.red.base)
    }
    
    fileprivate func prepareMoreButton() {
        moreButton = IconButton(image: Icon.cm.moreVertical, tintColor: Color.blueGrey.base)
    }
    
    fileprivate func prepareToolbar() {
        toolbar = Toolbar(rightViews: [moreButton])
        
        toolbar.title = "Material"
        toolbar.titleLabel.textAlignment = .left
        
        toolbar.detail = "Build Beautiful Software"
        toolbar.detailLabel.textAlignment = .left
        toolbar.detailLabel.textColor = Color.blueGrey.base
    }
    
    fileprivate func prepareContentView() {
        contentView = UILabel()
        contentView.numberOfLines = 0
        contentView.text = "Material is an animation and graphics framework that is used to create beautiful applications."
        contentView.font = RobotoFont.regular(with: 14)
    }
    
    fileprivate func prepareBottomBar() {
        let clipboardButton = IconButton(image: UIImage(named: "clipboard_darken1.png"))
        let dashboardButton = IconButton(image: UIImage(named: "dashboard_darken1.png"))
        let bookmarkButton = IconButton(image: UIImage(named: "bookmark_darken1.png"))
        let dotsButton = IconButton(image: UIImage(named: "dots_darken1.png"))
        
        bottomBar = Bar()
        bottomBar.centerViews = [clipboardButton, dashboardButton, bookmarkButton, dotsButton]
    }
    
    fileprivate func prepareImageCard() {
        card = Card()
        
        card.toolbar = toolbar
        card.toolbarEdgeInsetsPreset = .square3
        card.toolbarEdgeInsets.bottom = 0
        card.toolbarEdgeInsets.right = 8
        
        card.contentView = contentView
        card.contentViewEdgeInsetsPreset = .wideRectangle3
        
        card.bottomBar = bottomBar
        card.bottomBarEdgeInsetsPreset = .wideRectangle2
    }
}`

**Comment by danieldahan** [comment]
What version of Xcode are you using? This is interesting, I tested your code and the Sample project and I am seeing behavior I have not seen before.

**Comment by maba1984** [comment]
I am using Version 8.2.1 of Xcode. I tried to add just the subviews "card.toolbar, card.contentView..." and that works fine. Just the hole card does not layout right.

**Comment by danieldahan** [comment]
The issue is that it is aligning from the center, not the top as would be expected. I am working on a fix now.

**Comment by maba1984** [comment]
Thank you:)

**Comment by danieldahan** [comment]
Fixed it, now running tests and confirming I didn't create any issues :) This was a really good catch.

**Comment by danieldahan** [comment]
Please update to [Material 2.4.3](https://github.com/CosmicMind/Material/releases/tag/2.4.3) and it should work perfectly with the suggestions I had made earlier. Thanks again, this was a really good catch.
