### ISSUE TITLE
How to change switch on, off programmatically

### ISSUE THREAD

**Issue by bayarmanlai** [CosmicMind/Material#644]
2.4.1 release note says **Removed Switch.setOn function**.

I  need to change it's state programmatically. How can I do that.

First time switch state changed, after that it doesn't change it's state when I set isOn variable value programmatically.

**Comment by danieldahan** [comment]
To change the state programmatically, use: 

```swift
let control = Switch()
control.switchState = .on
```

or 

```swift
let control = Switch()
control.setSwitchState(state: .on, animated:  true) { (control) in 
    // Do something
}
```

If you need any further help, please reopen or create a new issue :)

**Comment by bayarmanlai** [comment]
Thanks, for your update. Not it works as expected :)
