### ISSUE TITLE
How can I implement a snack bar functionality in my own UIViewController Class ? I want to do it programmatically.

### ISSUE THREAD

**Issue by vksid** [CosmicMind/Material#645]

**Comment by danieldahan** [comment]
Have you seen this [SnackbarController sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/SnackbarController) ?

**Comment by danieldahan** [comment]
Hey, I haven't heard from you. If you are still having issue, please reopen or create a new issue :) Thank you!
