### ISSUE TITLE
Problem of calling becomeFirstResponder()

### ISSUE THREAD

**Issue by jeantimex** [CosmicMind/Material#646]
Hi folks,

When I call becomeFirstResponder() in viewDidLoad, the label of the textfield disappears, see the screenshot below:
![simulator screen shot dec 26 2016 11 06 32 pm](https://cloud.githubusercontent.com/assets/565300/21493845/84bc0ade-cbc2-11e6-9ea3-b0594cbfa56f.png)

when I type in the keyboard, the label shows up:
![simulator screen shot dec 26 2016 11 07 00 pm](https://cloud.githubusercontent.com/assets/565300/21493846/866ea83c-cbc2-11e6-88c8-392ab4f6bcad.png)

Is this a known issue? And how to make sure the label shows when the textfield becomes first responder? Thanks!

**Comment by danieldahan** [comment]
Hey :) 

I tested this using the latest Material and [TextField sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/TextField), where all worked out well. What version of Material are you using and what is your setup?

**Comment by danieldahan** [comment]
I made a change which I think will help. I was able to reproduce your issue somewhat, and with the change I made it fixed it. I will be putting this for release now and you can let me know how it works out.

**Comment by danieldahan** [comment]
Try [Material 2.4.5](https://github.com/CosmicMind/Material/releases/tag/2.4.5) :) All the best.

**Comment by jeantimex** [comment]
Thank you so much @danieldahan for your prompt reply! I just tried 2.4.5 on iOS 10.2, Xcode 8.2.1 and I can still see the issue.

**Comment by danieldahan** [comment]
Can you share your setup, because it should work. As well, I updated the TextField again with [Material 2.4.6](https://github.com/CosmicMind/Material/releases/tag/2.4.6).

**Comment by jeantimex** [comment]
Thanks @danieldahan! I tried v2.4.6, and I can still the problem, but here is my workaround in Swift 3:
```
override func viewDidLayoutSubviews() {
  super.viewDidLayoutSubviews()
  _ = self.emailField.becomeFirstResponder()
}
```
I guess this might just be related to my application though, my first view controller has a full-screen size video playing in the background, when user taps on "Login" button, the navigation controller pushes the email view controller which has the Material component. 

I tried the following:

1. In `viewDidLoad`, after the email text field is setup completely, dispatch resignFirstResponder call to the main thread queue like so:
```
DispatchQueue.main.async {
  _ = self.emailField.becomeFirstResponder()
}
```
This works great, but somehow the animation looks jerky, so I changed to the 2nd solution, delay the dispatch like so (still in viewDidLoad):
```
let when = DispatchTime.now() + 0.3 // delay 300ms
  DispatchQueue.main.asyncAfter(deadline: when) {
  _ = self.emailField.becomeFirstResponder()
}
```
This time, it works fine when the view controller is pushed in, but when I navigate back and come back to this view again, the keyboard animation looks jerky again, so I have to call `resignFirstResponder` in viewWillDisappear.

Anyhow, doing so will make the keyboard have the slide-in animation and I don't like it, so eventually I decide to simply call `becomeFirstResponder` in `viewDidLayoutSubviews`.

I don't think it's a problem with Material UI component, I guess since the keyboard and the text field need to show the animation in the same thread and thus conflict.

I love this component, thanks again for your help!!!

**Comment by jeantimex** [comment]
Actually, the following code will produce a smoother animation with keyboard:
```
override func viewDidAppear(_ animated: Bool) {
  super.viewWillAppear(animated)
  DispatchQueue.main.async {
    _ = self.emailField.becomeFirstResponder()
  }
}
    
override func viewWillDisappear(_ animated: Bool) {
  super.viewWillDisappear(animated)
   _ = self.emailField.resignFirstResponder()
}
```

Works with multiple view controllers in navigation controller.

Cheers!

**Comment by danieldahan** [comment]
@jeantimex This is great insight. I will keep playing with the `TextField` and see if I can improve its setup. It is a pretty tricky component, as it has so many setup cases, and requires many moving parts simultaneously. I really appreciate your help and feedback :) Thank you!
