### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by elsesiy** [CosmicMind/Material#648]
Hi,

as this beautiful library already supports Cocoapods and Carthage it'd be great to have support for the [Swift Package Manager](https://swift.org/package-manager/) too. Is that something you'd consider adding soon? Otherwise I'm happy to make the changes and submit a PR.

Cheers!

**Comment by danieldahan** [comment]
Hey, thank you :) A PR would be great actually. I have some other feature requests I am working on. If you don't get a chance to send one over, I will get to it soon. I placed it on the project board. Thank you.

**Comment by elsesiy** [comment]
@danieldahan I just started working on that just to find out that SPM still doesn't fully support iOS (you're relying on UIKit a lot). The initial issue has been discussed [here](http://stackoverflow.com/questions/34778823/swift-package-manager-uikit-dependency) and has been picked up by many repositories, i.e. [CocoaPods](https://github.com/CocoaPods/pod-template/issues/157). I guess we just have to wait until support is added...

**Comment by danieldahan** [comment]
Yeah, I hope support does come soon. CocoaPods is common for iOS packages in general pre swift. I will close this for now, and when there is support, we can make it happen :)
