### ISSUE TITLE
Having issues getting pulse effect when implementing in application

### ISSUE THREAD

**Issue by ty7466** [CosmicMind/Material#649]
Hello I am having an issue getting the pulse effect to happen on any of the buttons. I tried copying the same button that is in the sample and still not able to get it to work. Is there anything special that needs to be done?

Thank you ahead of time!

**Comment by danieldahan** [comment]
Hey :)

Can you show me your setup? Also, check the `pulseColor` and that you are using either `Button`, `FlatButton`, `FabButton`, or `RaisedButton`.

**Comment by ty7466** [comment]
wow thank you for the fast response!!! I figured it out, I was missing some code!!! Rookie mistake!!!

**Comment by danieldahan** [comment]
No worries :) Anytime you need help, feel free to ask.
