### ISSUE TITLE
NavigationController back button moves on each display of a view instance

### ISSUE THREAD

**Issue by travishaagen** [CosmicMind/Material#650]
With `NavigationController`, when I push/pop the _same_ instance of a given view, the toolbar's back-button moves to the right each time the view is pushed again. Tested with v2.4.6.

```
let nextView = MyViewController()
...
navigationController?.pushViewController(nextView!, animated: true)
```

If I create a new instance of the view every time I push it to the `NavigationController`, this problem does not occur.

**Comment by danieldahan** [comment]
Can you send a sample project of this? :) Thank you!

**Comment by travishaagen** [comment]
Here you go, just run `carthage update` and repeatedly navigate forward/back using the toolbar icons.

[Issue650.zip](https://github.com/CosmicMind/Material/files/681132/Issue650.zip)

**Comment by danieldahan** [comment]
Yes, thank you :) I will fix for the next release.

**Comment by danieldahan** [comment]
Looking into this today. Thank you!

**Comment by volkangurol** [comment]
hi, i want to reorder leftViews' buttons, and when i write this, left side is shifting

navigationItem.leftViews = [menuButton, navigationItem.backButton]

<img width="357" alt="screen shot 2017-03-13 at 06 41 09" src="https://cloud.githubusercontent.com/assets/2510054/23840707/22e26784-07b0-11e7-9d45-2d406998f793.png">

**Comment by danieldahan** [comment]
Hey, sorry this has not been fixed yet. Let me take a look :)

**Comment by muzoman** [comment]
I'm seeing this exact same issue in 2.12.16. Is this supposed to be fixed Daniel?

**Comment by muzoman** [comment]
OK, that's great, thank you Daniel.

**Comment by danieldahan** [comment]
@muzoman anytime. My majority of time is working on the education center. So I am splitting support and that for the next little while. Normally, issues are fixed faster.

**Comment by muzoman** [comment]
@danieldahan what timescales do you reckon it might me fixed in then? Just pondering whether to re-engineer my App to not cache all it's view controllers...

**Comment by danieldahan** [comment]
@muzoman  I'll release this fix by Friday if it is fixable, which it will most likely be :)

**Comment by muzoman** [comment]
@danieldahan that is awsome! :-) Will wait, plenty of other things to do!

**Comment by danieldahan** [comment]
sweet :)

**Comment by muzoman** [comment]
Hi @danieldahan,

Managed to get time to look at this issue yet?

Cheers!
Jim

**Comment by danieldahan** [comment]
Looking today :)

**Comment by danieldahan** [comment]
Issue has been fixed and will be in the next release. This is the commit 6f9f6ca92d83e1a4be5eeedecac8728323a66f00. Thank you! :)
