### ISSUE TITLE
Dynamically add view controllers to PageTabBarController

### ISSUE THREAD

**Issue by timoschwarzer** [CosmicMind/Material#651]
Hello! It's me again...

Is is possible to dynamically add an unspecified amount of view controllers to a PageTabBarController?
I've already tried with:
```
self.addChildViewController(newSubstitutesListFragment)
self.viewControllers.append(newSubstitutesListFragment)
```
but that didn't work. I think I need a hint ;-)

Thanks!

**Comment by timoschwarzer** [comment]
Okay, I found a way that kinda works:
```
self.viewControllers = self.substituteFragments
self.setViewControllers([self.viewControllers[0]], direction: .forward, animated: false)
```
But I don't know if there is a more elegant way to do this...

**Comment by danieldahan** [comment]
Hey, this is the correct way for now 

```swift
self.setViewControllers([self.viewControllers[0]], direction: .forward, animated: false)
```

That said, I am rewriting the entire PageTabBar. There are many updates I would like to add to it. There is already a card for this https://github.com/CosmicMind/Material/issues/608 so I will close this issue and you can follow that one :) Thank you for bringing this to our attention.
