### ISSUE TITLE
Allow PageTabBarController to programmatically change view controller.

### ISSUE THREAD

**Issue by danieldahan** [CosmicMind/Material#652]
[Associated StackOverflow question.](http://stackoverflow.com/questions/41464822/how-do-you-transition-tab-bar-controller-programmatically-i-need-to-switch-the).

**Comment by LuckyFA** [comment]
I did it like this for a temporary solution:
`tabBar.pageTabBar.buttons[index].sendActions(for: .touchUpInside)`

**Comment by danieldahan** [comment]
Excellent that you have made a temporary solution. I am almost done the addition of the animation and transition library for Material, and that is what I am going to use for the `PageTabBar`. It will be available soon. Thanks for your patience :)

**Comment by danieldahan** [comment]
This is the same feature request as https://github.com/CosmicMind/Material/issues/608. 
Please follow that issue. Thank you!
