### ISSUE TITLE
Placeholder keeps showing on TextField when I set a value programatically

### ISSUE THREAD

**Issue by andressaribeiro** [CosmicMind/Material#653]
Hi, I'm using Material v2.4.6 and I'm setting a text to a TextField programatically after the user chooses an option on a UIPickerView, but the Placeholder keeps showing and the text gets overlaid by it. Is there a fix for that? 

Thanks in advance

**Comment by danieldahan** [comment]
Can you share your code setup :) ?

**Comment by andressaribeiro** [comment]
Basically I have two textfields and one of them should behave as a dropdown, take a look:

`
import UIKit
import Material

class ViewController: UIViewController, UIPickerViewDelegate, UIPickerViewDataSource, UITextFieldDelegate {
    
    @IBOutlet weak var textField: TextField!
    
    @IBOutlet weak var textField2: TextField!
    
    var options = ["Option 1", "Option 2"]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let pickerView = UIPickerView()
        pickerView.delegate = self
        pickerView.dataSource = self
        pickerView.tag = 10
        textField.delegate = self
        textField.inputView = pickerView
        textField.dividerActiveColor = UIColor.black
        textField.placeholderActiveColor = UIColor.black
    }

    func textFieldDidEndEditing(_ textField: UITextField) {
        if textField.tag == textField.tag {
            let selectedRow = (textField.inputView as! UIPickerView).selectedRow(inComponent: 0)
            textField.text = options[selectedRow]
        }
    }
    
    public func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    public func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return options.count
    }
    
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return options[row]
    }
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        return false
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if let nextField = textField.superview?.viewWithTag(textField.tag + 1) as? UITextField {
            nextField.becomeFirstResponder()
        } else {
            textField.resignFirstResponder()
        }
        return false
    }
    
}
`

Thank you!

**Comment by danieldahan** [comment]
Since you are using Storyboards, can you send this as a sample project? I don't know what you have as constraints, so replicating the issue is tricky.

**Comment by andressaribeiro** [comment]
I have just sent it, take a look. Thanks!

**Comment by danieldahan** [comment]
Yes, looking now :)

**Comment by danieldahan** [comment]
Fixed your issue, I will make a release :)

**Comment by danieldahan** [comment]
Please find your fix in [Material 2.4.8](https://github.com/CosmicMind/Material/releases/tag/2.4.8). Thank you :) If you have any further issues, please reopen or create a new issue.

**Comment by andressaribeiro** [comment]
Thank you very much, it works perfectly now!

**Comment by danieldahan** [comment]
Keep the issues coming if you have them :) I am updating Material this entire month based off the great feedback and usage you and others are doing :)
