### ISSUE TITLE
Error installing Material

### ISSUE THREAD

**Issue by Rensothearin** [CosmicMind/Material#654]
Today when I tried installing Material and this error occured:

```
[!] Error installing Material
[!] /usr/bin/git clone https://github.com/CosmicMind/Material.git /var/folders/l4/947rqfxn3ng_rfsvdxdjfczc0000gn/T/d20170110-11756-bdn33q --template= --single-branch --depth 1 --branch 2.0.0

Cloning into '/var/folders/l4/947rqfxn3ng_rfsvdxdjfczc0000gn/T/d20170110-11756-bdn33q'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Please tell me what is the cause of this error. Thanks in advance.

**Comment by danieldahan** [comment]
How are you trying to install it, it looks like the connection failed. Have you tried again today?

**Comment by Rensothearin** [comment]
I tried to install it again after that. Now it's successfully installed.
Thank you so much for helping me.

**Comment by danieldahan** [comment]
No worries :) All the best!

**Comment by danieldahan** [comment]
Make sure you are using the latest `Material`. If you are using CocoaPods you might need to run this before installing: 

```bash
pod cache clean --all
```

**Comment by Rensothearin** [comment]
I resolved the error by going to `pod install` again to get the latest version of `Material`. However after doing that, my code still had error `Use of unresolved identifier 'Motion'`. Suddenly, I tried this by going to this code block:
```
open override func openMenu(completion: ((UIView) -> Void)? = nil) {
        super.openMenu(completion: completion)
        menu.views.first?.animate(animation: Motion.rotate(angle: 45))
}
```
and remove `Motion.rotate(angle: 45)` and then type it again. By doing so, the error disappeared.

**Comment by danieldahan** [comment]
Interesting. So all is good now?

**Comment by Rensothearin** [comment]
All is good now. Again, thanks for helping me out. :)

**Comment by danieldahan** [comment]
All the best and thank you for sharing your issue :)
