### ISSUE TITLE
 Icon subclassing

### ISSUE THREAD

**Issue by aperritano** [CosmicMind/Material#656]
@danieldahan is there a way I can setup my custom icons using the factories based on your Icon libs use, e.g. public static let image = Icon.icon("cm_image_white"). it is so optimal. would inheriting Icon and defining my own bundle work?

Daniel Dahan @danieldahan
@aperritano Can you make the Icon subclassing a Feature Request? It will help me track the investigation and work.

**Comment by danieldahan** [comment]
Excellent! Thank you, will take a look this weekend.

**Comment by danieldahan** [comment]
The solution for this is in this issue https://github.com/CosmicMind/Material/commit/0223578fb7b534f9e612a11de0a6661904ea58b6
