### ISSUE TITLE
TableViewWithinCard cell width broken when placed in scroll view.

### ISSUE THREAD

**Issue by HybridHB** [CosmicMind/Material#657]
Hello, Im seeing a problem with tableView cell widths being too narrow when placing a TableViewWithinCard inside of a scroll view. I modified the example that shows the problem. Any help on how to fix this would be appreciated.

import UIKit
import Material

class ViewController: UIViewController {
    /**
     Retrieves the data source items for the tableView.
     - Returns: An Array of DataSourceItem objects.
     */
    open var dataSourceItems = [DataSourceItem]()

    fileprivate var toolbar: Toolbar!
    fileprivate var tableView: TableView!
    fileprivate var card: Card!
    
    fileprivate var scrollView: UIScrollView!
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        prepareScrollView()
        prepareToolbar()
        prepareTableView()
        prepareCard()
        prepareData()
     }
}

extension ViewController {
    fileprivate func prepareToolbar() {
        toolbar = Toolbar()
        toolbar.title = "TableView Within Card"
        toolbar.detail = "Sample"
    }
    
    fileprivate func prepareTableView() {
        tableView = TableView()
        tableView.height = 10
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(TableViewCell.self, forCellReuseIdentifier: "TableViewCell")
    }
    
    fileprivate func prepareCard() {
        card = Card()
        card.toolbar = toolbar
        card.contentView = tableView
        
        // Add card to mainView, shows working cell widths
        //view.layout(card).horizontally(left: 20, right: 20).center()
        //view.layout(card).top(40)
        
        // Add card to scrollView, shows broken cell widths
        scrollView.layout(card).horizontally(left: 20, right: 20).center()
        scrollView.layout(card).top(40)
    }
    
    fileprivate func prepareData() {
        tableView.height = 300
        let persons = [["name": "Daniel"], ["name": "Sarah"]]
        for person in persons {
            dataSourceItems.append(DataSourceItem(data: person))
        }
        tableView.reloadData()
    }
    
    fileprivate func prepareScrollView(){
        scrollView = UIScrollView()
        scrollView.backgroundColor = Color.blueGrey.base
        view.layout(scrollView).horizontally(left: 0, right: 0).center()
        view.layout(scrollView).vertically(top: 0, bottom: 0).center()
    }
}

extension ViewController: TableViewDelegate {}

extension ViewController: TableViewDataSource {
    @objc
    open func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    @objc
    open func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dataSourceItems.count
    }
    
    @objc
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TableViewCell", for: indexPath) as! TableViewCell
        
        guard let data = dataSourceItems[indexPath.row].data as? [String: String] else {
            return cell
        }
        
        cell.textLabel?.text = data["name"]
    
        
        return cell
    }
}

**Comment by danieldahan** [comment]
Hey, I will be able to look at this tomorrow :)

**Comment by danieldahan** [comment]
Hey, so I had been playing around with your code and it is a really weird situation. Very interesting actually. I read throughout StackOverflow and it seems that the layout of the default `textLabel` behaves different in various situations. So I did an experiment and added a `UILabel` to the `TableViewCell` with the following code:

```swift
cell.width = view.bounds.width

let label = UILabel()
label.text = data["name"]
label.frame = cell.bounds

cell.addSubview(label)

return cell
```

This is in the `func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell` call. 

You can probably trim it down, and all seemed to work. So my suggestion for this case would be to add a label of your own and manage it in a subclass of `UITableViewCell` or `TableViewCell`. 

If you continue to have an issue, please reopen or create a new one. Thank you! :)
