### ISSUE TITLE
Is there a way to disable placeholder animation while entering text?

### ISSUE THREAD

**Issue by adeesh** [CosmicMind/Material#658]
Hello,
I am new to Material library.

i have a custom requirement where i don't want to have animation where placeholder of text fields animates to top left. But i do need other feature of Textfield.

I tried looking into implementation of Text Field but didn't find anything concrete. Please suggest.

**Comment by danieldahan** [comment]
Hey :) Welcome. 

There is this boolean:

```swift
textField.isPlaceholderAnimated = false
```

It wont animate, but will be at the top. Is that what you are looking for?

**Comment by adeesh** [comment]
We don't want to show it on top when user types i.e. default behavior of UITextfield. But we do want to show error message like Material TextField provides.

**Comment by danieldahan** [comment]
So to confirm, you want the placeholder, but not the animation ? Or you don't want it at all. If you don't want it at all, you don't need to set it. Otherwise, I may need to consider this a feature request.

**Comment by adeesh** [comment]
yes we want placeholder but not animation.

**Comment by danieldahan** [comment]
Okay that would be a feature request then. I can make that for you :)

**Comment by adeesh** [comment]
Thanks Daniel for quick support.

**Comment by adeesh** [comment]
How much time it usually take to add this type of feature?

**Comment by danieldahan** [comment]
I will make it work within the next couple days, latest the end of the week.

**Comment by danieldahan** [comment]
I will aim to get this out to you today.

**Comment by adeesh** [comment]
Thanks Daniel for update

**Comment by danieldahan** [comment]
Hey, so the update is in [Material 2.4.11](https://github.com/CosmicMind/Material/releases/tag/2.4.11). To use it, set the `placeholderAnimation` enum like so:

```swift
textField.placeholderAnimation = .hidden
```

That should do it :) All the best!

**Comment by adeesh** [comment]
Thanks @danieldahan , Its working.
