### ISSUE TITLE
PageTabBarController Position and Tab length issue.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CosmicMind/Material#660]
Heyy congrats for such a great library. I have few issues with the PageTabBarController. The following screenshot can be referred for the issues

<img width="346" alt="pagetabbar" src="https://cloud.githubusercontent.com/assets/15869731/22023545/9a129430-dcec-11e6-91b3-97f20c08271e.png">

**1. Position of Tab**  
I tried the following piece of code for positioning the tab to top of View Controller:
`        view.layout(pageTabBar).horizontally().top(CGFloat(20))`

That moved the tab to top but left behind the bottom white view. _**How to hide the same?**_

**2. TitleText is not scrollable and gets truncated.**

Title text gets truncated and is also not scrollable if the text is long. **_So is there any property for dynamic width and scrollable tab?_**

**Comment by danieldahan** [comment]
Hey :) Thank you!

For your questions:

1. Use the `pageTabBarAlignment` property of the `PageTabBarController`. 

2. I am adding in dynamic width feature, as I am rewriting the `PageTabBarController` component. I am almost done the new `MotionAnimation` and `MotionTransition` library for Material, which is what I need for the updates. 

If you have any other issues, please reopen or create a new one :)
