### ISSUE TITLE
Enable setting left inset for TextView

### ISSUE THREAD

**Issue by balazsgerlei** [CosmicMind/Material#663]
It would be nice to give an option to set left inset for the text (and placeholder) in TextView.

**Comment by danieldahan** [comment]
I will add this in the new updates I am making for TextView and Editor :) Always happy to receive suggestions, thank you!

**Comment by danieldahan** [comment]
Hey, please find your feature request in [Material 2.6.0](https://github.com/CosmicMind/Material/releases/tag/2.6.0) and a sample [TextView](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TextView) project. Thank you and all the best!
