### ISSUE TITLE
Enable setting different color for inactive placeholder when text is entered or not for TextField

### ISSUE THREAD

**Issue by balazsgerlei** [CosmicMind/Material#665]
If I set a background to the TextField, the same color is not always appropriate for the placeholder in inactive mode (when the cursor is not in the TextField) for when text is entered and when nothing is entered. It would be very useful to be able to set two different colors for the placeholder when text is entered and when not.

Thank you in advance!

**Comment by danieldahan** [comment]
Hey! 

Take a look at the following properties available for the `TextField`. 

```swift
textField.placeholderNormalColor = Color.amber.darken4
textFieldField.placeholderActiveColor = Color.pink.base
textFieldField.dividerNormalColor = Color.cyan.base
textFieldField.dividerActiveColor = Color.green.base
```

All the best :)

**Comment by balazsgerlei** [comment]
Sorry for the quite late response.
Yes, I tried these properties, but the thing is that I would like to specify a different color for the placeholder label when text is entered and when not. This is because if I use a dark background for the screen and a light background for the TextField itself, netiher a light or a dark color work for the "placeholderNormalColor", as the placeholder is inside the TextField when text is not entered and outside the TextField when text is entered.

Since I created this issue I switched to using my own TextField implementation (mainly not because of this problem) so the solution for this is not urgent for me in any way, but I still think it could be a nice addition to the library. But at this point it is only a suggestion, you may decide if it worth implementing it.

Cheers!
