### ISSUE TITLE
How to set Toolbar elevation/shadow?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#667]
How can I set Toolbar elevation/shadow?
Didn't you implement that?

I am currently overriding ```layoutSubviews``` method of the ToolbarController to achieve that.

```swift
override func layoutSubviews() {
    super.layoutSubviews()
    
    let b = self.toolbar.bounds
    let c = CGRect(x: 0.0, y: b.height, width: b.width, height: 0.25) // tiny shadow line below toolbar by the value of height
    let shadowPath = UIBezierPath(rect: c)
    self.toolbar.layer.masksToBounds = false
    self.toolbar.layer.shadowColor = UIColor.black.cgColor
    self.toolbar.layer.shadowOffset = CGSize.zero
    self.toolbar.layer.shadowOpacity = 0.5
    self.toolbar.layer.shadowPath = shadowPath.cgPath
}
```

**Comment by danieldahan** [comment]
Hey! 

You can set the `depthPreset` or `depth` property, for example:

```swift
toolbar.depthPreset = .depth2
```

That's all you need :) All the best!

**Comment by OrkhanAlikhanov** [comment]
@danieldahan they don't work though.
I set `toolbar.backroundColor` to `.clear. Can this be the case?`

**Comment by danieldahan** [comment]
Yes, because when it is clear, iOS will set the background on whatever is being drawn.

**Comment by OrkhanAlikhanov** [comment]
Do you think that it is worth including `forceShadow()` method  into the library for whom did `backgroundColor = .clear`?

**Comment by danieldahan** [comment]
Well the issue I see with that is that it will have to create a background color, which will have the developer want to change that color. Currently, it is defaulted to white, which is pretty much a force shadow unless you change or remove the color.
