### ISSUE TITLE
Implement Switch.buttonOnImage and Switch.buttonOffImage. Make Switch.trackThickness and Switch.buttonDiameter public

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#668]
I like this library's Switch control which has nice effects (bounce, ripple) but I had to customize it a little bit.
Please consider this for the future releases.

```swift
class OyanSwitch: Switch {
    override func prepare() {
        super.prepare()
        self.buttonOnColor = .white
        self.buttonOffColor = .white
        self.trackOnColor = .white
        self.trackOffColor = .white
        self.buttonOnImage = #imageLiteral(resourceName: "switch_on")
        self.buttonOffImage = Icon.favorite
        
        self.trackThickness = 24
        self.buttonDiameter = 24
    }
    override var intrinsicContentSize: CGSize {
         return CGSize(width: 50, height: 24)
    }
```

And setting images inside [updateColorForState](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/Switch.swift#L424)
```swift 
button.setImage(buttonOnImage, for: .normal)
button.setImage(buttonOffImage, for: .normal)
```

sharing the uncompleted current switch  :)

![image](https://cloud.githubusercontent.com/assets/15037839/22303264/ebac7fb2-e34b-11e6-9612-451bfbd31b6d.png)

**Comment by danieldahan** [comment]
Ah... interesting. Cool, I will leave this as a feature request and look into it for the upcoming releases. Thank you very much :)

**Comment by OrkhanAlikhanov** [comment]
@danieldahan Noone seems to have the same feature request that I had last year. But I can implement this or we can just close the issue. What do you say?

**Comment by danieldahan** [comment]
I think this would be a nice addition. Let's do it. If we have an issue for it, let's close this one, or the other so their is only one to follow. Thank you!

**Comment by OrkhanAlikhanov** [comment]
It's only this. You may assign me to the issue.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!

**Comment by hardikamal** [comment]
@danieldahan Any update on this?

**Comment by OrkhanAlikhanov** [comment]
@hardikamal it's abandoned feature. What do you need, exactly this feature?

**Comment by hardikamal** [comment]
@OrkhanAlikhanov Yes. I need the same feature. How do I achieve this?

**Comment by OrkhanAlikhanov** [comment]
Hey @hardikamal, check out #1221 it implements the needed feature.

**Comment by hardikamal** [comment]
@OrkhanAlikhanov I was using the switch in UIBarButtonItem custom view but after the change, the button does not appear on the uinavigationbar

**Comment by OrkhanAlikhanov** [comment]
How are you creating it? 

If you are using Material's `NavigationController`, we do not support using `UIBarButtonItem` stuff with it. Instead, you should be using our api `navigationItem.leftViews = [mySwitch]`

**Comment by hardikamal** [comment]
But It was working with UIBarButtonItem

**Comment by OrkhanAlikhanov** [comment]
I understand, that's why I asked how you create your bar button.  Following should work:
```swift
mySwitch.frame.size = mySwitch.intrinsicContentSize
navigationItem.leftBarButtonItem = UIBarButtonItem(customView: mySwitch)
```

**Comment by hardikamal** [comment]
It worked thanks a lot.
