### ISSUE TITLE
NavigationItem: leftViews and rightViews are not animated?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#669]
Why is the views that I put inside `leftViews` and `rightViews` of the `NavigationItem` not being animated when I use the swipe back gesture of `NavigationViewController`?

I do see that backButton is [inserted](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationController.swift#L150) into `leftViews` and it does be animated when I do so. What is the point that I am missing?

**Comment by OrkhanAlikhanov** [comment]
They stay static while back button is moving with above view controller. Maybe back Button is handled by the iOS API?

**Comment by OrkhanAlikhanov** [comment]
OK got it, the point that I was overlooking is that I was anticipating the below viewController's leftViews and rightViews to be animated as well while that of above viewController's were animating. However, the default UINavigationContoller does not do this as a design. I apologize for wasting whomever I disturbed :/

**Note:** above and below viewControllers refers to the viewControllers that are in sight when we are moving the finger left and right performing back swipe gesture.

**Comment by danieldahan** [comment]
Ah no worries, and with MotionTransition, which I am working on, you will be able to do such animations. All the best :)
