### ISSUE TITLE
Can Icons of Tab bar buttons be set to bottom of Title ?

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CosmicMind/Material#670]
Hi, Is there any property by which we can set image of tab bar button to bottom  of the text as below attached screenshot :

<img width="79" alt="screen shot 2017-01-27 at 2 47 12 pm" src="https://cloud.githubusercontent.com/assets/15869731/22365830/9b314b6c-e49f-11e6-9310-2c03d5549a4f.png">

**Comment by danieldahan** [comment]
Hey :) At the current moment they only set at the bottom. You could however set this type of behaviour with a custom UIView that is set within the `UIButton` property for the `TabBar`. Let me know if you need any further help, all the best!
