### ISSUE TITLE
Unable to use Material 2 in Xcode 8.2.1

### ISSUE THREAD

**Issue by vineetsansare** [CosmicMind/Material#673]
Hello guys,

Firstly, thank you for such a lovely library. 

Well, I'm working with Swift 3 using Xcode 8.2.1 and I installed Material 2.0 with Cocoapods. But I'm facing build time errors. Can you tell why is this happening? What am I missing?

# My Podfile looks like this -

  ```
source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'
  target 'Material2' do
  use_frameworks!
	pod 'Material', '~> 2.0'
   end
```
# Attaching the screenshot below -

![screen shot 2017-02-02 at 12 40 35 pm](https://cloud.githubusercontent.com/assets/6418402/22540361/bf9c323c-e945-11e6-933a-1881c2097ce6.png)

**Comment by hisham2007** [comment]
I face a similar issue. 
It fails in compile time:
"module compiled with swift 3.0 cannot be imported in swift 3.0.2"

**Comment by danieldahan** [comment]
Hey :) 

That is strange, everything is working for me. I will look into this. Thank you for bringing the issue to my attention.

**Comment by danieldahan** [comment]
So I cannot reproduce this issue. Possibly clear your Derived Data folder. Also clean the project and make sure that you don't have old builds around. If the issue persists, please reopen the issue. Thank you!

**Comment by vineetsansare** [comment]
@danieldahan Thanks for your reply. Closing the Xcode, Rebooting the machine and then with a fresh clean & build did the trick for me! Wonder how!!! :-\
Anyway, thanks again :)

Cheers!
