### ISSUE TITLE
Scrim color for NavigationDrawerController

### ISSUE THREAD

**Issue by dmwesterhoff** [CosmicMind/Material#675]
To my knowledge the 'dimming' of the root view controller content is done like so in the code:
`s.rootViewController.view.alpha = 0.5`

A possible enhancement to provide more flexibility could be a "scrim color" property (android nomenclature).

The user could optionally set a scrim color, behind the scenes this might be layered over the root view controller and set to full transparency when drawers are closed. When the drawers open the scrim color layer animates to the correct opacity.

The benefits are twofold, the user gets the flexibility of being able to set the dim factor as well as the dimming color.

**Comment by danieldahan** [comment]
Yes, this is a great suggestion and has been added in Material 2.5.0 for the FABMenu. I will look at adding it to other similar style views. Thank you! I will leave this open as a feature request until I release.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
