### ISSUE TITLE
Multi line UILabel not laying out correctly

### ISSUE THREAD

**Issue by HybridHB** [CosmicMind/Material#676]
In the presenter card sample with no modifications, the text in the content view (uilabel) is truncated instead of word wrapping like the sample image on the main project page. This happens with every sample project Ive tried.

**Comment by danieldahan** [comment]
Hey, nice catch. Please find a fix in [Material 2.4.12](https://github.com/CosmicMind/Material/releases/tag/2.4.12). The samples have been updated as well. Thank you!
