### ISSUE TITLE
Trouble setting Card contentView to anything but UILabel

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Material#678]
Possible regression in 2.4.13 in comparison to 2.4.0:

I cannot set `card.contentView = detailView` when `detailView` is a `UIView`
This makes the layout messed up:
<img width="586" alt="screen shot 2017-02-06 at 14 02 19" src="https://cloud.githubusercontent.com/assets/14074538/22648196/c74aba20-ec75-11e6-8faa-c12b98c2a465.png">

The detailView is orange in the screenshot and the card is green. The elements (TextView, TextView, FlatButton) inside detailView are constrained like this:
```
detailView.addConstraint(NSLayoutConstraint(item: passwordField, attribute: .leading, relatedBy: .equal, toItem: detailView, attribute: .leading, multiplier: 1.0, constant: 8))
detailView.addConstraint(NSLayoutConstraint(item: passwordField, attribute: .trailing, relatedBy: .equal, toItem: detailView, attribute: .trailing, multiplier: 1.0, constant: -8))
detailView.addConstraint(NSLayoutConstraint(item: passwordField, attribute: .centerY, relatedBy: .equal, toItem: detailView, attribute: .centerY, multiplier: 1.0, constant: -80))

```
Is there a workaround or do you need to change something?

I tried to find a sample that works, but the only one I found doesn't:
<img width="733" alt="screen shot 2017-02-06 at 14 05 45" src="https://cloud.githubusercontent.com/assets/14074538/22648212/db76fd74-ec75-11e6-97cc-f81b252ce6d8.png">

**Comment by danieldahan** [comment]
I tried the sample and it should work with the latest [Material 2.4.15](https://github.com/CosmicMind/Material/releases/tag/2.4.15). If the issue persists, please reopen or create a new issue. Thank you!

**Comment by theolof** [comment]
Yes, I got it to work. Had to set the height of the detailView, i.e. `detailView.height = 300`.
