### ISSUE TITLE
Tabbar covered when using PageTabBarController inside NavigationController

### ISSUE THREAD

**Issue by BenBeng** [CosmicMind/Material#679]
<img width="760" alt="c04219a2f60e723b34861d70f4d1434f" src="https://cloud.githubusercontent.com/assets/2141846/22726235/4d40eef4-ee0d-11e6-993e-908d46796f97.png">

Tabbar was covered by navigation bar which worked fine in `2.4.9`.
And I noticed there were some changes about tabbar in `2.4.10`.
So how can I get tabbar showed? Need your help.

**Comment by xaviermawet** [comment]
Hi,

I'm facing the same issue. I simply wanted to put a `PageTabBarController` with `Alignment = .top` as the rootViewController of a `NavigationController`, but it seams that the "page tab" are hidden (covered) by the NavigationBar of the `NavigationController` (page tabs are still at the top of the screen instead of being below the navigation bar).

The issue doesn't appear with `ToolbarController`.

Here is a sample code :

```swift
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        
        let vc1 = UIViewController()
        vc1.pageTabBarItem.title = "VC1"
        vc1.pageTabBarItem.titleColor = Color.white
        
        let vc2 = UIViewController()
        vc2.pageTabBarItem.title = "VC2"
        vc2.pageTabBarItem.titleColor = Color.white
        
        let appPageTabBarController = PageTabBarController(viewControllers: [vc1, vc2])
        appPageTabBarController.pageTabBarAlignment = .top
        appPageTabBarController.pageTabBar.lineAlignment = .bottom
        appPageTabBarController.pageTabBar.lineColor = Color.blue.lighten3
        appPageTabBarController.pageTabBar.backgroundColor = Color.blue.darken2
        
        // Don't work with NavigationController
        let appNavigationController = NavigationController(rootViewController: appPageTabBarController)
        // Work as expected with ToolBarController
        // let appToolBarController = ToolbarController(rootViewController: appPageTabBarController)
        
        
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = appNavigationController
        window?.makeKeyAndVisible()
    }
}
```

Thanks for your help,
Xavier

**Comment by danieldahan** [comment]
Yes, there is an issue with the NavigationBar. I know what it is and have already been working on a fix. It should be done soon. Please use the following issue to track https://github.com/CosmicMind/Material/issues/681 updates.

Thank you for sharing the issue.
