### ISSUE TITLE
How to do Navigation Bar translucent?

### ISSUE THREAD

**Issue by tayo119** [CosmicMind/Material#680]
When i do:
navigationBar.isTranslucent=true
![captura de pantalla 2017-02-08 a las 12 29 00](https://cloud.githubusercontent.com/assets/25578846/22735487/380393d8-edfa-11e6-8706-e71814be08c7.png)
New element called UIBarBackground with UIVisualEffectView appears on the NavigationBar and I can't do  the NavigationBar translucent.
In previous versions works.
Help me please.

**Comment by danieldahan** [comment]
Sorry about that. Yes, there was a regression. I am working on it in the following issue: https://github.com/CosmicMind/Material/issues/681, please follow that one.

Thank you for sharing the issue.
