### ISSUE TITLE
NavigationBar color breaking change?

### ISSUE THREAD

**Issue by svachmic** [CosmicMind/Material#681]
Hi,

I used version 2.4.10 in [my code](https://github.com/svachmic/ios-url-remote/blob/master/URLRemote/Classes/Controllers/ActionsCollectionViewController.swift) and had NavigationBar adjustment just as I wanted to. But after updating to 2.4.16, my NavigationBar colors are not being set leaving the bar white and status bar black.

Have there been any breaking changes in the last minor versions? Thank you!

**Comment by danieldahan** [comment]
Hey, yes, there is a translucency issue, which I am resolving. A fix should be available very soon.

**Comment by Ybrin** [comment]
+1

**Comment by danieldahan** [comment]
@Ybrin working on a solution for this.

**Comment by xaviermawet** [comment]
Is there any updates (release?) coming soon fixing issues about the Navigation{Bar|Controller} ? Regards.

**Comment by danieldahan** [comment]
Yes, I am working on it for the next release. Basically the hold up is going through everything to make sure all works well and to hammer off many issues with this release. Sorry for any delays.

**Comment by svachmic** [comment]
Hi Daniel,
thanks for the 2.5.0 release 🎉. However nothing has changed with regards to the bar color. Are we doing something wrong or is it really a bug? Should I style my bar in a different way?
Thanks!

**Comment by danieldahan** [comment]
No, you are correct. I didn't want to wait longer to release 2.5.0, so I will release this fix and a few others in 2.5.1. I will be working on it today and tomorrow. So it shouldn't be more than a day to get this to you.

**Comment by danieldahan** [comment]
@svachmic Hey :) Can you test the `development` branch and let me know if this solves the issue? Also, I didn't have an issue setting the background color in general, so if you could share some code if the proposed solution does not fix your issue. Thank you!

**Comment by danieldahan** [comment]
So I was able to revert back to the original setting. All should be fixed. If the issue persists, please reopen this issue. Thank you!

**Comment by danieldahan** [comment]
You should be able to find the fix in [Material 2.5.1](https://github.com/CosmicMind/Material/releases/tag/2.5.1). Thank you :)

**Comment by svachmic** [comment]
Confirming fully working code! Thanks!

**Comment by danieldahan** [comment]
@svachmic anytime :)
