### ISSUE TITLE
Material update start some issue

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Material#682]
I am using 2.4.11 version in my project, today I have try to update pod and I get 2.4.16.

In my APP I am using NavigationController. 

After update it start some strange behaviour like when I rotate screen Navigation bar does not resize to screen size and when I am going front and back of app it start some flickering. 

Then I have to undo that update back to 2.4.11.

Is this known issue?

Thanks,
Viral

**Comment by danieldahan** [comment]
Sorry about that. Yes, there was a regression. I am working on it in the following issue: https://github.com/CosmicMind/Material/issues/681, please follow that one.

Thank you for sharing the issue.
