### ISSUE TITLE
PageTabBar tab title color

### ISSUE THREAD

**Issue by Tolriq** [CosmicMind/Material#683]
Hi,

First thanks for this awesome library.
I'm facing a small issue, and I may have completely missed something in the doc but it seems it's not possible to change the text attributes of the selected Tab in a TabBarController.

```swift
        pageTabBarItem.setTitleColor(.black, for: .normal)
        pageTabBarItem.setTitleColor(.white, for: .highlighted)
        pageTabBarItem.setTitleColor(.white, for: .focused)
        pageTabBarItem.setTitleColor(.white, for: .selected)
```

Using above code the tab correctly change color on touch, but does not keep the chosen color for selected state (The active one).

I guess the library does not set the selected status to active tab button, but I think this would be a simple and nice way to handle that.

If I miss something and there's another documented way, then sorry for the noise and I'd appreciate an hint.

**Comment by danieldahan** [comment]
This is a good suggestion. Let me double check and if this is not a feature, it should be. Thank you :)

**Comment by Tolriq** [comment]
@danieldahan any other way to achieve active tab text color change before you add support for the selectors?

**Comment by danieldahan** [comment]
@Tolriq If you keep a state variable for the active button/tab, you could ensure it is always highlighted. That would be basically what I would do internally. You can do this by subclassing the `TabBar` or `PageTabBar` and adding the property, and then listen in on selection changes by subclassing the `select` method. I would go about it that way as an initial idea.

**Comment by danieldahan** [comment]
Let's follow this issue now for the feature request https://github.com/CosmicMind/Material/issues/823, thank you!
