### ISSUE TITLE
NavigationBar colour critical change - unable to set navigation bar

### ISSUE THREAD

**Issue by bilsou** [CosmicMind/Material#684]
Same as the previous users who noticed it, after an update to latest version, setting up navigation bar parameters (typically translucency) doesn't work anymore and end up with a black bar.
It would be great to know when it could be fixed, thanks

**Comment by danieldahan** [comment]
Sorry about that. Yes, there was a regression. I am working on it in the following issue: https://github.com/CosmicMind/Material/issues/681, please follow that one.

Thank you for sharing the issue.
