### ISSUE TITLE
Leftview of Textfield

### ISSUE THREAD

**Issue by nguyentrai2011** [CosmicMind/Material#687]
Hi,
I would like to create textfield with padding left, I created leftview for textfield but expect size not correct, padding left always = 16+ textfield height, and I see in source code have this method

```
open var leftViewWidth: CGFloat {
        guard nil != leftView else {
            return 0
        }
        return leftViewOffset + height
}
```

Why we have this code? and how can I have padding left with specify width? 

**Update**
I had created new class inherit from **TextField** and override __leftViewWidth__

```
override var leftViewWidth: CGFloat {
        guard nil != leftView else {
            return 0
        }
        return (leftView?.frame.size.width)!
}

```
Waiting for your team fix/update func with leftview
Thanks,

**Comment by danieldahan** [comment]
You could specify the `leftViewOffset` value to any size that you want. So it is at least the height of the textField + an offset of 16, which sets the image nicely and then gives space between the text. You could change the `leftViewOffset` value to whatever you like, +/-. If you want to override the leftViewWidth property, it is `open` for that reason. I will play with ideas on making this easier, but I don't see a clear issue here. Feel free to reopen this issue if you need more help :), and if possible, I will make an update that makes this easier to work with.

**Comment by nguyentrai2011** [comment]
@danieldahan 
That's my mistake bcz I don't pay attention about `leftViewOffset`
Thanks for your support, now i know using this, if expected padding left 16pt just doing 2 step:

1. Create left view
2. `self.txtTest.leftViewOffset = -(self.txtTest.frame.size.height - 16);`
