### ISSUE TITLE
NSCalendarsUsageDescription now required

### ISSUE THREAD

**Issue by garie** [CosmicMind/Material#688]
I recently updated to Material 2.4.16 (previously 2.2.4). Now when I attempt to submit my app to TestFlight, it fails with the message "Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data."

We are not using the calendar in any way. I ran the command `find Carthage ! -name '*CodeResources*' -type f ! -name "*.*" -exec nm -o -- {} + | grep EK` and the Material library is the only one using `EKEventStore`, and that was functionality was added recently, in December, for #630.

I realize that the workaround is to add the key with some message, but I would really prefer not to since there's no message I can write that's true besides "You should not be seeing this ask for permission, please say no if you are asked for calendar access.", which is unprofessional and probably won't pass code review! I don't want to put in some other message in case it does appear somewhere and our users don't understand why some piece of functionality isn't there when the message says it should be.

**Comment by danieldahan** [comment]
Hey, yes, in CocoaPods it is an optional addition. The easiest way to remove the issue is to delete the `Reminders` and `RemindersController` files. There is an issue to investigate using Carthage with optional file additions. I hope that helps for now and all the best. I will be looking into the optional file additions within the next few days before I release the next major update.

**Comment by timoman** [comment]
Sorry to dig up an old issue, but are there any updates on this?

I'm currently manually removing `Reminders` and `RemindersController` after building with Carthage. However, I'd like to move to Cocoapods, and it'd be really nice to not have to remember to do this every time this `Material` pod updates.

**Comment by danieldahan** [comment]
I removed Reminders from the latest Material, as they will be separate additions going forward. @timoman

**Comment by timoman** [comment]
Perfect, thanks!
