### ISSUE TITLE
Can this library actually support macOS?

### ISSUE THREAD

**Issue by KingBright** [CosmicMind/Material#690]
I can see the 'macos'  tag below the project description and also can find the macOS [support declaration](https://github.com/CosmicMind/Material#requirements) in requirements section in README. But when I use cocoapods to install it in a macOS project, it will tell me 

> *** not compatible with `Material (2.4.16)`, which does not support `osx`.

**Comment by danieldahan** [comment]
There was an issue with the podspec and only colors were supported. I am removed macOS support completely as of now. Thank you and all the best!
