### ISSUE TITLE
Build error Carthage

### ISSUE THREAD

**Issue by ntus1017** [CosmicMind/Material#692]
Version: 2.4.18
Command:

> carthage update Material --platform iOS

Output:

> *** Checking out Material at "2.4.18"
> *** xcodebuild output can be found in /var/folders/v4/8rfbk1c17qn30plppklmcr0w0000gn/T/carthage-xcodebuild.NuLrr3.log
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/gvz/repos/gakey/Carthage/Checkouts/Material/Material.xcodeproj -scheme "Material macOS" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
> xcodebuild: error: Scheme Material macOS is not currently configured for the clean action.

**Comment by SirComet** [comment]
same issue here...

**Comment by danieldahan** [comment]
I believe it is because I left a schema in the project. I am fixing it now.

**Comment by danieldahan** [comment]
Hey, sorry about this. The fix should be in [Material 2.4.19](https://github.com/CosmicMind/Material/releases/tag/2.4.19). Thank you!
