### ISSUE TITLE
FabMenu with the direction

### ISSUE THREAD

**Issue by lazarte** [CosmicMind/Material#695]
FabMenuItems messed up for the directions except up.

**First Tap**
![up_direction_1](https://cloud.githubusercontent.com/assets/248630/23490404/717a0eea-ff33-11e6-9db0-efa3c24ad5a9.png)

**Third Tap**
![up_direction_2](https://cloud.githubusercontent.com/assets/248630/23490412/780615d8-ff33-11e6-8440-b9ac1b71eb27.png)

**Comment by lazarte** [comment]
Did a pull request please check [SpringAnimation Pull Request](https://github.com/CosmicMind/Material/pull/696)

**Comment by danieldahan** [comment]
Yes, I took a look and looks good. I will test and review tomorrow :) Thank you!

**Comment by danieldahan** [comment]
Thank you for the PR, it worked out well. You should be able to find your fix in [Material 2.5.2.](https://github.com/CosmicMind/Material/releases/tag/2.5.2). All the best!
