### ISSUE TITLE
Layout Issue with UITableViewController + SearchBarController + BottomNavigationController

### ISSUE THREAD

**Issue by kudosQUJO** [CosmicMind/Material#698]
Hello,

First of all I LOVE this library so keep up the great work! Now onto my issue. I have a simple UITableViewController rooted in both a SearchBarController and a BottomNavigationController. I am running into an issue where the last couple cells are covered up behind the tabBar on the bottom after scrolling to the bottom of the tableView. It appears that the tableView layout ignores the tabBar.

If I miss something and there's another documented way, then sorry for the noise and I'd appreciate a hint.

**Comment by danieldahan** [comment]
Thank you :) 

Can you share your setup code?

**Comment by theolof** [comment]
I had this issue, but I changed the controller to a `UIViewController` with an embedded `UITableViewController` instead.

I also made sure the `UITableViewController` was aligned to the bottom layout guide, instead of `self.view`:

```
view.addSubview(tableView)
view.addConstraint(NSLayoutConstraint(item: tableView, attribute: .top, relatedBy: .equal, toItem: view, attribute: .top, multiplier: 1.0, constant: 0))
view.addConstraint(NSLayoutConstraint(item: tableView, attribute: .bottom, relatedBy: .equal, toItem: bottomLayoutGuide, attribute: .top, multiplier: 1.0, constant: 0))
```
It also works for me with this:
```
view.layout(tableView).edges()
```

Maybe any of that that helps.

**Comment by kudosQUJO** [comment]
@theolof Thanks for the advice! That worked!

**Comment by danieldahan** [comment]
@theolof thank you for your help on this one :)
