### ISSUE TITLE
TextField's rightView/leftView doesn't switch places in hebrew/arabic system language

### ISSUE THREAD

**Issue by mrfonda** [CosmicMind/Material#699]
<img width="320" alt="screen shot 2017-03-04 at 13 44 00" src="https://cloud.githubusercontent.com/assets/18546910/23578482/aa1e0cc0-00e0-11e7-93db-512f84b9d658.png">

**Comment by lrn2fly** [comment]
nice

**Comment by danieldahan** [comment]
There is a feature request that is along the lines of this. I will link it here: https://github.com/CosmicMind/Material/issues/575, I will push this up the priority chain, as I could imagine it is needed by many people. Thank you!

**Comment by danieldahan** [comment]
Please follow https://github.com/CosmicMind/Material/issues/575 for updates to this. Thank you!
