### ISSUE TITLE
Adding NavigationBar to existing ViewController

### ISSUE THREAD

**Issue by Yaldo425** [CosmicMind/Material#700]
Specifically in the NavigationController.xcodeproj sample, a ViewController with the navigation and everything is created all through code, but I would like to implement it to a storyboard viewcontroller that I already have, how would I do that?

This is what I've tried and it does not work:

 ```
open override func viewDidLoad() {
        super.viewDidLoad()
  var menuButton: IconButton!
  var starButton: IconButton!
   var searchButton: IconButton!

 starButton = IconButton(image: Icon.cm.star)
        searchButton = IconButton(image: Icon.cm.search)
         menuButton = IconButton(image: Icon.cm.menu)
        view.backgroundColor = Color.grey.lighten5
        
     navigationItem.title = "Material"
        navigationItem.detail = "Build Beautiful Software"
        
        navigationItem.leftViews = [menuButton]
        navigationItem.rightViews = [starButton, searchButton]



    }

```

**Comment by danieldahan** [comment]
@Yaldo425 Take a look at the [NavigationController storyboard example](https://github.com/CosmicMind/Samples/tree/d34507fc173428d36c94f43e22148929e8ca15dc/Material/Storyboards/NavigationController). If you need, reopen the issue. All the best :)

**Comment by Recouse** [comment]
I'm doing it as in the example. But naigationbar not work.

**Comment by danieldahan** [comment]
@Recouse What do you mean by it doesn't work?
