### ISSUE TITLE
Need a feature to support multiline for ErrorTextField.

### ISSUE THREAD

**Issue by SanRam** [CosmicMind/Material#701]
Use UITextView instead of UITextField.

**Comment by danieldahan** [comment]
Take a look at this `http://stackoverflow.com/questions/1345561/how-to-create-a-multiline-uitextfield`. Yes, the correct solution is to use a `UITextView` over a `UITextField`.

**Comment by SanRam** [comment]
I do know you have TextView in the library which extends UITextView.
But the problem it's not working straight out of the box. The Class TextView needs more work on it to bring Bottom line and label color changes based on text edit.

**Comment by danieldahan** [comment]
@SanRam yup, I am working on that for the next release.

**Comment by cody1024d** [comment]
Any progress on this?  I'd be willing to help chip in if it's needed; as I need this capability for my day job.  I'll write it myself if I have to, but would rather contribute if I can

**Comment by danieldahan** [comment]
@cody1024d I don't see this being a priority for a while. Contributions are always more appreciated than asking for work to be done ;) all the best!

**Comment by cody1024d** [comment]
@danieldahan Totally man.  I'll have something working by EoD I think.  It will probably be fairly rough, as I'm hacking it together in a local project (by copying the TextView source), and then tacking on the features I need by looking at the TextField implementation for it.  It'll be a start, atleast, though.  What I'll do, after I get it working locally, is fork this project, and make the changes directly into the TextView class, and then make a PR for it.  And we can discuss any cleaning-up there, Sound good?

**Comment by danieldahan** [comment]
@cody1024d Sounds great :) But let's do one better. Join [Material Gitter](https://gitter.im/CosmicMind/Material) and we can hash it out together as you go. I want to make updates to the `TextView` in general, so maybe this is the right time. Also, we can chat freely on there and more may join the conversation. I appreciate your help :)
