### ISSUE TITLE
Modify the title with self.navigationItem.title doesn't work

### ISSUE THREAD

**Issue by DamienLevel** [CosmicMind/Material#702]
Hi everyone,

Thank you for your awesome lib !

I just want to use the ErrorTextField component in my app but since I've imported Material in my project, I can't change programmatically the title of my ViewController with `self.navigationItem.title` because your Extension override the variable `title`.

    /// Title text.
	@nonobjc
	public var title: String? {
		get {
			return titleLabel.text
		}
		set(value) {
			titleLabel.text = value
            navigationItem.reload()
		}
	}

I don't want to use `self.title` to modify the title of my UINavigationBar because I have also a tabBar and `self.title` modify the title of the tabBarItem.

What can I do ?

Thanks.

**Comment by danieldahan** [comment]
On the next release, I will have an update for this. This conflict shouldn't exist. Thank you!

**Comment by DamienLevel** [comment]
Great, thank you @danieldahan !
I'll check that when the update will be released.

**Comment by danieldahan** [comment]
I tried your sample :) You only need to set the class type for the `UINavigationBar` to `NavigationBar`. That's it :) Best of luck and reach out whenever you need. Thank you!

**Comment by danieldahan** [comment]
Sorry, closed the wrong issue. This has been reopened.

**Comment by danieldahan** [comment]
To avoid conflicts, the `navigationItem.title` and `navigationItem.detail` have been moved to `navigationItem.titleLabel.text` and `navigationItem.detailLabel.text`, respectively.
