### ISSUE TITLE
TextView isn't scrolling with placeholder

### ISSUE THREAD

**Issue by cecilcosta** [CosmicMind/Material#703]
I'm struggling with the following issue: Create a scene with just a text view and its constraints (leading, trailing, top and bottom). Set its text to be greater than the current text view area. Run the app and you will see that you are able to scroll perfectly.
Now on the `viewDidLoad`, just add `self.textView.placeholderLabel = UILabel()`, and no more. Run the app and check that you are not able to scroll.
If you rotate the device the scroll returns enabled.
I tested that on Xcode 8.2, iOS 10.2

**Comment by danieldahan** [comment]
Please follow https://github.com/CosmicMind/Material/issues/704, which is similar to this, and will be solved with the latest update to TextView. Thank you!
