### ISSUE TITLE
Clips to bounds is removed on Text View

### ISSUE THREAD

**Issue by cecilcosta** [CosmicMind/Material#704]
add a text view and set its text to something that overflow its size. On the Interface Builder ensure that it is marked `clipsToBounds` and have a look that its preview works fine (clipping it). Run the app and check that the text field shows the overflowed area. Solution? Manually add `self.textView.clipsToBounds = true` on `viewDidLoad`, but it shouldn't be necessary.

**Comment by danieldahan** [comment]
I am almost done a rework on the TextView, called Editor. I will double check this is correctly setup before I ship it. Thank you!

**Comment by danieldahan** [comment]
I believe these two are connected, https://github.com/CosmicMind/Material/issues/703.

**Comment by danieldahan** [comment]
This is now fixed and will be released tomorrow. Thank you!

**Comment by danieldahan** [comment]
Sorry, I didn't get a chance to release the `TextView` when I had hoped. There is a version of it in `development` that works if you would like to try. Here is a [TextView Sample](https://github.com/CosmicMind/Samples/tree/development/Projects/Programmatic/TextView) project. 

The version in `development` is pretty stable, I haven't seen any errors, but I am not done the default configurations, so I have not released it yet. 

I'll close this issue when I make the release :) All the best!

**Comment by danieldahan** [comment]
Hey, please find your feature request in [Material 2.6.0](https://github.com/CosmicMind/Material/releases/tag/2.6.0) and a sample [TextView](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TextView) project. Thank you and all the best!
