### ISSUE TITLE
snackbar not working, even after copying everything

### ISSUE THREAD

**Issue by Yaldo425** [CosmicMind/Material#705]
I am trying to get a snackbar to work on my xcode project with no success. the snackbarcontroll project in the samples folder is working, so I even tried copying all swift files and the viewcontroller to my own xcode project to test and it still doesn't work. I get an empty viewcontroller without a snackbar showing up. What's the problem?

**Comment by Yaldo425** [comment]
Now I am pretty sure that the problem is with this:

```
  window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = AppSnackbarController(rootViewController: UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RootViewController"))
        window!.makeKeyAndVisible()
```

I cannot have that in my applicationDidFinishLaunching(). Why is this code there rather having it load by itself by setting an initial view controller?

**Comment by danieldahan** [comment]
Can you share your project with support@cosmicmind.com?

**Comment by Yaldo425** [comment]
As of yesterday I sent you guys the xcode project! Thanks in advance!

**Comment by Yaldo425** [comment]
Was just wondering if a solution was found for this? I've spent two hours messing with the code and storyboard but I just cannot get it to work without adding that code I posted at the top to my applicationDidFinishLaunching() which also overrides my whole storyboard configuration

**Comment by danieldahan** [comment]
Hey, sorry for any delay. Tomorrow I will tackle your issue :) 

This weekend has been busy with some other work. 

All the best!

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
Hey, taking a look now at your project... Sorry for any delays, I had looked earlier, but did not find anything. Thanks :)

**Comment by danieldahan** [comment]
So nowhere in your code did you actually add the `SnackbarController`. This is one option of how to do it and is in the [Snackbar sample](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/SnackbarController). Take a look at the [AppDelegate](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/SnackbarController/SnackbarController/AppDelegate.swift). 

If you need, please reopen the issue :) All the best!

**Comment by Yaldo425** [comment]
What are the other options for doing it? I mentioned that I cannot use that AppDelegate code because it overrides my storyboard configuration. Adding in that code in the AppDelegate would just  make the app take you to the snakbar viewcontroller but without any way for me to access any of my other viewcontrollers.

**Comment by danieldahan** [comment]
@Yaldo425 This is not entirely correct. If you set the `SnackbarController` as the root, it itself has a root, and that is where you will set your Storyboard. You can see that in this [AppDelegate](https://github.com/CosmicMind/Samples/blob/master/Projects/Storyboards/SnackbarController/SnackbarController/AppDelegate.swift) file, and in this [SnackbarController](https://github.com/CosmicMind/Samples/tree/master/Projects/Storyboards/SnackbarController) sample project using Storyboards. If this is not ideal for you, the last option is to add a `Snackbar` to your view controller and copy the animation logic in the `SnackbarController`.  Let me know :) All the best!
