### ISSUE TITLE
View controller-based status bar appearance not optional

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#706]
I know there are a bunch of issues reported with regards to status bar appearance not updating correctly & each of the resolutions are to disable view controller based status bar appearance.

However I'd like to use view controller based status bar appearance & I had a working solution on my app. After installing `Material` my project would no longer compile due to there being an extension on `UINavigationController` which implements `statusBarStyle`. Since this references `Application.statusBarStyle` my implementation no longer works.

Is there any way Materials status bar appearance handling can be optional?

**Comment by markst** [comment]
I think the issue is due to there being an extension on `UINavigationController` which implements the property `statusBarStyle`. When in actual fact it should be an extension on the `NavigationController` class...

**Comment by danieldahan** [comment]
Sounds correct, I will add your PR fix to the next release :) Thank you!
