### ISSUE TITLE
Unable to manually set PresenterCard height

### ISSUE THREAD

**Issue by tomdaniel0x01** [CosmicMind/Material#708]
I am trying to have a PresenterCard stretch from the top to the bottom of the screen no matter the height of its content. I cannot find any way to give a PresenterCard a manual height or obtain its height through constraints.

**Comment by tomdaniel0x01** [comment]
Sorry, I didn't realize these features were created by a Layout module. Everything is now working as expected.

Main functionality tutorials are hard to find on the website because they are mixed with all features. An easy fix would be to section out the primary tutorials all at the top of the Material page on the website.

**Comment by danieldahan** [comment]
@tomdaniel0x01

100%, I plan to reorganize the site to help. As well, I am not even teaching all that these frameworks can do. So that should improve as well. I hope you are enjoying the frameworks so far. All the best :)

**Comment by tomdaniel0x01** [comment]
I am sure you have plenty to keep you busy. Thanks for creating such a great UI framework! It's been a pleasure to work with once I figured it out.
