### ISSUE TITLE
BackButton appears while animating NavigationItem

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#709]
Could you explain why are you doing `item.hidesBackButton = false` in the [`UINavigationItem.prepareItem(_:)`](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationBar.swift#L309).
Deleting that line caused mysterious  three dots to appear when a viewController is pushed to the navigationController.

I have to somehow eliminate that line since it causes `backButton` to appear and disappear when I animate the `NavigationItem`.

**Comment by OrkhanAlikhanov** [comment]
I fixed my issue by adding boolean `shouldPrepareItem` and setting it to false when I don't need it. But I still want to know the wisdom behind the `prepareItem` :)

``` swift
internal func layoutNavigationItem(item: UINavigationItem) {
    guard willLayout else {
        return
    }
    
    if shouldPrepareItem {
        prepareItem(item: item)
    }

   ...
}
```

**Comment by danieldahan** [comment]
Hey, really sorry I didn't get to this earlier. The issue is a minor bug with hiding the `back button` using multiple methods at the same time. So `hidesBackButton` needed to be set to `false` to avoid the `...` that appeared. All the best and hope you are having fun with Material :)

**Comment by OrkhanAlikhanov** [comment]
What is actually the three dots (`...`) appearing? Just curious :)

**Comment by danieldahan** [comment]
It's Apple's way of saying there is a title value that is not fully being shown. It is like `Mate...`, but in this case it is only the `...`. This is the behaviour of Strings that are too long in some cases when coding with iOS :)
