### ISSUE TITLE
TableViewCell incorrect behavior

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/Material#712]
Hello Daniel,
it's been a long time 😄., I'm glad that this project is growing steadily!
There is an issue in `TableViewCell`, even if you set `cell.selectionStyle = .none`, cell can still be selected (I mean the ripple effect is still there). I know this beats the whole point of subclassing `TableViewCell` and not `UITableViewCell` in this case but there are some edge cases when this is still needed.
Thank you.

**Comment by danieldahan** [comment]
Hey :) 

Thank you! I am happy to see you using Material. 

You should set the `pulseAnimation` property to `.none`. 

```swift
(cell as? TableViewCell)?.pulseAnimation = .none
```

You only need to cast if the `cell` is considered the default `UITableVIewCell` or another type.

All the best :)
