### ISSUE TITLE
Unable to transition ToolbarController vc with stacked layout

### ISSUE THREAD

**Issue by tomdaniel0x01** [CosmicMind/Material#713]
I am trying to transition the rootVC of a ToolbarController from a NavigationDrawerController's leftVC.

I am calling ```toolbarController?.transition(to: dashboardViewController)``` from menuViewController.swift but nothing happens. However, I can use this same code within AppDelegate.swift and the transition works. Also, I did add a dashboardViewController variable within menuViewController.

Is this a situation where I can only change the rootVC of the NavigationDrawerController?

Here is the code within AppDelegate.swift
```
lazy var checkoutViewController: CheckoutViewController = {
        return UIStoryboard.viewController("CheckoutViewController") as! CheckoutViewController
    }()
    
    lazy var dashboardViewController: DashboardViewController = {
        return UIStoryboard.viewController("DashboardViewController") as! DashboardViewController
    }()
    
    lazy var menuViewController: MenuViewController = {
        return UIStoryboard.viewController("MenuViewController") as! MenuViewController
    }()
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        let toolbarController = AppToolbarController(rootViewController: checkoutViewController)
        
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = AppNavigationDrawerController(rootViewController: toolbarController,
                                                                   leftViewController: menuViewController)
        window!.makeKeyAndVisible()
    }
```

**Comment by danieldahan** [comment]
Hey, so the issue is that the `menuViewController` has no idea about the `toolbarController`. The relationship between them is the `NavigationDrawerController`. So you need to write this in your `menuViewController`.

```swift 
(navigationDrawerController?.rootViewController as? ToolbarController)?.transition(to: DashboardViewController())
```

You should take a look at the [NavigationDrawerController Sample](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController) project to see how this is done with the same setup. 

That should do it. All the best!

**Comment by tomdaniel0x01** [comment]
Worked like a charm! I thought there was a sample somewhere that had what I needed but I searched and couldn't find it.

Thanks!

**Comment by danieldahan** [comment]
Any time :)
