### ISSUE TITLE
Button - super.init(coder: aDecoder) exception

### ISSUE THREAD

**Issue by Johnny992** [CosmicMind/Material#716]
When i set All Exceptions breakpoint, compiler shows me that is something wrong with super.init method in Button init.

![screen shot 2017-03-15 at 10 57 44 2](https://cloud.githubusercontent.com/assets/3774213/23943094/915741f2-096e-11e7-9b0b-60017a75a367.png)

**Comment by danieldahan** [comment]
I will try this and see, thank you!

**Comment by danieldahan** [comment]
I can't seem to reproduce this. Could you send me a sample project? Also what version of Material are you using?

Please reopen the issue once you have these two items. Thank you :)

**Comment by Johnny992** [comment]
Material', '~> 2.0'

**Comment by danieldahan** [comment]
I tried again to reproduce this, with Material 2.5.2, can't get it to crash. Would you mind sharing a sample project, or trying an updated version? Also, are you using the simulator, or device, and if so, which one? Thank you!
