### ISSUE TITLE
Nothing showing up on presented NavigationBar

### ISSUE THREAD

**Issue by joninsky** [CosmicMind/Material#719]
Just started using this library. It's very nice and has a lot of useful extensions. 

I'm trying to present a NavigationController from the app's root view. I followed the example (storyboard project) to a T and still, no `NavigationBar` items will show! (Including the title) I think this [issue regarding the navigation item title](https://github.com/CosmicMind/Material/issues/702) might be part of my problem.

I am trying to add a button on the left side of the `NavigationBar` that will dismiss the `NavigationController`. However, neither my button or title are showing up! Please help:

- xCode Version 8.2.1
- iOS 10.0

And [here is a repo I set up](https://github.com/joninsky/Material-Navigation-Test.git) that reproduces the issue. just run good old `pod install` after you clone.

Hopefully I am just making a stupid mistake but this is driving me crazy!

Note: Since you can quickly select the `initialViewController` from a `UIStoryboard` file you can see that the issue is still present in this project even when the `UINavigationController` is selected as the `initialViewController`. 

Note 2: Please excuse the horrendous typo in the project name.

**Comment by danieldahan** [comment]
@joninsky No worries, let me take a look at your repo now. Thank you!

**Comment by danieldahan** [comment]
I tried your sample. You only need to set the class type for the `UINavigationBar` to `NavigationBar`. That's it :) Best of luck and reach out whenever you need. Thank you!

**Comment by joninsky** [comment]
Thank you @danieldahan. Small detail I guess I missed in the sample project. Such is the nature of software development 😜

**Comment by danieldahan** [comment]
No worries :)
