### ISSUE TITLE
Navigation title breaks if setting title on `navigationItem`

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#722]
`NavigationItem` is not optional & there is a an extension on `UINavigationItem` which overrides the `title` setter. 

This causes me trouble if setting the title either way:
```swift
self.navigationItem.title = "sites"
tabBarController.navigationItem.title = "sites"
```

Example:
![http://d.pr/i/b0WI](http://d.pr/i/b0WI.gif)

It seems that this is due to the fact I'm not using a `NavigationBar` instance; which therefor in turn doesn't call on `prepareTitleView()`.

I'd rather have the option of using `NavigationBar` instead of forced if this library is included in my project. 

Resolution for time being is to set the title on my tab bar controller:
`tabBarController.title = "sites"`
Rather than the navigation item. 

Can provide more details if necessary.

**Comment by danieldahan** [comment]
I'll have a response and fix for this later today. Sorry for any delay. Thank you!
