### ISSUE TITLE
[Enhancement] TextField tint (divider, etc.) should default to View tint

### ISSUE THREAD

**Issue by Deadpikle** [CosmicMind/Material#723]
Hi,

First time user of the library here, so it's possible I'm missing something, but it would be nice IMO if the default divider color and `placeholderActiveColor` (the latter of which appears to determine the overall tint color [e.g. caret, selection color]) for the `TextField` would follow the app's global tint and/or the tint set for the overall `View` in IB (see bottom of screenshot from IB). As it stands, the `TextField` defaults to a blue color with no changes.

<img width="242" alt="screen shot 2017-03-22 at 1 21 05 pm" src="https://cloud.githubusercontent.com/assets/5092399/24211439/6c5cc306-0f02-11e7-820e-9902c7d63f9b.png">

Before setting `placeholderActiveColor` and `dividerActiveColor`:
![screen shot 2017-03-22 at 1 25 45 pm](https://cloud.githubusercontent.com/assets/5092399/24211642/144f2cf2-0f03-11e7-960a-1b7e58e01a31.png)

After:
![screen shot 2017-03-22 at 1 26 48 pm](https://cloud.githubusercontent.com/assets/5092399/24211695/39387780-0f03-11e7-806a-a208b96486b2.png)

Perhaps if this wasn't the default, in order to keep backwards compatibility, we could toggle this option with a boolean? This would help the library be more "plug and play" as it were.

Thanks!

XCode 8.2.1
iOS 10.2

**Comment by danieldahan** [comment]
I believe you are talking about creating themes for Material? We have a [Theme Feature Request](https://github.com/CosmicMind/Material/issues/292#issuecomment-289220858) for this. Please follow that issue, and if I am not correct in my thinking, please reopen this issue and describe further. Thank you!
