### ISSUE TITLE
[TextField] inside a UITableViewCell

### ISSUE THREAD

**Issue by giofid** [CosmicMind/Material#724]
I'm trying to put TextField inside a UITableViewCell in this way:

                let cell = tableView.dequeueReusableCell(withIdentifier: "textfieldCell", for: indexPath)
                // Configure the cell...
                let passwordField = TextField()
                passwordField.placeholder = "Password"
                passwordField.isDividerHidden = true
                passwordField.clearButtonMode = .whileEditing
                passwordField.isVisibilityIconButtonEnabled = true
                cell.layout(passwordField).center().left(20).right(20)
                return cell

![schermata 2017-03-23 alle 16 19 01](https://cloud.githubusercontent.com/assets/13570450/24254961/7f66770c-0fe4-11e7-9629-29977197ecc0.png)

When `passwordField` is not selected it's correctly showed at centre of my table view cell.
Below my problem: 

![schermata 2017-03-23 alle 16 33 25](https://cloud.githubusercontent.com/assets/13570450/24255708/7f6f2094-0fe6-11e7-8b8b-de999db87ee6.png)

When I select it, the placeholder go out from my table view cell.
I would like if `passwordField` could stay vertically centered in table view cell whether it's selected or unselected.

I try to play with the `TextField` properties but without success. 
Is it possible to achieve this?

**Comment by OrkhanAlikhanov** [comment]
This is not a solution but you can play with `placeholderVerticalOffset` property.

**Comment by danieldahan** [comment]
Hey :)

You will need to adjust the height of the `TextField` with a slight top offset, and increate the height of the `UITableViewCell` to accommodate it. At the current moment, the height of the `TextField.placeholderLabel` is not included in the intrinsic height of the `TextField`. If you have any further questions, or need any help, please reopen this issue. Thank you!
