### ISSUE TITLE
Swiping in AppPageTabarController triggers other VC

### ISSUE THREAD

**Issue by volkangurol** [CosmicMind/Material#727]
In appPageTabBarController i have 3 VC, swiping second VC, triggers third VC as well.
This issue not occurs when its rootController. After i transitioned from other VC to appPageTabBarController, if i swipe from first VC to 2nd VC, it triggers 3rd VC.
 
let appPageTabBarController = AppPageTabBarController(viewControllers: [first,second,third])
toolbarController?.transition(to: appPageTabBarController)

Am i calling right ?

**Comment by danieldahan** [comment]
I am not sure what you mean by triggers.

**Comment by volkangurol** [comment]
ok, mouse dragging (swiping) in emulator misleading me, sorry for that. It is accurate in device

**Comment by danieldahan** [comment]
No worries :)
