### ISSUE TITLE
build error with last version on master branch

### ISSUE THREAD

**Issue by kerem1905** [CosmicMind/Material#728]
I am getting build error and logs are as follows,

/Users/jenkinsbuild04/jenkins/workspace/TM_MAD_Swift_iOS/Pods/Material/Sources/iOS/Material+Motion.swift:175:15: error: Objective-C method 'animationControllerForPresented:presenting:source:' provided by method 'animationController(forPresented:presenting:source:)' does not match the requirement's selector ('animationControllerForPresentedController:presentingController:sourceController:')
    open func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
              ^
    @objc(animationControllerForPresentedController:presentingController:sourceController:) 
/Users/jenkinsbuild04/jenkins/workspace/TM_MAD_Swift_iOS/Pods/Material/Sources/iOS/Material+Motion.swift:184:15: error: Objective-C method 'animationControllerForDismissed:' provided by method 'animationController(forDismissed:)' does not match the requirement's selector ('animationControllerForDismissedController:')
    open func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
              ^
    @objc(animationControllerForDismissedController:) 
/Users/jenkinsbuild04/jenkins/workspace/TM_MAD_Swift_iOS/Pods/Material/Sources/iOS/Material+Motion.swift:195:15: error: Objective-C method 'presentationControllerForPresented:presenting:source:' provided by method 'presentationController(forPresented:presenting:source:)' does not match the requirement's selector ('presentationControllerForPresentedViewController:presentingViewController:sourceViewController:')
    open func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
              ^
    @objc(presentationControllerForPresentedViewController:presentingViewController:sourceViewController:)

**Comment by danieldahan** [comment]
What version of Xcode are you using?

**Comment by danieldahan** [comment]
Please find an update for Xcode 8.3 in [Material 2.6.1](https://github.com/CosmicMind/Material/releases/tag/2.6.1). If you need, please reopen this issue. Thank you!
