### ISSUE TITLE
Switch inside cards doesn't work

### ISSUE THREAD

**Issue by AkiraTaki** [CosmicMind/Material#729]
In my app I put a Switch inside a Card, the layout is alright but it doesn't respond to touches (switch not changing its state). I've also tried UISwitch which does not work as well. Is this a bug in cards?

**Comment by AkiraTaki** [comment]
Oh, I've just figured it out. It turns out that I put a card inside a custom UITableViewCell. That causes the problem.

**Comment by danieldahan** [comment]
Great :) Happy all has worked out. Thank you!
