### ISSUE TITLE
PulseView with depth

### ISSUE THREAD

**Issue by AkiraTaki** [CosmicMind/Material#730]
When I programmatically called pulse() on a card with depth (the shadow), the pulse appears in the back of the card  (where the shadow is) rather than pulsing on the card itself. Is this normal? or am I doing something wrong?

**Comment by danieldahan** [comment]
Hmm... Can you show me a visual of this?

**Comment by danieldahan** [comment]
Hey, I haven't heard from you, when you get a chance, please provide a visual of the issue and the version of Material that you are using, and reopen the issue then :) Thank you!
