### ISSUE TITLE
TextView placeholder

### ISSUE THREAD

**Issue by reloni** [CosmicMind/Material#732]
Hello.
Previously TextView's placeholder worked similarly as placeholder in TextField (when you start input text placeholder moved up). Now placeholder in TextField simply disappears when control has text. Is it a bug or this functionality was removed?

**Comment by danieldahan** [comment]
Great question, the functionality was removed to simplify the TextView as it was causing issues with scrollable text. TextView has multi line support, using clipsToBounds = false, bugs out. If you have any suggestions, I'd be happy to discuss them. Please reopen the issue if needed.
