### ISSUE TITLE
How to call pushViewController in NavigationDrawerController ?

### ISSUE THREAD

**Issue by tariq235** [CosmicMind/Material#733]
I want to do pushViewController on rootViewController in current sample of `NavigationDrawerController` https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationDrawerController/NavigationDrawerController/RootViewController.swift

and as well as in ```TransitionedViewController``` https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationDrawerController/NavigationDrawerController/TransitionedViewController.swift

Nothing is happening if I call ```navigationController?.pushViewController(MyController(), animated: true)```

If attach NavigationController to rootViewController then center rootViewController will not change on tap of leftViewController
```(navigationDrawerController?.rootViewController as? ToolbarController)?.transition(to: TransitionedViewController(), completion: closeNavigationDrawer)```

This is because rootViewController doesn't have NavigationController. If I attach AppToolbarController to rootView then navigation will not work and if I attach AppToolbarController to rootViewController then navigationDrawer transition will not work.

Please help!

**Comment by danieldahan** [comment]
I am away until this evening, I can help you then :)

**Comment by danieldahan** [comment]
Your setup sounds like it is trying to combine more than one idea. So I am slightly confused, but from your issue question - the code to call `pushViewController` from the `NavigationDrawerController` where the `NavigationDrawerController.rootViewController` is a `NavigationController` do this:

```swift
(navigationDrawerController?.rootViewController as? NavigationController)?.pushViewController(MyViewController(), animated: true)
```

If you have any further issues or questions, please reopen or create a new issue. Thank you :)
