### ISSUE TITLE
Is there any way to use features like Fab button, snackbar in one view controller?

### ISSUE THREAD

**Issue by sdondon** [CosmicMind/Material#734]
Hello :)

I'm trying to implement fab button, snack bar and some other features that Material framework have in one viewcontroller.

but it seems like there is no way to use them in one VC other then nesting all different VCs like this :  
```

        // Set Drawer Views.
        let appNavigationController = AppNavigationController(rootViewController: mainViewController)
        
        let appFABMenuController = AppFABMenuController(rootViewController: appNavigationController)
        
        window = UIWindow(frame: UIScreen.main.bounds)
        
        // wrap rootViewController, leftViewController(Drawer), rightViewController(Dummy) in NavigationDrawerController.
        window!.rootViewController = AppSnackbarController(rootViewController : NavigationDrawerController(rootViewController: appFABMenuController,
                                                                                                           leftViewController: leftViewController,
                                                                                                           rightViewController: rightViewController))
        window!.makeKeyAndVisible()
```

It works fine when tested, but I just want to know if I'm doing right. Will there be any performance issues? sometimes the screen gets really odd when transition happen

**Comment by danieldahan** [comment]
Hey! You are doing it the correct way. If you would like them all to be in one view controller, you can take the components from the controllers and put them together yourself within a single view controller. For example `SnackbarController`, you could use the `Snackbar` and construct some of its features yourself that only the controller offers This is beneficial when you have certain reworks to animations, or other customized parts that you would like to do and not alter Material itself. A good way to organize your code, would be to subclass the controllers and put the relevant code setup within them for each component. 

If you need, please reopen or create a new issue :) All the best!

**Comment by litunny** [comment]
Hello there, @danieldahan , really impress with alot of work that you've put in place making this framework, thanks to you.

I wanna ask this, if per-adventure, I wanna make use of another controller, how do I inject, may be from the above sample code provided by @sdondon, how do we inject another controller when we cannot as well call them directly, I wouldn't mind if you can help with a sample code.

Waiting patiently to hearing from you.

Thanks.

**Comment by danieldahan** [comment]
@litunny Happy to help :) 

I am not sure I fully understand what you are asking. Are you asking how to reuse the code? How to add more controllers to the code above?

**Comment by litunny** [comment]
Thank you for your response. I'm looking at the possibility of adding more controllers at any point in time.
