### ISSUE TITLE
clarification - switch properties

### ISSUE THREAD

**Issue by johndpope** [CosmicMind/Material#735]
it wasn't clear to me how to achieve this stretched look from looking through switch class.

<img width="178" alt="screen shot 2017-04-11 at 12 34 28 pm" src="https://cloud.githubusercontent.com/assets/289994/24919934/4f99e22e-1eb3-11e7-9f02-7050fdc1e948.png">

thus far
<img width="147" alt="screen shot 2017-04-11 at 12 35 48 pm" src="https://cloud.githubusercontent.com/assets/289994/24919955/6a1f636c-1eb3-11e7-9f05-a40099c00233.png">

**Comment by johndpope** [comment]
<img width="1037" alt="screen shot 2017-04-12 at 9 36 44 am" src="https://cloud.githubusercontent.com/assets/289994/24960360/93767a24-1f63-11e7-9657-7dfb0629437f.png">

I can achieve making switch longer by changing these internal variable values.
<img width="669" alt="screen shot 2017-04-12 at 9 37 14 am" src="https://cloud.githubusercontent.com/assets/289994/24960378/a0ea7da4-1f63-11e7-982e-62e82d93e121.png">

**Comment by johndpope** [comment]
this seems to get the job done. 
```

import Foundation
import Material

class MySwitch:Switch{
    open override var intrinsicContentSize: CGSize {
        switch switchSize {
        case .small:
            return CGSize(width: 44, height: 44)
        case .medium:
            return CGSize(width: 30, height: 30)
        case .large:
            return CGSize(width: 36, height: 36)
        }
    }
}
```

**Comment by danieldahan** [comment]
Another way you could do this is by using a `Bar` and setting the views to the `rightViews`, or really any side and then placing the `Bar` in the position you would like.

**Comment by johndpope** [comment]
Hi Daniel, thanks for your hard work. Can I ask - did you ever attempt to do an expand menu from the kebab / overflow / more icon on timeline?

**Comment by johndpope** [comment]
perhaps - maybe not production worthy - but just a crude gist you could share?

**Comment by danieldahan** [comment]
@johndpope You mean [Expansion Panels](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage) ? If so, this is good, I will probably want to add these soon, they are quite useful. Thanks! 

There are a bunch of new features coming. I am working on a way to help make the process of creating new components much easier and faster. Thank you for your support!

**Comment by johndpope** [comment]
like a popup menu
<img width="194" alt="screen shot 2017-04-12 at 1 29 30 pm" src="https://cloud.githubusercontent.com/assets/289994/24970940/19d2517c-1f84-11e7-9655-4d7322e0d174.png">

**Comment by danieldahan** [comment]
Yes, I have a prototype for a `popmenu`. I am almost done the latest rebuild of the `PageTabBarController`, now being called `TabMenuController`. Once that is done, the `PopMenu` will probably one of the next on the list to complete, alongside the `BottomSheetController` :)
