### ISSUE TITLE
RaisedButton. Show full animation before action

### ISSUE THREAD

**Issue by mrengine** [CosmicMind/Material#736]
Hi, 

I have RaisedButton and action (tapping on this button) which is moving me to another viewcontroller.
The action is running so fast and I do not have time to notice button's animation. Is it possible to handle delay before action in order to show full animation to user? 

p.s. sure i can add delay (runAfter or Timer) inside my action method, but it's not good solution. maybe there is better solution. Thanks.

**Comment by danieldahan** [comment]
Hey :)

Have you thought of running the `action` as an `async` call on the main thread? That might be helpful. Other than that, a delay seems like a reasonable approach based on what you are describing. If you would like, please reopen or create a new issue. I think a better place to have this discussion is on [Material Gitter](https://gitter.im/CosmicMind/Material). There we can chat about different approaches to these types of issues :)
