### ISSUE TITLE
Material 2.6.2 has Menu library removed in it.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CosmicMind/Material#737]
I was using _**Menu**_ library in **Material 2.4.13** for my project. I updated the pod to version 2.6.2 to avail the functionality mentioned in `https://github.com/CosmicMind/Material/issues/608` .

But now, I can't find the **Menu** library anymore. Has this library been removed or altered?

**Comment by danieldahan** [comment]
Hey, checkout the [FABMenu Sample Project](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/FABMenuController). The `Menu` is now called the `FABMenu` and has some upgraded features. All the best!
