### ISSUE TITLE
Do NavigationDrawer and PageTabBar Support?

### ISSUE THREAD

**Issue by tharhtet** [CosmicMind/Material#738]
![image](https://cloud.githubusercontent.com/assets/7901572/25060978/038d6bfa-21d1-11e7-8ab0-ab5894d1f5fb.png) figure 1

I would like to show only 2 tabs such as red and Green.

![image](https://cloud.githubusercontent.com/assets/7901572/25060989/51124954-21d1-11e7-9291-ee0ac607a674.png) figure 2

I would like to add this navigation drawer. If I will add this 2 function, does it work or is any problem? if you already had sample, please let me know. Thank a lot.

**Comment by danieldahan** [comment]
I am not sure what you are asking? Are you asking if you can combine them? If so, the answer is yes. Please update your question for more help and feel free to reopen the issue :) Thank you!

**Comment by tharhtet** [comment]
[Testing.zip](https://github.com/CosmicMind/Material/files/924453/Testing.zip)

I mean this one "https://github.com/CosmicMind/Material/issues/605". and when i add only two tabs, it is not smooth well. Thank.

**Comment by danieldahan** [comment]
@tharhtet 

Okay, the `PageTabBarController` is being updated with a new component called `PageMenuController`. Once that is released, you can try it out and it should resolve your issue.
