### ISSUE TITLE
Xamarin bindings

### ISSUE THREAD

**Issue by mLupine** [CosmicMind/Material#739]
I was wondering if you could take the time to create Xamarin.iOS bindings for your fantastic library, so developers of Xamarin apps could make use of it.

**Comment by danieldahan** [comment]
I can take a look and see how much work it would take. I'll post back to this issue in a couple days with my findings.

**Comment by danieldahan** [comment]
Hey! So I wouldn't have the time to manage this on my own. If you or anyone else would want to help, I would consider it more. I will close the issue for now. Thank you for sharing this wonderful idea. All the best!

**Comment by delort** [comment]
I think I can help with this.

**Comment by danieldahan** [comment]
@delort how so?
