### ISSUE TITLE
TabBar button selected state

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#740]
We would like to style our tab bar so that the selected index updates the button title colour:
![image](https://cloud.githubusercontent.com/assets/274318/25115016/5c6d57c2-2446-11e7-90f1-4543910252bd.png)

**Comment by markst** [comment]
Seems it might be possible if it were possible to subclass `TabBar` and perhaps possible to override 
```swift
animate(to button: UIButton, isTriggeredByUserInteraction: Bool, completion: ((UIButton) -> Void)? = nil)
```
https://github.com/CosmicMind/Material/issues/710

**Comment by wwe-johndpope** [comment]
see the tabBar programmatic code samples.  specifically....

       tabBar.buttons = buttons
        tabBar.select(at: 0)

**Comment by johndpope** [comment]
https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabBar

**Comment by danieldahan** [comment]
@markst  You shouldn't need to override the function you are specifying. Also, there are delegation calls you can tap into:

```swift
@objc(TabBarDelegate)
public protocol TabBarDelegate {
    /**
     A delegation method that is executed when the button will trigger the
     animation to the next tab.
     - Parameter tabBar: A TabBar.
     - Parameter button: A UIButton.
     */
    @objc
    optional func tabBar(tabBar: TabBar, willSelect button: UIButton)
    
    /**
     A delegation method that is executed when the button did complete the
     animation to the next tab.
     - Parameter tabBar: A TabBar.
     - Parameter button: A UIButton.
     */
    @objc
    optional func tabBar(tabBar: TabBar, didSelect button: UIButton)
}
```

Give those a try, plus the other recommendations above and if you still have an issue, please reopen or create a new one. Thank you!

**Comment by markst** [comment]
Thanks for input guys. 
@danieldahan I'm aware this is possible - however the delegates only get called if `isTriggeredByUserInteraction` which isn't ideal as I'll have to ensure I set the selected state of my tab bar button whenever I programatically select the tab bar item at an index.

**Comment by danieldahan** [comment]
Your delegate is a function call, you could make a reusable function within there that you can trigger?
