### ISSUE TITLE
PageTabBarViewController does not take the tabBar height into account.

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#741]
Please consider shrinking the `rootViewController.view.height`  by `tabBar.height` in the case when the `PageTabBarViewController` is nested in `TabBarViewContoller`.
[PageTabBarController.swift:189](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/PageTabBarController.swift#L189)
``` swift
rootViewController.view.height = y - (rootViewController.tabBarController?.tabBar.height ?? 0)
```

**Comment by danieldahan** [comment]
Can you share your code setup, there may be an issue with the extended layout value. If I can replicate the issue, it might be a matter of a configuration to help you out.

**Comment by danieldahan** [comment]
I haven't heard from you, so if you need help, please reopen this issue. Thank you :)
