### ISSUE TITLE
TabsController not able to change tab with swipe

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Material#743]
The version of Xcode: 8.2.1
The version of iOS: 9+
Material Version: 2.6.3

Recently I am having issue with PageTabBarController. Clicking on tab I am able to change tab. but I am not able to change tabs on swipe.
![tabchanges](https://cloud.githubusercontent.com/assets/23634389/25176196/ff7a3bea-251a-11e7-990b-87f1b774438a.gif)

**Comment by johndpope** [comment]
hard to say why it's broken without seeing code. you're best off referring to sample code and swapping in your classes.
https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/PageTabBarController

You may also want to checkout XLPagerTabStrip

**Comment by danieldahan** [comment]
Thank you for sharing. It seems that when two view controllers are set, there is a crash, at least in the sample project. In the next release, there is a new controller, `PageMenuController` coming out to replace the `PageTabBarController`. So the fix will be ready then. Shouldn't be much longer, I am working out the final details. I will leave this issue up until the release. Thank you!

**Comment by PetresS** [comment]
At my project i have the same issue after i set following property to false: `pageTabBarController?.isBounceEnabled = false`

if I set it back to true, the swipe works, too.
Hope that this information helps.

**Comment by danieldahan** [comment]
@PetresS Yes, this issue is fixed in development with the latest `TabsController`. Mind you, the component is not complete. It will be done shortly.

**Comment by danieldahan** [comment]
This component has now been updated in [Material 2.8.0](https://github.com/CosmicMind/Material/releases/tag/2.8.0). Features like swiping have not been included in 2.8.0, and will be included in a following release. The overall TabsController adds stability and scrollable Tabs. I am closing this issue and thank you for your patience.

**Comment by PetresS** [comment]
Is the swipe-feature added in Material 2.10.2?

**Comment by danieldahan** [comment]
@PetresS Unfortunately not yet. It is getting there :)

**Comment by AlaeddineOuerteni** [comment]
@danieldahan Is it already not include ? If it's done do you have any commit number ? Thanks

**Comment by danieldahan** [comment]
I am closing this feature request as there is a PR for it now: https://github.com/CosmicMind/Material/pull/1019
