### ISSUE TITLE
TabBar scrolling - enhancement

### ISSUE THREAD

**Issue by johndpope** [CosmicMind/Material#744]
I have this use case where I need the items to layout beyond the controls dimensions. 
Is it possible with this control? 

<img width="407" alt="screen shot 2017-04-20 at 10 36 30 am" src="https://cloud.githubusercontent.com/assets/289994/25236253/67bdc18c-25b5-11e7-9fee-f975cc09e2ea.png">

**Comment by danieldahan** [comment]
Hey! I am almost done the feature you are looking for. Here is the issue https://github.com/CosmicMind/Material/issues/642 that follows its progress. If you look in development, there is a new controller called `PageMenuController`, and it will provide this feature. I am going to close this issue as you can follow the other. Thank you :)
