### ISSUE TITLE
Hide space toolbar in view

### ISSUE THREAD

**Issue by RogerBCA** [CosmicMind/Material#745]
Hello
There is possibility to hide the section indicated in the image because I want to put this screen to fullscreen

![Captura](https://i.imgur.com/BpWnsuL.png)

`guard let tc = toolbarController else {
            return
        }
        tc.toolbar.isHidden = true
`

**Comment by danieldahan** [comment]
Yes, set `toolbarDisplay` to `.full` :) All the best!
