### ISSUE TITLE
White space around navigation in landscape

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Material#746]
Xcode: 8.2.1
Material: 2.6.3

![simulator screen shot 24-apr-2017 3](https://cloud.githubusercontent.com/assets/23634389/25332664/ec1a4426-2904-11e7-9626-0442b0e6e996.png)

Steps to generate:
- View1: With navigation bar: Taping on one item from collection view is taking to View2
- View2: Without navigation bar 
hiding navigation bar using `self.navigationController?.isNavigationBarHidden = true` because I want View2 with fullscreen. Now I am changing to landscape and going back
- View1: On coming back, navigation bar with white space

I had face same issue before that at that time I have to undo Material update. Do I need to go back to "2.4.11" version? Because it is working properly.

Regards

**Comment by danieldahan** [comment]
Thank you for sharing this. Can you send me a sample project. Setting everything up, I may do it differently, which may give different results. Thank you! 

You can email it to support@cosmicmind.com

**Comment by viral-etymon** [comment]
I have created demo for your reference and attached screen recoding how it is generated, it might help you to investigate.

![navdemo](https://cloud.githubusercontent.com/assets/23634389/25370790/b3aaed56-29aa-11e7-9fd5-fe42968ecc2e.gif)


[MaterialNavigationIssue.zip](https://github.com/CosmicMind/Material/files/954022/MaterialNavigationIssue.zip)

Let me know anything else needed from my side.

Thanks

**Comment by danieldahan** [comment]
Thank you! I will take a look.

**Comment by danieldahan** [comment]
I ran your sample on my device and had zero issues. I think you need to update to Xcode 8.3.* as I have updated Material to use that version. Try and let me know. Thank you!

**Comment by danieldahan** [comment]
@viral-etymon great, let me know. If you have any further issues with this, please reopen the issue. Thank you!

**Comment by viral-etymon** [comment]
I have tested it in new version of xcode. Still there is same problem:

**Comment by viral-etymon** [comment]
One thing i have notice to regenerate issue
1) Run app
2) Go to second view
3) Rotate left
4) Go back (sometime issue generate here) if not generate then follow below steps
5) Back to portrait view
6) Repeat 2nd step 
7) Rotate right
8) Go back (here I am always getting issue)

Hope it appears at your side as well.

**Comment by danieldahan** [comment]
@viral-etymon Can you send me a sample app and then I will follow your steps, as well, please update to the latest. Thank you!

**Comment by viral-etymon** [comment]
Material: 2.6.3
Xcode: 8.3.2

You can use above app sample to regenerate issue. Below is the link

[https://github.com/CosmicMind/Material/files/954022/MaterialNavigationIssue.zip](url)

**Comment by danieldahan** [comment]
@viral-etymon I am able to see the issue, I believe I may know what it is, will see if I can spot the issue or make a fix. Thank you!

**Comment by danieldahan** [comment]
@viral-etymon Sorry, my mistake, I mixed up issues. I will verify this. Thank you!

**Comment by danieldahan** [comment]
@viral-etymon The link to your sample does not work.

**Comment by viral-etymon** [comment]
[MaterialNavigationIssue.zip](https://github.com/CosmicMind/Material/files/975712/MaterialNavigationIssue.zip)

**Comment by danieldahan** [comment]
@viral-etymon I am testing the issue on an iPhone 6+ and I am not seeing anything wrong with the NavigationBar.

**Comment by viral-etymon** [comment]
Ohh Its my bad luck. I am testing with simulator iPhone 6s and real device iPhone5 and in both I am getting that white space around navigation bar. Again I am attaching gif of my screen recording hope this time you will get idea. 

![navigationissue](https://cloud.githubusercontent.com/assets/23634389/25734802/37ab93ae-3184-11e7-87cf-289b36148f1e.gif)

You can use above attached sample demo, nothing change in that.

**Comment by danieldahan** [comment]
I still cannot reproduce this issue. Can you try and not use Storyboards as a test?

**Comment by viral-etymon** [comment]
Ohk, I will try but will take some time as I have some  on hand task to deliver. Thanks
