### ISSUE TITLE
`PageTabBarController` tab bar not honouring `layoutEdgeInsets`

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#747]
I'd like to set insets of my `PageTabBarController` tab bar:
```swift
self.pageController.pageTabBar.layoutEdgeInsets.right = -50.0
```

However this does not appear to affect the tab bars button layouts:
![image](https://cloud.githubusercontent.com/assets/274318/25466815/34796224-2b4e-11e7-8c37-9805e7161e96.png)

**Comment by markst** [comment]
oh it seems `contentEdgeInsets` is the correct property to use:
```swift
self.pageController.pageTabBar.contentEdgeInsets.right = 50
```

**Comment by danieldahan** [comment]
@markst yes that is correct, contentEdgeInsets is the general property for all components to adjust the padding. LayoutInsets is to adjust he entire component in its parent view bounds. If you need any further help, please let me know. I am closing this issue for now. Thank you!
