### ISSUE TITLE
Hiding Toolbar/NavigationBar on scroll inside PageTabBar

### ISSUE THREAD

**Issue by robforsythe** [CosmicMind/Material#748]
My app is laid out as follows: A Toolbar is the top-level controller, it contains a PageTabBar, and each Tab contains a ScrollView. I'd like to be able to scroll vertically and have the Toolbar (or NavigationBar) collapse - is there any way to hide the Toolbar/NavigationBar when a ScrollView scrolls inside a PageTabBar? I've looked through the API and tried some solutions, but nothing's worked. Perhaps I'm missing something simple?

Thanks for the awesome library and all your hard work!

**Comment by danieldahan** [comment]
Hey, thank you! There is not a direct way to do this in Material at the moment. That said, give me a couple days and let me see what I can think of. I am in the middle of adding updates to the Motion (animation) portion of Material, so maybe I can do something here with scroll techniques. I know there has been a feature request for it. Check in soon if you don't hear from me by Wednesday of next week. Thank you!

**Comment by robforsythe** [comment]
Thanks for taking the time to respond! Have you had any time to look into this yet?

**Comment by danieldahan** [comment]
@robforsythe Thank you for following up. I am still looking into it. Had a few other items pop up before I could dive fully into this. That said, have you taken a look at this: https://www.natashatherobot.com/navigation-bar-interactions-ios8/ ?

**Comment by danieldahan** [comment]
@robforsythe So at this point, the only options would be to use the native iOS scroll techniques. There is a noted feature request to make this more simple. I am going to close the issue for now, and hopefully you can help provide some insight after you tryout the iOS 8+ updates from Apple. Soon enough I will be working on this myself as well :) Always feel free to create any issue and reach out with more questions and suggestions. All the best!

**Comment by ebinjoy999** [comment]
Any luck on this?

**Comment by danieldahan** [comment]
@ebinjoy999 we haven't had time to work on it. We would be happy to work with someone who wants to lead this effort, but for us, we are focused on some other tasks.
