### ISSUE TITLE
NavigationDrawerController with NavigationController causes NavigationBar to flicker on transition

### ISSUE THREAD

**Issue by chrisdhaan** [CosmicMind/Material#749]
Xcode version: 8.3.2
iOS version: 10.2

I'm currently attempting to make use of a `NavigationDrawerController` that contains both a `rootViewController of type NavigationController` and a `leftViewController of type UIViewController`. I have a UITableViewCell in the `leftViewController` that when clicked should transition the `NavigationDrawerController` to a new `NavigationController` as its root. When this transition occurs the `NavigationBar` flickers during the transition between the two `NavigationControllers`. The end result is the correct `NavigationController` in the `NavigationDrawerController`. I'm hoping to remove the flicker. The code I'm using to complete the transition is below.

```
self.navigationDrawerController?.transition(to: UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "NavigationController"))
```

I attempted to do something like the following, but since NavigationController does not have the `transition(to:)` method so it was not possible.

```
(self.navigationDrawerController.rootViewController as? NavigationController)?.transition(to: UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "NavigationController"))
```

I've been able to figure out how to use all the components in your framework with the samples and documentation except for this case. I've tried long enough that I'm beginning to wonder if this flicker is 1) a bug or 2) not how the `NavigationDrawerController` is supposed to be used. If this is a bug please let me know if I can provide more code or information to assist in the fix. If I am just using the `NavigationDrawerController` incorrectly I apologize and this GitHub Issue can be closed.

**Comment by chrisdhaan** [comment]
Here is a YouTube video displaying the Issue above.

https://youtu.be/c48X4gB-vwA

**Comment by danieldahan** [comment]
@chrisdhaan No worries, I am here to help. The video is unavailable. It might be because of where I am in the world, not sure. As for the flicker, have you set the `UINavigationBar` to `NavigationBar`? As well, if you can share a sample project, I should be able to help you. 

All the best!

**Comment by chrisdhaan** [comment]
@danieldahan here is a link to example Github project `https://github.com/chrisdhaan/material-demo-app`. If you switch between the two `Drawer` options in the menu you will see the flicker. It doesn't occur every time but it does seem to occur 50% of the time.

**Comment by danieldahan** [comment]
@chrisdhaan Thank you! What version of Material are you using and what device / simulator are testing on?

**Comment by chrisdhaan** [comment]
I am using version `2.6.3` of Material and have experienced the flicker on the iPhone 6, iPhone 6s, iPhone 7, iPhone 7 Plus, and iPhone SE.

**Comment by danieldahan** [comment]
@chrisdhaan I am able to see the issue, I believe I may know what it is, will see if I can spot the issue or make a fix. Thank you!

**Comment by danieldahan** [comment]
@chrisdhaan are the devices you are testing on happening only on the simulator? I tried your sample on my iPhone 6s and the issue is not there.

**Comment by chrisdhaan** [comment]
@danieldahan I apologize. I could of sworn I tested it on a device and experienced the same flicker but testing on my iPhone 7 right now I am not seeing the bug. Again I am sorry for any large amount of time looking into this may have caused you.

I wonder if perhaps there's a way to document that it's a known simulator experience in case other users of your framework run into the same experience?

**Comment by danieldahan** [comment]
@chrisdhaan No worries :) I am happy you pointed it out. Currently I am making some really nice updates to Material and when I get to the NavigationController, I will be testing on simulators as well. Generally, I found that the simulators are not reliable at all, especially for animation work. All the best and never hesitate to reach out, I am here to help. All the best!
