### ISSUE TITLE
Disable page tab bar animation.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CosmicMind/Material#751]
Is there a way in which we can disable the animation for changing of view controllers when user selects any tab.

**Comment by danieldahan** [comment]
Can you give more details? Which tab bar style are you using? BottomNavigationController, PageTabBarController, an independent TabBar?

**Comment by GABHISEKBUNTY** [comment]
I am using PageTabBarController and have added viewControllers to it, with tabBar provided by the PageTabBarController. Now the animation is by default set to yes. So, when I switch in between the tabs the view controller changes with animation.

**Comment by danieldahan** [comment]
I can't seem to find one. That said, there is a BottomNavigationController that you may be able to utilize. There is a new component coming out called the TabsController which will allow you to do what you are looking for. The current PageTabBarController is using a UIPageViewController, which is accessible through the `PageTabBarController.pageViewController` property. You may be able to find a setting in there. I looked online and was not able to find anything. If you need any further help, let me know. All the best!
