### ISSUE TITLE
FABMenu delegation not called on fabMenu.close() - Why?

### ISSUE THREAD

**Issue by MatanGold** [CosmicMind/Material#752]
I saw there is a special `if` in FABMenu class for this case, why?
There are general things I would like to do in both cases (`isTriggeredByUserInteraction` true AND false)

**Comment by danieldahan** [comment]
According to Apple, controls should only call their delegation methods when triggered by a user interaction. If you need the delegation call to be called somewhere in your programmatic steps, then place the delegation call in a handler function and call that where and when needed. Hope that helps and please reopen the issue if you need :)
