### ISSUE TITLE
NavigationDrawerController toggle programmatically

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#753]
How I use toggleLeftView func to show/hide notification drawer.

Can be specified a top constraint for notification drawer?

Regards.

**Comment by danieldahan** [comment]
Hey, 

In any view controller once it appears, after `viewDidAppear` is called, you can use the `navigationDrawerController` optional property, so long as the view controller is a child view in the view hierarchy. Once calling it, you can then call the `toggleLeftView` function. For example:

```swift
open override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    navigationDrawerController?.toggleLeftView()
}
```

Take a look at the [NavigationDrawerController Sample Project](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController) to learn more. 

As for the top constraint, what do you mean exactly? You can easily add any constraint you would like to the `left/right view controllers` you add to the NavigationDrawerController. 

If you need any further help, let me know :) All the best!
