### ISSUE TITLE
how to change the tint color of title bar button

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Material#754]
```
import UIKit
import Material

class MyVC: UITableViewController {
    fileprivate var deleteButton: IconButton!

    override func viewDidLoad() {
        super.viewDidLoad()

        prepareDeleteButton()

        navigationItem.rightViews = [deleteButton]
    }
    // other delegates of UITableView
}

extension MyVC {
    fileprivate func prepareDeleteButton() {
        deleteButton = IconButton(image: UIImage(named: "Trash"))
        deleteButton.tintColor = Color.red.base
        deleteButton.addTarget(self, action: #selector(doSomething), for: .touchUpInside)
    }

    @objc
    fileprivate func doSomething() {
        print("delete accessory")
    }
}
```

Note that `MyVC` is pushed from another `ViewController`.

In `MyVC`, I want my trash can icon to be at the upper right corner of the screen, which is `navigationItem.rightViews = [deleteButton]`, and to have red base color `deleteButton.tintColor = Color.red.base`.

But it does not work in the code above, the trash can is still black, which is its default color. How can I change its tint color?

It seems that my trash icon is a little bigger then other Cosmic Mind icons at the same `rightViews` although it has the same size as Cosmic Mind icons (24x24 @1x). Is it true? How to make it a little smaller?

Regards,

**Comment by danieldahan** [comment]
Try using the ```public convenience init(image: UIImage?, tintColor: UIColor = Color.blue.base)``` initializer. For the image, if the image is exactly 24 x 24 than it will appear bigger, because all the icons in Material have space included in their image, based on the Material Design Icons from Google. Let me know how it works out and if you need any further help, reopen the issue. Thank you!

**Comment by quanguyen** [comment]
I just tried to use `Icon.cm.add` instead of `UIImage(named: "Trash")` and it works! i.e. The icon is tinted red as I wish.

So, there must be something wrong with my Trash icon, which I export from Sketch.
I tried to export some other icons (not this Trash icon) but things are still the same: I cannot tint it.

Do you have any advice?

**Comment by quanguyen** [comment]
OK, I filled it with red before exporting in Sketch -> no need for `tintColor = ...`

**Comment by danieldahan** [comment]
Use this :

deleteButton = IconButton(image: UIImage(named: "Trash")!.withRenderingMode(.alwaysOriginal))

:)

**Comment by Recouse** [comment]
Can't change tintColor too. It doesn't work for me:
`saveButton = IconButton(image: UIImage(named: "ic_save")!.withRenderingMode(.alwaysOriginal))`

**Comment by danieldahan** [comment]
Can you shore the code where you are trying to change this? As well, what version of Material and device are you using?

**Comment by Recouse** [comment]
This code from viewcontroller's `viewDidLoad` method:
```swift
let backButton = IconButton(image: Icon.arrowBack)
let saveButton = IconButton(image: UIImage(named: "ic_save")!.withRenderingMode(.alwaysOriginal))
backButton.addTarget(self, action: #selector(cancel), for: .touchUpInside)
saveButton.addTarget(self, action: #selector(save), for: .touchUpInside)
 
navigationItem.leftViews = [backButton]
navigationItem.rightViews = [saveButton]
```
Material 2.6.3, iphone 7, ios 10.3 simulator.

**Comment by danieldahan** [comment]
@Recouse I don't see the tinting code. Can you share that as well?

**Comment by Recouse** [comment]
I want to use tintColor default value. But color of my icons doesn't change.

**Comment by danieldahan** [comment]
@Recouse  It seems like you are facing two issues, this and https://github.com/CosmicMind/Material/issues/775#issuecomment-306963495. May you send a sample with both your issues and I can look into them? Thank you! Send it to support@cosmicmind.com

**Comment by Recouse** [comment]
@danieldahan I sent you an email to support@cosmicmind.com

**Comment by danieldahan** [comment]
@Recouse thank you, I will take a look.

**Comment by danieldahan** [comment]
@Recouse I am not sure I got the email, can you try and send it again? Please and thank you!

**Comment by Recouse** [comment]
@danieldahan Done.
