### ISSUE TITLE
Custom cell outlets are nil in UITableViewcontroller using PageTabBarController

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#757]
Custom cell in UITableViewController is working well in my test1 project (https://drive.google.com/open?id=0B12slIEw9f2Kb2hKdGNwNHhadm8).

I managed to integrate PageTabBarController capability changing AppDelegate : application: didFinishLaunchingWithOptions func.

If I comment marked code (from begin to end) the application is running well as single view:
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
[UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        // begin /*
        var viewControllers = [MyTableViewController]()
        
        viewControllers.append(MyTableViewController(category: "test1"))
        viewControllers.append(MyTableViewController(category: "test2"))
        
        let pageTabBarController = AppPageTabBarController(viewControllers: viewControllers)
        let toolbarController = AppToolbarController(rootViewController: pageTabBarController)
        let menuController = AppFABMenuController(rootViewController: toolbarController)
        
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = menuController
        window!.makeKeyAndVisible()
        // end */
        
        return true
    }

If I want to use PageTabBarController capability from Material framework, I get an exception:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier cell1 - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

I tried to register the identifier if MyTableViewController with 
self.tableView.register func, but outlets from custom cell are always nil (never happen without PageTabBarController).

Regards,
M.N.

**Comment by danieldahan** [comment]
Somewhere in your project you are referencing a cell identifier that is either not set correctly, or not registered in the correct sequence. Please provide a sample project, or some code I can reference. Once you do that, please reopen the issue :) Thank you!

**Comment by melcug** [comment]
In the beginning of first message (on top in current issue) you can see a link to a project where I faced this issue.

**Comment by danieldahan** [comment]
Sorry, I missed that: 

You need to register your identifier when using UITableView cells. 

```swift
tableView.register(MyTableViewCell1.self, forCellReuseIdentifier: "cell1")
```
and in your code here:

```swift
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

        if (indexPath.section == 0) {
            let cell = tableView.dequeueReusableCell(withIdentifier: "cell1", for: indexPath) as! MyTableViewCell1
            
            cell.lblText1?.text = "Item \(indexPath.startIndex)"
            cell.lblText2?.text = "\(indexPath.section)"
            
            return cell
        }
        else
            if (indexPath.section == 1) {
                let cell = tableView.dequeueReusableCell(withIdentifier: "cell2", for: indexPath) as UITableViewCell
                return cell
            }
            else
                if (indexPath.section == 2) {
                    let cell = tableView.dequeueReusableCell(withIdentifier: "cell3", for: indexPath) as UITableViewCell
                    return cell
                }
        
        return UITableViewCell()
    }
```

You are using identifiers "cell1", "cell2", "cell3" when they are not registered. Also, in your storyboard project, you need to set the UITableView to `TableView`. 

Hope that helps :)

**Comment by melcug** [comment]
I used the same register command for cell1, cell2 and cell3 and in tableView func with cellForRowAt i get cell instance using dequeueReusableCell, but lblText1 and lblText2 outlets are nil. All happen when I use your TabViewcontroller. If i use just MyTableViewController as initial view contrller, I don't need to register cell1, cell2 or cell3 because is done in Main storyboard and lblText1 and lblText2 outlets are valid.

**Comment by melcug** [comment]
I don't understand "_in your storyboard project, you need to set the UITableView to TableView_", how to do that.

**Comment by danieldahan** [comment]
Registering your cell classes is where the issue is arising. As for the Storyboard, in your `Main` storyboard, where you set the UITableView, git it a custom class name TableView.

**Comment by melcug** [comment]
I get an error if I comment register command:
![without register](https://cloud.githubusercontent.com/assets/8708178/26237687/e2fae1ba-3c7e-11e7-82f1-05b5da4e4a4f.png)

Register command **overwrites the storyboard and all the outlink associated with it** and in this context I get following error:
![with register](https://cloud.githubusercontent.com/assets/8708178/26237699/ecfca3b0-3c7e-11e7-9952-c11b9d912792.png)

In storyboard I set proper cell identifier:
![cell identifier in storyboard](https://cloud.githubusercontent.com/assets/8708178/26237703/f117f60c-3c7e-11e7-94d3-95a715d2e46f.png)

Bellow you have a link to test2 project:
[test2.tar.gz](https://github.com/CosmicMind/Material/files/1013461/test2.tar.gz)

Note. In my searches I found that tableView.register command is used just when I manage programmatically to create a cell, but in my project I need too use views already created in storyboard.

Regards and thanks for your effort,
Gogu.

**Comment by danieldahan** [comment]
I don't use storyboards at all, so the advice I will give you will surround programmatic solutions. I will take a look at your other same later today.

**Comment by danieldahan** [comment]
Hey, sorry, this slipped my mind and I didn't get a chance to look at it. Are you still facing an issue?

**Comment by melcug** [comment]
I still have this issue. 
In my previous message i posted a link to a sample project (test2), hopefully that you could solve the problem.
The problem only occurs when I use PageTabBarController and this force me to use tableView.register func that probably overwrite storyboard settings.

I am waiting a new version of Material to test again if it's working or not.

**Comment by danieldahan** [comment]
I am reopening this issue for you.

**Comment by danieldahan** [comment]
The `PageTabBarController` has been replaced with the `TabsController`. Please use that new controller and if the issue persists reopen this issue. Thank you :)

**Comment by melcug** [comment]
I succeed to implement UITableViewController views as tabs using TabBarController.
For that I changed views initialization in AppDelegate func application: didFinishLaunchingWithOptions from:
`var viewControllers = [MyTableViewController]()
    
    **viewControllers.append(MyTableViewController(category: "test1"))
    viewControllers.append(MyTableViewController(category: "test2"))**
    
    let pageTabBarController = AppPageTabBarController(viewControllers: viewControllers)
    let toolbarController = AppToolbarController(rootViewController: pageTabBarController)
    let menuController = AppFABMenuController(rootViewController: toolbarController)
    
    window = UIWindow(frame: Screen.bounds)
    window!.rootViewController = menuController
    window!.makeKeyAndVisible()`
to:
`
var table1ViewController: MyTableViewController = {
        return UIStoryboard.viewController(identifier: "Table1ViewController") as! MyTableViewController
    }()
var table2ViewController: MyTableViewController = {
        // different initialization
        return UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "Table2ViewController") as! MyTableViewController
    }()

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {

var viewControllers = [MyTableViewController]()

    **viewControllers.append(table1ViewController)
    viewControllers.append(table2ViewController)**

    let pageTabBarController = AppPageTabBarController(viewControllers: viewControllers)
    let toolbarController = AppToolbarController(rootViewController: pageTabBarController)
    let menuController = AppFABMenuController(rootViewController: toolbarController)
    
    window = UIWindow(frame: Screen.bounds)
    window!.rootViewController = menuController
    window!.makeKeyAndVisible()
`

In this mode the storyboard configuration is not broken.

Regards,
Gogu.
