### ISSUE TITLE
Hiding Search bar controller or toolbar controller 

### ISSUE THREAD

**Issue by ZahraShams** [CosmicMind/Material#758]
I used search bar and tool bar controller in my view controllers which include tableview controllers as well, 
how can i hide search bar controller or toolbar controller when user scrolls down , just like inbox app in IOS
i also need this config for tab bar controller

**Comment by danieldahan** [comment]
The feature to make this happen has not been made yet. It will shortly, it is called scroll techniques. I have it noted to make this feature. Thank you!
