### ISSUE TITLE
Update depth preset to match updated elevation guidelines

### ISSUE THREAD

**Issue by sverin** [CosmicMind/Material#759]
Update the preset of depths (shadow) to match the new guidelines of ten levels of elevation:

1dp, 2dp, 3dp, 4dp, 6dp, 8dp, 9dp, 12dp, 16dp, 24dp

https://material.io/guidelines/material-design/elevation-shadows
https://material.io/guidelines/resources/shadows.html

**Comment by danieldahan** [comment]
Thank you, I will add this as a feature request and will post it in the next release.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
