### ISSUE TITLE
TabBar isTriggeredByUserInteraction wrong value

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#764]
Tab bar `isTriggeredByUserInteraction` is incorrectly false when the user taps a tab bar item:

https://github.com/CosmicMind/Material/blob/master/Sources/iOS/PageTabBarController.swift#L278

Calls on:
https://github.com/CosmicMind/Material/blob/master/Sources/iOS/TabBar.swift#L265

**Comment by danieldahan** [comment]
I don't see anything wrong with it. The user has not triggered the event. Maybe you can describe a scenario to better demonstrate how it is behaving incorrectly. Please reopen the issue when you do :) Thank you!
