### ISSUE TITLE
Capture API: sometimes when tapping returns an image darker than it usually is.

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#766]
Using the Capture API of this library, I could sometimes trigger this issue, when the user taps on a random part of the capture preview screen. The view would go darker than expected.

**Comment by danieldahan** [comment]
I believe it is because this is enabled: `isTapToExposeEnabled`. Try setting that to false. If the issue persists, please reopen the issue :) Thank you!

**Comment by jojonarte** [comment]
@danieldahan  I actually tried disabling that, but this occurs when trying to do the func capture.expose(point)
when I as a user would tap on something in the dark, it would go even darker.

**Comment by jojonarte** [comment]
I can't reopen btw.

**Comment by danieldahan** [comment]
Let me investigate this. I can do the investigation once I am done the latest animation and text view changes. So I will queue this up.

**Comment by jojonarte** [comment]
ok cool :)

**Comment by danieldahan** [comment]
The Capture API is getting completely revamped and is no longer in the Material release branch. So I am going to make a note of this and close it for now. Thank you!
