### ISSUE TITLE
Translucent NavigationBar

### ISSUE THREAD

**Issue by emadd** [CosmicMind/Material#767]
Just started using this impressive framework.  Is it not possible to set the NavigationBar as translucent?  I was just messing around with the sample project (NavigationController via Storyboard) and it appears that setting isTranslucent = true and barTintColor to black causes the bar to go completely transparent.

**Comment by danieldahan** [comment]
Thank you :) I will take a look.

**Comment by danieldahan** [comment]
Hey, sorry I fell completely behind on this issue. If it is still an issue, please reopen it, and I will be glad to help. Sorry for the inconvenience.
