### ISSUE TITLE
Capture API works bad in dark corners, especially in night time.

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#772]
I've tried this one which works pretty well with improved lighting in the dark, it is pretty much useful for devices that don't have flash such as iPads. 

https://github.com/ooper-shlab/AVCamManual-Swift

I can't seem to get where the lighting optimization happens in the code. I would've help if I have figured out. 

The preview really would look a lot darker using the Capture API of material.

**Comment by jojonarte** [comment]
I will supply some sample images below:

Using AVCamManualDemo(Apple demo): 
![avcammanual](https://cloud.githubusercontent.com/assets/11880365/26825066/366da6aa-4ae6-11e7-9355-0eefd2dbc2d4.jpg)

Using Material Capture API (Demo):
![capturematerial_api](https://cloud.githubusercontent.com/assets/11880365/26825082/4565dfba-4ae6-11e7-82b0-a5019d034de8.jpg)

**Comment by jojonarte** [comment]
After a few hours of struggling to find an answer, I was finally able to figure out how to get the same result as above , by setting the preset of capturecontroller's capture into .presetPhoto.

One question left is it takes too long like around 2 -4 seconds to load the capture controller now than before.

I've set the preset like this.
`override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
         guard let capture = captureController?.capture else {
            return
        }

    capture.capturePreset = .presetPhoto

    }
`

**Comment by danieldahan** [comment]
@jojonarte Thank you for sharing this. I plan to rewrite the Capture component. It is still using the initial write, and a lot has been learned since then, but has not been updated yet. If you continue to find issues, please send them my way :)

**Comment by jojonarte** [comment]
ok I will :)

**Comment by danieldahan** [comment]
I am going to close this issue, as you found a solution for the problem, and I have made the update in the development branch, which will be ready for release shortly. Thank you! :) Your help is very much appreciated.
