### ISSUE TITLE
Help ~ 😂🙏 ~ Swift 4 Support

### ISSUE THREAD

**Issue by Rdxer** [CosmicMind/Material#773]
pod 'Material'
xcode 9(Version 9.0 beta (9M136h))

```
Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /Users/xxx/Library/Developer/Xcode/DerivedData/XXQrcode-ecjlrkexvbbkdodejchzeabjtuce/Build/Products/Debug-iphonesimulator/Material/Material.framework/Modules/Material.swiftmodule/x86_64.swiftmodule
```

**Comment by danieldahan** [comment]
I am currently working on Material 3. I will have Swift 4.0 in there. It will take a few days to get it going, so until then I will keep this up :)

**Comment by Rdxer** [comment]
Thank you very much!

**Comment by gmoalvarez** [comment]
So, according to the Swift Migration Guide https://swift.org/migration-guide/ as long as you compile the cocoapods in Swift 3.2 you should be able to use them in Swift 4. When I do that though, I still get two compilation errors in the Material library.

**Comment by iceman201** [comment]
@Rdxer Follow the steps you should be sweet

![image](https://user-images.githubusercontent.com/5027957/28371298-affe8508-6cf0-11e7-8bbc-d5a00fb69ee4.png)

**Comment by ssrballin** [comment]
Just curious around when Material 3 is scheduled to release?

**Comment by danieldahan** [comment]
@ssrballin Good question. I am not setting a date, but I am already working on it, making small releases in the 2.* branch.

**Comment by danieldahan** [comment]
Adding issue: https://github.com/CosmicMind/Material/issues/861#issuecomment-328708212

**Comment by danieldahan** [comment]
Adding issue: https://github.com/CosmicMind/Material/issues/783
