### ISSUE TITLE
Orientation issue in NavigationDrawer

### ISSUE THREAD

**Issue by LukA888** [CosmicMind/Material#774]
Hi! 
My app supports both orientations and I have an UITableView built in _rightViewController_. 

My problem is:
- When I change the orientation for example from portrait to landscape, I can't scroll to the bottom of the table. 
- If I do landscape -> portrait (starting the app in landscape mode), the _rightviewcontroller_ height ends at half of the screen.

I need a way to set the correct height again. 
For example, If the orientation is changed and I call to `navigationDrawerController?.prepare()` the height will be recalculated. However, I think that's not the best solution.

Thank you for your time and all your awesome work! :)

**Comment by danieldahan** [comment]
Hi @LukA888 Would it be possible to send me a slimmed down sample project with the issues? Thank you! :)

**Comment by LukA888** [comment]
Hello @danieldahan!  I created a little project for you and I discovered that the problem occurs only if the _rightViewController_ has embedded a UINavigationViewController. Try it for example in a iPhone 7 :)

Here's the project:

[NavigationDrawer.zip](https://github.com/CosmicMind/Material/files/1060499/NavigationDrawer.zip)

**Comment by danieldahan** [comment]
@LukA888 The NavigationController is a tricky view controller in embedded child view controller. Have you tried the ToolbarController?

**Comment by danieldahan** [comment]
I haven't heard back from you. When you are ready to continue the discussion, please reopen the issue. Thank you :)

**Comment by LukA888** [comment]
Hi! Yes, I've tried using ToolbarController and works perfectly now.
Thank you!
