### ISSUE TITLE
NavigationController doesn't work

### ISSUE THREAD

**Issue by Recouse** [CosmicMind/Material#775]
I'm doing it as in the example https://github.com/CosmicMind/Samples/tree/master/Projects/Storyboards/NavigationController.
But navigationbar not work. It only shows navigationbar, and nothing changes.

**Comment by danieldahan** [comment]
Can you elaborate? By doing it as in the example, does the example work? If so, what are the differences?

**Comment by Recouse** [comment]
It only shows default NavigationBar:
<img width="375" alt="screen shot 2017-06-08 at 05 24 58" src="https://user-images.githubusercontent.com/7093328/26907165-e9f2762c-4c0a-11e7-92d3-952eff29bb3c.png">

**Comment by danieldahan** [comment]
Have you set in Storyboards the class `NavigationBar` ?

**Comment by Recouse** [comment]
Yes, of course.

**Comment by danieldahan** [comment]
<img width="1440" alt="screen shot 2017-06-07 at 7 31 24 pm" src="https://user-images.githubusercontent.com/9982123/26908446-f6623f08-4bb7-11e7-9ec0-be4a874f651d.png">

**Comment by danieldahan** [comment]
And you have done the same for the `NavigationController` ?

**Comment by danieldahan** [comment]
May you show me the code you are using to set the items?

**Comment by Recouse** [comment]
Oh, I mixed up NavigationController with NavigationBar.
All works after adding `NavigationBar` class.

**Comment by danieldahan** [comment]
Nice :) Let's close this up.
