### ISSUE TITLE
MOV File from AVCaptureFileOutput gets deleted or missing when running the app again

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#776]
So I am currently using the Capture API of this library to take videos now and record them. I am able to get the video from the outputfileURL by setting it into an AVPlayer on a new view controller. 

Everything seems to be working fine, I could load the video to the AVPlayer by doing anything aside from running the app again through Xcode's run button.

If I just go on testing/using the app to record and load the video/play/pause etc everything is fine even if when I kill the app and restart, etc.

The problem occurs when I run the app again using xcode's run button, the files of recorded videos would go missing leaving my AVPlayer with nothing to play. I could record again just fine, but the old recorded videos are gone.

```
public func capture(capture: Capture, captureOutput: AVCaptureFileOutput, didFinishRecordingToOutputFileAt outputFileURL: NSURL, fromConnections connections: [Any], error: Error!) {
        print("Capture Stopped Recording \(outputFileURL)")
        changeModeButton.isHidden = false
        captureButton.image = Icon.cm.videocam

       // This function is used to load up the url to an AVPlayer.
        self.loadVideoPreviewController(url: outputFileURL)
    }
```

**Comment by jojonarte** [comment]
Update: 
The files aren't really missing as I could list them up using a function listing all .mov files in documents. 
The issue was upon rerunning the app through xcode run my AVPlayer would show slashed play button.

**Comment by danieldahan** [comment]
This is a player issue. The files you record should be moved to a safe location once you receive them. They are more or less temporary when provided by Material. Try moving them to a folder in the shared application space, or documents directory, and if the issue still persists, reopen this issue. I am  almost ready to get back to the Capture component for a rewrite, and I will be more helpful then.
