### ISSUE TITLE
Uneven spacing between page bar tabs.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CosmicMind/Material#777]
<img width="314" alt="screen shot 2017-06-08 at 3 01 45 pm" src="https://user-images.githubusercontent.com/15869731/26915803-d004650a-4c27-11e7-96b9-99e9c433b998.png">

In the above screenshot, there is uneven spacing between the tabs. Is there a way in which we can customise the tab spacing to be even ?

Class used: `TabBar`

```
        tabBar = TabBar()
        tabBar.delegate = self
        
        tabBar.height = calendarTypeView.height
        tabBar.backgroundColor = Color.clear
        tabBar.lineAlignment = .bottom
        tabBar.lineHeight = 2
        tabBar.lineColor = UIColor.goldenColor()
        tabBar.dividerColor = Color.clear
        tabBar.buttons = buttons

```

**Comment by danieldahan** [comment]
It is not actually uneven, it is that the word sizes are different. The buttons themselves are even. In scrollable version of the TabBar, this has been solved. It is within the development branch, so for this version there is not much I can offer, without rewriting some code within Material. If you cannot find another alternative before I release the next Material version with this update, please reopen the issue. Thank you!
