### ISSUE TITLE
Issues combining NavigationController + NavigationDrawerController

### ISSUE THREAD

**Issue by juvs** [CosmicMind/Material#778]
I did a small project base on your NavigationController sample and I found the following:

1. When displaying the left viewcontroller from the AppNavigationDrawerController using toggleLeftView(), show it below the NavigationBar.

![screen shot 2017-06-10 at 2 23 10 pm](https://user-images.githubusercontent.com/204912/27005670-9c45258e-4de8-11e7-92f9-ac6f9a9ed812.png)

Is this the normal behaviour? based on the sample from NavigationDrawerController, left viewcontroller must show above, right?

2. When navigate to the TransitionViewController using FAB button, and trying back RootViewController using drag gesture, if you did that really fast, NavigationBar shows with some alpha filter.... Check this video: https://youtu.be/4SecbdBmV84

Here's the sample project.

[NavigationControllerTest.zip](https://github.com/CosmicMind/Material/files/1066082/NavigationControllerTest.zip)

**Comment by danieldahan** [comment]
Hey :) 

You need to flip the order of the view controller hierarchy. 

```swift
func applicationDidFinishLaunching(_ application: UIApplication) {
        let rootViewController = RootViewController()
        let appNavigationController = AppNavigationController(rootViewController: rootViewController)
        let leftViewController = LeftViewController()
        
        let appNavDrawerController = AppNavigationDrawerController(rootViewController: appNavigationController, leftViewController: leftViewController)
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = appNavDrawerController
        window!.makeKeyAndVisible()
    }
```

Thank should fix it.

**Comment by juvs** [comment]
Excellent! Works ok, did you check point 2, maybe I should open a separate issue?

**Comment by danieldahan** [comment]
No I didn't see that. Can you send me the sample you are working from?

**Comment by juvs** [comment]
Already attach a sample and a url video

**Comment by danieldahan** [comment]
Ah, then yes I tried it, but didn't see the issue. Let me see, btw, I am guessing you recorded the bug on the simulator, if so, which one, and have you tried a device?

**Comment by juvs** [comment]
Correct! I record from emulator (iPhone 6 - iOS 10.3), I try on a real phone and works like a charm, but you never know... at least there's evidence and maybe is not a real "user" scenario. Anyway thanks for your "pronto" feedback... 

:thumbsup: :thumbsup: for this great framework!!!

**Comment by danieldahan** [comment]
Anytime :) I am always excited to get feedback. I am going to close this, as simulator issues are usually a result of the simulator. As long as it works on a device, I will dive into the issue. Thanks again!

**Comment by danieldahan** [comment]
Btw, the simulator issue is probably because you are swiping fast and and the cursor goes off the simulator, so the animation is cut.

**Comment by juvs** [comment]
Agree!
