### ISSUE TITLE
Capture API: Camera preview not correct

### ISSUE THREAD

**Issue by shemchavez** [CosmicMind/Material#779]
When CaptureController is being push using navigation controller, camera preview is always portrait. When going to landscape it won't reflect the camera preview. But when it's just a "self.present" it's okay like the sample project. How can I manipulate when orientation is landscape and the camera preview is also landscape. Captured image have correct orientation, just the camera preview.

See this link.
Lanscape but the camera preview orientaion is portait - https://goo.gl/photos/CE8CYNb2HtdZ8nFo9

**Comment by shemchavez** [comment]
Solved! This line fix the issue - **(capture.preview.layer as! AVCaptureVideoPreviewLayer).connection.videoOrientation = videoOrientation**, just put it in the delegate function **func capture(capture: Capture, didChangeFrom previousVideoOrientation: AVCaptureVideoOrientation, to videoOrientation: AVCaptureVideoOrientation)**

**Comment by danieldahan** [comment]
@shemchavez excellent :) Thank you!

**Comment by shemchavez** [comment]
Your'e welcome @danieldahan 👍
