### ISSUE TITLE
Side Navigation Menu gives jerking issue

### ISSUE THREAD

**Issue by adeesh** [CosmicMind/Material#780]
on first time opening of navigation menu, it gives jerking issue. 

Also if i select some item in menu and keep navigation menu open then push new controller on top of it then on press of back from that controller, it gives jerking.  This issue is noticeable in iphone6, iphone6 plus.

Any tips to optimize this behavior would be great.

**Comment by danieldahan** [comment]
@adeesh You would need to send me a sample so I can reproduce this issue. It may be because the shadow animations are set / not set correctly. Can you send a sample to support@cosmicmind.com. Thank you!

**Comment by danieldahan** [comment]
Hey, I have not heard from you, so when you are ready, please reopen the issue. Thank you!
