### ISSUE TITLE
Navigation bar shadow cannot be removed

### ISSUE THREAD

**Issue by sxmichaels** [CosmicMind/Material#781]
# Problem
The code at [this link](https://medium.com/simple-swift-programming-tips/how-to-disable-uinavigationbar-shadow-in-ios-9-swift-2bdf6e9be41e) details how to remove the shadow at the bottom of a regular UINavigationBar. This same method, when used on a Material `NavigationBar` (for instance, adding those two lines to the navbar sample [here](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationController/NavigationController/RootViewController.swift#L49).) has no effect.

# Proposed fix
Material's `NavigationBar` class  actually seems to be attempting to do the same thing already in `prepare()` (see [here](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationBar.swift#L300)). Through some experimentation, I've discovered that if you comment out `depthPreset = .depth1` in `prepare()` ([line 294 in NavigationBar.swift](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/NavigationBar.swift#L300)) the shadow will disappear without me needing to do anything in my own app, so it looks like this line is interfering somehow with your attempt to remove the shadow a few lines later. I think an appropriate fix is probably just to **remove that line** — I don't know what `depthPreset` is supposed to do, but commenting out that line doesn't appear to result in any change.

As a temporary fix, it's possible to use `navigationController?.navigationBar.depthPreset = .none` from within one's own app to remove the shadow. However, it would be nice for `NavigationBar` to have a variable exposed that toggles the shadow.

# Version info
Targeting iOS 9 with XCode 8.2.1 on OSX 10.11.

**Comment by danieldahan** [comment]
Thank you for sharing this. Are you using storyboards?

**Comment by sxmichaels** [comment]
No, my app does everything programmatically.

2017年6月18日 14:40，"Daniel Dahan" <notifications@github.com>写道：

Thank you for sharing this. Are you using storyboards?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CosmicMind/Material/issues/781#issuecomment-309294973>,
or mute the thread

**Comment by danieldahan** [comment]
Then you would need to share a sample project with me that reproduces the issue. I am not getting any issues with the NavigationBar at the moment. Would you be able to do that?

**Comment by sxmichaels** [comment]
Do you mean that if you build and run the NavigationBar sample from
Material (the second link in my first post above, I'm on my phone now so
it's hard to paste in) then you don't see the drop shadow? When I do, the
shadow is definitely there.

The app is closed source so I can't share it directly, but an equivalent
test is to take the sample app and add
`navigationController?.navigationBar.depthPreset
= .none` at the end of viewDidLoad of the RootViewController. I did the
same thing and was able to see a difference - the shadow should be gone.

2017年6月18日 14:55，"Daniel Dahan" <notifications@github.com>写道：

Then you would need to share a sample project with me that reproduces the
issue. I am not getting any issues with the NavigationBar at the moment.
Would you be able to do that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CosmicMind/Material/issues/781#issuecomment-309295837>,
or mute the thread

**Comment by danieldahan** [comment]
You cannot add it to the viewDidLoad of the view controller, because the optional `navigationController` property has not been set. You will need to do it in a subclass of the NavigationController within the `prepare` statement, or in the `viewWillAppear` method of the view controller, which will have the `navigationController` property set. 

Let me know how that works out.

**Comment by sxmichaels** [comment]
Oh, then probably I just misremembered when I said `viewDidLoad` - I don't
have the code in front of me right now. I'll be back at my computer in a
few hours and I'll let you know then what works (and give screenshots).

2017年6月18日 15:11，"Daniel Dahan" <notifications@github.com>写道：

You cannot add it to the viewDidLoad of the view controller, because the
optional navigationController property has not been set. You will need to
do it in a subclass of the NavigationController within the prepare
statement, or in the viewWillAppear method of the view controller, which
will have the navigationController property set.

Let me know how that works out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CosmicMind/Material/issues/781#issuecomment-309296707>,
or mute the thread

**Comment by danieldahan** [comment]
Generally, people make the same mistake. So you are probably correct about the code. Hopefully it is as simple as the recommendation I made. either way, we will figure it out. Thank you, and let me know how it turns out.

**Comment by sxmichaels** [comment]
Ah, so I found where I was wrong — you have a custom `prepare()` function in the example app that already sets `navigationBar.depthPreset = .none` ([AppNavigationController.swift line 41](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationController/NavigationController/AppNavigationController.swift#L41)) and I guess what's what I was messing with yesterday — the line I mentioned above was what I used in my own app.

**Comment by sxmichaels** [comment]
(Oops, sorry, I accidentally closed this a moment ago.)

So I found where I was wrong — you have a custom `prepare()` function in the example app that already sets `navigationBar.depthPreset = .none` ([AppNavigationController.swift line 41](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationController/NavigationController/AppNavigationController.swift#L41)) and I guess what's what I was messing with yesterday; the line I mentioned above was what I used in my own app.

Pictures below. The first one is with `depthPreset = .none` and the second is with the line commented out.
<img width="733" alt="screen shot 2017-06-18 at 5 28 49 pm" src="https://user-images.githubusercontent.com/13933679/27264452-dacd5302-544c-11e7-9b2e-2bbddcc6b0b8.png">
![screen shot 2017-06-18 at 5 32 04 pm](https://user-images.githubusercontent.com/13933679/27264454-ddf63aee-544c-11e7-8ea7-9db98fabb9be.png)

**Comment by danieldahan** [comment]
Yeah everything is correct. Remove the color from the divider line, you are not looking at a shadow, you are looking at the `navigationBar.dividerColor` being set.

**Comment by sxmichaels** [comment]
I see. Although, it's still the case that the default setting for `NavigationBar` is to show the shadow, and it's not obvious that you need to use `depthPreset = .none` to disable it. Maybe it would be a good idea to add a function or computed var like `dropShadowEnabled` that makes the toggle more explicit?

**Comment by danieldahan** [comment]
In this case that won't make sense, since a developer would need to manage multiple variables to set the depth. By setting it to `.none` it is clear that the depth will be gone. What really needs to exist is documentation that outlines this. I believe that is the best approach :) I am working on documentation for Material 3 and the latest updates. I will be sure to include this. Sorry for the inconvenience.
