### ISSUE TITLE
navigation item buttons not aligned correctly - xcode 9

### ISSUE THREAD

**Issue by volkangurol** [CosmicMind/Material#783]
im using Material Library in xcode 9,
if i use NavigationController  items not align correctly,
if i use ToolBarController  items align correctly
any quick fix / workaround is appreciated.

<img width="477" alt="screen shot 2017-06-20 at 05 45 36" src="https://user-images.githubusercontent.com/2510054/27314336-c7fc694a-557b-11e7-8b66-93c76109c632.png">

**Comment by danieldahan** [comment]
I haven't updated Material for Xcode 9 yet. I will need to look into that. I will keep this up and get back to you with a solution once I move Material to Xcode 9.

**Comment by robertying** [comment]
I also found this issue in the simulator but the problem will not appear in the real devices. Better use actual devices to run the app.

**Comment by danieldahan** [comment]
I have made an adjustment for this, now it centers correctly. That said iOS 11 introduces a new view container within the hierarchy. So I am working out that last issue.

**Comment by danieldahan** [comment]
This should be solved now. Thank you! :)
