### ISSUE TITLE
Incorrect layout for TableViewWithinCard with CardTableView

### ISSUE THREAD

**Issue by davros1970** [CosmicMind/Material#784]
Having an issue with using the TableViewWithinCard sample in the CardTableView sample. The layout of the default UITableViewCell.imageView is fine, but UITableViewCell.textLabel is shifted off-screen to the left of the imageView.

I noticed if I set the backgroundColor of the UITableViewCell to any color, that it is not spanning the entire width of its parent tableView (which goes the width of the screen). The samples by themselves work fine, but not together.

![simulator screen shot jun 20 2017 12 39 47 pm](https://user-images.githubusercontent.com/17870359/27352535-eb9eea46-55b5-11e7-8329-bfaef60f2933.png)

I modified CardTableViewCell.swift from CardTableView sample as follows:

`
import UIKit
import Material
import Graph

class CardTableViewCell: TableViewCell {

    open var dataSourceItems = [DataSourceItem]()

    private var spacing: CGFloat = 10
    
    /// A boolean that indicates whether the cell is the last cell.
    public var isLast = false

    fileprivate var toolbar: Toolbar!
    fileprivate var tableView: TableView!
    fileprivate var card: Card!

    public var data: Entity? {
        didSet {
            layoutSubviews()
        }
    }
    
    /// Calculating dynamic height.
    open override var height: CGFloat {
        get {
            return card.height + spacing
        }
        set(value) {
            super.height = value
        }
    }
    
    override func layoutSubviews() {

        super.layoutSubviews()

        toolbar.title = "Title"
        toolbar.detail = "Detail"
        
        card.x = 0
        card.y = 0
        card.width = width
        
        card.setNeedsLayout()
        card.layoutIfNeeded()

        tableView.reloadData()
    }
    
    open override func prepare() {
        super.prepare()
        
        layer.rasterizationScale = Screen.scale
        layer.shouldRasterize = true
        
        pulseAnimation = .none
        backgroundColor = nil
        
        prepareToolbar()
        prepareTableView()
        preparePresenterCard()
    }
    
    private func prepareToolbar() {
        toolbar = Toolbar()
        toolbar.heightPreset = .xlarge
        toolbar.contentEdgeInsetsPreset = .square3
        toolbar.titleLabel.textAlignment = .left
        toolbar.detailLabel.textAlignment = .left
        toolbar.dividerColor = Color.grey.lighten3
        toolbar.dividerAlignment = .top
    }
    
    private func preparePresenterCard() {

        card = Card()
        card.toolbar = toolbar
        card.contentView = tableView

        contentView.addSubview(card)
    }

    fileprivate func prepareTableView() {
        tableView = TableView()
        tableView.height = 300
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.isScrollEnabled = false
        tableView.register(TableViewCell.self, forCellReuseIdentifier: "TableViewCell")
    }

}

extension CardTableViewCell: TableViewDelegate {}

extension CardTableViewCell: TableViewDataSource {

    @objc
    open func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    @objc
    open func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 2
    }

    @objc
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TableViewCell", for: indexPath) as! TableViewCell

        cell.imageView?.image = Icon.addCircleOutline
        cell.textLabel?.text = "row \(indexPath.row)"

        return cell
    }
}

`

**Comment by danieldahan** [comment]
Hey, thank you for sharing this. Funny enough, I was working on a similar issue when combining these two components. I will try your code later today, does it solve the issue?

**Comment by davros1970** [comment]
Good, glad you'll be able to help look at this. I tried to work around it with my own custom UITableViewCell nib with autolayout but that didn't seem to help. There's something in the default programmatic TableView layout code thats not happy and I need to set it up I suppose, but I'm unable to find that magic. As it stands right now, I removed the tableview from the card as I only had a handful of static rows, so I manually made a UIView with static ImageViews and UILabels to emulate the UI of a table.

Hoping there will be a better solution to go back to the table in the card at some point.
Thx!

**Comment by danieldahan** [comment]
:) I will notify you once I have a solution. I am working on this particular issue in my work at the moment, so your timing is impeccable.

**Comment by davros1970** [comment]
I think this usage will be common for the worker bees out there so once there's a solution maybe a new sample would be helpful ultimately for others.

**Comment by danieldahan** [comment]
I am actually working on an Advanced sample pack for all the updates I have been doing and this is in there. So you are right on point.

**Comment by davros1970** [comment]
Excellent! Thx! Looking forward to that.
