### ISSUE TITLE
How to control original back button on navigationBar

### ISSUE THREAD

**Issue by Noodlekim** [CosmicMind/Material#785]
Hello.
I just want to set customized back button on navigationBar except original back button.
But I can't remove original back button like this screenshot.
<img width="375" alt="2017-06-21 08 53 38" src="https://user-images.githubusercontent.com/5136313/27360952-3f5b9b1c-565f-11e7-95a9-bf2577e5005e.png">

Moreover It can't be adjust `navigationBar.tintColor`
How to solve this issue? Please help~😥

**Comment by Noodlekim** [comment]
Sorry I just solved by myself.

Before I did set about navigation Bar options when viewDidLoad.

I modified `viewWillLayoutSubviews `. It is working good.
```
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        prepareNavi()
    }
```

**Comment by Noodlekim** [comment]
I think that this method 👆is not so good.
Because it need to input `prepareNavi()` in every detail viewController when I push sub viewController.
I want to set this just one time.
So I am trying to change tintColor original back button. But It was not work.

**Comment by danieldahan** [comment]
Try subclassing the `NavigationController` and setting the overall values you would like in there. 

```swift
class AppNavigationController: NavigationController {
    open override func prepare() {
        super.prepare()
        guard let v = navigationBar as? NavigationBar else {
            return
        }

        v.depthPreset = .none
        v.dividerColor = Color.grey.lighten3
    }
}
```

If you need any further help, feel free to reopen the issue. Thank you!
