### ISSUE TITLE
Drawer does not resize to fit when rotating device

### ISSUE THREAD

**Issue by ajonp** [CosmicMind/Material#787]
I am adding the drawer to the root
```
            let pageTabBarController = AppPageTabBarController( viewControllers:[myActivitiesViewController,myFollowingViewController,myFollowersViewController], selectedIndex: 0)
            let appToolbarController = AppToolbarController(rootViewController: pageTabBarController)
            
            window = UIWindow(frame: Screen.bounds)
            window!.rootViewController = AppNavigationDrawerController(
                rootViewController: appToolbarController,
                leftViewController: leftViewController,
                rightViewController: rightViewController)
            window!.makeKeyAndVisible()
```

**This is my layout**
![image](https://user-images.githubusercontent.com/3102249/27386573-470281c8-5664-11e7-9c41-609e1675643e.png)
**When this is in a vertical it looks great**
![image](https://user-images.githubusercontent.com/3102249/27386627-68cdd92e-5664-11e7-9bde-eb2eb49da928.png)
However when I rotate it the drawer I think wants to stay centered to its original position, so I loose all of my items up above the view.
![image](https://user-images.githubusercontent.com/3102249/27386668-83544b0c-5664-11e7-8ace-324e3cd0583d.png)

Ultimately I want it to rotate just like on my android view.
**Vertical Android**
![image](https://user-images.githubusercontent.com/3102249/27386792-e0f94a50-5664-11e7-957c-61a7f479a84b.png)
**Horizontal Android**
![image](https://user-images.githubusercontent.com/3102249/27386821-f6f83bf4-5664-11e7-88dc-72af7caed2a6.png)

I do notice that on android the entire drawer is allowed to scroll, maybe the drawer needs a scroll view at its top level??

**Comment by danieldahan** [comment]
You would need to handle changes in the panel view controllers by recalculating the view hierarchy when the view will layout. For example: 

```swift
open override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        layoutColorChoicesView()
        layoutColorCollectionView()
    }
```

If you need further help, please reopen the issue. Thank you!
