### ISSUE TITLE
anyone tried launching AEConsole

### ISSUE THREAD

**Issue by rushstrike** [CosmicMind/Material#790]
anyone succesful in getting AEConsole to work with this material UI? I use the code below and cannot get the console to open. I tried.commenting out setting the rootview controller and doesn't work either.
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

window = UIWindow(frame: Screen.bounds)
AEConsole.launch(with: self)
signinvc = SignInViewController()
window!.rootViewController = signinvc //SignInViewController()
window!.makeKeyAndVisible()
return true
}
```

**Comment by danieldahan** [comment]
This is better as a StackOverflow question. Not sure what AEConsole is and how it relates to Material. All the best :)
