### ISSUE TITLE
I have one query, How to set small font size when placeholder is active in textfield ? 

### ISSUE THREAD

**Issue by Akshayp101192** [CosmicMind/Material#792]

**Comment by danieldahan** [comment]
You want the size of the font to get smaller? It already shrinks to fit proportionally. If you start changing that, the component may not animate with the correct look and feel. Can you elaborate more on what you are trying to accomplish, possibly include a visual representation?

**Comment by Akshayp101192** [comment]
![screen shot 2017-06-28 at 10 49 27 am](https://user-images.githubusercontent.com/28347440/27621613-a5cf5092-5bef-11e7-88a7-a77e93d20a3a.png)
Please check this .. and suggest me i have not set custom font . I want active placeholder font to be smaller .

**Comment by danieldahan** [comment]
As I mentioned, it should be smaller by default. Can you share a sample project reproducing this issue?

**Comment by Akshayp101192** [comment]
is it because of constraints I set to textfield ?

**Comment by danieldahan** [comment]
Maybe, I need to see a reproducible sample in order to give correct feedback.

**Comment by danieldahan** [comment]
I am going to close this issue for now. Once you have a reproducible project, please send it to support@cosmicmind.com :) Thank you!
