### ISSUE TITLE
navigationbar frame issue

### ISSUE THREAD

**Issue by Tahlia-rt** [CosmicMind/Material#793]
Good day!
this issue about NavigationBar.swift , layoutShape() in the open override func layoutSubviews()

this was reported from Fabric, it was written;

"This crash has non-main threads that appear to use UIKit classes or functions. Generally speaking, it is only safe to use UIKit from the main thread. Calling into UIKit from background threads can cause unpredictable behavior (like crashes!).. Please double check that all of your code (that is not on the main thread) has been explicitly marked as safe to use in the background by Apple.""

My Navigationbar height is resized in AppNavigationController, inherited NavigationController.
so should I use dispatchqueue.main? Actually I did, but it is called after viewDidLoad in ViewController, so too late to set the frame that i resized. finally, i set that frame in the viewDidLoad, it worked well. But it would be not a good idea.

here is my code below;
<img width="781" alt="2017-06-29 3 42 23" src="https://user-images.githubusercontent.com/20659671/27674691-ab33deca-5ce1-11e7-8000-f0dc5f47f911.png">

If you need information more, please tell me i will reply asap

Thanks!

**Comment by danieldahan** [comment]
Hey, resizing the frame in the `prepare` function is the correct place to do it :) 

Was that your question?

**Comment by danieldahan** [comment]
Hi, I haven't heard from you. If you need, please reopen the issue. Thank you!

**Comment by Tahlia-rt** [comment]
ooh i should have used it. it could be occurred the thread issue!! Thank you very much!! :)

**Comment by danieldahan** [comment]
Great! Anytime :)
