### ISSUE TITLE
How to add a SearchView to an instantiated Controller

### ISSUE THREAD

**Issue by CAP-ONE** [CosmicMind/Material#794]
So to start, I'm completely new to iOS & Swift Development, coming from Android, so I naturally got attired by this lib. But one thing I can't get around is how do I add a simple SearchView (+ "More Menu" button and Graph, like in the sample) from an instantiated Controller ?

My project start with a first controller with only a login form, and after a successful authentification, the user is redirected to my instantiated controller, the main menu of my app, where I want to put the searchView. But the sample project only show you how to add it as the rootViewController of your app.

**Comment by danieldahan** [comment]
Hey :) Welcome to iOS and Material. Please use the [Gitter Material](https://gitter.im/CosmicMind/Material) channel to get help for this matter. I will be available to help you.
