### ISSUE TITLE
How to replace back button in Material in Swift

### ISSUE THREAD

**Issue by javimuu** [CosmicMind/Material#797]
I want to change behavior of back button and I replace back button of **Material** with new bar button like bellow:

    let backButton: UIButton = {
        let btn = UIButton()
        btn.setImage(UIImage(named: "prev"), for: .normal)
        btn.frame = CGRect(x: 0, y: 0, width: 33/2, height: 27/2)
            
        return btn
    }()

In **viewDidLoad** function:

    override func viewDidLoad() {
        super.viewDidLoad()
    
        backButton.action = { [weak self] in self?.showAlert() }
        let barButton = UIBarButtonItem(customView: backButton)
        navigationItem.backButton.isHidden = true
        navigationItem.leftBarButtonItems = [barButton]
    }

But I can not click to **new back button** because it was coverred by **UINavigationBarBackIndicatorView**.

How can I replace back button with **Material**?

**Comment by danieldahan** [comment]
Hey, I made a fix for this in development. I am going to release a new version of Material with it in the next few days.

**Comment by javimuu** [comment]
Yeah. Thank you very much  for this fix.

**Comment by danieldahan** [comment]
You can find a fix for this in [Material 2.7.0](https://github.com/CosmicMind/Material/releases/tag/2.7.0) :)
