### ISSUE TITLE
Issue with present/dismiss - navigation controllers for each tab within tabbarcontroller 

### ISSUE THREAD

**Issue by bilsou** [CosmicMind/Material#799]
My issue is the following: I have a MainTabBarController as the root of my window 
`window!.rootViewController = MainTabBarController()`
I have a navigation controller for each tab.
``` swift
        let v1 = FirstViewController()
        let v2 = SecondViewController()
        let v3 =ThirdViewController()
        let v4 = FourthViewController()
        let v5 = FifthViewController()
        
        let n1 = AppNavigationController(rootViewController: v1)
        let n2 = AppNavigationController(rootViewController: v2)
        let n3 = AppNavigationController(rootViewController: v3)
        let n4 = AppNavigationController(rootViewController: v4)
        let n5 = AppNavigationController(rootViewController: v5)

        let controllers = [n1, n2, n3, n4, n5]
        mainTabBarController.viewControllers = controllers
```

If I navigate, for instance, from my `FirstViewController` to a `CustomViewController` `self.navigationController?.pushViewController(CustomViewController(), animated: true)` then within `CustomViewController` I present another ViewController via `self.present(ModalVC(), animated: true)`. 
Calling `self.dismiss(animated: true)` within ModalVC does not bring me back to `CustomViewController` but  to `FirstViewController`.

I am quite confused as I tried several scenarios like creating a local navigationController containing my ModalVC
```swift
      let navVC = AppNavigationController(rootViewController: ModalVC())
      self.navigationController?.present(navVC, animated: true)
```
but it still goes back to `FirstViewController` and not `CustomViewController`

I might misunderstand  the way of presenting/dismissing a modal view controller so any explanation would  be more than welcome.

**Comment by danieldahan** [comment]
So this is really an iOS issue not a Material issue. That said, if you go to the [Gitter Material](https://gitter.im/CosmicMind/Material) channel, I can help you there :)

**Comment by bilsou** [comment]
I thought it was related to some issue with the Material's Navigation Controller. But fair enough I followed up your link and posted the issue on Gitter. 
Thanks in advance
