### ISSUE TITLE
Not able to Work with Xcode 8.2 with Material pod

### ISSUE THREAD

**Issue by sumitkapoorshineweb** [CosmicMind/Material#802]
Hello Friend, 
               I am using Material pod, version 1.42.9 with Xcode 7.3.1 . And it is working fine with Xcode 7.3.1 . Now I am trying to update my project for Xcode 8.2 But I am not able to solve Material pod issue, it gives legacy swift version issue, I tried to Set swift_version to 'YES' , 'NO' , trying to update latest Material version But issue is still there , Material gives thousands error. Can anyone please suggest me which Material version I used to work with Xcode 8.2. As I am stuck with Material Now.

**Comment by danieldahan** [comment]
Hey :)

You will need to upgrade a few things. Firstly, move to Xcode 8.3.* if you can, as that will save you upgrade time in general. If that is not possible, then make sure you have upgraded CocoaPods to the latest. Make sure to upgrade Material to the latest, and then clear your pod cache and User Derived directory in Xcode. If you need, connect on the [Gitter Material](https://gitter.im/CosmicMind/Material) channel and I can help you further. All the best!
