### ISSUE TITLE
Add convenience property for the attributed text of the text field placeholder label

### ISSUE THREAD

**Issue by asadali737** [CosmicMind/Material#803]
This will allow for developers to access the attributedText property of the UILabel of the text field placeholder and let us set attributed text to it for both modes. (Editing/Not Editing)

**Comment by danieldahan** [comment]
I believe you can access it through the `placeholderLabel`. If not, please reopen the issue :)

**Comment by asadali737** [comment]
We can set attributed string to `placeholderLabel ` but problem is, it has no effect. Because it's text colour get changed when we start editing text field. 
My actual requirement is to assign multicolour text to `placeholderLabel ` with different font sizes.

**Comment by danieldahan** [comment]
Okay, I understand. Let's reopen this as a feature request.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!

**Comment by turtle0001** [comment]
Hello, do this requested feature now available? The ability to have two different placeholder text for inactive and active textfield? 

Thank you!

**Comment by danieldahan** [comment]
@turtle0001 no, that feature is not available, but it shouldn't be that difficult to make it work. Have you tried any solutions yet?
