### ISSUE TITLE
Crash while changing viewControllers in PageTabbarController

### ISSUE THREAD

**Issue by Rico9260** [CosmicMind/Material#804]
![screen shot 2017-07-11 at 5 16 29 pm](https://user-images.githubusercontent.com/14157753/28067015-0258b868-665d-11e7-92bc-59c903a0223c.png)

When I tap rapidly on tabbar buttons to change the selected index it crashes and navigates me to this line in Code.

You can reproduce it by rapidly tapping the tabbar buttons.

Thanks

**Comment by danieldahan** [comment]
Excellent, thank you! I will take a look at this.

**Comment by danieldahan** [comment]
The `PageTabBarController` has been updated with a new `TabsController`. This should fix your issue. Thank you!
