### ISSUE TITLE
Can't properly hide Back Button

### ISSUE THREAD

**Issue by CAP-ONE** [CosmicMind/Material#805]
Hello, in my app, I've 3 ViewControllers, a login screen, a TableView screen and a screen which provide detailed infos of a row clicked from the TableView Page. I've a NavigationController for each pages, I want to hide the back button on the TableView Page to prevent the user from coming back on the login screen, and replace it with a menu button, I've managed to hide it but the space for the back button is still present and thus the menu button is offsetted : 

Screen : http://i.imgur.com/dPceDgl.png

I've searched far and wide on the issues, only one thread speak about it : [#561](https://github.com/CosmicMind/Material/issues/561) , but he doesn't say how he solved his issue

**Comment by danieldahan** [comment]
Thank you for sharing this. I have a fix for this in development, and added features to hide, change, and manipulate the back button. I will leave the issue up and notify you once I have released Material 2.7.0.

**Comment by danieldahan** [comment]
In the meantime, have you tried using the ToolbarController for the login screen and then a NavigationController for the page you are creating. This will make it that you actually don't have a back state, and will not need to hide the back button. An idea for you as a workaround for now.

**Comment by CAP-ONE** [comment]
Thanks for the reply. I tried the ToolbarController for the login screen yes, but I ran into a lot of trouble, like I couldn't access toolbar instance from the controller, nor pushing the next controller with navigationController.pushViewController (my guess was ToolbarController doesn't create a navigationController for the rootController).

I'll keep experimenting, but as I don't know when Material 2.7.0 will be released, and my application must be released soon, are those features in development are stable enough to be integrated in the current version ? Thanks

**Comment by danieldahan** [comment]
Yes, I have already submit an app with the development branch, Material Colors. All is fine. I am mainly working on documentation right now. As for accessing the ToolbarController, after the `viewWillAppear` message, you can call the `toolbarController` optional property that accesses the parent ToolbarController. You can either change the `rootViewController` with the `transition` helper function, or you can present a new UIViewController using the `present` function. I am going to close this issue, and if you need, please reopen it :)
