### ISSUE TITLE
Tabbar covered when using PageTabBarController inside NavigationController

### ISSUE THREAD

**Issue by rodolfohelfenstein** [CosmicMind/Material#806]
When I create a UINavigationViewController and set PageTabBarController as root my PageTab stay behind of NavigationBar.
Issue #679 describes something very similar that happened to some old versions, but I am in 2.6.3 and the problem persists

<img width="1103" alt="screen shot 2017-07-12 at 21 06 33" src="https://user-images.githubusercontent.com/4798334/28145194-9f2bf7d8-6746-11e7-8ec3-525675c6ed67.png">

**Comment by danieldahan** [comment]
Thank you for sharing this. Can you send a sample project over?

**Comment by danieldahan** [comment]
Hey, I have not heard from you, so I will close this issue, and if you need, please reopen it. Thank you!

**Comment by thatmarcel** [comment]
Hi, I'm using version 2.15 and my TabBar is still covered by the navigation bar. What can I do?

**Comment by danieldahan** [comment]
@thatmarcel Please send me a reproducible project to support@cosmicmind.com and I will be happy to help. Thank you!
