### ISSUE TITLE
I can't use development branch of Material

### ISSUE THREAD

**Issue by mirjalolbahodirov** [CosmicMind/Material#808]
Hello, @danieldahan 
Currently, I need to use scrollable Tabbar view. As I know it is working on development branch. But I can't use development branch with Cocoapods (my version is 1.2.1). Let me share my podfile content:

`pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'`
`pod 'Graph', '~> 2.0'`
`pod 'Motion', :git => 'https://github.com/CosmicMind/Motion.git', :branch => 'development'`

When I build project, Xcode says that: "/Users/mirjalol/Desktop/Samples-master/Projects/Programmatic/CardTableView/Pods/Material/Sources/iOS/Material+MotionAnimation.swift:33:11: Use of undeclared type 'MotionAnimation'"

My Xcode version is 8.3.3 and Swift version is 3
<img width="864" alt="screen shot 2017-07-15 at 19 46 31" src="https://user-images.githubusercontent.com/12315407/28240210-5bbc9d20-6996-11e7-87df-1c9bfe4c737a.png">

**Comment by mirjalolbahodirov** [comment]
Please, help me :-)

**Comment by mirjalolbahodirov** [comment]
@danieldahan can you give me any suggestions?

**Comment by danieldahan** [comment]
Hey, I wouldn't use the development branch right now. I am making a release after I finish the transition documentation. Then I will be making another release with the scrollable tab bar. Sorry I can't be any more help at this point. I will update this issue once it is out: https://github.com/CosmicMind/Material/issues/642.
