### ISSUE TITLE
detailTextLabel not working in TableViewCell

### ISSUE THREAD

**Issue by 01taylop** [CosmicMind/Material#809]
It seems that the `detailTextLabel` is not displaying inside `TableViewCell`.

1. I have just downloaded Samples and am looking at the Search example:
  `cd Downloads/Samples-master/Projects/Programmatic/Search`

2. Install Pods:
  `pod install`

```
Installing Graph (2.1.4)
Installing Material (2.6.3)
```

3. In `SampleData.swift` I can see that each `Entity` has a status:
  `u1["status"] = "Making the world a better place, one line of code at a time."`

4. The status is being used in `UserTableView` but it is not displayed.
  `cell.detailTextLabel?.text = user["status"] as? String`

![simulator screen shot 15 jul 2017 16 20 53](https://user-images.githubusercontent.com/727360/28240423-9a2e1826-6979-11e7-8d56-3a27582d0c88.png)

**Comment by danieldahan** [comment]
This was a good find. I made updates to Material and the sample to fix the issue. I will update this issue once I release it from the development branch. Shouldn't be long at all.

**Comment by danieldahan** [comment]
You can find a fix for this in [Material 2.7.0](https://github.com/CosmicMind/Material/releases/tag/2.7.0) :)
