### ISSUE TITLE
Scrollable TabBar incorrect divider position

### ISSUE THREAD

**Issue by haluzak** [CosmicMind/Material#811]
I noticed an issue with `TabBar` which is used by `PageTabBarController` when the divider is visible and `tabBarStyle` is set to `.scrollable`. The divider is initially at correct position, but after I scroll to another controller, the divider `x` offset is off. The `x` position is calculated correctly when tapping on tabs (although there is a weird/glitchy animation, the bounce starts animating and is immediately corrected).

Here's a `PageTabBarController` with multiple tabs after first scroll:
![pagetabbarcontroller divider line](https://user-images.githubusercontent.com/1022956/28431646-546feafc-6d85-11e7-901f-31c1c86b2590.png)

**Comment by danieldahan** [comment]
Darn, I shouldn't have released that feature in this version. I will need to take that out now until it is ready. Thank you! I am going to close this issue, as the feature was accidentally released and will be removed now.

**Comment by danieldahan** [comment]
Thank you! [Material 2.7.1](https://github.com/CosmicMind/Material/releases/tag/2.7.1) is available.
