### ISSUE TITLE
Scroll indicators visible after using Motion transition

### ISSUE THREAD

**Issue by gilthonweapps** [CosmicMind/Material#814]
Hi,

I have one issue when using Motion to animate the transition between views.

I have created a subclass of UITabBarController, so I can animate the transition between all the tabs. Here is the code:
```swift
class MyTabBarController: UITabBarController {

    override func viewDidLoad() {
        super.viewDidLoad()

        isMotionEnabled = true
        motionTabBarTransitionType = .autoReverse(presenting: .slide(direction: .left))
    }
}
```

Here is a simple video showing the visible scroll indicators on my views after I switch from one view to another. My views contain UICollectionView and UITableView. 
If I scroll in those views, the scroll indicators disappear and will not come back if I switch again between views.

![ios](https://user-images.githubusercontent.com/1831740/28571664-4424bdd6-7144-11e7-8075-5cda701ac079.gif)

**Comment by danieldahan** [comment]
Hey :) Have you set the 

```swift
collectionView.showsHorizontalScrollIndicator = false
collectionView.showsVerticalScrollIndicator = false
```

properties ?

**Comment by gilthonweapps** [comment]
Hi.

If I set those properties, then I don't have the issue anymore.
However, I would like to see the scroll indicator when I scroll. So I think, there is an issue somewhere in the Motion lib :)

**Comment by danieldahan** [comment]
Not necessarily. The scroll indicators show that the content is larger than the visible space. ScrollViews allow all directions and automatically find the direction once a scroll occurs and it needs to show your content. The only other scenario for scroll is when you set the direction manually. The visibility of the indicators can go on and off when first displayed and then no longer be shown if not needed. If you can send me a reproducible sample I will be able to investigate it further :)

**Comment by gilthonweapps** [comment]
Hi,

I have made a repo with the issue: https://github.com/gilthonweapps/testMaterial

If you switch between TabBarController and MyTabBarController in the storyboard, you will see the difference when you navigate between tabs.

**Comment by danieldahan** [comment]
@gilthonweapps awesome I will take a look :)

**Comment by danieldahan** [comment]
@gilthonweapps I will be working on this tomorrow if not tonight. Sorry for any delays :)

**Comment by gilthonweapps** [comment]
Great ! :-)

Envoyé de mon iPhone

**Comment by danieldahan** [comment]
I am looking more into your issue. I can verify it happens when using Motion. That said, I am not sure that it is actually Motion. It could be a symptom of custom animations being made with Apple's Animator objects. I will keep investigating over the next couple days. A temporary workaround is to hide and show the indicators within the `viewDidAppear` and `viewWillAppear` methods.

**Comment by gilthonweapps** [comment]
I will use the temporary workaround for now. Hope that you will find a better solution :)

**Comment by OrkhanAlikhanov** [comment]
Same here, I have `TabsController` managing 2 `UIViewController`s with `tableView`. When transition happens the scroll bars appear.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov this is on the high priority list. Will look more into it today.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan I tested [the project](https://github.com/gilthonweapps/testMaterial) and I confirm that this no longer persists after Material 2.13.0 (Motion 1.3.0). [Motion 1.2.5](https://github.com/CosmicMind/Motion/tree/1.2.5) had this bug, but the next release [1.3.0](https://github.com/CosmicMind/Motion/tree/1.3.0), where you reworked `Motion` internals, fixed this issue. So the issue can be closed, thank you all!

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Thank you!
