### ISSUE TITLE
Navigation Drawer Controller using Storyboards and code

### ISSUE THREAD

**Issue by amr6655** [CosmicMind/Material#816]
Hi,

I'd be really grateful for some help with this.

I'd like to use the NavigationDrawerController and ToolbarController to show a sequence of views connected by segues, with the Toolbar displayed on each view (showing the menu, toggle and more buttons) and left/right view controllers to show.

My storyboard layout is:

AppNavigationController -> RootViewController -> NextViewController

        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let leftViewController = LeftViewController()
        let rightViewController = RightViewController()

        let rootViewController: UIViewController = storyboard.instantiateViewController(withIdentifier :"RootViewController") as! UIViewController
        let appToolbarController: AppToolbarController = AppToolbarController(rootViewController: rootViewController)
        let navigationController: AppNavigationController = NavigationController(rootViewController: appToolbarController)

        window = UIWindow(frame: UIScreen.main.bounds)
        window!.rootViewController = AppNavigationDrawerController(rootViewController: navigationController, leftViewController: leftViewController, rightViewController: rightViewController)
        window!.makeKeyAndVisible()

I have tried to base this off the example projects but doesn't seem to be working out. I was hoping to determine if this is the correct setup in AppDelegate?, as I feel as though this is the issue since I run into various UI issues such as a blank space above the toolbar in RootViewController and no Toolbar icons (as defined in `appToolbarController`) shown in `NextViewController`. AppToolbarController, RootViewController and AppNavigationDrawerController contain the same as is shown in the example projects.

Issue in RootViewController, showing a gap above toolbar:
<img width="376" alt="rootview" src="https://user-images.githubusercontent.com/30460516/28711278-fcf6908c-737e-11e7-8aae-c920fe3c73e9.png">

Issue in NextViewController not showing toolbar icons (menu, toggle, more) as defined in AppToolbarController:
<img width="372" alt="nextview" src="https://user-images.githubusercontent.com/30460516/28711279-fcf723e4-737e-11e7-9809-773a92093b14.png">

**Comment by danieldahan** [comment]
So you should only use the `NavigationController` or `ToolbarController` in a screen setup like the one you are looking for. The `NavigationController` is a subclass of `UINavigationController`. So you can use it as you would normally use any navigation controller. When setting up the navigation controller items, you will want in each view controller that you are navigating to, to access the `navigationItem` properties. If you need any further help, please reopen or create a new issue :) Or use the [Material Gitter](https://gitter.im/CosmicMind/Material) chat, where I can help you further.
