### ISSUE TITLE
TextField with Mask

### ISSUE THREAD

**Issue by marcelosantoro** [CosmicMind/Material#817]
I would like to add a pattern to a UITextField. For example, when the user starts to type, automatically format the content inside the the UITextField with the following mask:

'###.###.###-##' // Brazilian Document Format

'+99 (99) 99999-9999' // Brazilian Phone Number Format.
How can I do this with Material UITextField ?

**Comment by danieldahan** [comment]
Material subclasses the `UITextField` found normally in `UIKit`. So everything should work as expected if you use the same methods. Have you tried this?

**Comment by danieldahan** [comment]
I am linking this issue to here: https://github.com/CosmicMind/Material/issues/818. As it is a feature request for text field masking.
