### ISSUE TITLE
TextField with text masking feature

### ISSUE THREAD

**Issue by nitishrana28** [CosmicMind/Material#818]
This isn't an issue. Requesting for a new feature in ErrorTextField wherein text can be masked. I basically want to mask the phone number entered, similar to the [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit). I could use that, but since I like validation message and UI of Cosmic's ErrorTextField, I would really like it here.

**Comment by danieldahan** [comment]
Nice, I will put this in the queue of items. I like the idea of adding this to Material.

**Comment by willianpinho** [comment]
Someone finish this issue?

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
