### ISSUE TITLE
tabBarController

### ISSUE THREAD

**Issue by wlching** [CosmicMind/Material#821]
Hello, in Material v2.8.1, pagerTabbarController is change to tabController.
The tabController doesn't have scrolling function.
Would you add scrolling feature to tabController in the future?
Thanks

**Comment by wlching** [comment]
I find the changed log.
https://github.com/CosmicMind/Material/wiki/change_log

2.7.1

issue-811: Removed scrollable TabBar style, until feature is ready.

**Comment by danieldahan** [comment]
The Scrollable TabBar is available now. It will automatically detect if it needs to add the scrollable feature.

**Comment by wlching** [comment]
Sorry, I miss-used the word. The feature what I want is horizontally swiping content view and also change  the selectedIndex of tabbar in tabController.

**Comment by danieldahan** [comment]
@wlching Yes, those features are coming :) I am making a nice update with those included.

**Comment by wlching** [comment]
@danieldahan  Thank you!!!!! :)
