### ISSUE TITLE
Features that are still missing in TabsController

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#823]
![pagertabstrip](https://user-images.githubusercontent.com/8708178/28943071-2c3fa8b6-78a6-11e7-8eab-78dbcde71513.png)

- active tab always in center
- different title color for inactive tabs and other for active tabs
- show only the active tab title and adjacent tabs (other tabs are hidden, but can be shown using scrolling function)
- event when a tab become inactive and other event when a tab become active
- change active tabs by swiping content view
- swiping between tab content views so do not interfere with NavigationDrawerController integrated together with TabsController based on an offset to margins of the screen
- showing diferent buttons on toolbar when the active tab is changed
- using navigation controller as content view for a tab and expand the next view to full screen when a seque is performed

Regards,
Gogu.

**Comment by danieldahan** [comment]
Thank you, I will follow up on these feature requests. I know that generally the `TabsController` is not fully complete, but that is part of why I released it that way so I can get back notes. Thank you, these are great!

**Comment by danieldahan** [comment]
Adding to this issue: https://github.com/CosmicMind/Material/issues/683

**Comment by danieldahan** [comment]
Adding to this issue: https://github.com/CosmicMind/Material/issues/860

**Comment by danieldahan** [comment]
The features that will be worked on have been added in separate issues or released. I will make note of this checklist. This issue will be closed now :) Thank you!

**Comment by melcug** [comment]
Function to change active tabs by horizontally swiping content view is already in production or not yet?

**Comment by danieldahan** [comment]
@melcug  That is only ready as a prototype at the moment.

**Comment by markst** [comment]
Seems I can no longer override selected index state. Previously I was do so:

```swift
open override func select(at index: Int) {
    super.select(at: index)

    for (idx, tabItem) in tabBar.tabItems.enumerated() {
        tabItem.isSelected = idx == index
    }
}
```

**Comment by danieldahan** [comment]
why not use the `selectedTabItem` property?

**Comment by markst** [comment]
@danieldahan because it's not possible:
![image](https://user-images.githubusercontent.com/274318/31642791-a230ac56-b338-11e7-9cd5-94a27a2b5928.png)

However with the introduction of: https://github.com/CosmicMind/Material/issues/860#issuecomment-336740672 it seems my logic above is no longer necessary.

**Comment by danieldahan** [comment]
@markst `selectedIndex` is different than `selectedTabItem`. Either way, if #860 is working for you, then let's go with the suggestion you made there.

**Comment by seubseub** [comment]
@danieldahan Function to change active tabs by horizontally swiping content view is on developing?

**Comment by danieldahan** [comment]
@seubseub Yes, it will be out soon.

**Comment by seubseub** [comment]
@danieldahan  Thanks 👍
