### ISSUE TITLE
Error on installing Material cocoapods

### ISSUE THREAD

**Issue by lddd** [CosmicMind/Material#827]
Hello there,

i am new to iOs development. Just trying to create my first app where i would like to use your great library. 

Right now i stuck here

pod install
`Analyzing dependencies
[!] Unable to find a specification for `Material (~> 2.0)``

Podfile
```
Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firstApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firstApp  
  pod 'Material', '~> 2.0'

  target 'firstAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firstAppakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by danieldahan** [comment]
Hey :) Welcome to iOS and Material. 

This is what you Podfile:

```bash
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firstApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Card
pod 'Material', '~> 2.0'

end
```

**Comment by danieldahan** [comment]
If you have any further trouble, please reopen or create a new issue. Thank you!

**Comment by lddd** [comment]
Still the same message

```
**pod install
Analyzing dependencies
[!] Unable to find a specification for `Material (~> 2.0)`**
```

**Comment by danieldahan** [comment]
What version of CocoaPods are you using?

**Comment by lddd** [comment]
cocoapods-1.3.1

**Comment by danieldahan** [comment]
Okay, send me your project please, I want to try and install it :)

**Comment by lddd** [comment]
Its actually a complete blank Xcode project based on a swift single view application. Hold, on just trying to complete reinstall cocoapods.

**Comment by kjhatis** [comment]
I installed Successfully using this:

` # Pods for firstApp  
  pod 'Material', '~> 2.0'
`
