### ISSUE TITLE
NavigationItem cannot find navigationBar

### ISSUE THREAD

**Issue by jbaez** [CosmicMind/Material#829]
Tested in iOS 11 and Material latest version 2.8.1 (previous version of Material was 2.4.0)
The current implementation to find the navigationBar from the navigationItem is:
`return contentView.superview?.superview as? NavigationBar`
I just updated Cocoa pods libraries for an App to prepare it for iOS11 and noticed that a when I was appending/removing views to navigation item (after the view has loaded) it was not adding or removing them anymore.
Adding some breakpoints I found that navigationBar in `navigationBar?.layoutSubviews()` was returning nil (in my case navigation bar was in contentView.superview?.superview?.superview?.superView)

As a quick fix I changed it to:
```swift
public var navigationBar: NavigationBar? {
        var view = contentView.superview
        while view != nil {
            if let navigationBar = view as? NavigationBar {
                return navigationBar
            }
            view = view?.superview
        }
        return nil
    }
```
Which works fine.

**Comment by danieldahan** [comment]
Nice, thank you. I will take your code as a PR and add it to the next release :) Awesome catch.
