### ISSUE TITLE
TabsController and ToolbarController bugs

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#830]
![2017-08-09 13 20 48](https://user-images.githubusercontent.com/8708178/29117256-3b3ac832-7d06-11e7-90e4-d4086e65d8e4.gif)

As you can see, there some problems with TabBar and toolbar controller:
1. When I initialize AppPageTabBarController with selectedIndex: 1 the second view is shown when the application is loaded, but first tab is selected and not second tab as I expect.
2. Changing the orientation makes the status bar invisible; In another project, the status bar is the over toolbar and not above.

Regards,
Gogu.

**Comment by danieldahan** [comment]
Great catch :)

**Comment by danieldahan** [comment]
You can now find a fix for this in [Material 2.10.1](https://github.com/CosmicMind/Material/releases/tag/2.10.1). Thank you!
