### ISSUE TITLE
TabBar view motion transition type sugestion

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#831]
![2017-08-09 13 23 52](https://user-images.githubusercontent.com/8708178/29118125-6a84fc40-7d09-11e7-9e0c-a7e83c6c2b6e.gif)

For a natural transition from a view to another view using Tabs Controller you could add a new value for slide motion transition like 'auto' that generates following behaviour: 
- as you can see above in the animation selecting first tab will **slide to left** because **last selected tab was on the right**; 
- next, if I select a tab from the right of **last selected tab that is on the left** the corespondent view will **slide to right** (not as above in animation because slide direction is set to left).

Regards,
Gogu.

**Comment by danieldahan** [comment]
The .auto behaviour already exists: It is `motionTransitionType = .autoReverse(presenting: .slide(direction: .left))`. That said, I will need to configure it to handle the case when moving between all directions. Good suggestion :)

**Comment by danieldahan** [comment]
Hey :) This has been added to [Material 2.10.0](https://github.com/CosmicMind/Material/releases/tag/2.10.0). Thank you!
