### ISSUE TITLE
TabsController indicator line bug #2

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#832]
![untitled](https://user-images.githubusercontent.com/8708178/29119202-e352a1f0-7d0d-11e7-8311-4fcfb81e50fa.png)

As you can see above, after selecting few times between tabs and changing the orientation, the line indicator has different size other that the size of the selected tab.

Regards,
Gogu.

**Comment by danieldahan** [comment]
I will double check this, I made adjustments to fix the other issue, and this may have already been fixed in the process.

**Comment by danieldahan** [comment]
Please try [Material 2.9.1](https://github.com/CosmicMind/Material/releases/tag/2.9.1) for a fix to this issue. Thank you!
