### ISSUE TITLE
Support for Options Menu

### ISSUE THREAD

**Issue by CAP-ONE** [CosmicMind/Material#835]
I know popovers are generally reserved for iPad, but is it possible to add some sort of support for Material Popover like in the picture below : 

![image](https://user-images.githubusercontent.com/7479837/29216869-4d2c9574-7eb0-11e7-93d9-64abe78b5987.png)

It could be linked to a ToolbarController or NavigationController, and we could easily add new items to it.

**Comment by danieldahan** [comment]
No worries. I have already started prototyping this sometime ago. I will add this to the feature list and put it in queue for development.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
