### ISSUE TITLE
Ambiguous use of 'title' UINavigationItem

### ISSUE THREAD

**Issue by james-ingold** [CosmicMind/Material#836]
Hello, 

Using Xcode9 and Swift4, I have a UIViewController that has a NavigationBar on it. I'm trying to dynamically update the navigation bar item title in prepareNavigationItem()

```
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        prepareNavigationItem()
    }
```
```
    fileprivate func prepareNavigationItem() {
        navigationItem.title = "My Title"
    }
```

I'm getting an error Ambiguous use of 'title'. It looks like in Materials extension of UINavigationItem the title property name conflicts with UIKit. I'm new to Swift and iOS programming, so I'm not sure if I'm doing something wrong with the library but here's the spot in Material:

```
    /// Title text.
	public var title: String? {
		get {
			return titleLabel.text
		}
		set(value) {
			titleLabel.text = value
            navigationItem.reload()
		}
	}
```

**Comment by danieldahan** [comment]
At the current moment I am not support Xcode 9 and Swift 4. That said, send me a project reproducing the issue, and I can take a look :)

**Comment by james-ingold** [comment]
Thanks, [here's a demo project with the issue](https://github.com/james-ingold/materialambiguous).
 I spun up a new single view app project in Xcode9, added a UINavigationBar in the storyboard and changed the class to a NavigationBar (Material). Added the following code to the ViewController class
```
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        prepareNavigationItem()
    }
```
```
    fileprivate func prepareNavigationItem() {
        navigationItem.title = "title" 
    }
```

**Comment by a88zach** [comment]
For now you can use the following to set the title
`
navigationItem.titleLabel.text = "foo"
`

**Comment by danieldahan** [comment]
@a88zach Thank you :)

@james-ingold I will be preparing a branch for Swift 4 and Xcode 9 this week. At that point I will publish a solution to the issue. Thank you!

**Comment by HowardCsie** [comment]
@danieldahan Excuse me Is there any branch swift4 supported?

**Comment by danieldahan** [comment]
Hey, checkout this commit https://github.com/CosmicMind/Material/commit/6b0bd134d458a1b3250985bf920cac952b799e9a from the https://github.com/CosmicMind/Material/tree/development branch :)

**Comment by HowardCsie** [comment]
Thanks :)
