### ISSUE TITLE
PulseView not working with layer changes

### ISSUE THREAD

**Issue by chanonly123** [CosmicMind/Material#837]
@IBDesignable
class CardView: PulseView {
	
	@IBInspectable var shadowOffsetWidth: CGFloat = 0
	@IBInspectable var shadowOffsetHeight: CGFloat = 1.5
	@IBInspectable var cardCornerRadius: CGFloat = 7
    
	override func layoutSubviews() {
		let shadowColor: UIColor? = UIColor.darkGray
		let shadowOpacity: Float = 0.5
		layer.cornerRadius = cardCornerRadius
		let shadowPath = UIBezierPath(roundedRect: bounds, cornerRadius: cardCornerRadius)
		layer.masksToBounds = false
		layer.shadowColor = shadowColor?.cgColor
		layer.shadowOffset = CGSize(width: shadowOffsetWidth, height: shadowOffsetHeight);
		layer.shadowOpacity = shadowOpacity
		layer.shadowPath = shadowPath.cgPath
		for view in subviews {
			view.layer.cornerRadius = cardCornerRadius
			view.layer.masksToBounds = true
			break
		}
        pulseOpacity = 0.5
        pulseColor = .gray
        depthPreset = .depth1
        pulseAnimation = .centerWithBacking
	}
}

**Comment by adamdahan** [comment]
@chanonly123 missing a call to super in layoutSubviews.

**Comment by adamdahan** [comment]
Also your for loop is in a dangerous place. Layout subviews gets called multiple times. And because you are just breaking out of it. Your for loop has no value.

**Comment by danieldahan** [comment]
@chanonly123 I think there is a better approach to what you are trying to do. Would you please explain your goal with this code?

**Comment by chanonly123** [comment]
Thanks for reply. My goal is to use the touch pulse effect with any UIView. (here with CardView).

**Comment by danieldahan** [comment]
The CardView already inherits from the PulseView. So the pulse effect is already there. Just set the `pulseAnimation` animation property. To set the pulse effect is not the best idea as it adds two layers to each view making it an expensive addition. This is why it is isolated to its own view type. Most major components inherit or implement the pulse effect in the optimal way.

**Comment by danieldahan** [comment]
Let's move this issue to [Material GItter](https://gitter.im/CosmicMind/Material). As this is more of a conversation for there :)

**Comment by hardikamal** [comment]
@chanonly123 - Were you able to achieve this? Even I am trying something similar.
