### ISSUE TITLE
Right view controller on NavigationDrawerController 

### ISSUE THREAD

**Issue by amr6655** [CosmicMind/Material#839]
Hi,

I'm quite new to Swift/iOS development and have a query I was hoping could be answered regarding the Right view controller that can be swiped in on the navigation drawer controller. I set up the AppNavigationDrawerController in AppDelegate as shown in the examples and that's all fine. 

`appNavigationDrawerController = AppNavigationDrawerController(rootViewController: navigationController, leftViewController: leftViewController, rightViewController: rightViewController)`

I then, later in the application, need to load data into the right view controller (of that AppNavigationDrawerController). I'm assuming I would start with something like this...

`let storyboard = UIStoryboard(name: "Main", bundle: nil)`
`rightViewController = storyboard.instantiateViewController(withIdentifier : "RightViewController") as! MyViewController`
`rightViewController.myData = myNewData
`

My intention then would be to set that newly instantiated right view controller to the AppNavigationDrawerController and so my data be visible in the right view controller.

I'm just wondering what would be the best way around this?
Any help would greatly appreciated

**Comment by danieldahan** [comment]
Hey, welcome to iOS and Material. So there are basically two approaches you can take. The first approach is to create the view controller as you did, then pass that controller to the initializer for the NavigationDrawerController. The second option is to pass in the view controller to the NavigationDrawerController without initializing the data, and then in your view controller itself, you implement a function being called in the `viewWillAppear` or `viewDidAppear` function that loads your data. Both options have benefits and downfalls. It depends on how you like to organize your data being passed to your view controllers. Let me know if you need any further help, we can chat on [Material Gitter](http://gitter.im/CosmicMind/Material).
