### ISSUE TITLE
Switch Too narrow；

### ISSUE THREAD

**Issue by Ccmi** [CosmicMind/Material#841]

**Comment by danieldahan** [comment]
You will need to describe more than this please.

**Comment by Ccmi** [comment]
Set the size to medium or large,width too narrow;
![image](https://user-images.githubusercontent.com/17047142/29597856-02d92d96-878b-11e7-930c-e0391936a35e.png)

**Comment by danieldahan** [comment]
hmmm... okay, I will take a look. Thanks.

**Comment by theolof** [comment]
The width for `.small` is also smaller than intended

This is my Switch:
```
theSwitch = Switch(state: .off, style: .light, size: .small)
theCell.layout(theSwitch).right(16).top(16).bottom(16)
```
which leads to
<img width="59" alt="screen shot 2017-08-25 at 08 53 22" src="https://user-images.githubusercontent.com/14074538/29702758-e56b7f9a-8972-11e7-9de9-70a852521c49.png">
This is the Switch from https://github.com/CosmicMind/Material#switch
<img width="94" alt="screen shot 2017-08-25 at 08 53 06" src="https://user-images.githubusercontent.com/14074538/29702759-e56df680-8972-11e7-8419-4795c624f920.png">

**Comment by OrkhanAlikhanov** [comment]
As a workaround you can subclass it and return custom `intrinsicContentSize`.

**Comment by danieldahan** [comment]
I am not sure if this is an issue or just an incorrect use of the Switch control. If there is an issue here to solve, please reopen this. Thank you!

**Comment by aemgtz** [comment]
I can confirm that this is an issue. As you can see @theolof comment.
I face the same problem that the switch is too **short** for all swith size.

**Comment by danieldahan** [comment]
I see, okay I have reopened the issue and will run the sample project and see what's up. Thanks for the feedback :)

**Comment by Recouse** [comment]
Has this already fixed?

**Comment by danieldahan** [comment]
Can someone test this, who has been facing the issue: 4433996f6f89bce19b11f917182d89f4877b5077, thank you!

**Comment by Recouse** [comment]
It's better now.
<img width="559" alt="screen shot 2018-02-08 at 08 15 49" src="https://user-images.githubusercontent.com/7093328/35953844-5da5aa04-0ca8-11e8-9132-82cf48303c51.png">

**Comment by danieldahan** [comment]
Cool, so unless there is further need to adjust the sizing, I am going to close this issue and the next release will include this fix. Thank you!
