### ISSUE TITLE
BottomSheetController?

### ISSUE THREAD

**Issue by phlippieb** [CosmicMind/Material#843]
According to #628, BottomSheetController was slated for release in 2.5.0. When I search for it in this repo, I see some commits adding it, but it doesn't seem to be in the code base at the moment. Was it removed?

**Comment by danieldahan** [comment]
It was in, but I removed it as it wasn't fully completed. I needed to updated Motion and some other components before I had time to fully make this. I added this to the feature list. I will need it in an app I am working on, so it will most likely be out very soon.

**Comment by phlippieb** [comment]
Outstanding 👍

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
