### ISSUE TITLE
Textfield(On secure text entry ) Memory Leak in iPhone 6S+ 

### ISSUE THREAD

**Issue by amitrajmodi** [CosmicMind/Material#844]
Hello,
Memory is leaking when type secure text in Textfield in iPhone 6s+ after 20 characters. Please do needful.

Set Font system 18 and wR - hR font 24 in attribute inspector. 
Xcode 8.3.2
iOS version:- 10.1.1 
Thank You

**Comment by danieldahan** [comment]
Thank you, I will investigate this :)

**Comment by amitrajmodi** [comment]
[MaterialTest.zip](https://github.com/CosmicMind/Material/files/1255387/MaterialTest.zip)
pfy

**Comment by danieldahan** [comment]
Thank you! This is very helpful.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov We should confirm this as well. If it is not an issue, let's close it. Thank you!

**Comment by OrkhanAlikhanov** [comment]
I don't see any memory leak in the `MaterialTest.zip` project attached.
Tested with:
* Xcode 9.3.1
* iPhone 6s simulator
* iOS 11.3

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Great! Thank you!

@amitrajmodi if you are still facing this issue, please reopen or create a new issue. Thank you!
