### ISSUE TITLE
UIView extension causes ambiguity due to name collision.

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Material#845]
Importing a framework in swift results in importing all public extensions from that framework. Material offers [`UIView.borderWidth`](https://github.com/CosmicMind/Material/blob/2.9.4/Sources/iOS/Material%2BUIView.swift#L258) extension which causes ambiguity for the compiler when I try to use [`PopTip.borderWidth`](https://github.com/andreamazz/AMPopTip/blob/2.1.7/Source/PopTip.swift#L105). According to **[this answer](https://stackoverflow.com/a/33894767/5555803) and its comments** it is impossible to resolve. I tried subclassing and overriding the `borderWidth` assuming that compiler will recognize what I am overriding, yet again failed. As the final way out I am using `NSObject.setValue(, forKey)` method. It works but I am not sure about its behavior. 
```swift
popTip.setValue(0.5, forKey: "borderWidth")
```

**Comment by danieldahan** [comment]
Let's discuss this in [Material Gitter](http://gitter.im/CosmicMind/Material) as there isn't an issue here. There is a conflict because of two libraries.

**Comment by OrkhanAlikhanov** [comment]
Well, actually I opened an issue here so that when someone encounteres the same problem, he/she can search for and find a way out.

**Comment by danieldahan** [comment]
Yes, that is a great reason. So in that case, let's leave a fix for this. I was hoping to discuss what should be done when this situation arises? As it will probably again on another property.

**Comment by AtherSajjad** [comment]
Cannot override mutable property 'borderColor' of type 'UIColor?' with covariant type 'UIColor'
Same issues it is complaining it is trying to override borderColor in Material Framework

**Comment by OrkhanAlikhanov** [comment]
@AtherSajjad When did that happen? Let's discuss this at [CosmicMind/Material gitter](http://gitter.im/CosmicMind/Material)
