### ISSUE TITLE
TextField in SearchBar cannot become the first responder

### ISSUE THREAD

**Issue by robertying** [CosmicMind/Material#846]
I was trying to make the textField in searchBar the first responder, but it always failed.

What I have done:

- `searchBar.textField.canBecomeFirstResponder` returns true
- `searchBar.textField.becomeFirstResponder()` returns false
- look for the current first responder but returns nil
``` swift
func findFirstResponder() -> Any?
    {
        if (self.isFirstResponder) {
            return self
        }
        for subView in self.view.subviews {
            if subView.isFirstResponder {
                return subView
            }
        }
        return nil
    }
``` 

I don't know whether I was missing something or It seems to be a bug.
Any help would be appreciated.

- Xcode 9 beta 5
- iOS 10.3

**Comment by danieldahan** [comment]
When are you calling this function? Can you send me a sample with this and I will take a look?

**Comment by robertying** [comment]
@danieldahan
I use the Search Sample from [https://github.com/CosmicMind/Samples](url)
I try to add `searchBar.textField.becomeFirstResponder()` in two places.
- `prepareSearchBar()` in `AppSearchBarController.swift`
- `prepareSearchBar()` in `RootViewController.swift`

Thanks for you time ;)

**Comment by danieldahan** [comment]
Yeah, I can see it is not working. Weird, well I shall take a look :)

**Comment by danieldahan** [comment]
Hey, so you need to call `becomeFirstResponder()` when the view controller has appeared, like so: 

```swift
open override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        searchBar.textField.becomeFirstResponder()
    }
```

:) All the best!

**Comment by robertying** [comment]
That works! Thank you!  ;)
I should have investigated the view life cycles better.

**Comment by danieldahan** [comment]
No worries :) I am happy to help.
