### ISSUE TITLE
Set TextView's placeholderNormalColor failed

### ISSUE THREAD

**Issue by littlemozart** [CosmicMind/Material#849]
No matter what color I set, the placeholderNormalColor was always blue.

**Comment by danieldahan** [comment]
Can you share your code? Thank you!

**Comment by littlemozart** [comment]
@danieldahan Sorry for the late reply, here are my codes before.
//        textView.placeholderNormalColor = UIColor.lightGray
//        textView.placeholderActiveColor = UIColor.orange
But later I tried to set "placeholderLabel.textColor" and that was what I wanted. 
        textView.placeholderLabel.textColor = UIColor.lightGray
Thank you!

**Comment by danieldahan** [comment]
You are correct, there is a bug here. Also, there shouldn't be a `placeholderActiveColor` property, as TextView doesn't act as `TextField` just yet. I am going to make an update and release this within a couple hours. Thank you!

**Comment by danieldahan** [comment]
Please find a fix for this in [Material 2.10.2](https://github.com/CosmicMind/Material/releases/tag/2.10.2). Use the `textView.placeholderColor` property.

**Comment by littlemozart** [comment]
Thank you very much!
