### ISSUE TITLE
ChipIconButton within TextField

### ISSUE THREAD

**Issue by hariDasu** [CosmicMind/Material#850]
For selecting contacts, invites, etc this would be a nice feature.

<img width="410" alt="lizcr" src="https://user-images.githubusercontent.com/2300054/29979734-b2b0a556-8f14-11e7-895d-17a20efeeee2.png">

**Comment by danieldahan** [comment]
I'll expand the Chips to support this, it is a very useful feature :) Thank you!

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
