### ISSUE TITLE
isMotionEnabled is true, Set a button or other failure.

### ISSUE THREAD

**Issue by Ccmi** [CosmicMind/Material#853]

**Comment by danieldahan** [comment]
This issue is not clear. Please revise it and then reopen the issue, thank you!

**Comment by Ccmi** [comment]
isMotionEnabled is true , Set button or other alpha failure.

**Comment by Ccmi** [comment]
open

**Comment by danieldahan** [comment]
Please send over a sample project demonstrating the issue. I still don't get what you are describing. Thank you!

**Comment by Ccmi** [comment]
[Test.zip](https://github.com/CosmicMind/Material/files/1283185/Test.zip)

**Comment by Ccmi** [comment]
Hi，Have you seen the problem?

**Comment by danieldahan** [comment]
I will take a look tomorrow :)

**Comment by danieldahan** [comment]
@Ccmi I will be looking at it today. I had fallen way behind due to work, sorry about any delay.

**Comment by mohpor** [comment]
I can confirm that this is a valid issue.
if you set `isMotionEnabled` to `true`, setting views' `alpha` prior to `viewDidAppear` would have no effect, meaning, the view will have an apha value of `1.0` upon view being displayed.
It seems `MotionContext` disregards view's alpha ater finishing with it. I need to investgate it some more, but I have very little knowledge on Motion, if @danieldahan could take a look, that would take less time.

**Comment by danieldahan** [comment]
I believe I know where the issue is :)

**Comment by danieldahan** [comment]
I will be working on this issue and preparing a release for this week. Thank you!

**Comment by danieldahan** [comment]
This is a linked issue: https://github.com/CosmicMind/Motion/issues/16

**Comment by danieldahan** [comment]
Please give [Motion 1.3.0](https://github.com/CosmicMind/Motion/releases/tag/1.3.0) a try. If the issue persists, please reopen it. Thank you!
