### ISSUE TITLE
Improper bounds to View

### ISSUE THREAD

**Issue by kudosQUJO** [CosmicMind/Material#854]
![img_1535](https://user-images.githubusercontent.com/12536850/30069410-4bf1957c-9226-11e7-8c33-a7224e5d2e6d.PNG)

Why is there a white box at the bottom of the viewcontroller (just above the bottomNavBar)?

Code in AppDelegate (with unimportant info removed):

let rightVC = FMSideDrawerViewController()
let feedNav = FMNavigationController(rootViewController: FMFeedTableViewController())    
let profileNav = FMNavigationController(rootViewController: FMUserProfileViewController())
let feedDrawer = FMNavigationDrawerController(rootViewController: feedNav, leftViewController: profileNav, rightViewController: rightVC)
    
let searchNav = FMNavigationController(rootViewController: FMSearchViewController())    
let blahNav = FMNavigationController(rootViewController: BlahViewController())
    
let btmNav = FMBottomNavigationController(viewControllers: [feedDrawer, searchNav, blahNav, profileNav])
    
window!.rootViewController = btmNav

Other important info:
- Screenshot depicts FMFeedTableViewController with rightVC toggled
- FMFeedTableViewController background color is darker grey so its view is clearly chopped
- view in FMFeedTableViewController lines up perfectly (so no white box) w/o feedDrawer, so 
let btmNav =  FMBottomNavigationController(viewControllers: [feedNav....]) instead of
let btmNav =  FMBottomNavigationController(viewControllers: [feedDrawer....])

**Comment by kudosQUJO** [comment]
Also to be clear the white box is there even when the rightVC is not toggled

![img_1536](https://user-images.githubusercontent.com/12536850/30069888-7f05bd84-9227-11e7-891c-4ef1ac9856bb.PNG)

**Comment by danieldahan** [comment]
Hey, sorry for my late reply. I will need a reproducible project so I can see what is happening. Would you be able to send one? Thank you!

**Comment by danieldahan** [comment]
Hey, I haven't heard from you. If you need, please reopen this issue and I will be happy to help out. Thank you :)
