### ISSUE TITLE
Collapsable/Expandable Header Views above TabsController

### ISSUE THREAD

**Issue by kudosQUJO** [CosmicMind/Material#855]
![giphy](https://user-images.githubusercontent.com/12536850/30070780-2924365e-922a-11e7-83ca-5d706d4f2c29.gif)

How would one go about achieving something like the above where there is an expandable/collapsable header view above a TabBar? 

Would it be like BottomNavController -> NavController -> CustomStretchyHeaderController? (of type TransitionController) -> TabsController -> ContentTableViewController  

I'm having trouble replicating it with the Materials Framework. A reddit user managed to accomplish something similar with the MXSegmentedPager Framework but I really enjoy Material and would like to know how I'd go about accomplishing this.

**Comment by yasirmturk** [comment]
i think this is similar to what i seek https://github.com/CosmicMind/Samples/issues/69

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
