### ISSUE TITLE
Text field placeholder with placeholderAnimation set to none not appearing when text set to nil

### ISSUE THREAD

**Issue by Pwootage** [CosmicMind/Material#856]
With `.placeholderAnimation = .hidden`, setting `.text = nil` programmatically does not properly re-show the placeholder. It is fixed if you open then close the keyboard.

XCode 8.3, Material 2.9.4

Working:
![placeholder working](https://user-images.githubusercontent.com/503910/30088832-11982202-9266-11e7-9a25-333eae89adaf.jpg)

After setting to nil from having text (i.e. to clear):
![placeholder broken](https://user-images.githubusercontent.com/503910/30088846-2ba34474-9266-11e7-96d6-a0d367acf18f.jpg)

**Comment by danieldahan** [comment]
Thank you for sharing this, I will reproduce the issue and push a fix :)

**Comment by danieldahan** [comment]
Please find a fix for this in Material 2.10.2. Thank you for sharing the issue :)
