### ISSUE TITLE
statusBar.backgroundColor in ToolbarController is white

### ISSUE THREAD

**Issue by svachmic** [CosmicMind/Material#857]
I'm using the version **2.9.4** and by doing this setup:

```
func presentEmbedded(viewController: UIViewController, barTintColor: UIColor) {
        let toolbarController = ToolbarController(rootViewController: viewController)
        toolbarController.statusBarStyle = .lightContent
        toolbarController.statusBar.backgroundColor = barTintColor.darker()
        toolbarController.toolbar.backgroundColor = barTintColor
        self.parent?.present(toolbarController, animated: true, completion: nil)
}
```

I get this result:

<img width="282" alt="screen shot 2017-09-07 at 09 04 20" src="https://user-images.githubusercontent.com/1448888/30150457-c08b13d2-93ab-11e7-8e8a-6a096dae01ce.png">

The function [`darker()`](https://github.com/svachmic/ios-url-remote/blob/develop/URLRemote/Classes/Helpers/UIColorExtension.swift) is not the issue (tried it without it), it used to work normally around version ~ **2.5**.

Am I meant to not use ToolbarController anymore? Or is it possibly a bug?

Cheers

**Comment by danieldahan** [comment]
This was a great catch, and a fix has been made and will be released within 30 minutes. Thank you :)

**Comment by svachmic** [comment]
Works like a charm, thanks a lot!
