### ISSUE TITLE
missing buttons property 

### ISSUE THREAD

**Issue by wdcurry** [CosmicMind/Material#858]
Testing out the Photos sample, with the latest repo, seeing this. Guessing this is now supposed to refer to tabItems. A quick conversion in the prepare methods was all that is needed.. just a minor FYI. ;)

/Users/me/Downloads/Samples-master/Projects/Programmatic/Photos/Photos/PhotoCollectionViewController.swift:109:9: Value of type 'TabBar' has no member 'buttons'

**Comment by danieldahan** [comment]
The issue has been fixed and an update will be posted within 30 minutes. Thank you :)

**Comment by paraschodavadiya** [comment]
Still getting same issue.

**Comment by danieldahan** [comment]
@paraschodavadiya it should be fine, please pull the latest. Thank you!

**Comment by ismaPM** [comment]
Still getting same issue in v2.12.1

**Comment by danieldahan** [comment]
@ismaPM There isn't a `buttons` property. Maybe that is the issue. It is called `tabItems` now.

**Comment by ismaPM** [comment]
f I saw it but could update the example of tabs, ask tabItems but as I add buttons or articles @danieldahan

**Comment by atistank** [comment]
it still error with "tabBar.tabItems = buttons " please update tabbar example

**Comment by danieldahan** [comment]
@atistank great catch, please take a look at the latest [TabBar sample](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabBar) for an updated version :)
