### ISSUE TITLE
navigationBar is nil.

### ISSUE THREAD

**Issue by Ccmi** [CosmicMind/Material#861]
![image](https://user-images.githubusercontent.com/17047142/30269640-26a4795a-96af-11e7-83f5-ac77c3c5fc2a.png)
![image](https://user-images.githubusercontent.com/17047142/30269655-34157206-96af-11e7-992b-cdf5796fff5c.png)

**Comment by Ccmi** [comment]
Xcode 9 beta 6

**Comment by danieldahan** [comment]
Are you using Storyboards? If so, set the class name to NavigationBar where appropriate.

**Comment by Ccmi** [comment]
No.
![image](https://user-images.githubusercontent.com/17047142/30304441-2e19ab7c-9733-11e7-9195-1ee219e8698e.png)

**Comment by danieldahan** [comment]
Okay, I haven't updated Material for Xcode 9. So I will add this issue to that Feature Request and get back to you ASAP :)

**Comment by Ccmi** [comment]
Thank you very much!

**Comment by robertying** [comment]
@Ccmi Have you tried `navigationController?.navigationBar`?

**Comment by Ccmi** [comment]
@robertying Yes, In xcode 9 beta 6 is nil.

**Comment by danieldahan** [comment]
I am preparing Material for Xcode 9 and iOS 11. I will get back to you within a couple days. Most likely a release and update as well :)

**Comment by danieldahan** [comment]
Can you test the `development` branch please?

**Comment by danieldahan** [comment]
@Ccmi Hey, checkout this commit https://github.com/CosmicMind/Material/commit/6b0bd134d458a1b3250985bf920cac952b799e9a from the [development](https://github.com/CosmicMind/Material/tree/development) branch :)
