### ISSUE TITLE
Swift 4 Conversion

### ISSUE THREAD

**Issue by WillMays1** [CosmicMind/Material#865]
Swift 4 breaks Material please update

**Comment by danieldahan** [comment]
Try the development branch for now :) it has been updated. All the best :)

**Comment by WillMays1** [comment]
What’s the url

**Comment by WillMays1** [comment]
What’s the url?

**Comment by danieldahan** [comment]
https://github.com/CosmicMind/Material/tree/development

**Comment by WillMays1** [comment]
Error In:

class Base: UIControl {

under

func prepare() {

self.addTarget(self, action: #selector(didTap), for: .touchUpInside)

Argument of '#selector' refers to instance method 'didTap()' that is not exposed to Objective-C
Add '@objc' to expose this instance method to Objective-C

**Comment by danieldahan** [comment]
Sorry about that. That is a commit that was PRed into the repo recently. It has not been groomed yet for the framework. Use this commit: 6b0bd134d458a1b3250985bf920cac952b799e9a. All the best!
