### ISSUE TITLE
TabsController delegate func not fired

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#866]
Using 
`tabsController?.select(at: tabIndex)`
the new tab item is selected, the content view of the tab is changed, but tabBar(tabBar: TabBar, willSelect tabItem: TabItem) delegate function is not fired.

**Comment by danieldahan** [comment]
Delegation methods are only fired when the user interacts with the application. You can utilize the callback available:

```swift
open func select(at index: Int, completion: ((TabItem) -> Void)? = nil) {
```

In general, delegates should only be fires when the user interacts with a control.
