### ISSUE TITLE
Swift 4 - Extra argument in call

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Material#867]
Hi,

I just migrated to Swift 4. 

When compiling, it raises the error below:

<img width="1104" alt="screen shot 2017-09-20 at 2 19 41 pm" src="https://user-images.githubusercontent.com/11938078/30631544-c991b9aa-9e0e-11e7-83e5-a3f785bcf8ac.png">

How should I fix this?

Sided question: when is the new Material version, that is compatible with Swift 4, released?

Regards

**Comment by danieldahan** [comment]
Hey, checkout this commit 6b0bd13 from the development branch :)

I am releasing to the master branch by tomorrow :)
