### ISSUE TITLE
Statusbar Investigation

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#868]
![statusbar](https://user-images.githubusercontent.com/8708178/30634375-92dd96e8-9df7-11e7-96d6-a115cfb568d1.png)
Changing the orientation, status bar become invisible or is over the toolbar.

**Comment by danieldahan** [comment]
It should be hidden when using an iPhone. Can you share your setup code for this, device, and branch that you are using for Material?

**Comment by melcug** [comment]
I am using the latest release of Material.
The screenshots are taken in Simulator.
In first application (blue toolbar) i don't use a NavigationDrawer controller, but in second application I do.

On second application, in the output window is shown, when I change the orientation in the Simulator, the following message:

> navigationDrawerController statusBar is hidden: No

printed by

```
    func navigationDrawerController(navigationDrawerController: NavigationDrawerController, statusBar isHidden: Bool) {
        print("navigationDrawerController statusBar is hidden:", isHidden ? "Yes" : "No")
    }
```

**Comment by danieldahan** [comment]
Are you using the latest [development](https://github.com/CosmicMind/Material/tree/development) branch version? If so, can you send over a reproducible project. Also, I don't rely on simulators as they are buddy. This should be tested on a device. I await to hear from you :)

**Comment by danieldahan** [comment]
Hey! I haven't heard from you. If you still face this issue, please reopen it. Thank you!
