### ISSUE TITLE
Update from 1.37.3 to 2.10.2

### ISSUE THREAD

**Issue by SandroMachado** [CosmicMind/Material#871]
Hi,

I am experiencing some difficulties to update from version `1.37.3` to `2.10.2`, I tried to follow the changelog without luck.

I want to update the following code:

```
textField.attributedPlaceholder = NSAttributedString(string: placeholder, attributes:[NSForegroundColorAttributeName: Color.coolGrey])
textField.backgroundColor = Color.transparent
textField.bottomBorderLayerDistance = -12
textField.borderColor = Color.coolGrey
textField.detailLabel = UILabel()
textField.detailLabelAnimationDistance = 2
textField.detailLabelActiveColor = MaterialColor.red.accent3
textField.textColor = Color.gunMetal
textField.titleLabel = UILabel()
textField.titleLabelAnimationDistance = -12
textField.titleLabelActiveColor = MaterialColor.grey.darken4
textField.titleLabelColor = Color.coolGrey

guard let detailLabel = textField.detailLabel, let titleLabel = textField.titleLabel else {
    return
}

detailLabel.font = Font.getRegularFont(12)
titleLabel.font = Font.getRegularFont(12)
```

The `detailLabelAnimationDistance` is not available anymore?
The `titleLabel` change to `leftLabel`?

Can someone help converting this code to the latest version?

Some things like the color I were able to convert, like `MaterialColor` -> `Material.Color*`.

**Comment by danieldahan** [comment]
Hey :)
Are you using Xcode 9 with Swift 4, or using Xcode 8.* with Swift 3.*?

**Comment by SandroMachado** [comment]
Hi @danieldahan, Xcode 8.* with Swift 3.*.

**Comment by danieldahan** [comment]
Cool, I can take a look a little later today. I think it would be better to move this conversation to [Material Gitter](http://gitter.im/CosmicMind/Material). So please post their the issue and I will be happy to help :)

**Comment by SandroMachado** [comment]
Sure 👍
