### ISSUE TITLE
Declarations from extensions cannot be overridden yet

### ISSUE THREAD

**Issue by Coppola-Aleandro** [CosmicMind/Material#877]
in xcode9 in new project, when I build my app occurred this error: "Declarations from extensions cannot be overridden yet"

**Comment by danieldahan** [comment]
Make sure to use the `development` branch for now :) If the issue persists, please reopen it. Thank you!

**Comment by Coppola-Aleandro** [comment]
Not working with: pod 'Material', '~> 2.0' but i downloaded the Material Project and changed the core files and working!

**Comment by danieldahan** [comment]
Hmmm interesting. I am going to prepare the Swift 4 release tonight, so I will be double checking tonight.

**Comment by Coppola-Aleandro** [comment]
Good!! 👍
