### ISSUE TITLE
Getting Swift Compiler Issues (Declarations from extensions cannot be overridden yet)

### ISSUE THREAD

**Issue by spot-developers** [CosmicMind/Material#881]
Generates subsequent errors in ambiguous use of cornerRadiusPreset and shapePreset members.

Building using Swift 4.0 and Xcode 9.0 (9A235)

**Comment by mohpor** [comment]
@spot-developers 
Can you tell us more about the issue you're having?
What method of integration are you using? (Cocoapods? Source?)
What Branch are you on? Are you using `development` branch?

**Comment by spot-developers** [comment]
Ignore above - realised not using development branch for Swift 4 support.
