### ISSUE TITLE
ErrorTextField error

### ISSUE THREAD

**Issue by LuckyFA** [CosmicMind/Material#882]
I updated to Xcode 9, the Project itself is working.
If dismiss a ViewController with an ErrorTextField in it, i get this Error:

Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.

Layout.swift; Line 974

```
    private class func prepareForConstraint(_ parent: UIView, child: UIView) {
        if parent != child.superview {
            child.removeFromSuperview() //<-- Line 974
            parent.addSubview(child)
        }
        child.translatesAutoresizingMaskIntoConstraints = false
    }
```

**Comment by mohpor** [comment]
@LuckyFA 
This is not directly related to Material. Please check if you are trying to Layout the TextField directly to a `VisualEffectView`.
Thanks
