### ISSUE TITLE
Transitions using NavigationDrawerController with NavigationController

### ISSUE THREAD

**Issue by seongminnpark** [CosmicMind/Material#888]
Hello. I am trying to achieve the same behavior as the [NavigationDrawerController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController/NavigationDrawerController) sample with `NavigationController` and `NavigationDrawerController`.

The sample uses a `ToolbarController`, however, and calls the following in its `NavigationDrawerController` to transition views:
`toolbarController?.transition(to: TransitionedViewController(), completion: closeNavigationDrawer)`

The transition method was not available when using NavigationController. Would 
`navigationController?.transition(from: , to: , duration: , options: , animations: , completion: )` be the right method to use?

My app is structured the same way as the sample app. The app delegate creates a `NavigationDrawerController` as its `rootViewController`(which in turn has `NavigationController` as its `rootViewController`, which in turn has `ViewController1` as its `rootViewController`), and a `UIViewController`(To be used as a navigation drawer menu) as its `leftViewController`. 

I am having trouble transitioning from `ViewController1` to `ViewController2` when pressing a button in my `NavigationDrawerController`. I am also not sure if I should be using the same `NavigationController` for every `ViewController`s.

I would appreciate any input. I have been struggling with this basic transition for over a week :( Thank you so much for your wonderful library!

**Comment by seongminnpark** [comment]
For reference, the following is my AppDelegate that initializes the app.

`let appNavigationController = AppNavigationController(rootViewController: DiscoverViewController())
        let leftViewController = MenuViewController() // This view contains buttons with ViewController names.
        
        window = UIWindow(frame: UIScreen.main.bounds)
        window!.rootViewController = AppNavigationDrawerController(rootViewController: appNavigationController, leftViewController: leftViewController)
        window!.makeKeyAndVisible()`

**Comment by danieldahan** [comment]
@seongminnpark Hey :) 

When using the `NavigationController`, you actually want to use the `pushViewController` method. The Toolbar was custom built so it has a slightly different interface. The NavigationController is subclassed from UINavigationController, so most of its features from there. So you can do this: 

```swift
navigationController?.pushViewController(TransitionViewController(), animated: true)
```

Take a look at this line in the `NavigationController` sample project https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationController/NavigationController/ViewController.swift#L84.

If you need any further help, please reopen the issue :)
