### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by alvincrisuy** [CosmicMind/Material#889]
<img width="993" alt="screen shot 2017-10-03 at 3 05 17 pm" src="https://user-images.githubusercontent.com/7260700/31113548-6744cccc-a84c-11e7-9d81-ef7b99c16611.png">

Xcode 9
iOS 11.0

**Comment by mohpor** [comment]
@alvincrisuy 
Can you provide us with the `Swift Language Version` build setting of your target?
thanks

**Comment by slxl** [comment]
@mohpor 
since I have the same error [happened exactly at the same moment of time :)  - 13 mins ago]: 

1. For app target I have 3.2
2. For pods - post_install action which writes 3.2 to all pod targets as well

**Comment by slxl** [comment]
+ there are few others:

![2017-10-03 14 25 11](https://user-images.githubusercontent.com/3089985/31114108-b0abfbc0-a846-11e7-8a95-d530115a6f6e.png)

**Comment by mohpor** [comment]
I guess the problem is that you are using 3.2, it needs to be 4. You can specifically set 4 to be used by Material (if you don't want all your pods to use Swift 4). just add the following code at the end of your pod file:


``` ruby

 swift4pods = ['Material']
 
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     if swift4pods.include? target.name
       target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '4.0'
       end
     end
   end
 end
```

**Comment by alvincrisuy** [comment]
Thanks! that did the trick! 😄

**Comment by mohpor** [comment]
I'm glad it did.
Have a nice day
