### ISSUE TITLE
Facing Issues in Both swift3 and swift4

### ISSUE THREAD

**Issue by Shivaprabhu049** [CosmicMind/Material#892]
Lot of compile time errors after updating the podfile
![screen shot 2017-10-04 at 12 24 35 pm](https://user-images.githubusercontent.com/13536023/31163449-10778830-a900-11e7-9cd7-07ccc29e0d01.png)
![screen shot 2017-10-04 at 12 25 02 pm](https://user-images.githubusercontent.com/13536023/31163450-12b31e5c-a900-11e7-8f91-c75a23a48679.png)
![screen shot 2017-10-04 at 12 25 10 pm](https://user-images.githubusercontent.com/13536023/31163454-15a7c720-a900-11e7-8226-e11ad92d1bc0.png)
![screen shot 2017-10-04 at 12 25 13 pm](https://user-images.githubusercontent.com/13536023/31163457-17552766-a900-11e7-864d-60ae14476fff.png)

**Comment by mohpor** [comment]
@Shivaprabhu049 
Could you elaborate on the settings of the workspace you are testing with?
`2.10.3` is Swift 4 only. You need to either set your **Target**'s `Swift Language Version` to 4, or 
set the swift version for Material pod in your pod file (see #889)

**Comment by muppetkermit** [comment]
version 2.x already have swift 4.0 codes. Could you upgrade version 3.0 ( maybe 4.0 ) so conflicts would resolve.
Have a nice day.

**Comment by danieldahan** [comment]
@muppetkermit What do you mean version 3.0?

**Comment by muppetkermit** [comment]
I mean release label 2.x for before swift 4.0 and Material label 3.0 for swift 4+ support would be nice

**Comment by danieldahan** [comment]
The `v2.x.x` branch is a running branch to point to tags aside from `master`. Once Apple makes an official update, everything we maintain gets pushed to that update. I'd be happy to further help in the [Material Gitter](http://gitter.im/cosmicmind/material) channel :) As for now, I am going to close this issue and hope to hear from you there. Thank you!
