### ISSUE TITLE
NavigationController: hidesBottomBarWhenPushed with isMotionEnabled introduces bug with iOS 11

### ISSUE THREAD

**Issue by chilinh** [CosmicMind/Material#893]
I make an app with view controller structure like BottomNavigationController with 4 tabs as NavigationController. 
I want to enable isMotionEnabled in NavigationController to use Motion api when push childViewController. If I set childViewController. hidesBottomBarWhenPushed = true when push, after pop that viewController and back to the NavigationController, the BottomBar can not be interacted.
If I don't set isMotionEnabled = true, the BottomBar is interactable after pop back but I cannot use Motion api.
This bug only appears in iOS 11 and still exists in 2.10.3

**Comment by danieldahan** [comment]
Can you send me a sample project that highlights this issue?

**Comment by chilinh** [comment]
Sample project to show this issue is [here](https://github.com/chilinh/SampleNavigationController)
And I have another issue here: if BaseNavigationController doesn't extend UINavigationController but NavigationController, app will crash on iOS 10

**Comment by danieldahan** [comment]
@chilinh thank you! I will take a look at the sample.

**Comment by chilinh** [comment]
@danieldahan Do you take a look at sample project? Do you have any solution to work around with those bugs?

**Comment by danieldahan** [comment]
I will look later tonight, if not tomorrow latest. Sorry for any delays :)

**Comment by danieldahan** [comment]
Hey, sorry for any delays, @chilinh. I had fallen behind due to work. I will be looking at your issue today. Thank you!

**Comment by danieldahan** [comment]
This is confirmed as an issue and we will work on a fix. Thank you for bringing this to our attention :)

**Comment by danieldahan** [comment]
Working on this :) Hopefully a fix will be available very soon.

**Comment by phillippbertram** [comment]
Is there a workaround that I could use until this bug is fixed? :)

**Comment by danieldahan** [comment]
@phillippbertram I will take a look today and see what I can come back with.

**Comment by phillippbertram** [comment]
muchas gracias ;)

**Comment by OrkhanAlikhanov** [comment]
Same here ...

**Comment by danieldahan** [comment]
Please give [Motion 1.3.0](https://github.com/CosmicMind/Motion/releases/tag/1.3.0) a try. If the issue persists, please reopen it. Thank you!
