### ISSUE TITLE
Swift 4 (XCode 9)

### ISSUE THREAD

**Issue by ybanezmarjune** [CosmicMind/Material#894]
I got error when upgrading to XCode 9.

![screen shot 2017-10-05 at 1 11 33 pm](https://user-images.githubusercontent.com/6849087/31211829-d706b4fc-a9ce-11e7-8104-29e326f95757.png)

**Comment by mohpor** [comment]
@ybanezmarjune 
Have you seen #890?
I think your issue might be related.

**Comment by ybanezmarjune** [comment]
This will fix the error. Thank you @mohpor 
![screen shot 2017-10-05 at 1 55 06 pm](https://user-images.githubusercontent.com/6849087/31212745-d541ed48-a9d4-11e7-8b4e-2ad142925fc8.png)
