### ISSUE TITLE
UITextFiled Placeholder

### ISSUE THREAD

**Issue by WillMays1** [CosmicMind/Material#895]
I have 5 UITextFields and have information stored in them which always leaves the placeholder above the text. Is there anyway to move it down closer to the text? It seems like it is very high. I don’t know if this is a bug or what. I can post a screenshot

**Comment by danieldahan** [comment]
Hey! You can use this `placeholderVerticalOffset`, `placeholderHorizontalOffset`, and `placeholderActiveScale` in order to customize the distance and scale on both axis.
