### ISSUE TITLE
List of all components?

### ISSUE THREAD

**Issue by Zangoran** [CosmicMind/Material#896]
Is there a list of all the components that this framework adds? If so, where is it located. Does it have pictures and examples of it being used? Thanks!

**Comment by danieldahan** [comment]
There are [sample projects](https://github.com/CosmicMind/Samples) you can use. As well, we will be demonstrating many new things that can be done with Material this month as we have finished our documentation tool :)

**Comment by Zangoran** [comment]
@danieldahan Does the documentation tool include the list of each elements and their usage?

**Comment by danieldahan** [comment]
It will include that and more, but mind you, Material is a tool to make any component really, so you can always go beyond what we supply.

**Comment by Zangoran** [comment]
@danieldahan Yeah, of course. Where can one access the documentation?

**Comment by danieldahan** [comment]
It will be available on either CosmicMind.com or MaterialSwift.com. We are deciding on how we will roll this out. I am starting to put it together here https://www.cosmicmind.com/danieldahan/lesson/7.

**Comment by Zangoran** [comment]
@danieldahan Awesome! Just let me know when its live. Thanks!

**Comment by danieldahan** [comment]
@Zangoran Will do!
