### ISSUE TITLE
Any body have insight on this issue??? 

### ISSUE THREAD

**Issue by TheAsadHayat** [CosmicMind/Material#897]
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x103e0d1fc specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 120
1  Material                       0x102f4151c _TFE8MaterialCSo6UIView18transitionSnapshotfT12afterUpdatesSb10shouldHideSb_S0_ + 1872
2  Material                       0x102f42064 _TToFE8MaterialCSo6UIView18transitionSnapshotfT12afterUpdatesSb10shouldHideSb_S0_ + 112
3  Material                       0x102f48bf4 _TFC8Material6MotionP33_2E1495B4BEBA0F20E3747D441246302C25prepareTransitionSnapshotfT_T_ + 184
4  Material                       0x102f489a8 _TFFC8Material6Motion17animateTransitionFT5usingPSo36UIViewControllerContextTransitioning__T_U_FT_T_ + 80
5  Material                       0x102ec9efc _TTRXFo___XFdCb___ + 44
6  libdispatch.dylib              0x18254d088 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x18254d048 _dispatch_client_callout + 16
8  libdispatch.dylib              0x182559b74 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1016
9  CoreFoundation                 0x182b6ff20 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x182b6dafc __CFRunLoopRun + 2012
11 CoreFoundation                 0x182a8e2d8 CFRunLoopRunSpecific + 436
12 GraphicsServices               0x18491ff84 GSEventRunModal + 100
13 UIKit                          0x18c03b880 UIApplicationMain + 208
14 TimeAppUI                      0x1024f01ec main (AppDelegate.swift:20)
15 libdyld.dylib                  0x1825b256c start + 4

**Comment by danieldahan** [comment]
Can you send over a project that reproduces this issue?

**Comment by danieldahan** [comment]
Hey! I Haven't heard from you. Please reopen the issue when you have a sample project reproducing the issue. Thank you!
