### ISSUE TITLE
missing feature after update to swift 4

### ISSUE THREAD

**Issue by ahmedsafadii** [CosmicMind/Material#898]
<img width="254" alt="screen shot 2017-10-09 at 1 05 25 pm" src="https://user-images.githubusercontent.com/6974081/31333403-9f322c24-acf2-11e7-8f9d-1852e18850cc.png">

after update no border color or width or radius and so on ..

**Comment by danieldahan** [comment]
Yes, that is correct. I removed all conflicting extension properties that are bound to a layer to avoid conflicts with other libraries. To add them, you can add an extension like so to your project:

```swift
extension UIView {
    @IBDesignable
    var borderColor: UIColor {
        get {
             .....
        } 
        set(value) {
             .....
       }
    }
}
```

Personally I would have loved to keep them in. That said, too many libraries make these shorthands and it was becoming an issue. All the best!

**Comment by ahmedsafadii** [comment]
thanks i will see how it goes :)
