### ISSUE TITLE
Title of Navigation Item Not Visible

### ISSUE THREAD

**Issue by vksid** [CosmicMind/Material#899]
While using NavigationController as a class of Navigation Controller and NavigationBar as a class of Navigation Bar of Navigation Controller. Title of UINavigationItem is not available in the view hierarchy.

**Comment by danieldahan** [comment]
Since `title` caused conflicts, you can now access the `navigationItem.titleLabel.text` for setting that value :) Please reopen the issue if you need and further help. Thank you!

**Comment by vksid** [comment]
@danieldahan How can I alignment titleLabel in center of the navigation bar?

**Comment by danieldahan** [comment]
It should by default be set to center. Can you make sure you have set the `NavigationController` and `NavigationBar` in storyboard, and if this is programmatic, please share your code setup.

**Comment by vksid** [comment]
Here is the link to Xcode Sample Project : https://www.dropbox.com/s/0x0aoasun8odvv1/iOSResearch.zip?dl=0

I'm using Xcode 9, iOS 11.0.2

**Comment by vksid** [comment]
Can I set titleTextAttributes here to make titleLabel text White Color?

`class AppNavigationController: NavigationController {

    open override func prepare() {
        
        super.prepare()
        guard let v = navigationBar as? NavigationBar else {
            return
        }
        
        v.depthPreset = .none
        v.barTintColor = Color.red.accent3
    }
}`

**Comment by danieldahan** [comment]
Not in this version of Material. You will need to set the color like so: 

```swift
navigationItem.titleLabel.textColor = .white
```

We are working on theming, which will solve this issue as a global solution.

**Comment by danieldahan** [comment]
I will take a look at your sample project tonight or latest tomorrow :)

**Comment by vksid** [comment]
@danieldahan Thank you :)

**Comment by danieldahan** [comment]
Hey @vksid I will be looking at your issue today. I had fallen behind due to work. Sorry for any delays.

**Comment by vksid** [comment]
@danieldahan I think I got the reason for the issue. I have added UIBarButtonItem on the left side, and nothing on the right side which made it align right side.

**Comment by danieldahan** [comment]
Yes, that would definitely do it. If you need any further help, please reopen the issue :)
