### ISSUE TITLE
How to set a Button with Text in in Toolbar.rightViews? 

### ISSUE THREAD

**Issue by Coppola-Aleandro** [CosmicMind/Material#901]
My problem is: cut the name "Frances....."

![simulator screen shot - ipad pro 12 9-inch - 2017-10-11 at 16 08 34](https://user-images.githubusercontent.com/5457653/31445577-98b00da0-ae9e-11e7-8bc9-c5527e562676.png)

**Comment by danieldahan** [comment]
Please send over your project, I will take a look at what is going on? Also, what version of Xcode and Material are you using?

**Comment by Coppola-Aleandro** [comment]
fileprivate var userButton: Button!
userButton = Button()
        userButton.setTitleColor(.white, for: .normal)
        userButton.pulseColor = .white
        userButton.addTarget(self, action: #selector(handleUserName(button:)), for: .touchUpInside)

toolbar.rightViews      = [userButton]

xCode 9 - Swift4

**Comment by danieldahan** [comment]
Thank you, I will investigate this.

**Comment by danieldahan** [comment]
I tested this use the [ToolbarController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/ToolbarController) and all works well. I don't see anywhere where you are setting the title. Try setting the title in the initializer: 

```swift
let b = Button(title: "Testing")
```

If you experience further issues, please reopen this and send a sample project that reproduces the issue. Thank you!
