### ISSUE TITLE
Camera Freezes when going back to the captureview after dismissing a recently pushed view controller

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#910]
So I have a MainViewController that has the capture button and displays a preview of a photo if one has already been taken, clicking that button opens the captureview controller that holds the Capture implementation here, then after capturing the result photo gets populated on the main controller, then the user has the option to press next button on the top to go to a different controller, then when that controller is dismissed and clicking on the same capture button to open the capture view again the camera preview freezes.

**Comment by mohpor** [comment]
@jojonarte 
Couple of questions:
1- How is it related to Material (Which components of Material are you using)?
2- Could you provide us with a sample project that demonstrates the problem?
Thnaks

**Comment by mohpor** [comment]
In any case, there is an `AVCaptureSession` that's being stopped (a call to `stopRunning()`
All you need to do, is to call `startRunning()` on your capture session and it will unfreeze.

**Comment by jojonarte** [comment]
I'm using Capture API

**Comment by danieldahan** [comment]
The Capture API is being completely rewritten and has been removed from Material many versions ago in order to not create issues for anyone. The best approach to help you is to provide the version of Material you are using and a sample project so we can look from there. Thank you :)

**Comment by jojonarte** [comment]
I got it to work by calling the activeCamera.startSession. Thanks :)

**Comment by danieldahan** [comment]
@jojonarte great! Thank you @mohpor :)
