### ISSUE TITLE
TabBar can't set tab bar items in Objective-C

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#911]

**Comment by markst** [comment]
Property needs ` @objc` prefix:
```swift
@objc open var tabItems = [TabItem]() {
```

**Comment by markst** [comment]
Also unable to set attributes:

![image](https://user-images.githubusercontent.com/274318/31600837-9b3b7bfa-b2a3-11e7-9fa2-e3234e745fd6.png)

**Comment by danieldahan** [comment]
So it looks like now @Obj-C requires this addition for Swift 4. I pushed a version now that adds the `@objc` to the `tabItems`, [Material 2.12.1](https://github.com/CosmicMind/Material/releases/tag/2.12.1). Please verify this works for you and I will add the remaining `@objc` where necessary.

**Comment by markst** [comment]
@danieldahan cheers daniel. changes has worked.

**Comment by danieldahan** [comment]
The associated PR for this https://github.com/CosmicMind/Material/pull/914.
