### ISSUE TITLE
TabBar can't select tab bar index in Objective-C

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#912]

**Comment by danieldahan** [comment]
How are you trying to access it?

**Comment by markst** [comment]
@danieldahan 
![image](https://user-images.githubusercontent.com/274318/31641528-fd31c73c-b330-11e7-93fa-d90d3f25add3.png)

**Comment by danieldahan** [comment]
I merged in your PR. So I will close this for now and use the PR as a release note. Thank you! :)
