### ISSUE TITLE
Issue while using with Firebase

### ISSUE THREAD

**Issue by smalam119** [CosmicMind/Material#913]
I am using xcode 8.3.3 (Swift 3). Material was working fine but when I add Firebase through pod some files of extensions that Material uses shows some error. Can anyone shade some lights?

**Comment by danieldahan** [comment]
It is most likely because Material has updated to Swift 4 on you in the update. What version of Material are you using? To fix it, you will need to force a version of Material that is still Swift 3. Can you share the errors?

**Comment by danieldahan** [comment]
Hey! I haven't heard from you. If you still have any issues, please reopen this issue. Thank you!

**Comment by smalam119** [comment]
Sorry for the late response. I am using Material 2.0. I cannot upgrade to Swift 4 for some reason. Can you please give me a version name that can be used with Swift 3 (Alongside firebase)
Thank you.

**Comment by danieldahan** [comment]
@smalam119 There is nothing about Material that should be stopping you from using `firebase`. Try [Material 2.10.2](https://github.com/CosmicMind/Material/releases/tag/2.10.2). If the issue persists, please share the errors that you are getting. Thank you!

**Comment by smalam119** [comment]
@danieldahan Have used 2.10.2 but no luck. It is showing some errors in NSMutableAttributedString extension e.g. "use of undeclared type NSAttributedStringKey. It is also showing some error in TextStorage, SearchBar, NavigationItem etc classes. Mostly related with 'NSAttributedStringKey'

**Comment by danieldahan** [comment]
I am not sure what your setup is. Make sure you are using Swift 4 for Material 2.10.3+ and Swift 3 for anything below. I am not sure what Firebase is doing, so if you prepare a sample project, I can comment on Material within there.

**Comment by smalam119** [comment]
Okay let me try that and come back to you. Thanks a lot.

**Comment by danieldahan** [comment]
Anytime :)
