### ISSUE TITLE
TabsController TabBar -setColorForState should not affect lineColor in updateColors() method

### ISSUE THREAD

**Issue by argentounce** [CosmicMind/Material#916]
It should either not affect lineColor or be separated with setLineColorForState

![screen shot 2017-10-18 at 16 54 24](https://user-images.githubusercontent.com/304203/31744660-4608de9c-b425-11e7-846f-ad93f1dadce3.png)

As an example, in 2.12.1 this configuration will change lineColor to white when tab is selected. Forcing all elements to be of the same color restricts customization

**TabBar.swift:471**

**Comment by OrkhanAlikhanov** [comment]
https://github.com/CosmicMind/Material/blob/2bd5e6089c0a14140509e0cec65b5d9351711ec4/Sources/iOS/TabBar.swift#L455-L472

**Comment by danieldahan** [comment]
I fully agree. I added this issue to https://github.com/CosmicMind/Material/issues/860. Let's track the conversation there.
