### ISSUE TITLE
Using with Swift 3.2

### ISSUE THREAD

**Issue by stasivanov** [CosmicMind/Material#917]
Is it possible to use the pod version 2.10.3+ with Swift 3.2 set in Build Settings? I can build with 2.10.2. But 2.10.3, that has "Added Swift 4 support" note, doesn't build with Swift 3.2.

"Added Swift 4 support" means "Force using Swift 4"? :)

I have the same issue as here https://github.com/CosmicMind/Material/issues/773#issuecomment-308552141 (related issue to the "Added Swift 4 Support" note)

So do I understand it right? I can't use the latest pod version with Swift 3.2, so I'm forced to use pod 2.10.2 or update project settings to Swift Language 4. Correct? Or that's the issue with the pod and it should be configured to build without errors with Swift 3.2?

**Comment by danieldahan** [comment]
@stasivanov You are correct, you must use Swift 4 now. If you need help migrating, please let us know. Thank you!
