### ISSUE TITLE
Allow TabBar to be updated to different colors using the corresponding index value.

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#922]
Previously I was able to update the tab bar line colour based on selected index. 

For example:

![](https://camo.githubusercontent.com/8af09f3096001d78f07b309a942c02f876433dea/68747470733a2f2f642e70722f692f4f41687038472e676966)

Code example: https://github.com/CosmicMind/Material/issues/915#issuecomment-337094036

With the introduction of https://github.com/CosmicMind/Material/commit/03a4e9f808bb383e18450abdb6265646e3e3f240 this is no longer possible.

**Comment by danieldahan** [comment]
You can use the:

```swift
open func setLineColor(_ color: UIColor, for state: TabItemLineState)

/// example:

tabBar.setLineColor(.green, for: .selected)
```

So replace your `self.pageController?.tabBar.lineColor = UIColor.cs_Citron()` lines with that. 

:) All the best!

**Comment by markst** [comment]
@danieldahan afraid that's not the behaviour I wish to implement. Please observe the animated gif on the op. Notice how the paddle turns red when navigating to "Test & Status" this is no longer possible with the new setup.

**Comment by markst** [comment]
This actually related to the issue I created here: https://github.com/CosmicMind/Material/issues/915#issuecomment-337094036
Where by it's not longer possible to have different colour states for each tab bar index.

**Comment by danieldahan** [comment]
Not sure I understand where the difference is. You are updating a property versus using a function to update. The same code you are running is running internally now. Possibly a more interesting solution would be to allow colors to be selected based on index. Something like: 

```swift
tabBar.setLineColor(.green, forIndex: 3) 
```

thinking out loud here.

**Comment by markst** [comment]
Yeah that's exactly right - as a compromise we can setup different colours for certain index items. This can also be applied to tab bar title colours.

**Comment by danieldahan** [comment]
Cool, I like this feature :) I will make it a feature request and update it by then end of the weekend.

**Comment by markst** [comment]
glad you're on board. there's no rush

however I personally had no drama with setting up title colour & states on a view controllers tab item:
```swift
vc.tabItem.setTitleColor(UIColor.cs_Citron(), for: .highlighted)
```

I suppose now extra effort is having to be made to cater for everyones edge cases

**Comment by danieldahan** [comment]
There is always a challenge in make an easy to use component and one that has many configurations. I will be working more on this component today, which will add and review features. Thank you for the PR. It will be a great start for me today :)

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
