### ISSUE TITLE
TabsController - line drawing issue

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#925]
![2017-10-20 11 31 35](https://user-images.githubusercontent.com/8708178/31812354-67f80e62-b58b-11e7-8948-ef342c475274.gif)

As you can see above, the line of the selected tab item is drawn correctly when I select directly other tab item. 

But, when I drag the bar to left or to right, the line is splitted in two parts, one that moves together with tab items and second one that remains on previous position.

**Comment by danieldahan** [comment]
What version of Material are you using and is this happening only on the simulator?

**Comment by melcug** [comment]
I am using the last release of Material. I didn't tried yet to a real device, but the video is taken from the simulator.

**Comment by danieldahan** [comment]
Yes, you need to test on devices as simulators are known to have issues in general when doing animations. Apple recommends that all animation based testing be done on devices over simulators. I have confirmed that this works correctly on a device. If you test it on a device and the issue persists, please reopen the issue. Thank you!

**Comment by melcug** [comment]
I tested on real device where the animation runs flawless.

**Comment by danieldahan** [comment]
Sweet :) Thank you for double checking.
