### ISSUE TITLE
TabsController - centering tab item after selection (sugestion)

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#926]
It would be nice if after I select a tab item, this will be centered automatically, of course if is not the first or the last.

In this manner is easy to select neighbor tab item from left or right without scrolling the bar in order to ritch to next/previous tab item if it is hidden.

**Comment by danieldahan** [comment]
Cool, I will add this as a feature request :)

**Comment by yasirmturk** [comment]
Also there is a need of having no selected tab item on a tab bar .. i am using it as bottom bar on card view and first item always show selected

can not do `bottomBar.selectedTabItem = nil`

**Comment by danieldahan** [comment]
@OrkhanAlikhanov What do you think of this?

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!

**Comment by danieldahan** [comment]
Please find the solution for this in [Material 2.16.2](https://github.com/CosmicMind/Material/releases/tag/2.16.2). Thank you!
