### ISSUE TITLE
 No such module 'Motion'

### ISSUE THREAD

**Issue by ArunAshokan11** [CosmicMind/Material#927]
Hi,
I download the material design source files and put it into the my project. i got the error No such module 'Motion'

**Comment by danieldahan** [comment]
Hey, welcome to Material. Please take a look at the [installation guide](https://www.cosmicmind.com/danieldahan/lesson/6) for help. Basically, you need to include the `Motion` framework that is built with Material. If you need any further help, please reopen this issue. Thank you!
