### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mihailsalari** [CosmicMind/Material#929]
![screen shot 2017-10-21 at 12 44 36 pm](https://user-images.githubusercontent.com/23311250/31850597-c027ea76-b65d-11e7-8b87-298a973cfd37.png)
How to fix?

**Comment by mihailsalari** [comment]
Value of type 'TabBar' has no member 'lineColor'

**Comment by mihailsalari** [comment]
Value of type 'TabBar' has no member 'buttons'

**Comment by mihailsalari** [comment]
Why?

**Comment by danieldahan** [comment]
What version of Material are you using? 

- TabBar.buttons is now TabBar.tabItems.
- Setting the line color is done through `tabBar.setLineColor(.green, for: .selected) -> a color and state. 

Make sure that you are using Swift 4. If you need any further help, please reopen this issue and please consult the [CHANGELOG](https://github.com/CosmicMind/Material/blob/master/CHANGELOG.md).
