### ISSUE TITLE
Scrolling Techniques

### ISSUE THREAD

**Issue by reeichert** [CosmicMind/Material#93]
Do you have any plans to put some of these techniques on the lib?

https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling

**Comment by danieldahan** [comment]
Hi @reeichert Yes, we have a prototype of the NavigationBarView already.

**Comment by danieldahan** [comment]
I am closing this issue, if you have any other questions, please let me know :) Thanks!

**Comment by reeichert** [comment]
Perfect, one more question, any plans merge this prototype to Development or Master?

**Comment by danieldahan** [comment]
Most likely by the end of the week it will be in release :) Latest Monday. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by reeichert** [comment]
Hi @danieldahan, you have some progress with Scrolling Techniques? 

In my app i'm using CATransform3D with scrollview delegate to make something like [that](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsZXB3RENhR1diQlk/patterns-scrolling-techniques_flex_space_image_xhdpi_003.mp4) 
but in every place I did that, the navigation bar and flexible space had the same color. 

![Google](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsa3pFOVUya2tJX2c/patterns_scrolling_scroll5.png)

but now, I need to do exactly like in the [video](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsZXB3RENhR1diQlk/patterns-scrolling-techniques_flex_space_image_xhdpi_003.mp4) with background image.

what you can suggest to me?

**Comment by danieldahan** [comment]
I reopened this issue, as now I plan to integrate a solution to your issue. At this point, I am currently thinking of my approach.

**Comment by danieldahan** [comment]
We are going to launch a feature that supports Scroll Techniques by the end of the month, is the anticipated date. As for now, I don't have any out of box solutions for you. That said, I really like Scroll Techniques and will put something nice together.

If you have any further question, or need help, please reopen or create a new issue. Sorry at this point I can't be more help.

**Comment by reeichert** [comment]
No problem, thanks for you help
