### ISSUE TITLE
TabBar: How can I make rounded corner line

### ISSUE THREAD

**Issue by chilinh** [CosmicMind/Material#932]
As title, from Material version 2.12.2, line is fileprivate. Please remove this restriction and make it open as older version.

**Comment by chilinh** [comment]
I make a pull request to change access level for line in TabBar #934
@danieldahan please take a look and release it in future version.

**Comment by danieldahan** [comment]
It has been released, and if you like, change the corner radius for the line, something like this: 

```swift
tabBar.line.layer.cornerRadius = tabBar.line.bounds.height / 2
```

:) All the best!
