### ISSUE TITLE
navigation drawer going invisible

### ISSUE THREAD

**Issue by GolapHasan** [CosmicMind/Material#933]
![unadjustednonraw_thumb_2f0](https://user-images.githubusercontent.com/8912589/31885093-283e32fa-b811-11e7-8d85-8799639884ce.jpg)

When I drag left to right (or right to left) and immediately drag back again then it happens regularly.

**Comment by danieldahan** [comment]
What version of Material are you using? Can you send over a sample project?

**Comment by melcug** [comment]
I have the same issue in the latest release (2.12.7) and this issue is not present in 2.12.4 release of Material.

**Comment by danieldahan** [comment]
@melcug Please provide a sample so I can reproduce the issue. Thank you!

**Comment by melcug** [comment]
I prepared for you a sample project with the same source(*) code before and after pods update :

- [test2-2.12.4](https://drive.google.com/file/d/0B12slIEw9f2KajdYZ1dYZ19mZXM/view?usp=sharing) with working navigationdrawer
 - [test2-2.12.7](https://drive.google.com/file/d/0B12slIEw9f2KRVo0ZUJkME5KbHM/view?usp=sharing) with not working navigationdrawer

(*) In 2.12.7 release TabsController didn't includes anymore motionTransitionType property.

**Comment by danieldahan** [comment]
@melcug for `(*) In 2.12.7 release TabsController didn't includes anymore motionTransitionType property.` 

In the next version, you will be able to use the `motionTransitionType` property with a new rule set for overriding transitions. It was accidentally not released in the latest.

**Comment by danieldahan** [comment]
Please find this fixed in [Material 2.12.8](https://github.com/CosmicMind/Material/releases/tag/2.12.8) :)
