### ISSUE TITLE
TabsController - Child view controllers do no belong to parent

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#935]
There has been some issue during merging that has now introduced different issues with the `TabsController`.

See commit: 11430ef1c8bb5be1566aa1cf56c5bf1720bbb31c
The lines: 
```swift
tvc.beginAppearanceTransition(true, animated: true)
prepareViewController(at: tvcIndex!)
```
Are now missing. This is causing issues with the tab child view controllers not having a parent appropriately.

#919

**Comment by markst** [comment]
@danieldahan I imagine this is either due to having performed a revert PR 5541cb0fbe451a4b2342206c5c8f145fa17c1f82 or some issue during merge with development branch.

**Comment by seubseub** [comment]
I had a same issue, but add @markst code, then it work! :) Thanks

**Comment by danieldahan** [comment]
I am making the update now.

**Comment by danieldahan** [comment]
This is now in [Material 2.12.5](https://github.com/CosmicMind/Material/releases/tag/2.12.5) :)
