### ISSUE TITLE
TabBar can't line colour in Objective-C

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#937]
![image](https://user-images.githubusercontent.com/274318/31929832-17d9835a-b8e9-11e7-96f0-0781b2ad9291.png)

**Comment by danieldahan** [comment]
The access to this function was blocked in favour of your previous suggestion, tabBar.setLineColor(.green, for: .selected) I will open this back up as it is cumbersome to set the line color this way for one state.

**Comment by danieldahan** [comment]
This is now in [Material 2.12.5](https://github.com/CosmicMind/Material/releases/tag/2.12.5) :)
