### ISSUE TITLE
TabsController missing prepare in transition

### ISSUE THREAD

**Issue by Bino90** [CosmicMind/Material#939]
"prepareViewController(at: tvcIndex)" is missing in transition, this is causing issues with the tab child view controllers not having a parent appropriately. You remove the current with "s.rootViewController = tvc" but you forgot to call prepare for tvc.
 
Version 2.12.6

**Comment by Bino90** [comment]
Oh sorry - i see on dev u fix this problem :)

**Comment by danieldahan** [comment]
No worries, thank you for sharing :)
