### ISSUE TITLE
Swift 4 : Issues

### ISSUE THREAD

**Issue by girishghoda** [CosmicMind/Material#941]
Hi @danieldahan ,There ara multiple issues faced by me after upgrade to swift 4
Issue 1 :  if view have any scrollable control and its property scrolling enabled is false then this issue occur
I have attach sample demo project
[Matrial-demo.zip](https://github.com/CosmicMind/Material/files/1417250/Matrial-demo.zip)

Issue 2: In some view when press back 3 dot show or show back button with name conflict
![img_0810](https://user-images.githubusercontent.com/19307918/32038646-81b0a5f0-ba48-11e7-844b-80c992b7c7fa.PNG)

Below issue occur when press on back button(popview)
![img_0811](https://user-images.githubusercontent.com/19307918/32038720-de93cec8-ba48-11e7-9c6c-61385c1af4f6.PNG)

Any suggestion
Thank you

**Comment by danieldahan** [comment]
I will take a look. At the moment, I am working on Navigation issues, so this will be testes with those updates.

**Comment by danieldahan** [comment]
things look good in your sample, I don't see any buttons though.

<img width="477" alt="screen shot 2017-10-28 at 1 17 38 pm" src="https://user-images.githubusercontent.com/9982123/32137706-831e8e3e-bbe2-11e7-8a17-4cbfd86927f4.png">
