### ISSUE TITLE
Problem with NavigationDrawerController

### ISSUE THREAD

**Issue by Coppola-Aleandro** [CosmicMind/Material#942]
When click on toggle left menu i have a clear view.
The CODE is the same of Sample ( https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController/NavigationDrawerController )
![simulator screen shot - iphone 8 plus - 2017-10-26 at 14 04 53](https://user-images.githubusercontent.com/5457653/32052351-46ee0fce-ba58-11e7-9ef1-fdf9096730a0.png)

**Comment by Coppola-Aleandro** [comment]
#933

**Comment by danieldahan** [comment]
Let's follow this issue using #933. Thank you!
