### ISSUE TITLE
Errors after updating from 2.10.2 to 2.12.7

### ISSUE THREAD

**Issue by PetresS** [CosmicMind/Material#943]
I'm using XCode 9.0.1 and my `Swift Language Version` is set on **Swift 3.2**

after I updated the material-pod, xcode showed me following errors: 
<img width="881" alt="bildschirmfoto 2017-10-26 um 14 48 34" src="https://user-images.githubusercontent.com/15786274/32056391-d44b0780-ba64-11e7-8b1d-7b7cf2374290.png">
___

Am I doing something wrong ?
maybe wrong settings?

**Comment by danieldahan** [comment]
Yes, you need to set the `Swift Language Version` to Swift 4. If you have any further issue with this, please reopen this issue. Thank you!
