### ISSUE TITLE
Can't load underlying module

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Material#944]
My Xcode is 9.0.1 and MacOS is 10.12.6
I used cocoapods to integrate Material as follows:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Material', '~> 2.0'

After that, when I tried to import Material and Motion, I found XCode can't find Motion or Material module.
Did anybody meet the similar things?
Thanks for any help.

BTW: I also used SnapKit in my Podfile, and it can be imported successfully.

**Comment by danieldahan** [comment]
Hey! I believe your Pods project or Material target within the pod configuration needs to be set to Swift 4. Please give that a try, and let me know :)

**Comment by guoyingtao** [comment]
Thanks for your help.
I checked the target and it has already been set to Swift 4.
<img width="646" alt="1" src="https://user-images.githubusercontent.com/26723384/32057949-b6dc5aa6-ba36-11e7-8f4c-afb9361e8bc7.png">

**Comment by danieldahan** [comment]
How about the `Pods` project?

**Comment by guoyingtao** [comment]
I set "Swift Language Version" to "Swift 4.0" for my Pods project, now it works!
Thanks for your help!

**Comment by danieldahan** [comment]
Sweet :) All the best!
