### ISSUE TITLE
Can you specify supported Xcode / swift settings?

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#947]
I'm getting compile failures on iOS when using xcode 9 or 8.3.3
In both cases, I set the swift version to 3

these are the errors I get for `Material 2.12.12` on xcode 8.3.3 for a new project with just material added to the podfile.

am I missing something?

`
.../Pods/Material/Sources/iOS/Font.swift:97:59: Cannot force unwrap value of non-optional type 'CGFont'
.../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:40:39: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:50:42: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:61:42: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/Material+UIFont.swift:44:18: Type 'String' has no member 'font'
.../Pods/Swift.String:231:16: Did you mean 'count'?
.../Pods/Material/Sources/iOS/NavigationItem.swift:44:27: Cannot convert value of type 'Button' to specified type 'IconButton'
.../Pods/Material/Sources/iOS/SearchBar.swift:112:83: Type 'String' has no member 'foregroundColor'
.../Pods/Material/Sources/iOS/SearchBar.swift:122:83: Type 'String' has no member 'foregroundColor'
.../Pods/Material/Sources/iOS/TextStorage.swift:108:93: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/TextStorage.swift:129:45: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/TextStorage.swift:141:45: Use of undeclared type 'NSAttributedStringKey'
.../Pods/Material/Sources/iOS/TextStorage.swift:152:48: Use of undeclared type 'NSAttributedStringKey'
`

**Comment by ConfusedVorlon** [comment]
my old build setup (xcode 9 with material 2.6.3) still builds correctly

**Comment by danieldahan** [comment]
You need to use a Swift 4 :)

**Comment by ConfusedVorlon** [comment]
thanks - I misread other issues and thought swift 4 wasn't supported yet.
perhaps update the front page to show swift 4? (it currently shows swift 3+)

**Comment by danieldahan** [comment]
Ah yes, sorry about that. I’ll do it on the next release. Thank you!
