### ISSUE TITLE
I don NOT understand your design 

### ISSUE THREAD

**Issue by mosn** [CosmicMind/Material#948]
Sorry for the harsh title and thanks for your library. But I really do not understand why `SearchBar` should be linked to `SearchBarController` and they all link to `RootViewController` that need to be instantiated and placed in `UIWindows`! 

Everything is so coupled and tangled and I do not get why you think this was the best way to do your whole design. Maybe I do not get it but I already spent four hours on this and I do not see a point of making something so simple,  so complex.

**Comment by danieldahan** [comment]
You can use the SearchBar without the controller. Nothing stops you from doing so. As well nothing is complex, it’s a lack of knowledge that you face.

**Comment by danieldahan** [comment]
I can help you, what is your desired look?

**Comment by mosn** [comment]
Sorry @danieldahan maybe I'm just not used to seeing something like this that often 

```
AppSearchBarController(rootViewController: UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RootViewController"))
```
It would be better to explain how this can be linked to a `TableView` or a plain `UIViewController` without dependency to anything else, examples provided only demonstrate implementation with `SearchBarController`. I have a simple design without `RootViewController` and without any NavigationController.

**Comment by danieldahan** [comment]
No worries. It is actually the exact signature of the most popular UI component, UINavigationController. So what are you trying to do? I can help you. Thanks :)

**Comment by mosn** [comment]
:)
ViewController -> Segue -> TableViewController with SearchBar, If necessary I can have search bar in another controller similar to UISearchController implementation. 

Optionally I would like to use AutoLayout Constraints to position the Search Bar but that's not necessary.

**Comment by danieldahan** [comment]
*If necessary I can have search bar in another controller similar to UISearchController implementation" -> this is exactly what the `SearchBarController(rootViewController: ...)` pattern does. It organizes the SearchBar separate from your changing view controllers, which are being transitioned in the `rootViewController` space. If you want to do this with a standalone SearchBar, you can do this, and you can also use AutoLayout. 

```swift
import UIKit
import Material

class ViewController: UIViewController {
    fileprivate var searchBar: SearchBar!
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        prepareSearchBar()
    }
}

fileprivate extension ViewController {
    func prepareSearchBar() {
        searchBar = SearchBar()
        view.layout(searchBar).top().horizontally()
    }
}
```
If you need any further help, please reopen this issue. Thank you!
