### ISSUE TITLE
Please include way to constrain child object dimensions added to a Bar

### ISSUE THREAD

**Issue by robcecil** [CosmicMind/Material#950]
Usage scenario:

I want to add 5 Flatbuttons to a Bar, but constrain their width to a constant. 

Currently this is impossible.

Tried adding constraints before adding like this:

`myButton.widthAnchor.constraint(equalToConstant: 80)`

Then including it in leftViews, rightViews arrays.

etc.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
