### ISSUE TITLE
layoutSubviews for TabBar NOT being called before viewDidLayoutSubviews

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Material#951]
I have a `TabBar` as a bottom bar of `ImageCard` which is being prepared on `viewDidLoad` but as all the widths of elements are 0 i started hooking up all the methods:
`viewWillAppear`
`viewWillLayoutSubviews`
`viewDidLayoutSubviews`

but it was still 0.. on further investigation i came to know that `layoutSubviews` for the `TabBar` is being called ONLY after the `viewDidLayoutSubviews` and it is invoked by the line `tv.layoutIfNeeded()` in `Motion.prepareToView` method

**Comment by yasirmturk** [comment]
on further investigation the `container.bounds.width` is still 0 for `Card` which sets the width 0 also for the bottom bar and the bottom bar will never layout subviews due to width check here
`guard willLayout else {
            return
        }`

**Comment by danieldahan** [comment]
If you set the width of the `ImageCard`, then the width of the subcomponents will automatically adjust to size. Have you tried that?

**Comment by yasirmturk** [comment]
I have provided layout.horizontally left and right padding now how can i set the width and also actual width of the view is not available in viewdidload

**Comment by danieldahan** [comment]
@yasirmturk If you set the horizontally value, it stretches the width across, so you wouldn't provide another width value. Have you looked at the sample?

**Comment by yasirmturk** [comment]
that the issue i provided horizontally layout but still the width is 0 or default.. i am attaching screenshot from the sample project please see that the `layoutSubviews()` method is called after `viewDidLayoutSubViews()` and that actual width of `Toolbar` or `Tabbar` whatever we use is NOT available untill `viewDidAppear` method
![layout](https://user-images.githubusercontent.com/306691/32428042-992c54fe-c2e5-11e7-877b-336b1f21067c.jpg)

**Comment by danieldahan** [comment]
Okay, I will take a look, thank you!

**Comment by yasirmturk** [comment]
another best example of this issue is the Grid in Samples project which no longer works at all.. to fix it, i tried overriding the `layoutSubViews` method and forcefully call `grid.commit` then it works again

`override func layoutSubviews() {
        super.layoutSubviews()
        
        if grid.views.count > 0 {
            grid.commit()
        }
    }`

**Comment by danieldahan** [comment]
Grid works perfectly fine and is the basis of every component practically, so if it didn't work, everything would be broken. And you must call `grid.commit()` because `grid.begin()` was called earlier. 

The ImageCard works perfectly in the sample and with the latest. 

<img width="531" alt="screen shot 2017-11-08 at 10 51 28 am" src="https://user-images.githubusercontent.com/9982123/32561852-e3c15cc4-c472-11e7-8afb-9e3ed2e2fcd9.png">


You will need to provide me a sample that reproduces your issue. All the best!

**Comment by yasirmturk** [comment]
try https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/Grid it doesnt work

**Comment by danieldahan** [comment]
I don't have an issue if it does not get called then. I don't think there should be any layouts until the views need to layout. So what are you trying to accomplish?

**Comment by yasirmturk** [comment]
i mean to say the Grid project does not render any output it shows blank

**Comment by danieldahan** [comment]
Seems to work for me. Are you fully updated to the latest?

<img width="475" alt="screen shot 2017-11-08 at 11 01 03 am" src="https://user-images.githubusercontent.com/9982123/32562386-226f2d4c-c474-11e7-8125-7665261a5640.png">

**Comment by yasirmturk** [comment]
i pulled the day before yesterday, let me pull again

**Comment by danieldahan** [comment]
Please pull the latest Samples too, I updated the Grid sample now :)
