### ISSUE TITLE
TabBar no selected item option needed - [Feature Request] - Add base ScrollBar class for Toolbar and TabBar.

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Material#952]
there is a need of having no selected tab item on a tab bar .. i am using it as bottom bar on card view and first item always shown selected

can not do `bottomBar.selectedTabItem = nil`

**Comment by danieldahan** [comment]
Well let's say this is a case, what would be shown if the TabBar was on `selectedTabItem = nil`?

**Comment by yasirmturk** [comment]
nothing ..just like a regular toolbar with no item selected

**Comment by danieldahan** [comment]
You should then use a Toolbar, as that breaks the behaviour of the TabBar. Tabs are always meant to have a selected Tab. Supporting a nil state will over complicate the component at the moment. What you can do, is hide the line until a Tab is selected, but you will need to manage its view controllers if you are using the TabsController. If you want to send over a PR, I'd be happy to look it over and further consider it once the behaviour is at least usable. If you need further help with this issue, please reopen this, thank you!

**Comment by yasirmturk** [comment]
I actually needed a toolbar and thats how i am using it but the thing is that `Toolbar` is just a `NavigationBar`, its not providing the functionality of a toolbar so No, i cant use a `Toolbar` as it does not have a scroller.. and i can not set a long list of "tools" to it

**Comment by yasirmturk** [comment]
so suggesting me for having a nullable selectedtabitem was a quick fix as i thought it.. instead of re-implementing the toolbar may be :)

**Comment by danieldahan** [comment]
I think the best approach would be to create a base ScrollBar class that is extended for both the TabBar and Toolbar, allowing it to spread the scrollable functionality. I am reopening this as a feature request.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
