### ISSUE TITLE
Motion prevents Material to update via Carthage for Swift 4

### ISSUE THREAD

**Issue by AndriiNarinian** [CosmicMind/Material#953]
<img width="1070" alt="screen shot 2017-11-02 at 2 05 54 pm" src="https://user-images.githubusercontent.com/27504688/32334724-dda4cad4-bff3-11e7-92d5-85871c3a6543.png">

**Comment by danieldahan** [comment]
I tested it and all seems to be fine. Are you using `carthage update`?

<img width="836" alt="screen shot 2017-11-03 at 2 22 26 pm" src="https://user-images.githubusercontent.com/9982123/32394364-74bf06f6-c0a2-11e7-94bf-dd12d6609d05.png">

**Comment by danieldahan** [comment]
I haven't heard from you, so I will close this issue for now. Thank you!
