### ISSUE TITLE
Extend edges not working in navigationDrawerController and adds a white space above Tableview

### ISSUE THREAD

**Issue by SandeepCBL** [CosmicMind/Material#955]
I am using navigationDrawerController and its leftViewController has a tableview. Whenever I change tab , a white space appears at top of tableview.
Things I tried:
Disabled Extend edges from storyBoard.
Tried disabling through code

**Comment by danieldahan** [comment]
Can you send over a sample project to reproduce the issue?

**Comment by danieldahan** [comment]
I haven't heard from you, so for now I will close this issue. Thank you!
