### ISSUE TITLE
Layout.center(): View display in wrong position if it was init with frame = .zero

### ISSUE THREAD

**Issue by ndlinh** [CosmicMind/Material#956]
It's seem that layout not calculate size of view using layout constraint.
This code work in version `2.11.4` but not work in `2.12.13`

    fileprivate func prepareIndicator() {
        let color = UIColor(hexString: "C69C9F")
        activityIndicatorView = NVActivityIndicatorView(frame: .zero, type: .ballClipRotateMultiple, color: color, padding: 10)
        activityIndicatorView.layer.zPosition = 9999
        view.layout(activityIndicatorView)
            .height(50)
            .width(50)
            .center()
    }

In `2.12.13` I need to change to:

    fileprivate func prepareIndicator() {
        let color = UIColor(hexString: "C69C9F")
        activityIndicatorView = NVActivityIndicatorView(frame: CGRect(x: 0, y: 0, width: 50, height: 50), type: .ballClipRotateMultiple, color: color, padding: 10)
        activityIndicatorView.layer.zPosition = 9999
        view.layout(activityIndicatorView)
            .height(50)
            .width(50)
            .center()
    }

**Comment by danieldahan** [comment]
I will investigate this, thank you :)

**Comment by intoxicated** [comment]
Anyone follow up this issue? I may look into layout system to figure out what cause the problem

**Comment by danieldahan** [comment]
Is this the difference `CGRect(x: 0, y: 0, width: 50, height: 50)`?

**Comment by intoxicated** [comment]
Technically CGRect.zero and CGRect(x:0, y:0, width: 50, height:50) is not same since latter one assigned width and height. But if 

```
     view.layout(activityIndicatorView)
        .height(50)
        .width(50)
        .center()
```
works properly, there shouldn't be any difference.

**Comment by danieldahan** [comment]
Okay, so nothing in Material has changed, only a direct change in the activity indicator setup. As well, NVActivityIndicator is in another library, so the investigation should start there in that library. Has it been confirmed that the indicator from that library is correctly handling iOS 11 changes?

**Comment by danieldahan** [comment]
Please reopen this issue if you still face troubles with it. Thank you!
