### ISSUE TITLE
Capture API is missing.

### ISSUE THREAD

**Issue by shemchavez** [CosmicMind/Material#958]
Where is Capture API? Is it not included anymore?

**Comment by danieldahan** [comment]
It was removed a while ago in favour of a rewrite that will be launched in Material 3 as an optional subcomponent. Here is the new repo [Capture](https://github.com/CosmicMind/Capture), which we can work on to integrate into your application and will be part of Material 3 :)

**Comment by shemchavez** [comment]
How can we install it through Pod? Like this? - pod CosmicMind/Capture ?

**Comment by danieldahan** [comment]
Well I wouldn't say that it is stable yet with all the latest changes. So installing through Pod may not be the best idea. The current Pod name is `Flash`. I am working on this API in December for Material 3.

**Comment by shemchavez** [comment]
Thanks @danieldahan :)
