### ISSUE TITLE
navigationDrawerController?.toggleLeftView() does not work when navigationDrawer is not rootViewController

### ISSUE THREAD

**Issue by varijkapil13** [CosmicMind/Material#960]
I am building navigationDrawerController with tabsController. And in the application not all view controller require the navigation drawer, there I only assign navigation drawer to the view that requires it. It works fine when the tabsController is set as window root, but when I transition to tabsController via a navigationController push method (UINavigationController or Material) from another roortViewController, example a login screen, the `navigationDrawerController?.toggleLeftView()` code in the menu button handler does not open the navigationDrawer. However, sliding from left opens the drawer.

****AppDelegate****

<img width="913" alt="screen shot 2017-11-09 at 12 20 10" src="https://user-images.githubusercontent.com/8291077/32602946-6451ab0c-c548-11e7-947d-49357632b532.png">

****Login View Controller**** (when login is done, I want to go to the tabsController with the navigationDrawer)

<img width="1064" alt="screen shot 2017-11-09 at 12 22 05" src="https://user-images.githubusercontent.com/8291077/32603051-a5f92df0-c548-11e7-8bf9-2b5c98078386.png">

****Menu Button handler****

<img width="374" alt="screen shot 2017-11-09 at 12 23 09" src="https://user-images.githubusercontent.com/8291077/32603096-c88ca0ae-c548-11e7-9ca0-0b31638bcfd1.png">

**Comment by danieldahan** [comment]
Hey :) Is your `handleMenuButton` in a view controller that is being removed once you push your new view controllers? If that is the case, then the function handler may be out of scope causing the issue. I would need to look at your project to confirm this.

**Comment by varijkapil13** [comment]
Hey :) `handleMenuButton` is in the new view controller that is being pushed. it is in the startegyViewController that I have in the DrawerController and then in TabsController (See second screenshot). It gets fired whenever I click on the menu button, but nothing happens except the ripple effect on the button.

Unfortunately I cannot put the project on GitHub, I can email you the relevant files if you want :)

**Comment by danieldahan** [comment]
Yes, please email me the project at support@cosmicmind.com :) It would be easier. Once I am done giving you help, I delete all materials you sent.

**Comment by varijkapil13** [comment]
Thank you! Sent! :)

**Comment by danieldahan** [comment]
Great! I will take a look shortly :)

**Comment by OrkhanAlikhanov** [comment]
@danieldahan I confirm that this issue no longer persists after `Material 2.13.4`. It was fixed when you fix #1016 in https://github.com/CosmicMind/Material/commit/cf88010a46778f7fb98a29ebb6d63632cfc75f2b
