### ISSUE TITLE
breakpoint when set properties to Tabbar 

### ISSUE THREAD

**Issue by atistank** [CosmicMind/Material#962]
Hi, I'm studing about tabbar from example Tabbar, but get break point when run app, i try set properties tabItems to tabbar, it not work for me.

```
fileprivate var buttons = [TabItem]()
       let btn1 = TabItem(title: "Library", titleColor: Color.blueGrey.base)
        btn1.pulseAnimation = .none
        buttons.append(btn1)
        let btn2 = TabItem(title: "Photo", titleColor: Color.blueGrey.base)
        btn2.pulseAnimation = .none
       buttons.append(btn2)
/////
tabBar.tabItems = buttons  <= break point
```

here my file. What should I do right now ?
https://github.com/atistank/TiengAnhGiaoTiep/blob/master/tabbarErorr

**Comment by danieldahan** [comment]
Are you using the `TabsController`? If so, please take a look at the [TabsController sample](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabsController). You should be setting the tabs in the view controllers themselves. If you need, please reopen the issue for further assistance :)

**Comment by atistank** [comment]
Sorry but your example not work .I use the same code of you and It still crack, you should check again.

**Comment by danieldahan** [comment]
@atistank awesome :) All the best!
