### ISSUE TITLE
TextField constraints error

### ISSUE THREAD

**Issue by Johnny992** [CosmicMind/Material#963]
When I change focus from one text field to another I get error: "Unable to simultaneously satisfy constraints".

This is known bug?

![screen shot 2017-11-13 at 11 14 06 am](https://user-images.githubusercontent.com/3774213/32720421-c9c9075a-c863-11e7-8165-1ed258a691ba.png)

**Comment by danieldahan** [comment]
You need to check your constraints for your app, this is not a Material issue. If you would like help with your application, you can write to [Material Gitter](https://gitter.im/CosmicMind/Material) :) All the best!
