### ISSUE TITLE
Explain License Terms

### ISSUE THREAD

**Issue by dannysood** [CosmicMind/Material#964]
Can you please explain the license terms. From what I understand the license says that if I use this component my app should reproduce this license which pretty much says the app is copyrighted by CosmicMind.  What am I missing here.

**Comment by danieldahan** [comment]
The code that is delivered through our frameworks is copyrighted. Anything else you do is yours. As well, you can modify our code, but you must leave the license in there if you leave a substantial amount untouched. You cannot use our name to endorse your app. That's it :) no tricks. Enjoy!

**Comment by dannysood** [comment]
Thanks explains it. Thanks a ton :)
