### ISSUE TITLE
View: convenience init() should not call prepare() again.

### ISSUE THREAD

**Issue by cuongtv51** [CosmicMind/Material#965]
View.swift line 162 , i suggest convenience init should not call prepare() again

**Comment by OrkhanAlikhanov** [comment]
That's correct, and I think there is no need to declare `convenience init()`. It should work without.
https://github.com/CosmicMind/Material/blob/68e44743466162fe03466a1f5df635c7fb808f81/Sources/iOS/View.swift#L159-L163

**Comment by cuongtv51** [comment]
Thanks for quick response, i just try to use your framework, thanks for your great work.

**Comment by danieldahan** [comment]
It's a pleasure :)

**Comment by cuongtv51** [comment]
I have search all convenience method and checking , i found another place in Button.swift also duplicate prepare() function call.

**Comment by danieldahan** [comment]
@cuongtv51 excellent, I will update that as well and make a push now.

**Comment by danieldahan** [comment]
Please find a fix for this in [Material 2.12.16](https://github.com/CosmicMind/Material/releases/tag/2.12.16) :)
