### ISSUE TITLE
Swift 4 compiler errors

### ISSUE THREAD

**Issue by barrymcnamara** [CosmicMind/Material#966]
Getting 'declarations from extensions cannot be overridden yet' and 'ambiguous use of...' compiler errors in Card.swift - Swift 4.0

![screen shot 2017-11-14 at 21 35 42](https://user-images.githubusercontent.com/6928918/32806268-d81402d0-c983-11e7-828e-089ad777e7a5.png)
![screen shot 2017-11-14 at 21 35 52](https://user-images.githubusercontent.com/6928918/32806269-d83ec9c0-c983-11e7-94fd-af67de9c2460.png)

**Comment by danieldahan** [comment]
You need to set your Pods project to Swift 4. Give that a try, and if you need, please reopen this issue. Thank you!

**Comment by barrymcnamara** [comment]
Got it sorted! Thanks for getting back. It’s a great framework!

Sent from my iPhone

On 15 Nov 2017, at 14:43, Daniel Dahan <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to set your Pods project to Swift 4. Give that a try, and if you need, please reopen this issue. Thank you!

**Comment by danieldahan** [comment]
Awesome! Thank you :)
