### ISSUE TITLE
Can't find needed swift version of library

### ISSUE THREAD

**Issue by Maxatma** [CosmicMind/Material#967]
If I need specific swift version, should I look into tags one by one trying to find needed version of swift ( swift 3) or there is easier way?

**Comment by Maxatma** [comment]
If someone will that too, **swift 3** latest version is
    pod 'Material', '2.10.2'

**Comment by danieldahan** [comment]
That is the correct tag to use. To make it easier, I made a branch [swift-3](https://github.com/CosmicMind/Material/tree/swift-3) from that tag. 

:) Thank you!

**Comment by Maxatma** [comment]
Great, thanks for fast response! :)
