### ISSUE TITLE
TextField renders 2 placeholder labels if placeholder is set in IB

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Material#968]
If the user sets `UITextField.placeholder` in IB and also set `TextField.placeholder` in the code or in IB the dual text is rendered. A quick solution could be to set `UITextField.placeholder` to nil in override property

![_xcworkspace](https://user-images.githubusercontent.com/306691/32836093-7a291f6e-ca2a-11e7-8174-fd6c4be87c48.jpg)

**Comment by danieldahan** [comment]
If this is still an issue, please reopen it. Thank you! Sorry for the late reply.
