### ISSUE TITLE
NavigationController backButtonImage location

### ISSUE THREAD

**Issue by MattKiazyk** [CosmicMind/Material#970]
When subclassing `NavigationController` and overriding the `backButtonImage` the back image isn't fully left aligned..should it?

<img width="622" alt="screenshot 2017-11-16 16 05 05" src="https://user-images.githubusercontent.com/1119565/32918697-da2615b6-cae8-11e7-86dd-9a8a1a675e51.png">

You'll see the small space on the left before the toolbar. Can I set that so that there is no space?

I fully understand the space around the image for the pulse animation, but more talking about the left/right side of whole toolbar

```
class AppNavigationController: NavigationController {
    open override func prepare() {
        super.prepare()

        guard let v = navigationBar as? NavigationBar else {
            return
        }
        v.backgroundColor = UIColor.black
        v.tintColor = UIColor.white
        v.backButtonImage = Icon.cm.arrowBack?.tint(with: .white)
    }

```

Thanks!

**Comment by MattKiazyk** [comment]
Further read into it and looks like an iOS 11 issue with navigationBars in the way they are implemented internally:

https://forums.developer.apple.com/thread/80075
https://stackoverflow.com/questions/44677018/ios-11-uinavigationbar-bar-button-items-alignment/46660888#46660888

**Comment by yasirmturk** [comment]
try this in `prepare()`
`if let navBar = navigationBar as? NavigationBar {
            navBar.contentEdgeInsetsPreset = .none
}`

**Comment by MattKiazyk** [comment]
Unfortunately that still doesn't work @yasirmturk - still leaves a 8 pt margin on left/right sides

<img width="425" alt="screenshot 2017-11-17 08 05 07" src="https://user-images.githubusercontent.com/1119565/32951038-145a67e8-cb6e-11e7-89cc-04bae1fdfa5b.png">

**Comment by danieldahan** [comment]
@yasirmturk is correct. This is an iOS 11 issue and I have tried many times to fix it without the best results. I will give it another try, so I will this up for now. Thank you!

**Comment by intoxicated** [comment]
@danieldahan this should be with with #1038

**Comment by danieldahan** [comment]
Correct, we can close this. Thank you @intoxicated
