### ISSUE TITLE
NavigationDrawer left/right padding

### ISSUE THREAD

**Issue by Coppola-Aleandro** [CosmicMind/Material#971]
Hi! You can keep a minimum padding of the left or right view menu as attached?

Thanks!

![schermata-2017-11-17-alle-12 08 35](https://user-images.githubusercontent.com/5457653/32944914-a0ed95ea-cb91-11e7-910e-251735a23959.png)
![schermata-2017-11-17-alle-12 18 47](https://user-images.githubusercontent.com/5457653/32944915-a108ff7e-cb91-11e7-94cb-24cf860d68c8.png)

**Comment by danieldahan** [comment]
Hey! Are you asking how to do this?

**Comment by Coppola-Aleandro** [comment]
@danieldahan yes! 👍 If possible!

**Comment by danieldahan** [comment]
One way would be to add a container view and then pad it as you would like. Then add a child view controller to that container, in this case it is a NavigationDrawer. Then from there continue as you would normally. If you need any further help, please reopen this issue :)
