### ISSUE TITLE
2.12.16 can't run . swift language version is 4.0    a lot of syntax error

### ISSUE THREAD

**Issue by lhalcyon** [CosmicMind/Material#972]

**Comment by lhalcyon** [comment]
sorry , solved . just swift language wrong

**Comment by shemchavez** [comment]
What should we change? Material version to Swift 4 only or with  setting App build version also?

**Comment by danieldahan** [comment]
@shemchavez  If you are using Pods, update the Pod project, if not, then update the working App project.

**Comment by shemchavez** [comment]
Thanks @danieldahan :)
