### ISSUE TITLE
'prepare' function is overwritten by private prepare functions

### ISSUE THREAD

**Issue by Eric0625** [CosmicMind/Material#973]
When inheriting from FlatButton, it's no use to override `prepare()` to customize the title color of the button. Because when initialize the child Button with `init(title: String?, titleColor: UIColor = Color.blue.base)`, the prepare function is called first in the super.init function, then followed by `prepare(with: title, titleColor: titleColor)` which will reset titleColor to the default blue color.

And when I seek to call Button class's initializer in the init function of my custom Button class, the complier pops up the error: "Must call a designated initializer of the superclass 'FlatButton'"

![default](https://user-images.githubusercontent.com/18132007/32976050-5d21ffea-cc4a-11e7-87b7-ea0f87884e6f.PNG)

**Comment by Eric0625** [comment]
In the previous version this definition works fine, but now it's no use to define the title color in `prepare()`
![default](https://user-images.githubusercontent.com/18132007/32976086-06418168-cc4b-11e7-8f8f-b82b566b2454.PNG)

**Comment by danieldahan** [comment]
I will investigate this today and release a fix :) Thank you!

**Comment by danieldahan** [comment]
This will be in the next release and here is the commit for the fix 6612bfd0da441a2669546c69285193ab6d89a3b9. Thank you :)

**Comment by Eric0625** [comment]
Great, so fast! And you are welcome =)
