### ISSUE TITLE
Tab bar layout not working on iPhone X sim

### ISSUE THREAD

**Issue by ConfusedVorlon** [CosmicMind/Material#975]
I'm using Material 2.12.16
The tab bar is added through storyboard tab-bar controller

On iPhoneX, the tab bar seems to be getting an appropriate amount of height - but the items are squishing to the top.

iPhone 8+ (all good)

![2017-11-19 06 25 07 pm](https://user-images.githubusercontent.com/586910/32993904-0ed7ced8-cd57-11e7-82d1-b71a802f63ed.png)

iPhone X

![2017-11-19 06 25 22 pm](https://user-images.githubusercontent.com/586910/32993907-1720a2c2-cd57-11e7-9d0d-3998555f443d.png)

following suggestions online, I have checked that the root view controller (the UITabBarController) has 'Use Safe Area Layout Guides' selected.

<img width="179" alt="2017-11-19 06 28 42 pm" src="https://user-images.githubusercontent.com/586910/32993928-7beef4c4-cd57-11e7-883e-83a84dac554d.png">

any suggestions?

thank you

**Comment by ConfusedVorlon** [comment]
turns out this was not your issue - sorry!

**Comment by danieldahan** [comment]
No worries :)
