### ISSUE TITLE
Black flash when using navigationController?.pushViewController

### ISSUE THREAD

**Issue by henryhardy** [CosmicMind/Material#976]
when I call navigationController?.pushViewController() there is a black flash during the slide animation to the new view.

Has anyone else experienced this?

**Comment by danieldahan** [comment]
Can you send a sample over please?

**Comment by rblalock** [comment]
I've actually experienced the same thing.  Currently doing this:

```
class AppNavigationController: NavigationController {
	open override func viewDidLoad() {
		super.viewDidLoad()
		isMotionEnabled = true
	}

	open override func prepare() {
		super.prepare()

		guard let v = navigationBar as? NavigationBar else {
			return
		}

		v.depthPreset = .none
		v.dividerColor = Color.grey.lighten2
	}
}
```

`navigationController?.pushViewController(regDetailController, animated: true)`

**Comment by danieldahan** [comment]
Sorry the delay, I was on vacation - I am taking a look now :)

**Comment by danieldahan** [comment]
@rblalock you can remove `isMotionEnabled = true` as it is enabled by default for the NavigationController. Also, I am having trouble to reproduce the issue on the latest with the iPhone X simulator. Would you be able to send over a reproducible project?

**Comment by rblalock** [comment]
it’s only reproducible on device unfortunately

**Comment by danieldahan** [comment]
@rblalock I don't have an iPhone X. I will keep an eye out for this.

**Comment by rblalock** [comment]
Here's a video, on device, of it happening.  https://www.dropbox.com/s/tcg8xlgf89zhdfp/ScreenRecording_12-05-2017%2009%3A04.MP4?dl=0

I'm going to try to troubleshoot it tonight.

**Comment by danieldahan** [comment]
@rblalock Can you share how you are setting up your view controller stack?

**Comment by AurelTyson** [comment]
I used to have the same problem (only on device, iPhone 7+), now it's gone since the version 2.13.0 👌
