### ISSUE TITLE
Cannot change app delegate for snackbar

### ISSUE THREAD

**Issue by appintima** [CosmicMind/Material#978]
How do I manually add a snackbar within a particular viewcontroller? My hierarchy is very complex with splashscreens and multiple rootviewcontrollers for different parts of my application. I just need a snakcbar in a single viewcontroller, and not elsewhere. How can we manually add one without modifying the appdelegate file or changing the rootVC?

Also the same for things like TabsController etc, Is there no way to implement them without using the appdelegate?

**Comment by danieldahan** [comment]
To add a Snackbar to a view controller is an exercise of adding the code in the [SnackbarController](https://github.com/CosmicMind/Material/blob/master/Sources/iOS/SnackbarController.swift) file. You can extract what you need and add it to your view controller. As well, you do not need to have the SnackbarController as your rooViewController. You can wrap it around any view controller and it would only be available in the view tree. Does this make sense?

**Comment by srikanthsrnvs** [comment]
The first part of what you said makes sense, but I don't understand what you mean by 'wrapping it around any view controller'

Im sorry, I taught myself to use Xcode, and so may not understand your terminology..

**Comment by danieldahan** [comment]
@srikanthsrnvs no worries :)

So basically a SnackbarController uses a rootViewController initializer. This basically take a view controller that you have, let's say MyVC and allows you to wrap it, like so: 

```swift
let vc = SnackbarController(rootViewController: MyVC(...))

/// add vc to hierarchy 

```

Now the Snackbar will be accessible in the MyVC to do with what you like and all the functionality will be there.

**Comment by srikanthsrnvs** [comment]
So lets say I have a MyVC class, and want a snackbar to appear when the view loads, I have to initialize one manually using the wrapper that you mentioned above? What if this VC is a child of another Tab Controller, or something else? Will using this wrapper still work?

**Comment by danieldahan** [comment]
Yeah, for example: let's say you have this as a TabItem in a TabsController: 

```swift
import UIKit
import Material

class FeedTabItemViewController: SnackbarController {
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    public init() {
        super.init(rootViewController: FeedViewController())
    }
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        prepareTabItem()
        prepareSnackbar()
    }
}

fileprivate extension FeedTabItemViewController {
    func prepareTabItem() {
        tabItem.image = Icon.cm.photoLibrary?.tint(with: Color.blueGrey.base)
    }
    
    func prepareSnackbar() {
        /// prepare snackbar...
    }
}
```
Now the SnackbarController is wrapping the FeedViewController and you can do what you like. This is a more advanced technique.

**Comment by srikanthsrnvs** [comment]
I see, and if I were to follow the first option of manually adding the code from the snackbar controller file into MyVC, all I have to do is add the functions, and then call them at viewdidload or whenever else I need the snackbar to show up?

**Comment by danieldahan** [comment]
Yeah, copy the SnackbarController as your base and build from there. Sorry I can't be more help, an Education Center is being worked on aggressively to help with questions like these.

**Comment by srikanthsrnvs** [comment]
Thank you!

**Comment by danieldahan** [comment]
Awesome, if you need any further help, please feel free to ask away :) I am taking note of these questions and writing up content for them.

**Comment by appintima** [comment]
Hi, I still have issues, now with the FABMenuControlller. Again, I cannot change my appdelegate, and so instead, I have MyVC connected to the VC in my storyboard, and I have AppFABMenuController. How do I wrap MyVC with AppFABMenuController? I tried doing this in appdelegate, creating a function that wraps it, and then calling that function in the VC that segues into MyVC, but I keep running into the Unexpectedly found nil when unwrapping an optional value error.
