### ISSUE TITLE
Add "@objc" to the variables declared in extension

### ISSUE THREAD

**Issue by stasivanov** [CosmicMind/Material#980]
The problem with Xcode 9 is that it doesn't work with User Defined Runtime Attributes that are declared in extension. But it works if I add "@objc" to it.

So, in file "Material+UIView.swift", there are properties like "shadowColor" or "borderColor", that earlier were @IBInspectable. Now, with the new version, they are no longer inspectable, but PLEASE make it works with "User Defined Runtime Attributes", by adding "@objc" flag to them. 

I already checked, and it works fine, if I try to use "shadowColor" as User Defined Runtime Attribute if there is an "@objc" flag added to "shadowColor" variable declaration.

**Comment by OrkhanAlikhanov** [comment]
You can add [Material+UIView.swift](https://github.com/CosmicMind/Material/blob/c3ff93617ca5d819c008b481a6c1b522b542d133/Sources/iOS/Material%2BUIView.swift) manually to your project.

**Comment by stasivanov** [comment]
I know, of course :) But I want to be always up-to-date with the live version of this pod.

**Comment by danieldahan** [comment]
@stasivanov yes, I will add them today and make a release with some other fixes. Thank you! If you can make a PR with a working version, that would be even better to avoid any issues with me missing something.

**Comment by danieldahan** [comment]
Will be in the next release with this commit: e19cd9cb51fde2f49a9ae66546355f182e7e67af
