### ISSUE TITLE
FAB Button not floating in TableView

### ISSUE THREAD

**Issue by shemchavez** [CosmicMind/Material#981]
Is Fab Button can float in TableView? If yes can you give an example? Thanks!

**Comment by danieldahan** [comment]
Yes, it can float anywhere. In the [FABMenuController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/FABMenuController) sample you can see it on its own with an added view controller that you can add a TableView or other view components. In the [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/CardTableView) sample you can see a more robust usage of a TableView and FABMenuController. Hope this helps :)

**Comment by shemchavez** [comment]
My bad, can't set a view in layout when initializing an object in variable declaration. It causes "Material Layout Error".

For example: 

var fabButton: FabButton {
     var fb = FabButton()
     return fb
}

When you set a layout in viewDidLoad() it causes that error. My solution is you must let the variable being instanstiate inside a life cycle.
