### ISSUE TITLE
Make Icon static properties a var instead of a constant(let) 

### ISSUE THREAD

**Issue by f-gonzalez** [CosmicMind/Material#982]
Currently if I want to replace and just use my own icon for something in a subclass it is too much trouble, just changing an asset...

If you can change: 
**From  :** public static _let_ visibility = Icon.icon("ic_visibility_white")
**to** : public static **var** visibility = Icon.icon("ic_visibility_white")

Then in a TextField subclass, I could simple change Icon.visibility = UIImage(named: "myImage") and that's it.

**Comment by danieldahan** [comment]
A related feature request is this one: https://github.com/CosmicMind/Material/issues/656 and the commit to your suggestion is here https://github.com/CosmicMind/Material/commit/0223578fb7b534f9e612a11de0a6661904ea58b6. I am going to release this in the next release.
