### ISSUE TITLE
I can't find a way to make the TabBar item title to position below the image.

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#983]
I've been trying to find a way to position the title of the tabbar below the icon vertically. Is there no exposed property that does this?

**Comment by danieldahan** [comment]
You need to use a BottomNavigationController to do that. If you need any further help, please reopen this issue. Thank you!

**Comment by jojonarte** [comment]
What property in BottomNavigationController should I use.

**Comment by jojonarte** [comment]
I can't reopen.

**Comment by jojonarte** [comment]
![image](https://user-images.githubusercontent.com/11880365/33247261-ac45b864-d357-11e7-8eb5-d1b3770c8f39.png)

**Comment by jojonarte** [comment]
I couldn't find a way to make it look as the guidelines
https://material.io/guidelines/components/bottom-navigation.html#

**Comment by danieldahan** [comment]
Use the [BottomNavigationController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/BottomNavigationController) as a base and here is some sample code that achieves what you are looking for: 

```swift
import UIKit
import Material

class PhotoViewController: UIViewController {
    convenience init() {
        self.init(nibName: nil, bundle: nil)
        prepareTabBarItem()
    }
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = Color.red.base
    }
}

extension PhotoViewController {
    fileprivate func prepareTabBarItem() {
        tabBarItem.image = Icon.cm.photoCamera?.tint(with: Color.blueGrey.base)
        tabBarItem.selectedImage = Icon.cm.photoCamera?.tint(with: Color.blue.base)
        tabBarItem.title = "Photos"
    }
}
```

<img width="441" alt="screen shot 2017-12-04 at 3 29 33 pm" src="https://user-images.githubusercontent.com/9982123/33574684-f7059102-d907-11e7-9cc7-1f6b4d3ff272.png">

**Comment by jojonarte** [comment]
Still the same on an iPad though.

**Comment by danieldahan** [comment]
I need to see an image or get a sample project to investigate. Please send one my way :) Thank you!
