### ISSUE TITLE
Unable to extend Layout class

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Material#986]
I am trying to add methods to allow safe area anchors but parent, child and some other methods are inaccessible
![cbmaterialextentions_swift_ _edited](https://user-images.githubusercontent.com/306691/33264914-41bcdccc-d391-11e7-9874-dcc158d4d42c.jpg)

currently i am forced to make & use class method
`Layout.topSafe(parent: view, child: card, top: 64)`

**Comment by danieldahan** [comment]
How about you make some adjustments and then PR it?

**Comment by danieldahan** [comment]
I am closing this issue for now.
