### ISSUE TITLE
Color: Mapping from codes (e.g. a400) to names (e.g. accent1)

### ISSUE THREAD

**Issue by phlippieb** [CosmicMind/Material#987]
It seems like material colors are usually named according to a code-based naming scheme (e.g. blue 500, orange a400). The material color library uses a different naming scheme (e.g. blue.base, orange.accent1). The alternative naming scheme is presumably chosen because `blue.500` would be invalid syntax, and that's fine. But: how do these schemes map to one another? Is this documented somewhere that I missed?

**Comment by danieldahan** [comment]
Hey! Take a look at this site, materialcolor.com. It shows you the colors mapped with code, hex, and the swift label. If you need further help, please let me know. Thank you!

**Comment by phlippieb** [comment]
Hi @danieldahan! Thanks for the response. I have seen that site, and (unless I'm being an idiot) I don't see the swift labels there. I mean, there are colors (e.g. "Red"), but no "darken1", "lighten4", "accent3"-style text. I can see in the page's html that those values are used as tag classes etc, but I don't see it surfaced as human-readable text at all.

**Comment by phlippieb** [comment]
![screen shot 2017-11-30 at 10 01 55 am](https://user-images.githubusercontent.com/2232699/33419989-8618fc72-d5b5-11e7-9843-1053b93676e4.png)
@danieldahan This is what the site looks like to me in chrome. There is no more content to the left or right.
