### ISSUE TITLE
Feature request for Collapsible Toolbar

### ISSUE THREAD

**Issue by jombie** [CosmicMind/Material#989]
Can we have a collapsible toolbar feature as in [Android](https://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html?utm_campaign=io15&utm_source=dac&utm_medium=blog)

**Comment by danieldahan** [comment]
I will put this in the queue and aim to launch it with Material 3.

**Comment by danieldahan** [comment]
We are documenting the feature requests and closing them as issues. Thank you!
