### ISSUE TITLE
use only the SearchBar (not SearchBarController)

### ISSUE THREAD

**Issue by CavalcanteLeo** [CosmicMind/Material#991]
As my app is in objective-c, I can't inherit SearchBar as my viewController, is there a way to use only the serachBar as UIView, not as showing as this example: https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/Search/Search/AppSearchBarController.swift#L34,

And even more, the result also had to be in a collectionView in my app.

So, just to use the searchBar as UIView will work for now.

Any help?

**Comment by danieldahan** [comment]
Yes, you can use the `SearchBar` component. If you need to see any functional references using it, take a look at the `SearchBarController` internals and the [Search](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/Search) and [SearchBarController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/SearchBarController) samples :)
