### ISSUE TITLE
Visibility Button & Clear Button can't be shown in TextField at the same time !!

### ISSUE THREAD

**Issue by lhalcyon** [CosmicMind/Material#992]
as said above,i  ran the demo of textfield and set 2 buttons to textfield , but they can't be visible at the same time. it'is bug  or cuz i make the wrong configuration. 🔢

**Comment by danieldahan** [comment]
Okay, I will take a look :) May you share with me a visual of what you want to accomplish?

**Comment by lhalcyon** [comment]
![4be42dd9-2bb8-4815-906c-e99eba408464](https://user-images.githubusercontent.com/21357951/33657540-9e6a6e4c-dab4-11e7-9d26-779f64291f9f.png)     just like this.  @danieldahan

**Comment by danieldahan** [comment]
@lhalcyon thank you!

**Comment by danieldahan** [comment]
@OrkhanAlikhanov What do you think of this issue?

**Comment by OrkhanAlikhanov** [comment]
Sounds easy to me. Will look into today.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan Material [2.16.1](https://github.com/CosmicMind/Material/tree/2.16.1) has the requested feature added. The issue can be closed.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov awesome! I will close this issue. Thank you!
