### ISSUE TITLE
Weird Issue: FabMenuItem icon not centered

### ISSUE THREAD

**Issue by jojonarte** [CosmicMind/Material#993]
I have setup the FabMenu like this:
```
fileprivate func setupInputAddressFabMenuItem() {
        self.fabEnterAddress = FABMenuItem()
        self.fabEnterAddress.fabButton.title = "Enter Address"
        self.fabEnterAddress.fabButton.image = CustomIcons.locationSearch
        self.fabEnterAddress.fabButton.tintColor = .white
        self.fabEnterAddress.fabButton.pulseColor = .white
        self.fabEnterAddress.fabButton.backgroundColor = Color.blue.base
        self.fabEnterAddress.fabButton.imageView?.contentMode = .scaleAspectFill
        self.fabEnterAddress.fabButton.addTarget(self, action: #selector(handleEnterAddressFabClick(button:)), for: .touchUpInside)
    }
```
![screen shot 2017-12-07 at 6 26 56 pm](https://user-images.githubusercontent.com/11880365/33710662-40c0bd82-db7c-11e7-928b-b70762d264b2.png)

**Comment by danieldahan** [comment]
can you remove this: `self.fabEnterAddress.fabButton.imageView?.contentMode = .scaleAspectFill` ?

**Comment by jojonarte** [comment]
I've removed it and it's still the same, I actually added that thinking it would fix it btw.

**Comment by jojonarte** [comment]
I've fixed it, I've made a mistake.
Instead of 
`self.fabEnterAddress.fabButton.title = "Enter Address"`
I replaced it with 
`self.fabEnterAddress.title = "Enter Address"`
