### ISSUE TITLE
Build issues using Material with Swift 4.

### ISSUE THREAD

**Issue by dakamojo** [CosmicMind/Material#997]
I just realized I can't reopen another person's issue.  So creating my own related to issue #900.

I have the same build errors.  I am building the sample project CardTableView.  Below is my podfile.  I have already updated Graph to use the development branch because I understand that is needed for Swift 4.  The build settings in both my Pods project and my CardTableView project are set to Swift 4.

```

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CardTableView' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for CardTableView
pod 'Material', '~> 2.0'
#pod 'Graph', '~> 2.0'
pod 'Graph', :git => 'https://github.com/CosmicMind/Graph.git', :branch => 'development'



end


```

**Comment by samantharachelb** [comment]
Hi, I'm assuming your issue is partially related to #998. You just need to make a change to your Podfile.

Change `pod 'Material', '~> 2.0'` to `'pod 'Material', '~> 2.2'`, reinstall your pods and your project should successfully build

**Comment by dakamojo** [comment]
That resolved it.  Closing issue.
