### ISSUE TITLE
Builed Failed in swift 4, Xcode 9.2 IOS 11.2

### ISSUE THREAD

**Issue by kjhatis** [CosmicMind/Material#998]
Please check the attached snapshots:
![screen shot 2017-12-14 at 2 43 47 pm](https://user-images.githubusercontent.com/24405562/33984930-28a7cf8e-e0df-11e7-9f23-f61b7627adee.png)
![screen shot 2017-12-14 at 2 56 19 pm](https://user-images.githubusercontent.com/24405562/33984934-2b12b978-e0df-11e7-8d9a-89ca5dddb8f9.png)

**Comment by samantharachelb** [comment]
Replacing `pod 'Material', '~> 2.0'` with `pod 'Material', '~> 2.2'`, and reinstalling your pods should fix the error

**Comment by kjhatis** [comment]
Tried The solution above. It fixed many errors but now i am getting 

> Type 'T' does not conform to protocol 'ZeroableAndSubtractable'

![screen shot 2017-12-15 at 10 03 43 am](https://user-images.githubusercontent.com/24405562/34026939-87366c86-e17f-11e7-946e-44695405dae4.png)

**Comment by samantharachelb** [comment]
The pod "MaterialMotion" is written by a different [author](https://github.com/material-motion/material-motion-swift), and doesn't support Swift 4. I suggest contacting those authors for help or find a different pod that does what you need.

**Comment by danieldahan** [comment]
@samantharachelb Yes, that is correct. I am closing this issue as an update to Swift 4 is what is needed. Thank you!
