### ISSUE TITLE
How to integrate AppDrawer and SnackBarController?

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Material#999]
Hi,

My app is an `AppDrawer`:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let rootNavigationController = storyboard.instantiateViewController(withIdentifier: "RootNavigationController")
        
        let menu = storyboard.instantiateViewController(withIdentifier: "Menu")
        
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = AppDrawer(rootViewController: rootNavigationController, leftViewController: menu, rightViewController: nil)
        window!.makeKeyAndVisible()
        
        return true
    }
```

What should I do to use `SnackBar`? I have read examples in `Samples-master`, which only suggest to have `SnackBarController` separately. How to have it integrate with another `ViewController`, such as `AppDrawer` in my project?

Thanks,

**Comment by Dmurph24** [comment]
+1

**Comment by danieldahan** [comment]
This is a great question. In Material 3, which releases next month, we address this issue more simply, with a better API. For now, you would need to wrap the controllers around each other, like so:

```swift
let snackbarController = SnackbarController(rootViewController: rootNavigationController)
window!.rootViewController = AppDrawer(rootViewController: snackbarController, leftViewController: menu)
```

You can access the SnackbarController using the optional `snackbarController` property found in all UIViewControllers. 

If you need any further help, please reopen this issue. Thank you!
